### ISSUE TITLE
@typeInfo only works for empty structs 

### ISSUE THREAD

**Issue by lovely-error** [ziglang/zig#16289] opened 2023-07-01 19:07 UTC
### Zig Version

0.11.0-dev.2194+626a75bbc

### Steps to Reproduce and Observed Behavior

Hey, check out the following:
```zig 
const std = @import("std");

const Ty = struct {
    // u1 // guess what happens when this gets uncommented OwO
};

pub fn main() !void {

    const tys = [_]type{
        Ty
    };
    inline for (tys) |item| {
        const ty = @typeInfo(item);
        std.debug.print("{}", .{ty});
    }
}
```
It works, don't worry, but as soon as I uncomment that u1 the compiler starts to behave rather strangely...

```
PS C:\Users\balco\Code\minos-rt> zig run src/main.zig
C:\Users\balco\Code\zig-windows-x86_64-0.11.0-dev.2194+626a75bbc\lib\std\fmt.zig:662:22: error: values of type '[]const builtin.Type.StructField' must be comptime-known, but index value is runtime-known
                for (value, 0..) |elem, i| {
                     ^~~~~
C:\Users\balco\Code\zig-windows-x86_64-0.11.0-dev.2194+626a75bbc\lib\std\builtin.zig:294:15: note: struct requires comptime because of this field
        type: type,
              ^~~~
C:\Users\balco\Code\zig-windows-x86_64-0.11.0-dev.2194+626a75bbc\lib\std\builtin.zig:294:15: note: types are not available at runtime
        type: type,
              ^~~~
C:\Users\balco\Code\zig-windows-x86_64-0.11.0-dev.2194+626a75bbc\lib\std\builtin.zig:297:20: note: struct requires comptime because of this field
        alignment: comptime_int,
                   ^~~~~~~~~~~~
referenced by:
    formatType__anon_7813: C:\Users\balco\Code\zig-windows-x86_64-0.11.0-dev.2194+626a75bbc\lib\std\fmt.zig:596:21
    formatType__anon_6577: C:\Users\balco\Code\zig-windows-x86_64-0.11.0-dev.2194+626a75bbc\lib\std\fmt.zig:557:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

PS C:\Users\balco\Code\minos-rt>

```
This is what it throws at me. You can witness it on godbolt https://godbolt.org/z/4sbs9dfEo

### Expected Behavior

Shouldn't this work?

**Comment by ianprime0509** [comment] 2023-07-01 20:08
The error here is actually not due to `@typeInfo`, but rather `std.debug.print`, since the implementation of the latter is trying to perform an operation at runtime (`for` loop over slice elements) on a comptime-only type (`Type`).

One workaround for this is to use [`std.fmt.comptimePrint`](https://ziglang.org/documentation/master/std/#A;std:fmt.comptimePrint) (which works completely at comptime and hence has no issues with comptime-only types) and use the result of that:
```zig
std.debug.print("{s}", .{std.fmt.comptimePrint("{}", .{ty})});
```

**Comment by lovely-error** [comment] 2023-07-02 11:07
Thank you for providing a workaround, but it seems somewhat off that this works...
```zig 
...
const Ty = struct {};
...
``` 
...but this doesn't in the original snippet
```zig 
...
const Ty = struct { u1 };
...
```
🤔

**Comment by Vexu** [comment] 2023-07-02 11:22
Duplicate of #12431

**Closed by Vexu** 2023-07-02 11:22 UTC
Labels: bug
