### ISSUE TITLE
Index outside slice in comptime ( using types and structs )

### ISSUE THREAD

**Issue by SrMordred** [ziglang/zig#3807] opened 2019-11-29 23:33 UTC
```
comptime {
        const array: [1]type = .{ i32 };
        switch( array.len )
        {
            1 =>{ const r = struct{ field: array[0] }; },
            2 =>{ 
                  const r = struct{ field: array[1] }; //error: index 1 outside array of size 1
                },

            else => {}
        }
}
```
workaround:
```
comptime {
        const array: [1]type = .{ i32 };
        switch( array.len )
        {
            1 =>{ const r = struct{ field: array[0] }; },
            2 =>{ 
                  const _type = array[1];
                  const r = struct{ field: _type }; 
                },
            else => {}
        }
}
```

**Comment by andrewrk** [comment] 2019-12-03 16:11
Can you clarify this issue, with a real test case? What is the expected behavior, what is the actual behavior? What command to run it.

**Comment by SrMordred** [comment] 2019-12-03 16:43
Just the code above inside a main fn. 
```
const array: [1]type = .{ i32 };
switch( array.len ) {
```
Since `array.len` is comptime known, I expect that this switch only evaluate the right path `1`
but

```
2 =>{
   const r = struct{ field: array[1] }; //error: index 1 outside array of size 1 
} 
```
The compiler evaluate this branch, and indicate me that the index 1 is out of bounds.

But this issue seem to appear only because i´m trying to use array[1] inside a struct declaration. 
if I do this way:
```
2 =>{ 
   const _type = array[1];
   const r = struct{ field: _type }; 
}
```
the array[1] bounds are not checked, as expected.

**Comment by Vexu** [comment] 2022-12-28 13:33
Duplicate of #3778

**Closed by Vexu** 2022-12-28 13:33 UTC
Labels: bug, stage1
