### ISSUE TITLE
Broken LLVM module where there should be a compiler error

### ISSUE THREAD

**Issue by mattnite** [ziglang/zig#6873] opened 2020-10-30 04:06 UTC
Due to #6720 which adds a null sentinel value to args iterators I understandably got a compilation failure for some of my code, however I got a broken LLVM module instead of an error message along the lines of `expected [:0]const u8 not []const u8`:

```
Code Generation [2192/2764] std.fmt.formatText... broken LLVM module found: Call parameter type does not match function signature!
  %6 = getelementptr inbounds { %"?[]const u8", i16 }, { %"?[]const u8", i16 }* %0, i32 0, i32 0, !dbg !6406
 %"?[:0]const u8"*  call fastcc void @std.process.ArgIterator.nextPosix(%"?[]const u8"* sret %6, %std.process.ArgIterator* %4), !dbg !6406
```

**Comment by LemonBoy** [comment] 2020-10-30 09:11
Duplicate of 6147

**Closed** 2020-10-30 10:03 UTC
