### ISSUE TITLE
provide robust command line argument parser in the std lib

### ISSUE THREAD

**Issue by catastrop** [ziglang/zig#2961] opened 2019-07-28 11:02 UTC
robust and configurable

**Comment by daurnimator** [comment] 2019-07-28 11:11
Duplicate of #923

**Comment by zimmi** [comment] 2019-07-28 11:33
@andrewrk 
Can you block this account for ziglang? They create lots of low effort issues in high profile projects, just take a look at their "contributions" page. See also [here](https://github.com/angular/angular/issues/31869) and [here](https://github.com/rollup/rollup/issues/3008).

**Closed** 2019-07-29 06:32 UTC
