### ISSUE TITLE
[build system] cannot build static library for any windows-gnu target

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6552] opened 2020-10-04 12:55 UTC
The build.zig

```zig
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();
    const lib = b.addStaticLibrary("demo", "src/main.zig");
    lib.setTarget(target);
    lib.setBuildMode(mode);
    lib.install();

    var main_tests = b.addTest("src/main.zig");
    main_tests.setBuildMode(mode);

    const test_step = b.step("test", "Run library tests");
    test_step.dependOn(&main_tests.step);
}
```

command:
```batch
D:\Temp\demo> zig build -Dtarget=x86_64-windows-gnu
error: FileNotFound
```

some details:
it seems try to copy libdemo.a but there only demo.lib in cache folder.
crash in 
https://github.com/ziglang/zig/blob/0e2d858d69ee1595bb58d936f83f0e0248d54d68/lib/std/build.zig#L2415
and got `zig build ... --name demo ...` here
https://github.com/ziglang/zig/blob/0e2d858d69ee1595bb58d936f83f0e0248d54d68/lib/std/build.zig#L2102-L2103

**Comment by MasterQ32** [comment] 2020-10-04 16:45
Seems like a duplicate of #6483

**Comment by andrewrk** [comment] 2020-10-16 00:30
Fixed by https://github.com/ziglang/zig/commit/33bc1ebe37ef6ba5dfe73e458d662b5b516723ba

**Closed by andrewrk** 2020-10-16 00:30 UTC
Labels: bug, os-windows
