### ISSUE TITLE
Compiler crash writing to a 0-sized `packed struct` field at `comptime`

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#21239] opened 2024-08-29 10:27 UTC
### Zig Version

0.14.0-dev.617+208baa37c

### Steps to Reproduce and Observed Behavior

minimized repro:
```zig
comptime {
    const S = packed struct {
        a: u8,
        b: u0,
    };
    var x: S = undefined;
    x.a = 0; //writing to a positive-sized field is fine
    x.b = 0; //writing to a 0-sized field crashes the compiler
    @compileError("here"); //only reached if the above line is commented out
}
```
`zig test .zig` crashes pretty much immediately (hangs, then exits with non-0 exit code), afterwards I also see leftover remnants of the progress display.

### Expected Behavior

Writing to a 0-sized field should be supported at `comptime`, and afaik always be a no-op.
<details><summary>Status-quo workaround:</summary>
<p>

```zig
fn setField(aggregate_pointer: anytype, comptime field_name: []const u8, new_value: @TypeOf(@field(aggregate_pointer.*, field_name))) void {
    const Field = @TypeOf(@field(aggregate_pointer.*, field_name));
    if (@bitSizeOf(Field) == 0) return; //workaround for https://github.com/ziglang/zig/issues/21239
    @field(aggregate_pointer.*, field_name) = new_value;
}

comptime {
    const S = packed struct {
        a: u8,
        b: u0,
    };
    var x: S = undefined;
    setField(&x, "a", 0); //writes the field
    setField(&x, "b", 0); //skips writing the field
    @compileError("here"); //correctly reached in analysis, compiles if commented out
}
```

</p>
</details>

**Comment by Vexu** [comment] 2024-09-01 15:34
Duplicate of #19908

**Closed by Vexu** 2024-09-01 15:34 UTC
Labels: bug
