### ISSUE TITLE
Unexpected behavior with array assignment

### ISSUE THREAD

**Issue by leesongun** [ziglang/zig#9283] opened 2021-07-02 10:26 UTC
I compiled the following code, and it printed `{ 1, 1 }` while i expected `{ 1, 0 }`. Is this intended behavior? 

```Zig
fn swap(a: [2]u8) [2]u8 {
    return .{ a[1], a[0] };
}

const print = @import("std").debug.print;

pub fn main() void {
    var i = [2]u8{ 0, 1 };
    i = swap(i);

    print("{any}\n", .{i});
}
```

**Comment by daurnimator** [comment] 2021-07-02 10:36
Duplicate of https://github.com/ziglang/zig/issues/3696

**Closed by daurnimator** 2021-07-02 10:36 UTC
