### ISSUE TITLE
Incorrect error message location

### ISSUE THREAD

**Issue by InspectorBoat** [ziglang/zig#17923] opened 2023-11-08 01:10 UTC
### Zig Version

0.12.0-dev.1486+234693bcb

### Steps to Reproduce and Observed Behavior

The following errors, as expected:
```zig
fn foo(comptime T: []u8) void {
    _ = T;
}

pub fn main() !void {
    foo(.{1});
}
```
However, the location of the error message is wrong:
```
src\main.zig:1:1: error: type '[]u8' does not support array initialization syntax
fn foo(comptime T: []u8) void {
^~
```

### Expected Behavior

The error message should appear at the function call's argument, not at the beginning of the file.

**Comment by Vexu** [comment] 2023-11-08 06:35
Duplicate of #17127

**Closed by Vexu** 2023-11-08 06:35 UTC
Labels: bug
