### ISSUE TITLE
Returning an optional error union type like that found in std.process causes a compiler bug.

### ISSUE THREAD

**Issue by IridescentRose** [ziglang/zig#6515] opened 2020-10-03 09:44 UTC
I was starting off by making a very simple command parser, and made a separate method for getting the argument - resulting in a compiler error. This crashes on v0.6.0 -> 0.6.0+006b780d4 (last build)

Expected output:
`/path/to/zig/program -parameter param`

Repro:
```zig
const std = @import("std");
const process = std.process;

//Get args
var arg_it : process.ArgIterator = undefined;
var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);

fn init() void{
    arg_it = process.args();
}

fn getNextArg() ?anyerror![]u8{
    const allocator = &arena.allocator;
    return arg_it.next(allocator);
}
pub fn main() anyerror!void{
    init();
    while(true){
        var arg = try getNextArg() orelse{
            break;
        };
        std.debug.warn("{} ", .{arg});
    }
}
```

Error:
```
broken LLVM module found: Call parameter type does not match function signature!
%"?anyerror![]u8"* %0
 %"?std.process.NextError![]u8"*  call fastcc void @std.process.ArgIterator.next(%"?anyerror![]u8"* sret %0, %std.process.ArgIterator* @arg_it, %std.mem.Allocator* getelementptr inbounds (%std.heap.ArenaAllocator, %std.heap.ArenaAllocator* @arena, i32 0, i32 0)), !dbg !16732

This is a bug in the Zig compiler.
```

**Comment by kivikakk** [comment] 2020-10-26 01:18
This is reproduced when building the `zig-master` branch of @Hejsil's zig-clap: https://github.com/Hejsil/zig-clap/tree/zig-master

```
$ zig build
Code Generation [155/601] std.hash_map.HashMapUnmanaged(usize,*std.debug.ModuleDebugInfo,... broken LLVM module found: Call parameter type does not match function signature!
  %6 = getelementptr inbounds { %"?[]const u8", i16 }, { %"?[]const u8", i16 }* %0, i32 0, i32 0, !dbg !18118
 %"?[:0]const u8"*  call fastcc void @std.process.ArgIterator.nextPosix(%"?[]const u8"* sret %6, %std.process.ArgIterator* %4), !dbg !18118

This is a bug in the Zig compiler.
/home/kivikakk/zig/src/stage1.zig:167:5: 0x562da895f80c in stage2_panic (zig1)
    @panic(ptr[0..len]);
```

**Comment by kivikakk** [comment] 2020-10-26 01:42
Ah, #6720.

**Comment by kivikakk** [comment] 2020-10-26 03:23
It looks like a level of indirection is causing a coercion to be skipped? @IridescentRose's example works with the following change:

```diff
-   return arg_it.next(allocator);
+   return @as(?anyerror![]u8, arg_it.next(allocator));
```

Similarly, zig-clap compiles if we change the function that calls into the std lib like so:

```diff
-    pub fn next(iter: *OsIterator) Error!?[]const u8 {
+    pub fn next(iter: *OsIterator) Error!?[:0]const u8 {
         if (builtin.os.tag == .windows) {
             return try iter.args.next(&iter.arena.allocator) orelse return null;
         } else {
             return iter.args.nextPosix();
         }
     }
```

Probably breaks the Windows side. This works correctly too:

```diff
     pub fn next(iter: *OsIterator) Error!?[]const u8 {
         if (builtin.os.tag == .windows) {
             return try iter.args.next(&iter.arena.allocator) orelse return null;
         } else {
             return @as(Error!?[]const u8, iter.args.nextPosix());
         }
     }
```

**Comment by gracefuu** [comment] 2021-04-08 17:46
Ran into a similar thing earlier. Here's a shrunk test case for the brave soul that wants to fix this.

```zig
const std = @import("std");
const testing = std.testing;

const Enum = enum {
    a,
    b,
    fn isB(self: Enum) bool {
        return self == Enum.b;
    }
};

const UnionEnum = union(enum) {
    e: Enum,
    f: u32,
};

const Struct = struct {
    bool_field: bool,
    opt_field: ?UnionEnum,
};

test {
    var e: Enum = Enum.b;
    var s: Struct = Struct{
        .bool_field = e.isB(),
        .opt_field = UnionEnum{ .e = e },
    };
    testing.expectEqual(e, s.opt_field.?.e); // fails
}
```

Similarly, explicitly coercing to optional fixes the bug:

```zig
test {
    var e: Enum = Enum.b;
    var s: Struct = Struct{
        .bool_field = e.isB(),
        .opt_field = @as(?UnionEnum, UnionEnum{ .e = e }),
    };
    testing.expectEqual(e, s.opt_field.?.e); // passes
}
```

**Comment by Vexu** [comment] 2024-03-28 11:39
Fixed in master.

**Closed by Vexu** 2024-03-28 11:39 UTC
Labels: bug, stage1
