### ISSUE TITLE
Does zig have something like standalone installer like unity3d on mac os?

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1179] opened 2018-06-30 09:04 UTC
* Standalone installer should be made the beginner easier to learn and use the zig programming language. 

For example:
* I want to download something like 2GB of binary files, I can use them to develop zig immediately from a fresh linux/macos/windows machine.

I know that depend on 3rd part softwares can land to unreliable install experience, untested 3rd part software bugs.
For example:
* What will happen when my isp or my country block the domain or ip of brew server? What will happen when brew server crash? What will happen when the network connect to brew server is slow? I can not use zig from my new mac os, even if i can download all the source code or binary file from zig website.
* What will happen when the default newest LLVM have some bugs that can stop me to use the zig, and the version of your LLVM looks good?

**Comment by tiehuis** [comment] 2018-06-30 10:13
The downloads provided at https://ziglang.org/download/ are all statically linked. There are no external depenencies/libraries required on the user end and they should always work provided the os interface/syscalls is at least some minimally supported version.

There is nothing to install by default since it is all self-contained as a portable executable. The only manual thing in regards to installation would be adding the zig compiler command to your PATH if needed.

I suppose we could elaborate on the installation method and explain this more clearly though, since it isn't explicitly mentioned on the download page.

**Comment by bronze1man** [comment] 2018-06-30 12:02
I am using mac os to use zip. And the download page do not have the mac os binary files.
I have to download 1.3GB LLVM@6 and build it from the source code. It costs about an hour.

**Comment by monouser7dig** [comment] 2018-06-30 12:10
> do not have the mac os binary files

 https://github.com/ziglang/zig/issues/1089

**Comment by binary132** [comment] 2018-06-30 12:32
Some day it will be easy to download a Zig compiler and use it to build Zig from source, with no dependencies, so I'm not sure what the issue is.

**Comment by binary132** [comment] 2018-06-30 12:33
Some day it will be easy to download a Zig compiler and use it to build Zig from source, with no dependencies, so I'm not sure what the issue is.  If the C++ build depends on LLVM, it depends on LLVM.  You can't get around that...

**Comment by bronze1man** [comment] 2018-06-30 12:51
@binary132 
It is ok to depends on LLVM. 
The LLVM library can be embed into the standalone installer, even clang can be embed into standalone installer.
It is ok for me to download a 2GB standalone installer on the mac os. It only cost 4 minutes to download a 2GB file with the 10MB/s bandwidth.
I just do not want the beginner like me costs a lot effect to install it.

**Comment by binary132** [comment] 2018-06-30 17:03
So are you talking about project dependency management, or about dep management for the stage 1 zig compiler itself?

**Comment by andrewrk** [comment] 2018-06-30 17:08
This is a duplicate of #1089

**Closed by andrewrk** 2018-06-30 17:08 UTC

**Comment by andrewrk** [comment] 2018-06-30 17:10
We are not going to have an option for developing zig other than the standard build from source instructions. For using zig on macos, #1089. Other distribution channels for using zig are welcome. But working on zig itself is always going to be "obtain a correct version of llvm and then build from source" instructions.
