### ISSUE TITLE
Containers break comptime laziness in branches

### ISSUE THREAD

**Issue by e-mm-a** [ziglang/zig#11385] opened 2022-04-05 01:09 UTC
### Zig Version

0.10.0-dev.1724+51ef31a83

### Steps to Reproduce

```zig
comptime {
    _ = if (false) struct {
        comptime {
            @compileError("foo");
        }
    } else void;
}
```
This is only triggered when an `if`/`switch` branch is a struct/union/enum and comptime evaluated.

### Expected Behavior

The struct containing a `@compileError` should not be evaluated.

### Actual Behavior

It is evaluated, incorrectly causing a compile error. This appears to be present in 0.8.0 as well.

**Comment by Vexu** [comment] 2022-04-05 05:50
Duplicate of #3778, fixed in stage2.

**Closed by Vexu** 2022-04-05 05:50 UTC
Labels: bug
