### ISSUE TITLE
Progress cuts off prints to the terminal

### ISSUE THREAD

**Issue by NicoElbers** [ziglang/zig#20119] opened 2024-05-29 22:04 UTC
### Zig Version

0.13.0-dev.339+6b020c3d1

### Steps to Reproduce and Observed Behavior

Create a template project using `zig init`

paste the following in `src/main.zig`
```zig
const std = @import("std");

pub fn main() !void {
    std.debug.print("0\n", .{});
    std.debug.print("1\n", .{});
    std.debug.print("2\n", .{});
    std.debug.print("3\n", .{});
    std.debug.print("4\n", .{});
    std.debug.print("5\n", .{});
    std.debug.print("6\n", .{});
    std.debug.print("7\n", .{});
    std.debug.print("8\n", .{});
    std.debug.print("9\n", .{});
    std.debug.print("10\n", .{});
}
```
Run `zig build run`

Your ouput should look something like this:
```
❯ zig build run           
[2/7] steps
└─ [5] zig build-exe ProgressObscuresLogging De
   └─ LLVM Emit Object
0
1
2
3
4
5
6
7
```

Notice that the "8", "9" and "10" prints are cut off.

From my testing the same holds true for printing to std out.

### Expected Behavior

That all 10 debug print statements are successfully displayed in the terminal.

**Comment by nektro** [comment] 2024-05-29 22:28
Related https://github.com/ziglang/zig/issues/18855

**Comment by Vexu** [comment] 2024-05-30 05:58
Cannot reproduce on Linux, are you on Windows perhaps #20105?

**Comment by Cloudef** [comment] 2024-05-30 06:26
I can reproduce this with `alacritty` terminal on linux using zig `0.13.0-dev.340+d750a78b2`
![2024-05-30-152613_hyprshot](https://github.com/ziglang/zig/assets/480330/eaab4e86-833e-4ddd-93fa-7fd333b133e5)

**Comment by Cloudef** [comment] 2024-05-30 06:29
Removing cache and running again makes even more lines disappear, so it seems the amount of rows in the `std.Progress` output seems to affect it.
![2024-05-30-152845_hyprshot](https://github.com/ziglang/zig/assets/480330/ed42513d-8eaf-44fc-8f80-097d85ad0a9d)

**Comment by andrewrk** [comment] 2024-05-31 19:49
Duplicate of #18855

**Closed by andrewrk** 2024-05-31 19:49 UTC
Labels: bug, zig build system, regression
