### ISSUE TITLE
Writing a bitcast bitfield struct to a volatile pointer generates multiple reads/writes

### ISSUE THREAD

**Issue by yvt** [ziglang/zig#5340] opened 2020-05-14 05:09 UTC
```zig
pub const Ctrl = packed struct {
    selr: u4 = 0,
    seli: u6 = 0,
    selp: u5 = 0,
    bypasspll: bool = false,
    bypasspostdiv2: bool = false,
    limupoff: bool = false,
    bwdirect: bool = false,
    bypassprediv: bool = false,
    bypasspostdiv: bool = false,
    clken: bool = false,
    frmen: bool = false,
    frmclkstable: bool = false,
    skewen: bool = false,
    _pad: u7 = undefined,
};
export fn configureHardware(base: *volatile u32) void {
    base.* = @bitCast(u32, Ctrl{
        .selr = 0,
        .seli = 39,
        .selp = 19,
        .bypasspostdiv2 = true,
        .clken = true,
    });
}
```

Expected: A single write to `base.*`, e.g.,

```asm
configureHardware:
        mov     eax, dword ptr [rip + __unnamed_1]
        mov     dword ptr [rdi], eax
        ret

__unnamed_1:
        .ascii  "pN"
        .byte   33
        .byte   0
```

Actual:

```asm
configureHardware:
        and     word ptr [rdi], -16
        movzx   eax, word ptr [rdi]
        and     eax, -1009
        or      eax, 624
        mov     word ptr [rdi], ax
        movzx   eax, word ptr [rdi]
        and     eax, -31745
        or      eax, 19456
        mov     word ptr [rdi], ax
        or      byte ptr [rdi + 2], 1
        or      byte ptr [rdi + 2], 32
        and     word ptr [rdi], 32767
        and     byte ptr [rdi + 2], -3
        and     byte ptr [rdi + 2], -5
        and     byte ptr [rdi + 2], -9
        and     byte ptr [rdi + 2], -17
        and     byte ptr [rdi + 2], -65
        and     byte ptr [rdi + 2], 127
        and     byte ptr [rdi + 3], -2
        ret
```

[Compiler Explorer Link](https://zig.godbolt.org/z/6FgmsC)

**Comment by michalsieron** [comment] 2022-04-26 21:01
Looks like duplicate of #8981
Change it to
```zig
    base.* = @ptrCast(*const u32, &Ctrl{
        .selr = 0,
        .seli = 39,
        .selp = 19,
        .bypasspostdiv2 = true,
        .clken = true,
    }).*;
```
and you should get expected result
In my case using zig `0.10.0-dev.1933+5f2d0d414`:
```asm
0000000000000000 <configureHardware>:
   0:	c7 07 70 4e 21 00    	mov    DWORD PTR [rdi],0x214e70
   6:	c3                   	ret
```

**Comment by Vexu** [comment] 2023-01-21 22:38
Fixed by the new integer backed packed struct semantics.

**Closed by Vexu** 2023-01-21 22:38 UTC
Labels: bug, stage1, miscompilation
