### ISSUE TITLE
incorrect `resumed an async function which already returned` crash when async function called from loop

### ISSUE THREAD

**Issue by charles-l** [ziglang/zig#11603] opened 2022-05-07 03:53 UTC
### Zig Version

0.10.0-dev.2103+ac1aaec9c

### Steps to Reproduce

```zig
var frames = [2]anyframe{ undefined, undefined };
var frames_i: usize = 0;

fn f() void {
    suspend {
        frames[frames_i] = @frame();
        frames_i += 1;
    }
}

pub fn main() void {
    var x: u32 = 0;

    while (x < 2) : (x += 1) {
        _ = async f();
    }

    for (frames) |frame| {
        // for debug
        std.debug.print("{}\n", .{@ptrCast(*const anyopaque, frame)});
        resume frame;
    }
}
```

If you replace the while loop with two `_ = async f();` calls, it works as expected.

### Expected Behavior

The program should run successfully since two async frames should be stored.

The expected behavior is equivalent to replacing the while loop with two `async f()` calls, which results in the following output (i.e. two different addresses):

```
anyopaque@7ffd7a6c1ba8
anyopaque@7ffd7a6c1b90
```

### Actual Behavior
With the code provided, I get the same address for both, and the program crashes with `resumed an async function which already returned`.
```
anyopaque@7ffe23d39bc0
anyopaque@7ffe23d39bc0
```

**Comment by Vexu** [comment] 2022-05-07 07:15
Duplicate of #5040

`anyframe` is a pointer, the actual frame of the async functions is getting stack allocated and overwritten in the loop.

**Closed by Vexu** 2022-05-07 07:15 UTC
Labels: bug

**Comment by charles-l** [comment] 2022-05-07 15:06
OK, my mental model of how async works isn't quite there yet. I guess it does make more sense that the frame created in the while loop referenced the same stack slot, since that's how, e.g. an `i32` would be stored on the stack. Sorry about the erroneous bug report.

In case anyone else runs into this issue, I was able to get it working as I expected by heap allocating the frames like so:

```
const std = @import("std");
var frames = [2]anyframe{ undefined, undefined };
var gpa = std.heap.GeneralPurposeAllocator(.{}){};
var frames_i: usize = 0;

fn f() void {
    suspend {
        var frame_ptr = gpa.allocator().create(@Frame(f)) catch unreachable;
        frame_ptr.* = @frame().*;
        frames[frames_i] = frame_ptr;
        frames_i += 1;
    }
}

pub fn main() void {
    var x: u32 = 0;

    while (x < 2) : (x += 1) {
        _ = async f();
    }

    for (frames) |frame| {
        std.debug.print("{}\n", .{@ptrCast(*const @Frame(f), frame)});
        resume frame;
        gpa.allocator().destroy(@ptrCast(*const @Frame(f), frame));
    }
}
```
