### ISSUE TITLE
Compiler crash when compiling recursive function

### ISSUE THREAD

**Issue by teoet6** [ziglang/zig#16664] opened 2023-08-03 14:30 UTC
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

When compiling the following code with `zig build-exe main.zig` the compiler segfaults.
```zig
fn f(comptime msg: []const u8) !void {
    try f("a");
    _ = msg;
}

pub fn main() !void {
    try f("a");
}
```

### Expected Behavior

The compiler not to segfault.

**Comment by alichraghi** [comment] 2023-08-03 23:02
Duplicate of #13780

**Closed** 2023-08-12 09:33 UTC
Labels: bug
