### ISSUE TITLE
dead comptime switch cases being analyzed and causing errors

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9682] opened 2021-09-03 03:27 UTC
I found this bug while updating zigwin32 with the new `usingnamespace` semantics.  Consider the following code:

```zig
const Platform = enum {a, b};
const platform = Platform.a;

const TypeOnlyForPlatformB = switch(platform) {
    .b => u32,
    else => @compileError("TypeOnlyForPlatformB does not work on this platform"),
};

const Foo = switch(platform) {
    .a => extern struct {
        placeholder: u32,
    },
    .b => extern struct {
        field: TypeOnlyForPlatformB,
    },
};

test {
    _ = Foo;
}
```

This example will fail to compile:
```sh
$ zig test bug.zig 
./bug.zig:6:13: error: TypeOnlyForPlatformB does not work on this platform
    else => @compileError("TypeOnlyForPlatformB does not work on this platform"),
            ^
./bug.zig:14:16: note: referenced here
        field: TypeOnlyForPlatformB,
               ^
```

However, the only thing being referenced by the test is "Foo", which should only analyze the `.a` case in the corresponding switch, however, we get a semantic error that comes from the `.b` case even though the platform is hardcoded to `.a`.

This bug is causing an issue in zigwin32 because there are types that are only defined for certain architectures, and they are only referenced by other types with those same architectures, however, Zig is still analyzing the switch cases for architectures that are do not match what's being compiled for, which results in compile errors because these types being referenced aren't supported.

**Comment by Vexu** [comment] 2021-09-03 04:53
Duplicate of #3778 which also contains a workaround.

**Closed by Vexu** 2021-09-03 04:53 UTC

**Comment by marler8997** [comment] 2021-09-03 05:26
I don't see where the workaround is...?

**Comment by Vexu** [comment] 2021-09-03 06:15
The `DontEval` branch is the workaround, putting the struct in a separate declaration.
