### ISSUE TITLE
big mach-o x86_64 executable size

### ISSUE THREAD

**Issue by frarees** [ziglang/zig#7777] opened 2021-01-14 13:09 UTC
The following code produces a ~128mb executable. Looks like `PixelBuffers` (4000 * 4000 * 2 * 4) is stored in the .bss section. It is initialized with zeroes.

This doesn't seem to happen cross-compiling for `x86_64-linux-gnu` (~600kb executable size).

OS: macOS 11.1
Zig: 0.8.0-dev.956+2c79d669a

```zig
const std = @import("std");
const warn = std.debug.warn;
const fmt = std.fmt;

const Color = struct {
    color: [4]u8 = [4]u8{ 0, 0, 0, 0 },
    pub fn black() Color {
        var color = Color{ .color = [4]u8{ 0, 0, 0, 255 } };
        return color;
    }
};

const PixelBuffers = struct {
    const pixelsCapacity = 4000 * 4000;
    buffers: [2][pixelsCapacity]Color,
    frontIndex: usize,
    w: usize,
    h: usize,

    pub fn init(self: *PixelBuffers, nW: usize, nH: usize) void {
        self.*.frontIndex = 1;
        self.*.w = nW;
        self.*.h = nH;
        var y: usize = 0;
        while (y < nH) {
            var x: usize = 0;
            while (x < nW) {
                self.*.buffers[0][x + nW * y] = Color.black();
                self.*.buffers[1][x + nW * y] = Color.black();
                x += 1;
            }
            y += 1;
        }
    }
};

var pixels: PixelBuffers = undefined;

pub fn main() !void {
    pixels.init(600, 600);
}
```

Verbose link:
```
ld64.lld -error-limit 0 -demangle -dynamic -arch x86_64 -macosx_version_min 11.1.0 -sdk_version 11.1.0 -pie -o paint -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk zig-cache/o/a84dbfa41346328b29638daef49cb7db/paint.o /Users/frarees/.cache/zig/o/a5b597c34b97827c13407a7328c96c39/libcompiler_rt.a -lSystem
```

**Comment by vesim987** [comment] 2021-01-14 14:27
Just a quick note.
We were looking at this at discord, and we realized that the linker put the sections in the wrong order:
```
__DATA       0x000000010004f000 
.data        0x000000010004f000
.bss         0x000000010004f0c0
.thread_vars 0x0000000107a62180
.const       0x0000000107a62198``` thats just couple of them, .bss is before .const, so the linker was not able to reduce the filesize.

**Comment by LemonBoy** [comment] 2021-01-14 16:52
lld's mach-o backend is known to be .. quirky? If you can't reproduce the problem with the system `ld` (that's Apple's ld64) we can be pretty sure it's lld's fault.
The good news is that [a new mach-o backend may land in LLVM-12](https://lists.llvm.org/pipermail/llvm-dev/2021-January/147665.html), that'd solve a lot of problems we have/had.

**Comment by frarees** [comment] 2021-01-15 09:38
Indeed seems like an issue caused by lld. Having `ZIG_SYSTEM_LINKER_HACK=1` generates a ~500kb executable file.

Verbose link:
```
ld -demangle -dynamic -arch x86_64 -macosx_version_min 11.1.0 -sdk_version 11.1.0 -pie -o paint -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk zig-cache/o/a84dbfa41346328b29638daef49cb7db/paint.o /Users/frarees/.cache/zig/o/a5b597c34b97827c13407a7328c96c39/libcompiler_rt.a -lSystem
```

**Comment by kubkon** [comment] 2022-05-27 07:48
Given that we have no intention of going back to using LLVM's lld.ld64 since we are using our own, I am closing this issue.

**Closed by kubkon** 2022-05-27 07:48 UTC
Labels: bug, upstream
