### ISSUE TITLE
Bug in compiler: broken LLVM module found: Call parameter type does not match function signature!

### ISSUE THREAD

**Issue by Pistahh** [ziglang/zig#9277] opened 2021-07-01 18:53 UTC
Compiler breaks when compiling this, instead of properly reporting an error (source also available at https://gist.github.com/Pistahh/9bff4a9da6f84d9e48b261c6ca2f839b
)

Fails both with 0.8.0 and latest git version.

```
broken LLVM module found: Call parameter type does not match function signature!
  %1 = getelementptr inbounds %Mystruct, %Mystruct* %0, i32 0, i32 1, !dbg !18922
 %"?[]const u8"*  call fastcc void @Mystruct.destroyField(%Mystruct* %0, %"?[]u8"* %1), !dbg !18924

This is a bug in the Zig compiler.thread 32324 panic:
Unable to dump stack trace: debug info stripped
zsh: abort (core dumped)  zig build-exe b.zig
```

```
const std = @import("std");
const print = std.debug.print;
const Allocator = std.mem.Allocator;

const Mystruct = struct {
    const Self = @This();
    allocator: *Allocator,
    field1: ?[]u8 = null,

    fn destroyField(self: Self, field: ?[]const u8) void {
        if (field != null) {
            self.allocator.free(field.?);
        }
    }

    fn destroy(self: Self) void {
        self.destroyField(self.field1);
    }

    fn init(alloc: *Allocator) !Mystruct {
        var process = Mystruct{ .allocator = alloc };

        return process;
    }
};

pub fn main() !void {
    var gpalloc = std.heap.GeneralPurposeAllocator(.{}){};
    defer std.debug.assert(!gpalloc.deinit());

    const alloc = &gpalloc.allocator;

    const str = try Mystruct.init(alloc);
    defer str.destroy();

}
```

**Comment by Vexu** [comment] 2021-07-01 19:11
Duplicate of #6147, #5686 etc. The cast is allowed by Zig but is not being generated properly.

**Closed by Vexu** 2021-07-01 19:11 UTC
