### ISSUE TITLE
Add a more helpful error for string comparision using ==

### ISSUE THREAD

**Issue by Mouvedia** [ziglang/zig#8290] opened 2021-03-19 00:23 UTC
I dunno if it's a bug or not. If it isn't I would like to have an explanation.

```
const foo: i32 = 0;
const stringFoo = switch (foo) {
  0 => "zero",
  1...std.math.maxInt(i32) => "positive",
  else => "negative",
};
assert(stringFoo == "positive");
```
throws
```
error: operator not allowed for type '[:0]const u8'
assert(stringFoo == "positive"); 
```
but
```
const foo: i32 = 0;
const stringFoo = switch (foo) {
  0 => "zero",
  1...std.math.maxInt(i32) => "positive",
  else => "negative",
};
assert(stringFoo == "zero");
```
doesn't throw.

IMHO it's **inconsistent** either I should have a type error for both _or_ the failing one should throw an error for the condition (not the type). If I could choose Id pick the latter.

version 0.7.1 on https://godbolt.org/

**Comment by Tetralux** [comment] 2021-03-19 00:58
Also occurs on master. (96ae451bbe78cd35a62e00e3fb48a32f24ebd315)

**Comment by SpexGuy** [comment] 2021-03-19 02:19
Ah, this took me a minute to spot.  The problem is that `==` is defined for strings of the same length but not strings of differing lengths.  So `"foo" == "bar"` compiles because these are both `*const [3:0]u8`, but `"foo" == "quux"` does not.  In this case, the two operands are `*const [3:0]u8` and `*const [4:0]u8`, so the compiler performs peer type resolution to `[:0]const u8`, and then attempts to do `==`, which causes a compile error.

Everything here is working as designed, but this might constitute a design flaw.  At minimum, the error message is not very helpful since it's complaining about slices, and none of the types in the code are slices.  We could improve it to list the inputs before peer type resolution instead of the peer type resolution result.  But there may be more we can do to improve it.

**Comment by SpexGuy** [comment] 2021-03-19 02:21
I don't know if `"foo" == "foo"` is actually guaranteed to work though, so even when this does compile it may be a footgun.

**Comment by Mouvedia** [comment] 2021-03-19 02:30
> I don't know if `"foo" == "foo"` is actually guaranteed to be true though, so even when this does compile it may be a footgun.

Please enforce that this is always true.

> the error message is not very helpful

Id prefer if we had only 2 cases for an assert: passes or unreachable. Right now we have 3:
- conditions passes
- same length string but not the same characters (unreachable)
- type mismatch

Ideally the type mismatch case should be merged into unreachable by adding extra information.
e.g. instead of `reached unreachable code` you would get `reached unreachable code, expected *const[4:0]u8 received *const[8:0]u8`

**Comment by MasterQ32** [comment] 2021-03-19 08:29
> Please enforce that this is always true.

This isn't possible with a language like Zig. The reason why this comparison is allowed is that you must be able to compare pointer equality. But consider this:
```zig
var a = [3:0]u8 { 'f', 'o', 'o' };
var b = [3:0]u8 { 'f', 'o', 'o' };

std.debug.assert(&a == &b);
```
This will never happen, as `a` and `b` are different objects and thus will never share the same address. The same happens when you compare `"foo" == "foo"`, which has the same types applied.

Comparing slice or pointer contents with `==` is out of scope for zig as it introduces a lot of code (see `std.mem.eql` which implements this behaviour).

If you want to compare two slice contents, you should use `std.mem.eql`:

```zig
const foo: i32 = 0;
const stringFoo = switch (foo) {
  0 => "zero",
  1...std.math.maxInt(i32) => "positive",
  else => "negative",
};
assert( std.mem.eql(u8, stringFoo, "positive")); // compares for string content, not for address equality
```

**Comment by Vexu** [comment] 2021-03-19 08:47
The switch type inconsistency is covered by #5401.

**Comment by Mouvedia** [comment] 2021-03-19 09:48
Oh you mean that there's a high probability of reusing the same string in memory as a mean of optimization but it cannot be guaranteed. I guess that makes sense.
Is this undefined behaviour territory then?

**Comment by Vexu** [comment] 2021-03-19 10:00
>Oh you mean that there's a high probability of reusing the same string in memory as a mean of optimization but it cannot be guaranteed. I guess that makes sense.

Two different string literals will never have the same address at compile time, and may only have the same address as an optimization in certain release modes.

> I am sure there's a lot code that lazily uses `==` instead of `std.mem.eql`.

There isn't, using `==` for string literals is nearly always the wrong solution.

**Comment by Mouvedia** [comment] 2021-03-19 10:11
I wish the non-reproducibility of an `assert` could be detected and produce a warning.

> There isn't

That's optimist; you have a good opinion of zig enthusiasts, I respect that.

**Comment by Vexu** [comment] 2021-03-19 10:21
>That's optimist

It's not optimistic, using `==` for string comparison means your code is completely broken

**Comment by Mouvedia** [comment] 2021-03-19 10:29
> using `==` for string comparison means your code is completely broken

I understand that. I am just saying that it's harder to notice when your assert passes.
Anyway, this issue now only requests an error message change.

**Closed** 2022-12-03 05:42 UTC
Labels: enhancement, error message

**Comment by Mouvedia** [comment] 2022-12-03 06:29
Thanks.

BTW seems like the issue has the wrong milestone.
