### ISSUE TITLE
stage2: tagged union leads to error when order of declarations doesn't match the enum.

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#12667] opened 2022-08-28 21:09 UTC
### Zig Version

0.10.0-dev.3685+dae7aeb33

### Steps to Reproduce

Run the following code with `zig run test.zig`:
```zig
const std = @import("std");

pub const Enum = enum(u32) {
    a,
    b
};
pub const TaggedUnion = union(Enum) {
    b: []const u8,
    a: []const u8,
};

pub fn main() void {
    const result = TaggedUnion{.b="b"};
    std.log.err("Test: {s}", .{(result).b});
}
```

### Expected Behavior

It should work. The field `b` of the union is initialized and accessed.

### Actual Behavior

The compiler thinks that field `a` is active:
```
test.zig:14:40: error: access of union field 'b' while field 'a' is active
    std.log.err("Test: {s}", .{(result).b});
                               ~~~~~~~~^~
test.zig:7:25: note: union declared here
pub const TaggedUnion = union(Enum) {
                        ^~~~~
```

It does work in stage1.

It seems to be related to the order of the declarations. When I swap `a` and `b` in either the enum or the union it works.

**Comment by leecannon** [comment] 2022-08-28 21:16
This is a duplicate of #12543 which should be resolved in https://github.com/ziglang/zig/commit/d48af541c7aa235948621cdbc250d983af303977 however the download on ziglang.org doesn't yet include this commit as the CI is still not green.

A proposal to make this a compile error has been raised #12556

**Comment by Vexu** [comment] 2022-08-28 21:22
Looks like I missed this case in d48af541c7aa235948621cdbc250d983af303977 since it happens with latest master.

**Closed** 2022-08-29 20:46 UTC
Labels: bug, stage2
