### ISSUE TITLE
Cannot create type in inline for

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6284] opened 2020-09-08 08:05 UTC
```zig
const std = @import("std");

pub fn main() anyerror!void {
    comptime var xt: [2]std.builtin.TypeInfo.StructField = undefined;
    inline for (xt) |*t, i| {
        t.* = .{
            .name = "invalid",
            .default_value = null,
            .is_comptime = false,
            .field_type = struct {
                arr: [i]u8,
            },
        };
    }
    @compileLog(xt[0].field_type == xt[1].field_type);
}
```

It will give true, and both types are `struct { arr: [1]u8 }`

(create an addition function will work)

Maybe just disallow define struct in this inline loop.

**Comment by Vexu** [comment] 2020-09-14 18:28
Duplicate of #4148

**Closed by Vexu** 2020-09-14 18:28 UTC
