### ISSUE TITLE
`windows.DeleteFile` Does not fail on non-empty directories

### ISSUE THREAD

**Issue by xEgoist** [ziglang/zig#15315] opened 2023-04-16 09:11 UTC
### Zig Version

0.11.0-dev.2613+b42562be7

### Steps to Reproduce and Observed Behavior

Upon reading this unrelated issue: https://github.com/dokan-dev/dokany/issues/883,
I learned that calling `NtCreateFile` with `FILE_DELETE_ON_CLOSE` does **not** fail on non-empty directories, but simply mark it as `DELETE_PENDING` with a success `NTSTATUS`. 

Here are simple steps to reproduce this bug:

1- Create any folder, here i am using `C:\example`
2- Create any empty file inside it `C:\example\test.txt` 

run the following:

```zig
const std = @import("std");

pub fn main() !void {
    var fd = try std.fs.openDirAbsolute("C:\\", .{});
    defer fd.close();
    try fd.deleteDir("example");
}
```
`deleteDir` will not complain and the folder will not be removed, which is not what the docs says [here](https://ziglang.org/documentation/master/std/#A;std:fs.Dir.deleteDir)

### Expected Behavior

`DIRECTORY_NOT_EMPTY`/`error.DirNotEmpty` should be returned.

---
Side Note: I am mostly guessing here, and haven't looked deeply in the changes,  but I think that the recent CI timeouts #14948  are caused by `windows.OpenFile` infinite looping through `DELETE_PENDING` due to this (again, i could definately be wrong here).

https://github.com/ziglang/zig/blob/23ac4dd87b740012ba33e8ab2ea6fb25c04b6268/lib/std/os/windows.zig#L141-L156

---
## Solution/Alternative Delete Functions

I explored few solutions to resolve this bug to find out how other delete functions works:

- `kernel32!RemoveDirectory()` returns false and sets the last error to 145 - Directory not empty. I haven't traced it, but i assume it calls `SetInformationFile`. 
- `ntdll!NtDeleteFile` Marks for deletion and silently fails as well (There is some controversy if it just sets `FILE_DELETE_ON_CLOSE` ). 
- Open for deletion + `ntdll!NtSetInformationFile` with `FileDispositionInformation`: this marks it for deletion and reports if not-empty.

**Comment by squeek502** [comment] 2023-04-16 19:20
Duplicate of https://github.com/ziglang/zig/issues/5537

**Closed** 2023-04-16 20:32 UTC
Labels: bug

**Comment by xEgoist** [comment] 2023-04-16 20:54
> Duplicate of #5537
> 
> Also relevant: #6452

I apologize for not doing a better search. Thanks for pointing that out.
