### ISSUE TITLE
Misleading error arrow when misusing builtin function @as

### ISSUE THREAD

**Issue by Costava** [ziglang/zig#15189] opened 2023-04-05 23:02 UTC
### Zig Version

0.10.1

### Steps to Reproduce and Observed Output

`as.zig`:
```zig
const std = @import("std");

pub fn main() !void {
    var foo: usize = 9;
    var bar: u8 = @as(u8, foo);

    std.debug.print("bar: {}\n", .{bar});
}
```

```sh
$ zig run as.zig 
as.zig:3:1: error: expected type 'u8', found 'usize'
pub fn main() !void {
^~~
as.zig:3:1: note: unsigned 8-bit int cannot represent all possible unsigned 64-bit values
referenced by:
    callMain: /usr/lib/zig/std/start.zig:614:32
    initEventLoopAndCallMain: /usr/lib/zig/std/start.zig:548:51
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

`for.zig`:
```zig
const std = @import("std");

pub fn main() !void {
    var table: [32][16]u8 = undefined;

    for (table[0..4]) |*s, i| {
        s.*[i] = @as(u8, i);

        std.debug.print("baz: {}\n", .{s.*[i]});
    }
}
```

```sh
$ zig run for.zig 
for.zig:7:13: error: expected type 'u8', found 'usize'
        s.*[i] = @as(u8, i);
            ^
for.zig:7:13: note: unsigned 8-bit int cannot represent all possible unsigned 64-bit values
referenced by:
    callMain: /usr/lib/zig/std/start.zig:614:32
    initEventLoopAndCallMain: /usr/lib/zig/std/start.zig:548:51
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Output

In the two snippets above, using `@truncate` in place of `@as` is correct and doesn't cause an error.  
When `@as` is misused, as seen in the snippets, the error message arrow points to a misleading part of the code.

The arrow should probably instead be pointing to the second argument of the `@as` calls.

**Comment by mlugg** [comment] 2023-04-06 00:16
Both issues still present on master

**Comment by Vexu** [comment] 2023-04-07 12:00
Duplicate of #14768

**Closed by Vexu** 2023-04-07 12:00 UTC
Labels: error message
