### ISSUE TITLE
Compiler crash when using stackFallbackAllocator.get() during comptime

### ISSUE THREAD

**Issue by Ratakor** [ziglang/zig#21233] opened 2024-08-28 18:54 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Code:
```zig
const std = @import("std");
var al = blk: {
    var al_sfa = std.heap.stackFallback(4096, std.heap.page_allocator);
    break :blk std.ArrayList(u8).init(al_sfa.get());
};

pub fn main() !void {
    _ = al;
}
```
Output:
```
thread 5513 panic: reached unreachable code
/home/ratakor/tmp/zig-0.13.0/src/codegen/llvm.zig:4421:60: 0x1ba69c8 in lowerPtr (zig)
            .arr_elem, .comptime_field, .comptime_alloc => unreachable,
                                                           ^
/home/ratakor/tmp/zig-0.13.0/src/codegen/llvm.zig:3959:35: 0x18ee160 in lowerValue (zig)
            .ptr => try o.lowerPtr(arg_val, 0),
                                  ^
/home/ratakor/tmp/zig-0.13.0/src/codegen/llvm.zig:4241:60: 0x18f369a in lowerValue (zig)
                        vals[llvm_index] = try o.lowerValue(
                                                           ^
/home/ratakor/tmp/zig-0.13.0/src/codegen/llvm.zig:4241:60: 0x18f369a in lowerValue (zig)
                        vals[llvm_index] = try o.lowerValue(
                                                           ^
/home/ratakor/tmp/zig-0.13.0/src/codegen/llvm.zig:4761:41: 0x18e8b68 in genDecl (zig)
                else => try o.lowerValue(init_val),
                                        ^
/home/ratakor/tmp/zig-0.13.0/src/codegen/llvm.zig:1774:19: 0x1906ba5 in updateDecl (zig)
        dg.genDecl() catch |err| switch (err) {
                  ^
/home/ratakor/tmp/zig-0.13.0/src/link/Elf.zig:3002:70: 0x1b97ec6 in updateDecl (zig)
    if (self.llvm_object) |llvm_object| return llvm_object.updateDecl(mod, decl_index);
                                                                     ^
/home/ratakor/tmp/zig-0.13.0/src/link.zig:406:82: 0x190892a in updateDecl (zig)
                return @as(*tag.Type(), @fieldParentPtr("base", base)).updateDecl(module, decl_index);
                                                                                 ^
/home/ratakor/tmp/zig-0.13.0/src/Module.zig:5470:22: 0x1908177 in linkerUpdateDecl (zig)
        lf.updateDecl(zcu, decl_index) catch |err| switch (err) {
                     ^
/home/ratakor/tmp/zig-0.13.0/src/Compilation.zig:3395:48: 0x1afd520 in processOneJob (zig)
                    try module.linkerUpdateDecl(decl_index);
                                               ^
/home/ratakor/tmp/zig-0.13.0/src/Compilation.zig:3345:30: 0x1936a2c in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
/home/ratakor/tmp/zig-0.13.0/src/Compilation.zig:2132:31: 0x19325ec in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/ratakor/tmp/zig-0.13.0/src/main.zig:4404:20: 0x196374d in updateModule (zig)
    try comp.update(prog_node);
                   ^
/home/ratakor/tmp/zig-0.13.0/src/main.zig:3422:21: 0x19cb54b in buildOutputType (zig)
        updateModule(comp, color, root_prog_node) catch |err| switch (err) {
                    ^
/home/ratakor/tmp/zig-0.13.0/src/main.zig:271:31: 0x1816fb9 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .run);
                              ^
/home/ratakor/tmp/zig-0.13.0/src/main.zig:209:20: 0x1813c55 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/ratakor/tmp/zig-0.13.0/lib/std/start.zig:524:37: 0x18136ee in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x73651ce37d6d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x73651ce37d6d` was not available, trace may be incomplete
zsh: IOT instruction  ./zig-debug-0.13.0 run test.zig
```

When not using comptime block the compiler doesn't crash but still display an error which is probably due to  https://github.com/ziglang/zig/pull/18275 because both used to work perfectly fine during comptime.

Code:
```zig
const std = @import("std");
var al_sfa = std.heap.stackFallback(4096, std.heap.page_allocator);
var al = std.ArrayList(u8).init(al_sfa.get());

pub fn main() !void {
    _ = al_sfa;
    _ = al;
}
```

Output
```
/lib/zig/std/heap.zig:532:24: error: unable to evaluate comptime expression
                assert(!self.get_called); // `get` called multiple times; instead use `const allocator = stackFallback(N).get();`
                       ^~~~~~~~~~~~~~~~
test.zig:4:43: note: called from here
var al = std.ArrayList(u8).init(al_sfa.get());
                                ~~~~~~~~~~^~
```

### Expected Behavior

No compilation error or crash from the compilator when using stackFallbackAllocator.get() during comptime.

**Comment by Vexu** [comment] 2024-09-01 15:51
Duplicate of #20365

**Closed by Vexu** 2024-09-01 15:51 UTC
Labels: bug
