### ISSUE TITLE
C translation error  ( with lua code )

### ISSUE THREAD

**Issue by SrMordred** [ziglang/zig#3824] opened 2019-12-01 21:57 UTC
```
const c = @cImport({
    @cInclude("lua.h");
    @cInclude("lualib.h");
    @cInclude("lauxlib.h"); 
});

const LUA_REGISTRYINDEX = c.LUA_REGISTRYINDEX; //error originate here
```

`error: expected type 'type', found 'comptime_int'`

Original source code:
```
#if LUAI_BITSINT >= 32
#define LUAI_MAXSTACK		1000000
#else
#define LUAI_MAXSTACK		15000
#endif

#define LUA_REGISTRYINDEX	(-LUAI_MAXSTACK - 1000)
```

generated code:

```
pub const LUAI_MAXSTACK = 1000000;

pub const LUA_REGISTRYINDEX = if (@typeId(@typeOf(-1000)) == @import("builtin").TypeId.Pointer) @ptrCast(-LUAI_MAXSTACK, -1000) else if (@typeId(@typeOf(-1000)) == @import("builtin").TypeId.Int) @intToPtr(-LUAI_MAXSTACK, -1000) else @as(-LUAI_MAXSTACK, -1000);
```

**Comment by pixelherodev** [comment] 2019-12-01 22:15
That generated code looks very, very wrong...

If you manually adjust that LUA_REGISTRYINDEX value to equal -1001000 in the zig code (better yet, in the C header), you should be good, but that's a workaround and this is definitely a bug in `translate-c`

**Comment by daurnimator** [comment] 2019-12-02 01:10
Duplicate of #2936

**Closed by daurnimator** 2019-12-02 01:10 UTC
