### ISSUE TITLE
@floatToInt failing on negative numbers

### ISSUE THREAD

**Issue by sporksmith** [ziglang/zig#10600] opened 2022-01-16 01:12 UTC
### Zig Version

Happens on:

* 0.9.0
* 0.10.0-dev.258+349a7cc27

*doesn't* happen on:
* 0.10.0-dev.290+3901b6fb0

### Steps to Reproduce

On Linux, x86_64:

Source file `f2i.zig`:

```
pub fn main() void {
    _ = @floatToInt(i64, -1.0);
}
```

```
$ zig build-exe f2i.zig
```

### Expected Behavior

Successfully compile a ~no-op program.

### Actual Behavior

```
$ zig build-exe f2i.zig 
./f2i.zig:5:9: error: integer value '-18446744073709551615' cannot be stored in type 'i64'
    _ = @floatToInt(i64, a);
        ^
```

**Comment by pfgithub** [comment] 2022-01-16 02:25
This is working for me on 0.10.0-dev.285+a5c7742ba for macos-x86_64, what platform are you using?

```zig
pfg@pfgs-MacBook-Pro ~/D/N/t/g/9/tmp> zig run a.zig
| -1
./a.zig:2:5: error: found compile log statement
    @compileLog(@floatToInt(i64, -1.0));
    ^
pfg@pfgs-MacBook-Pro ~/D/N/t/g/9/tmp [1]> zig run a.zig -Dtarget=wasm32-freestanding
| -1
./a.zig:2:5: error: found compile log statement
    @compileLog(@floatToInt(i64, -1.0));
    ^
```

**Comment by sporksmith** [comment] 2022-01-16 02:59
> what platform are you using?

Ubuntu 20.04.3, x86_64

**Comment by sporksmith** [comment] 2022-01-16 03:29
> This is working for me on 0.10.0-dev.285+a5c7742ba for macos-x86_64,

I just tried the latest nightly (zig-linux-x86_64-0.10.0-dev.290+3901b6fb0), which indeed works as expected. So apparently it's fixed, though it's probably worth backporting for 9.1 if it hasn't been already

**Comment by tiehuis** [comment] 2022-01-17 03:54
Duplicate of #10592.

**Closed by tiehuis** 2022-01-17 03:54 UTC
Labels: bug
