### ISSUE TITLE
`inline for` should imply `comptime`

### ISSUE THREAD

**Issue by scheibo** [ziglang/zig#10235] opened 2021-11-28 03:55 UTC
### Zig Version

0.9.0-dev.1795+aa61e03f2

### Steps to Reproduce

I expect to be able to iterate over a type's fieldNames with `std.meta.fieldNames`, but instead get an error.

```zig
const std = @import("std");
const Foo = struct { a: u8, b: u8 };

test {
    var a = Foo{ .a = 1, .b = 2 };
    var b = Foo{ .a = 3, .b = 4 };
    inline for (std.meta.fieldNames(@TypeOf(a))) |name| {
        @field(a, name) = @field(b, name);
    }
}
```

### Expected Behavior

I expect the above snippet to be equivalent to iterating over `std.meta.field` and accessing the `field.name`:

```zig
const std = @import("std");
const Foo = struct { a: u8, b: u8 };

test {
    var a = Foo{ .a = 1, .b = 2 };
    var b = Foo{ .a = 3, .b = 4 };
    inline for (std.meta.fields(@TypeOf(a))) |field| {
        @field(a, field.name) = @field(b, field.name);
    }
}
```

Alternatively, I expect that since `std.meta.fieldNames` takes a single `comptime` param and its entire body is in a `comptime` block that it should "just work" with an `inline for`, however an explicit `comptime` before the call is necessary:

```zig
const std = @import("std");
const Foo = struct { a: u8, b: u8 };

test {
    var a = Foo{ .a = 1, .b = 2 };
    var b = Foo{ .a = 3, .b = 4 };
    inline for (comptime std.meta.fieldNames(@TypeOf(a))) |name| {
        @field(a, name) = @field(b, name);
    }
}
```

While both of the above approaches work, it is non-intuitive that the most direct approach does not. The [language documentation](https://ziglang.org/documentation/master/#inline-for) says:

> It is recommended to use inline loops only for one of these reasons:
>
> - **You need the loop to execute at comptime for the semantics to work.**
> - You have a benchmark to prove that forcibly unrolling the loop in this way is measurably faster.

From the part I bolded I would expect that the original snippet to work.

### Actual Behavior

```
./foo.zig:7:51: error: cannot store runtime value in compile time variable
    inline for (std.meta.fieldNames(@TypeOf(a))) |name| {
 ```

**Comment by matu3ba** [comment] 2021-11-29 10:41
In your example `a` is a runtime value.
You expect Zig to silently insert an additional `comptime` variable for the `inline for`/`inline while`, which goes against the Zen of Zig to make intent explicit.
Further more its less good for code review to have (long) loop invariants inside the loop or to mix comptime and runtime semantics.

Accepting something along #8019 (only runtime values) still requires to be explicit about variable instantiation.

**Comment by SpexGuy** [comment] 2021-11-29 15:53
This is probably not a bug, but not for any of the reasons given above.  There are several precedents for this sort of implied comptime in stage 2.

The actual problem here is that `inline for` works on runtime known values, as long as the length is comptime known.  You can do `inline for (some_tuple)`, for example, even if the tuple has runtime fields.  Same with arrays of known lengths. The loop will be unrolled but the value will be runtime known.  We could maybe force comptime only if the type does not have known length, but this would be very difficult to spec because type resolution and comptime execution happen in a single pass.  So for simplicity, we cannot put an implicit comptime here.

---

Re: the above arguments,

> `a` is a runtime value.

This doesn't matter, `@TypeOf(a)` is still a comptime known expression.  If the loop condition used `a` directly, it would be a compile error.  The compiler would never magically convert variables to `comptime var`.

> Further more its less good for code review [...] to mix comptime and runtime semantics.

Mixing comptime and runtime semantics is the explicit purpose of `inline for`, it's not really a big leap.

---

**Comment by scheibo** [comment] 2021-11-29 20:47
Hey, thanks for the responses. When [I had asked this in #zig-help](https://discord.com/channels/605571803288698900/605572581046747136/914354526625103942) there were other similarly confused parties, so I think at the very least this is a documentation gap here to address? 

I think the 'gotcha' here really comes down to ` inline for (std.meta.fields(@TypeOf(a))) |field| {` working and `  inline for (std.meta.fieldNames(@TypeOf(a))) |field| {` *not* working, even though `fieldNames` is defined in terms of the former to begin with. Logically, a comptime transformation (`fields`-> `fieldNames`) that occurs over comptime values really seems like it should work (I also think the idea that we are attempting to "store runtime value in compile time variable" is misleading, because AIUI the field names of a strict are in-fact comptime? I'm not sure how it would be possible to add additional fields to a struct at runtime.

**Comment by SpexGuy** [comment] 2021-11-29 21:01
I think the problem here will be fixed once we have a way to annotate `std.meta.fieldNames` as `callconv(.Comptime)` or `inline` (by stage 2's definition of inline, where comptime known results are comptime known at the call site).  With either of those, `std.meta.fieldNames` will always return a comptime known value.

**Closed** 2021-11-29 21:28 UTC
Labels: question
