### ISSUE TITLE
`addDepFileOutputArg()` doesn't work

### ISSUE THREAD

**Issue by tristan957** [ziglang/zig#18398] opened 2023-12-29 06:00 UTC
### Zig Version

0.12.0-dev.1802+56deb5b05

### Steps to Reproduce and Observed Behavior

Call `addDepFileOutputArg()` in a `build.zig` file.

Here is the generated error:

```
/home/tristan957/Projects/ghostty/build.zig:439:42: error: type '[]const u8' does not support struct initialization syntax
            gresources.addOutputFileArg(.{ .generated = b.fmt("{}/ghostty-resources.h", wf.getDirectory()) });
                                        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    runBuild__anon_6876: /home/tristan957/.opt/zig/lib/std/Build.zig:1883:37
    steps__anon_6672: /home/tristan957/.opt/zig/lib/build_runner.zig:969:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/home/tristan957/.opt/zig/lib/std/Build/Step/Run.zig:246:44: error: expected type 'Build.LazyPath', found 'void'
    return self.addPrefixedDepFileOutputArg("", basename);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/home/tristan957/.opt/zig/lib/std/Build.zig:1916:22: note: union declared here
pub const LazyPath = union(enum) {
                     ^~~~~
/home/tristan957/.opt/zig/lib/std/Build/Step/Run.zig:245:71: note: function return type declared here
pub fn addDepFileOutputArg(self: *Run, basename: []const u8) std.Build.LazyPath {
                                                             ~~~~~~~~~^~~~~~~~~
/home/tristan957/.opt/zig/lib/std/fmt.zig:87:9: error: expected tuple or struct argument, found Build.LazyPath
        @compileError("expected tuple or struct argument, found " ++ @typeName(ArgsType));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tristan957/.opt/zig/lib/std/fmt.zig:87:9: error: expected tuple or struct argument, found Build.LazyPath
        @compileError("expected tuple or struct argument, found " ++ @typeName(ArgsType));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Looking at the code in the repo, it is obvious the what the error is:

https://github.com/ziglang/zig/blob/b0dba4680012e47ffc99f87bab4b53a976cb8b8e/lib/std/Build/Step/Run.zig#L242-L252

### Expected Behavior

Not generate a compile error.

**Comment by andrewrk** [comment] 2024-01-03 21:24
Duplicate of #18259, fixed landed in f64205b4456a81229886019e3621132ae150e053.

**Closed by andrewrk** 2024-01-03 21:24 UTC
Labels: bug, standard library, zig build system
