### ISSUE TITLE
if/else if/else chain inside std.debug.warn causes panic in codegen.cpp

### ISSUE THREAD

**Issue by nmichaels** [ziglang/zig#6302] opened 2020-09-09 21:24 UTC
```zig
fn problem(a: bool, b: bool) void {
    std.debug.warn("{}\n", .{if (a) true else if (b) true else false});
}
```

Calling the above function gives this result:

> $ zig build run
> when analyzing /home/me/zig/bug/src/main.zig:4:47 in compiler source at /home/me/zig/zig/src/codegen.cpp:1814: assertion failed. This is a bug in the Zig compiler.
> /home/me/zig/zig/src-self-hosted/stage2.zig:36:5: 0x55af9678f72c in stage2_panic (zigstage2)
>     @panic(ptr[0..len]);
>     ^
> /home/me/zig/zig/src/analyze.cpp:9507:17: 0x55af967625f6 in src_assert_impl (/home/me/zig/zig/src/analyze.cpp)
>     stage2_panic(msg, strlen(msg));
>                 ^
> /home/me/zig/zig/src/codegen.cpp:876:20: 0x55af9662e86d in ir_assert_impl (/home/me/zig/zig/src/codegen.cpp)
>     src_assert_impl(ok, source_instruction->base.source_node, file, line);
>                    ^
> /home/me/zig/zig/src/codegen.cpp:1814:9: 0x55af9663219e in ir_llvm_value (/home/me/zig/zig/src/codegen.cpp)
>         ir_assert(instruction->value->special != ConstValSpecialRuntime, instruction);
>         ^
> /home/me/zig/zig/src/codegen.cpp:3924:41: 0x55af9663aef8 in ir_render_store_ptr (/home/me/zig/zig/src/codegen.cpp)
>         LLVMValueRef ptr = ir_llvm_value(g, instruction->ptr);
>                                         ^
> /home/me/zig/zig/src/codegen.cpp:6716:39: 0x55af966468c2 in ir_render_instruction (/home/me/zig/zig/src/codegen.cpp)
>             return ir_render_store_ptr(g, executable, (IrInstGenStorePtr *)instruction);
>                                       ^
> /home/me/zig/zig/src/codegen.cpp:6892:60: 0x55af966472d3 in ir_render (/home/me/zig/zig/src/codegen.cpp)
>             instruction->llvm_value = ir_render_instruction(g, executable, instruction);
>                                                            ^
> /home/me/zig/zig/src/codegen.cpp:8287:18: 0x55af9664d62d in do_code_gen (/home/me/zig/zig/src/codegen.cpp)
>         ir_render(g, fn_table_entry);
>                  ^
> /home/me/zig/zig/src/codegen.cpp:11066:24: 0x55af96658a16 in codegen_build_and_link (/home/me/zig/zig/src/codegen.cpp)
>             do_code_gen(g);
>                        ^
> /home/me/zig/zig/src/main.cpp:1677:39: 0x55af966274ac in main0 (/home/me/zig/zig/src/main.cpp)
>                 codegen_build_and_link(g);
>                                       ^
> /home/me/zig/zig/src/main.cpp:1864:24: 0x55af96628000 in main (/home/me/zig/zig/src/main.cpp)
>     auto result = main0(argc, argv);
>                        ^
> bug...The following command terminated unexpectedly:
> /home/me/bin/zig build-exe /home/me/zig/bug/src/main.zig --cache-dir /home/me/zig/bug/zig-cache --name bug --cache on 
> 
> Build failed. The following command failed:
> /home/me/zig/bug/zig-cache/o/96Mpg4SQC3R2940VITVrfSFSeyRlmrhmchL9n5vmbAhQWdh-34mlYQCrVcp2fQSR/build /home/me/bin/zig /home/me/zig/bug /home/me/zig/bug/zig-cache run
> 

Found in 0.6.0 and 507416419be20661b4d6cb8f508071124b48a8c8

**Comment by travisstaloch** [comment] 2020-09-10 18:07
looks like a duplicate of #3882

**Comment by nmichaels** [comment] 2020-09-10 18:19
It does, though I couldn't reproduce 3882 in a recent build. This only failed with the `else if` bit in place.

**Closed** 2022-12-28 13:36 UTC
Labels: bug, stage1
