### ISSUE TITLE
No warning on returning pointer to stack

### ISSUE THREAD

**Issue by ellistg** [ziglang/zig#8198] opened 2021-03-10 12:22 UTC
Was writing some benchmarks the other day and made the mistake of returning a pointer to the stack, what I did specifically was create an array or random `u8`'s and attempted to  `return str[0..];`, I can see now that this is incorrect but seems like something that the compiler/debug mode should warn or error. 

Currently it returns the value but if you attempt to access it will just be random data. I don't know how possible this is and am fairly new to low level programming so it may just be something that is not worth having, but thought it was worth mentioning.

**Comment by Vexu** [comment] 2021-03-10 12:36
Duplicate of #2646.

**Closed by Vexu** 2021-03-10 12:36 UTC
