### ISSUE TITLE
false positive dependency loop when analyzing declaration TypeInfo prior to type constant

### ISSUE THREAD

**Issue by jessrud** [ziglang/zig#6066] opened 2020-08-16 11:08 UTC
```zig
pub const X = fn (*Y) void;
pub const Y = struct {
    x: X,
};

comptime {
    const decls = @typeInfo(@This()).Struct.decls;
    //_ = decls[0]; //triggered when uncommented.
    //_ = decls[1]; // ''
    _ = X;
    _ = Y;
    _ = decls[0];
    _ = decls[1];
}
```
when uncommented:
```
<source>:3:8: error: dependency loop detected
    x: X,
       ^
```

Ran into this running a test containing `refAllDecls(@This())` with similar (but seemingly valid) mutually dependent types.

**Comment by Vexu** [comment] 2020-08-16 11:21
Duplicate of #4476

**Closed by Vexu** 2020-08-16 11:21 UTC
