### ISSUE TITLE
Zig -> C ABI corrupt data bug

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#9487] opened 2021-07-30 06:03 UTC
LLVM IR: https://github.com/Jarred-Sumner/dump/raw/master/bug-extern-struct-undefined-memory.ll (warning: 178 MB)

When I return an `extern struct` containing other `extern struct` of a certain size from Zig to C, it sometimes is undefined memory. It sounds like an issue with calculating the sizes or alignment of the fields.

Notice how `bytecodecache_fd` has different values? It should be zero.

In Zig:
![image](https://user-images.githubusercontent.com/709451/127607313-8e44dc90-e4e0-4f94-a0b6-b0b4a0b9a0e5.png)

In C:
![image](https://user-images.githubusercontent.com/709451/127607303-8821114e-9c33-4a8e-80bc-d4bc9b31c2fc.png)

In the above case, `bytecodecache_fd` is defined as a `u32`.

If I change it to a `u64`, then it works as expected.

In C, after making `bytecodecache_fd` a `u64`.
![image](https://user-images.githubusercontent.com/709451/127607461-3a5bf051-dc52-4c39-87c1-3f4eeb19ef09.png)

Zig types:
```zig
pub fn Errorable(comptime Type: type) type {
    return extern struct {
        result: Result,
        success: bool,

        pub const Result = extern union {
            value: Type,
            err: ZigErrorType,
        };

        pub fn value(val: Type) @This() {
            return @This(){ .result = .{ .value = val }, .success = true };
        }

        pub fn ok(val: Type) @This() {
            return @This(){ .result = .{ .value = val }, .success = true };
        }

        threadlocal var err_buf: [4096]u8 = undefined;
        pub fn errFmt(code: anyerror, comptime fmt: []const u8, args: anytype) @This() {
            const message = std.fmt.bufPrint(&err_buf, fmt, args) catch @as([]const u8, @errorName(code)[0..]);

            return @call(.{ .modifier = .always_inline }, err, .{ code, message });
        }

        pub fn err(code: anyerror, msg: []const u8) @This() {
            return @This(){
                .result = .{
                    .err = .{
                        .code = ErrorCode.from(code),
                        .message = ZigString.init(msg),
                    },
                },
                .success = false,
            };
        }
    };
}
pub const ZigString = extern struct {
    ptr: [*]const u8,
    len: usize,
}
pub const ResolvedSource = extern struct {
    specifier: ZigString,
    source_code: ZigString,
    source_url: ZigString,
    hash: u32,

    // 0 means disabled
    bytecodecache_fd: u32,
};

pub const ErrorableResolvedSource = Errorable(ResolvedSource);
```

C types:
```c
typedef uint16_t ZigErrorCode;
typedef struct ZigErrorType {
  ZigErrorCode code;
  ZigString message;
} ZigErrorType;
typedef struct ZigString {
  const unsigned char *ptr;
  size_t len;
} ZigString;
typedef struct ResolvedSource {
  ZigString specifier;
  ZigString source_code;
  ZigString source_url;
  uint32_t hash;
  uint32_t bytecodecache_fd;
} ResolvedSource;
typedef union ErrorableResolvedSourceResult {
  ResolvedSource value;
  ZigErrorType err;
} ErrorableResolvedSourceResult;
typedef struct ErrorableResolvedSource {
  ErrorableResolvedSourceResult result;
  bool success;
} ErrorableResolvedSource;
```

**Comment by michal-z** [comment] 2021-07-30 14:28
I observe similar issue. Looks like Zig compiler does not set to 0 padding bytes in extern struct in some cases. My workaround is to zero a struct with std.mem.zeroes before use.

**Comment by floooh** [comment] 2021-08-11 11:26
@michal-z padding bytes aren't guaranteed to be zeroed in C either too though, for instance I've seen that initializing a struct with C99 designed init keeps random values in padding bytes (that's for instance why one should never use memcmp() for checking if two structs are equal, or use a hashing function over the "raw bytes" of a struct).

**Comment by michal-z** [comment] 2021-08-11 12:35
@floooh I see, thanks for the info. I was comparing Zig to designed init in C++20 where MSVC zeroes out padding bytes (I don't know if spec requires this though).

**Comment by floooh** [comment] 2021-08-11 12:44
Hmm interesting, it seems that clang also zeroes padding bytes, but gcc doesn't (unfortunately godbolt doesn't have an MSVC executor):

https://www.godbolt.org/z/v98xTzTMe

I'm pretty sure it's not guaranteed by the standard though, at least in C (don't know about C++).

**Comment by andrewrk** [comment] 2021-11-20 22:37
Duplicate of  #1481

I'll note that I implemented a more robust x86_64 C ABI system for self-hosted: https://github.com/ziglang/zig/blob/master/src/arch/x86_64/abi.zig#L30

This is something that could be backported to stage1 if someone was motivated to do it. Personally I will be focusing on getting self-hosted up to par instead.

**Closed by andrewrk** 2021-11-20 22:37 UTC
Labels: bug, stage1
