### ISSUE TITLE
Automatically compute comptime function arguments at compile-time?

### ISSUE THREAD

**Issue by jshholland** [ziglang/zig#7384] opened 2020-12-10 20:41 UTC
The following fails to compile:

```zig
const std = @import("std");

pub fn main() void {
    var arr = [_]u16{ 38, 283, 293, 2838, 1823, 183, 123, 23, 193, 949 };
    std.sort.sort(u16, &arr, {}, std.sort.asc(u16));
    for (arr) |n| std.debug.print("{}\n", .{n});
}
```

with the error:
```
./foo.zig:5:46: error: runtime value cannot be passed to comptime arg
    std.sort.sort(u16, &arr, {}, std.sort.asc(u16));
                                             ^
```

This is easily fixed by changing it to `comptime std.sort.asc(u16)`. But shouldn't the compiler know from the definition of `std.sort.sort`:
```
pub fn sort(
    comptime T: type,
    items: []T,
    context: anytype,
    comptime lessThan: fn (context: @TypeOf(context), lhs: T, rhs: T) bool,
) void {
```
that the `lessThan` argument is needed at comptime, and therefore evaluate it then without being explicit? Or is this an instance of "Communicate intent precisely" (or some other aspect of The Zen of Zig)? Note that I don't have to say `comptime u16`.

**Comment by jshholland** [comment] 2020-12-10 20:43
I'm not sure if this is related to #5672

**Comment by Vexu** [comment] 2020-12-10 20:48
Duplicate of #1708

**Closed by Vexu** 2020-12-10 20:48 UTC
