### ISSUE TITLE
Memory leak when running zig build test-cases

### ISSUE THREAD

**Issue by antlilja** [ziglang/zig#14269] opened 2023-01-11 18:15 UTC
### Zig Version

0.11.0-dev.1265+3ab43988c

### Steps to Reproduce and Observed Behavior

Arch Linux (x86_64)
LLVM version 15.06

Run ```zig build test-cases```

Result:
```
Test [1/87] test_0... [gpa] (err): memory address 0x7f52e89a85c0 leaked:
/home/anton/dev/zig/zig/src/Sema.zig:7136:47: 0xe4bfa8 in instantiateGenericCall (test)
        const new_module_func = try gpa.create(Module.Fn);
                                              ^
/home/anton/dev/zig/zig/src/Sema.zig:6399:40: 0xba90f0 in analyzeCall (test)
        if (sema.instantiateGenericCall(
                                       ^
/home/anton/dev/zig/zig/src/Sema.zig:6211:32: 0x8b4b53 in zirCall (test)
        return sema.analyzeCall(block, func, func_src, call_src, modifier, ensure_result_used, resolved_args, bound_arg_src);
                               ^
/home/anton/dev/zig/zig/src/Sema.zig:911:62: 0x772a09 in analyzeBodyInner (test)
            .call                         => try sema.zirCall(block, inst),
                                                             ^
/home/anton/dev/zig/zig/src/Sema.zig:5308:34: 0xbe35f5 in resolveBlockBody (test)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/anton/dev/zig/zig/src/Sema.zig:5291:85: 0x9605b1 in zirBlock (test)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                                                                    ^
/home/anton/dev/zig/zig/src/Sema.zig:1446:69: 0x780b17 in analyzeBodyInner (test)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/anton/dev/zig/zig/src/Sema.zig:793:30: 0x88235b in analyzeBody (test)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {

... Many identical leaks

All 87 tests passed.
87 errors were logged.
1 tests leaked memory.
```

### Expected Behavior

All tests pass

**Comment by Vexu** [comment] 2023-01-11 19:09
Duplicate of #14193

**Closed by Vexu** 2023-01-11 19:09 UTC
Labels: bug

**Comment by antlilja** [comment] 2023-01-11 19:43
> Duplicate of #14193

Oops sorry totally missed that issue
