### ISSUE TITLE
Improve semantics of function-level `comptime` blocks

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#14536] opened 2023-02-04 00:18 UTC
Currently, `comptime` blocks within functions and tests have confusing semantics where they don't *actually* force evaluation of statements at compile-time. For instance, the following code works fine:
```zig
pub fn main() void {
    var x: u8 = 0;
    std.log.info("{}", .{x});
    comptime {
        x = 42;
    }
    std.log.info("{}", .{x});
}
```
This outputs `0`, followed by `42`. (Checking with godbolt confirms the local variable is genuinely being assigned, rather than `x` being treated as a `comptime var` or something weird like that.)

These semantics are confusing because they mean effects you are trying to guarantee occur at comptime may very well not. The language reference doesn't actually seem to describe `comptime` blocks, but this does *technically* line up with its description of `comptime` expressions (we don't create any `var`s, run any loops, or call any functions, so by a strict reading of the language reference, the block gives no guarantees!), so it's not clear whether or not these semantics are intentional.

It seems much simpler and more logical for `comptime` blocks to instead fully force evaluation of their contents at compile time. Put differently, ignoring issues of scoping, a block `comptime { <statements> }` should be precisely equivalent to the call `comptime foo();` where the body of `foo` contains `<statements>`. This would make them better line up with `comptime` blocks at container-level, which guarantee *full evaluation* of their contents at compile-time.

I tried to flesh this proposal out more, but really there's nothing else to say - the current semantics seem confusing and entirely pointless, and making the blocks evaluate their entire body at comptime is the obvious solution.

**Comment by r00ster91** [comment] 2023-02-04 11:44
I think although confusing it is behaving as expected because I think what it does is it's forcing the result of the block to be void at comptime, disregarding anything in the block.
This is similar to how you can initialize void values like `var x: void = { std.debug.print("hello", .{}) };` etc. Not saying that we couldn't still change the semantics of this.

**Comment by mlugg** [comment] 2023-02-04 14:14
> I think although confusing it is behaving as expected because I think what it does is it's forcing the result of the block to be void at comptime, disregarding anything in the block.

I'm not sure where you got that notion from, but it's verifiably not true. For instance, `comptime { foo(); }` (at function scope) calls the function `foo` entirely at compile-time:
```zig
var x: u32 = 0;
fn foo() void {
    x = 1;
}
pub fn main() void {
    comptime {
        foo();
    }
}
// test.zig:3:7: error: unable to evaluate comptime expression
//     x = 1;
//     ~~^~~
// test.zig:3:5: note: operation is runtime due to this operand
//     x = 1;
//     ^
// test.zig:7:12: note: called from here
//         foo();
//         ~~~^~
```

Unlabelled blocks, by definition, always have a result type of `void`, so there's nothing to "guarantee" here.

**Comment by r00ster91** [comment] 2023-02-04 14:24
I agree that is quite inconsistent and your original code example should probably throw a compile error.

**Comment by Vexu** [comment] 2023-02-07 12:58
Duplicate of #7056

**Closed by Vexu** 2023-02-07 12:58 UTC
