### ISSUE TITLE
Compiler crashes in sliceAsBytes

### ISSUE THREAD

**Issue by eatonphil** [ziglang/zig#13471] opened 2022-11-07 02:02 UTC
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

Grab Zig 0.10.0, copy this program into crash.zig:

```zig
const std = @import("std");

fn ownZeroString(zstr: [*:0]u8) []u8 {
    var spanned = std.mem.span(zstr);
    const result = std.heap.c_allocator.alloc(u8, spanned.len) catch unreachable;
    std.mem.copy(u8, result, spanned);
    std.heap.c_allocator.free(zstr);
    return result;
}

pub fn main() void {
    var err: ?[*:0]u8 = null;
    if (err) |errStr| {
        var x = ownZeroString(errStr);
        _ = x;
    }
}
```

And build:

```
$ zig build-exe crash.zig
crash.zig:11:5: error: TODO call isNull and invert the result
pub fn main() void {
~~~~^~~~~~~~~~~~~~
/Users/phil/vendor/zig/zig-out/lib/zig/std/heap.zig:99:5: error: TODO call isNull and invert the result
    fn alloc(
    ^~
/Users/phil/vendor/zig/zig-out/lib/zig/std/heap.zig:125:5: error: TODO implement wrap optional for target.Target.Cpu.Arch.aarch64
    fn resize(
    ^~
/Users/phil/vendor/zig/zig-out/lib/zig/std/mem/Allocator.zig:193:5: error: TODO implement airRetAddr for aarch64
pub fn alloc(self: Allocator, comptime T: type, n: usize) Error![]T {
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/phil/vendor/zig/zig-out/lib/zig/std/mem.zig:3456:9: error: expected []T or *[_]T, passed [*:0]u8
        @compileError("expected []T or *[_]T, passed " ++ @typeName(sliceType));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/phil/vendor/zig/zig-out/lib/zig/std/mem.zig:3463:59: note: called from here
pub fn sliceAsBytes(slice: anytype) SliceAsBytesReturnType(@TypeOf(slice)) {
                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
thread 1908531 panic: Zig compiler bug: attempted to destroy declaration with an attached error
Analyzing /Users/phil/vendor/zig/zig-out/lib/zig/std/mem/Allocator.zig: mem/Allocator.zig:free__anon_1566
      %2395 = dbg_block_begin()
      %2396 = dbg_stmt(2, 5)
      %2397 = typeof_builtin({
        %2398 = break_inline(%2397, %2393)
      }) node_offset:488:29 to :488:44
      %2399 = type_info(%2397) node_offset:488:19 to :488:45
      %2400 = field_val(%2399, "Pointer") node_offset:488:19 to :488:53
      %2401 = dbg_var_val(%2400, "Slice")
      %2402 = save_err_ret_index(%2400)
      %2403 = dbg_stmt(3, 5)
      %2405 = decl_ref("mem") token_offset:489:19 to :489:22
      %2406 = field_call_bind(%2405, "sliceAsBytes") node_offset:489:19 to :489:35
      %2407 = dbg_stmt(3, 35)
    > %2408 = call(.auto, %2406, [
        {
          %2409 = break_inline(%2408, %2393)
        },
      ]) node_offset:489:19 to :489:43
      %2411 = save_err_ret_index(%2408)
      %2412 = dbg_var_val(%2408, "bytes")
      %2413 = dbg_stmt(4, 5)
      %2414 = field_val(%2408, "len") node_offset:490:23 to :490:32
      %2420 = block({
        %2415 = dbg_stmt(4, 39)
        %2416 = field_val(%2400, "sentinel") node_offset:490:39 to :490:53
        %2417 = cmp_neq(%2416, @Zir.Inst.Ref.null_value) node_offset:490:39 to :490:61
        %2418 = as_node(@Zir.Inst.Ref.bool_type, %2417) node_offset:490:39 to :490:61
        %2419 = condbr(%2418, {
          %2421 = dbg_block_begin()
          %2422 = field_val(%2400, "child") node_offset:490:71 to :490:82
          %2424 = dbg_block_end()
          %2423 = size_of(%2422) node_offset:490:63 to :490:83
          %2426 = break(%2420, %2423)
        }, {
          %2427 = break(%2420, @Zir.Inst.Ref.zero)
        }) node_offset:490:35 to :490:90
      }) node_offset:490:35 to :490:90
      %2428 = add(%2414, %2420) node_offset:490:23 to :490:90
      %2429 = dbg_var_val(%2428, "bytes_len")
      %2430 = dbg_stmt(5, 9)
      %2434 = block({
        %2431 = cmp_eq(%2428, @Zir.Inst.Ref.zero) node_offset:491:9 to :491:23
        %2432 = as_node(@Zir.Inst.Ref.bool_type, %2431) node_offset:491:9 to :491:23
        %2433 = condbr(%2432, {
          %2435 = dbg_block_begin()
          %2436 = dbg_stmt(5, 25)
          %2437 = restore_err_ret_index(@Zir.Inst.Ref.none, @Zir.Inst.Ref.none)
          %2439 = dbg_block_end()
          %2438 = ret_node(@Zir.Inst.Ref.void_value) node_offset:491:25 to :491:31
        }, {
          %2440 = break(%2434, @Zir.Inst.Ref.void_value)
        }) node_offset:491:5 to :491:31
      }) node_offset:491:5 to :491:31
      %2441 = ensure_result_used(%2434) node_offset:491:5 to :491:31
      %2442 = dbg_stmt(6, 5)
      %2443 = ptr_type(@Zir.Inst.Ref.u8_type, Many) node_offset:492:37 to :492:42
      %2444 = field_val(%2408, "ptr") node_offset:492:54 to :492:63
      %2445 = ptr_to_int(%2444) node_offset:492:44 to :492:64
      %2446 = int_to_ptr(%2443, %2445) node_offset:492:27 to :492:65
      %2455 = ref(%2446) token_offset:495:18 to :495:31
      %2447 = dbg_var_val(%2446, "non_const_ptr")
      %2448 = dbg_stmt(8, 5)
      %2449 = memset(%2446, @Zir.Inst.Ref.undef, %2428) node_offset:494:5 to :494:49
      %2450 = dbg_stmt(9, 5)
      %2451 = ref(%2392) token_offset:495:5 to :495:9
      %2452 = field_call_bind(%2451, "rawFree") node_offset:495:5 to :495:17
      %2453 = dbg_stmt(9, 17)
      %2462 = dbg_block_end()
      %2454 = call(nodiscard .auto, %2452, [
        {
          %2456 = slice_end(%2455, @Zir.Inst.Ref.zero, %2428) node_offset:495:18 to :495:45
          %2457 = break_inline(%2454, %2456)
        },
        {
          %2458 = field_val(%2400, "alignment") node_offset:495:47 to :495:62
          %2459 = break_inline(%2454, %2458)
        },
        {
          %2460 = extended(ret_addr()) node_offset:495:64 to :495:80
          %2461 = break_inline(%2454, %2460)
        },
      ]) node_offset:495:5 to :495:81
      %2463 = restore_err_ret_index(%2394, @Zir.Inst.Ref.none)
      %2464 = break(%2394, @Zir.Inst.Ref.void_value)
    For full context, use the command
      zig ast-check -t /Users/phil/vendor/zig/zig-out/lib/zig/std/mem/Allocator.zig

  in /Users/phil/vendor/zig/zig-out/lib/zig/std/mem/Allocator.zig: mem/Allocator.zig:free__anon_1566
    > %2394 = block({%2395..%2464}) node_offset:487:52 to :487:53

/Users/phil/vendor/zig/src/Module.zig:3493:13: 0x1028f581f in destroyDecl (zig)
            @panic("Zig compiler bug: attempted to destroy declaration with an attached error");
            ^
/Users/phil/vendor/zig/src/Sema.zig:6935:33: 0x10341ee8b in instantiateGenericCall (zig)
        errdefer mod.destroyDecl(new_decl_index);
                                ^
/Users/phil/vendor/zig/src/Sema.zig:6237:40: 0x1031edcd7 in analyzeCall (zig)
        if (sema.instantiateGenericCall(
                                       ^
/Users/phil/vendor/zig/src/Sema.zig:6049:32: 0x102f37b4f in zirCall (zig)
        return sema.analyzeCall(block, func, func_src, call_src, modifier, ensure_result_used, resolved_args, bound_arg_src);
                               ^
/Users/phil/vendor/zig/src/Sema.zig:820:62: 0x102cadc3b in analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst),
                                                             ^
/Users/phil/vendor/zig/src/Sema.zig:5149:34: 0x103224b5f in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/Users/phil/vendor/zig/src/Sema.zig:5132:33: 0x102fe2537 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/Users/phil/vendor/zig/src/Sema.zig:1353:69: 0x102cbdcf3 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/Users/phil/vendor/zig/src/Sema.zig:704:30: 0x102cac1f3 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/Users/phil/vendor/zig/src/Module.zig:5656:21: 0x102b41c43 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/Users/phil/vendor/zig/src/Module.zig:4344:40: 0x1029eb677 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/Users/phil/vendor/zig/src/Compilation.zig:3065:42: 0x1029e9633 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/Users/phil/vendor/zig/src/Compilation.zig:3003:30: 0x10293405f in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/Users/phil/vendor/zig/src/Compilation.zig:2331:31: 0x102930587 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/Users/phil/vendor/zig/src/main.zig:3337:20: 0x10295b2b3 in updateModule (zig)
    try comp.update();
                   ^
/Users/phil/vendor/zig/src/main.zig:3008:17: 0x10285225b in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/Users/phil/vendor/zig/src/main.zig:230:31: 0x10282a983 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/Users/phil/vendor/zig/src/main.zig:174:20: 0x10282a0a3 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/phil/vendor/zig-0.10.0/lib/std/start.zig:606:37: 0x10282c3e3 in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x104ec508b in ??? (???)
???:?:?: 0xd56affffffffffff in ??? (???)
[1]    31724 abort      ./zig-out/bin/zig build-exe crash.zig
```

### Expected Behavior

I assume there's a bug in my code as well. But the compiler shouldn't crash either. It should tell me what I did wrong.

**Comment by eatonphil** [comment] 2022-11-07 02:04
I don't understand the bug, so feel free to rename this issue with a better name, or close it if it's already a known issue!

**Comment by nektro** [comment] 2022-11-07 04:47
likely duplicate of https://github.com/ziglang/zig/issues/12927

**Comment by Vexu** [comment] 2022-11-07 12:08
> I assume there's a bug in my code as well. But the compiler shouldn't crash either. It should tell me what I did wrong.

It did tell you what you did wrong:
```
/Users/phil/vendor/zig/zig-out/lib/zig/std/mem.zig:3456:9: error: expected []T or *[_]T, passed [*:0]u8
        @compileError("expected []T or *[_]T, passed " ++ @typeName(sliceType));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/phil/vendor/zig/zig-out/lib/zig/std/mem.zig:3463:59: note: called from here
pub fn sliceAsBytes(slice: anytype) SliceAsBytesReturnType(@TypeOf(slice)) {
                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```

Obviously the compiler shouldn't panic but that panic was placed there intentionally as we were unable to fix the underlying issue (#12927) in time.

**Closed by Vexu** 2022-11-07 12:08 UTC
Labels: bug

**Comment by eatonphil** [comment] 2022-11-07 16:05
> It did tell you what you did wrong:

It did, but it didn't say *where*.

**Comment by EnderKilledYou** [comment] 2023-06-14 09:10
I can reproduce. 

`pub const EnvValue = struct {
    const Self = @This();
    value: *[]u8 = undefined, //reuse stack buffer for speed`
`

`     pub fn free_value(self: *Self) void {
            self.allocator.*.free(self.value);
           //should be             self.allocator.*.free(self.value.*);

        }
`
