### ISSUE TITLE
Assertion failed when passing a [:0]const u8 to a [*:0]const u8 parameter

### ISSUE THREAD

**Issue by xackus** [ziglang/zig#7464] opened 2020-12-16 15:10 UTC
```zig
fn fun(cstr: [*:0]const u8) void {}

pub fn main() !void {
    var slice: []const u8 = "test\x00";

    fun(slice[0..:0]);
}
```

```
Semantic Analysis [754/913] when analyzing main.zig:8:14 in compiler source at zig/src/stage1/codegen.cpp:1792: assertion failed. This is a bug in the Zig compiler.
```

This doesn't trip:
```zig
fn fun(cstr: [*:0]const u8) void {}

pub fn main() !void {
    var slice: []const u8 = "test\x00";
    var slice2 = slice[0..:0];
    fun(slice2);
}
```

**Comment by Vexu** [comment] 2020-12-17 15:57
Duplicate of  #4423.

**Closed by Vexu** 2020-12-17 15:57 UTC
