### ISSUE TITLE
make `packed struct` always use a single backing integer, inferring it if not explicitly provided

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#10113] opened 2021-11-07 11:21 UTC
So, everyone knows the problems we have with `packed structs`. Some are implementation problems, but we also have a huge problem with *not* having a proper specification on how they should work at all, except for "zero padding".

So i want to propose a definition for `packed struct`s that is easy to understand and implement.

Let's consider this code example:
```zig
const T = packed struct {
    a: u4,
    b: u4,
};

var bits = [_]u8 { 0x01 };
var t = @bitCast(T, bits);

std.debug.print("{}\n", .{ t });
```
What do you expect it to print?  
Is it `T{ .a = 1, .b = 0 }`? Then you have assumed a little-endian platform, as on big endian, it will print `T{ .a = 0, .b = 1 }`.  
[Check it out on Compiler Explorer](https://godbolt.org/z/GnW73hj9x).

Personally, i find this confusing, thus i propose:

A packed struct will have a similar semantic as a unsigned integer with the same amount of bits. Each field is considered an unsigned integer of the same amount of bits.

To explain the idea, we have this struct:
```zig
const T1 = packed struct { // u8
  a: u4, // occupies bits 0..3
  b: u4, // occupies bits 4..7
};

const T2 = packed struct { // u32
  a: u4, // occupies bits 0..3 in our u32
  b: u3, // occupies bits 4..6 in our u32
  c: u25, // occupies bits 7..31 in our u32
};
```

So the packed struct implements exactly what we would do in a language without packed structs:
```zig
var value: T2 = …;
var a = @truncate( u4, 0x0000000F & (value >> 0));
var b = @truncate( u3, 0x00000007 & (value >> 4));
var c = @truncate(u25, 0x01FFFFFF & (value >> 7));
```

This means that we have a predictable model for backed structs and in case of `T2`, we can reason about it:
```
const integer: u32 = 0x165652B6;
const value = @bitCast(T2, integer);
std.debug.assert(value.a == 6);
std.debug.assert(value.b == 3);
std.debug.assert(value.c == 0x2CACA5);
```

This will be true for both little and big endian hardware, so it will do what we expect, even if the bytes on disk have a different order.  
If a known byte order is required, we can use `std.mem.writeIntLittle`, `@byteSwap` and others.

In addition, we can declare a struct as `packed struct(u32)`, which will enforce the struct size to 32 bit, and we will get a compiler error if it isn't the case.

This will also guarantee that this struct is handled as a `u32` and can be used as such, similar to enums. This also guarantees that loads and stores will not be sliced into more than one access if possible and allows atomic load/store for such packed structs. (See #5049).

What needs to be clarified:
- How to handle floats ([float endianess is a thing](https://en.wikipedia.org/wiki/Endianness#Floating_point))
- How to handle pointers in a packed struct
- How to handle pointers to struct fields

Related issues:
- #3133
- #2627
- #5049

Regards
- xq

**Comment by praschke** [comment] 2021-11-07 12:28
as a weak usecase (weak because this could just be a quirk of X11), the X protocol embeds bitmasks in u16 and u32 fields whose layout is dependent on the byte-order specified by the client in the protocol setup. i don't know if the preferred representation for bitmasks is defining a bunch of `1 << n` constants, or packed structs, but to express these elements with packed structs i would have to define two different sets.

it's not super terrible, but having packed structs act however shifts act on the target architecture seems more correct to me.

**Comment by zzyxyzz** [comment] 2021-11-07 13:06
The `packed struct { a: u4, b: u4 }` example could be a compiler bug. Endianness determines the *byte* order only, while the *bit* order within a single byte is entirely up to the compiler and can be made consistent across all platforms.

That said, it's true that endianness is a problem for packed structs. However, enforcing a single consistent endianness is not a costless action. For example, if you have
```zig
const Vec3 = packed struct {
    x: i32,
    y: i32,
    z: i32,
};
```
then with this proposal every field access would require byte order conversion on big-endian platforms.

Ultimately, the problem is that packed structs are used for two different purposes:
1. As an ordinary struct, but with defined field order and no extra padding.
2. As a bit-for-bit data serialization format.

Ideally, we would have two different struct types to match the different use cases. Maybe something like `serialized struct {}`. Or even `struct {}` vs `struct(.Packed) {}` vs `struct(.Serialized) {}`.

**Comment by MasterQ32** [comment] 2021-11-07 13:19
> then with this proposal every field access would require byte order conversion on big-endian platforms.

No, it would not. `y` would still allocate bits 32…64 in the packed struct, which can be extracted by "bitshifting". There is no endianess encoding in that, but only bit offsets in a larger "integer". This means that reading `z` on a big-endian platform will read from byte offset 0, while reading `z` on a little-endian platfrom will read from byte-offset 8. They are *not* layed out consecutively in memory as it is now.

So *As an ordinary struct, but with defined field order and no extra padding.* will be true, but the field order will be swapped in memory for big-endian platforms.

Imho, the use cases are:
- Reflection of hardware registers (where we need `packed struct(u32)`)
- Compression of in-memory structures (where the memory layout is completly irrelevant)
- Serialization data (where one might still apply manual byte order swapping)

Only the last use case requires the use of extra work for handling endianess, but this is relevant in any case, as file formats, network protocols and such all need to define a byte order and using `packed structs` aren't the right tool in most cases here anyways

**Comment by SpexGuy** [comment] 2021-11-07 13:44
What happens with a very large packed struct? (Over 65536 bits).  Is it still built like one giant integer, laid out in reverse field order on big endian?  Also what about npot sizes (like 24 bits)?  Does that round up to 32 or end at 24?

**Comment by zzyxyzz** [comment] 2021-11-07 14:00
@MasterQ32,
Sorry, I misunderstood that part. Maybe because I wouldn't ever expect a "packed" struct to have its field order reversed on some platforms. :smile:

Also, correct me if I'm wrong, but wouldn't this convention make packed structs useless for parsing binary data? Or at least you would have to always define two structs with fields A, B, C and C, B, A respectively, and then use the appropriate struct depending on platform endianness?

**Comment by MasterQ32** [comment] 2021-11-07 14:32
> What happens with a very large packed struct? (Over 65536 bits). Is it still built like one giant integer, laid out in reverse field order on big endian?

The integer layout is only a mental layout, how access is implemented for non-integer backed structs isn't defined. So yeah, for huge big-endian structs, the order would still be "reverse" to allow efficient access of parts.

> Also what about npot sizes (like 24 bits)? Does that round up to 32 or end at 24?

It will be the same as `u24`, so in a normal struct, it will take up 3 byte aligned to 4, and in a packed struct, it will take exactly 24 bit

**Comment by N00byEdge** [comment] 2021-11-07 14:48
There are many more things you have to consider when working with packed structs. Usually bitfields are used together with mmio. There you have more issues than just the bit order. It has concepts of such things like access/registers sizes. I'm not sure if packed structs should have all of these covered. I have written [a little library](https://github.com/FlorenceOS/Florence/blob/master/lib/util/bitfields.zig) for working with mmio registers which specify bit offsets of fields, while still encompassing them within a register with a certain access/register size something like this:
```zig
    command_status: extern union {
        raw: u32,

        start: bf.Boolean(u32, 0),
        recv_enable: bf.Boolean(u32, 4),
        fis_recv_running: bf.Boolean(u32, 14),
        command_list_running: bf.Boolean(u32, 15),
    },
    ```
    Here each bit offset is explicitly noted, which I believe is going to be desired when you want to deal with these kinds of layouts anyways. The only thing I'm missing is some kind of way of getting rid of the repeated register type/size.
    
    I think the goal for MMIO related structs should either be provided as a library solution like above, or at least something with a similar syntax (but hopefully without the repeated type) `register struct`?

**Comment by MasterQ32** [comment] 2021-11-07 14:50
>  There you have more issues than just the bit order. It has concepts of such things like access/registers sizes. 

I know, this is covered by the integer-backed struct, that will be handled like the integer you base it on. See #5049 for a wider discussion of this topic

**Comment by N00byEdge** [comment] 2021-11-07 14:50
Oh, I see. Yes that encompasses exactly what I was trying to say here. Nevermind my comment.

**Comment by DanB91** [comment] 2021-11-28 20:10
To build on this, I currently (and very carefully) use packed structs to represent bit fields in MMIO hardware registers.  It'd be nice if we can actually specify the backing register size.  so something like this:
```
const T1 = packed struct(Type) {
  a: u4, // occupies bits 0..3
  b: u4, // occupies bits 4..7
};
```
Where `Type` must be a standard unsigned type that is a byte multiple (e.g. `u8`, `u16`, etc).  In this case it would be `u8`  And on top of that, if the sum of the bits don't equal the backing type, you get a compile error (not sure if this would be too much).

This doesn't clarify the 3 points (handling floats, etc) in the original post, so not sure if this would conflict with them.  Maybe I'm asking for a completely different structure type here?  Like instead of `packed struct` what I'm asking for should be called `bitfield`?

**Comment by SpexGuy** [comment] 2021-11-29 00:06
@DanB91 you might be interested in #5049 😉

**Comment by DanB91** [comment] 2021-11-29 04:56
> @DanB91 you might be interested in #5049 😉

Oh man, this proposal is exactly what I was thinking, thanks!

**Comment by topolarity** [comment] 2022-02-11 22:53
What's the plan of action for arrays? Will these be stored in "big-endian" order, and then Zig will prevent casting any pointers to normal "little-endian"-ordered arrays?

**Comment by topolarity** [comment] 2022-02-14 06:44
A few options I can imagine would be:
  1. Prohibit arrays within `packed struct` entirely
  2. Order arrays within packed structs in reverse order. Use an offset-encoded pointer or similar to prevent casting to a standard-order array pointer
  3. Add a stride to arrays/pointers. Use a negative stride for reverse-order arrays

**Comment by zzyxyzz** [comment] 2022-02-14 10:30
There is a fairly common situation where this proposal would increase awkwardness, namely if a binary data format specifies big-endian encoding for its integers (think network headers). Consider this example:
```zig
const X = packed struct {
    a: u16,
    b: u16,
    c: u32,
}
```
With normal field ordering, we have the following layouts:
```
[a1 a0 b1 b0 c3 c2 c1 c0]  // physical data layout per the standard
[a1 a0 b1 b0 c3 c2 c1 c0]  // struct X on big-endian platform
[a0 a1 b0 b1 c0 c1 c2 c3]  // struct X on little-endian platform
```
Thus, when parsing this format into the struct, a byte swap on the individual fields needs to be performed on an LE platform, and no action is necessary on BE.

With this proposal, the situation would change to:
```
[a1 a0 b1 b0 c3 c2 c1 c0]  // data format
[c3 c2 c1 c0 b1 b0 a1 a0]  // struct X on BE
[a0 a1 b0 b1 c0 c1 c2 c3]  // struct X on LE
```
Now *both* platforms need to perform a conversion. On little-endian it is still a per-field byte swap. But on big-endian we now need to reverse the order of fields without changing the fields themselves. If, on the other hand, the data format is little-endian, then no action is required on LE platforms and a whole-struct byte reversal is needed on BE. *Except* if the struct contains an array, as pointed out by @topolarity. Then we need to perform the big byte swap piecewise around the array(s), and also a per-element byte swap within the array, with the rules applying recursively if the elements are themselves packed structs.

Before, we had a problem with byte order. Now we have two problems.

**Comment by MasterQ32** [comment] 2022-02-14 10:47
> There is a fairly common situation where this proposal would increase awkwardness, namely if a binary data format specifies big-endian encoding for its integers (think network headers)

I disagree that using `packed struct` is the right choice here, due to several reasons:
- performance (accessing a u32 in a packed struct are pretty much always 4 byte reads as they can be unaligned)
- byte order (packed structs aren't portable anyways, so you have to either perform a byte swap on the underlying integer or a byte swap on each individual field depending on the platform)

We have the guarantee(?) that `TypeInfo.Struct.fields` is always in declared order, so you can easily build a serializer that reads/writes fields in order and performs byte swaps if necessary, taking no more time than reading a packed struct and performing all necessary byte swaps by hand.

**Comment by zzyxyzz** [comment] 2022-02-14 12:12
>> There is a fairly common situation where this proposal would increase awkwardness, namely if a binary data format specifies big-endian encoding for its integers (think network headers)

> I disagree that using packed struct is the right choice here, due to several reasons

That depends. When parsing binary formats (especially convoluted legacy formats), I think it's a fairly common pattern to read a certain number of bytes corresponding to a particular substructure, cast it to a packed struct, extract the information needed to find and interpret other substructures, and repeat. You should not be obliged to use a deserialization library to do that. Slicing and dicing data by hand should feel natural in a low-level language like Zig.

**Comment by ayende** [comment] 2022-02-14 12:34
FWIW, I'm using `packed struct` extensively for persistent and network data. That means that I expect to have 1:1 model from the struct definition to the memory representation. 

That means that `u32` in a `packed struct` is expected to be store in LE on LE systems and vice versa. If I need endianness support, I'll call byte swap directly myself.

**Comment by topolarity** [comment] 2022-02-14 19:28
Based on @zzyxyzz's point regarding serialization, it seems worth exploring what it would take to enforce a single ordering for packed fields across little- and big-endian systems. 

We could define the field ordering on big-endian systems to match the little-endian field ordering. 

Every packed field would need a well-defined `packed` representation (i.e. representation as a contiguous set of `@bitSizeOf` bits). The load sequence would be:
1. Perform a large, unaligned load
2. Slice out the `packed` representation (byteSwap + shift/mask)
3. Convert to the correct integer value, if needed

This comes with costs on BE systems, but it depends on the field type:
| Field | Extra Load/Store Ops |
| ------------- | ---------------------------- |
| Byte-aligned power-of-two integer  | None [^1]|
| Unaligned power-of-two integer  | (2x) `@byteSwap`|
| Not crossing a byte boundary  | None [^2] | 
| Smaller than a byte, crossing boundary  | `@byteSwap` [^3] | 
| Larger than a byte, NPOT  | Depends on `packed` representation | 

[^1]: Power-of-two integers already have a `packed` representation and require only standard byte-endian conversion. On big-endian systems, the "conversion" is included as part of the load, so no extra operations are needed.

[^2]: The load is just a single-byte load, no platform differences

[^3]: For integers smaller than a byte, their `packed` representation is just their serialized bytes. This requires no conversion, only slicing.

The hard cases are the >8-bit, NPOT integers like `u15`, `u24`, etc. I don't have a proposal for these, but it's useful to know that providing an efficient `packed` representation for these could make a standard field ordering possible.

**Comment by zzyxyzz** [comment] 2022-02-14 21:08
@topolarity
I would much prefer your solution. If I understand correctly, the rule is
1. For objects completely filling a byte-aligned region, the platform endianness applies.
2. For objects sharing bytes with other objects, endianness is not a well-defined concept anyway, so we simply say that bits are filled from least to most significant on all platforms. On BE platforms loads and stores to such fields *only* will require a byte swap in addition to the mask and shift operations. But such accesses are slow anyway so the overhead should be acceptable.

I admit this is less elegant than the original proposal, but I think that leaving the fields in the declared order more than makes up for that.

**Comment by topolarity** [comment] 2022-02-14 21:42
Yeah, that's a much simpler summary :-)

I hadn't thought to choose the `packed` representation based on the field alignment, but I like that solution a lot 👍 

Maybe a less implicit rule is that any manually aligned field (`align(1)` or greater) would be encoded in standard platform byte-order, while any other integer is encoded LSB to MSB (requiring at most an additional `byteSwap` to load/store)

**Comment by zzyxyzz** [comment] 2022-02-15 10:20
Upon reflection, the alignment-based solution is also far from ideal. Having the layout change because you're off by one bit is inelegant, not to mention a footgun. But I think we're trying to fit a round peg into a square hole here. Pretty much all the hairy problems and open questions are caused by bit granularity. Any rigorous solution I can think of severely interferes with the simplicity and usability of ordinary byte-packed structs, and vice versa. So how about this: We let packed structs be packed structs, and introduce a separate bitfield type with the semantics of the original proposal.

### Packed structs
* Fields are laid out sequentially and without padding, unless forced by an explicit alignment.
* Fields have platform-native endianness.
* **Fractional-byte fields are not allowed**, unless manually aligned/padded to whole bytes.
* Integer-backed packed structs facilitate register mapping and atomic operations. The backing integer mostly determines the size only. In cases where the struct needs to be treated as an actual integer, it has platform-native endianness, i.e., what you'd get by casting it to a byte array and then to the backing integer type.
* Field pointers, contained arrays, and conversions to and from byte arrays work exactly as you'd expect.
* Intended use cases:
    * Dense in-memory representation with reasonably efficient access
    * Serialization and deserialization

### Bit fields
* Syntax: `bitfield(u8) { a: u4, b: u4 }`, with the backing integer being optional.
* The bitfield is logically a single integer, with bits filled in order from least to most significant. On big-endian platforms this causes fields to be laid out backwards, and may require an end-to-end byte swap if a bitfield is used to parse binary data.
* To keep the semantics well defined, there are some restrictions on field types:
    * Integers (signed and unsigned) are allowed, along with Booleans and integer-backed structs and enums.
    * Bitfields are allowed.
    * Arrays are allowed, but have to follow the same layout rules as everything else, including byte-reversal on BE platforms.
    * Pointers are not allowed, due to platform-dependent size.
    * Floats are not allowed, due to inconsistent representation on some platforms.
    * Structs, enums and anything else that doesn't have a fixed representation is not allowed.
* Field pointers are not allowed unless someone works out how to handle them.
* The intended use cases are:
    * Bit sets and flag arrays
    * Maximum-density in-memory representation with slower access
    * Serialization and parsing of bit-packed binary data
* There are a lot of possibilities to add more bitfield-specific functionality in the future:
    * Support for logical operations, rotations, clz/ctz, etc.
    * Bit slicing, extraction, assignment.
    * Exact position specifiers (`bitfield { 0..4 => a: u4, ... }`).
    * And more. But this is out of scope for this proposal.

**Comment by topolarity** [comment] 2022-02-15 16:26
Yeah, all the existing proposals have some flaw (in terms of surprise, performance, etc.) by not allowing the user to be explicit about different representations across systems.

I'm not convinced it's the right solution, but if we are going to expose that representational complexity to the user, I'd prefer to just be able to override default platform ordering with an "endian(X)" tag.

For example:
- `endian(.Big) packed struct { ... }` affects field-, array-, and default byte-ordering of fields
-  `endian(.Big) u32` is the standard big-endian u32 representation
- `endian(.Little) u15` is serialized from LSB to MSB
- `endian(.Big) u15` is a compile-error

This is enough to get a well-defined serialized set of bits out of a packed struct, just by opting in with `endian(.Little) packed struct`

I'm not sure whether I like this any better, but at least the user maintains strong control, as well as good performance if the right representation is chosen (the platform default should always be good for perf)

**Comment by zzyxyzz** [comment] 2022-02-16 00:11
I'm also not sure I like this :). My main objection would be that defining a "normal" packed struct (i.e. with sequential layout and efficient access) gets a lot more verbose: 
```zig
// before:
const S1 = packed struct {
    a: u8,
    b: u8,
    c: u16,
    d: u32,
};

// after:
const native_endian = std.Target.current.cpu.arch.endian();
const S2 = endian(.Little) packed struct {
     a: endian(native_endian) u8,
     b: endian(native_endian) u8,
     c: endian(native_endian) u16,
     d: endian(native_endian) u32,
};
```
It's also not quite clear to me how this will work with fractional-byte fields.

BTW, I've found some old issues (#307, #649) where something similar was proposed, including a solution for pointers to non-byte-aligned fields (e.g., `&.Endian.Big :4 u4`). But apparently this didn't go anywhere.

**Comment by topolarity** [comment] 2022-02-16 03:24
Seems that the design space is well-explored at this point. Thanks for the references :)

As far as your proposal goes, I wonder if it would be well-served by this syntax:
- `struct(u32)` = an integer-backed packed struct
- `struct(align(1))` = a struct with fixed field order, min. alignment of 1 for all fields

The key constraint that makes things work out OK is that "struct(align(X))" does not allow a field alignment of less than one byte. 

`struct(u32)` is byte-order affected, because it "is" a u32. `struct(align(1))` is the same layout on all platforms, although its fields may have byte-order differences.

**Comment by MasterQ32** [comment] 2022-02-16 08:07
> The key constraint is that in a non-integer-backed `packed struct` any field that crosses a byte-boundary must occupy a byte-aligned region.

Can you explain the differece of `packed struct` to a `struct` with all fields `align(1)` then? Or is it just syntax sugar?

```zig
const Packed = extern struct {
    a: u32 align(1),
    b: u16 align(1),
    c: u32 align(1),
    d: u8 align(1),
    e: u64 align(1),
};
```

Because this use case is already supported. For me `packed struct` is always bit-packed, and thus has to be defined differently from `extern` structs which are byte packed

**Comment by topolarity** [comment] 2022-02-16 09:14
Two differences:
1. `packed struct` supports bit-packed fields which don't cross a byte boundary
2. `extern struct` is intended only to match the target C ABI. It's not clear to me that manually-aligned fields should actually be permitted, except to the extent they correctly imitate `alignas`, which does not support under-aligning

If we ignore any targets with exotic layout rules and the question of whether the described extern struct is compatible with the C ABI, then it's just sugar :-)

FWIW, your question makes me think that a theoretical `align(0)` directive could be useful to request bit-packing even in a normal `struct` - I can't see any problems with that, other than the usual limitations with bit-packed fields

**Comment by topolarity** [comment] 2022-02-16 17:37
To provide a concrete example, consider a very similar-looking C11 struct:
```c
typedef struct {
    alignas(1) uint32_t a;  // keeps natural alignment - alignas has no effect
    alignas(1) uint16_t b;  // keeps natural alignment - alignas has no effect
    alignas(1) uint32_t c;  // keeps natural alignment - alignas has no effect
    alignas(1) uint8_t d;   // keeps natural alignment - alignas has no effect
    alignas(1) uint64_t e;  // keeps natural alignment - alignas has no effect
} Packed;
```

This is _guaranteed_ to have a different layout than your `Packed` struct above, since `alignas` has no effect if it would weaken a type's natural alignment.

You might want to add a rule that `extern struct` matches the target C ABI, _except_ if any field has a manually-specified `align(...)`. Maybe that would work, but we'd lose the ability to support structs with `alignas`, which is part of the C11 standard

**Comment by topolarity** [comment] 2022-02-17 04:30
I stand corrected:

It looks like `extern struct` is being considered for more than just the C ABI in https://github.com/ziglang/zig/issues/6700 . Based on the discussion there, sequential forward-aligned field offsets correctly describe struct layout for a very wide range of C ABIs. ["The Lost Art of Structure Padding"](http://www.catb.org/esr/structure-packing/#_alignment_requirements) concludes something similar, noting that NTP has relied on these struct layout assumptions on a wide variety of platforms.

So there may be hope that a generalized `extern struct` could support this use case after all 👍  

`alignas` will need working out as a wrinkle, but that is probably the lesser of all the immediate concerns

**Comment by andrewrk** [comment] 2022-08-23 05:15
This is now implemented in self-hosted, which is now the default compiler.

**Closed by andrewrk** 2022-08-23 05:15 UTC
Labels: proposal, accepted

**Comment by fifty-six** [comment] 2022-09-09 10:22
Is there any alternative/planned alternative for interfacing with C code that uses packed structs? With the current change it's significantly more difficult as any packed struct with an array or any extern struct in it isn't a valid packed type. As an example, my use case is bootloader code and the UEFI spec defines things in a way no longer compatible with the new packed structs - e.g. 
![image](https://user-images.githubusercontent.com/10470872/189328945-7353cad9-0f39-4c04-ab4c-d27921102c33.png)

**Comment by MasterQ32** [comment] 2022-09-09 10:24
Yes. A "packed struct" in C is equivalent to an `extern struct` in zig with all fields having `align(1)`. It's planned to have some kind of syntax like `extern struct align(1) { … }` which would be equivalent to the C version

**Comment by tleydxdy** [comment] 2022-10-21 09:46
how about
`packed struct(uX)` for treating the whole struct as integer (on some platform the field might have reverse in memory order)
`packed struct(.bit)` where fields are always stored in order in memory and packed bit by bit, performance for field access is out the window but the bit order is most consistent
`packed struct(.byte)` where fields are always stored in order in memory, each field is padded to a multiple of 8bit, access might be not aligned but at least there's not a ton of shifts.
for ease of use maybe something like C's unnamed struct member might be used so nesting `packed struct(.bit)` inside `packed struct(.byte)` is easy and can still be accessed by foo.bar

**Comment by zzyxyzz** [comment] 2022-10-21 09:57
xref #12852

**Comment by raddad772** [comment] 2024-06-25 12:55
There is no magic bullet for byte order. It's painful and will always be painful. It requires too much context on the internal data and there's no simplistic and good way of representing it all, unlike what some proposals are trying to do. Not being able to use a simple packed array inside a struct is a pretty huge feature missing.

Here's how you deal with byte order:
1. Cry
2. Suffer
3. Code the program to deal with it

Byteswap requires impossible context. If someone tries to byteswap a struct with a packed array in it, just give an error! Introduce a second, ByteSwapAllExceptPackedStruct() kinda function, that does as it says, for packed structs.
