### ISSUE TITLE
noreturn error union type will allow try and catch

### ISSUE THREAD

**Issue by dylan-conway** [ziglang/zig#19382] opened 2024-03-21 20:51 UTC
### Zig Version

0.12.0-dev.3397+43edd53c3

### Steps to Reproduce and Observed Behavior

```zig
fn foo() !noreturn {
    while (true) {}
}

pub fn main() !void {
    try foo() catch |err| {
        return err;
    };
}
```
This will compile without an error.

### Expected Behavior

I expect this code to produce a compiler error like this because the code in the `catch` block is never reached:
```
repro.zig:745:15: error: expected error union type, found 'noreturn'
    try foo() catch |err| {
    ~~~~~~~~~~^~~~~
```

**Comment by kassane** [comment] 2024-03-21 21:04
This is being ambiguous in this example.

```zig
try foo() catch |err| {
        return err;
    };
```
If you are going to use `catch`, it does not require the `try` keyword.

#### Reference

https://ziglang.org/documentation/master/#try

**Comment by nektro** [comment] 2024-03-21 21:06
its not ambiguous, `catch` takes precedence and the compile error is there if the return type is `!u32` for example. in @dylan-conway's example the compile error should be `error: expected error union type, found 'noreturn'` as stated, in @Rexicon226 examples it should error with `error: unreachable code`.

**Comment by nektro** [comment] 2024-03-21 21:10
edit: `try` does appear to be the one to actually take precedence in the `!u32` example so it should perhaps be `error: unreachable code` in both cases. this is consistent with how you can `try foo() orelse xyz` on a `!?T`

**Comment by lacc97** [comment] 2024-03-21 21:28
Doesn't a `!noreturn` return type still make sense? It either never returns or it returns an error. A use case that comes to mind is execve. It does sound like a very niche use case though.

**Comment by silversquirl** [comment] 2024-03-21 21:35
Zig currently types `execve` with an error set return type (ie. `error { ... }`, as opposed to an error union `error { ... }!T`).
I do agree that `!noreturn` would be more communicative though

**Comment by nektro** [comment] 2024-03-21 21:43
yes it does make sense, i was not trying to say `!noreturn` should be disallowed. only agreeing that attempting to `try` *and* `catch` it should be a compile error like with other non-noreturn types. and my edit was only clarifying my opinion on *which* compile error it should throw.

**Comment by paperdave** [comment] 2024-03-21 22:40
this reminds me that anything that is `noreturn` (without error) will stop analyzing. which i think is an intentional design choice, but it is odd because it prevents stuff shown above from erroring.

note that something like this also compiles
```zig
const std = @import("std");

pub fn main() void {
    std.process.exit(0);
    std.debug.print("Hello, world!\n", .{});
    @compileError("did not analyze me");
}
```

or, for more silliness:

```zig
const std = @import("std");

pub fn main() void {
    // all analysis stops after the noreturn is seen
    // so any nonsense that astgen does not silence
    // can compile successfully
    const a: void = std.process.exit(0) + 1;
    a;
    try 0 catch {};
    return 1;
}
```

so for `try` and `catch` at the same time, `noReturnOrError() catch ...` gets seen, but then since the result of this is just `noreturn`, the `try (...)` part is ignored.

**Comment by nektro** [comment] 2024-03-21 22:45
oh good observation, since this isn't caught by AstGen it may be a duplicate of #11686 and #18504. implementers of those should also include this case in the tests

**Comment by andrewrk** [comment] 2024-08-16 07:21
This is working as designed. Semantic analysis cannot proceed after noreturn, otherwise you would get unwanted compilation errors.

**Closed by andrewrk** 2024-08-16 07:21 UTC
Labels: bug
