### ISSUE TITLE
Incorrect or misleading 'runtime control flow' error message

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#14196] opened 2023-01-04 15:37 UTC
### Zig Version

0.11.0-dev.1182+fd0fb26ab

### Steps to Reproduce and Observed Output

```zig
fn foo(comptime T: type, val: T) void {
    _ = val;
}

test {
    var b: bool = true;
    var i: u64 = 0;
    while (i < 10) : (i += 1) {
        foo(u16, if (b) 0 else 1);
    }
}
```
gives the compile error:
```
strange.zig:9:18: error: value with comptime-only type 'comptime_int' depends on runtime control flow
        foo(u16, if (b) 0 else 1);
                 ^~~~~~~~~~~~~~~
strange.zig:8:14: note: runtime control flow here
    while (i < 10) : (i += 1) {
           ~~^~~~
```

### Expected Output

Either no compile error or a note that is more relevant.

**Comment by Vexu** [comment] 2023-01-04 16:16
Duplicate of #13353

**Closed by Vexu** 2023-01-04 16:16 UTC
Labels: error message
