### ISSUE TITLE
Zig never outputs reference trace

### ISSUE THREAD

**Issue by mpfaff** [ziglang/zig#16757] opened 2023-08-09 19:09 UTC
### Zig Version

0.12.0-dev.5+fc6e57568

### Steps to Reproduce and Observed Behavior

When a compile error occurs, no reference trace is output, regardless of `-freference-trace` being passed or its value.

Similar to #16376, except this happens everywhere I have tried.

I can confirm that this works as intended on version 0.10.1, as well as 0.11.0-dev.3946+b9fc0d290, and breaks on 0.11.0.

The environments I have tried this in are:
- kitty 0.28.1 (`TERM=xterm-kitty`)
- tmux inside kitty 0.28.1 (`TERM=tmux-256color`)
- alacritty 0.12.2 (9d9982df) (`TERM=alacritty`)

Here is an example:

```zig
fn foo(x: anytype) void {
    if (@TypeOf(x) != usize) @compileError("Expected usize, found " ++ @typeName(@TypeOf(x)));

    // do something here
}

pub fn main() !void {
    _ = foo(@as(u32, 1));
}
```

This is the output I get when I try to run the code with `zig run main.zig` or `zig run -freference-trace main.zig`:

```
main.zig:2:30: error: Expected usize, found u32
    if (@TypeOf(x) != usize) @compileError("Expected usize, found " ++ @typeName(@TypeOf(x)));
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

I would expect to get a reference trace so I know where `foo` was called:

```
main.zig:2:30: error: Expected usize, found u32
    if (@TypeOf(x) != usize) @compileError("Expected usize, found " ++ @typeName(@TypeOf(x)));
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

referenced by:
    main: main.zig:8:9
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Comment by nektro** [comment] 2023-08-09 19:11
likely duplicate https://github.com/ziglang/zig/issues/12969

**Comment by mlugg** [comment] 2023-08-09 19:21
Duplicate of #16725; resolved by #16604

**Closed** 2023-08-10 07:20 UTC
Labels: frontend, error message

**Comment by jacobly0** [comment] 2023-08-18 08:36
- [ ]

**Comment by mpfaff** [comment] 2023-08-19 22:20
Can we get some insight into why has this been closed as not planned?

**Comment by mlugg** [comment] 2023-08-19 23:13
That's GitHub being weird - this was solved.

**Comment by jacobly0** [comment] 2023-08-19 23:35
According to GitHub, "not planned" means "Won't fix, can't repro, duplicate, stale", in this case it is a duplicate of a solved issue.  We only fixed one issue, we don't also get credit for fixing all 7 duplicate issues.
