### ISSUE TITLE
Type considered as a runtime value

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#10334] opened 2021-12-14 07:19 UTC
### Zig Version

0.9.0-dev.1952+5d1aab72d

### Steps to Reproduce

```
//bug.zig

pub fn main() void {
    const T = blk: {
        if (true) break :blk u32;
        break :blk u8;
    };
    comptime { _ = T; }
}
```
``zig build-exe bug.zig``

### Expected Behavior

The program should compile with no errors.

### Actual Behavior

```
./bug.zig:3:30: error: cannot store runtime value in type 'type'
        if (true) break :blk u32;
```

**Comment by Vexu** [comment] 2023-01-16 14:20
Duplicate of #3376

**Closed by Vexu** 2023-01-16 14:20 UTC
Labels: bug, stage1
