### ISSUE TITLE
Proposal: make `errdefer` in function not returning an error union a compile error

### ISSUE THREAD

**Issue by ifreund** [ziglang/zig#5612] opened 2020-06-15 17:21 UTC
The following compiles despite the `errdefer` being dead code:
```zig
const std = @import("std");

pub fn main() void {
    errdefer std.debug.warn("I'm alive!\n", .{});
    std.debug.warn("hello world!\n", .{});
}
```
Making this a compile error would avoid dead code hanging around after refactoring.

**Comment by Vexu** [comment] 2020-06-15 17:28
Duplicate of #2654.

**Closed by Vexu** 2020-06-15 17:28 UTC

**Comment by ifreund** [comment] 2020-06-15 17:29
whoops, should've searched first :D
