### ISSUE TITLE
switch + if + enum confused the compiler

### ISSUE THREAD

**Issue by ayende** [ziglang/zig#10559] opened 2022-01-10 08:23 UTC
### Zig Version

0.9.0

### Steps to Reproduce

Try to compile the following code (https://godbolt.org/z/b5fj6dhxG):

```
pub const Num = enum{Even,Odd};

fn isEven(a: u32) Num {
    return switch(a) {
       3 => if (a & 1 != 0 ) .Odd else .Even,
       else => .Even
    };
}
```

### Expected Behavior

Should compile successfully

### Actual Behavior

```
/example.zig:23:13: error: values of type '@Type(.EnumLiteral)' must be comptime known
       3 => if (a & 1 != 0 ) .Odd else .Even,
            ^
```

**Comment by Vexu** [comment] 2022-01-10 08:43
Duplicate of #3750, fixed in the self hosted compiler.

**Closed by Vexu** 2022-01-10 08:43 UTC
Labels: bug
