### ISSUE TITLE
"This is a bug in the zig compiler"

### ISSUE THREAD

**Issue by donaldcallen** [ziglang/zig#3998] opened 2019-12-29 20:30 UTC
```
dca@franz:~/Software/newcash_zig$ make                                                                                     
cd common && make NEWCASH_DEBUG=0 all                                                                                      
make[1]: Entering directory '/home/dca/Software/newcash_zig/common'                                                        
make[1]: Nothing to be done for 'all'.                                                                                     
make[1]: Leaving directory '/home/dca/Software/newcash_zig/common'                                                         
cd composite_register && make NEWCASH_DEBUG=0                                                                              
make[1]: Entering directory '/home/dca/Software/newcash_zig/composite_register'                                            
zig build-exe --main-pkg-path .. --single-threaded -I/usr/include -L/usr/local/lib -L/usr/lib -lc -lsqlite3 composite_register.zig
Code Generation [624/804] std.fmt.formatText...broken LLVM module found: Call parameter type does not match function signature!
  %path = alloca %"[]u8", align 8                                                                                          
 { %"[]u8", i16 }*  call fastcc void @std.fmt.allocPrint.49(%"[]u8"* sret %path, %std.builtin.StackTrace* %error_return_trace, %std.mem.Allocator* @c_allocator_state, %"common.common.struct:375:54"* %11), !dbg !2195
                                                                                                                           
This is a bug in the Zig compiler.                                                                                         
Unable to dump stack trace: debug info stripped                                                                            
make[1]: *** [makefile:4: composite_register] Aborted (core dumped)                                                        
make[1]: Leaving directory '/home/dca/Software/newcash_zig/composite_register'                                             
make: *** [makefile:7: all] Error 2        
```

**Comment by lun-4** [comment] 2019-12-29 20:33
maybe a duplicate of https://github.com/ziglang/zig/issues/3898, which implies a missing `try` for your `allocPrint` call (there also isn't any code provided to help track down the problem).

**Comment by donaldcallen** [comment] 2019-12-29 20:58
On Sun, 29 Dec 2019 at 15:33, luna <notifications@github.com> wrote:

> maybe a duplicate of #3898 <https://github.com/ziglang/zig/issues/3898>,
> which implies a missing try for your allocPrint call (there also isn't
> any code provided to help track down the problem).
>
There is no example code because there is nothing in the error message to
pin-point the code you would need. Based on that error message, I'd have
needed to send you my application and everything it imports.

If allocPrint is the problem, there are no calls to that in the module
being compiled. But there *are* calls to allocPrint
in an imported 'common' module and I found one call to allocPrint that did
not have error handling. I fixed that and now another hard-to-understand
problem has turned up.

I stopped trying to use zig a month or two ago, because it became clear
that the project was not far enough along to support my development
requirements. This was an attempt to check back
and see where things are now. I don't think the conclusion has changed. I
am not saying this in a pejorative way, just stating fact. I will continue
to check back periodically, because I think there is real promise here.

**Comment by andrewrk** [comment] 2019-12-31 08:01
hi @donaldcallen, I suggest to subscribe to these bugs (there is a subscribe button on the right-hand side of a github issue):

* #3422
* #3646
* #3224
* #3327
* #3269

Once you get a notification that all these bugs are fixed, then I would suggest to try again.

In the meantime I will close this one, because it is not enough information to reproduce the issue, and I believe it is a duplicate of one of these other issues.

I definitely understand folks not wanting to use zig until it is more stable. Another thing you can watch is the open bug report count. It is currently high. Once the number starts going down reliably over time, you can tell zig is becoming more stable.

**Closed by andrewrk** 2019-12-31 08:01 UTC

**Comment by donaldcallen** [comment] 2019-12-31 13:23
Andrew -- 

A mature, well-reasoned and polite response, also offering good suggestions that I will take.

"Polite" is not always the case with project leaders, e.g. Theo de Raadt, who has created a community as nasty as he is. Most of the world has not heard of OpenBSD, which is a shame, because it's great work. But when people get subjected to de Raadt's flame-thrower, they respond by going to Plan B. You have wisely chosen (or perhaps it's just who you are, with due credit to your parents :-) the opposite approach.

/Don
