### ISSUE TITLE
Designated init of optional struct field segfaults in debug mode.

### ISSUE THREAD

**Issue by cshenton** [ziglang/zig#5573] opened 2020-06-09 12:54 UTC
`0.6.0+4302f276e`

Repro:

```zig
const std = @import("std");

pub const Outer = struct {
    a: ?Inner,
};

pub const Inner = struct {
    x: u64,
    y: []const u64,
    z: [3]u32,
};

pub fn main() void {
    // Something runtime dependent
    const e: u64 = @intCast(u64, std.time.milliTimestamp());
    const f: u64 = e+1;
    const g: u64 = e+2;

    const inner = Inner{
        .x = e,
        .y = &[_]u64{f, g},
        .z = [3]u32{4, 3, 2},
    };

    const outer_success = Outer{ .a = inner };

    const outer_fail = Outer{
        .a = Inner{
            .x = e,
            .y = &[_]u64{f, g},
            .z = [3]u32{4, 3, 2},
        },
    };
}
```

Exact structures built to roughly match my main codebase. Construction of `outer_fail` will segfault, (also fails if the`.{}` syntax is used).

```
$ zig run repro.zig
Segmentation fault at address 0x7ff666587438
repro.zig:28:19: 0x7ff6665537a5 in main (run.obj)
        .a = Inner{
                  ^
```

**Comment by Vexu** [comment] 2023-01-21 22:53
Duplicate of #4955

**Closed by Vexu** 2023-01-21 22:53 UTC
Labels: bug, stage1
