### ISSUE TITLE
zig0 uses inordinate amounts of ram when building self-hosted parts of stage1

### ISSUE THREAD

**Issue by qeeg** [ziglang/zig#9005] opened 2021-06-06 00:17 UTC
I've seen it using literally 8 GB of RAM, and that's a bit ridiculous IMO.

**Comment by g-w1** [comment] 2021-06-06 00:18
Duplicate of https://github.com/ziglang/zig/issues/6485

**Closed** 2021-06-06 00:36 UTC
