### ISSUE TITLE
Stage2: Miscompilation: array of vectors

### ISSUE THREAD

**Issue by misanthrop** [ziglang/zig#12399] opened 2022-08-10 22:28 UTC
### Zig Version

0.10.0-dev.3513+e218b7ea0

### Steps to Reproduce

Test the following code using `zig test -fno-stage1 -fLLVM vec.zig`

```
const std = @import("std");
const n = 3;                                 // <- Works as expected with n = 2 or n = 4
const V = @Vector(n, f32);
const M = [2]V;

fn zero() M {
	var res: M = undefined;
	for (res) |*v| v.* = @splat(n, @as(f32, 0));
	return res;
}

test {
	const m = zero();
	try std.testing.expectEqual(m, M{
		V{0, 0, 0},
		V{0, 0, 0},
	});
}
```

### Expected Behavior

The test should pass.

### Actual Behavior

Test fails with the message
```
Test [1/1] test_0... index 1 incorrect. expected { 0.0e+00, 0.0e+00, 0.0e+00 }, found { 0.0e+00, 0.0e+00, 3.15325785e-39 }
Test [1/1] test_0... FAIL (TestExpectedEqual)
/usr/lib/zig/std/testing.zig:301:13: 0x224805 in expectEqualSlices__anon_999 (test)
            return error.TestExpectedEqual;
            ^
/usr/lib/zig/std/testing.zig:108:27: 0x224c35 in expectEqual__anon_998 (test)
        .Array => |array| try expectEqualSlices(array.child, &expected, &actual),
                          ^
./miscompilation1.zig:14:2: 0x224c8e in test_0 (test)
	try std.testing.expectEqual(m, M{
 ^
0 passed; 0 skipped; 1 failed.```

**Comment by Vexu** [comment] 2022-08-30 15:43
Likely duplicate of #12026, fixed in master

**Closed by Vexu** 2022-08-30 15:43 UTC
Labels: bug, stage2, miscompilation
