### ISSUE TITLE
zig cc does not work with wasm32-freestanding

### ISSUE THREAD

**Issue by DagAgren** [ziglang/zig#5854] opened 2020-07-12 11:29 UTC
Running this command using the master build from today (0.6.0+fe08a4d06):

    zig cc -target wasm32-freestanding test.c -o test -lc

With test.c containing:

    #include <stdio.h>
    
    int main(void) {
    	printf("Wasm time!\n");
    }

Generates this error:

```
In file included from test.c:1:
/Users/dag/Code/WebAssembly/zig-master/lib/zig/libc/include/generic-musl/stdio.h:26:10: fatal error: 
      'bits/alltypes.h' file not found
#include <bits/alltypes.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.

The following command failed:
/Users/dag/Code/WebAssembly/zig-master/zig clang -c -nostdinc -fno-spell-checking -target wasm32-unknown-unknown-musl -isystem /Users/dag/Code/WebAssembly/zig-master/lib/zig/include -isystem /Users/dag/Code/WebAssembly/zig-master/lib/zig/libc/include/wasm32-freestanding-musl -isystem /Users/dag/Code/WebAssembly/zig-master/lib/zig/libc/include/generic-musl -isystem /Users/dag/Code/WebAssembly/zig-master/lib/zig/libc/include/wasm32-freestanding-any -isystem /Users/dag/Code/WebAssembly/zig-master/lib/zig/libc/include/any-freestanding-any -Xclang -target-cpu -Xclang generic -Xclang -target-feature -Xclang -atomics -Xclang -target-feature -Xclang -bulk-memory -Xclang -target-feature -Xclang -exception-handling -Xclang -target-feature -Xclang -multivalue -Xclang -target-feature -Xclang -mutable-globals -Xclang -target-feature -Xclang -nontrapping-fptoint -Xclang -target-feature -Xclang -sign-ext -Xclang -target-feature -Xclang -simd128 -Xclang -target-feature -Xclang -tail-call -Xclang -target-feature -Xclang -unimplemented-simd128 -MD -MV -MF zig-cache/tmp/ISG_1JpSw97E-test.o.d -ffreestanding -fno-omit-frame-pointer -fsanitize=undefined -fsanitize-trap=undefined -D_DEBUG -Og -fstack-protector-strong --param ssp-buffer-size=4 -o zig-cache/tmp/ISG_1JpSw97E-test.o test.c
```

**Comment by zigazeljko** [comment] 2020-07-12 12:21
It seems like the directory `lib/zig/libc/include/wasm32-freestanding-musl` is missing. Since musl has no official support for wasm, we would need to implement those headers ourself (or use one of the musl forks).

@DagAgren In the meantime, you can try using headers from some other 32-bit arch (such as i386). For your example, just copy `/Users/dag/Code/WebAssembly/zig-master/lib/zig/libc/include/i386-linux-musl` to `/Users/dag/Code/WebAssembly/zig-master/lib/zig/libc/include/wasm32-freestanding-musl`. I tried that and it worked, but YMMV.

**Comment by DagAgren** [comment] 2020-07-12 12:47
Looks like it works at least for the purposes of the test! Thanks for the workaround.

**Comment by DagAgren** [comment] 2020-07-12 21:03
This doesn't seem to run in wasmtime, though, probably because it is not using the WASI version of musl?

**Comment by andrewrk** [comment] 2020-12-01 03:34
```
andy@ark ~/d/zig (master)> gl --stat -- lib/libc/include/wasm32-freestanding-musl
commit f70ce707e2d35a5ed8349d03b6aa8d493792e180
Author: Andrew Kelley <andrew@ziglang.org>
Date:   Tue Jul 16 19:02:51 2019 -0400

    update musl headers to musl v1.1.23

 lib/libc/include/wasm32-freestanding-musl/bits/alltypes.h | 385 --------------------------------------
 lib/libc/include/wasm32-freestanding-musl/errno.h         |  24 ---
 2 files changed, 409 deletions(-)

```

OH NO!! I accidentally completely wiped `wasm32-freestanding-musl` with the upgrade to musl v1.1.23!

**Comment by andrewrk** [comment] 2020-12-01 03:51
The regression is fixed with https://github.com/ziglang/zig/commit/21565ca991bba9692ed74ec9fb9a665f8e504c7f.

The example you give however is an enhancement: supporting more of libc functions in a freestanding environment. This is in fact a problem not specific to WebAssembly. It is an interesting use case: provide libc header definitions for a freestanding environment. Support for this use case is indeed in scope, but not for 0.7.x.

Here's what works now:

```c
int foo(void) {
    return 1234;
}
```

```
zig build-lib -target wasm32-freestanding test.c -lc
```

In the future, your code example would work too but `printf` would be a linker error and you would have to provide it in your own code, since it is a freestanding environment.

**Comment by andrewrk** [comment] 2020-12-01 03:51
> This doesn't seem to run in wasmtime, though, probably because it is not using the WASI version of musl?

There is no WASI version of musl, and if you wanted WASI then that is a different target: `wasm32-wasi`

**Closed by andrewrk** 2020-12-01 03:51 UTC
Labels: arch-wasm32, bug, contributor friendly, os-freestanding, zig cc

**Comment by zigazeljko** [comment] 2020-12-01 17:45
> There is no WASI version of musl

There is https://github.com/WebAssembly/wasi-libc, which is based on musl.

**Comment by andrewrk** [comment] 2020-12-01 19:13
I see. Well, improvements to the header files in `lib/libc/include/zig's wasm-freestanding-musl` directory are welcome. In the same way that WebAssembly/wasi-libc are based on musl, that directory of zig is also based on musl. The implementations go in `lib/std/special/c.zig` (or files referenced by that one).
