### ISSUE TITLE
Improved type inference on initialization

### ISSUE THREAD

**Issue by Srekel** [ziglang/zig#3547] opened 2019-10-27 19:56 UTC
Coming from C, I tend to want to declare the type, rather than rely on the type getting automatically resolved from the rhs. I've been playing with Zig the last couple of weeks, and really liking it, but a number of times I've stumbled on initializing arrays, and I just realized that it may be because it seems Zig currently doesn't infer the type correctly on initialization.

For example, in C, this works:
`int arr[2] = {1,2};`

But in Zig:
```
var arr1a:[_]i32 = {1,2};
var arr1b:[2]i32 = {1,2};

error: expected token ';', found ','
    var arr1a:[_]i32 = {1,2};
                         ^

error: expected token ';', found ','
    var arr1b:[2]i32 = {1,2};
                         ^
```

Some more examples. 2ab and 3ab works, but 4ab doesn't compile:
```
    var arr2a = [_]i32{ 1, 2 };
    var arr2b = [2]i32{ 1, 2 };
    var arr3a: [2]i32 = [_]i32{ 1, 2 };
    var arr3b: [2]i32 = [2]i32{ 1, 2 };
    var arr4a: [_]i32 = [_]i32{ 1, 2 };
    var arr4b: [_]i32 = [2]i32{ 1, 2 };

error: inferred array size invalid here
    var arr4a: [_]i32 = [_]i32{ 1, 2 };
               ^
error: inferred array size invalid here
    var arr4b: [_]i32 = [2]i32{ 1, 2 };
               ^
```

And a multi dimensional example. The first one compiles, the second one doesn't.

```
    var multarr1 = [2][2][3]u8{
        [2][3]u8{
            [3]u8{ 3, 2, 1 },
            [3]u8{ 2, 6, 7 },
        },
        [2][3]u8{
            [3]u8{ 3, 3, 1 },
            [3]u8{ 2, 6, 7 },
        },
    };

    var multarr2 = [2][2][3]u8{
        {
           {30, 20, 10},
           {20, 60, 70},
        },
        {
            {30, 30, 10},
            {20, 60, 70},
        },
    };

error: expected token ';', found ','
           {30, 20, 10},
              ^
```

Related to #3546, we're discussing the problem on Discord but accidentally posted similar issues. :)

**Comment by JesseRMeyer** [comment] 2019-10-28 13:22
I completely agree.  And to add my tidbit, I don't see this issue as a 'verbosity' vs 'clean, or DRY' syntax issue, but a 'is this a good use of my mind's time and energy' issue?  

Do the explicit LHS specifiers aid in code comprehension? No - the RHS specifies the context completely.  Does it aid in maintainability?  No, quite the opposite.  A change in the RHS requires a change in the LHS, and the vast majority of use cases here is symmetric (can you even have this in a non-symmetric form?).

Fortunately, the related issues discuss this specific issue in a rather comprehensive way, so I hope that continues forward..

**Comment by daurnimator** [comment] 2019-10-28 13:27
I think this issue is also a duplicate of #685

**Closed by daurnimator** 2019-10-28 13:27 UTC
