### ISSUE TITLE
stage2 compiler segfaults when working on a faulty bit shift

### ISSUE THREAD

**Issue by Phytolizer** [ziglang/zig#12507] opened 2022-08-20 04:37 UTC
### Zig Version

0.10.0-dev.3659+e5e6eb983

### Steps to Reproduce

- Save this code as `broken.zig`:
```zig
pub fn main() !void {
    var j: usize = 8;
    _ = 1 << (j - 1);
}
```
- Attempt to compile the code (with `zig build-exe broken.zig`)
- The compiler will segfault
- Attempt to compile the code again with `-fstage1` added
- Appropriate diagnostics are emitted:
```
./broken.zig:3:11: error: LHS of shift must be a fixed-width integer type, or RHS must be compile-time known
    _ = 1 << (j - 1);
          ^
```

### Expected Behavior

I expected the compiler to emit diagnostics as usual.

### Actual Behavior

The compiler segfaults and provides no output.

**Comment by Vexu** [comment] 2022-09-02 10:28
Duplicate of #12290, fixed in master

**Closed by Vexu** 2022-09-02 10:28 UTC
Labels: bug, stage2
