### ISSUE TITLE
Compiler error triggered when calling with wrong parameter for DefaultPrng init

### ISSUE THREAD

**Issue by rganesan** [ziglang/zig#14044] opened 2022-12-23 04:48 UTC
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

I made a typo while playing with rand and hit a compiler error:

```
const std = @import("std");
const Prng = std.rand.DefaultPrng;
const crandom = std.crypto.random;

pub fn main() void {
    const rng = Prng.init(crandom.init(u64));
    _ = rng;
}
```

That should have been `crandom.int(u64)`, the compiler catches the error but panics later:

```
zig run rand-test.zig 
/opt/homebrew/Cellar/zig/0.10.0/lib/zig/std/rand.zig:35:44: error: expected type 'fn(*const rand.Random, []u8) void', found 'type'
    pub fn init(pointer: anytype, comptime fillFn: fn (ptr: @TypeOf(pointer), buf: []u8) void) Random {
                                           ^~~~~~
thread 11639360 panic: Zig compiler bug: attempted to destroy declaration with an attached error
Unable to dump stack trace: debug info stripped
```

### Expected Behavior

Compiler should not panic with wrong code.

**Comment by nektro** [comment] 2022-12-23 05:16
duplicate of https://github.com/ziglang/zig/issues/12927

**Closed** 2022-12-23 08:47 UTC
Labels: bug
