### ISSUE TITLE
false dependency loop with recursive declaration addresses

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#14517] opened 2023-02-02 18:10 UTC
### Zig Version

0.11.0-dev.1457+cb9d00e1a

### Steps to Reproduce and Observed Behavior

This happens when declarations depend on each others addresses recursively.  Here is a reduction provided by [Vexu](https://github.com/ziglang/zig/issues/12325#issuecomment-1413614549)

```zig
// /tmp/tmp.zig
const a = &b;
const b = &a;

test {
    _ = a;
}
```
```console
/tmp/tmp.zig:1:1: error: dependency loop detected
const a = &b;
^~~~~~~~~~~~
```

My use case is that I'm really wanting to use this feature for generated code in my [protobuf-zig](https://github.com/travisstaloch/protobuf-zig) lib so that i don't have to resort to generating duplicate .c,/h files to achieve this.  [Here](https://github.com/travisstaloch/protobuf-zig/issues/1) is an issue for this.  This can be achieved in c by using a forward declaration (or an extern i believe for referencing from .h to .c).

### Expected Behavior

I think it should compile.  Or at least this reduction shouldn't be a dependency loop error.

**Comment by praschke** [comment] 2023-02-02 22:02
Duplicate of #131.

**Closed** 2023-02-03 12:47 UTC
Labels: bug
