### ISSUE TITLE
Packed struct initialization bug with some combo of a runtime value and undefined

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#15395] opened 2023-04-22 05:18 UTC
### Zig Version

0.11.0-dev.2725+4374ce51b

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub const Foo = packed struct(u32) {
    a: bool = false,
    b: bool = false,
    c: bool = false,
    d: bool = false,
    padding: u28 = undefined,
};

fn testFoo(foo: Foo) !void {
    std.debug.print("\n{}\n\n", .{foo});
    try std.testing.expectEqual(@as(bool, true), foo.a);
    try std.testing.expectEqual(@as(bool, false), foo.b);
    try std.testing.expectEqual(@as(bool, false), foo.c);
    try std.testing.expectEqual(@as(bool, false), foo.d);
}

// This will fail:
test "runtime init" {
    var runtime_bool: bool = true;
    var runtime_init = Foo{
        .a = runtime_bool,
    };
    try testFoo(runtime_init);
}

// This will succeed:
test "comptime init" {
    var comptime_init = Foo{
        .a = true,
    };
    try testFoo(comptime_init);
}
```

```
Test [1/2] test.runtime init...
weird.Foo{ .a = false, .b = true, .c = false, .d = true, .padding = 178956970 }

expected true, found false
Test [1/2] test.runtime init... FAIL (TestExpectedEqual)
C:\Users\Ryan\Programming\Zig\zig\lib\std\testing.zig:78:17: 0x7ff62275104a in expectEqual__anon_2436 (test.exe.obj)
                return error.TestExpectedEqual;
                ^
C:\Users\Ryan\Programming\Zig\resinator\tmp\weird.zig:13:5: 0x7ff62275126c in testFoo (test.exe.obj)
    try std.testing.expectEqual(@as(bool, true), foo.a);
    ^
C:\Users\Ryan\Programming\Zig\resinator\tmp\weird.zig:25:5: 0x7ff6227514c7 in test.runtime init (test.exe.obj)
    try testFoo(runtime_init);
    ^
Test [2/2] test.comptime init...
weird.Foo{ .a = true, .b = false, .c = false, .d = false, .padding = 0 }

1 passed; 0 skipped; 1 failed.
```

Notes:
- If `padding` is initialized to e.g. `0` instead, the problem goes away
- The `undefined` being a default value is irrelevant, the same behavior occurs if the initialization of that field is moved into the `test` block

### Expected Behavior

Both tests to pass

**Comment by Vexu** [comment] 2023-04-22 10:08
Duplicate of #13480

The init is getting lowered with operations on undefined values:
```zig
test "runtime init" {
    var runtime_bool: bool = true;
    var runtime_init: Foo = undefined;
    runtime_init = (runtime_init & -2) | @as(u32, runtime_bool) << 0;
    try testFoo(runtime_init);
}
```

**Closed by Vexu** 2023-04-22 10:08 UTC
Labels: bug
