### ISSUE TITLE
test/link/macho/uuid is failing in the llvm16 branch

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14555] opened 2023-02-04 23:30 UTC
```
========= Expected to find: ==========================
uuid 675bb6ba8e5d3d3191f7936d7168f0e9
========= But parsed file does not contain it: =======
LC 0
cmd SEGMENT_64
cmdsize 152
segname __TEXT
vmaddr 0
vmsize 4000
fileoff 0
filesz 4000
sectname __text
addr 298
size 4
offset 298
align 2
LC 1
cmd SEGMENT_64
cmdsize 72
segname __LINKEDIT
vmaddr 4000
vmsize 4000
fileoff 4000
filesz 210
LC 2
cmd DYLD_INFO_ONLY
cmdsize 48
rebaseoff 4000
rebasesize 0
bindoff 4000
bindsize 0
weakbindoff 0
weakbindsize 0
lazybindoff 4000
lazybindsize 0
exportoff 4000
exportsize 10
LC 3
cmd FUNCTION_STARTS
cmdsize 16
dataoff 4010
datasize 8
LC 4
cmd DATA_IN_CODE
cmdsize 16
dataoff 4018
datasize 0
LC 5
cmd SYMTAB
cmdsize 24
symoff 4018
nsyms 9
stroff 40a8
strsize a8
LC 6
cmd DYSYMTAB
cmdsize 80
ilocalsym 0
nlocalsym 8
iextdefsym 8
nextdefsym 1
iundefsym 9
nundefsym 0
indirectsymoff 40a8
nindirectsyms 0
LC 7
cmd LOAD_DYLINKER
cmdsize 32
LC 8
cmd ID_DYLIB
cmdsize 48
name @rpath/libtest.dylib
timestamp 2
current version 10000
compatibility version 10000
LC 9
cmd SOURCE_VERSION
cmdsize 16
LC 10
cmd BUILD_VERSION
cmdsize 32
LC 11
cmd UUID
cmdsize 24
uuid af0f4c21a07c30daba59213d80262e45
LC 12
cmd LOAD_DYLIB
cmdsize 56
name /usr/lib/libSystem.B.dylib
timestamp 2
current version 50c6405
compatibility version 10000
LC 13
cmd CODE_SIGNATURE
cmdsize 16
dataoff 4150
datasize c0

error: TestFailed
/home/andy/misc/zig/lib/std/Build/CheckObjectStep.zig:345:25: 0x2eae74 in make (build)
                        return error.TestFailed;
                        ^
/home/andy/misc/zig/lib/std/Build/Step.zig:75:5: 0x2901db in make (build)
    try self.makeFn(self);
    ^
/home/andy/misc/zig/lib/std/Build.zig:732:5: 0x27cdff in makeOneStep (build)
    try s.make();
    ^
/home/andy/misc/zig/lib/std/Build.zig:726:13: 0x27cd6a in makeOneStep (build)
            return err;
            ^
/home/andy/misc/zig/lib/std/Build.zig:687:9: 0x27ca93 in make (build)
        try self.makeOneStep(s);
        ^
/home/andy/misc/zig/lib/build_runner.zig:230:21: 0x27fb8c in main (build)
            else => return err,
                    ^
error: the following build command failed with exit code 1:
/home/andy/misc/zig/test/link/macho/uuid/zig-cache/o/6143e3529adaa2549a0ee75a9974c966/build /home/andy/misc/zig/build/stage3/bin/zig /home/andy/misc/zig/test/link/macho/uuid /home/andy/misc/zig/test/link/macho/uuid/zig-cache /home/andy/.cache/zig test
The following command exited with error code 1 (expected 0):
cd /home/andy/misc/zig && build/stage3/bin/zig build --build-file /home/andy/misc/zig/test/link/macho/uuid/build.zig test 
error: UnexpectedExitCode
```

cc @kubkon - I would appreciate your help with this one

**Comment by kubkon** [comment] 2023-02-06 15:14
It's not a regression, we just need to update the expected UUID values since the new version of LLVM has likely produced different machine code and hence different UUID values. Alternatively, perhaps there would be a way to test this differently than how we do it ATM.

**Comment by kubkon** [comment] 2023-02-08 10:20
I have improved the test by not relying on hardcoded UUID values for the test to pass in https://github.com/ziglang/zig/pull/14590. Instead, per optimize mode, we now build the same dylib with and without debug info, but install both in the same folder under a different name, and then we parse both, read the UUID values, and compare for equality. The trick here is to build each dylib having the same install name, say `libtest.dylib`, but rename it into something else in the output folder so that we do not affect the calculated UUID values per run and can still have both artifacts available for comparison.

This improved test will ensure we still validate the UUID computation mechanism while not depending on a specific version of LLVM as the expected UUID values are no longer hard-coded. After https://github.com/ziglang/zig/pull/14590 is merged, you will need to rebase the LLVM 16 branch or cherry-pick the commit.

**Closed** 2023-02-08 16:26 UTC
Labels: bug, os-macos

**Comment by andrewrk** [comment] 2023-02-08 17:32
Brilliant, thank you!
