### ISSUE TITLE
C ABI: extern struct size mismatch.

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [ziglang/zig#14566] opened 2023-02-05 13:48 UTC
### Zig Version

0.11.0-dev.1313+bb15e4057

### Steps to Reproduce and Observed Behavior

While porting C code to Zig, I have observed a size mismatch reported by sizeof() and @sizeOf().
The C version of the structure is reported to be 16 bytes, while Zig version is reported to be 20.
Hand-translated and translate-c zig code is identical.

```
typedef struct waveformat_tag {
    uint16_t wFormatTag;
    uint16_t nChannels;
    uint32_t nSamplesPerSec;
    uint32_t nAvgBytesPerSec;
    uint16_t nBlockAlign;
} WAVEFORMAT;

typedef struct pcmwaveformat_tag {
    WAVEFORMAT  wf;
    uint16_t wBitsPerSample;
} PCMWAVEFORMAT;
```

### Expected Behavior

extern struct must match the C ABI.

**Comment by Vexu** [comment] 2023-02-05 13:57
What target is this on? `sizeof(PCMWAVEFORMAT) == 20` for me on x86_64 linux.

**Comment by eLeCtrOssSnake** [comment] 2023-02-05 14:27
x86_64-windows-gnu

**Comment by Vexu** [comment] 2023-02-05 14:33
Makes no difference for me, can you share more of your code?

**Comment by eLeCtrOssSnake** [comment] 2023-02-05 14:43
> Makes no difference for me, can you share more of your code?

I think I got trolled by windows headers.
I think there's a pragma pack push in some other file.
Standalone definition is indeed 20 bytes, but translated-c file ignores pragma pack and outputs 20 byte version also.
This turned out to be translate-c issue.

**Comment by eLeCtrOssSnake** [comment] 2023-02-05 14:44
PCMWAVEFORMAT is defined somewhere through windows.h includes if you want to see original. It is packed to be 16 bytes.

**Comment by Vexu** [comment] 2023-02-05 15:02
Then this is a duplicate of #4754

**Closed by Vexu** 2023-02-05 15:02 UTC
Labels: bug

**Comment by eLeCtrOssSnake** [comment] 2023-02-05 22:00
Well, it turned out to be a completely different issue. Windows headers are very confusing, sorry. Good thing I asserted struct size!!
