### ISSUE TITLE
Regression: bitcast initialized empty packed struct should be zero but is non-zero

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#19692] opened 2024-04-18 20:34 UTC
### Zig Version

0.12.0-dev.3674+a0de07760

### Steps to Reproduce and Observed Behavior

```zig
const Cell = packed struct(u64) {
    content: packed union {
        a: u21,
        b: u22,
    } = .{ .a = 0 },
    _padding: u42 = 0,
};

test {
    const cell: Cell = .{};
    const cell_int: u64 = @bitCast(cell);
    try @import("std").testing.expectEqual(@as(u64, 0), cell_int);
}
```

### Expected Behavior

I expect the test to pass but it fails. It used to pass with `0.12.0-dev.3405+31791ae15`

I can understand why it's failing: I'm setting the smaller field of the `packed union` so the extra bits are probably undefined? Should I be setting the largest field always?

I'm willing to accept this is my problem and not yours but wanted to raise it in case you believe this is a regression.

**Comment by mlugg** [comment] 2024-04-18 20:42
Yes, I think it's accurate to say that initializing a packed union with a small field leaves the remaining bits undefined, so that code snippet just has a bug. That said, I'll wait for @andrewrk to confirm the intended behavior before closing.

**Comment by andrewrk** [comment] 2024-04-18 21:15
Thanks for the report.

This is indeed working as designed given how unions work in zig: only the active field has a defined value, and the bitcast therefore accesses undefined memory, making cell_int have undefined bits, or be fully undefined, depending on the resolution of #19634.

Based on the [recent guidance that I wrote on struct field initialization](https://ziglang.org/documentation/master/#Default-Field-Values), I would recommend this instead:

```zig
const Cell = packed struct(u64) {
    content: packed union {
        a: u21,
        b: u22,
    },
    _padding: u42,

    const init: Cell = @bitCast(@as(u64, 0));
};
test {
    const cell = Cell.init;
    const cell_int: u64 = @bitCast(cell);
    try @import("std").testing.expectEqual(@as(u64, 0), cell_int);
}
```

This code snippet should be considered when evaluating #19634, but I don't think it needs to remain open as a bug or a proposal.

**Closed by andrewrk** 2024-04-18 21:15 UTC
Labels: bug

**Comment by mitchellh** [comment] 2024-04-18 21:33
Thanks, that's exactly what I ended up doing.
