### ISSUE TITLE
Compiler crash on `comptime` pointer type mismatch (missing `@ptrCast`)

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#21479] opened 2024-09-21 15:28 UTC
### Zig Version

0.14.0-dev.1579+f3445f8f6

### Steps to Reproduce and Observed Behavior

Reduced from https://github.com/ziglang/zig/issues/21478, repro `zig test .zig`:
```zig
pub const S = struct {
    data: [4]u8,
    pub fn begin(self: *const S) [*]const u8 {
        return &self.data[0];
    }
};
const s: S = undefined;
const s_begin = s.begin(); //leads to compiler crash
//const s_begin: [*]const u8 = &s.data[0]; //correctly triggers compile error
const offset = s_begin - s_begin;
test {
    @compileLog(offset);
}
```
Leads to a compiler crash (no output, Windows exit code `-1073741819`).
Switching to the other `s_begin` definition yields a correct compile error:
```
.zig:9:30: error: expected type '[*]const u8', found '*const u8'
const s_begin: [*]const u8 = &s.data[0]; //correctly triggers compile error
                             ^~~~~~~~~~
.zig:9:30: note: a single pointer cannot cast into a many pointer
```

### Expected Behavior

No compiler crash, instead a compile error as with the commented-out, inlined `s_begin` initializer.
I'm not sure why the compiler accepts the `return` of the incorrect type within the method.
Maybe there's some slightly wrong / outdated casting logic used internally, by which the value would automatically coerce, but then that coercion never happens?

**Comment by der-teufel-programming** [comment] 2024-09-25 10:51
Stack trace from a debug build of the compiler begins with
```
thread 33876 panic: access of union field 'func' while field 'cau' is active
Analyzing issue21479.zig
      %13 = ret_type()
      %14 = dbg_stmt(2, 9)
      %15 = validate_ref_ty(%13)
      %16 = ref(%10)
      %17 = dbg_stmt(2, 21)
      %18 = field_ptr(%16, "data")
      %19 = dbg_stmt(2, 26)
      %20 = elem_ptr_node(%18, @zero)
      %21 = restore_err_ret_index_unconditional(.none)
      %22 = dbg_stmt(2, 9)
    > %23 = ret_node(%20)
    For full context, use the command
      zig ast-check -t issue21479.zig

  in issue21479.zig
    > %34 = field_call(.compile_time, %32, "begin", [])
  in issue21479.zig
    > %37 = decl_val("s_begin")
  in issue21479.zig
    > %43 = decl_val("offset")

C:\Users\Krzysztof\dev\zig\src\Sema.zig:30578:74: 0x11d3ab3 in coerceExtra (zig.exe.obj)
            !zcu.test_functions.contains(zcu.funcInfo(sema.owner.unwrap().func).owner_nav))
                                                                         ^
C:\Users\Krzysztof\dev\zig\src\Sema.zig:20445:37: 0x1f8f2f3 in analyzeRet (zig.exe.obj)
    const operand = sema.coerceExtra(block, sema.fn_ret_ty, uncasted_operand, operand_src, .{ .is_ret = true }) catch |err| switch (err) {
                                    ^
C:\Users\Krzysztof\dev\zig\src\Sema.zig:20218:27: 0x1b0bbf2 in zirRetNode (zig.exe.obj)
    return sema.analyzeRet(block, operand, src, block.src(.{ .node_offset_return_operand = inst_data.src_node }));
                          ^
C:\Users\Krzysztof\dev\zig\src\Sema.zig:1258:57: 0x15b6f0d in analyzeBodyInner (zig.exe.obj)
            .ret_node       => break try sema.zirRetNode(block, inst),
                                                        ^
C:\Users\Krzysztof\dev\zig\src\Sema.zig:935:26: 0x1a29c53 in analyzeFnBody (zig.exe.obj)
    sema.analyzeBodyInner(block, body) catch |err| switch (err) {
```

**Comment by Vexu** [comment] 2024-09-27 13:26
Duplicate of #21159

**Closed by Vexu** 2024-09-27 13:26 UTC
Labels: bug
