### ISSUE TITLE
Zig-generated function names can clash with LLVM intrinsics

### ISSUE THREAD

**Issue by lucascharlesmyers** [ziglang/zig#11525] opened 2022-04-25 21:58 UTC
### Zig Version

0.10.0-dev.1931+ab658e32b

### Steps to Reproduce

Create a file called `llvm.zig` with a `pub` function in it:
```zig
pub fn foo() {}
```

and a root source that depends on it (e.g. `root.zig`):
```zig
comptime {
    _ = @import("llvm.zig").foo;
}
```

Then try to compile `root.zig`, e.g.
```
zig build-obj root.zig
```

### Expected Behavior

The compilation succeeds and produces an object file.

### Actual Behavior

The compilation fails with this output:
```
broken LLVM module found: llvm intrinsics cannot be defined!
void ()* @llvm.foo

This is a bug in the Zig compiler.
```

**Comment by ifreund** [comment] 2022-04-25 22:37
Thanks for the bug report! I'm going to close this as a duplicate of https://github.com/ziglang/zig/issues/2291 since they have the same root cause and fix.

**Closed by ifreund** 2022-04-25 22:37 UTC
Labels: bug
