### ISSUE TITLE
Passing `.{@src()}` to `anytype` param traps

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#13170] opened 2022-10-15 10:47 UTC
### Zig Version

0.10.0-dev.4333+f5f28e0d2

### Steps to Reproduce

```zig
pub fn main() void {
    x(.{@src()});
}

fn x(args: anytype) void {
    _ = args;
}
```

### Expected Behavior

```
$ zig run x.zig
$
```

### Actual Behavior

```
$ zig run x.zig
Trace/breakpoint trap (core dumped)
$
```

**Comment by Vexu** [comment] 2022-10-15 13:33
Duplicate of #12702

**Closed by Vexu** 2022-10-15 13:33 UTC
Labels: bug
