### ISSUE TITLE
Constructing struct field from failable method without try results in broken LLVM ir

### ISSUE THREAD

**Issue by ForLoveOfCats** [ziglang/zig#3698] opened 2019-11-15 14:56 UTC
Zig version 0.5.0 and 8c4784f9c181a13eae36d7a1ac57f278cf5fcd72 on Linux x86_64

The following invalid code passes Zig's validation and results in broken LLVM ir
```zig
const std = @import("std");
const mem = std.mem;

const SomeStruct = struct {
    string: []u8,
};

pub fn main() void {
    const allocator = std.heap.direct_allocator;

    var instance = SomeStruct {
        .string = mem.dupe(allocator, u8, "Hello"),
    };
}
```
```
Code Generation [253/452] std.fmt.format...broken LLVM module found: Call parameter type does not match function signature!
  %5 = getelementptr inbounds %SomeStruct, %SomeStruct* %instance, i32 0, i32 0, !dbg !14630
 { %"[]u8", i16 }*  call fastcc void @std.mem.dupe(%"[]u8"* sret %5, %std.builtin.StackTrace* %error_return_trace, %std.mem.Allocator* @direct_allocator_state, %"[]u8"* @327), !dbg !14631
```

<br/><br/>

Once the error is handled everything works correctly
```zig
const std = @import("std");
const mem = std.mem;

const SomeStruct = struct {
    string: []u8,
};

pub fn main() !void {
    const allocator = std.heap.direct_allocator;

    var instance = SomeStruct {
        .string = try mem.dupe(allocator, u8, "Hello"),
    };
}
```

**Comment by Vexu** [comment] 2019-11-15 15:09
Duplicate of #3269, #3422, #3646, #3224, #2881, #3223 and #3327.

[See](https://github.com/ziglang/zig/issues/3688#issuecomment-553770070)

**Comment by ForLoveOfCats** [comment] 2019-11-15 16:26
I just want to say for the record that I did see most of those issues this has a different reproduction so I played it safe and opened an issue. 

Should this be closed if it is indeed the same issue?

**Comment by Vexu** [comment] 2019-11-15 16:33
> Should this be closed if it is indeed the same issue?

I think it is pretty safe to close this as a duplicate.

**Closed** 2019-11-15 16:34 UTC
