### ISSUE TITLE
Miscompilation with switch in anonymous struct literal

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#7097] opened 2020-11-13 09:55 UTC
The following function will always print `reading from` and will ignore the runtime parameter:

```zig
fn logErrorBad(err: Error, address: u24, access: BusAccess) Error {
    std.debug.print("{} when {} {X:0>6}\n", .{
        @errorName(err),
        @as([]const u8, switch (access) {
            .read => "reading from",
            .write => "writing to",
        }),
        address,
    });
    return err;
}
```

Fully runnble example can be found here:
https://gist.github.com/MasterQ32/da5b1f2dbe4ebc89ebbf602d8b118fca

Moving out the switch+`@as` will fix the problem. This is probably a known issue already

**Comment by travv0** [comment] 2020-11-13 14:39
Related to #3882?

**Comment by dbandstra** [comment] 2020-11-13 18:34
I think this is a more likely duplicate: https://github.com/ziglang/zig/issues/6444

**Comment by Mouvedia** [comment] 2020-11-14 12:02
dupe of #5230

**Closed** 2022-12-28 13:36 UTC
Labels: bug, stage1, miscompilation
