### ISSUE TITLE
InvalidTargetGLibCVersion:  error: zig does not yet provide glibc version 2.35, the max provided version is 2.34

### ISSUE THREAD

**Issue by winspool** [ziglang/zig#13252] opened 2022-10-21 20:38 UTC
### Zig Version

0.10.0-dev.3952+9e070b653

### Steps to Reproduce

* download binary release 3952,
* unpack the archive
* add the dir to the PATH
* compile a helloworld.c with: `zig cc helloworld.c -o helloworld_zig_3952`

regression detected between rev. 3944 and 3952: InvalidTargetGLibCVersion
error: zig does not yet provide glibc version 2.35, the max provided version is 2.34
error: unable to build glibc shared objects: InvalidTargetGLibCVersion

last good binary release:
zig-linux-x86_64-0.10.0-dev.3944+c9f145a50.tar.xz
first broken binary release
zig-linux-x86_64-0.10.0-dev.3952+9e070b653.tar.xz

### Expected Behavior

build a helloworld app

### Actual Behavior

`zig cc helloworld.c -o helloworld_zig_3952`

error: zig does not yet provide glibc version 2.35, the max provided version is 2.34
error: unable to build glibc shared objects: InvalidTargetGLibCVersion

Unable to check, if this bug was fixed in the meantime, due to bug #13185
https://github.com/ziglang/zig/issues/13185

**Comment by nektro** [comment] 2022-10-21 20:39
duplicate of https://github.com/ziglang/zig/issues/12808

**Comment by nektro** [comment] 2022-10-21 20:40
should be falling back to your native version though if its newer than whats available

**Comment by nektro** [comment] 2022-10-21 20:41
what distro/version are you on?

**Comment by Vexu** [comment] 2022-10-21 20:45
Duplicate of #12808, fallback fixed in #12814

**Closed by Vexu** 2022-10-21 20:45 UTC
Labels: bug

**Comment by winspool** [comment] 2022-10-21 20:57
Oh, sorry for the dupe.

**Comment by winspool** [comment] 2022-10-21 22:39
> what distro/version are you on?

xubuntu 22.04 LTS (jammy jellyfish)

**Comment by nektro** [comment] 2022-10-21 22:41
fix landed in `0.10.0-dev.3984+349df40d1` if you update and it persists, let us know :)
