### ISSUE TITLE
inline condition causes inability to infer expression type

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#1718] opened 2018-11-14 04:13 UTC
```
$ zig version
0.3.0+5b3f7a8e
```

```zig
fn M0(x:f64,y:f64) u8 {
    return if ((x+y)<4) 0 else 0xe0;  // this fails with 'error: unable to infer expression type'
    //if ((x+y)<4) { return 0;}else{ return 0xe0; } // this works fine
}

pub fn main() void {
    const pixels = comptime(M0(0,0));
}
```

Note: this was run into while translating [this](https://gist.github.com/daurnimator/da3d4a6d9b582fd38d2cde160e269cdc#file-cursed_mandelbrot-zig) C to Zig.

**Comment by andrewrk** [comment] 2018-11-14 17:11
Duplicate of #137. Note that this is fixed in the copy-elision PR (#1682).

**Closed by andrewrk** 2018-11-14 17:11 UTC
