### ISSUE TITLE
Core dump instead of "missing struct field" error

### ISSUE THREAD

**Issue by Reokodoku** [ziglang/zig#18671] opened 2024-01-24 17:50 UTC
### Zig Version

0.12.0 (built from 9221113 with Alpine Linux)

### Steps to Reproduce and Observed Behavior

Using this file
```zig
// build.zig

const A = struct {
    c: usize = 23,
    e: B,
};

const B = struct {
    a: bool = false,
};

const C = struct {
    p: A,
};

const D = struct {
    A,
    C,
};

pub fn build(b: *std.Build) void {
    ...

    const build_options = b.addOptions();
    build_options.addOption(D, "D", .{});

    ...

    exe.root_module.addOptions("build_options", build_options);

    ...
}
```
the compiler crashes.

Output:
```
/tmp/zig/Test # ../build/stage4/bin/zig build --debug
Semantic Analysis [2361] thread 323 panic: index out of bounds: index 0, len 0
Analyzing /tmp/zig/Test/build.zig: build.zig:build
    > %69 = struct_init_empty_result(%64) node_offset:27:37 to :27:40
      %70 = break_inline(%64, %69)
    For full context, use the command
      zig ast-check -t /tmp/zig/Test/build.zig

  in /tmp/zig/Test/build.zig: build.zig:build
    > %64 = field_call(nodiscard .auto, %61, "addOption", [
        {%65, %66},
        {%67, %68},
        {%69, %70},
      ]) node_offset:27:5 to :27:41
  in /tmp/zig/Test/build.zig: build.zig:build
    > %33 = block({%34..%171}) node_offset:21:34 to :21:34

/tmp/zig/src/Sema.zig:19966:71: 0x26a16fe in finishStructInit (zig)
                    const field_name = struct_type.field_names.get(ip)[i];
                                                                      ^
/tmp/zig/src/Sema.zig:19661:33: 0x2203ce6 in structInitEmpty (zig)
    return sema.finishStructInit(block, init_src, dest_src, field_inits, struct_ty, struct_ty, false);
                                ^
/tmp/zig/src/Sema.zig:19629:44: 0x213bb12 in zirStructInitEmptyResult (zig)
        .Struct => try sema.structInitEmpty(block, obj_ty, src, src),
                                           ^
/tmp/zig/src/Sema.zig:1110:79: 0x1d18d90 in analyzeBodyInner (zig)
            .struct_init_empty_result     => try sema.zirStructInitEmptyResult(block, inst, false),
                                                                              ^
/tmp/zig/src/Sema.zig:939:45: 0x1a602c1 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/tmp/zig/src/Sema.zig:888:50: 0x2650420 in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 ^
/tmp/zig/src/Sema.zig:7047:59: 0x2bbb475 in analyzeArg (zig)
                const uncoerced_arg = try sema.resolveBody(block, arg_body, zir_call.call_inst);
                                                          ^
/tmp/zig/src/Sema.zig:7979:49: 0x2bbe13a in instantiateGenericCall (zig)
        const arg_ref = try args_info.analyzeArg(sema, block, arg_index, param_ty, generic_owner_ty_info, func);
                                                ^
/tmp/zig/src/Sema.zig:7278:40: 0x2657a6f in analyzeCall (zig)
        if (sema.instantiateGenericCall(
                                       ^
/tmp/zig/src/Sema.zig:6758:43: 0x21082f5 in zirCall__anon_98805 (zig)
    const call_inst = try sema.analyzeCall(block, func, func_ty, callee_src, call_src, modifier, ensure_result_used, args_info, call_dbg_node, .call);
                                          ^
/tmp/zig/src/Sema.zig:1034:62: 0x1d15522 in analyzeBodyInner (zig)
            .field_call                   => try sema.zirCall(block, inst, .field),
                                                             ^
/tmp/zig/src/Sema.zig:5918:34: 0x2698bc7 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/tmp/zig/src/Sema.zig:5901:33: 0x21c2238 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/tmp/zig/src/Sema.zig:1598:49: 0x1d25fd3 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[@intFromEnum(inst)] == .block_comptime);
                                                ^
/tmp/zig/src/Sema.zig:922:30: 0x2021688 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/tmp/zig/src/Module.zig:4587:21: 0x1cf2d1a in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/tmp/zig/src/Module.zig:3272:40: 0x1a3e479 in ensureFuncBodyAnalyzed (zig)
            var air = zcu.analyzeFnBody(func_index, sema_arena) catch |err| switch (err) {
                                       ^
/tmp/zig/src/Compilation.zig:3531:42: 0x1a3c6cf in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/tmp/zig/src/Compilation.zig:3468:30: 0x180254f in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
/tmp/zig/src/Compilation.zig:2180:31: 0x17fe105 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/tmp/zig/src/main.zig:4474:24: 0x182da7c in updateModule (zig)
        try comp.update(main_progress_node);
                       ^
/tmp/zig/src/main.zig:5556:21: 0x186b171 in cmdBuild (zig)
        updateModule(comp, color) catch |err| switch (err) {
                    ^
/tmp/zig/src/main.zig:293:24: 0x164ba2a in mainArgs (zig)
        return cmdBuild(gpa, arena, cmd_args);
                       ^
/tmp/zig/src/main.zig:223:20: 0x16486d5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/tmp/zig/lib/std/start.zig:585:37: 0x1648156 in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7c36876a86d0 in ??? (ld-musl-x86_64.so.1)
Unwind information for `ld-musl-x86_64.so.1:0x7c36876a86d0` was not available, trace may be incomplete

???:?:?: 0x7fff7ce79f20 in ??? (???)
Aborted (core dumped)
```

### Expected Behavior

An error message like "missing struct field".

**Comment by xdBronch** [comment] 2024-01-24 18:05
i believe this is a duplicate of #18609

**Comment by Vexu** [comment] 2024-01-25 11:52
It is duplicate.

**Closed by Vexu** 2024-01-25 11:52 UTC
Labels: bug
