### ISSUE TITLE
Runtime comparison with @sizeOf(struct) triggers assertion in the compiler.

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#12626] opened 2022-08-25 07:29 UTC
### Zig Version

0.10.0-dev.3736+7453f56e6

### Steps to Reproduce

`zig test` the following code:
```zig
test {
    var val: usize = 0; // runtime value
    _ = (@sizeOf(Struct) == val);
}

pub const Struct = extern struct { some: u8 };
```

### Expected Behavior

All 1 tests passed.

### Actual Behavior

```
thread 16124 panic: reached unreachable code
Analyzing wtf.zig: wtf.zig:test_0
      %2 = dbg_block_begin())
      %3 = dbg_stmt(2, 5)
      %4 = alloc_mut(@Zir.Inst.Ref.usize_type) node_offset:2:5 to :2:23
      %5 = store_node(%4, @Zir.Inst.Ref.zero) node_offset:2:22 to :2:23
      %6 = dbg_var_ptr(%4, "val")
      %7 = dbg_stmt(3, 5)
      %8 = decl_val("Struct") token_offset:3:18 to :3:24
      %9 = size_of(%8) node_offset:3:10 to :3:25
      %10 = load(%4) node_offset:3:29 to :3:32
    > %11 = cmp_eq(%9, %10) node_offset:3:10 to :3:32
      %13 = dbg_block_end())
      %12 = ensure_result_non_error(%11) node_offset:3:10 to :3:32
      %14 = ret_tok(@Zir.Inst.Ref.void_value) token_offset:4:1 to :4:2
    For full context, use the command
      zig ast-check -t wtf.zig


/home/felix/projects/forks/zig/build/stage1/lib/zig/std/debug.zig:281:14: 0x300beb3 in assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
/home/felix/projects/forks/zig/src/type.zig:5701:45: 0x359dc9d in structFieldOffset (zig)
                assert(struct_obj.haveLayout());
                                            ^
/home/felix/projects/forks/zig/src/type.zig:3252:75: 0x340539f in abiSizeAdvanced (zig)
                    return AbiSizeAdvanced{ .scalar = ty.structFieldOffset(field_count, target) };
                                                                          ^
/home/felix/projects/forks/zig/src/type.zig:3169:32: 0x3136d48 in abiSize (zig)
        return (abiSizeAdvanced(ty, target, .eager) catch unreachable).scalar;
                               ^
/home/felix/projects/forks/zig/src/value.zig:1101:37: 0x3775588 in toBigIntAdvanced (zig)
                const x = ty.abiSize(target);
                                    ^
/home/felix/projects/forks/zig/src/value.zig:1058:36: 0x359e287 in toBigInt (zig)
        return val.toBigIntAdvanced(space, target, null) catch unreachable;
                                   ^
/home/felix/projects/forks/zig/src/value.zig:1759:37: 0x3fe0091 in intBitCountTwosComp (zig)
                return self.toBigInt(&buffer, target).bitCountTwosComp();
                                    ^
/home/felix/projects/forks/zig/src/Sema.zig:26648:51: 0x3d8b652 in cmpNumeric (zig)
            lhs_bits = lhs_val.intBitCountTwosComp(target);
                                                  ^
/home/felix/projects/forks/zig/src/Sema.zig:13435:31: 0x3b813ba in analyzeCmp (zig)
        return sema.cmpNumeric(block, src, lhs, rhs, op, lhs_src, rhs_src);
                              ^
/home/felix/projects/forks/zig/src/Sema.zig:13354:27: 0x38cfda2 in zirCmpEq (zig)
    return sema.analyzeCmp(block, src, lhs, rhs, op, lhs_src, rhs_src, true);
                          ^
/home/felix/projects/forks/zig/src/Sema.zig:728:104: 0x370ab30 in analyzeBodyInner (zig)
            .cmp_eq                       => try sema.zirCmpEq(block, inst, .eq, Air.Inst.Tag.fromCmpOp(.eq, block.float_mode == .Optimized)),
                                                                                                       ^
/home/felix/projects/forks/zig/src/Sema.zig:609:30: 0x3708dc8 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/felix/projects/forks/zig/src/Module.zig:5534:21: 0x3560ea3 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/felix/projects/forks/zig/src/Module.zig:4245:40: 0x3362fe4 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/felix/projects/forks/zig/src/Compilation.zig:2974:42: 0x3361532 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/felix/projects/forks/zig/src/Compilation.zig:2912:30: 0x32588ee in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/felix/projects/forks/zig/src/Compilation.zig:2253:31: 0x32551e5 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/felix/projects/forks/zig/src/main.zig:3334:20: 0x327f2a6 in updateModule (zig)
    try comp.update();
                   ^
/home/felix/projects/forks/zig/src/main.zig:3008:17: 0x302ea22 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/felix/projects/forks/zig/src/main.zig:236:31: 0x300994b in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/felix/projects/forks/zig/src/main.zig:174:20: 0x3008d90 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/felix/projects/forks/zig/build/stage1/lib/zig/std/start.zig:576:37: 0x300b2c9 in main (zig)
            const result = root.main() catch |err| {
```

## Additional information:

Making `val` `comptime`-known makes the test go "ok":
```zig
test {
    const val: usize = 0; // runtime value
    _ = (@sizeOf(Struct) == val);
}

pub const Struct = extern struct { some: u8 };
```

My guess is that `@sizeOf()` is evaluated with lazy evaluation of the struct and thus the compiler is not able to compute the size as the struct wasn't evaluated yet.

Replacing the type in `@sizeOf` with a `union(enum)`, `union`, `enum(u8)`, `u32`, `packed struct` does not trigger the error. I can only reproduce it with `struct` or `extern struct`.

**Comment by MasterQ32** [comment] 2022-08-25 08:44
Additional information:
Storing the result of `@sizeOf()` into a runtime value or forcing it otherwise to become *runtime known* resolves the problem

**Comment by Vexu** [comment] 2022-08-25 09:00
Duplicate of #12498

**Closed by Vexu** 2022-08-25 09:00 UTC
Labels: bug
