### ISSUE TITLE
Segmentation fault when trying to inline `std.fmt.format` in a complex project

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#16362] opened 2023-07-08 21:09 UTC
### Zig Version

0.11.0-dev.3939+9c2db36e9

### Steps to Reproduce and Observed Behavior

Alright so the easiest reproduction I found is a bit more involved:
Edit `src/main.zig` inside the compiler (it also works in other projects) and add the following code to the start of the main() function:
```zig
// Line before: pub fn main() anyerror!void {
	var buf: [4096]u8 = undefined;
	var writer = std.io.fixedBufferStream(&buf);
	try @call(.always_inline, std.fmt.format, .{writer.writer(), "abc", .{}});
	
// Line after:    crash_report.initialize();
```

Compile the compiler. Here is the command I ran, llvm prefix and stuff might be different on your machine:
```
$ ./stage3/bin/zig build --search-prefix ~/zig-bootstrap/out/x86_64-linux-gnu-native/ --zig-lib-dir lib -Dstatic-llvm -p stage4
LLVM Emit Object... 
!dbg attachment points at wrong subprogram for function
!107898 = distinct !DISubprogram(name: "format__anon_60831", linkageName: "SemanticVersion.format__anon_60831", scope: !6636, file: !6636, line: 153, type: !107899, scopeLine: 158, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2, retainedNodes: !107901)
ptr @SemanticVersion.format__anon_60831
  %63 = getelementptr inbounds %SemanticVersion, ptr %1, i32 0, i32 4, !dbg !108005
!108005 = !DILocation(line: 163, column: 13, scope: !107980)
!107980 = distinct !DILexicalBlock(scope: !107974, file: !1149, line: 162, column: 43)
!107975 = distinct !DISubprogram(name: "format", linkageName: "fmt.format", scope: !1149, file: !1149, line: 79, type: !29816, scopeLine: 83, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2, retainedNodes: !107976)

thread 18831 panic: LLVM module verification failed
/home/mint/zig/src/codegen/llvm.zig:795:17: 0x88ae37a in flushModule (zig)
                @panic("LLVM module verification failed");
                ^
/home/mint/zig/src/link/Elf.zig:1031:47: 0x88cc042 in flushModule (zig)
            return try llvm_object.flushModule(comp, prog_node);
                                              ^
/home/mint/zig/src/link/Elf.zig:1325:29: 0x88c1fb7 in linkWithLLD (zig)
        try self.flushModule(comp, prog_node);
                            ^
/home/mint/zig/src/link/Elf.zig:1017:32: 0x866b4c6 in flush (zig)
        return self.linkWithLLD(comp, prog_node);
                               ^
/home/mint/zig/src/link.zig:790:68: 0x840f2d8 in flush (zig)
            .elf => return @fieldParentPtr(Elf, "base", base).flush(comp, prog_node),
                                                                   ^
/home/mint/zig/src/Compilation.zig:2169:24: 0x840eb35 in flush (zig)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/home/mint/zig/src/Compilation.zig:2133:27: 0x84120f2 in update (zig)
            try comp.flush(main_progress_node);
                          ^
/home/mint/zig/src/main.zig:3862:24: 0x8441ec4 in updateModule (zig)
            },
                       ^
/home/mint/zig/src/main.zig:4503:21: 0x82c43ad in cmdBuild (zig)
            fatal("unable to create compilation: {s}", .{@errorName(err)});
                    ^
/home/mint/zig/src/main.zig:285:24: 0x8266ef2 in mainArgs (zig)
        mem.eql(u8, cmd, "ar"))
                       ^
/home/mint/zig/src/main.zig:213:20: 0x8263705 in main (zig)
            @panic("only build-exe or build-obj is supported in a -Donly-c build");
                   ^
/home/mint/zig/lib/std/start.zig:608:37: 0x8263103 in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7f75379a8082 in ??? (???)
Aborted (core dumped)
```

There seems to be some problem with the debug information.

### Expected Behavior

The compiler shouldn't crash.

**Comment by Vexu** [comment] 2023-07-09 10:40
Duplicate of #15668, removing the `always_inline` should make it work.

**Closed by Vexu** 2023-07-09 10:40 UTC
Labels: bug
