### ISSUE TITLE
Conditional export broken on master

### ISSUE THREAD

**Issue by leroycep** [ziglang/zig#9326] opened 2021-07-07 08:56 UTC
On zig version `0.9.0-dev.401+cff7ecee0`, conditionally exporting a function does not work. The function will always be exported, which can cause issues if, for example, the exported function is exported by other code for different targets. the following code produces an error at the linking stage when building for `x86_64-linux-gnu`:

```zig
const std = @import("std");
const builtin = @import("builtin");

fn main() void {
    std.log.info("hello, world", .{});
}

usingnamespace if (builtin.cpu.arch == .wasm32) struct {
    // Misc stuff for web support
    extern fn log_write(str_ptr: [*]const u8, str_len: usize) void;
    extern fn log_flush() void;

    fn logWrite(write_context: void, bytes: []const u8) error{}!usize {
        _ = write_context;

        log_write(bytes.ptr, bytes.len);
        return bytes.len;
    }

    fn logWriter() std.io.Writer(void, error{}, logWrite) {
        return .{ .context = {} };
    }

    pub fn log(
        comptime message_level: std.log.Level,
        comptime scope: @Type(.EnumLiteral),
        comptime format: []const u8,
        args: anytype,
    ) void {
        const writer = logWriter();
        defer log_flush();
        writer.print("[{s}][{s}] ", .{ std.meta.tagName(message_level), std.meta.tagName(scope) }) catch {};
        writer.print(format, args) catch {};
    }

    pub export fn _start() callconv(.C) void {
        main();
    }
} else struct {};
```

The error is as follows:

```
❯ zig build-exe conditional_export.zig
/home/geemili/.local/share/zigup/0.9.0-dev.401+cff7ecee0/files/lib/std/start.zig:79:54: error: exported symbol collision: '_start'
                if (!@hasDecl(root, start_sym_name)) @export(_start, .{ .name = start_sym_name });
                                                     ^
./conditional_export.zig:36:9: note: other symbol here
    pub export fn _start() callconv(.C) void {
        ^
/home/geemili/.local/share/zigup/0.9.0-dev.401+cff7ecee0/files/lib/std/start.zig:467:45: error: 'main' is private
    switch (@typeInfo(@typeInfo(@TypeOf(root.main)).Fn.return_type.?)) {
                                            ^
./conditional_export.zig:4:1: note: declared here
fn main() void {
^
```

Building a library for wasm32 works as expected:
```
/tmp
❯ zig build-lib -target wasm32-freestanding conditional_export.zig

/tmp
❯ ls conditional_export.*
conditional_export.wasm  conditional_export.zig
```

__Edit:__ I did find a work around. If you create a function that exports the symbol, and then call it in a comptime block where it is protected by an if statement, you can get zig to not export the function:

```zig
    comptime {
        if (builtin.cpu.arch == .wasm32)
            entrypoint(main);
    }

    pub fn entrypoint(comptime f: fn () void) void {
        _ = struct {
            export fn _start() void {
                f();
            }
        };
    }
````

**Comment by Vexu** [comment] 2021-08-06 07:05
Duplicate of #3778.

**Closed by Vexu** 2021-08-06 07:05 UTC
