### ISSUE TITLE
Infinite loop with memory allocation on compiling function returning `!noreturn`.

### ISSUE THREAD

**Issue by vi** [ziglang/zig#3263] opened 2019-09-20 07:57 UTC
```
$ cat q.zig 
pub fn main() !noreturn {
    return error.Eee;
}
$ ulimit -v 1000000
$ zig build-exe q.zig |& head -n 10
allocation failed���cT��c ��[T���cT X�c�H�c����`�cTx�cT��cT��cT��cT�a�cTP�cT��cT��cT@�cTa�`8�c -�cT��cTVv'YT������������cT���cT@W�[T`�cT�cT�AA��/�cT���cT@W�[T`�cT�cT�AA��1�cT���cT@W�[T`�cT�cT�AA� 3�cT���cT@W�[T`�cT�cT�AA��4�cT���cT@W�[T`��cT�cT�AA� 7�cT���cT@W�[T`cT�cT�AA��8�cT���cT@W�[T`�cT�cT�AA��c���cT	���cT(�cT���cT����)�cT���cTVv'YT�a`
$ zig version
0.4.0+c6e77f24
```

**Comment by Vexu** [comment] 2022-01-29 16:19
Closing as duplicate of #3461 which has more discussion.

**Closed by Vexu** 2022-01-29 16:19 UTC
Labels: bug, stage1
