### ISSUE TITLE
Compiler returns error code 3 and no error message when doing comparison with left bit-shift

### ISSUE THREAD

**Issue by cheeze42** [ziglang/zig#12654] opened 2022-08-28 02:42 UTC
### Zig Version

0.10.0-dev.3685+dae7aeb33

### Steps to Reproduce

Try to compile and run the following Zig snippet:

```zig
pub fn main() anyerror!void {
    var foo: usize = 0;
    var bar: bool = 0 < 1 << foo;
    _ = bar;
}
```

### Expected Behavior

Either the program should compile or give a descriptive compile error as to why it isn't a valid Zig program.

### Actual Behavior

I get the following error message:

```
C:\Users\cheeze42\ZigProjects\Testing>zig build run
error: Testing...
error: The following command exited with error code 3:
C:\Program Files\Zig\zig.exe build-exe C:\Users\cheeze42\ZigProjects\Testing\src\main.zig --cache-dir C:\Users\cheeze42\ZigProjects\Testing\zig-cache --global-cache-dir C:\Users\cheeze42\AppData\Local\zig --name Testing --enable-cache
error: the following build command failed with exit code 3:
C:\Users\cheeze42\ZigProjects\Testing\zig-cache\o\cfff6d499e69f6ba7db410da28b1e942\build.exe C:\Program Files\Zig\zig.exe C:\Users\cheeze42\ZigProjects\Testing C:\Users\cheeze42\ZigProjects\Testing\zig-cache C:\Users\cheeze42\AppData\Local\zig run
```

**Comment by Vexu** [comment] 2022-08-28 08:16
Duplicate of #12290 (`<<` and `@shlExact` are implemented in the same function).

**Closed by Vexu** 2022-08-28 08:16 UTC
Labels: bug
