### ISSUE TITLE
Coercion of `[][*:0]u8` to `[][*:0]const u8` in function call causes broken LLVM module

### ISSUE THREAD

**Issue by ifreund** [ziglang/zig#7807] opened 2021-01-17 19:29 UTC
Minimal reproducer:
```zig
const std = @import("std");
pub fn main() void {
    std.debug.print("{}\n", .{foo(std.os.argv)});
}
fn foo(bar: [][*:0]const u8) usize {
    return bar.len;
}
```
Result:
```
./build/zig version
0.8.0-dev.1000+3562edf13

./build/zig run /tmp/foo.zig                    
Code Generation [219/549] std.fs.path.joinSep... broken LLVM module found: Call parameter type does not match function signature!
%"[][*:0]u8"* @argv
 %"[][*:0]const u8"*  %1 = call fastcc i64 @foo(%"[][*:0]u8"* @argv), !dbg !15972

This is a bug in the Zig compiler.thread 7675 panic: 
Unable to dump stack trace: debug info stripped
zsh: abort      ./build/zig run /tmp/foo.zig
```

**Comment by ifreund** [comment] 2021-01-17 19:40
Note that this works:
```zig
const std = @import("std");
pub fn main() void {
    const argv: [][*:0]const u8 = std.os.argv;
    std.debug.print("{}\n", .{foo(argv)});
}
fn foo(bar: [][*:0]const u8) usize {
    return bar.len;
}
```
but removing the const causes it to fail again:
```zig
const std = @import("std");
pub fn main() void {
    const argv: [][*:0]u8 = std.os.argv;
    std.debug.print("{}\n", .{foo(argv)});
}
fn foo(bar: [][*:0]const u8) usize {
    return bar.len;
}
```

**Comment by Vexu** [comment] 2021-01-26 16:39
Duplicate of #4907, #4123, #6147.

**Closed by Vexu** 2021-01-26 16:39 UTC
