### ISSUE TITLE
It can't recognize the identifier of itself in the param(`self`) type, for the methods of enum declared in a block.

### ISSUE THREAD

**Issue by mdisprgm** [ziglang/zig#18707] opened 2024-01-27 14:41 UTC
### Zig Version

0.12.0-dev.2334+aef1da163

### Steps to Reproduce and Observed Behavior

![image](https://github.com/ziglang/zig/assets/49188795/5fc4ab7e-0bdf-4c4c-914d-a1adebaaec7b)
```zig
pub fn main() void {
    const Suit = enum {
        var Joker: u32 = 0x1234;
        clubs,
        spades,
        diamonds,
        hearts,
        pub fn isClubs(self: Suit) bool {
            return self == Suit.clubs;
        }
    };
    _ = Suit; // autofix
}
```
```
src\main.zig:56:30: error: use of undeclared identifier 'Suit'
        pub fn isClubs(self: Suit) void {
                             ^~~~
error: the following command failed with 1 compilation errors:
C:\Program Files\Zig\zig-windows-x86_64-0.12.0-dev.2334+aef1da163\zig.exe build-exe -ODebug -Mroot=C:\Users\username\learnzig\src\main.zig --cache-dir C:\Users\username\learnzig\zig-cache --global-cache-dir C:\Users\username\AppData\Local\zig --name learnzig --listen=- 
Build Summary: 2/5 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install learnzig transitive failure
   └─ zig build-exe learnzig Debug native 1 errors
error: the following build command failed with exit code 1:
C:\Users\username\learnzig\zig-cache\o\a4dedae2f71496d44a8a14c69cb4abfe\build.exe C:\Program Files\Zig\zig-windows-x86_64-0.12.0-dev.2334+aef1da163\zig.exe C:\Users\username\learnzig C:\Users\username\learnzig\zig-cache C:\Users\username\AppData\Local\zig --seed 0x87635ca7
```

### Expected Behavior

No errors in that code.

**Comment by Vexu** [comment] 2024-01-27 14:53
Duplicate of #8222

Variables in functions are not order independent so `Suit` is not declared before it's initializer has been analyzed. Use `@This()` to get the enum type.

**Closed by Vexu** 2024-01-27 14:53 UTC
Labels: bug

**Comment by mdisprgm** [comment] 2024-01-27 15:18
oh I searched only "enum"..
thank you.
