### ISSUE TITLE
Zig build run   fails on Raspberry Pi 5

### ISSUE THREAD

**Issue by curuvar** [ziglang/zig#18819] opened 2024-02-04 22:53 UTC
### Zig Version

 0.12.0-dev.2550+a65bc8d07

### Steps to Reproduce and Observed Behavior

To Reproduce in Ras Pi 5:

  
  mkdir zig-test
  cd zig-test
  zig init
  zig build run

zig goes through the build process and then stops with:

thread 1998 panic: reached unreachable code
Panicked during a panic. Aborting.
error: the following build command crashed:
/home/craig/zig-test/zig-cache/o/5ab4d18f2ddd1ccfdec54cc769e36159/build /opt/zig-linux-aarch64-0.12.0-dev.2550+a65bc8d07/zig /home/craig/zig-test /home/craig/zig-test/zig-cache /home/craig/.cache/zig --seed 0x33ed21e0 run

I have also tried with zig 0.11.0 with equivalent results.

I followed exact same procedure on a Raspberry Pi 4B (with same OS version) and it worked fine.

As a side node running the code with:

  zig run src/main.zig  

works as expected on both platforms.

### Expected Behavior

See:  All your codebase are belong to us.

**Comment by RossComputerGuy** [comment] 2024-02-04 22:57
Known issue, will be resolved once #17382 is merged.

**Comment by curuvar** [comment] 2024-04-25 19:11
Perhaps dupe of #16331

**Comment by andrewrk** [comment] 2024-08-15 07:36
Dupe of  #16331

**Closed by andrewrk** 2024-08-15 07:36 UTC
Labels: bug

**Comment by bfreis** [comment] 2024-11-14 10:29
FWIW, if you're willing to change your Pi 5 configuration, it's possible to work around this issue.

By adding `kernel=kernel8.img` to `/boot/firmware/config.txt`, you instruct the Pi 5 to load kernel8.img instead of kernel_2712.img. The kernel8.img is configured with 4k page size, while the 2712, specific for the Pi 5, is configured with 16k page size. When I made the change and rebooted, I was able to use Zig build just fine.
