### ISSUE TITLE
Packed struct padding bits can cause incorrect values to be observed

### ISSUE THREAD

**Issue by cdwfs** [ziglang/zig#13480] opened 2022-11-07 18:14 UTC
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

I ran into this issue while converting my 2021 Advent of Code solutions from Zig 0.9.1 to 0.10.0. I originally reported the problem on Discord; see [the thread](https://discord.com/channels/605571803288698900/1038579728883392584/1038878085715591358) for additional details.

Build the attached `day08.zig` source using `zig build-exe day08.zig`, and run the resulting `day08.exe`. The assert on line 108 will fire, indicating that the loop directly above the assert did not run correctly.
```
>day08.exe
thread 13716 panic: reached unreachable code
C:\users\Me\bin\zig\lib\std\debug.zig:278:14: 0x7ff70ff432c0 in assert (day08.exe.obj)
    if (!ok) unreachable; // assertion failure
             ^
C:/Users/Me/Downloads/day08.zig:108:15: 0x7ff70ff42452 in part2 (day08.exe.obj)
        assert(digit_index_for_numeral[9] >= 0 and digit_index_for_numeral[9] < 10);
```
Now make nearly any change to the surrounding code, such as uncommenting the `load_bearing_bool` definition directly above the loop on lines 95-96. Build and run again, and note that the loop now runs correctly; the assert does not fire.

Note that if `-fstage1` is passed at build time to opt into the Bootstrap Compiler, the original unmodified code works as expected.
[day08.zip](https://github.com/ziglang/zig/files/9954379/day08.zip)

### Expected Behavior

The assert on line 108 should not trigger, regardless of whether unrelated/unused variables are defined, or `print()` is called to inspect variable values, etc.

**Comment by cdwfs** [comment] 2022-11-07 18:17
@SpexGuy poked at the source for a while and simplified it a bit further; the modified repro case is attached. The repro steps are basically the same.
> This is a fun version.  It asserts that:
> 1. mask_a has one bit set
> 2. mask_a has three trailing zeros
> 3. mask_a is 0b0001000
> 
> 1 and 2 pass, 3 fails xD

[day08-alt.zip](https://github.com/ziglang/zig/files/9954384/day08-alt.zip)

**Comment by Vexu** [comment] 2022-11-07 19:29
Cannot reproduce on latest master.

**Comment by cdwfs** [comment] 2022-11-07 21:36
I just tested on `0.11.0-dev.86+b83e4d965` and can still reproduce the issue. If anything it's even weirder with this version: with the `load_bearing_bool` lines uncommented, the assert still fires, but only about 50% of the time (even just running the same `day08.exe` repeatedly). Without the lines uncommented, the assert still seems to fire 100% of the time.

**Comment by SpexGuy** [comment] 2022-11-07 22:16
I think both cdwfs and I are using Windows, it's possible that the bug only repros on that system.  (though that would be somewhat strange since the program shouldn't use any OS APIs aside from VirtualAlloc).  Given the instability of the bug, it's also possible that recent compiler changes have jostled things enough to mask it without fixing it.

**Comment by Vexu** [comment] 2022-11-07 22:51
Can't reproduce on `0.11.0-dev.86+b83e4d965` either.

> though that would be somewhat strange since the program shouldn't use any OS APIs aside from VirtualAlloc

Can you try using a fixed buffer allocator?

**Comment by cdwfs** [comment] 2022-11-08 00:07
@Vexu To clarify, when you say "can't reproduce", do you mean you don't see the assert firing at all? Or that it's firing consistently, whether any other changes are made to the file?

> Can you try using a fixed buffer allocator?
Sure -- I replaced lines 183-185 (the arena allocator) with
```
var buffer: [1020*1024]u8 = undefined;
var fba = std.heap.FixedBufferAllocator.init(&buffer);
const allocator = fba.allocator();
```
and this does indeed seem to stop the assert from firing. But on the other hand, on my machine, so does defining an unrelated `bool` variable that's never used, or adding `print()` calls, or initializing the `mask_*` variables with their constant values directly instread of computing them at runtime. So I'm not sure how much I'd read into this :)

I feel like the appropriate next step is to look at the generated code for the `part2()` function with and without the "meaningless" changes, to see if anything looks suspicious. Is there a way to have Zig spit out that information directly?

**Comment by SpexGuy** [comment] 2022-11-08 00:36
This is really freaky.  I just reproed the inconsistency you were mentioning.  This is all the same executable:
<details>
<summary>Console log, collapsed</summary>

```
D:\Stuff $ day08.exe
thread 26852 panic: reached unreachable code
C:\Program Files\Zig\Current\lib\std\debug.zig:278:14: 0x7ff7942b38f0 in assert (day08.exe.obj)
    if (!ok) unreachable; // assertion failure
             ^
D:/Stuff/day08.zig:101:15: 0x7ff7942b24c9 in part2 (day08.exe.obj)
        assert(mask_a.mask == 0b0001000);
              ^
D:/Stuff/day08.zig:223:27: 0x7ff7942b1d35 in testPart2 (day08.exe.obj)
    var result:i64 = part2(test_input);
                          ^
D:/Stuff/day08.zig:231:18: 0x7ff7942b341d in main (day08.exe.obj)
    try testPart2(allocator);
                 ^
C:\Program Files\Zig\Current\lib\std\start.zig:377:41: 0x7ff7942b35e7 in WinStartup (day08.exe.obj)
    std.debug.maybeEnableSegfaultHandler();
                                        ^
???:?:?: 0x7fff2f707033 in ??? (???)
???:?:?: 0x7fff308e26a0 in ??? (???)

D:\Stuff $ day08.exe
a: 1000
result: 0

D:\Stuff $ day08.exe
thread 23048 panic: reached unreachable code
C:\Program Files\Zig\Current\lib\std\debug.zig:278:14: 0x7ff7942b38f0 in assert (day08.exe.obj)
    if (!ok) unreachable; // assertion failure
             ^
D:/Stuff/day08.zig:101:15: 0x7ff7942b24c9 in part2 (day08.exe.obj)
        assert(mask_a.mask == 0b0001000);
              ^
D:/Stuff/day08.zig:223:27: 0x7ff7942b1d35 in testPart2 (day08.exe.obj)
    var result:i64 = part2(test_input);
                          ^
D:/Stuff/day08.zig:231:18: 0x7ff7942b341d in main (day08.exe.obj)
    try testPart2(allocator);
                 ^
C:\Program Files\Zig\Current\lib\std\start.zig:377:41: 0x7ff7942b35e7 in WinStartup (day08.exe.obj)
    std.debug.maybeEnableSegfaultHandler();
                                        ^
???:?:?: 0x7fff2f707033 in ??? (???)
???:?:?: 0x7fff308e26a0 in ??? (???)

D:\Stuff $ day08.exe
a: 1000
result: 0

D:\Stuff $ day08.exe
a: 1000
result: 0

D:\Stuff $ day08.exe
thread 18692 panic: reached unreachable code
C:\Program Files\Zig\Current\lib\std\debug.zig:278:14: 0x7ff7942b38f0 in assert (day08.exe.obj)
    if (!ok) unreachable; // assertion failure
             ^
D:/Stuff/day08.zig:101:15: 0x7ff7942b24c9 in part2 (day08.exe.obj)
        assert(mask_a.mask == 0b0001000);
              ^
D:/Stuff/day08.zig:223:27: 0x7ff7942b1d35 in testPart2 (day08.exe.obj)
    var result:i64 = part2(test_input);
                          ^
D:/Stuff/day08.zig:231:18: 0x7ff7942b341d in main (day08.exe.obj)
    try testPart2(allocator);
                 ^
C:\Program Files\Zig\Current\lib\std\start.zig:377:41: 0x7ff7942b35e7 in WinStartup (day08.exe.obj)
    std.debug.maybeEnableSegfaultHandler();
                                        ^
???:?:?: 0x7fff2f707033 in ??? (???)
???:?:?: 0x7fff308e26a0 in ??? (???)

D:\Stuff $ day08.exe
a: 1000
result: 0
```

</details>

AFAIK the only things that could cause randomness in this program are
- address space layout randomization
- changes in pointer values returned by VirtualAlloc

So somehow the high bits of a pointer must be influencing the result.

I've attached the executable in case anyone wants to mess with it, I wonder if it repros under wine.
[day08.zip](https://github.com/ziglang/zig/files/9956521/day08.zip)

**Comment by SpexGuy** [comment] 2022-11-08 00:57
Figured it out.  The problem is the top bit of the u7.  Here's the relevant part of the disassembly:
```asm
; var mask_a = std.bit_set.IntegerBitSet(7){
;     .mask = display.digit_masks[digit_index_for_numeral[7]].mask ^ mask_cf.mask,
; };
    ; ...
    mov     cl, byte ptr [rsp+429h]
    and     cl, 80h
    or      al, cl
    mov     byte ptr [rsp+429h], al
; ...
; assert(mask_a.mask == 0b0001000);
    mov     al, byte ptr [rsp+429h]
    sub     al, 8
    sete    cl
    call    day08!assert (7ff7942b38c0)
```

When the u7 is written to memory, the write preserves the top bit for some reason.  Then later when it's read, the top bit isn't masked off.  So it gets whatever happened to be on the stack in the top bit, which I guess in this particular program happens to be a pointer, and memory space randomization causes it to sometimes be 1 and sometimes 0.  I'll see if I can come up with a more consistent repro.

**Comment by Vexu** [comment] 2022-11-23 16:00
Due to the integer backed packed struct semantics this is actually the same issue as #11263

**Comment by Validark** [comment] 2023-06-04 18:36
Not sure if this is the same issue @Vexu but I just ran into this:

```zig
const std = @import("std");

const Node = packed struct {
    const @"c/d" = packed struct(u40) {
        c: u32 = 0,
        d: u8 = 0,
    };

    const @"a/b" = packed struct(u40) {
        a: u32 = 0,
        b: u8 = 0,
    };

    @"a/b": @"a/b" = .{},
    @"c/d": @"c/d" = .{},

    pub fn init(d: u8) Node {
        return Node{
            // These fields work okay
            .@"a/b" = .{ .a = d, .b = d + 1 },
            // Writing to either of these fields will not work:
            .@"c/d" = .{ .c = d, .d = d + 1 },
        };
    }
};

pub fn main() !void {
    const node = Node.init(9);
    std.debug.print("{any}\n", .{node});
}
```

**Comment by jacobly0** [comment] 2023-07-29 09:06
Closing as a duplicate of the newer #14200 because I just so happened to fix that one first.  @SpexGuy's explanation perfectly matches the issue I fixed and that reduction crashes without my fix and succeeds with my fix.

**Closed by jacobly0** 2023-07-29 09:06 UTC
Labels: bug, frontend, miscompilation
