### ISSUE TITLE
Allow bitcast of comptime_int

### ISSUE THREAD

**Issue by Rageoholic** [ziglang/zig#6984] opened 2020-11-05 01:42 UTC
So in certain cases we may want to use a comptime int to describe a bit mask.  For example
```
const CW_USEDEFAULT = @bitCast(i32, 0x80000000);
```
but this isn't allowed. You also can't use 0x80000000 as a literal because it gets treated as the unsigned value and won't coerce to the signed value. That bit is probably correct but allowing a bitCast to be a back door to that seems like the right thing. And you can have a compile error if you truncate any bits.

**Comment by LemonBoy** [comment] 2020-11-05 08:44
Your real problem is trying to use a signed integer to hold a bitmask, the type system is trying to make sure you really know what you're doing by requiring something as verbose as
```zig
const CW_USEDEFAULT = @bitCast(i32, @as(u32, 0x80000000));
```

> That bit is probably correct but allowing a bitCast to be a back door to that seems like the right thing.

The right thing is using the proper type. A bitcast is a bit-by-bit reinterpretation of a given value, how it's supposed to work when a `comptime_int` has infinite bits?

**Comment by Rageoholic** [comment] 2020-11-06 02:01
Sometimes that's imposed on you by libraries. This is a windows constant that's required to be a signed integer.

**Comment by LemonBoy** [comment] 2020-11-06 06:50
> Sometimes that's imposed on you by libraries. This is a windows constant that's required to be a signed integer.

Then use the `as` plus `bitcast` combo or `math.minInt(u32)`.

**Comment by marler8997** [comment] 2020-11-12 18:04
@Rageoholic I ran into this exact issue with this exact windows constant just yesterday :)

I'm working on complete autogenerated windows bindings (https://github.com/marler8997/zig-os-windows).  My solution to this is I have a comptime function that handles all these cases:

https://github.com/marler8997/zig-os-windows/blob/3c1da1363191bf401f6e0686663d02918f77ec9f/src/gluezig.zig#L16

So it would look like this in code:
```
const CW_USEDEFAULT = typedConstant(i32, 0x80000000);
```

`typedConstant` detects that `0x80000000` cannot fit inside `i32`, so it tries to cast it to a `u32` and then bitcasts it to `i32`, which essentially becomes this:
```zig
return @bitCast(i32, @as(u32, 0x80000000));
```

It looks like @LemonBoy came up with the same solution and I agree is the correct solution here.

**Comment by thejoshwolfe** [comment] 2021-03-04 00:56
i found the constant in question in zig's own `lib/` directory.

https://github.com/ziglang/zig/blob/34ca6b7b449f065fd0f65f8cfad82140cafe4c7d/lib/libc/include/any-windows-any/winuser.h#L2169

https://github.com/ziglang/zig/blob/34ca6b7b449f065fd0f65f8cfad82140cafe4c7d/lib/std/os/windows/user32.zig#L361

so is this situation under control? am i missing something?

**Comment by marler8997** [comment] 2021-03-04 01:08
> so is this situation under control? am i missing something?

It looks like the author wanted to do this:

```zig
const CW_USEDEFAULT = @bitCast(i32, 0x80000000);
```

However, I'm not even sure what that is supposed to mean.  Because `0x80000000` has no explicit bit width so there's no "bit pattern" to cast.  I think I would close this as "working as intended".

**Comment by thejoshwolfe** [comment] 2021-03-04 03:55
Zig's `comptime_int` is intended to be more abstract and mathematical than any particular bit representation. To get a bitcast of an abstract numerical value, you first need to make it a bit-based value with `@as(u32, 0x80000000)`. Then you can do bitwise operations on the value.

The double-cast strategy used in `user32.zig` linked above is the intended way to accomplish the use case in the original post of this thread.

**Closed by thejoshwolfe** 2021-03-04 03:55 UTC
Labels: proposal
