### ISSUE TITLE
Forward --just-symbols to linker

### ISSUE THREAD

**Issue by fwsGonzo** [ziglang/zig#22273] opened 2024-12-19 20:37 UTC
### Zig Version

0.14.0-dev.2441+3670910f2

### Steps to Reproduce and Observed Behavior

I have an ELF file with just symbols (using objcopy --extract-symbol), which I am using in my GNU RISC-V toolchain. The problem is when trying to add the symbols to the final output using `--just-symbols`. `zig c++` seems to reject it:

```
error: unsupported linker arg: --just-symbols
```
Is this something that can be forwarded to the linker?

I tried to figure out if LLD supports that flag, and it does seem like it. Let me know if I'm wrong here.

### Expected Behavior

Hopefully it can be forwarded to the linker without too much work.

**Comment by alexrp** [comment] 2024-12-19 20:43
Duplicate of #22112.

**Closed by alexrp** 2024-12-19 20:43 UTC
Labels: bug
