### ISSUE TITLE
cImport macro error

### ISSUE THREAD

**Issue by danielabbott** [ziglang/zig#5045] opened 2020-04-15 11:33 UTC
Zig 0.6.0+1e23a3cd9

c.h:
```
void f(int a, int b);
#define RUN_F(a) f(a, 3)
```

main.zig:
```
const c = @cImport({
    @cInclude("c.h");
});

pub fn main() void {
    c.RUN_F(1);
}
```
Output:

```
.\zig-cache\o\5CMkFygIMJCNjKzWcOlbBfI0SsDBBSfjefYRfGv13kTgzxkYc_J1ltbJqEZ5p4tI\cimport.zig:117:37: error: unable to evaluate constant expression
pub inline fn RUN_F(a: var) @TypeOf(f(a, 3)) {
                                    ^
.\zig-cache\o\5CMkFygIMJCNjKzWcOlbBfI0SsDBBSfjefYRfGv13kTgzxkYc_J1ltbJqEZ5p4tI\cimport.zig:117:29: note: called from here
pub inline fn RUN_F(a: var) @TypeOf(f(a, 3)) {
                            ^
.\src\main.zig:5:20: note: called from here
pub fn main() void {
                   ^
.\zig-cache\o\5CMkFygIMJCNjKzWcOlbBfI0SsDBBSfjefYRfGv13kTgzxkYc_J1ltbJqEZ5p4tI\cimport.zig:117:38: note: referenced here
pub inline fn RUN_F(a: var) @TypeOf(f(a, 3)) {
                                     ^
.\src\main.zig:6:12: note: referenced here
    c.RUN_F(1);
           ^
zig_c_import_error...The following command exited with error code 1:
C:\Users\dabbo\zig\zig.exe build-exe C:\Users\dabbo\zig_c_import_error\src\main.zig --cache-dir C:\Users\dabbo\zig_c_import_error\zig-cache --name zig_c_import_error -I C:\Users\dabbo\zig_c_import_error\src --cache on

Build failed. The following command failed:
C:\Users\dabbo\zig_c_import_error\zig-cache\o\j5t--53Nh8xNyGsqIlIvz6E8bsLRUy2zq-arXBm6926PTlYlg0TlCcpNtSpEEwPp\build.exe C:\Users\dabbo\zig\zig.exe C:\Users\dabbo\zig_c_import_error C:\Users\dabbo\zig_c_import_error\zig-cache
```

Macros similar to this are in the OpenSSL headers which are where I found this bug.

**Comment by Vexu** [comment] 2020-04-15 11:41
Duplicate of #4328

**Closed by Vexu** 2020-04-15 11:41 UTC
