### ISSUE TITLE
Set cwd as cwd reaches unreachable

### ISSUE THREAD

**Issue by Guigui220D** [ziglang/zig#12876] opened 2022-09-16 17:03 UTC
### Zig Version

0.10.0-dev.4060+61aaef0b0

### Steps to Reproduce

Run this:
```zig
const std = @import("std");

pub fn main() !void {
    var cwd = std.fs.cwd();
    try cwd.setAsCwd();
}
```

I am on Linux

### Expected Behavior

Expected it to stay in the cwd (or go back to it, where I wanted to use that), without errors.

### Actual Behavior

``` 
thread 24144 panic: reached unreachable code
/snap/zig/5728/lib/std/os.zig:3012:22: 0x20d460 in fchdir (error)
            .BADF => unreachable,
                     ^
/snap/zig/5728/lib/std/fs.zig:1564:22: 0x20d3a2 in setAsCwd (error)
        try os.fchdir(self.fd);
                     ^
./error.zig:5:21: 0x20d597 in main (error)
    try cwd.setAsCwd();
                    ^
```

**Comment by yujiri8** [comment] 2022-09-16 22:35
Hmm. std.fs.cwd returns a constant defined in std.os.linux, AT.FDCWD, which is -100, a special value that supposedly means the current directory to the OS. However from looking at the man pages it looks like that constant is valid for openat, but not for fchdir.

**Comment by Guigui220D** [comment] 2022-09-17 10:10
Should it be possible then or should there just be a better error message?

**Comment by yujiri8** [comment] 2022-09-17 21:31
I'm not sure. Need to get someone with more knowledge in here than me.

**Comment by yujiri8** [comment] 2022-09-17 21:37
Seems to me like the expectable behavior is that std.fs.cwd returns a value that always represents the current directory at the time it was called, but that's not what AT.FDCWD does. I think there are two ways this could go:
* std.fs.Dir is changed to store a path string instead of an fd.
* std.fs.cwd makes a syscall to open the current working directory, getting an actual fd to it, whereas currently I think it doesn't make any syscalls.

Both options seem to have a downside. If I were in charge I'd go for the second one, but I'm not confident enough to make such a redesign without the approval of someone more involved with the project.

**Comment by ominitay** [comment] 2022-09-17 21:37
No, it shouldn't be possible. The cwd file descriptor has caused a number of problems, for example #9688. My suggestion would be for `std.fs.cwd()` to actually open cwd.

**Comment by matu3ba** [comment] 2022-09-19 00:54
> My suggestion would be for std.fs.cwd() to actually open cwd.

Why? `cwd().openDir(".", .{});` does the expected thing in a cross-platform and explicit way and sounds not ridicolously hard to teach.

To me this looks like this is missing better documentation, because `handle to the current working directory` is not factual correct in all cases and missing relevant information.

A hint to use `openDir(".", .{});` instead, if one wants to modify or "store" `cwd` for later usage sounds good.

**Comment by ominitay** [comment] 2022-09-19 16:36
Perhaps it is a documentation issue. I do think there should be some sort of safeguard here.

**Comment by Guigui220D** [comment] 2022-09-19 19:17
I don't know if it's just a documentation issue, it's clearly not an unreachable situation

**Comment by nektro** [comment] 2022-09-19 19:39
`unreachable` means programmer error, which is what this situation is (and a docs issue thats its not intended to work)

**Comment by Guigui220D** [comment] 2022-09-20 08:55
I probably misunderstood what unreachable was for 😅 then it makes sense

**Comment by gooncreeper** [comment] 2024-07-15 01:09
Cannot reproduce on master

**Comment by xdBronch** [comment] 2024-07-15 01:31
https://github.com/ziglang/zig/pull/17616 fixed it

**Comment by Vexu** [comment] 2024-07-15 08:11
Duplicate of #9688

**Closed by Vexu** 2024-07-15 08:11 UTC
Labels: bug, standard library, os-linux
