### ISSUE TITLE
All 1 tests passed. (Poor grammar)

### ISSUE THREAD

**Issue by DJ-Dav** [ziglang/zig#15049] opened 2023-03-22 17:57 UTC
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

zig test a file with 1 test that should pass
keel over and die at the sight of the abysmal grammar

### Expected Behavior

Grammar rules should be followed, and it should log out `The 1 test passed.`

**Comment by coffeebe4code** [comment] 2023-03-25 17:25
The complexity of handling the singular test case could be resolved with grammar like this.
`1 of 1 tests have passed`

I certainly wouldn't call this a bug, more of a feature request.

**Comment by andrewrk** [comment] 2023-04-10 17:24
This is a subjective preference, not a bug. You are welcome to submit a patch to the test runner with your proposed changes.

https://github.com/ziglang/zig/blob/311d50f9dc96c3d397081a1afcc3b519ae1e973f/lib/test_runner.zig#L200-L210

**Closed by andrewrk** 2023-04-10 17:24 UTC
