### ISSUE TITLE
stage3: compiler assertion failed when building a project

### ISSUE THREAD

**Issue by davidgm94** [ziglang/zig#12243] opened 2022-07-26 11:47 UTC
### Zig Version

0.10.0-dev.2620+93f24e929

### Steps to Reproduce

1. ```git clone https://github.com/davidgm94/RNU```
2. Run ```zig build``` on the project root directory with a stage3 binary.
3. You hit the assertion failure

### Expected Behavior

Project should build

### Actual Behavior

Building the project triggers a failure in a compiler assertion.

```
david@Davids-Air:~/dev/RNU$ ../try-zig/stage3/bin/zig build
Semantic Analysis [2270] stage2... thread 25630 panic: reached unreachable code
/Users/david/dev/try-zig/stage2/lib/zig/std/debug.zig:281:9: 0x10271316b in assert (zig)
    if (!ok) unreachable; // assertion failure
        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:5179:28: 0x102e96ba7 in airStructFieldVal (zig)
            assert(!isByRef(field_ty));
                           ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4163:64: 0x102ca7ab3 in genBody (zig)
                .struct_field_val => try self.airStructFieldVal(inst),
                                                               ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4681:25: 0x102e7abcf in airBlock (zig)
        try self.genBody(body);
                        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4094:53: 0x102ca6287 in genBody (zig)
                .block          => try self.airBlock(inst),
                                                    ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4744:25: 0x102e7d6db in airCondBr (zig)
        try self.genBody(then_body);
                        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4100:54: 0x102ca6493 in genBody (zig)
                .cond_br        => try self.airCondBr(inst),
                                                     ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4681:25: 0x102e7abcf in airBlock (zig)
        try self.genBody(body);
                        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4094:53: 0x102ca6287 in genBody (zig)
                .block          => try self.airBlock(inst),
                                                    ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4887:25: 0x102e8306b in airLoop (zig)
        try self.genBody(body);
                        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4109:52: 0x102ca685b in genBody (zig)
                .loop           => try self.airLoop(inst),
                                                   ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4681:25: 0x102e7abcf in airBlock (zig)
        try self.genBody(body);
                        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4094:53: 0x102ca6287 in genBody (zig)
                .block          => try self.airBlock(inst),
                                                    ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4747:25: 0x102e7d74f in airCondBr (zig)
        try self.genBody(else_body);
                        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4100:54: 0x102ca6493 in genBody (zig)
                .cond_br        => try self.airCondBr(inst),
                                                     ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4681:25: 0x102e7abcf in airBlock (zig)
        try self.genBody(body);
                        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4094:53: 0x102ca6287 in genBody (zig)
                .block          => try self.airBlock(inst),
                                                    ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4744:25: 0x102e7d6db in airCondBr (zig)
        try self.genBody(then_body);
                        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4100:54: 0x102ca6493 in genBody (zig)
                .cond_br        => try self.airCondBr(inst),
                                                     ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4681:25: 0x102e7abcf in airBlock (zig)
        try self.genBody(body);
                        ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:4094:53: 0x102ca6287 in genBody (zig)
                .block          => try self.airBlock(inst),
                                                    ^
/Users/david/dev/try-zig/src/codegen/llvm.zig:973:35: 0x102ca2e93 in updateFunc (zig)
        fg.genBody(air.getMainBody()) catch |err| switch (err) {
                                  ^
/Users/david/dev/try-zig/src/link/MachO.zig:3611:74: 0x102ca927b in updateFunc (zig)
        if (self.llvm_object) |llvm_object| return llvm_object.updateFunc(module, func, air, liveness);
                                                                         ^
/Users/david/dev/try-zig/src/link.zig:510:77: 0x102b3df57 in updateFunc (zig)
            .macho => return @fieldParentPtr(MachO, "base", base).updateFunc(module, func, air, liveness),
                                                                            ^
/Users/david/dev/try-zig/src/Module.zig:4148:37: 0x1029b3607 in ensureFuncBodyAnalyzed (zig)
            comp.bin_file.updateFunc(mod, func, air, liveness) catch |err| switch (err) {
                                    ^
/Users/david/dev/try-zig/src/Compilation.zig:2979:42: 0x1029b1e3b in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/Users/david/dev/try-zig/src/Compilation.zig:2911:30: 0x1028e588f in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/Users/david/dev/try-zig/src/Compilation.zig:2251:31: 0x1028e2ed3 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/Users/david/dev/try-zig/src/main.zig:3305:20: 0x102902f37 in updateModule (zig)
    try comp.update();
                   ^
/Users/david/dev/try-zig/src/main.zig:3897:21: 0x102739c2f in cmdBuild (zig)
        updateModule(gpa, comp, .none) catch |err| switch (err) {
                    ^
/Users/david/dev/try-zig/src/main.zig:250:24: 0x1027120f7 in mainArgs (zig)
        return cmdBuild(gpa, arena, cmd_args);
                       ^
/Users/david/dev/try-zig/src/main.zig:174:20: 0x102711483 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/david/dev/try-zig/stage2/lib/zig/std/start.zig:580:37: 0x1027128e3 in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x10ebe5087 in ??? (???)
???:?:?: 0x7d3d7fffffffffff in ??? (???)
Abort trap: 6
```

**Comment by Vexu** [comment] 2022-07-26 11:56
Duplicate of #12236

**Closed by Vexu** 2022-07-26 11:56 UTC
Labels: bug
