### ISSUE TITLE
`zig run` segfaults when using error.FooBar as parameter type

### ISSUE THREAD

**Issue by rbino** [ziglang/zig#11430] opened 2022-04-13 20:38 UTC
### Zig Version

0.10.0-dev.1757+b0edd8752

### Steps to Reproduce

Initialize a new exe with `zig init-exe` and replace `main.zig` with this (`divTrunc` can be replaced by any function that returns an error):

```zig
const std = @import("std");

pub fn main() anyerror!void {
    try std.math.divTrunc(u8, 4, 2) catch |err| handleErr(err);
}

pub fn handleErr(err: error.FooBar) !void {
    return err;
}
```

Compile with `zig build` or run with `zig run`

### Expected Behavior

This should either compile correctly or return a compiler error, I assume the latter. I ran into this because I was trying to use a specific error set as the type of a parameter and I used the wrong syntax.

### Actual Behavior

`zig build` fails with
```bash
$ zig build
test...The following command terminated unexpectedly:
/home/rbino/.asdf/installs/zig/master/zig build-exe /tmp/test/src/main.zig --cache-dir /tmp/test/zig-cache --global-cache-dir /home/rbino/.cache/zig --name test --enable-cache 
error: the following build command failed with exit code 11:
/tmp/test/zig-cache/o/b3df03cde0cf3690532440497b7c1e51/build /home/rbino/.asdf/installs/zig/master/zig /tmp/test /tmp/test/zig-cache /home/rbino/.cache/zig
```

`zig run` segfaults:
```bash
$ zig run src/main.zig
[1]    2062161 segmentation fault  zig run src/main.zig
```

**Comment by Vexu** [comment] 2022-04-14 10:32
Duplicate of #9887

**Closed by Vexu** 2022-04-14 10:32 UTC
Labels: bug
