### ISSUE TITLE
Tracking issue for bringing back async/await to Zig

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#18873] opened 2024-02-09 09:58 UTC
Since stage2 was shipped (536 days ago according to https://news.ycombinator.com/item?id=32529113, at the time of writing), `async` / `await` was removed from the language.

Will async / await return? 

Is there an existing issue where the status of async / await can be tracked? If there isn't an existing issue, maybe this could become that issue?

If there is an existing issue, feel free to close this and link to it. I tried searching but couldn't find an obvious one

**Comment by nektro** [comment] 2024-02-09 10:02
Duplicate of https://github.com/ziglang/zig/issues/6025

**Closed** 2024-02-09 10:07 UTC
