### ISSUE TITLE
Some ifs that ignore a captured bool take the if-branch even if the value is false

### ISSUE THREAD

**Issue by sndels** [ziglang/zig#13751] opened 2022-12-03 07:53 UTC
### Zig Version

0.11.0-dev.461+5eaacf1ce

### Steps to Reproduce and Observed Behavior

Run the following with no args
```
const std = @import("std");

fn retFalse() bool {
    return false;
}

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (false) {
        std.debug.print("This won't be taken\n", .{});
    }
    if (false) |_| {
        std.debug.print("This won't be taken\n", .{});
    }

    if (args.len == 2) {
        std.debug.print("This won't be taken\n", .{});
    }
    if (args.len == 2) |_| {
        std.debug.print("{d} == 2 :(\n", .{args.len});
    } else {
        std.debug.print("{d} != 2\n", .{args.len});
    }

    const arg_count_2 = args.len == 2;
    if (arg_count_2) {
        std.debug.print("This won't be taken\n", .{});
    }
    if (arg_count_2) |_| {
        std.debug.print("{d} == 2 :(\n", .{args.len});
    } else {
        std.debug.print("{d} != 2\n", .{args.len});
    }

    if (retFalse()) {
        std.debug.print("This won't be taken\n", .{});
    }
    if (retFalse()) |_| {
        std.debug.print("This will be taken :(\n", .{});
    } else {
        std.debug.print("This should be taken\n", .{});
    }
}
```
and the program prints
```
1 == 2 :(
1 == 2 :(
This will be taken :(
```

### Expected Behavior

The compiler should give an error from trying to capture a `bool` (like it does if I name and use the captured variable) or the compiled program should print
```
1 != 2
1 != 2
This should be taken
```

**Comment by andrewrk** [comment] 2022-12-03 07:57
Reduction:

```zig
test {
    var f = false;
    if (f) |_| {}
}
```

This is supposed to be a compile error: expected optional, found bool

This is a regression from the stage1 compiler (although the error message is pointing at the wrong location):

```
$ zig test test.zig -fstage1
./test.zig:4:5: error: expected optional type, found 'bool'
    var f = false;
    ^
```

**Comment by Vexu** [comment] 2022-12-03 08:30
Duplicate of #13023

**Closed by Vexu** 2022-12-03 08:30 UTC
Labels: bug, stage2, regression
