### ISSUE TITLE
proposal: isComptime builtin.

### ISSUE THREAD

**Issue by lolbinarycat** [ziglang/zig#7539] opened 2020-12-24 18:44 UTC
currently (as far as I know), there is no simple to get whether a value is known at compile time. For integer types, you can do `@TypeOf(@clz(u8, val)) == comptime_int`, but this is really more of a hack. Since this check already exists as part of `@clz`, it shouldn't be hard to implement into zig.

**Comment by lolbinarycat** [comment] 2020-12-24 18:50
originally I had the idea for a function that would take a value of type T and return a comptime ?T (which would be null if the value isn't comptime), but it turns out this isn't necessary, as this works:
```
    const foo = try std.io.getStdIn().reader().readByte();
    comptime {
        if (@TypeOf(@clz(u8, foo)) == comptime_int) {
            const bar = foo + 6;
        }
}
```

**Comment by Vexu** [comment] 2020-12-24 18:51
Duplicate of #868.

**Comment by lolbinarycat** [comment] 2020-12-24 19:02
@Vexu that issue is about whether the function is being a called from a `comptime` block, while this issue is about telling whether a *value* is available at comptime, which aren't the same. while this proposal might help with the other issue, the opposite is not true.

**Comment by Vexu** [comment] 2020-12-24 19:11
A value will only be `comptime` if you explicitly make it so or the function is being executed at `comptime` when all values will be `comptime` meaning that an `@areWeInComptime` would also solve this.

**Comment by lolbinarycat** [comment] 2020-12-24 19:22
@Vexu 
> A value will only be `comptime` if you explicitly make it so or the function is being executed at `comptime` when all values will be `comptime` meaning that an `@areWeInComptime` would also solve this.
This just isn't true at all...
```
const std = @import("std");

fn isComptime(val: anytype) bool {
    return @TypeOf(@clz(usize, val)) == comptime_int;
}

test "" {
    const foo = 4;
    comptime {
        std.testing.expect(isComptime(foo));
        _ = bar(foo);
    }
}

fn bar(val: usize) type {
    return [val]u8;
}
```

**Comment by Vexu** [comment] 2020-12-24 19:26
`const foo = 4;`is the same as `const foo: comptime_int = 4`, which makes it always `comptime` as does making a variable of type  `comptime_float` or `type`.

**Comment by lolbinarycat** [comment] 2020-12-24 19:32
@Vexu Perhaps, but how do you explain this?
```
const std = @import("std");

fn isComptime(val: anytype) bool {
    return @TypeOf(@clz(usize, val)) == comptime_int;
}

test "" {
    const foo: usize = 4;
    comptime {
        std.testing.expect(isComptime(foo));
        _ = bar(foo);
    }
    _ = bar(foo);
}

fn bar(val: usize) type {
    return [val]u8;
}
```

**Comment by Vexu** [comment] 2020-12-24 19:37
If you declare a `const` variable with a `comptime` value, the variable will be `comptime` known since the compiler knows that you cannot change it to a non-`comptime` value. If you make it a `var` then it will be runtime known unless the function is running at `comptime`, same happens at container level except all values have to be initiated with `comptime` values.

**Comment by lolbinarycat** [comment] 2020-12-24 19:42
@Vexu, ok, but that doesn't change the fact that your original statement was wrong. My point is that in this case `@areWeInComptime` would be fairly unhelpful. It becomes even less helpful if you use multiple parameters in your function. They are separate issues, as they address separate problems.

**Comment by Vexu** [comment] 2020-12-24 19:50
`bar` not requiring `comptime` on `val` is a bug #5709.

**Comment by lolbinarycat** [comment] 2020-12-24 19:54
@Vexu `usize` is not a compile-only type though. Can you please just reopen the issue, these are clearly not the same thing.

**Comment by Vexu** [comment] 2020-12-24 19:56
I got that wrong but `@areWeInComptime` would tell that val is `comptime`.

**Comment by andrewrk** [comment] 2020-12-24 20:10
Thanks for the proposal. It is planned to not have this builtin because the language intends for Zig programmers to write code that works both at comptime and runtime values. There is no need to explicitly check, and having such a builtin would lead to its use, making code needlessly more complex.

**Closed by andrewrk** 2020-12-24 20:10 UTC
Labels: proposal

**Comment by lolbinarycat** [comment] 2020-12-24 21:04
@andrewrk 
>  language intends for Zig programmers to write code that works both at comptime and runtime values. 

The language also has operators that only work on comptime values, as well as lots of stuff that only works at runtime. Add to this the fact that it is already possible to tell if values are comptime by abusing `@clz`, and that plenty of builtins come with disclaimers discouraging their use. and I feel like this is a somewhat arbitrary line to draw.

**Comment by windows-h8r** [comment] 2021-06-25 16:31
Possible use case: A more user-friendly implementation of `std.debug.assert`:

```zig

pub fn assert(condition: bool) void {
    if (!condition) {
        switch (comptime std.builtin.mode) {
            .Debug, .ReleaseSafe => if (@isComptime()) {
                // because @panic(...) doesn't show the message at compile time
                @compileError("assertion failed");
            } else {
                @panic("assertion failed");
            },

            .ReleaseFast, .ReleaseSmall => unreachable,
        }
    }
}

```

**Comment by gooncreeper** [comment] 2024-08-12 16:47
@andrewrk Knowing if a value is comptime known can allow optimized code paths to be implemented for such cases. Adding this feature would go with Zig's goal of being able to write optimal code.

**Comment by castholm** [comment] 2024-08-12 18:53
@gooncreeper FYI, it's currently possible to discover whether or not a value is comptime-known by instantiating an anonymous tuple and reflecting on its fields, which in turn makes it possible to implement an `isComptimeKnown` function in user code like this:

```zig
const std = @import("std");
const expectEqual = std.testing.expectEqual;

inline fn isComptimeKnown(val: anytype) bool {
    return @typeInfo(@TypeOf(.{val})).Struct.fields[0].is_comptime;
}

test {
    const a: i32 = 15;
    try expectEqual(true, isComptimeKnown(a));

    var x: u64 = undefined;
    x = 15;
    try expectEqual(false, isComptimeKnown(x));
    try expectEqual(true, isComptimeKnown(x >= 0));
}
```

(Adapted from https://github.com/ziglang/zig/issues/868#issuecomment-1201549797)
