### ISSUE TITLE
Bug: Function mutates argument when it is also the result location

### ISSUE THREAD

**Issue by EleanorNB** [ziglang/zig#7412] opened 2020-12-12 13:03 UTC
Noticed by sinitax on Discord.

Consider the following code:
``` zig
const std = @import("std");
const Pos = struct { x: i64, y: i64 };

pub fn modify(p: Pos) Pos {
    return Pos{ .x = 1, .y = p.x };
}

pub fn main() !void {
    p = modify(p);
    std.debug.print("{} {}\n", .{ p.x, p.y });
}
```
The expected output is `1 5`, but the actual output is `1 1`. This is because `p` is passed by reference, but also set as the result location; so, the first field assignment mutates it in-place. This is not expected or desired behaviour. To avoid this, when the result location would overlap any argument, we should instead allocate a temporary.

**Comment by Vexu** [comment] 2020-12-12 13:18
Duplicate of #3696

**Closed by Vexu** 2020-12-12 13:18 UTC
