### ISSUE TITLE
Shifting by `@intCast(u0, <var>)` causes compiler segfault

### ISSUE THREAD

**Issue by tgschultz** [ziglang/zig#1697] opened 2018-11-04 02:46 UTC
```
test "" {
    var x = u1(0);
    var y = usize(0) << @intCast(u0, x);
}
```

```
Segmentation fault (core dumped)
```

Probably related to #1568.

**Comment by andrewrk** [comment] 2019-02-09 00:51
Fixed in f330eebe4bc6a036846cf05706f72855627c705a. #1817 was a duplicate of this issue

**Closed by andrewrk** 2019-02-09 00:51 UTC
Labels: bug
