### ISSUE TITLE
"error: cannot assign to constant" when @export is called in a loop

### ISSUE THREAD

**Issue by rgreenblatt** [ziglang/zig#8027] opened 2021-02-16 18:31 UTC
```zig
fn f() callconv(.C) void {}

comptime {
    // fails
    inline for (.{ "a", "b" }) |n| {
        @export(f, .{ .name = n, .linkage = .Strong });
    }
    // works fine
    inline for (.{ "c", "d" }) |n| {
        const options = .{ .name = n, .linkage = .Strong };
        @export(f, options);
    }
}
```
https://zig.godbolt.org/z/aWh6TY

It seem likely to me that this issue occurs for things other than just `@export`, but I haven't looked for this issue with any other builtins.

Possibly related to https://github.com/ziglang/zig/issues/5497

**Comment by Vexu** [comment] 2021-02-21 09:57
Duplicate of #4639.

**Closed by Vexu** 2021-02-21 09:57 UTC
