### ISSUE TITLE
Compiler crashes when resolving Optional types inside a comptime loop.

### ISSUE THREAD

**Issue by TUSF** [ziglang/zig#14119] opened 2022-12-29 17:04 UTC
### Zig Version

0.11.0-dev.987+a1d82352d

### Steps to Reproduce and Observed Behavior

In a loop that runs at comptime, call a function that returns an optional type, and then resolve it (either with `.?`, `orelse`, or capturing with `if` or `while`).
```zig
const std = @import("std");
const str = "Hello cruel world!";

const precomputed = blk: {
    var wordsIt = std.mem.split(u8, str, " ");
    var words = [_][]const u8{};
    while (wordsIt.next()) |word| {
        words = words ++ word;
    }
    break :blk .{
        .words = words,
    };
};

pub fn main() void {
    std.debug.print("First Word: {s}\n", .{precomputed.words[0]});
}
```

The compiler seems to struggle for a while (much longer than it would take to normally compile this) and then returns an error code (on Windows it's 5, on Linux it's 11). We can avoid this by not resolving the optional until the loop is finished, or check if an optional `== null` inside the loop, but that isn't very useful. At best I can only capture the final iteration, because the compiler also crashes if I attempt to concatenate an array of optionals `[_]?[]const u8`

### Expected Behavior

To not crash.

The above loop works (with some changes) when performed at runtime, and just seems to choke when running at comptime.

**Comment by Vexu** [comment] 2022-12-29 17:10
Duplicate of #12765, fixed by #13017

**Closed by Vexu** 2022-12-29 17:10 UTC
Labels: bug
