### ISSUE TITLE
Invalid codegen for switch inside unnamed struct

### ISSUE THREAD

**Issue by sivukhin** [ziglang/zig#10509] opened 2022-01-04 17:38 UTC
### Zig Version

0.9.0-dev.1815+20e19e75f

### Steps to Reproduce

**Brief description**: you can wrap `switch` expression in an `unnamed struct` and after that zig incorrectly compute branches of the `switch`.

Example code (godbolt link with slightly rewritten example: https://godbolt.org/z/P6bW9zvqe):
```zig
const std = @import("std");

// workaround to disable Zig comptime behaviour
pub fn get() i32 {
    return 0;
}

pub fn main() void {
    const x: i32 = get();
    const unnamed_struct_switch = .{switch (x) {
        0 => @as(i32, 0),
        else => @as(i32, -1),
    }};
    std.debug.print("unnamed_struct_switch={}\n", .{unnamed_struct_switch.@"0"});
}

```

Looks like the bug reproduces only with mutual usage of switch within unnamed struct because following code works fine:
```zig
const std = @import("std");

pub fn get() i32 {
    return 0;
}

const T = struct { value: i32 };

pub fn main() void {
    const x: i32 = get();
    const struct_switch = T{ .value = switch (x) {
        0 => @as(i32, 0),
        else => @as(i32, -1),
    } };
    const simple_switch = switch (x) {
        0 => @as(i32, 0),
        else => @as(i32, -1),
    };
    std.debug.print("struct_switch={}\n", .{struct_switch.value}); // struct_switch=0
    std.debug.print("simple_switch={}\n", .{simple_switch}); // simple_switch=0
}
```

### Expected Behavior

```unnamed_struct_switch=0```

### Actual Behavior

```unnamed_struct_switch=-1```

**Comment by Vexu** [comment] 2023-01-13 17:51
Duplicate of #3882

**Closed by Vexu** 2023-01-13 17:51 UTC
Labels: bug, stage1
