### ISSUE TITLE
Broken LLVM module found: Call parameter type does not match function signature

### ISSUE THREAD

**Issue by dmgk** [ziglang/zig#8808] opened 2021-05-17 21:19 UTC
Minimal reproducer (0.8.0-dev.2275+8467373bb):

```zig
const std = @import("std");

fn func(args: [][*:0]const u8) void {}

pub fn main() void {
    var args = [_][*:0]const u8{ "one", "two" };

    // OK
    func(&args);

    // ICE
    {
        // broken LLVM module found: Call parameter type does not match function signature!
        // %"[][*:0]u8"* @argv
        // %"[][*:0]const u8"*  call fastcc void @func(%"[][*:0]u8"* @argv), !dbg !16063

        // This is a bug in the Zig compiler.thread 69656 panic:
        // Unable to dump stack trace: debug info stripped

        func(std.os.argv);
    }
}

```

**Comment by ehaas** [comment] 2021-05-18 03:31
I think this is a dupe of https://github.com/ziglang/zig/issues/7807

There is a workaround listed there: `const argv: [][*:0]const u8 = std.os.argv;` and then call `func(argv)`

**Closed** 2021-05-18 06:03 UTC
