### ISSUE TITLE
Comptime implicit coercion can be loosy

### ISSUE THREAD

**Issue by PauloCampana** [ziglang/zig#21728] opened 2024-10-16 22:44 UTC
### Zig Version

0.14.0-dev.1694+3b465ebec

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test {
    const a: u32 = 268435455;
    const b: f32 = a;
    std.debug.print("a = {d}\n", .{a});
    std.debug.print("b = {d}\n", .{b});
}

test {
    const c: f32 = 268435455;
    std.debug.print("c = {d}\n", .{c});
}

// output:
// a = 268435455
// b = 268435460
// c = 268435460
// All 2 tests passed.
```

In the first test, the implicit cast from u32 to f32 is allowed because `a` is comptime known,
same thing in the second test from comptime_int to f32.

They shouldn't be allowed as 268435455 is too big to be uniquely represented as an f32 and is thus rounded to nearest representable one.

### Expected Behavior

The lack of a @floatFromInt in the code above is only valid because the values are known at compile time, so a compiler error is due.
  
```
error: type 'f32' cannot represent value 268435455
    const b: f32 = a;
                   ^
```

```
error: type 'f32' cannot represent value 268435455
    const c: f32 = 268435455;
                   ^
```

**Comment by PauloCampana** [comment] 2024-10-16 22:49
From the [langref](https://ziglang.org/documentation/master/#Type-Coercion-Compile-Time-Known-Numbers)

> When a number is comptime-known to be representable in the destination type, it may be coerced

Current behaviour does not match that

**Comment by xdBronch** [comment] 2024-10-16 23:34
looks like #21586

**Comment by andrewrk** [comment] 2024-10-16 23:40
duplicate of #21586

**Closed by andrewrk** 2024-10-16 23:40 UTC
Labels: bug
