### ISSUE TITLE
Compiler enter infinite loop and crashes with "out of memory" OOM

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#10042] opened 2021-10-27 14:08 UTC
### Zig Version

0.9.0-dev.1513+3af973160

This was master as of Oct 27, 2021.

This also occurs on 0.8.1 and 0.7.0, 0.6.0, 0.5.0 but does not occur on 0.4.0.

### Steps to Reproduce

Run `zig build-exe` on the following file:

```zig
pub fn main() void {
    const result = blk: {
        if (true) {
            defer for ("a") |_| { };
            break :blk true;
        } else unreachable;
    };
    _ = result;
}
```

### Expected Behavior

Example to compile, or at least not enter an infinite loop until it runs out of memory.

### Actual Behavior

Enters an infinite loop and eventually gets a "kill signal" on linux from the OOM killer.

On my machine it takes 30 seconds or so to be killed by the OOM killer.  I ran it with GDB and stopped it a few times.  I compared the backtraces and here was the "common" part:

```
#2  0x0000000001753f1d in analyze_fn_ir (g=0x4bc9080, fn=0x9eea1c0, return_type_node=0x4c05d70) at /home/marler8997/git/zig4/src/stage1/analyze.cpp:5094
#3  0x00000000017544a3 in analyze_fn_body (g=0x4bc9080, fn_table_entry=0x9eea1c0) at /home/marler8997/git/zig4/src/stage1/analyze.cpp:5209
#4  0x0000000001754c76 in semantic_analyze (g=0x4bc9080) at /home/marler8997/git/zig4/src/stage1/analyze.cpp:5313
#5  0x0000000001691173 in gen_root_source (g=0x4bc9080) at /home/marler8997/git/zig4/src/stage1/codegen.cpp:9713
#6  0x00000000016914c7 in codegen_build_object (g=0x4bc9080) at /home/marler8997/git/zig4/src/stage1/codegen.cpp:9762
#7  0x00000000016653e7 in zig_stage1_build_object (stage1=0x4bc9080) at /home/marler8997/git/zig4/src/stage1/stage1.cpp:132
#8  0x0000000000c26ef5 in Module.build_object (mod=0x4bc9080) at /home/marler8997/git/zig4/src/stage1.zig:149
#9  0x0000000000ba3458 in Compilation.updateStage1Module (comp=0x4bc6128, main_progress_node=0x7fffffff5e80) at /home/marler8997/git/zig4/src/Compilation.zig:4460
#10 0x000000000096a15f in Compilation.processOneJob (comp=0x4bc6128, job=..., main_progress_node=0x7fffffff5e80) at /home/marler8997/git/zig4/src/Compilation.zig:2538
#11 0x000000000095d626 in Compilation.performAllTheWork (self=0x4bc6128) at /home/marler8997/git/zig4/src/Compilation.zig:2156
#12 0x0000000000958f78 in Compilation.update (self=0x4bc6128) at /home/marler8997/git/zig4/src/Compilation.zig:1787
#13 0x00000000008ed370 in main.updateModule (gpa=0x4b19210 <c_allocator_state>, comp=0x4bc6128, hook=...) at /home/marler8997/git/zig4/src/main.zig:2487
#14 0x000000000080e8f0 in main.buildOutputType (gpa=0x4b19210 <c_allocator_state>, arena=0x7fffffffbc78, all_args=..., arg_mode=...)
    at /home/marler8997/git/zig4/src/main.zig:2181
#15 0x00000000007e2cc8 in main.mainArgs (gpa=0x4b19210 <c_allocator_state>, arena=0x7fffffffbc78, args=...) at /home/marler8997/git/zig4/src/main.zig:203
#16 0x00000000007e270a in main (argc=3, argv=0x7fffffffbeb8) at /home/marler8997/git/zig4/src/stage1.zig:48
```

**Comment by Vexu** [comment] 2023-01-16 14:12
Duplicate of #9600

**Closed by Vexu** 2023-01-16 14:12 UTC
Labels: bug, stage1
