### ISSUE TITLE
x86_64-windows and arch64-windows fail at comptime at getting file scope stdout

### ISSUE THREAD

**Issue by matu3ba** [ziglang/zig#14203] opened 2023-01-05 01:48 UTC
### Zig Version

https://ziglang.org/deps/zig+llvm+lld+clang-x86_64-windows-gnu-0.11.0-dev.448+e6e459e9e.zip

### Steps to Reproduce and Observed Behavior

Windows CI does not show the build zig version, so I added the tarball.

On Windows (CI) add `cases.add("tools/extract-grammar.zig");` to standalone.zig.
The behavior should also be reproducible with running on Windows `zig build-exe D:\a\zig\zig\tools\extract-grammar.zig`, but I have not tested this yet.

```
D:\a\zig\zig\lib\std\os\windows.zig:1795:28: error: unable to evaluate comptime expression
                break :blk asm volatile (
                           ^~~
D:\a\zig\zig\lib\std\os\windows.zig:1810:15: note: called from here
    return teb().ProcessEnvironmentBlock;
           ~~~^~
D:\a\zig\zig\lib\std\io.zig:43:30: note: called from here
        return os.windows.peb().ProcessParameters.hStdOutput;
               ~~~~~~~~~~~~~~^~
D:\a\zig\zig\lib\std\io.zig:57:34: note: called from here
        .handle = getStdOutHandle(),
                  ~~~~~~~~~~~~~~~^~
D:\a\zig\zig\tools\extract-grammar.zig:41:31: note: called from here
const stdout_wr = io.getStdOut().writer();
                  ~~~~~~~~~~~~^~
error: test...
```
from this CI run: https://github.com/ziglang/zig/actions/runs/3842681803

### Expected Behavior

Successful build. On my Linux machine it also works as expected.

**Comment by Vexu** [comment] 2023-01-05 09:58
Duplicate of #6845

**Closed by Vexu** 2023-01-05 09:58 UTC
Labels: bug
