### ISSUE TITLE
zig-windows-x86 fails with Unexpected on x86_64 windows

### ISSUE THREAD

**Issue by pfgithub** [ziglang/zig#20848] opened 2024-07-29 00:07 UTC
### Zig Version

zig-windows-x86-0.14.0-dev.653+91c17979f

### Steps to Reproduce and Observed Behavior

```
zig init
zig build
```

```
error: unable to check cache: stat file …\zig-windows-x86-0.14.0-dev.653+91c17979f\lib\compiler\build_runner.zig' failed: Unexpected
```

### Expected Behavior

Shouldn't fail with unexpected. Since x86 programs are compatible on x86_64 it should probably work, or it could give an error saying you downloaded the wrong version of zig.

**Comment by squeek502** [comment] 2024-07-29 00:14
Duplicate of https://github.com/ziglang/zig/issues/20047, this target is fully broken right now. Root cause is likely https://github.com/ziglang/zig/issues/20469

**Closed by squeek502** 2024-07-29 00:14 UTC
Labels: bug
