### ISSUE TITLE
segfault passing non-pointer to `std.mem.bytesToValue`

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#12974] opened 2022-09-26 05:18 UTC
### Zig Version

0.10.0-dev.4176+6d7b0690a

### Steps to Reproduce

```zig
const std = @import("std");
test {
    const tag = [_]u8{ 0x13, 0x01 };
    _ = std.mem.bytesToValue(u16, tag);
}
```

### Expected Behavior

```
All 1 tests passed.
```

### Actual Behavior

```
Segmentation fault (core dumped)
```

**Comment by yujiri8** [comment] 2022-09-26 05:25
> All 1 tests passed.

I don't think that is the correct behavior, since bytesToValue expects a pointer. It should be a compile error, as it was in 0.9.1:
```
/usr/lib/zig/std/mem.zig:2582:9: error: expected *[2]u8, passed [2]u8
        @compileError(std.fmt.bufPrint(&buf, "expected *[{}]u8, passed " ++ @typeName(B), .{size}) catch unreachable);
        ^
/usr/lib/zig/std/mem.zig:2590:77: note: called from here
pub fn bytesAsValue(comptime T: type, bytes: anytype) BytesAsValueReturnType(T, @TypeOf(bytes)) {
                                                                            ^
/usr/lib/zig/std/mem.zig:2590:77: note: called from here
pub fn bytesAsValue(comptime T: type, bytes: anytype) BytesAsValueReturnType(T, @TypeOf(bytes)) {
                                                                            ^
./t.zig:4:29: note: called from here
    _ = std.mem.bytesToValue(u16, tag);
                            ^
./t.zig:2:6: note: called from here
test {
     ^
```

**Comment by Vexu** [comment] 2022-09-26 08:38
Duplicate of #12927

**Closed by Vexu** 2022-09-26 08:38 UTC
Labels: bug
