### ISSUE TITLE
Add support for mocking (wrapping) functions in tests

### ISSUE THREAD

**Issue by bheads** [ziglang/zig#5138] opened 2020-04-22 19:31 UTC
Mocking is an extremely useful tool in testing, but in a non-OO it can be tricky. One way to do this is via function wrapping in the linker. Currently that means LLD, but that an implementation detail. I bet the compiler could do a better job wrapping functions in test in a test build.

**Comment by andrewrk** [comment] 2020-05-30 01:15
Duplicate of #500

**Closed by andrewrk** 2020-05-30 01:15 UTC
