### ISSUE TITLE
Allow error sets to contain associated values

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#9720] opened 2021-09-09 19:02 UTC
## Motivation

Error sets in their current form in Zig are effectively fancy error codes. For some use cases, this is sufficient; however, often, errors include more information. For instance, consider a parser; if it reports a syntax error, it should return information about the specific error, what tokens were expected, where in the input the error was, and so on.

Currently, this issue would likely be solved by setting some state which can be accessed by the error handling code to view the error information; for instance, in an `error_info` field on a `Parser` type. This solution works, but is quite inelegant for several reasons. Firstly, it separates two pieces of data which are intrinsically linked: the error type and the extra associated data. Secondly, it adds extra state which will generally go unused to e.g. the `Parser` struct; this feels clunky, especially if you need to add a union or several fields to deal with different kinds of errors. Lastly, some functions may not have any data structure on which to actually put this state, at which point the only available solution is to either have global state which can be later fetched, or to pass in a pointer to a place error info can be outputted; both of these solutions reek of C-style error handling, full of global state and/or boilerplate.

## Proposal

I propose modifying error unions to be more like a standard tagged union, but tagged with an error set rather than an enum. Error types would be defined like this:

```
pub const TrivialError = union(error) {
    TrivialErrorA: void,
    TrivialErrorB: void,
};

pub const ComplexError = union(error) {
    ComplexErrorA: u32,
    ComplexErrorB: struct {
        foo: u32,
        bar: []const u8,
    },
};
```

Note the similarity between this syntax and normal union definitions, especially `union(enum)` syntax. Like a normal union, we can associate the type `void` with the error tag if we don't want to include any extra data.

These errors can also be constructed much like union types. For instance:
```
fn a() TrivialError!void {
    return error.TrivialErrorA;
}

fn b() ComplexError!void {
    return error{ .ComplexErrorA = 4 };
}
```

Both of these styles of error construction are analagous to how other union types can be constructed; if the contained type is `void`, it can be constructed simply using the name, otherwise you can use regular initialization syntax, but in this case replacing the union name with `error`.

`try` would not be affected by this change; as before, it simply returns any unwrapped errors, but that error now includes the actual error data too. `catch` would also be unchanged.

Error set inference would work just like it currently does:
```
// c's inferred error set contains both TrivialError and ComplexError
fn c() !void {
    try a();
    try b();
}
```

The behaviour of `switch` on error types would need to be slightly changed; it should allow capturing the value contained in an error type. As with lots of this proposal, this isn't really a new syntax; it's just taken from how the construct works for union types. For instance:
```
b() catch |err| switch (err) {
    error.ComplexErrorA => |val| std.log.info("{}", .{val}), // print the contained value, just as you would for a standard union
    else => |e| return e,
};
```

The semantics of switching on multiple error tags for one branch (i.e. `error.ComplexErrorA, error.ComplexErrorB => |e| ...`) are somewhat up for debate. There are two main options I can see:
1) Match the behaviour of switching on unions; extract the contained error data for whichever error was caught, emitting a compile error if the types of the contained values do not match. This is consistent with how `switch` works for regular unions, which aligns well with the rest of this proposal. It could be useful, for instance, if you have a parser with several different errors all of which just return a source location, and which you want to all give similar output.
2) Treat it similarly to an `else` branch by just capturing a smaller error set. This syntax would make it easy, for instance, to return a specific set of error types whilst handling others. However, it feels inconsistent with normal tagged union types, and it also treats having multiple cases in a branch specially, which I'm not a huge fan of.

On balance, I think the second option would probably be slightly more useful; however, the first option personally wins me over just on its consistency with the rest of the language. Community input would be good here!

## Notes

This proposal would make type-checking combinations of error unions - either created through `||`, or error set inference - slightly more complex, and it would need to be checked that if two tags of the same name exist that they also have the same contained type. However, this should be fairly simple to do.

This proposal also breaks backwards compatibility fairly significantly; any code that declares explicit error sets would need to be updated. However, the changes needed are fairly simple - generally just replacing `error` with `union(error)` and adding `: void` to each line in the error set. `zig fmt` could detect old-style code - probably just on any array-like usage of the `error{ ... }` initialization syntax - and upgrade to the new style.

**Comment by Vexu** [comment] 2021-09-09 19:04
Duplicate of #2647.

**Closed** 2021-09-10 02:06 UTC
Labels: duplicate, proposal
