### ISSUE TITLE
Function parameter in a member function of generic type, typed as an anonymous enum produces confusing error message when marked as comptime.

### ISSUE THREAD

**Issue by dmitry-ant** [ziglang/zig#9704] opened 2021-09-08 09:57 UTC
I am really sorry for that long title, couldn't think of how to condense this problem.

When i try to use this generic struct
```
fn GenStruct(comptime T: type) type {
    return struct {
        fn addNum(x: T, comptime num: enum { One, Six }) T {
            return switch (num) {
                .One => return x + 1,
                .Six => return x + 6
            };
        }
    };
}
```

Like this:
```
pub fn main() void {
    const Struct_f32 = GenStruct(f32);
    const a = Struct_f32.addNum(4.0, .One);
}
```
Compiler produces this error:
```
./repr.zig:19:38: error: expected type 'enum:6:39', found 'enum:6:39'
    const a = Struct_f32.addNum(4.0, .One);
                                     ^
./repr.zig:6:39: note: enum:6:39 declared here
        fn addNum(x: T, comptime num: enum { One, Six }) T {
                                      ^
./repr.zig:6:39: note: enum:6:39 declared here
        fn addNum(x: T, comptime num: enum { One, Six }) T {
                                      ^
./repr.zig:19:32: note: referenced here
    const a = Struct_f32.addNum(4.0, .One);
```

I am not sure if this shouldn't work (comptime anonymous enums as function parameters in a generic struct), but same code works flawlessly when anonymous enum parameter not marked as comptime, when a function is not a member of a generic struct, or with a named comptime enum.

In any case, at least error message is really confusing.

**Comment by Vexu** [comment] 2021-09-08 11:52
Duplicate of #3707.

**Closed by Vexu** 2021-09-08 11:52 UTC
