### ISSUE TITLE
translate-c can`t translate-c c anonymous structures ( struct  union  ) 

### ISSUE THREAD

**Issue by Dozingfiretruck** [ziglang/zig#18847] opened 2024-02-07 04:23 UTC
### Zig Version

0.11

### Steps to Reproduce and Observed Output

if zig support anonymous structures ( struct  union  ) , it is very very convenient for embedded，such as describe the registers 
typedef struct{
    union {
        struct {
            uint32_t LSEON:1;         
            uint32_t LSERDY:1;        
            uint32_t LSEBYP:1;        
            uint32_t :2;              
            uint32_t LSECSSON:1;      
            uint32_t LSECSSD:1;       
            uint32_t :1;              
            uint32_t RTCSEL:2;        
            uint32_t :5;              
            uint32_t RTCEN:1;         
            uint32_t BDRST:1;         
            uint32_t :7;              
            uint32_t LSCOEN:1;        
            uint32_t LSCOSEL:1;       
            uint32_t :6;              
        };
        __IO uint32_t RCC_BDCR;      
    };
} rcc_register_t;
uint32_t :6; is also usefull

### Expected Output

support anonymous structures ( struct  union  )

**Comment by f-cozzocrea** [comment] 2024-02-07 06:14
Duplicate of #6349.

**Closed** 2024-02-07 10:40 UTC
Labels: error message
