### ISSUE TITLE
anonymous enum literals fail to coerce to comptime enum literal typed parameters

### ISSUE THREAD

**Issue by RaphiJS6-13** [ziglang/zig#7424] opened 2020-12-13 17:27 UTC
The following code does not compile:
```Zig
fn foo(comptime bar: enum { baz }) void {}

test "passing anon enum literal to comptime enum parameter" {
  foo(.baz);
}
```
The error message is:
```
./enums.zig:4:7: error: expected type 'enum:1:22', found 'enum:1:22'
  foo(.baz);
      ^
./enums.zig:1:22: note: enum:1:22 declared here
fn foo(comptime bar: enum { baz }) void {}
                     ^
./enums.zig:1:22: note: enum:1:22 declared here
fn foo(comptime bar: enum { baz }) void {}
                     ^
./enums.zig:4:6: note: referenced here
  foo(.baz);
     ^
```
<h3>Version</h3>

```Bash
sapphire@Raphi-Spoerri:~$ zig version
0.6.0
```

**Comment by Vexu** [comment] 2020-12-13 17:32
Duplicate of #3707.

**Closed by Vexu** 2020-12-13 17:32 UTC
