### ISSUE TITLE
Bad error trace

### ISSUE THREAD

**Issue by danielchasehooper** [ziglang/zig#11593] opened 2022-05-05 22:31 UTC
### Zig Version

0.10.0-dev.2083+13d1798ea

### Steps to Reproduce

run `zig test phantomErrorTrace.zig`

```
// phantomErrorTrace.zig
const std = @import("std");

fn alwaysErrors() !void {
    return error.BUG_ThisErrorShouldNotAppearInAnyTrace;
}

test "test expected error" {
    try std.testing.expectError(error.BUG_ThisErrorShouldNotAppearInAnyTrace, alwaysErrors());
}

test "trigger error trace" {
    return error.WeExpectToSeeThisInTheTrace;
}

```

### Expected Behavior

should only see error trace for the second test
```
1/2 test "test expected error"... OK
2/2 test "trigger error trace"... FAIL (WeExpectToSeeThisInTheTrace)
FAIL (WeExpectToSeeThisInTheTrace)
/Users/daniel/Developer/zigtests/phantomerrortrace.zig:14:5: 0x1005a992f in test "trigger error trace" (test)
    return error.WeExpectToSeeThisInTheTrace;
    ^
1 passed; 0 skipped; 1 failed.
```

### Actual Behavior

Error trace from the first test appears in the error trace for the second test
```
1/2 test "test expected error"... OK
2/2 test "trigger error trace"... FAIL (WeExpectToSeeThisInTheTrace)
FAIL (WeExpectToSeeThisInTheTrace)
/Users/daniel/Developer/zigtests/phantomerrortrace.zig:6:5: 0x10085dce7 in alwaysErrors (test)
    return error.BUG_ThisErrorShouldNotAppearInAnyTrace;
    ^
/Users/daniel/Developer/zigtests/phantomerrortrace.zig:14:5: 0x10085cd3b in test "trigger error trace" (test)
    return error.WeExpectToSeeThisInTheTrace;
    ^
1 passed; 0 skipped; 1 failed.
```

**Comment by squeek502** [comment] 2022-05-06 00:15
Very likely to be a duplicate of https://github.com/ziglang/zig/issues/1923

**Closed** 2022-05-06 07:42 UTC
Labels: bug
