### ISSUE TITLE
slice of allowzero pointer is rejected in for

### ISSUE THREAD

**Issue by LemonBoy** [ziglang/zig#4361] opened 2020-02-01 22:36 UTC
Reduced from clashos, this may be a regression ¯\\\_(ツ)\_/¯

```zig
export fn _start() void {
    var a = [4]u32{ 1, 2, 3, 4 };
    var b = @ptrCast([*]allowzero u32, &a);

    for (b[0..4]) |ch| {
        if (ch > 4) @panic("");
    }
}
const builtin = @import("builtin");
pub fn panic(msg: []const u8, error_return_trace: ?*builtin.StackTrace) noreturn {
    while (true) {}
}
```

**Comment by mikdusan** [comment] 2020-02-06 06:57
This looks to be a regression by #4152. We actually had a reduction that I later marked as off-topic to the PR, but I think it was just side-stepped. This comment is relevant: https://github.com/ziglang/zig/pull/4152#issuecomment-573975258

**Comment by fengb** [comment] 2020-02-06 07:06
Forcing a pointer capture works around the compiler error: `for (b[0..4]) |*ch| {`

The for loop capture seems to be trying to coerce into a non-allowzero pointer:
```
error: expected type '*const u32', found '*allowzero u32'
```

**Comment by LemonBoy** [comment] 2020-02-06 14:12
The problem lies in how the compiler lowers the loop. The `ch` payload is desugared as a `var ch: <elem-type>` whose base backing memory (`IrInstSrcDeclVar->ptr`) is the i-th element of the array/slice/pointer it's looping on. The index `i` is increased every loop and so every time `ch` is dereferenced in the loop body the correct value is used.

Of course this trick falls short once you take into account that a pointer may be `allowzero`.

**Closed** 2020-02-14 19:39 UTC
Labels: bug, stage1
