### ISSUE TITLE
Non-canonical member function invocations do not respect private visibility

### ISSUE THREAD

**Issue by Qix-** [ziglang/zig#4909] opened 2020-04-02 14:40 UTC
```zig
// foo.zig
pub const Foo = struct {
    a: u32,

    fn getA(self: *Foo) u32 {
        return self.a;
    }
};
```
```zig
// bar.zig
const Foo = @import("foo.zig").Foo;

pub fn main() void {
    var f = Foo{ .a = 10 };
    if (f.getA() != 10) unreachable;    // !! should raise compile error, but doesn't
    if (Foo.getA(f) != 10) unreachable; // correctly raises compile error
}
```

Thanks to @MasterQ32 for the tip to check the canonical form (`Foo.getA(f)`).

**Comment by ifreund** [comment] 2020-04-02 14:45
Kind of a duplicate of #2514, though that issue is closed.

**Comment by Qix-** [comment] 2020-04-02 14:46
Yep, https://github.com/ziglang/zig/issues/2514#issuecomment-570993357 appears to address it but it looks like it went unnoticed.

**Comment by ifreund** [comment] 2020-04-02 14:47
Per  #569 and  #1717 it seems that pub won't be allowed on functions in the future, so this might be a wont fix.

**Comment by Tetralux** [comment] 2020-04-02 15:00
@ifreund That's a little confusing - It's more that they'll be allowed They will be allowed on functions - just not directly; they'll be on the binding of a function to a variable name.

**Comment by squeek502** [comment] 2020-04-03 08:10
This might explain https://github.com/ziglang/zig/issues/4280#issuecomment-589690842 as well.

**Closed** 2020-05-08 15:21 UTC
Labels: bug
