### ISSUE TITLE
vectors with non power of 2 sized elements misbehaving

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#5933] opened 2020-07-27 04:15 UTC
Using 0.6.0+485231dea from Jul  7, I was trying to use a `std.meta.Vector(5, u6)` and getting unexpected results.  The following test shows the result of creating a vector of `u1` through `u16` from an array `{ 1, 2, 3, 4, 5 }`  It seems only the power of 2 sized elements produce expected results.  

```zig
test "vectors" {
    warn("\n", .{});
    const TS = .{ u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 };
    inline for (TS) |T| {
        const array = [_]T{
            1,
            2 % std.math.maxInt(T),
            3 % std.math.maxInt(T),
            4 % std.math.maxInt(T),
            5 % std.math.maxInt(T),
        };
        warn("{: <3} - ", .{@typeName(T)});
        const V = std.meta.Vector(5, T);
        const vector: V = array;
        // creating the vector like this produces the same output
        // const vector = V{ array[0], array[1], array[2], array[3], array[4] };
        warn("array: {{", .{});
        for (array) |e| warn("{}, ", .{e});
        warn("}} vector: {}\n", .{vector});
    }
}
```
Produces:
```sh
$ zig test ../test/test1.zig --test-filter vectors
Test [1/1] test "vectors"...
u1  - array: {1, 0, 0, 0, 0, } vector: { 1, 0, 0, 0, 0 }
u2  - array: {1, 2, 0, 1, 2, } vector: { 1, 2, 0, 1, 2 }
u3  - array: {1, 2, 3, 4, 5, } vector: { 1, 1, 1, 1, 1 }
u4  - array: {1, 2, 3, 4, 5, } vector: { 1, 2, 3, 4, 5 }
u5  - array: {1, 2, 3, 4, 5, } vector: { 1, 1, 1, 1, 1 }
u6  - array: {1, 2, 3, 4, 5, } vector: { 1, 1, 1, 1, 1 }
u7  - array: {1, 2, 3, 4, 5, } vector: { 1, 1, 1, 1, 1 }
u8  - array: {1, 2, 3, 4, 5, } vector: { 1, 2, 3, 4, 5 }
u9  - array: {1, 2, 3, 4, 5, } vector: { 1, 4, 12, 32, 80 }
u10 - array: {1, 2, 3, 4, 5, } vector: { 1, 8, 48, 256, 257 }
u11 - array: {1, 2, 3, 4, 5, } vector: { 1, 16, 192, 0, 8 }
u12 - array: {1, 2, 3, 4, 5, } vector: { 1, 32, 768, 3, 64 }
u13 - array: {1, 2, 3, 4, 5, } vector: { 1, 64, 3072, 12, 512 }
u14 - array: {1, 2, 3, 4, 5, } vector: { 1, 128, 12288, 48, 4096 }
u15 - array: {1, 2, 3, 4, 5, } vector: { 1, 256, 16385, 192, 0 }
u16 - array: {1, 2, 3, 4, 5, } vector: { 1, 2, 3, 4, 5 }
All 1 tests passed.
```

**Comment by Vexu** [comment] 2020-07-27 15:52
Duplicate of #3246 which is supposedly fixed upstream.

**Closed by Vexu** 2020-07-27 15:52 UTC

**Comment by travisstaloch** [comment] 2020-07-27 16:34
Ah good. Thank you. Looks like that [llvm commit](https://github.com/llvm/llvm-project/commit/a5fa77888243beede98959ced17596b380e8de59) was from feb 24th.  llvm 10 was released on march 24th.  Does this not mean the fix should already be present or did it not make it into the llvm 10 release?

**Comment by Vexu** [comment] 2020-07-27 20:53
It seems to me like the upstream issue was closed prematurely. The generated llvm ir looks correct, but it is only correctly generated for some sizes.
