### ISSUE TITLE
Error message when a struct function is not a method could be clearer

### ISSUE THREAD

**Issue by ssteinbach** [ziglang/zig#15178] opened 2023-04-04 17:44 UTC
### Zig Version

0.11.0-dev.86+b83e4d965

### Steps to Reproduce and Observed Output

this file:
```
const std = @import("std");

pub const some_struct = struct {
    pub fn not_a_method() i32 {
        return 12;
    }
};

test "struct field error example" {
    const example = some_struct{};
    
    // not an error
    try std.testing.expectEqual(some_struct.not_a_method(), 12);

    // error
    example.not_a_method();

    // error message is:
    //
    // /var/tmp/test.zig:15:12: error: no field or member function named
    // 'not_a_method' in 'test.some_struct'
    //     example.not_a_method();
    //     ~~~~~~~^~~~~~~~~~~~~
    // /var/tmp/test.zig:3:25: note: struct declared here
    // pub const some_struct = struct {

}
```

Produces this error:

```
❯ zig test /var/tmp/test.zig
/var/tmp/test.zig:16:12: error: no field or member function named 'not_a_method' in 'test.some_struct'
    example.not_a_method();
    ~~~~~~~^~~~~~~~~~~~~
/var/tmp/test.zig:3:25: note: struct declared here
pub const some_struct = struct {
                        ^~~~~~
```

The confusing here is that it makes it sound like the `some_struct` type has no field `not_a_method`, when the reality is that while the `example` instance of the struct does not, the _type_ object does.

### Expected Output

While technically correct, the way this is worded it makes it sound as if there isn't a function in the `some_struct` named `not_a_method` at all.  The actual problem is one of the arguments to the function, not whether it exists or not.  I'd love an error message that indicates that this function doesn't have a `self` argument and/or needs to be called from the `some_struct` object rather than any instance.

```
error: struct function 'not_a_method' cannot be called from an instance and must be called from the type's namespace: 'some_struct.not_a_method(...)'
```

Thanks for taking a look!

**Comment by Vexu** [comment] 2023-04-04 19:34
Duplicate of #14880

**Closed by Vexu** 2023-04-04 19:34 UTC
Labels: error message
