### ISSUE TITLE
[SIGSEGV] Switching on parameter slice crashes

### ISSUE THREAD

**Issue by enderger** [ziglang/zig#10741] opened 2022-01-31 02:43 UTC
### Zig Version

0.9.0

### Steps to Reproduce

1. Pass a slice as an argument to a function (may happen in other circumstances, but this is what I could consistently reproduce with)
2. Switch on said slice as a pointer (in my testing, it happens if there are above ~3 cases)
3. Crash

Code:
```zig
pub fn crash(val: []const u8) !void {
    return switch(val.ptr) {
        "foo" => {},
        "bar" => {},
        "baz" => {},
        else => error.Crash,
    };
}

test {
    _ = try crash("bad"); 
}
```
Note that the crash still occurs even if the value is valid below ~case 3.

### Expected Behavior

The compiler should not segfault

### Actual Behavior

The compiler segfaults:
```
$ lldb zig
> r test ./sigsegv-switch.zig
Process 153365 launched: '/nix/store/f5vr6r76lmcmq7pqwf789dqjbvvi440w-zig-0.9.0/bin/zig' (x86_64)
Code Generation [751/832] std.fmt.formatIntValue... Process 153365 stopped
* thread #1, name = 'zig', stop reason = signal SIGSEGV: invalid address (fault address: 0x3ffff9)
    frame #0: 0x00007ffff215ce20 libLLVM-13.so`llvm::APInt::compareSigned(llvm::APInt const&) const + 144
libLLVM-13.so`llvm::APInt::compareSigned:
->  0x7ffff215ce20 <+144>: movq   (%rdx,%rax), %rcx
    0x7ffff215ce24 <+148>: movq   (%rsi,%rax), %rdi
    0x7ffff215ce28 <+152>: cmpq   %rdi, %rcx
    0x7ffff215ce2b <+155>: jne    0x7ffff215ce68            ; <+216>
> bt
* thread #1, name = 'zig', stop reason = signal SIGSEGV: invalid address (fault address: 0x3ffff9)
  * frame #0: 0x00007ffff215ce20 libLLVM-13.so`llvm::APInt::compareSigned(llvm::APInt const&) const + 144
    frame #1: 0x00007ffff28dcc9c libLLVM-13.so`void std::__insertion_sort<__gnu_cxx::__normal_iterator<llvm::SwitchCG::CaseCluster*, std::vector<llvm::SwitchCG::CaseCluster, std::allocator<
llvm::SwitchCG::CaseCluster> > >, __gnu_cxx::__ops::_Iter_comp_iter<llvm::SwitchCG::sortAndRangeify(std::vector<llvm::SwitchCG::CaseCluster, std::allocator<llvm::SwitchCG::CaseCluster> >&):
:'lambda'(llvm::SwitchCG::CaseCluster const&, llvm::SwitchCG::CaseCluster const&)> >(__gnu_cxx::__normal_iterator<llvm::SwitchCG::CaseCluster*, std::vector<llvm::SwitchCG::CaseCluster, std:
:allocator<llvm::SwitchCG::CaseCluster> > >, __gnu_cxx::__normal_iterator<llvm::SwitchCG::CaseCluster*, std::vector<llvm::SwitchCG::CaseCluster, std::allocator<llvm::SwitchCG::CaseCluster>
> >, __gnu_cxx::__ops::_Iter_comp_iter<llvm::SwitchCG::sortAndRangeify(std::vector<llvm::SwitchCG::CaseCluster, std::allocator<llvm::SwitchCG::CaseCluster> >&)::'lambda'(llvm::SwitchCG::Cas
eCluster const&, llvm::SwitchCG::CaseCluster const&)>) (.constprop.0) + 172
    frame #2: 0x00007ffff28dd564 libLLVM-13.so`llvm::SwitchCG::sortAndRangeify(std::vector<llvm::SwitchCG::CaseCluster, std::allocator<llvm::SwitchCG::CaseCluster> >&) + 132
    frame #3: 0x00007ffff2b6bdd9 libLLVM-13.so`llvm::SelectionDAGBuilder::visitSwitch(llvm::SwitchInst const&) + 185
    frame #4: 0x00007ffff2b7cc73 libLLVM-13.so`llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) + 67
    frame #5: 0x00007ffff2be0106 libLLVM-13.so`llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false,
true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, bool&) + 390
    frame #6: 0x00007ffff2be1647 libLLVM-13.so`llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) + 5287
    frame #7: 0x00007ffff2be3d86 libLLVM-13.so`llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (.part.0) + 2022
    frame #8: 0x00007ffff52aa679 libLLVM-13.so`(anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) + 89
    frame #9: 0x00007ffff26a3264 libLLVM-13.so`llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 180
    frame #10: 0x00007ffff23e7b00 libLLVM-13.so`llvm::FPPassManager::runOnFunction(llvm::Function&) + 1024
    frame #11: 0x00007ffff23e7c6c libLLVM-13.so`llvm::FPPassManager::runOnModule(llvm::Module&) + 44
    frame #12: 0x00007ffff23e95f8 libLLVM-13.so`llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1384
    frame #13: 0x0000000000d63537 zig`ZigLLVMTargetMachineEmitToFile + 4519
    frame #14: 0x0000000000c44156 zig`codegen_build_object(CodeGen*) + 10902
    frame #15: 0x0000000000c3b6e1 zig`zig_stage1_build_object + 2417
    frame #16: 0x00000000009498b3 zig`Compilation.processOneJob + 80131
    frame #17: 0x000000000092c555 zig`Compilation.update + 5109
    frame #18: 0x00000000008edf0f zig`main.updateModule + 31
    frame #19: 0x00000000008c3320 zig`main.buildOutputType + 136576
    frame #20: 0x0000000000896cd2 zig`main + 2274
    frame #21: 0x00007ffff1247780 libc.so.6`__libc_start_main + 208
    frame #22: 0x0000000000894aca zig`_start + 42
```

**Comment by Vexu** [comment] 2022-02-14 10:42
Duplicate of #7357

**Closed by Vexu** 2022-02-14 10:42 UTC
Labels: bug, stage1
