### ISSUE TITLE
`zig cc`  ld fail

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ziglang/zig#20341] opened 2024-06-18 15:37 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

reference https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html

export CC="zig cc"
make CC="$CC"

result:
![image](https://github.com/ziglang/zig/assets/59160162/d430e852-5ea8-4423-959e-76ec418a4a44)

### Expected Behavior

build success

**Comment by Vexu** [comment] 2024-06-18 20:01
Duplicate of #14089

**Closed by Vexu** 2024-06-18 20:01 UTC
Labels: bug
