### ISSUE TITLE
Segmentation fault initializing anonymous struct with local variable

### ISSUE THREAD

**Issue by jeffkdev** [ziglang/zig#5397] opened 2020-05-21 23:37 UTC
```zig
test "anon struct initialization" {
    const SomeStruct = struct {x :f32, y:f32,};
    var local: f32 = 25.0;
    const some_value = .{
        SomeStruct{ .x = local, .y = 2 },
        SomeStruct{ .x = 2, .y = 2 },
    };
}
```
```
test "anon struct initialization"...Segmentation fault at address 0x7ff77b9167b8
0x7ff77b8839d4 in test "segfaulter 9000" (test.obj)
        SomeStruct{ .x = local, .y = 2 },
                         ^
```
Happens on 0.6.0 release build and master.

**Comment by Vexu** [comment] 2020-05-22 09:35
Duplicate of #4597 and  #3915.

**Closed by Vexu** 2020-05-22 09:35 UTC
