### ISSUE TITLE
Reading the sentinel value of a slice during comptime results in out of bounds error

### ISSUE THREAD

**Issue by Laremere** [ziglang/zig#10424] opened 2021-12-27 19:27 UTC
### Zig Version

0.9.0

### Steps to Reproduce

https://www.godbolt.org/z/TjvsPbxWr

```zig
pub fn main() void {
    loopString("Test"); // Works
    comptime loopString("Test"); // Fails
}

fn loopString(str: [:0]const u8) void {
  var i: usize = 0;
  while (str[i] != 0) : (i += 1) {}
}
```

It is safe to read the sentinel value of a slice.  This works during runtime, but results in an out of bounds error during comptime.  With the recent changes to the canonical string type, string handling code running at comptime which uses this behavior will not work.  In particular `lib/std/zig/tokenizer.zig` was changed to use this behavior and no longer works at comptime.

### Expected Behavior

It returns the sentinel value during comptime, like it does during runtime.  In general code that works during runtime works during comptime, to the extent that is reasonable.

### Actual Behavior

```
./example.zig:8:13: error: out of bounds slice
  while (str[i] != 0) : (i += 1) {}
            ^
./example.zig:3:24: note: called from here
    comptime loopString("Test"); // Fails
                       ^
./example.zig:1:20: note: called from here
pub fn main() void {
                   ^
./example.zig:3:24: note: referenced here
    comptime loopString("Test"); // Fails
                       ^
Compiler returned: 1
```

**Comment by Vexu** [comment] 2021-12-27 19:47
Duplicate of #8286.

**Closed by Vexu** 2021-12-27 19:47 UTC
Labels: bug
