### ISSUE TITLE
Unexpected result when assigning a vector to itself

### ISSUE THREAD

**Issue by jedisct1** [ziglang/zig#6659] opened 2020-10-12 11:42 UTC
```zig
const std = @import("std");
const Vector = std.meta.Vector;

pub fn main() anyerror!void {
    var b = Vector(4, u32){ 1, 2, 3, 4 };
    b = Vector(4, u32){ b[3], b[2], b[1], b[0] };
    std.debug.print("{}\n", .{b});
}
```

Prints

```text
{ 4, 3, 3, 4 }
```

instead of 

```text
{ 4, 3, 2, 1 }
```

Using a temporary variable produces the correct output. Is assigning a vector containing some of its own elements UB?

**Comment by daurnimator** [comment] 2020-10-12 11:48
Possible dupe of #3696

**Comment by Vexu** [comment] 2020-10-12 11:57
Also #3234 and #6216. In the future this will hopefully either result in a copy to a temporary like #4454 or a compile error.

**Closed by Vexu** 2020-10-12 11:57 UTC
