### ISSUE TITLE
build-obj fails for sources with fn main() on Windows without -lc

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#4193] opened 2020-01-15 22:28 UTC
- fails on Windows only
- workaround: add `-lc` to command

#### reduction: `main.zig`
```zig
pub fn main() void {}
```

#### command: `zig build-obj main.zig`
```
Generate .h...TODO implement get_c_type for more types
Unable to dump stack trace: debug info stripped
```

**Comment by daurnimator** [comment] 2020-01-15 22:39
Duplicate of #2173?

**Comment by andrewrk** [comment] 2020-01-28 21:24
I'd like to let .h file generation rot in stage1, and solve it in self-hosted only. Easy solution here would be disabling .h file generation by default.

**Comment by andrewrk** [comment] 2023-02-20 00:20
Issue no longer applicable with the new compiler implementation.

**Closed by andrewrk** 2023-02-20 00:20 UTC
Labels: bug, os-windows, stage1
