### ISSUE TITLE
compiler segfault in gen_const_val

### ISSUE THREAD

**Issue by vrischmann** [ziglang/zig#7737] opened 2021-01-10 01:20 UTC
Hello,

this code crashes the compiler:
```zig
const std = @import("std");
const os = std.os;

const Session = struct {
    socket: os.socket_t,
    socket_writer: SocketWriter,
};

pub fn main() anyerror!void {
    const client_fd = try os.accept(10, null, null, 0);

    var session = .{
        .socket = client_fd,
        .socket_writer = .{ .context = client_fd },
    };
}
```

here's the crash:
```
Code Generation [346/555] std.fmt.format... Segmentation fault at address 0xec10
../src/stage1/codegen.cpp:7584:34: 0x14cf75e in gen_const_val (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:7867:46: 0x14d0bb5 in render_const_val (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:7269:33: 0x14ce06f in gen_const_val_ptr (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:7801:37: 0x14d07b5 in gen_const_val (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:7867:46: 0x14d0bb5 in render_const_val (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:1798:25: 0x14b79e6 in ir_llvm_value (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:4606:44: 0x14c3805 in ir_render_struct_field_ptr (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:6804:46: 0x14cc6e3 in ir_render_instruction (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:6972:60: 0x14cd078 in ir_render (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:8390:18: 0x14d3471 in do_code_gen (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:9563:16: 0x14d80b6 in codegen_build_object (../src/stage1/codegen.cpp)
../src/stage1/stage1.cpp:128:25: 0x14ac118 in zig_stage1_build_object (../src/stage1/stage1.cpp)
/home/vincent/dev/devtools/zig/src/stage1.zig:141:32: 0xd3e524 in Module.build_object (zig1)
        zig_stage1_build_object(mod);
                               ^
/home/vincent/dev/devtools/zig/src/Compilation.zig:3220:31: 0xb6cbf9 in Compilation.updateStage1Module (zig1)
    stage1_module.build_object();
                              ^
/home/vincent/dev/devtools/zig/src/Compilation.zig:1684:36: 0xb25c3b in Compilation.performAllTheWork (zig1)
            self.updateStage1Module(main_progress_node) catch |err| {
                                   ^
/home/vincent/dev/devtools/zig/src/Compilation.zig:1297:31: 0xb1efbd in Compilation.update (zig1)
    try self.performAllTheWork();
                              ^
/home/vincent/dev/devtools/zig/src/main.zig:1997:20: 0xac17f6 in main.updateModule (zig1)
    try comp.update();
                   ^
/home/vincent/dev/devtools/zig/src/main.zig:1838:17: 0xa0f3bf in main.buildOutputType (zig1)
    updateModule(gpa, comp, zir_out_path, hook) catch |err| switch (err) {
                ^
/home/vincent/dev/devtools/zig/src/main.zig:162:31: 0x9e659c in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/home/vincent/dev/devtools/zig/src/stage1.zig:45:24: 0x9e5fbe in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
```

I'm using Zig version `0.8.0-dev.886+29928af60`

**Comment by g-w1** [comment] 2021-01-10 01:26
For me I just get 
```
./test.zig:13:19: error: compiler bug: generating const value for struct field 'socket'
        .socket = client_fd,
                  ^
```
also where is `SocketWriter` defined? Am I missing something?

**Comment by vrischmann** [comment] 2021-01-10 01:31
It's supposed to be this:
```
const SocketWriter = io.Writer(os.socket_t, os.WriteError, socketWrite);

fn socketWrite(fd: os.socket_t, bytes: []const u8) os.WriteError!usize {
    return os.write(fd, bytes);
}
```

and yeah on godbolt it doesn't segfault as well https://gcc.godbolt.org/z/xxdG85

I have no idea what's special on my machine.

**Comment by vrischmann** [comment] 2021-01-10 01:58
So I tested on a Debian vm with the same version and there I do get 
```
./src/main.zig:20:19: error: compiler bug: generating const value for struct field 'socket'
        .socket = client_fd,
```

My main desktop runs Fedora 33.

**Comment by LemonBoy** [comment] 2021-01-12 09:09
Valgrind shows there's something fishy going on:

```
Conditional jump or move depends on uninitialised value(s)
==5318==    at 0x14F4228: gen_const_val(CodeGen*, ZigValue*, char const*) (codegen.cpp:7578)
==5318==    by 0x14F5728: render_const_val(CodeGen*, ZigValue*, char const*) (codegen.cpp:7867)
==5318==    by 0x14F2B12: gen_const_val_ptr(CodeGen*, ZigValue*, char const*) (codegen.cpp:7269)
==5318==    by 0x14F530B: gen_const_val(CodeGen*, ZigValue*, char const*) (codegen.cpp:7801)
==5318==    by 0x14F5728: render_const_val(CodeGen*, ZigValue*, char const*) (codegen.cpp:7867)
==5318==    by 0x14DBBA5: ir_llvm_value(CodeGen*, IrInstGen*) (codegen.cpp:1798)
==5318==    by 0x14E7EC8: ir_render_struct_field_ptr(CodeGen*, IrExecutableGen*, IrInstGenStructFieldPtr*) (codegen.cpp:4606)
==5318==    by 0x14F10DB: ir_render_instruction(CodeGen*, IrExecutableGen*, IrInstGen*) (codegen.cpp:6804)
==5318==    by 0x14F1A82: ir_render(CodeGen*, ZigFn*) (codegen.cpp:6972)
==5318==    by 0x14F8094: do_code_gen(CodeGen*) (codegen.cpp:8390)
==5318==    by 0x14FCFF0: codegen_build_object(CodeGen*) (codegen.cpp:9563)
==5318==    by 0x14CFBE4: zig_stage1_build_object (stage1.cpp:128)
```

**Comment by vrischmann** [comment] 2021-01-12 22:41
Simpler repro:
```zig
fn getFd() usize {
    return 20;
}

pub fn main() anyerror!void {
    const client_fd = getFd();

    var session = .{
        .socket = client_fd,
        .socket_writer = .{ .context = client_fd },
    };
}
```

**Comment by Vexu** [comment] 2021-01-26 16:58
Duplicate of #6446

**Closed by Vexu** 2021-01-26 16:58 UTC
