### ISSUE TITLE
LLVM error: Unsupported library call operation!

### ISSUE THREAD

**Issue by kassane** [ziglang/zig#7473] opened 2020-12-17 14:46 UTC
I  was trying to open a json file using `@embedFile` and so far so good. But when trying to transfer the string to `json.TokenStream`, this happens:

```zig
const std = @import("std");
const json = std.json;

pub fn main() void {
    openJson();
}
const stdout = std.io.getStdOut().writer();
fn openJson() void {
    const file = @embedFile("employer.json");
    const content = json.TokenStream.init(file);
    stdout.print("{}", .{content}) catch unreachable;
}
```

Output:
```bash
$ zig run test.zig
LLVM ERROR: Unsupported library call operation!
Aborted (core dumped)
```

**Info:**
**OS:** ArchLinux
**Zig version**: latest master

**Comment by Vexu** [comment] 2020-12-17 15:52
Duplicate of  #5959.

**Closed by Vexu** 2020-12-17 15:52 UTC
