### ISSUE TITLE
way to cast arrays to a smaller array

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1376] opened 2018-08-12 16:14 UTC
I ran into a wall when trying to implement x25519 without being able to slice-and-dice arrays into smaller arrays. (without `@ptrCast`)

**Comment by shawnl** [comment] 2018-08-12 16:29
as seen in the later example: ` @ptrCast(*[32]u32,work[32..].ptr).* = recip(@ptrCast(*[32]u32,work[32..64].ptr).*);` it should also be able to set a subset of a larger array with a smaller array.

**Comment by shawnl** [comment] 2018-08-12 16:34
```
    // https://github.com/ziglang/zig/issues/1376
    var pass64: [64]u32 = undefined;
    var pass32_a: [32]u32 = undefined;
    var pass32_b: [32]u32 = undefined;
    var pass32_c: [32]u32 = undefined;
    mem.copy(u32, pass64[0..], work[0..64]);
    mainloop(pass64,e);
    mem.copy(u32, pass32_a[0..], work[32..64]);
    pass32_b = recip(pass32_a);
    mem.copy(u32, work[32..64], pass32_b[0..32]);
    mem.copy(u32, pass32_a[0..], work[0..32]);
    mem.copy(u32, pass32_b[0..], work[32..64]);
    pass32_c = mult(pass32_a, pass32_b);
    mem.copy(u32, work[64..96], pass32_c[0..]);
    mem.copy(u32, pass32_a[0..], work[64..96]);
    freeze(pass32_a);
```

**Comment by thejoshwolfe** [comment] 2018-08-12 16:55
wait. is this issue about copying or referencing?

**Comment by shawnl** [comment] 2018-08-12 17:09
referencing, but as the function does not modify the array, copying does the same thing in this case.

**Comment by thejoshwolfe** [comment] 2018-08-12 18:01
ok. the OP was misleading then.

```zig
// this designates a storage location for 2 u32's
var smaller_array: [2]u32 = ...;

// this parameter does not necessitate any actual storage,
// and will in practice be a const reference, not a copy.
fn foo(a: [2]u32) void {}

// this is definitely a reference, not a copy.
var a: *[2]u32 = ...;
```

i think the `smaller_array` example from the OP should not work. perhaps there is something that should work with the `a` examples in this comment.

here's an idea:

```zig
var array: [64]u32 = ...;
var first_half: *[32]u32 = array[0..32];
var second_half: *[32]u32 = array[32..];
```

In order for this to work, the compiler would need to know the slicing index/bounds at comptime. That's kind of an awkward requirement, since the comptime-knownness of values determines what kinds of type casts are allowed.

More specifically, the compiler really only needs to know the length of the resulting slice, not the start index. That's even more awkward, since you could do `array[x..x+32]`, where `x` is not comptime known; then neither of the slice values are comptime known, but the length of the slice could be known if you pay sophisticated enough attention to the slicing expressions.

This is leading me to think that maybe this operation should really be a different feature. How about this builtin function:

```zig
var array: [64]u32 = ...;
var first_half: *[32]u32 = @arrayPtr(array, 0, 32);
var first_half: *[32]u32 = @arrayPtr(array, 32, 32);

// pseudocode signature:
fn @arrayPtr(array: [n]T, start: usize, comptime len: usize) *[len]T;
```

I can almost imagine this being implemented in userspace, except for some complications with propagating `const` qualifiers, and maybe the function should also take a slice in addition to an array.

**Comment by shawnl** [comment] 2018-08-12 18:05
> More specifically, the compiler really only needs to know the length of the resulting slice, not the start index. 

Also the alignment (not on x86 or arm64 or armv7, but for other arches)

**Comment by shawnl** [comment] 2018-08-12 18:08
Maybe the correct solution is just to use a union.

**Comment by Hejsil** [comment] 2018-08-12 20:00
I think #863 is related?

**Comment by thejoshwolfe** [comment] 2018-08-13 18:00
@Hejsil ah, yes. that's what i was going for.

@shawnl i'm still confused why "visa versa" is in the title of this issue. wouldn't "casting" from a smaller array into a larger array only be meaningful with copying?

**Comment by tgschultz** [comment] 2018-08-15 11:54
I went ahead and implemented a variation of `@arrayPtr` in userspace for the next version of my utils package. It was, as predicted, just a little hairy because of the const/non-const distinction, but I'd already solved that for a different function in utils. I've copied appropriate support functions into this code for convenience.

```
fn isConst(comptime T: type) bool
{
    comptime
    {
        if(!isPointer(T)) return false;
        const info = @typeInfo(T);
        return info.Pointer.is_const;
    }
}

fn isPointer(comptime T: type) bool
{
    comptime
    {
        const inp_type_id = @typeId(T);
        return inp_type_id == builtin.TypeId.Pointer;
    }
}

fn isSingleItemPointer(comptime T: type) bool
{
    comptime
    {
        if(isPointer(T))
        {
            const info = @typeInfo(T);
            return info.Pointer.size == builtin.TypeInfo.Pointer.Size.One;
        }
        return false;
    }
}

fn isArray(comptime T: type) bool
{
    comptime
    {
        const inp_type_id = @typeId(T);
        return inp_type_id == builtin.TypeId.Array;
    }
}

fn _ArraySliceReturnType(comptime T: type, comptime len: usize) type
{
    debug.assert(isSingleItemPointer(T));
    debug.assert(isArray(T.Child));
    
    if(isConst(T))
    {
        return *const [len]T.Child.Child;
    }
    return *[len]T.Child.Child;
}

pub fn arraySlice(ptr: var, comptime start: usize, comptime len: usize)
    _ArraySliceReturnType(@typeOf(ptr), len)
{
    debug.assert(isSingleItemPointer(@typeOf(ptr)));
    debug.assert(isArray(@typeOf(ptr).Child));
    
    return @ptrCast(_ArraySliceReturnType(@typeOf(ptr), len), &ptr.*[start]);
}

test "arraySlice"
{
    const array = comptime arr:
    {
        var temp = []u32{0} ** 64;
        for(temp) |*e, i| e.* = @intCast(u32, i);
        break :arr temp;
    };
    
    const first_half = arraySlice(&array, 0, 32);
    const second_half = arraySlice(&array, 32, 32);
    
    for(first_half.*) |e, i|
    {
        debug.assert(i == e);
    }
    
    for(second_half.*) |e, i|
    {
        debug.assert(i + 32 == e);
    }
}
```

**Comment by tgschultz** [comment] 2019-06-04 15:58
It should be noted that this has long since been included in `std.meta`.

**Comment by andrewrk** [comment] 2019-07-02 23:26
I'm fairly certain this is a duplicate of the accepted proposal  #863

**Closed by andrewrk** 2019-07-02 23:26 UTC
Labels: proposal
