### ISSUE TITLE
string literals of differing sizes are type incompatible but only as arguments

### ISSUE THREAD

**Issue by zenspider** [ziglang/zig#12452] opened 2022-08-15 06:52 UTC
### Zig Version

0.10.0-dev.3457+5c9826630

### Steps to Reproduce

bad:
```zig
        print("{s}\n", .{(if (std.meta.eql(exp, act)) "GOOD" else "BAD")});
        // ./zlox.zig:583:67: error: expected type '*const [4:0]u8', found '*const [3:0]u8'
```
ok:
```zig
        const r = (if (std.meta.eql(exp, act)) "GOOD" else "BAD");
        print("{s}\n", .{r});
```

### Expected Behavior

same in both? more intelligent/flexibly typing of string literals. Can they all be `const [_:0]u8`?

seems like if the first example can work, the second one can too even if by behind-the-scenes variable lifting.

### Actual Behavior

see above

**Comment by Vexu** [comment] 2022-08-15 08:06
Duplicate of #3882

**Closed by Vexu** 2022-08-15 08:06 UTC
Labels: bug
