### ISSUE TITLE
packed struct - strange field offset

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#2713] opened 2019-06-20 01:57 UTC
This program displays 4 for the offset of b, where I am expecting it to be 16.

    Linux localhost 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
    0.4.0+381c6a38

    const std = @import("std");

    const S = packed struct {
        a: u32,
        pad: [3]u32,
        b: u32
    };

    pub fn main() anyerror!void {
        var offset: usize = @byteOffsetOf(S, "b");
        std.debug.warn("offset {}\n", offset);
    }

**Comment by timonkruiper** [comment] 2019-06-20 08:44
Related: #2627

**Comment by SamTebbs33** [comment] 2019-06-20 09:48
Yeah this is a duplicate of the issue linked by @timonkruiper I found a little while ago, where the total size of the struct is also wrong.

**Closed** 2019-06-26 14:32 UTC
