### ISSUE TITLE
std.fmt: A signed 3 formatted w/ "{d:0>4}" gives "00+3"

### ISSUE THREAD

**Issue by rofrol** [ziglang/zig#20040] opened 2024-05-22 19:21 UTC
### Zig Version

0.13.0-dev.242+6635360db

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const print = std.debug.print;

pub fn main() !void {
    // A signed 3 formatted w/ "{d:0>4}" gives "00+3".
    // https://x.com/karlseguin/status/1792374097009357302
    const n: i32 = 3;
    print("{d:0>4}\n", .{n}); // 00+3
}
```

prints `00+3`.

works correctly with `u32`.

### Expected Behavior

prints `0003`.

**Comment by rofrol** [comment] 2024-05-22 19:21
@karlseguin

**Comment by Vexu** [comment] 2024-05-22 19:32
Duplicate of #14436

**Closed by Vexu** 2024-05-22 19:32 UTC
Labels: bug
