### ISSUE TITLE
Suggestion: make returning pointer to stack memory created in the same scope a compiler error

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#13441] opened 2022-11-04 07:15 UTC
One spot where Zig lags behind C compilers in memory safety: returning a pointer to a temporary created in the same scope (specifically when the value is not comptime known)

For people new to manual memory management, [this is a footgun](https://github.com/oven-sh/bun/commit/70e778c2a85836f8139597c0bb0f5fe10e74610f?diff=split)

In C:
```c
static char *myFunction() {
  char buf[200];
  buf[0] = 'h';
  buf[1] = 'e';
  buf[2] = 'y';
  buf[3] = '!';

  return buf;
}

int main(void) { myFunction(); }
```

Compile:

```c
$ clang hey.c

hey.c:11:10: warning: address of stack memory associated with local variable 'buf' returned [-Wreturn-stack-address]
  return buf;
         ^~~
1 warning generated.
```

In Zig:

```zig
fn myFunction() []u8 {
    var buf: [100]u8 = undefined;
    buf[0.."hello".len].* = "hello".*;
    return buf[0..];
}

pub fn main() anyerror!void {
  std.mem.doNotOptimizeAway(myFunction());
}
```

Compile:
```bash
$ zig build-exe hey.zig
# no error
```

**Comment by andrewrk** [comment] 2022-11-04 07:32
duplicate of #2646

**Closed by andrewrk** 2022-11-04 07:32 UTC
