### ISSUE TITLE
Zig 0.7.1 allows user to return addresses of local variables

### ISSUE THREAD

**Issue by LucasToole** [ziglang/zig#8702] opened 2021-05-07 02:37 UTC
Contents of a function are still accessible even after their lifetime. For example: 
```
const std = @import("std");

pub fn main() anyerror!void {
    const test_ptr: *i32 = test_func();
    std.debug.print("Address: {}\n", .{test_ptr});
    std.debug.print("Value: {}\n", .{test_ptr.*});
}

fn test_func() *i32 {
    var test_var: i32 = 5;
    return &test_var;
}
```
Results in: 
```
$ zig run localaddress.zig
Address: i32@7fff157f79a4
Value: 5
```

The equivalent C code:
```
#include <stdio.h>

int* test_func() {
	int test_var = 5;
	return &test_var;
}

int main(void) {
	int *test_ptr = test_func();
	printf("Address: %ls\n", test_ptr);
	printf("Value: %d\n", *test_ptr);
	return 0;
}
```
Produces a compile-time warning:
```
$ gcc localaddr.c -o localaddr
localaddr.c: In function ‘test_func’:
localaddr.c:5:9: warning: function returns address of local variable [-Wreturn-local-addr]
    5 |  return &test_var;
      |         ^~~~~~~~~
```
And produces:
```
$ ./localaddr 
Address: (null)
Segmentation fault
```

**Comment by g-w1** [comment] 2021-05-07 02:40
Dupe of https://github.com/ziglang/zig/issues/2646

**Comment by LucasToole** [comment] 2021-05-07 02:48
@g-w1 Oops, sorry about that! I'll do more searching in the future.

**Closed** 2021-05-07 03:17 UTC
