### ISSUE TITLE
stage2: crash after emitting a compile error

### ISSUE THREAD

**Issue by davidgm94** [ziglang/zig#13654] opened 2022-11-26 14:30 UTC
### Zig Version

0.11.0-dev.251+7c527c6df

### Steps to Reproduce and Observed Behavior

```
git clone https://github.com/davidgm94/rise.git
cd rise
git checkout zig-compile-error-crash
zig build
```

```
Semantic Analysis [2355] mem... /home/david/dev/zig/stage3/lib/zig/std/mem.zig:3191:9: error: expected single item pointer, passed [3]u32
        @compileError("expected single item pointer, passed " ++ @typeName(P));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/david/dev/zig/stage3/lib/zig/std/mem.zig:3199:47: note: called from here
pub fn asBytes(ptr: anytype) AsBytesReturnType(@TypeOf(ptr)) {
                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
thread 238089 panic: Zig compiler bug: attempted to destroy declaration with an attached error
Analyzing /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
      %1314 = decl_ref("common") token_offset:224:52 to :224:58
      %1315 = dbg_stmt(166, 58)
      %1316 = field_ptr(%1314, "std") node_offset:224:52 to :224:62
      %1317 = dbg_stmt(166, 62)
      %1318 = field_ptr(%1316, "mem") node_offset:224:52 to :224:66
      %1319 = dbg_stmt(166, 66)
      %1320 = field_call_bind(%1318, "asBytes") node_offset:224:52 to :224:74
      %1321 = dbg_stmt(166, 74)
    > %1322 = call(.auto, %1320, [
        {
          %1323 = load(%1246) node_offset:224:75 to :224:83
          %1324 = break_inline(%1322, %1323)
        },
      ]) node_offset:224:52 to :224:84
      %1325 = break_inline(%1312, %1322)
    For full context, use the command
      zig ast-check -t /home/david/dev/rise/src/common/disk.zig

  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %1312 = call(.auto, %1310, [
        {%1313},
        {%1314..%1325},
        {%1326, %1327},
      ]) node_offset:224:25 to :224:94
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %1303 = block({%1304..%1336}) node_offset:223:215 to :223:216
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %1288 = block({%1302..%1337}) node_offset:223:17 to :223:22
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %1286 = condbr(%1285, {%1290..%1338}, {%1339}) node_offset:223:17 to :223:22
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %1287 = block({%1266..%1286}) node_offset:223:17 to :223:22
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %1265 = loop({%1287, %1289}) node_offset:223:17 to :223:22
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %984 = block({%985..%1344}) node_offset:159:82 to :159:83
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %975 = condbr(%974, {%981..%1346}, {%1347}) node_offset:159:13 to :159:16
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %976 = block({%973..%975}) node_offset:159:13 to :159:16
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %972 = loop({%976..%980}) node_offset:159:13 to :159:16
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %309 = block({%310..%1351}) node_offset:81:39 to :81:40
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %304 = condbr(%303, {%306..%1360}, {%1353..%1361}) node_offset:81:9 to :81:11
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %305 = block({%303, %304}) node_offset:81:9 to :81:11
  in /home/david/dev/rise/src/common/disk.zig: src/common/disk.zig:Descriptor.image
    > %164 = block({%165..%1366}) node_offset:59:165 to :59:166
  in /home/david/dev/rise/build.zig: build.zig:DiskImage.make
    > %1541 = try(%1495, {%1542..%1544}) node_offset:259:35 to :259:38
  in /home/david/dev/rise/build.zig: build.zig:DiskImage.make
    > %1482 = block({%1483..%1551}) node_offset:258:30 to :258:31
  in /home/david/dev/rise/build.zig: build.zig:DiskImage.make
    > %1478 = switch_block(%1475,
        %1480 => {%1481..%1554},
        %1556 => {%1557..%1564}) node_offset:257:17 to :257:23
  in /home/david/dev/rise/build.zig: build.zig:DiskImage.make
    > %1461 = block({%1462..%1568}) node_offset:255:24 to :255:25
  in /home/david/dev/rise/build.zig: build.zig:DiskImage.make
    > %1457 = switch_block(%1454,
        else => {%1571..%1573},
        %1459 => {%1460..%1570}) node_offset:254:9 to :254:15
  in /home/david/dev/rise/build.zig: build.zig:DiskImage.make
    > %1370 = block({%1371..%1610}) node_offset:243:32 to :243:33

/home/david/dev/zig/src/Module.zig:3487:13: 0x7abbe93 in destroyDecl (zig)
            @panic("Zig compiler bug: attempted to destroy declaration with an attached error");
            ^
/home/david/dev/zig/src/Sema.zig:6910:33: 0x872765c in instantiateGenericCall (zig)
        errdefer mod.destroyDecl(new_decl_index);
                                ^
/home/david/dev/zig/src/Sema.zig:6204:40: 0x844db0d in analyzeCall (zig)
        if (sema.instantiateGenericCall(
                                       ^
/home/david/dev/zig/src/Sema.zig:6016:32: 0x8005693 in zirCall (zig)
        return sema.analyzeCall(block, func, func_src, call_src, modifier, ensure_result_used, resolved_args, bound_arg_src);
                               ^
/home/david/dev/zig/src/Sema.zig:818:62: 0x7deb49a in analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst),
                                                             ^
/home/david/dev/zig/src/Sema.zig:719:45: 0x7c40022 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/david/dev/zig/src/Sema.zig:669:50: 0x84494c5 in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 ^
/home/david/dev/zig/src/Sema.zig:5965:46: 0x80051b9 in zirCall (zig)
        const resolved = try sema.resolveBody(block, args_body[arg_start..arg_end], inst);
                                             ^
/home/david/dev/zig/src/Sema.zig:818:62: 0x7deb49a in analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst),
                                                             ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:683:30: 0x8485a5a in analyzeBodyRuntimeBreak (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/david/dev/zig/src/Sema.zig:16175:37: 0x80c6643 in zirCondbr (zig)
    try sema.analyzeBodyRuntimeBreak(&sub_block, then_body);
                                    ^
/home/david/dev/zig/src/Sema.zig:1459:61: 0x7dfbe65 in analyzeBodyInner (zig)
                if (!block.is_comptime) break sema.zirCondbr(block, inst);
                                                            ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:702:30: 0x7fb8c08 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/david/dev/zig/src/Sema.zig:4942:25: 0x80c343e in zirLoop (zig)
    try sema.analyzeBody(&loop_block, body);
                        ^
/home/david/dev/zig/src/Sema.zig:1337:68: 0x7dfa3bc in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirLoop(block, inst);
                                                                   ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:683:30: 0x8485a5a in analyzeBodyRuntimeBreak (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/david/dev/zig/src/Sema.zig:16175:37: 0x80c6643 in zirCondbr (zig)
    try sema.analyzeBodyRuntimeBreak(&sub_block, then_body);
                                    ^
/home/david/dev/zig/src/Sema.zig:1459:61: 0x7dfbe65 in analyzeBodyInner (zig)
                if (!block.is_comptime) break sema.zirCondbr(block, inst);
                                                            ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:702:30: 0x7fb8c08 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/david/dev/zig/src/Sema.zig:4942:25: 0x80c343e in zirLoop (zig)
    try sema.analyzeBody(&loop_block, body);
                        ^
/home/david/dev/zig/src/Sema.zig:1337:68: 0x7dfa3bc in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirLoop(block, inst);
                                                                   ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:683:30: 0x8485a5a in analyzeBodyRuntimeBreak (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/david/dev/zig/src/Sema.zig:16175:37: 0x80c6643 in zirCondbr (zig)
    try sema.analyzeBodyRuntimeBreak(&sub_block, then_body);
                                    ^
/home/david/dev/zig/src/Sema.zig:1459:61: 0x7dfbe65 in analyzeBodyInner (zig)
                if (!block.is_comptime) break sema.zirCondbr(block, inst);
                                                            ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:702:30: 0x7fb8c08 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/david/dev/zig/src/Module.zig:5639:21: 0x7dd022e in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/david/dev/zig/src/Module.zig:4338:40: 0x7c20b62 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/david/dev/zig/src/Sema.zig:27367:36: 0x8519f6f in ensureFuncBodyAnalyzed (zig)
    sema.mod.ensureFuncBodyAnalyzed(func) catch |err| {
                                   ^
/home/david/dev/zig/src/Sema.zig:29515:40: 0x80f805d in resolveInferredErrorSet (zig)
        try sema.ensureFuncBodyAnalyzed(ies.func);
                                       ^
/home/david/dev/zig/src/Sema.zig:27646:49: 0x80c8706 in analyzeIsNonErrComptimeOnly (zig)
                try sema.resolveInferredErrorSet(block, src, ies);
                                                ^
/home/david/dev/zig/src/Sema.zig:16226:60: 0x80c76e0 in zirTry (zig)
    const is_non_err = try sema.analyzeIsNonErrComptimeOnly(parent_block, operand_src, err_union);
                                                           ^
/home/david/dev/zig/src/Sema.zig:1505:67: 0x7dfd466 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirTry(block, inst);
                                                                  ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:683:30: 0x8485a5a in analyzeBodyRuntimeBreak (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/david/dev/zig/src/Sema.zig:10407:45: 0x80289b6 in zirSwitchBlock (zig)
            try sema.analyzeBodyRuntimeBreak(&case_block, body);
                                            ^
/home/david/dev/zig/src/Sema.zig:883:69: 0x7deed9d in analyzeBodyInner (zig)
            .switch_block                 => try sema.zirSwitchBlock(block, inst),
                                                                    ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:683:30: 0x8485a5a in analyzeBodyRuntimeBreak (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/david/dev/zig/src/Sema.zig:10407:45: 0x80289b6 in zirSwitchBlock (zig)
            try sema.analyzeBodyRuntimeBreak(&case_block, body);
                                            ^
/home/david/dev/zig/src/Sema.zig:883:69: 0x7deed9d in analyzeBodyInner (zig)
            .switch_block                 => try sema.zirSwitchBlock(block, inst),
                                                                    ^
/home/david/dev/zig/src/Sema.zig:5116:34: 0x848a26c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/david/dev/zig/src/Sema.zig:5099:33: 0x80c403c in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/david/dev/zig/src/Sema.zig:1351:69: 0x7dfa923 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/david/dev/zig/src/Sema.zig:702:30: 0x7fb8c08 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/david/dev/zig/src/Module.zig:5639:21: 0x7dd022e in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/david/dev/zig/src/Module.zig:4338:40: 0x7c20b62 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/david/dev/zig/src/Compilation.zig:3142:42: 0x7c1e9dd in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/david/dev/zig/src/Compilation.zig:3080:30: 0x7b045fe in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/david/dev/zig/src/Compilation.zig:2389:31: 0x7b004c5 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/david/dev/zig/src/main.zig:3347:20: 0x7b2dba6 in updateModule (zig)
    try comp.update();
                   ^
/home/david/dev/zig/src/main.zig:3957:21: 0x7a1dc82 in cmdBuild (zig)
        updateModule(gpa, comp, .none) catch |err| switch (err) {
                    ^
/home/david/dev/zig/src/main.zig:261:24: 0x79efc2e in mainArgs (zig)
        return cmdBuild(gpa, arena, cmd_args);
                       ^
/home/david/dev/zig/src/main.zig:174:20: 0x79ee800 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/david/dev/zig/lib/std/start.zig:614:37: 0x79f0d91 in main (zig)
            const result = root.main() catch |err| {
                                    ^
```                                    

### Expected Behavior

Not a crash

**Comment by Vexu** [comment] 2022-11-26 14:31
Duplicate of #13354

**Closed by Vexu** 2022-11-26 14:31 UTC
Labels: bug
