### ISSUE TITLE
std.Build.RunStep only works once on windows

### ISSUE THREAD

**Issue by Jack-Ji** [ziglang/zig#14666] opened 2023-02-17 14:13 UTC
### Zig Version

0.11.0-dev.1639+438b71155

### Steps to Reproduce and Observed Behavior

Create a new project and run it more than once, only works the first time.

> zig init-exe

> zig build run

> zig build run

### Expected Behavior

Running command should always work as long as executable is normal.

**Comment by star-tek-mb** [comment] 2023-02-17 14:17
Duplicate of #14646

**Comment by hazeycode** [comment] 2023-02-17 22:31
I also ran into this on Linux. It seems to happen somewhat randomly and can be remedied by deleting zig-cache and building afresh

**Comment by InKryption** [comment] 2023-02-17 22:34
Did you try setting the run step's `condition` field to `.always`?

**Comment by andrewrk** [comment] 2023-02-17 22:43
Presumably the point of a build system is to only rebuild outdated build artifacts. I made a recent change that detects whether a RunStep is intended to be run in order to produce an output file, or whether it appears to be intended to be used for the side effects (because there are no outputs). The `condition` field is a way to override the default.

I'm guessing, since it was working for you before, that you do not in fact have any output args, and the default logic is actually not behaving correctly.

**Comment by Namek** [comment] 2023-02-18 13:34
The same happens on MacOS M1. After I delete some artifacts, the run step executes app. If there is nothing to compile/link then nothing runs. In my case it doesn't seem to be random in any way.

In case anyone would be searching for a workaround:
```zig
    const run_cmd = exe.run();
    run_cmd.condition = .always;
```

**Comment by andrewrk** [comment] 2023-02-18 17:57
I think this is the fix:

```diff
--- a/lib/std/Build/RunStep.zig
+++ b/lib/std/Build/RunStep.zig
@@ -192,6 +192,10 @@ fn stdIoActionToBehavior(action: StdIoAction) std.ChildProcess.StdIo {
 }
 
 fn needOutputCheck(self: RunStep) bool {
+    switch (self.condition) {
+        .always => return false,
+        .output_outdated => {},
+    }
     if (self.extra_file_dependencies.len > 0) return true;
 
     for (self.argv.items) |arg| switch (arg) {
@@ -199,10 +203,7 @@ fn needOutputCheck(self: RunStep) bool {
         else => continue,
     };
 
-    return switch (self.condition) {
-        .always => false,
-        .output_outdated => true,
-    };
+    return false;
 }
 
 fn make(step: *Step) !void {
```

I just need to add a test and then I open a PR for it.

**Closed** 2023-02-19 00:33 UTC
Labels: bug, zig build system, regression
