### ISSUE TITLE
Remove fields on `type` redundant with @typeInfo

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#6207] opened 2020-08-31 00:17 UTC
I think these are already deprecated from scattered comments on issues, but it would be nice to have an accepted issue to point to.

- `Int`
    - `bit_count`
    - `is_signed`
- `Float`
    - `bit_count`
- `Pointer`
    - `Child`
    - `alignment`
- `Array`
    - `Child`
    - `len`
- `ErrorUnion`
    - `Payload`
    - `ErrorSet`
- `Optional`
    - `Child`
- `Fn`
    - `ReturnType`
    - `is_var_args`
    - `arg_count`

**Comment by daurnimator** [comment] 2020-08-31 00:20
Notably, if we remove these (which I think we should), they should be removed from error messages too.
Infact, the change in error messages can occur first.

**Comment by tadeokondrak** [comment] 2020-08-31 00:52
I think the only time it shows up in error messages is for the name of an inferred error set:
```cpp
buf_appendf(&err_set_type->name, "@TypeOf(%s).ReturnType.ErrorSet", buf_ptr(&fn_entry->symbol_name));
```
Not sure what to replace it with.

**Comment by Vexu** [comment] 2020-08-31 07:43
Duplicate of #2117 assuming it applies to all the other redundant fields.

**Comment by lithdew** [comment] 2020-09-03 15:31
@Vexu would it be possible to have `zig fmt` replace usages of these deprecated fields with their standard library equivalents?

**Comment by Vexu** [comment] 2020-09-03 15:37
No. `zig fmt` doesn't know anything about types and would just lead to more breakage. However I believe these are quite rare in anything made after the introduction of `@typeInfo`.

**Closed** 2020-09-05 10:58 UTC
Labels: accepted, proposal
