### ISSUE TITLE
Missing stack trace for `error: accessing union field 'Pointer' while field 'Int' is set` 

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#12780] opened 2022-09-08 08:22 UTC
### Zig Version

0.10.0-dev.3880+e2bb92b2e

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() !void {
    var xy: u32 = 0;
    std.heap.page_allocator.free(xy);
}
```

### Expected Behavior

For fixing compiler errors I really need to know the stack trace, otherwise I'm searching blind.
This works in stage1:
```
$ zig run test.zig -fstage1
/home/mint/Downloads/zig/lib/std/mem/Allocator.zig:498:45: error: accessing union field 'Pointer' while field 'Int' is set
    const Slice = @typeInfo(@TypeOf(memory)).Pointer;
                                            ^
./test.zig:5:33: note: called from here
    std.heap.page_allocator.free(xy);
                                ^
./test.zig:3:21: note: called from here
pub fn main() !void {
                    ^
```

### Actual Behavior

In stage2 I only get the information where the union is declared, which doesn't help me:
```
$ zig run test.zig
/home/mint/Downloads/zig/lib/std/mem/Allocator.zig:498:45: error: access of union field 'Pointer' while field 'Int' is active
    const Slice = @typeInfo(@TypeOf(memory)).Pointer;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/mint/Downloads/zig/lib/std/builtin.zig:193:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
```

**Comment by Vexu** [comment] 2022-09-08 09:17
Duplicate of #7668

**Closed by Vexu** 2022-09-08 09:17 UTC
Labels: bug
