### ISSUE TITLE
packed union int struct segmentation fault

### ISSUE THREAD

**Issue by abdulbahajaj** [ziglang/zig#11518] opened 2022-04-24 22:05 UTC
### Zig Version

0.10.0-dev.1717+91eb1af91

### Steps to Reproduce

Run the following
```zig
const ops = packed union {
    one: u10,
};

const a = packed struct {
    ops: ops,
};

pub fn main() !void {
    var s = a{
        .ops = ops{
            .one = 30,
        },
    };
    _ = s.ops.one;
}
```

### Expected Behavior

For the code to compile

### Actual Behavior

The compiler itself is failing with:

Job 1, 'zig build-exe {redacted filename}' terminated by signal SIGSEGV (Address boundary error)

Note: that the code compiles when the packed union uses an int size that is the power of 2 ( e.g. u8 instead of u10 ).

**Comment by matu3ba** [comment] 2022-04-24 22:12
Does https://github.com/ziglang/zig/commit/cf20b97b713d992d84fdd8935ef935f61ed6d747 fix this problem?

**Comment by ominitay** [comment] 2022-04-24 22:13
Possible duplicate of #10686?

**Comment by matu3ba** [comment] 2022-04-24 22:18
Nope, problem persists with https://github.com/ziglang/zig/commit/cf20b97b713d992d84fdd8935ef935f61ed6d747:
```sh
zig run packedstr2.zig 
Segmentation fault at address 0x0
Abgebrochen (Speicherabzug geschrieben)
```

running in debug build...

**Comment by Vexu** [comment] 2023-01-19 16:14
Fixed in self-hosted:
```
$ git grep "packed union in packed struct" test
test/behavior/union.zig:test "packed union in packed struct" {
```

**Closed by Vexu** 2023-01-19 16:14 UTC
Labels: bug, stage1
