### ISSUE TITLE
Improper behavior of volatile packed struct on riscv32

### ISSUE THREAD

**Issue by Jeff-Ciesielski** [ziglang/zig#13158] opened 2022-10-14 11:42 UTC
### Zig Version

0.10.0-dev.4253+fa9327ac0

### Steps to Reproduce

Create a volatile packed struct containing 8 bits. Assign bit 0 and bit 7. 

```
fn mmio(address: u32, comptime mmio_type: type) *volatile mmio_type {
    return @intToPtr(*volatile mmio_type, address);
}

const GPO = mmio(0x20002000,  packed struct {
    a: u1,
    b: u1,
    c: u1,
    d: u1,
    e: u1,
    f: u1,
    g: u1,
    h: u1
});

export fn entry() void {
    GPO.a = 1;
    GPO.h = 1;
}
```

### Expected Behavior

I'd expect to load the first 8 bits at the specified address, or it with 1, store it, then re-load, or with 128, and store again.

V0.9.0 assembly listing
```
        addi    sp, sp, -16
        sw      ra, 12(sp)
        sw      s0, 8(sp)
        addi    s0, sp, 16
        lui     a1, 131074
        lb      a0, 0(a1)
        ori     a0, a0, 1
        sb      a0, 0(a1)
        lb      a0, 0(a1) < --  correct address loaded
        ori     a0, a0, 128
        sb      a0, 0(a1)
        lw      s0, 8(sp)
        lw      ra, 12(sp)
        addi    sp, sp, 16
        ret
```

### Actual Behavior

What seems to instead happen is that the initial load works, but the second load is offset by one byte, causing incorrect behavior.

Trunk assembly
```
        addi    sp, sp, -16
        sw      ra, 12(sp)
        sw      s0, 8(sp)
        addi    s0, sp, 16
        lui     a1, 131074
        lb      a0, 0(a1)
        ori     a0, a0, 1
        sb      a0, 0(a1)
        lb      a0, 1(a1) <--- This offset is incorrect
        ori     a0, a0, 128
        sb      a0, 1(a1)
        lw      ra, 12(sp)
        lw      s0, 8(sp)
        addi    sp, sp, 16
        ret
```

See godbolt link: https://godbolt.org/z/sbdqGdhcn

**Comment by Vexu** [comment] 2022-10-18 16:20
Duplicate of #12363

**Closed by Vexu** 2022-10-18 16:20 UTC
Labels: bug, stage2, backend-llvm
