### ISSUE TITLE
read from bool is_var_args with value 3, possibly uninitialized

### ISSUE THREAD

**Issue by numsim1415** [ziglang/zig#1638] opened 2018-10-05 22:05 UTC
I used gcc's flag `-fsanitize=undefined`  and then ran `./zig build --build-file ../build.zig test`, which yields
`runtime error: load of value 3, which is not a valid value for type 'bool'`
which comes from line 17060 of [ir.cpp](https://github.com/ziglang/zig/blob/c81a4b3e3d75577b69f37f57a21d2434019fa41d/src/ir.cpp#L17060) 
```rust
bool is_varargs = fn_node->is_var_args;
```
I checked with a debugger and indeed `is_var_args` reliably has a value of `3` in both Debug and RelWithDebInfo builds. Grepping for `is_var_args.*=` I found no code that assigns a value other than a boolean one.
Is this a possible bug?

Sincerely

**Comment by andrewrk** [comment] 2021-11-24 21:25
> Is this a possible bug?

Yes but this issue does not give enough information to solve the bug, and it is likely a duplicate of another issue.

**Closed by andrewrk** 2021-11-24 21:25 UTC
Labels: bug
