### ISSUE TITLE
Unexpected behavior changes between optimization modes in child process output collection

### ISSUE THREAD

**Issue by brianferri** [ziglang/zig#21838] opened 2024-10-28 09:56 UTC
### Zig Version

0.13.0 (MacOS 15.0.1)

### Steps to Reproduce and Observed Behavior

- `git clone https://github.com/brianferri/Zig-Child.run`
- cd into the cloned repo
- `zig build -Doptimize=Debug run -- ls -a` -> Exits normally
```shell
 brianferri in …/Zig-Child.run on  main at  10:46 ❯ zig build -Doptimize=Debug run -- ls -a       
info: Child process exited with out: .
..
.git
.gitignore
.vscode
.zig-cache
build.zig
build.zig.zon
src
zig-out
```
- `zig build -Doptimize=ReleaseSafe run -- ls -a` -> `thread xxx panic: reached unreachable code`
```shell
 brianferri in …/Zig-Child.run on  main at  10:46 ❯ zig build -Doptimize=ReleaseSafe run -- ls -a 
thread 273404 panic: reached unreachable code
run
└─ run Zig-Child.run failure
error: the following command terminated unexpectedly:
/Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run/zig-out/bin/Zig-Child.run ls -a 
Build Summary: 3/5 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run Zig-Child.run failure
error: the following build command failed with exit code 1:
/Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run/.zig-cache/o/2150b426a8144f5f03b6246bfff63461/build /opt/homebrew/Cellar/zig/0.13.0/bin/zig /Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run /Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run/.zig-cache /Users/brianferri/.cache/zig --seed 0x4b0119d4 -Z74439805628802fe -Doptimize=ReleaseSafe run -- ls -a
```
- `zig build -Doptimize=ReleaseSmall run -- ls -a` -> Fails without apparent error
```shell
 brianferri in …/Zig-Child.run on  main at  10:47 ❯ zig build -Doptimize=ReleaseSmall run -- ls -a
run
└─ run Zig-Child.run failure
error: the following command terminated unexpectedly:
/Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run/zig-out/bin/Zig-Child.run ls -a 
Build Summary: 3/5 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run Zig-Child.run failure
error: the following build command failed with exit code 1:
/Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run/.zig-cache/o/2150b426a8144f5f03b6246bfff63461/build /opt/homebrew/Cellar/zig/0.13.0/bin/zig /Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run /Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run/.zig-cache /Users/brianferri/.cache/zig --seed 0xdd3b791b -Z16cf26e22baa7c74 -Doptimize=ReleaseSmall run -- ls -a
```
- `zig build -Doptimize=ReleaseFast run -- ls -a` -> Fails without apparent error
```shell
 brianferri in …/Zig-Child.run on  main at  10:47 ❯ zig build -Doptimize=ReleaseFast run -- ls -a 
run
└─ run Zig-Child.run failure
error: the following command terminated unexpectedly:
/Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run/zig-out/bin/Zig-Child.run ls -a 
Build Summary: 3/5 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run Zig-Child.run failure
error: the following build command failed with exit code 1:
/Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run/.zig-cache/o/2150b426a8144f5f03b6246bfff63461/build /opt/homebrew/Cellar/zig/0.13.0/bin/zig /Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run /Users/brianferri/Desktop/Main/Scripts/_Misc/Repros/Zig-Child.run/.zig-cache /Users/brianferri/.cache/zig --seed 0xa67cf8dc -Z9235edd05b12e303 -Doptimize=ReleaseFast run -- ls -a
```

### Expected Behavior

I'd expect the Releases to work the same as Debug code

**Comment by brianferri** [comment] 2024-10-28 10:01
I've debugged some of it and noticed that the issue presents itself in:
```zig
// .../zig/0.13.0/lib/zig/std/process/Child.zig
396 |    try child.spawn();
397 |    try child.collectOutput(&stdout, &stderr, args.max_output_bytes); // <- here
398 |
```
line 397;
Specifically inside the collectOutput function:
```zig
pub fn collectOutput(
    child: ChildProcess,
    stdout: *std.ArrayList(u8),
    stderr: *std.ArrayList(u8),
    max_output_bytes: usize,
) !void {
    assert(child.stdout_behavior == .Pipe); // <- here
```
On the assert

**Comment by rohlem** [comment] 2024-10-28 10:50
Might be related to https://github.com/ziglang/zig/issues/21756

**Comment by squeek502** [comment] 2024-10-29 05:40
Yep, duplicate of https://github.com/ziglang/zig/issues/21756 / https://github.com/ziglang/zig/issues/17704

**Closed by squeek502** 2024-10-29 05:40 UTC
Labels: bug
