### ISSUE TITLE
Inferred enum types produce `error: values of type '(enum literal)' must be comptime known`

### ISSUE THREAD

**Issue by hazeycode** [ziglang/zig#10294] opened 2021-12-07 13:54 UTC
### Zig Version

0.8.1

### Steps to Reproduce

not working:
```
test "char-enum mapping" {
    const Foo = enum(u8) { A, B, C, Unknown };

    const val: Foo = if (std.meta.intToEnum(
        enum(u8) {
            a = 'a',
            b = 'b',
            c = 'c',
        },
        'x',
    )) |e| switch (e) {
        .a => .A,
        .b => .B,
        .c => .C,
    } else |_| .Unknown;

    try std.testing.expectEqual(Foo.Unknown, val);
}
```

working:
```
test "char-enum mapping" {
    const Foo = enum(u8) { A, B, C, Unknown };

    const val: Foo = if (std.meta.intToEnum(
        enum(u8) {
            a = 'a',
            b = 'b',
            c = 'c',
        },
        'x',
    )) |e| switch (e) {
        .a => Foo.A,
        .b => Foo.B,
        .c => Foo.C,
    } else |_| Foo.Unknown;

    try std.testing.expectEqual(Foo.Unknown, val);
}
```

### Expected Behavior

I wouldn't expect to have to specify the enum type in each switch case here. It should be inferred from the type of `val`.

### Actual Behavior

produces a confusing compiler error `error: values of type '(enum literal)' must be comptime known`

**Comment by Vexu** [comment] 2021-12-07 14:31
Duplicate of #3750 etc. Fixed in stage2.

**Closed by Vexu** 2021-12-07 14:31 UTC
Labels: bug
