### ISSUE TITLE
zig build -Drelease-small=true

### ISSUE THREAD

**Issue by hwoy** [ziglang/zig#14192] opened 2023-01-04 10:29 UTC
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior
```
$ zig init-exe
$ zig build -Drelease-small=true
error: FileNotFound
C:\Coding\zig\lib\std\os\windows.zig:126:35: 0x7ff7a3ce2809 in OpenFile (build.exe.obj)
        .OBJECT_NAME_NOT_FOUND => return error.FileNotFound,
                                  ^
C:\Coding\zig\lib\std\fs.zig:1224:23: 0x7ff7a3ce5eb3 in openFileW (build.exe.obj)
            .handle = try w.OpenFile(sub_path_w, .{
                      ^
C:\Coding\zig\lib\std\fs.zig:1096:13: 0x7ff7a3cc324e in openFile (build.exe.obj)
            return self.openFileW(path_w.span(), flags);
            ^
C:\Coding\zig\lib\std\fs.zig:2532:24: 0x7ff7a3d46392 in updateFile (build.exe.obj)
        var src_file = try source_dir.openFile(source_path, .{});
                       ^
C:\Coding\zig\lib\std\build.zig:1089:29: 0x7ff7a3d5b14d in updateFile (build.exe.obj)
        const prev_status = try fs.Dir.updateFile(cwd, source_path, cwd, dest_path, .{});
                            ^
C:\Coding\zig\lib\std\build.zig:3427:13: 0x7ff7a3d3d448 in make (build.exe.obj)
            try builder.updateFile(self.artifact.getOutputPdbSource().getPath(builder), full_pdb_path);
            ^
C:\Coding\zig\lib\std\build.zig:3649:9: 0x7ff7a3cae449 in make (build.exe.obj)
        try self.makeFn(self);
        ^
C:\Coding\zig\lib\std\build.zig:509:9: 0x7ff7a3c9c76c in makeOneStep (build.exe.obj)
        try s.make();
        ^
C:\Coding\zig\lib\std\build.zig:503:17: 0x7ff7a3c9c6e5 in makeOneStep (build.exe.obj)
                return err;
                ^
C:\Coding\zig\lib\std\build.zig:464:13: 0x7ff7a3c9c438 in make (build.exe.obj)
            try self.makeOneStep(s);
            ^
C:\Coding\zig\lib\build_runner.zig:223:21: 0x7ff7a3c9f3aa in main (build.exe.obj)
            else => return err,
                    ^
error: the following build command failed with exit code 1:
C:\Users\Hwoy\Desktop\zig_cache\o\c83704c33d69c2b3f7d34e2caa61252d\build.exe C:\Coding\zig\zig.exe C:\Users\Hwoy\Desktop\voy C:\Users\Hwoy\Desktop\zig_cache C:\Users\Hwoy\Desktop\zig_cache -Drelease-small=true

```
### Expected Behavior

Should be build properly without any issue

**Comment by hwoy** [comment] 2023-01-05 02:13
Code generated by zig init-exe

zig init-exe
zig build -Drelease-small=true

==================================
Let me guess this is a bug in library(package) used by build.zig

zig version 0.10.0 x86_64 windows
zig build -Drelease-small=true -> Not succcess
zig build -Drelease-fast=true -> Succcess
zig build -Drelease-safe=true -> Succcess

**Comment by Ristovski** [comment] 2023-01-05 13:25
Duplicate of https://github.com/ziglang/zig/issues/13405, also Windows-only

**Closed** 2023-01-05 15:39 UTC
Labels: bug
