### ISSUE TITLE
Zig 0.9.1 fails to build test suite

### ISSUE THREAD

**Issue by hazeycode** [ziglang/zig#10450] opened 2021-12-30 01:26 UTC
### Zig Version

0.9.1

### Steps to Reproduce

`zig build test` iguanaTLS. See https://github.com/alexnask/iguanaTLS/pull/29

### Expected Behavior

the test suite compiles

### Actual Behavior

compilation fails
```
❯ zig build test
Code Generation [1798/2200] crypto.ecc.muladd_small... broken LLVM module found: Call parameter type does not match function signature!
  %229 = getelementptr inbounds { %"?[]const u8", i16 }, { %"?[]const u8", i16 }* %0, i32 0, i32 0, !dbg !38311
 %"?[]align(8) u8"*  call fastcc void @std.mem.Allocator.resize.431(%"?[]const u8"* sret(%"?[]align(8) u8") %229, %std.mem.Allocator* %2, %"[]u8"* %23, i64 %227), !dbg !38311

This is a bug in the Zig compiler.thread 116721 panic: 
???:?:?: 0x5629d097f337 in ??? (???)
???:?:?: 0x5629d18a17bb in ??? (???)
???:?:?: 0x5629d18c86a2 in ??? (???)
???:?:?: 0x5629d18cd7cd in ??? (???)
???:?:?: 0x5629d189d48f in ??? (???)
???:?:?: 0x5629d0d71884 in ??? (???)
???:?:?: 0x5629d0d3374a in ??? (???)
???:?:?: 0x5629d0b16135 in ??? (???)
???:?:?: 0x5629d0b09362 in ??? (???)
???:?:?: 0x5629d0b04f01 in ??? (???)
???:?:?: 0x5629d0a93b7f in ??? (???)
???:?:?: 0x5629d09adb8d in ??? (???)
???:?:?: 0x5629d097db76 in ??? (???)
???:?:?: 0x5629d097d309 in ??? (???)
???:?:?: 0x7f18ae251b24 in ??? (???)
```

update: issue persists from Zig 0.9.0 to 0.9.1

**Comment by jedisct1** [comment] 2022-11-07 22:23
Does that still happen on Zig 0.10.0, especially with stage2?

**Comment by Vexu** [comment] 2023-01-16 14:18
Duplicate of #6147

**Closed by Vexu** 2023-01-16 14:18 UTC
Labels: bug, stage1
