### ISSUE TITLE
Compiler segfault with `orelse` in anonymous struct literal

### ISSUE THREAD

**Issue by git-bruh** [ziglang/zig#11205] opened 2022-03-17 18:06 UTC
### Zig Version

0.9.1

### Steps to Reproduce

```zig
pub fn main() !void {
    var a: ?i32 = null;
    var b: ?i32 = 1;

    const s = .{a orelse b};
    _ = s;
}
```

### Expected Behavior

A successful build

### Actual Behavior

```
broken LLVM module found: Instruction does not dominate all uses!
  %6 = getelementptr inbounds %"struct:5:16", %"struct:5:16"* %s, i32 0, i32 0, !dbg !17154
  %11 = getelementptr inbounds %"?i32", %"?i32"* %6, i32 0, i32 1, !dbg !17153
Instruction does not dominate all uses!
  %6 = getelementptr inbounds %"struct:5:16", %"struct:5:16"* %s, i32 0, i32 0, !dbg !17154
  %12 = getelementptr inbounds %"?i32", %"?i32"* %6, i32 0, i32 0, !dbg !17153

This is a bug in the Zig compiler.thread 17670 panic:
Unable to dump stack trace: debug info stripped
Aborted
```

**Comment by Vexu** [comment] 2023-01-13 17:36
Duplicate of #3882

**Closed by Vexu** 2023-01-13 17:36 UTC
Labels: bug, stage1
