### ISSUE TITLE
Segfault when embedding cImport struct in a zig struct

### ISSUE THREAD

**Issue by mil** [ziglang/zig#8122] opened 2021-03-02 02:37 UTC
Running into a strange segfault when using @cImport:

Create `sample.h` in a folder:
```c
typedef struct somecstruct {
    usize foo;
} somecstruct;
```
And then create `foo.zig` as:
```zig
const std = @import("std");
const sample = @cImport({
    @cInclude("sample.h");
});

pub const Foo = struct { 
  Bar: sample.somecstruct
};

pub fn main() !void {
    var d = @intCast(usize, 37);
    std.debug.warn("Converted {}\n", .{d});
    var x = .{ .Bar = .{ .foo = d } };
}
```

Run with:
```sh
zig run -lc foo.zig -I./
```

Produces:
```
> zig run -lc foo.zig -I./
Converted 37
Segmentation fault at address 0x201d90
/home/m/foo.zig:13:33: 0x203ce2 in main (foo)
    var x = .{ .Bar = .{ .foo = d } };
                                ^
/usr/lib/zig/std/start.zig:345:37: 0x204031 in std.start.main (foo)
            const result = root.main() catch |err| {
                                    ^
zsh: abort      zig run -lc foo.zig -I./
```

Tested on musl / Alpine linux with zig version:
```
> zig version
0.8.0-dev.1343+3c0238e73
```

**Comment by Vexu** [comment] 2021-03-02 07:42
Duplicate of  #3915.

Adding a type to `x` makes this work just fine:
```zig
pub const Foo = struct { 
  Bar: sample.somecstruct
};

pub fn main() !void {
    var d = @intCast(usize, 37);
    std.debug.warn("Converted {}\n", .{d});
    var x: Foo = .{ .Bar = .{ .foo = d } };
}
```

**Closed by Vexu** 2021-03-02 07:42 UTC
