### ISSUE TITLE
Error traces can get filled with irrelevant entries

### ISSUE THREAD

**Issue by Aransentin** [ziglang/zig#5753] opened 2020-06-30 09:22 UTC
Consider the following program:

```const std = @import("std");
pub fn main() !void {
    var addrlist = try std.net.getAddressList(std.heap.page_allocator, "google.com", 80);
    addrlist.deinit();
    return error.Foobar;
}
```
When `getAddressList` returns on my computer, it'll have hit 9 errors. For example, it first check whether the string is valid IP address, and only does a DNS lookup if not. These "errors" are however still stored in the error return trace, and sticks around forever even after the function returns successfully and `deinit` is called: [Return Trace](https://gist.github.com/Aransentin/881855fd01b37828695b2f97c2f11a4c).

Larger software that (for example) does a lot of DNS lookups will after a while accrue really large mostly irrelevant return traces due to this.

**Comment by daurnimator** [comment] 2020-06-30 09:34
Duplicate of #1923

**Closed by daurnimator** 2020-06-30 09:34 UTC
