### ISSUE TITLE
`@memcpy(many_ptr, "hey")` causes segfault in  codegen

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#15689] opened 2023-05-13 14:43 UTC
### Zig Version

0.11.0-dev.3106+3062f9b02 

### Steps to Reproduce and Observed Behavior

Still trying to narrow this one down to a minimal reproduction (currently waiting for Zig debug build to compile so that a more useful stack trace can be produced)

But it starts in [this commit of bun](https://github.com/oven-sh/bun/commit/b702997c48849de61a82b6e50877094aa153a318) using zig version `0.11.0-dev.2571+31738de28` (pre memset). The immediate commit before it does not reproduce the segfault (as seen in https://github.com/oven-sh/bun/commit/1bcd168dadd28adddcb4eea41b458349f7139d6c). I upgraded to a more recent build of Zig in [52e9ba303254920d157b39e35e87ee0369fae492](https://github.com/oven-sh/bun/commit/52e9ba303254920d157b39e35e87ee0369fae492)

```zig
❯ zig build
Build darwin-aarch64 v11 - v13.2.1 (apple_m1)
Output: /Users/jarred/Code/bun/packages/debug-bun-darwin-aarch64/bun-debug

zig build-obj bun-debug Debug native-native.11: error: the following command terminated unexpectedly:
/Users/jarred/zig/0.11.0-dev.3106+3062f9b02/files/zig build-obj /Users/jarred/Code/bun/root.zig -lc -femit-bin=/Users/jarred/Code/bun/packages/debug-bun-darwin-aarch64/bun-debug.o -fno-strip --cache-dir /Users/jarred/Code/bun/zig-cache --global-cache-dir /Users/jarred/.cache/zig --name bun-debug -fno-compiler-rt -fno-omit-frame-pointer -target native-native.11 -mcpu apple_m1 --mod build_options::/Users/jarred/Code/bun/zig-cache/c/ab5a81b4558c3558d5e34a40cc540b17/options.zig --mod async_io::/Users/jarred/Code/bun/src/io/io_darwin.zig --deps async_io,build_options -I /Users/jarred/Code/bun/src/deps -I /Users/jarred/Code/bun/src/deps --main-pkg-path /Users/jarred/Code/bun --listen=- 
Build Summary: 1/4 steps succeeded; 1 failed (disable with -fno-summary)
install transitive failure
└─ obj transitive failure
   └─ zig build-obj bun-debug Debug native-native.11 failure
      └─ options cached
error: the following build command failed with exit code 1:
/Users/jarred/Code/bun/zig-cache/o/5e7f024849805608476af6dce9573b44/build /Users/jarred/zig/0.11.0-dev.3106+3062f9b02/files/zig /Users/jarred/Code/bun /Users/jarred/Code/bun/zig-cache /Users/jarred/.cache/zig
```

### Expected Behavior

No compiler segfault, probably a compiler error for some code that is wrong

**Comment by Jarred-Sumner** [comment] 2023-05-13 14:51
Here is a stack trace:
```c
codegen_llvm_FuncGen_sliceOrArrayLenInBytes__111280 (zig2.c:1520595)
codegen_llvm_FuncGen_airMemcpy__111380 (zig2.c:1072529)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087632)
codegen_llvm_FuncGen_airSwitchBr__111274 (zig2.c:1061398)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087069)
codegen_llvm_FuncGen_airBlock__111268 (zig2.c:1060586)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087041)
codegen_llvm_FuncGen_airCondBr__111270 (zig2.c:1061925)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087129)
codegen_llvm_FuncGen_airBlock__111268 (zig2.c:1060586)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087041)
codegen_llvm_FuncGen_airLoop__111275 (zig2.c:1064059)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087273)
codegen_llvm_FuncGen_airBlock__111268 (zig2.c:1060586)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087041)
codegen_llvm_FuncGen_airCondBr__111270 (zig2.c:1061925)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087129)
codegen_llvm_FuncGen_airBlock__111268 (zig2.c:1060586)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087041)
codegen_llvm_FuncGen_airSwitchBr__111274 (zig2.c:1061451)
codegen_llvm_FuncGen_genBody__111256 (zig2.c:1087069)
codegen_llvm_Object_updateFunc__21751 (zig2.c:745276)
link_MachO_updateFunc__5437 (zig2.c:745783)
link_File_updateFunc__5297 (zig2.c:750198)
Module_ensureFuncBodyAnalyzed__15387 (zig2.c:548160)
Compilation_processOneJob__5215 (zig2.c:422005)
Compilation_performAllTheWork__5214 (zig2.c:423084)
Compilation_update__5199 (zig2.c:310441)
main_updateModule__212 (zig2.c:319697)
main_buildOutputType__204 (zig2.c:338177)
main_mainArgs__193 (zig2.c:262421)
main_main__191 (zig2.c:261425)
main (zig2.c:261498)
start (@start:639)
```

I was unable to compile the stage3 build of zig on master. I think it is not working right now. `docgen` crashed about 30 times according to Console.app

**Comment by Jarred-Sumner** [comment] 2023-05-13 14:54
The crash is here: https://github.com/ziglang/zig/blob/46527292178d64daa9f81be3eef378d78d254b5d/src/codegen/llvm.zig#L5807

A minimal reproduction - looks like the previous syntax for `@memcpy` causes the segfault
```zig
pub extern var memcpy_ptr: [*]u8;

test {
    @memcpy(memcpy_ptr, "hey");
}
```

**Comment by Vexu** [comment] 2023-05-13 15:53
Duplicate of #15513

**Closed by Vexu** 2023-05-13 15:53 UTC
Labels: bug
