### ISSUE TITLE
figuring out where to put @setEvalBranchQuota is not intuitive

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#1767] opened 2018-11-21 19:05 UTC
This small test case fails to compile:
```zig
test "" {
    switch (1) {
        case() => {},
        else => {},
    }
}

fn case() usize {
    for ([_]void{{}} ** 1004) |_| {} // error: evaluation exceeded 1000 backwards branches
    return 1;
}
```

But I have no way to easily extend the eval quota. This won't work:
```zig
test "" {
    switch (1) {
        case() => {},
        else => {},
    }
}

fn case() usize {
    comptime {
        @setEvalBranchQuota(10000); // error: @setEvalBranchQuota must be called from the top of the comptime stack
        for ([_]void{{}} ** 1004) |_| {}
        return 1;
    }
}
```

This is the only way to do this:
```zig
test "" {
    switch (1) {
        comptime blk: {@setEvalBranchQuota(10000); break :blk case();} => {},
        else => {},
    }
}


fn case() usize {
    for ([]void{{}} ** 1004) |_| {}
    return 1;
}
```

But this kinda defeats the purpose of the `case` function.

**Comment by andrewrk** [comment] 2018-11-21 19:31
What about this?

```zig
test "" {
    @setEvalBranchQuota(2000);
    switch (1) {
        case() => {},
        else => {},
    }
}

fn case() usize {
    for ([]void{{}} ** 1004) |_| {} // error: evaluation exceeded 1000 backwards branches
    return 1;
}
```

**Comment by Hejsil** [comment] 2018-11-21 19:40
@andrewrk Ooh, is this possible? Thought it had to be at the top of the comptime scope.

**Comment by andrewrk** [comment] 2018-11-21 20:10
Yep, it passes for me. Sounds like we need to figure out how to communicate this more clearly, perhaps in the error message. It makes sense semantically when you consider how everything works, but if even Jimmi Holst Christensen ends up filing an issue rather than figuring out how to make it work, then it's far from intuitive!

**Comment by Hejsil** [comment] 2018-11-22 06:34
How about global scope? I guess a block is required here.

**Comment by Hejsil** [comment] 2019-02-12 08:03
If I make the loop `inline` the code fails.
```zig
test "" {
    @setEvalBranchQuota(2000);
    switch (1) {
        case() => {},
        else => {},
    }
}

fn case() usize {
    // error: evaluation exceeded 1000 backwards branches
    inline for ([]void{{}} ** 1004) |_| {}
    return 1;
}
```

**Comment by andrewrk** [comment] 2019-08-19 20:39
The `This won't work:` code now works. So I think this issue can be closed.

As for the last example, it's a duplicate of #1719. I want to solve it, but it's a nontrivial change.

**Closed by andrewrk** 2019-08-19 20:39 UTC
