### ISSUE TITLE
Zig fmt does not fix whitespace on one side of an operator

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#11384] opened 2022-04-05 00:45 UTC
### Zig Version

0.10.0-dev.1558+2af69710a

### Steps to Reproduce

Try to run `zig fmt` on the following code:
```zig
pub fn main() void {
    a+ b;
}
```

### Expected Behavior

The code should be reformatted to:
```zig
pub fn main() void{
    a + b;
}
```

### Actual Behavior

```
<stdin>:2:6: error: binary operator `+` has whitespace on one side, but not the other.
    a+ b;
     ^
```

Probably caused by the implementation of #7399. Ideally this would be a compile error, but not a syntax error.

**Comment by Vexu** [comment] 2022-04-05 05:54
Duplicate of #11261.

**Closed by Vexu** 2022-04-05 05:54 UTC
Labels: bug

**Comment by jibal** [comment] 2022-04-14 23:59
This is intended behavior: https://github.com/ziglang/zig/issues/7399#issuecomment-743537724
