### ISSUE TITLE
profiler/debugger integration broken

### ISSUE THREAD

**Issue by erplsf** [ziglang/zig#12671] opened 2022-08-29 10:02 UTC
### Zig Version

0f27836c218ee84f5fb7d4c47dd93a920663c037

### Steps to Reproduce

1. Create a sample file:
```
const std = @import("std");

pub fn main() void {
    std.log.info("All your bases belongs to us.", .{});
}
```
2. Compile it: `zig build-exe ./sample.zig`
3. Run it with valgrind/callgrind: `valgrind --tool=callgrind ./sample`
4. Run kcachegrind, and observe that there are no function names present, only memory addresses:
![2022-08-29_11:55:48](https://user-images.githubusercontent.com/4072364/187176815-33b2f041-f239-422d-94a9-7bcf441d8a86.png)
![2022-08-29_11:56:19](https://user-images.githubusercontent.com/4072364/187176824-f4151637-fa72-4179-add0-a9b4af899c70.png)

### Expected Behavior

I expected to be able to see actual function names and all the other stuff, for example, sample C file compiled with zig works:
1. Create a sample C file:
```
#include <stdio.h>

int main() {
   printf("All your bases belongs to us.\n");
   return 0;
}
```
2. Compile it: `zig cc -Og -dwarf-4 main.c` (added debug option and the same dwarf version for honest comparison)
3. Run valgrind: `valgrind --tool=callgrind ./a.out`
4. Observe expected behaviour:
![2022-08-29_12:01:31](https://user-images.githubusercontent.com/4072364/187176722-a574b83e-7ebe-4294-ba0e-fdf9232769fc.png)
![2022-08-29_12:01:34](https://user-images.githubusercontent.com/4072364/187176733-a094c293-8033-4899-ba5d-e7a924672b0a.png)

### Actual Behavior

Profiling/debugging information is incomplete/missing.
Both files contain the dwarf information, and have debugging symbols embedded:
![2022-08-29_12:04:17](https://user-images.githubusercontent.com/4072364/187177477-fda075cf-5644-4793-b4f5-b2278a597841.png)
![2022-08-29_12:04:24](https://user-images.githubusercontent.com/4072364/187177481-1df328ea-6ed7-455e-b484-c3105a59075b.png)
![2022-08-29_12:04:52](https://user-images.githubusercontent.com/4072364/187177482-01bbc09d-93f5-47ae-985c-b32a33703d94.png)
![2022-08-29_12:05:04](https://user-images.githubusercontent.com/4072364/187177484-c44e19f0-3b4f-4f3f-979d-d4b5303557aa.png)

Valgrind version used: `valgrind-3.19.0`

**Comment by Vexu** [comment] 2022-08-30 11:52
Likely duplicate of #12257

**Closed by Vexu** 2022-08-30 11:52 UTC
Labels: bug
