### ISSUE TITLE
`zig libc` crashes on macos

### ISSUE THREAD

**Issue by pfgithub** [ziglang/zig#16300] opened 2023-07-02 15:01 UTC
### Zig Version

0.11.0-dev.3905+309aacfc8 / Darwin 21.2.0 x86_64 i386

### Steps to Reproduce and Observed Behavior

```
$> zig libc
thread 2311584 panic: Darwin is handled separately via std.zig.system.darwin module
Unable to dump stack trace: debug info stripped
fish: Job 1, 'zig libc' terminated by signal SIGABRT (Abort)
```

### Expected Behavior

```
$> zig libc
... libc.txt is outputted
```

**Comment by kubkon** [comment] 2023-07-02 18:15
Duplicate of https://github.com/ziglang/zig/issues/15024

**Closed by kubkon** 2023-07-02 18:15 UTC
Labels: bug
