### ISSUE TITLE
failing assert(a | b & b == a | (b & b))

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4051] opened 2020-01-03 00:53 UTC
test "binary masking" {
        const a: u32 = 1;
        const b: u32 = 0;
        assert(a | b & b == a | (b & b));
    }

    const assert = @import("std").debug.assert;

targets linux aarch64, x64 and freestanding armv6m

zig version
0.5.0+a90fa45ae

**Comment by tiehuis** [comment] 2020-01-03 02:47
Duplicate of #1902.

**Closed by tiehuis** 2020-01-03 02:47 UTC
