### ISSUE TITLE
Defining large arrays cause compile issues

### ISSUE THREAD

**Issue by sagehane** [ziglang/zig#16791] opened 2023-08-12 15:09 UTC
### Zig Version

0.12.0-dev.66+5e0107fbc

### Steps to Reproduce and Observed Behavior
All of this was reproduced on x86_64-linux.

---

Run the following code in debug mode:
```zig
pub fn main() void {
    // Changing this to a `const` fixes the compile error.
    var array: [1 << 24]u8 = undefined;
    _ = array;
}
```

Output:
```sh-session
$ zig run test.zig 
Segmentation fault (core dumped)
```

---

To break other release modes, one can make the array bigger and perform array multiplication:
```zig
pub fn main() void {
    // `const` won't save you here.
    const array = [1]u8{undefined} ** (1 << 32);
    _ = array;
}
```

Output:
```sh-session
$ zig run -O ReleaseFast test.zig
LLVM Emit Object... Terminated
```

### Expected Behavior

The code shouldn't cause a segfault and the compilation shouldn't terminate. At worst, it should cause a compile error indicative of the issue.

**Comment by nektro** [comment] 2023-08-12 17:32
duplicate of https://github.com/ziglang/zig/issues/9906

**Closed** 2023-11-29 11:09 UTC
Labels: bug
