### ISSUE TITLE
zig fmt: expression not on same line not properly indented

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#13364] opened 2022-10-30 22:12 UTC
### Zig Version

0.10.0-dev.4544+0ae60f723

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() void {
    const a =
        if (true)
        'a'
    else
        'b';

    const b =
        if (true)
    {} else {};

    const c =
        switch (true) {
        true => {},
        false => {},
    };

    x() catch
    // this is not reachable
        unreachable;

    _ = a;
    _ = b;
    _ = c;
}

fn x() !void {}
```
```shell
$ zig fmt
$ # code is not pretty
```

### Expected Behavior

Something like this:
```zig
pub fn main() void {
    const a =
        if (true)
            'a'
        else
            'b';

    const b =
        if (true)
        {} else {};

    const c =
        switch (true) {
            true => {},
            false => {},
        };

    x() catch
        // this is not reachable
        unreachable;

    _ = a;
    _ = b;
    _ = c;
}

fn x() !void {}
```

So basically there are two ways for e.g. short `if`s whose result is immediately assigned:
```zig
    const a =
        if (true)
            'a'
        else
            'b';
```
and
```zig
    const a = if (true)
        'a'
    else
        'b';
```
where the latter is probably more common, but sometimes I still feel like the former is a bit prettier, and I think especially people from functional languages will often choose the former so it'd be nice if we could have that look nice.

Also, I suspect this might be a duplicate but I couldn't find a similar issue.

**Comment by ifreund** [comment] 2022-10-30 22:23
> Also, I suspect this might be a duplicate but I couldn't find a similar issue.

Indeed, this is a duplicate of #7363. All of these examples have the same root cause that is non-trivial to fix with the current architecture of zig fmt.

**Closed by ifreund** 2022-10-30 22:23 UTC
Labels: bug
