### ISSUE TITLE
Bug: using structs with default initialized comptime members causes error if field left uninitialized

### ISSUE THREAD

**Issue by kenjpirkle** [ziglang/zig#5698] opened 2020-06-24 17:45 UTC
```
pub const Foo = struct {
    comptime bar: u32 = 0,
};

pub fn main() anyerror!void {
    const foo: Foo = .{};
}
```

**Comment by Vexu** [comment] 2020-06-24 18:07
Duplicate of #5497

**Closed by Vexu** 2020-06-24 18:07 UTC
