### ISSUE TITLE
Crash when using ArrayList init with ArenaAllocator

### ISSUE THREAD

**Issue by QiBaobin** [ziglang/zig#20123] opened 2024-05-30 07:18 UTC
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

A simple project has the code to reproduce: https://github.com/QiBaobin/team-tracer/tree/arena-crash
`zig build run` got below crash:

```
thread 3049520 panic: start index 16 is larger than end index 0
~/Library/Caches/hermit/pkg/zig-0.12.0/lib/std/heap/arena_allocator.zig:187:42: 0x10948f5a3 in alloc (which-team)
            const cur_buf = cur_alloc_buf[@sizeOf(BufNode)..];
                                         ^
~/Library/Caches/hermit/pkg/zig-0.12.0/lib/std/mem/Allocator.zig:86:29: 0x109497c9b in allocBytesWithAlignment__anon_7750 (which-team)
    return self.vtable.alloc(self.ptr, len, ptr_align, ret_addr);
                            ^
~/Library/Caches/hermit/pkg/zig-0.12.0/lib/std/mem/Allocator.zig:211:40: 0x1094f665b in allocWithSizeAndAlignment__anon_9025 (which-team)
    return self.allocBytesWithAlignment(alignment, byte_count, return_address);
                                       ^
~/Library/Caches/hermit/pkg/zig-0.12.0/lib/std/mem/Allocator.zig:205:75: 0x1094e2e09 in alignedAlloc__anon_8915 (which-team)
    const ptr: [*]align(a) T = @ptrCast(try self.allocWithSizeAndAlignment(@sizeOf(T), a, n, return_address));
                                                                          ^
~/Library/Caches/hermit/pkg/zig-0.12.0/lib/std/array_list.zig:457:67: 0x1094bf173 in ensureTotalCapacityPrecise (which-team)
                const new_memory = try self.allocator.alignedAlloc(T, alignment, new_capacity);
                                                                  ^
~/Library/Caches/hermit/pkg/zig-0.12.0/lib/std/array_list.zig:434:51: 0x1094ad71e in ensureTotalCapacity (which-team)
            return self.ensureTotalCapacityPrecise(better_capacity);
                                                  ^
~/Library/Caches/hermit/pkg/zig-0.12.0/lib/std/array_list.zig:483:41: 0x1094907db in addOne (which-team)
            try self.ensureTotalCapacity(newlen);
                                        ^
~/Library/Caches/hermit/pkg/zig-0.12.0/lib/std/array_list.zig:262:49: 0x10946218a in append (which-team)
            const new_item_ptr = try self.addOne();
                                                ^
~/code/which-team/src/main.zig:70:37: 0x10945ca44 in refresh (which-team)
                team.packages.append(line) catch break;
                                    ^
~/code/which-team/src/main.zig:51:21: 0x10945bbd3 in init (which-team)
        self.refresh();
                    ^
~/code/which-team/src/main.zig:122:31: 0x10945b678 in main (which-team)
    var handler = Handler.init(allocator);
                              ^
~/Library/Caches/hermit/pkg/zig-0.12.0/lib/std/start.zig:511:37: 0x10945cffb in main (which-team)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7ff8101e9365 in ??? (???)
Unwind information for `???:0x7ff8101e9365` was not available, trace may be incomplete

???:?:?: 0x0 in ??? (???)
run
+- run which-team failure
error: the following command terminated unexpectedly:
~/code/which-team/zig-out/bin/which-team 
Build Summary: 7/9 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
+- run which-team failure
error: the following build command failed with exit code 1:
~/code/which-team/zig-cache/o/a67cc5d7ed36fe1907c379d7b6e2fbe2/build ~/Library/Caches/hermit/pkg/zig-0.12.0/zig ~/code/which-team ~/code/which-team/zig-cache ~/.cache/zig --seed 0xd42eb04 -Zd2ceb7f112432f20 run

```

### Expected Behavior

Run without issue

**Comment by Vexu** [comment] 2024-05-30 07:26
You are returning a pointer to a stack variable https://github.com/QiBaobin/team-tracer/blob/7f462d7329b5a0e03cb1c470df6a26b392eb5851/src/main.zig#L15-L18

Duplicate of https://github.com/ziglang/zig/issues/19320#issuecomment-2000439944

**Closed by Vexu** 2024-05-30 07:26 UTC
Labels: bug
