### ISSUE TITLE
Compiler segfault on code with empty error union

### ISSUE THREAD

**Issue by saltzm** [ziglang/zig#17849] opened 2023-11-03 19:17 UTC
### Zig Version

0.12.0-dev.1388+d89266569

### Steps to Reproduce and Observed Behavior

The compiler segfaults when compiling the following code: 

```zig
const std: type = @import("std");
// If I change this to 
// const Error = error{Foo};
// It doesn't crash.
const Error = error{};
const Status = struct {
    val: union(enum) {
        success,
        err: Error,
    },

    fn check(self: @This()) Error!void {
        switch (self.val) {
            .success => {},
            .err => |e| return e,
        }
    }
};

fn runTest() !void {
    const status: Status = .{ .val = .success };
    try status.check();
}

pub fn main() !void {
    try runTest();
}
```

[Godbolt with failing example](https://godbolt.org/z/zzcjv11oM)

This may be a silly thing to do, but the compiler should not segfault.

### Expected Behavior

The compiler shouldn't segfault. If it's meant to be disallowed to use an empty error union, it should return a compiler error instead.

**Comment by saltzm** [comment] 2023-11-03 19:17
I just checked and it also segfaults on version 0.10.0 but not on version 0.9.0

**Comment by rohlem** [comment] 2023-11-04 15:17
The usage scenario is valid, `error{}` is a `noreturn`-like type, which is a type the compiler may assume will never have a value instantiated. See also https://github.com/ziglang/zig/issues/15909 .

**Comment by Vexu** [comment] 2023-11-04 15:42
Duplicate of #13807

**Closed by Vexu** 2023-11-04 15:42 UTC
Labels: bug
