### ISSUE TITLE
Compiler segfault in `Module.CaptureScope.failed` due to undefined memory access

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#14113] opened 2022-12-29 09:31 UTC
### Zig Version

34887cf136878c87357fa0eec52a12db300d8f27

### Steps to Reproduce and Observed Behavior

Call stack:
```zig
Module.CaptureScope.failed (/Users/jarred/Build/zig-latest4/src/Module.zig:369)
Sema.zirClosureGet (/Users/jarred/Build/zig-latest4/src/Sema.zig:15158)
Sema.analyzeBodyInner (/Users/jarred/Build/zig-latest4/src/Sema.zig:919)
Sema.analyzeBodyBreak (/Users/jarred/Build/zig-latest4/src/Sema.zig:817)
Sema.resolveBody (/Users/jarred/Build/zig-latest4/src/Sema.zig:767)
Sema.zirTypeofBuiltin (/Users/jarred/Build/zig-latest4/src/Sema.zig:16215)
Sema.analyzeBodyInner (/Users/jarred/Build/zig-latest4/src/Sema.zig:994)
Sema.analyzeBodyBreak (/Users/jarred/Build/zig-latest4/src/Sema.zig:817)
Module.semaDecl (/Users/jarred/Build/zig-latest4/src/Module.zig:4670)
Module.ensureDeclAnalyzed (/Users/jarred/Build/zig-latest4/src/Module.zig:4291)
```

<img width="774" alt="image" src="https://user-images.githubusercontent.com/709451/209930911-e66022d6-69c1-40a7-87ae-2ec21473a07e.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/709451/209930930-daaf3207-e98e-4e44-a9eb-416e33e1182a.png">

After the following diff, the segfault above becomes a panic due to incorrect alignment:

Before:
```zig
 pub fn hash_(
            this: *@This(),
            globalThis: *JSGlobalObject,
            input: JSC.Node.StringOrBuffer,
            output: ?JSC.Node.StringOrBuffer,
        ) JSC.JSValue {
```

After:
```zig
 pub fn hash_(
            globalThis: *JSGlobalObject,
            algorithm: ZigString,
            input: JSC.Node.StringOrBuffer,
            output: ?JSC.Node.StringOrBuffer,
        ) JSC.JSValue {
```

The function where this error happens is defined here: https://github.com/oven-sh/bun/blob/main/src/bun.js/base.zig#L2623-L2807

The panic trace:

```zig
Process exited with code 9.
Console is in 'commands' mode, prefix expressions with '?'.
Launching: /Users/jarred/Build/zig-latest4/build/stage3/bin/zig build-obj -fLLVM /Users/jarred/Code/bun/root.zig -lc -fno-strip --cache-dir /Users/jarred/Code/bun/zig-cache --global-cache-dir /Users/jarred/.cache/zig --name bun-debug -fcompiler-rt -fno-omit-frame-pointer -target native-native.11 -mcpu apple_m1 --pkg-begin async_io /Users/jarred/Code/bun/src/io/io_darwin.zig --pkg-end --pkg-begin bun /Users/jarred/Code/bun/src/bun_redirect.zig --pkg-end --pkg-begin compiler_rt /Users/jarred/zig/0.11.0-dev.971+19056cb68/files/lib/compiler_rt.zig --pkg-end --pkg-begin build_options /Users/jarred/Code/bun/zig-cache/options/LmEeZ1uLeNO7rzsK_SbFmz0XMA1rEiSVjkKKYnl2Yv9X1bRtDTn35zk9SmIImEky --pkg-end -I /Users/jarred/Code/bun/src/deps -I /Users/jarred/Code/bun/src/deps --main-pkg-path /Users/jarred/Code/bun --enable-cache
Launched process 74736
Semantic Analysis [2622] boring... [35D[0KSemantic Analysis [2705] initFull... [37D[0KSemantic Analysis [2892] fromAPI... [36D[0KSemantic Analysis [3049] instance... [37D[0KSemantic Analysis [3105] string... [35D[0KSemantic Analysis [3160] loadDefines... [40D[0KSemantic Analysis [3305] scanIdentifierWithEscapes... [54D[0KSemantic Analysis [3364] getOrPutAssumeCapacity... [51D[0KSemantic Analysis [3427] RESET... [34D[0KSemantic Analysis [3434] GenerateNodeModuleBundle... [53D[0KSemantic Analysis [3649] Field... [34D[0KSemantic Analysis [3756] std... [32D[0KSemantic Analysis [4027] BuildCommand... [41D[0KSemantic Analysis [4101] Environment... [40D[0KSemantic Analysis [4199] toOwnedSlice... [41D[0KSemantic Analysis [4206] [25D[0KSemantic Analysis [4227] print... [34D[0KSemantic Analysis [4313] init... [33D[0KSemantic Analysis [4363] append... [35D[0KSemantic Analysis [4373] init... [33D[0KSemantic Analysis [4377] init... [33D[0KSemantic Analysis [4381] Output... [35D[0KSemantic Analysis [4391] init... [33D[0KSemantic Analysis [4399] initBuf... [36D[0KSemantic Analysis [4493] isSplitByte... [40D[0KSemantic Analysis [4497] platform_specific_backend_label... [60D[0KSemantic Analysis [4633] addDefaultError... [44D[0KSemantic Analysis [4641] parseNumericLiteralOrDot... [53D[0KSemantic Analysis [4648] runParser... [38D[0KSemantic Analysis [4680] parseExpr... [38D[0KSemantic Analysis [4726] always_loads_config... [48D[0KSemantic Analysis [4854] put... [32D[0KSemantic Analysis [4868] flag... [33D[0KSemantic Analysis [4994] isPeer... [35D[0KSemantic Analysis [5016] getCacheDirectory... [46D[0KSemantic Analysis [5104] isEmpty... [36D[0KSemantic Analysis [5137] fmt... [32D[0KSemantic Analysis [5211] enqueueDependencyList... [50D[0KSemantic Analysis [5324] chmod... [34D[0KSemantic Analysis [5347] read_8bytes_swapped... [48D[0KSemantic Analysis [5349] [25D[0KSemantic Analysis [5392] writeYarnLock... [42D[0KSemantic Analysis [5452] NamesIterator... [42D[0KSemantic Analysis [5460] printStartEndStdout... [48D[0KSemantic Analysis [5461] AddCommand... [39D[0KSemantic Analysis [5540] remove_params... [42D[0KSemantic Analysis [5557] LinkCommand... [40D[0KSemantic Analysis [5572] isNPMPackageName... [45D[0KSemantic Analysis [5579] UnlinkCommand... [42D[0KSemantic Analysis [5647] TestCommand... [40D[0KSemantic Analysis [6568] __negti2... [37D[0KSemantic Analysis [6854] nextCodepoint... [42D[0KSemantic Analysis [6893] id_continue_masks... [46D[0KSemantic Analysis [6983] [25D[0KSemantic Analysis [7026] [25D[0KSemantic Analysis [7064] symbolName... [39D[0KSemantic Analysis [7085] [25D[0KSemantic Analysis [7121] [25D[0KSemantic Analysis [7161] [25D[0KSemantic Analysis [7233] [25D[0KSemantic Analysis [7271] [25D[0KSemantic Analysis [7301] VTable... [35D[0KSemantic Analysis [7366] name... [33D[0KSemantic Analysis [7464] EnumArrayExt... [41D[0KSemantic Analysis [7526] prettyWithPrinter... [46D[0KSemantic Analysis [7649] EnumArrayExt... [41D[0KSemantic Analysis [7669] toOwnedSliceLeaky... [46D[0KSemantic Analysis [7678] is_darwin... [38D[0KSemantic Analysis [7699] public_params... [42D[0KSemantic Analysis [7730] DefineColonList... [44D[0KSemantic Analysis [7900] allocate... [37D[0KSemantic Analysis [7932] save... [33D[0KSemantic Analysis [7989] usingnamespace_0... [45D[0KSemantic Analysis [8057] [25D[0KSemantic Analysis [8505] insertAllEntriesIntoNewHeaderGeneric... [65D[0KSemantic Analysis [8625] exit... [33D[0KSemantic Analysis [8676] getParent... [38D[0KSemantic Analysis [8722] cache... [34D[0KSemantic Analysis [8787] alloc... [34D[0KSemantic Analysis [8815] utf16ToString... [42D[0KSemantic Analysis [8856] json... [33D[0KSemantic Analysis [8961] isPackagePath... [42D[0KSemantic Analysis [9006] print... [34D[0KSemantic Analysis [9047] appendToModuleList... [47D[0KSemantic Analysis [9069] comptime_0... [39D[0KSemantic Analysis [9149] blockSwap... [38D[0KSemantic Analysis [9166] encode... [35D[0KSemantic Analysis [9181] FeatureFlags... [41D[0KSemantic Analysis [9272] write... [34D[0KSemantic Analysis [9351] prepareToSendBody... [46D[0KSemantic Analysis [9457] append... [35D[0KSemantic Analysis [9502] printBinding... [41D[0KSemantic Analysis [9519] getError... [37D[0KSemantic Analysis [9561] printCommonJS... [42D[0KSemantic Analysis [9606] print... [34D[0KSemantic Analysis [9651] sendInternalError... [46D[0KSemantic Analysis [9671] autoClose... [38D[0KSemantic Analysis [9709] writeAll... [37D[0KSemantic Analysis [9758] getError... [37D[0KSemantic Analysis [9800] init... [33D[0KSemantic Analysis [9844] print... [34D[0KSemantic Analysis [9889] deinit... [35D[0KSemantic Analysis [9936] init... [33D[0KSemantic Analysis [9982] getError... [37D[0KSemantic Analysis [10024] init... [34D[0KSemantic Analysis [10068] print... [35D[0KSemantic Analysis [10113] params_list... [41D[0KSemantic Analysis [10149] printExportClauseItem... [51D[0KSemantic Analysis [10169] deinit... [36D[0KSemantic Analysis [10235] default_favicon_shasum... [52D[0KSemantic Analysis [10239] isRoot... [36D[0KSemantic Analysis [10247] options... [37D[0KSemantic Analysis [10255] isFull... [36D[0KSemantic Analysis [10313] NodeBuiltinsMap... [45D[0KSemantic Analysis [10318] items... [35D[0KSemantic Analysis [10344] with... [34D[0KSemantic Analysis [10388] with... [34D[0KSemantic Analysis [10419] with... [34D[0KSemantic Analysis [10454] with... [34D[0KSemantic Analysis [10469] writeChunk... [40D[0KSemantic Analysis [10505] std... [33D[0KSemantic Analysis [10549] flag... [34D[0KSemantic Analysis [10581] utf16ToString... [43D[0KSemantic Analysis [10623] options... [37D[0KSemantic Analysis [10688] PackageJSONSort... [45D[0KSemantic Analysis [10720] toOwnedSentinelLeaky... [50D[0KSemantic Analysis [10747] countWithDifferentBuffers... [55D[0KSemantic Analysis [10799] count... [35D[0KSemantic Analysis [10805] count... [35D[0KSemantic Analysis [10808] isSet... [35D[0KSemantic Analysis [10829] sizes... [35D[0KSemantic Analysis [10879] dynamicRootDependencies... [53D[0KSemantic Analysis [10881] deinit... [36D[0KSemantic Analysis [10900] ensureTotalCapacityContext... [56D[0KSemantic Analysis [10922] fstatatZ... [38D[0KSemantic Analysis [10960] External... [38D[0KSemantic Analysis [10973] alignment_bytes_to_repeat_buffer... [62D[0KSemantic Analysis [10992] isMatch... [37D[0KSemantic Analysis [11024] printElapsedStdout... [48D[0KSemantic Analysis [11025] ensureUnusedCapacity... [50D[0KSemantic Analysis [11059] flag... [34D[0KSemantic Analysis [11079] comptime_0... [40D[0KSemantic Analysis [11224] promote... [37D[0KSemantic Analysis [11278] [26D[0KSemantic Analysis [11428] JSC__JSValue__jsBoolean... thread 985695 panic: incorrect alignment
Analyzing src/bun.js/base.zig: src/bun.js/base.zig:wrapWithHasContainer__struct_62870.FunctionType
    > %13836 = closure_get(%13835) 
      %13838 = closure_get(%13837) 
      %13839 = as_node(@Zir.Inst.Ref.const_slice_u8_type, %13838) 
      %13840 = field_val_named(%13836, %13839) 
      %13841 = break_inline(%13834, %13840)
    For full context, use the command
      zig ast-check -t src/bun.js/base.zig

  in src/bun.js/base.zig: src/bun.js/base.zig:wrapWithHasContainer__struct_62870.FunctionType
    > %13834 = typeof_builtin({%13836..%13841}) 
  in src/bun.js/base.zig: src/bun.js/base.zig:wrapWithHasContainer__struct_62870.Args
    > %13860 = decl_val("FunctionType") 
  in src/bun.js/base.zig: src/bun.js/base.zig:wrapWithHasContainer__struct_62870.Args
    > %13859 = call(.compile_time, %13857, [
        {%13860, %13861},
      ]) 
  in src/bun.js/base.zig: src/bun.js/base.zig:wrapWithHasContainer__struct_62870.callback
    > %13942 = decl_val("Args") 
  in src/bun.js/base.zig: src/bun.js/base.zig:wrapWithHasContainer__struct_62870.callback
    > %13918 = block({%13919..%15284})
/Users/jarred/Build/zig-latest4/lib/std/hash_map.zig:945:100: 0x1007284e3 in header (zig)
            return @ptrCast(*Header, @ptrCast([*]Header, @alignCast(@alignOf(Header), self.metadata.?)) - 1);
                                                                                                   [32;1m^
/Users/jarred/Build/zig-latest4/lib/std/hash_map.zig:959:31: 0x100728037 in capacity (zig)
            return self.header().capacity;
                              [32;1m^
/Users/jarred/Build/zig-latest4/lib/std/hash_map.zig:1145:39: 0x1010ef4f7 in getPtrAdapted__anon_175897 (zig)
            const mask = self.capacity() - 1;
                                      [32;1m^
/Users/jarred/Build/zig-latest4/lib/std/hash_map.zig:1244:38: 0x100dcfdbf in getPtrContext (zig)
            return self.getPtrAdapted(key, ctx);
                                     [32;1m^
/Users/jarred/Build/zig-latest4/lib/std/hash_map.zig:1241:38: 0x100a8a683 in getPtr (zig)
            return self.getPtrContext(key, undefined);
                                     [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:15166:44: 0x100671a77 in zirClosureGet (zig)
        if (scope.captures.getPtr(inst_data.inst)) |tv| {
                                           [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:919:68: 0x10043d823 in analyzeBodyInner (zig)
            .closure_get                  => try sema.zirClosureGet(block, inst),
                                                                   [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:817:45: 0x100273387 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:767:50: 0x100a7cd9f in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:16215:41: 0x1006add93 in zirTypeofBuiltin (zig)
    const operand = try sema.resolveBody(&child_block, body, inst);
                                        [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:994:71: 0x100441d37 in analyzeBodyInner (zig)
            .typeof_builtin               => try sema.zirTypeofBuiltin(block, inst),
                                                                      [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:817:45: 0x100273387 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            [32;1m^
/Users/jarred/Build/zig-latest4/src/Module.zig:4670:50: 0x10026f8eb in semaDecl (zig)
    const result_ref = (try sema.analyzeBodyBreak(&block_scope, body)).?.operand;
                                                 [32;1m^
/Users/jarred/Build/zig-latest4/src/Module.zig:4291:38: 0x1000dda47 in ensureDeclAnalyzed (zig)
    const type_changed = mod.semaDecl(decl_index) catch |err| switch (err) {
                                     [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:27874:32: 0x100ac45a3 in ensureDeclAnalyzed (zig)
    sema.mod.ensureDeclAnalyzed(decl_index) catch |err| {
                               [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:27916:32: 0x100744cfb in analyzeDeclRef (zig)
    try sema.ensureDeclAnalyzed(decl_index);
                               [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:27844:45: 0x100a8feef in analyzeDeclVal (zig)
    const decl_ref = try sema.analyzeDeclRef(decl_index);
                                            [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:5777:31: 0x1006752d7 in zirDeclVal (zig)
    return sema.analyzeDeclVal(block, src, decl);
                              [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:928:65: 0x10043e0db in analyzeBodyInner (zig)
            .decl_val                     => try sema.zirDeclVal(block, inst),
                                                                [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:817:45: 0x100273387 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:767:50: 0x100a7cd9f in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:6142:63: 0x100670cab in zirCall (zig)
        const resolved = try sema.resolveBody(block, args_body[arg_start..arg_end], inst);
                                                              [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:918:62: 0x10043d73b in analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst),
                                                             [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:817:45: 0x100273387 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            [32;1m^
/Users/jarred/Build/zig-latest4/src/Module.zig:4670:50: 0x10026f8eb in semaDecl (zig)
    const result_ref = (try sema.analyzeBodyBreak(&block_scope, body)).?.operand;
                                                 [32;1m^
/Users/jarred/Build/zig-latest4/src/Module.zig:4291:38: 0x1000dda47 in ensureDeclAnalyzed (zig)
    const type_changed = mod.semaDecl(decl_index) catch |err| switch (err) {
                                     [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:27874:32: 0x100ac45a3 in ensureDeclAnalyzed (zig)
    sema.mod.ensureDeclAnalyzed(decl_index) catch |err| {
                               [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:27916:32: 0x100744cfb in analyzeDeclRef (zig)
    try sema.ensureDeclAnalyzed(decl_index);
                               [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:27844:45: 0x100a8feef in analyzeDeclVal (zig)
    const decl_ref = try sema.analyzeDeclRef(decl_index);
                                            [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:5777:31: 0x1006752d7 in zirDeclVal (zig)
    return sema.analyzeDeclVal(block, src, decl);
                              [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:928:65: 0x10043e0db in analyzeBodyInner (zig)
            .decl_val                     => try sema.zirDeclVal(block, inst),
                                                                [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:5288:34: 0x100abeb4f in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:5271:85: 0x1007207e7 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                                                                    [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:1453:69: 0x10044db17 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    [32;1m^
/Users/jarred/Build/zig-latest4/src/Sema.zig:800:30: 0x100620bff in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             [32;1m^
/Users/jarred/Build/zig-latest4/src/Module.zig:5697:43: 0x100421a5f in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                                          [32;1m^
/Users/jarred/Build/zig-latest4/src/Module.zig:4377:40: 0x1002521ff in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       [32;1m^
/Users/jarred/Build/zig-latest4/src/Compilation.zig:3119:42: 0x10024ff83 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         [32;1m^
/Users/jarred/Build/zig-latest4/src/Compilation.zig:3057:30: 0x10011cca7 in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             [32;1m^
/Users/jarred/Build/zig-latest4/src/Compilation.zig:2361:31: 0x100118e3f in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              [32;1m^
/Users/jarred/Build/zig-latest4/src/main.zig:3441:20: 0x10014551b in updateModule (zig)
    try comp.update();
                   [32;1m^
/Users/jarred/Build/zig-latest4/src/main.zig:3103:17: 0x1000296d3 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                [32;1m^
/Users/jarred/Build/zig-latest4/src/main.zig:261:31: 0x100002ed3 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Obj });
                              [32;1m^
/Users/jarred/Build/zig-latest4/src/main.zig:201:20: 0x10000245f in main (zig)
    return mainArgs(gpa, arena, args);
                   [32;1m^
/Users/jarred/Build/zig-latest4/lib/std/start.zig:614:37: 0x1000048b3 in main (zig)
            const result = root.main() catch |err| {
                                    [32;1m^
???:?:?: 0x1af26fe4f in ??? (???)
???:?:?: 0x81417fffffffffff in ??? (???)
Stop reason: signal SIGABRT
```

### Expected Behavior

No segfault, just a compilation error

**Comment by Jarred-Sumner** [comment] 2022-12-29 10:05
When the `getHashes` function was not defined, the compiler segfaulted:
```zig
 comptime {
        if (@TypeOf(CryptoHasher.constructor) != (fn (*JSC.JSGlobalObject, *JSC.CallFrame) callconv(.C) ?*CryptoHasher)) {
            @compileLog("CryptoHasher.constructor is not a constructor");
        }

        if (@TypeOf(CryptoHasher.finalize) != (fn (*CryptoHasher) callconv(.C) void)) {
            @compileLog("CryptoHasher.finalize is not a finalizer");
        }

        if (@TypeOf(CryptoHasher.getAlgorithm) != GetterType)
            @compileLog("Expected CryptoHasher.getAlgorithm to be a getter");

        if (@TypeOf(CryptoHasher.getByteLength) != GetterType)
            @compileLog("Expected CryptoHasher.getByteLength to be a getter");

        if (@TypeOf(CryptoHasher.digest) != CallbackType)
            @compileLog("Expected CryptoHasher.digest to be a callback but received " ++ @typeName(@TypeOf(CryptoHasher.digest)));
        if (@TypeOf(CryptoHasher.update) != CallbackType)
            @compileLog("Expected CryptoHasher.update to be a callback but received " ++ @typeName(@TypeOf(CryptoHasher.update)));
        if (@TypeOf(CryptoHasher.hash) != StaticCallbackType)
            @compileLog("Expected CryptoHasher.hash to be a static callback");
        if (@TypeOf(CryptoHasher.getHashes) != StaticGetterType)
            @compileLog("Expected CryptoHasher.getHashes to be a static getter");

        if (!JSC.is_bindgen) {
            @export(CryptoHasher.constructor, .{ .name = "CryptoHasherClass__construct" });
            @export(CryptoHasher.digest, .{ .name = "CryptoHasherPrototype__digest" });
            @export(CryptoHasher.finalize, .{ .name = "CryptoHasherClass__finalize" });
            @export(CryptoHasher.getAlgorithm, .{ .name = "CryptoHasherPrototype__getAlgorithm" });
            @export(CryptoHasher.getByteLength, .{ .name = "CryptoHasherPrototype__getByteLength" });
            @export(CryptoHasher.getHashes, .{ .name = "CryptoHasherClass__getHashes" });
            @export(CryptoHasher.hash, .{ .name = "CryptoHasherClass__hash" });
            @export(CryptoHasher.update, .{ .name = "CryptoHasherPrototype__update" });
        }
    }
```

There were other functions which were not defined and those did not cause the compiler segfault. Once `getHashes` was defined, it no longer segfaulted.

I'm guessing that this would only occur when other errors were also present

**Comment by Vexu** [comment] 2022-12-29 10:58
Likely duplicate of #12765

**Closed by Vexu** 2022-12-29 10:58 UTC
Labels: bug
