### ISSUE TITLE
intCast to var_args causes crash

### ISSUE THREAD

**Issue by sin-ack** [ziglang/zig#16214] opened 2023-06-25 20:55 UTC
### Zig Version

0.11.0-dev.3831+df389b62d

### Steps to Reproduce and Observed Behavior

Minimal reproducer:

```zig
const std = @import("std");

pub fn main() void {
    _ = std.os.system.open("foo", 0, @intCast(0));
}
```

Need to build with `-lc`.

<details>
<summary>Crash log</summary>

```
thread 17338 panic: reached unreachable code
Analyzing test.zig: test.zig:main
      %19 = dbg_stmt(2, 38)
    > %20 = int_cast(%15, @InternPool.Index.zero) 
      %21 = break_inline(%15, %20)
    For full context, use the command
      zig ast-check -t test.zig

  in test.zig: test.zig:main
    > %15 = field_call(.auto, %12, "open", [
        {%16, %17},
        {%18},
        {%19..%21},
      ]) 
  in test.zig: test.zig:main
    > %5 = block({%6..%25}) 

/home/agni/zig/compiler/lib/std/debug.zig:258:14: 0x8e5986 in assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
/home/agni/zig/compiler/src/Sema.zig:1817:11: 0x158801a in resolveType (zig)
    assert(air_inst != .var_args_param_type);
          ^
/home/agni/zig/compiler/src/Sema.zig:1841:36: 0x15a949a in resolveCastDestType (zig)
    const raw_ty = sema.resolveType(block, src, zir_ref) catch |err| switch (err) {
                                   ^
/home/agni/zig/compiler/src/Sema.zig:9632:49: 0x10d6905 in zirIntCast (zig)
    const dest_ty = try sema.resolveCastDestType(block, src, extra.lhs, .remove_eu_opt, "@intCast");
                                                ^
/home/agni/zig/compiler/src/Sema.zig:1045:65: 0xddb83f in analyzeBodyInner (zig)
            .int_cast                     => try sema.zirIntCast(block, inst),
                                                                ^
/home/agni/zig/compiler/src/Sema.zig:840:45: 0xc0bee5 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/agni/zig/compiler/src/Sema.zig:789:50: 0x15ab603 in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 ^
/home/agni/zig/compiler/src/Sema.zig:6524:46: 0x1082a30 in zirCall__anon_134123 (zig)
        const resolved = try sema.resolveBody(block, args_body[arg_start..arg_end], inst);
                                             ^
/home/agni/zig/compiler/src/Sema.zig:945:62: 0xdd694f in analyzeBodyInner (zig)
            .field_call                   => try sema.zirCall(block, inst, .field),
                                                             ^
/home/agni/zig/compiler/src/Sema.zig:5675:34: 0x165ca39 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/agni/zig/compiler/src/Sema.zig:5658:33: 0x115851d in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/agni/zig/compiler/src/Sema.zig:1485:49: 0xde8225 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
/home/agni/zig/compiler/src/Sema.zig:823:30: 0x1023c28 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/agni/zig/compiler/src/Module.zig:5625:21: 0xdb9100 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/agni/zig/compiler/src/Module.zig:4223:40: 0xbec269 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func_index, sema_arena) catch |err| switch (err) {
                                       ^
/home/agni/zig/compiler/src/Compilation.zig:3143:42: 0xbea249 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/agni/zig/compiler/src/Compilation.zig:3080:30: 0xa7fefe in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
/home/agni/zig/compiler/src/Compilation.zig:2029:31: 0xa7c6c0 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/agni/zig/compiler/src/main.zig:3842:24: 0xaa92aa in updateModule (zig)
        try comp.update(main_progress_node);
                       ^
/home/agni/zig/compiler/src/main.zig:3277:17: 0x938305 in buildOutputType (zig)
    updateModule(comp) catch |err| switch (err) {
                ^
/home/agni/zig/compiler/src/main.zig:269:31: 0x8e7811 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/home/agni/zig/compiler/src/main.zig:213:20: 0x8e4e05 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/agni/zig/compiler/lib/std/start.zig:608:37: 0x8e4887 in main (zig)
            const result = root.main() catch |err| {
                                    ^
```

</details>

### Expected Behavior

No crashy

**Comment by Vexu** [comment] 2023-06-25 21:06
Duplicate of #16197

**Closed by Vexu** 2023-06-25 21:06 UTC
Labels: bug
