### ISSUE TITLE
comptime crash on type confusion

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#13564] opened 2022-11-16 12:55 UTC
### Zig Version

0.11.0-dev.183+ceb9fedb4

### Steps to Reproduce and Observed Behavior

Perform `zig test` on the following snippet:

```zig
const std = @import("std");

comptime {
    @compileLog(minimize);
}

const ColorIndex = enum(u8) { _ };

fn parse(comptime def: []const u8) [9][9]?ColorIndex {
    var icon = std.mem.zeroes([9][9]?ColorIndex);
    var it = std.mem.split(u8, def, "\n");
    var y: usize = 0;
    while (it.next()) |line| : (y += 1) {
        var x: usize = 0;
        while (x < icon[0].len) : (x += 1) {
            icon[y][x] = std.fmt.parseInt(u8, line[x .. x + 1], 16) catch null;
        }
    }
    return icon;
}

pub const minimize = parse(
    \\.........
    \\.FFFFFFF.
    \\.F.....F.
    \\.FFFFFFF.
    \\.F.....F.
    \\.F.....F.
    \\.F.....F.
    \\.FFFFFFF.
    \\.........
);
```

If doing so, the code crashes with the following stack trace:

<details>
 <summary>Stack trace ([Segmentation fault at address 0x40](panic: incorrect alignment))</summary>

```
thread 30461 panic: incorrect alignment
/home/felix/projects/forks/zig/lib/std/hash_map.zig:937:100: 0x79fa6fe in header (zig)
            return @ptrCast(*Header, @ptrCast([*]Header, @alignCast(@alignOf(Header), self.metadata.?)) - 1);
                                                                                                   ^
/home/felix/projects/forks/zig/lib/std/hash_map.zig:951:31: 0x79fa36c in capacity (zig)
            return self.header().capacity;
                              ^
/home/felix/projects/forks/zig/lib/std/hash_map.zig:1137:39: 0x82f3269 in getPtrAdapted__anon_200875 (zig)
            const mask = self.capacity() - 1;
                                      ^
/home/felix/projects/forks/zig/lib/std/hash_map.zig:1236:38: 0x802eba4 in getPtrContext (zig)
            return self.getPtrAdapted(key, ctx);
                                     ^
/home/felix/projects/forks/zig/lib/std/hash_map.zig:1233:38: 0x7d69c54 in getPtr (zig)
            return self.getPtrContext(key, undefined);
                                     ^
/home/felix/projects/forks/zig/src/Sema.zig:14772:44: 0x79349e0 in zirClosureGet (zig)
        if (scope.captures.getPtr(inst_data.inst)) |tv| {
                                           ^
/home/felix/projects/forks/zig/src/Sema.zig:819:68: 0x772da98 in analyzeBodyInner (zig)
            .closure_get                  => try sema.zirClosureGet(block, inst),
                                                                   ^
/home/felix/projects/forks/zig/src/Sema.zig:719:45: 0x7592905 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/felix/projects/forks/zig/src/Sema.zig:669:50: 0x7d5f0bb in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 ^
/home/felix/projects/forks/zig/src/Sema.zig:5965:63: 0x7933999 in zirCall (zig)
        const resolved = try sema.resolveBody(block, args_body[arg_start..arg_end], inst);
                                                              ^
/home/felix/projects/forks/zig/src/Sema.zig:818:62: 0x772d9ba in analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst),
                                                             ^
/home/felix/projects/forks/zig/src/Sema.zig:5116:34: 0x7d9d2ac in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/felix/projects/forks/zig/src/Sema.zig:5099:85: 0x79f28e9 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                                                                    ^
/home/felix/projects/forks/zig/src/Sema.zig:1351:69: 0x773ce54 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/felix/projects/forks/zig/src/Sema.zig:5116:34: 0x7d9d2ac in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/felix/projects/forks/zig/src/Sema.zig:5099:85: 0x79f28e9 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                                                                    ^
/home/felix/projects/forks/zig/src/Sema.zig:1351:69: 0x773ce54 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/felix/projects/forks/zig/src/Sema.zig:702:30: 0x78e85b8 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/felix/projects/forks/zig/src/Module.zig:5639:43: 0x7712c50 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                                          ^
/home/felix/projects/forks/zig/src/Module.zig:4338:40: 0x7573bd2 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/felix/projects/forks/zig/src/Compilation.zig:3090:42: 0x7571a7d in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/felix/projects/forks/zig/src/Compilation.zig:3028:30: 0x745bdca in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/felix/projects/forks/zig/src/Compilation.zig:2356:31: 0x7457db8 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/felix/projects/forks/zig/src/main.zig:3342:20: 0x7483c06 in updateModule (zig)
    try comp.update();
                   ^
/home/felix/projects/forks/zig/src/main.zig:3009:17: 0x739e76e in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/felix/projects/forks/zig/src/main.zig:236:31: 0x737dce5 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/felix/projects/forks/zig/src/stage1.zig:56:24: 0x74e6cf7 in main (zig)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
```

</details>

The crash can also produce other errors:

<details>
 <summary>Stack trace (Segmentation fault at address 0x40)</summary>

```
Semantic Analysis [1025] closeDir... Segmentation fault at address 0x40
/home/felix/projects/forks/zig/lib/std/hash_map.zig:951:33: 0x79fa36d in capacity (zig)
            return self.header().capacity;
                                ^
/home/felix/projects/forks/zig/lib/std/hash_map.zig:1137:39: 0x82f3269 in getPtrAdapted__anon_200875 (zig)
            const mask = self.capacity() - 1;
                                      ^
/home/felix/projects/forks/zig/lib/std/hash_map.zig:1236:38: 0x802eba4 in getPtrContext (zig)
            return self.getPtrAdapted(key, ctx);
                                     ^
/home/felix/projects/forks/zig/lib/std/hash_map.zig:1233:38: 0x7d69c54 in getPtr (zig)
            return self.getPtrContext(key, undefined);
                                     ^
/home/felix/projects/forks/zig/src/Sema.zig:14772:44: 0x79349e0 in zirClosureGet (zig)
        if (scope.captures.getPtr(inst_data.inst)) |tv| {
                                           ^
/home/felix/projects/forks/zig/src/Sema.zig:819:68: 0x772da98 in analyzeBodyInner (zig)
            .closure_get                  => try sema.zirClosureGet(block, inst),
                                                                   ^
/home/felix/projects/forks/zig/src/Sema.zig:719:45: 0x7592905 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/felix/projects/forks/zig/src/Sema.zig:669:50: 0x7d5f0bb in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 ^
/home/felix/projects/forks/zig/src/Sema.zig:5965:63: 0x7933999 in zirCall (zig)
        const resolved = try sema.resolveBody(block, args_body[arg_start..arg_end], inst);
                                                              ^
/home/felix/projects/forks/zig/src/Sema.zig:818:62: 0x772d9ba in analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst),
                                                             ^
/home/felix/projects/forks/zig/src/Sema.zig:5116:34: 0x7d9d2ac in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/felix/projects/forks/zig/src/Sema.zig:5099:85: 0x79f28e9 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                                                                    ^
/home/felix/projects/forks/zig/src/Sema.zig:1351:69: 0x773ce54 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/felix/projects/forks/zig/src/Sema.zig:5116:34: 0x7d9d2ac in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/felix/projects/forks/zig/src/Sema.zig:5099:85: 0x79f28e9 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                                                                    ^
/home/felix/projects/forks/zig/src/Sema.zig:1351:69: 0x773ce54 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/felix/projects/forks/zig/src/Sema.zig:702:30: 0x78e85b8 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/felix/projects/forks/zig/src/Module.zig:5639:43: 0x7712c50 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                                          ^
/home/felix/projects/forks/zig/src/Module.zig:4338:40: 0x7573bd2 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/felix/projects/forks/zig/src/Compilation.zig:3090:42: 0x7571a7d in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/felix/projects/forks/zig/src/Compilation.zig:3028:30: 0x745bdca in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/felix/projects/forks/zig/src/Compilation.zig:2356:31: 0x7457db8 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/felix/projects/forks/zig/src/main.zig:3342:20: 0x7483c06 in updateModule (zig)
    try comp.update();
                   ^
/home/felix/projects/forks/zig/src/main.zig:3009:17: 0x739e76e in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/felix/projects/forks/zig/src/main.zig:230:31: 0x737da12 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/home/felix/projects/forks/zig/src/stage1.zig:56:24: 0x74e6cf7 in main (zig)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
```

</details>

### Expected Behavior

The code compiles and prints out an array

**Comment by Vexu** [comment] 2022-11-16 13:11
Duplicate of #12765, fixed by #13017, error revealed by adding `--debug-compile-errors`:
```sh-session
$ zig3 build-obj a.zig --debug-compile-errors
compile error during Sema: expected type '?a.ColorIndex', found 'u8', src: a.zig:Module.LazySrcLoc{ .node_offset_store_operand = 68 }
```

**Closed by Vexu** 2022-11-16 13:11 UTC
Labels: bug

**Comment by MasterQ32** [comment] 2022-11-16 13:20
Thanks for the confirmation. Wasn't sure if it was a duplicate, was hard to find the right issue.

**Comment by Vexu** [comment] 2022-11-16 13:24
If you see ` .closure_get` in the stack trace there and there is no `Zig compiler bug` panic then there is a pretty good chance it's a duplicate of that issue which can be verified using `--debug-compile-errors`.
