### ISSUE TITLE
cannot print u0 or use u0 in var args

### ISSUE THREAD

**Issue by kristate** [ziglang/zig#1538] opened 2018-09-17 16:21 UTC
```zig
const std = @import("std");
test "print u0" {
  var uz: u0 = 0;
  std.debug.warn("uz: {}", uz);
}
```

```
/Users/cfkk/Source/zig2/build/lib/zig/std/debug/index.zig:46:23: error: compiler bug: var args can't handle void. https://github.com/ziglang/zig/issues/557
    stderr.print(fmt, args) catch return;
                      ^
/Users/cfkk/Source/zig2/build/u0.zig:4:17: note: called from here
  std.debug.warn("uz: {}", uz);
                ^
```

related: #557 #1530

**Comment by andrewrk** [comment] 2019-12-09 21:28
duplicate of #557

**Closed by andrewrk** 2019-12-09 21:28 UTC
