### ISSUE TITLE
Windows paths allow unpaired surrogates

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2565] opened 2019-05-27 07:07 UTC
Windows allows unpaired surrogates in paths; which are not valid UTF-16LE.

_Originally posted by @daurnimator in https://github.com/ziglang/zig/pull/2527_

**Comment by emekoi** [comment] 2019-05-27 14:54
see [here](https://simonsapin.github.io/wtf-8/).

**Comment by tgschultz** [comment] 2019-05-27 15:34
The only way I can think to deal with this universally would be to consider all file paths to be raw bytes and ignore encoding. I'm not sure that's viable in a cross-platform api.

**Comment by shawnl** [comment] 2019-05-27 15:57
@tgschultz  these can be encoded with WTF-8, if someone cares enough to do the work. I haven't even gotten my UTF-8 improvements merged yet. The problem is that then a whole bunch of APIs have to accept WTF-8 instead of UTF-8, and have flags to tell them apart, so its a huge maintenance burden to support junk. As Windows already has a bunch of nutty path-name restrictions, I think erroring out on non-valid unicode is fine.

**Comment by mikdusan** [comment] 2019-05-27 16:13
came across this article might be relevant: https://googleprojectzero.blogspot.com/2016/02/the-definitive-guide-on-win32-to-nt.html

**Comment by tgschultz** [comment] 2019-05-27 16:20
Actually yeah, I think you're right. Erroring out on the edge case of unpaired surrogates is probably better, and then the programmer can use the OS API directly if they really need to support it. 

Does anyone have information about how often such cases occur in reality? Off-hand, I think it would most likely be an issue in Asian locales where 2-byte character representations were used pre-UCS2.

Another alternative would be having a real string type in std in the form of a tagged byte buffer with the encoding specified. Of course, that also means rewriting a whole lot of APIs.

**Comment by daurnimator** [comment] 2019-05-28 06:03
> Actually yeah, I think you're right. Erroring out on the edge case of unpaired surrogates is probably better, and then the programmer can use the OS API directly if they really need to support it.

I think erroring out is the wrong option, converting to/from WTF-8 is the well-established solution in other languages.

> Does anyone have information about how often such cases occur in reality?

They get onto the file system often enough if someone is truncating strings in Java or Javascript (languages where strings are UCS-2) without realising they could be astral plane characters (e.g. emojis).
I would not expect e.g. directory iteration in zig to suddenly fail in the presence of such characters. Or that a path returned from a directory iteration is unable to be passed to `delete`.

**Comment by jdalton** [comment] 2024-02-09 19:18
Reference for anyone wanting to tackle a support PR bun handles it here:

https://github.com/oven-sh/bun/blob/f77b217abf2f33fdea4a50298d07cd601a655b0d/src/string_immutable.zig#L1835-L1848

**Closed** 2024-02-25 09:00 UTC
Labels: bug, standard library, os-windows
