### ISSUE TITLE
Compiler segfault when breaking from block in inline for loop

### ISSUE THREAD

**Issue by LordMZTE** [ziglang/zig#11845] opened 2022-06-11 09:12 UTC
### Zig Version

0.10.0-dev.2587+9b05474d7

### Steps to Reproduce

1. Create a file `segfault.zig` with this content:
```zig
const std = @import("std");

pub fn main() !void {
    // I'm allocating this on the heap to prevent the whole inline for shenanigans
    // getting optimized out
    const a = try std.testing.allocator.create(u8);
    defer std.testing.allocator.destroy(a);
    a.* = 1;

    const n: ?u8 = blk: {
        // needs to be multiple values, `.{ 1 }` doesn't trigger the error
        inline for (.{ 1, 2 }) |n| {
            // break has to be conditional
            if (n == a.*)
                break :blk n;
        }

        break :blk null;
    };

    std.debug.print("{}", .{n});
}
```
2. `zig build-exe segfault.zig`

### Expected Behavior

The code compiles and runs as expected.

### Actual Behavior

The zig compiler segfaults: `fish: Job 1, 'zig build-exe segfault.zig' terminated by signal SIGSEGV (Address boundary error)`.

Stack trace (using lldb):
```
* thread #1, name = 'zig', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x00007fffeedeb1c4 libLLVM-13.so`llvm::BasicBlock::getContext() const + 4
    frame #1: 0x00007fffeeecc644 libLLVM-13.so`llvm::BranchInst::BranchInst(llvm::BasicBlock*, llvm::Instruction*) + 36
    frame #2: 0x00007fffeee2aa7f libLLVM-13.so`LLVMBuildBr + 79
    frame #3: 0x0000555555c401d6 zig`___lldb_unnamed_symbol8039 + 6646
    frame #4: 0x0000555555c41938 zig`___lldb_unnamed_symbol8040 + 2904
    frame #5: 0x0000555555c4311c zig`codegen_build_object(CodeGen*) + 2316
    frame #6: 0x00005555557ed05c zig
    frame #7: 0x00005555557ddfa4 zig
    frame #8: 0x000055555579fe0f zig
    frame #9: 0x000055555577b990 zig
    frame #10: 0x000055555572cc5d zig`main + 4285
    frame #11: 0x00007fffeda29290 libc.so.6`___lldb_unnamed_symbol3123 + 128
    frame #12: 0x00007fffeda2934a libc.so.6`__libc_start_main + 138
    frame #13: 0x0000555555729415 zig`_start + 3
    ```

**Comment by LordMZTE** [comment] 2022-06-11 09:22
Some additional info:
- OS: Arch Linux, 5.18.3 kernel
- Target: x86_64 on GNU
- The compiler was built by my build server, so not the machine it's running on.

**Comment by Vexu** [comment] 2022-06-11 09:26
Duplicate of #9524

**Closed by Vexu** 2022-06-11 09:26 UTC
Labels: bug
