### ISSUE TITLE
`std.mem.Allocator.allocZeroed`

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#11559] opened 2022-05-01 15:13 UTC
So what initially led me down this rabbit hole is that I have to allocate at least 64 KiB (the size of one page in Wasm) of memory to instantiate a Wasm module. I started with a naive `std.mem.Allocator.alloc(u8, std.wasm.page_size)` but then I remembered that the Wasm specification also requires all the memory to be zeroed.
So initially I just wanted to go with an `std.mem.set`. But then I informed myself a bit more and realized that **most modern operating systems already give you zero-initialized memory**.
So why would I have to `std.mem.set` it to zero all over again? At least on the platforms where I already have guaranteed zero-initialized memory I shouldn't have to do it again if we can avoid it, which we can with this idea.

For example `mmap` guarantees zero-initialized memory, and so does `VirtualAlloc`.
But still we `@memset` all memory to `undefined` (https://github.com/ziglang/zig/blob/master/lib/std/mem/Allocator.zig#L320 and other places) because we can't just rely on memory being zero "on most OSes". It would break portability and be unsafe if we decide to run our program on an OS that may not guarantee zero-initialized memory. Surely there are OSes out there that will happily give you insight to the memory of other processes.

But still, AFAIK the 3 major OSes Linux, macOS, and Windows all essentially guarantee you zero-initialized memory, so why don't we take advantage of this guarantee on at least those platforms and propagate that guarantee to the user with something like `std.mem.Allocator.allocZeroed`? Of course, to take advantage of it we will have to implement some other function first on a level low enough to know whether or not the OS provides us with zero-initialized memory or not.
The appropriate level would be the `VTable` https://github.com/ziglang/zig/blob/master/lib/std/mem/Allocator.zig#L16, I believe.
So we would add something like `allocZeroed` there with the same signature as `alloc` (https://github.com/ziglang/zig/blob/master/lib/std/mem/Allocator.zig#L64) and then, in a place where we have to implement said `allocZeroed` (like here https://github.com/ziglang/zig/blob/master/lib/std/heap.zig#L253), we could simply do some `switch`ing on the OS tag, and choose the appropriate allocation function (e.g. `mmap` or `VirtualAlloc`). Then in the `else` prong we will have an OS that doesn't provide any function that guarantees zero-initialized memory (but only functions to allocate memory filled with whatever). There we will simply do a manual `@memset(slice.ptr, 0, slice.len);`. Problem solved.
So on some OSes `allocZeroed` would at least from the internal functionality essentially be an alias to `alloc`, but with an important guarantee.

Then you can expose that internal `allocZeroed` on the higher level with an `std.mem.Allocator.allocZeroed` etc.

I had a talk on Discord with some people and it doesn't seem like too bad of an idea, apparently.

#4298 could be relevant.

- [ ] Also, when that is added to `VTable`, it might make sense to adjust the documentation a bit and state that `VTable.alloc` provides no guarantees about the initial content, while `VTable.allocZeroed` will guarantee zeroed memory.

---

(Next follows something that is possibly a bit off-topic)
Additionally, while I was at it, I researched a bit about the ways of allocating heap memory on Windows and came across an alternative to `VirtualAlloc` which is `HeapAlloc`:
https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapalloc
On Windows Zig currently uses `VirtualAlloc` to allocate heap memory (<https://github.com/ziglang/zig/blob/master/lib/std/heap.zig#L273>) but the alternative to `VirtualAlloc` I came across which is `HeapAlloc` apparently allocates faster than `VirtualAlloc` if you don't pass `HEAP_ZERO_MEMORY` to it as a flag because that will make it not zero-initialize the memory.
So `HeapAlloc` without a `HEAP_ZERO_MEMORY` flag could be used in the implementation of `VTable.alloc` and the `VirtualAlloc` we use currently would only be used in the new `VTable.allocZeroed`.
The advantage here is performance. I'm no expert on these functions at all, so I could be very wrong.

**Comment by daurnimator** [comment] 2022-05-03 01:33
Duplicate of rejected https://github.com/ziglang/zig/issues/2090

**Closed by daurnimator** 2022-05-03 01:33 UTC

**Comment by r00ster91** [comment] 2022-05-03 07:44
I'm sorry but I think that's a bit of an early close.
What is the alternative? We need an alternative.
I don't understand why it's such a bad thing to expose something that most operating systems provide out of the box. They specifically provide memory with zeroes, no other specific value. That's why I didn't propose `allocWithValue` or something.
Do you expect people to go back to the stone age for this and use `calloc` or something? That's going to introduce some unidiomatic and possibly problematic code.
Does this mean we will always have to take the hit of a possibly very large `std.mem.set`? Don't expect the compiler to optimize it, because it won't: https://zig.godbolt.org/z/4WvWohaW8
The compiler doesn't know what we know and could expose.

Is one problem perhaps the implicit zeroing `@memset` on platforms that don't provide any allocation functions that guarantee zeroed memory? In that case, we could also throw a compile  error if that's an issue.

I wonder if this will be acceptable. Will Zig permanently suffer from this disadvantage?
It's been 3 years since #2090 has been closed.
Can we please get some feedback from @andrewrk himself on this, the original closer of #2090?

How do I efficiently allocate >= `64 * 1024` of memory that I need to be zero? In this case, I need it for the instantiation of a Wasm module.

**Comment by r00ster91** [comment] 2022-05-03 08:33
So I had a talk with @Deecellar on Discord and we came to the conclusion that:
* The allocator interface doesn't know anything about the allocators.
* The allocator interface doesn't know the initial content of the memory. It is decided by the implementing allocator.
* It is best **to simply add something like `ZeroAllocator`**. Whether something like that should be in the `std` or not is a different topic.

**Comment by nektro** [comment] 2023-03-02 05:41
implemented this in my `gimme` allocator-collection module, available here https://github.com/nektro/gimme/blob/master/src/ZeroAllocator.zig
