### ISSUE TITLE
Customize the file name of the shared library

### ISSUE THREAD

**Issue by heibor** [ziglang/zig#3092] opened 2019-08-18 08:40 UTC
Is there any way to customize the file name of the shared library?

In the build.zig, when I use method `addSharedLibrary("foo", null, ver)`, it will generate `libfoo.dylib` in MacOSX, sometimes, I want to customize the file name, for example I want to use `foo.so` in MacOSX, is it possible?

**Comment by daurnimator** [comment] 2019-08-18 11:06
Duplicate of #2231

**Closed by daurnimator** 2019-08-18 11:06 UTC
