### ISSUE TITLE
Unable to open library dir (AUR)

### ISSUE THREAD

**Issue by abuxTM** [ziglang/zig#21839] opened 2024-10-28 14:15 UTC
### Zig Version

0.14.0-dev.2051+b1361f237

### Steps to Reproduce and Observed Output

i have downloaded the newest zig version from arch linux AUR

```
paru -S zig-nightly-bin
```

```
zig build run
```

ERROR
```
   └─ zig build-exe gunna-maskot Debug native failure
error: warning: unable to open library directory '/usr/local/lib64': FileNotFound
warning: unable to open library directory '/usr/lib/x86_64-linux-gnu': FileNotFound
warning: unable to open library directory '/lib/x86_64-linux-gnu': FileNotFound
```

### Expected Output

```
error: warning: unable to open library directory
```

Error be gone

**Comment by NicoElbers** [comment] 2024-10-28 22:30
hacky fix from zulip:
> i hadn't clocked that it's a warning, so ig i can just invoke zig build-exe directly, or hack the build system locally -- but it does block a normal zig build workflow, because zig build interprets stderr from a zig process as failure (see my paste above)

https://zsf.zulipchat.com/#narrow/channel/454360-compiler/topic/linking/near/479174521
https://zsf.zulipchat.com/#narrow/channel/454360-compiler/topic/linking/near/479069188

**Comment by andrewrk** [comment] 2024-10-29 06:37
dupe of #21797

**Closed by andrewrk** 2024-10-29 06:37 UTC
Labels: error message
