### ISSUE TITLE
segmentation fault when compiling a free on an undefined pointer

### ISSUE THREAD

**Issue by Pyrolistical** [ziglang/zig#13289] opened 2022-10-24 19:07 UTC
### Zig Version

0.10.0-dev.4560+828735ac0

### Steps to Reproduce

Given `repo.zig`
```
const std = @import("std");

pub fn main() void {
    const bar: [*]u8 = undefined;
    std.heap.page_allocator.free(bar);
}
```

Run: `zig build-exe repo.zig`

### Expected Behavior

Compiler error or success

### Actual Behavior

Crashes
```
$ zig build-exe repo.zig
zsh: segmentation fault  zig build-exe repo.zig
```

**Comment by Pyrolistical** [comment] 2022-10-24 19:07
Might be related to https://github.com/ziglang/zig/issues/5488

**Comment by Pyrolistical** [comment] 2022-10-24 19:09
Also tested with GPA still crashes.

**Comment by Vexu** [comment] 2022-10-24 19:17
Duplicate of #12927

**Closed by Vexu** 2022-10-24 19:17 UTC
Labels: bug
