### ISSUE TITLE
_ = aFunctionThatReturnsNonVoidErrorUnion(); // discards error

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#1997] opened 2019-02-22 23:34 UTC
There is neither a syntactic declaration nor a compile error that an error is being discarded:

    fn a() !i32 {
        return Error.SomeError;
    }

    fun b() void {
        _ = a();                           // compile error - discarding error from a()
        _ = try Error.SomeError catch a(); // compile error - discarding error from a()
    }

Rewritten to declare discarding of errors:

    if (a()) |_| {} else |_| {}
    try Error.SomeError catch {if (a()) |_| {} else |_| {};

edit: my actual case was something like:

    fn c() !i32 {
        _ = std.fmt.bufPrint(...);
        ...
        _ = try std.fmt.bufPrint(...);
    }

and the compiler did not tell me that I was losing an error in the first call to bufPrint.

**Comment by andrewrk** [comment] 2019-02-23 03:03
Duplicate of #772

**Closed by andrewrk** 2019-02-23 03:03 UTC
