### ISSUE TITLE
regression: can't target x86_64-freebsd-* ("error: libc not available"/"unable to provide libc" - even if not linking to libc)

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [ziglang/zig#14729] opened 2023-02-25 19:26 UTC
### Zig Version

0.11.0-dev.1797+d3c9bfada

### Steps to Reproduce and Observed Behavior

As of now, libc is not provided on freebsd yet, but zig should allow to cross compile for freebsd target if not linking libc.
But even with empty project that doesn't use libc zig complains about libc, afaik this shouldn't happen.

```
> zig init-exe
> zig build -Dtarget=x86_64-freebsd
```

Gives:
```
error: libc not available
    note: run 'zig libc -h' to learn about libc installations
    note: run 'zig targets' to see the targets for which zig can always provide libc
error: directory_name...
error: The following command exited with error code 1:
```

I tried other x86_64-freebsd-* triplets with different abi's, but none worked.

### Expected Behavior

Compile a standalone project without libc dependency for freebsd even if we don't ship libc for freebsd yet without compiler complaining about it.

**Comment by eLeCtrOssSnake** [comment] 2023-02-25 20:07
Note that if linking to libc it gives a different error message.

**Comment by ifreund** [comment] 2023-02-25 20:20
Zig intentionally requires linking libc when targeting FreeBSD as libc is the only stable syscall interface on FreeBSD.

Cross compiling to FreeBSD is currently only possible by obtaining your own copy of the FreeBSD libc and using zig's `--libc` flag to link against it.

Once #2876 is implemented zig will be able provide a copy of FreeBSD for this use case itself.

Also, the title says regression but to my knowledge this has never worked due to the reasons listed above.

Anyhow, I'm closing this since it's effectively a duplicate of #2876.

**Closed by ifreund** 2023-02-25 20:20 UTC
Labels: bug

**Comment by jiacai2050** [comment] 2024-09-28 01:23
> by obtaining your own copy of the FreeBSD libc

Sorry to update this closed issue, but I have no idea how to copy freebsd libc, the doc [here](https://github.com/ziglang/zig/wiki/Updating-libc#freebsd) is also TBD

**Comment by nektro** [comment] 2024-09-28 01:36
<https://cgit.freebsd.org/src/tree/include/> 
plus an arch directory such as <https://cgit.freebsd.org/src/tree/sys/amd64/include/>
