### ISSUE TITLE
Filesystem Hierarchy Standard and build.zig's linkSystemLibrary

### ISSUE THREAD

**Issue by gamester0** [ziglang/zig#2575] opened 2019-05-28 14:15 UTC
build.zig's linkSystemLibrary function does not look into all the necessary directories at the moment.

In section 4.8 of the Filesystem Hierarchy Standard it states:

> /usr/lib\<qual\> performs the same role as /usr/lib for an alternate binary format, except that the
> symbolic links /usr/lib<qual>/sendmail and /usr/lib<qual>/X11 are not required.

In section 3.1 it states:

> There may be one or more variants of the /lib directory on systems which support more than one binary format requiring separate libraries. 

> This is commonly used for 64-bit or 32-bit support on systems which support multiple binary formats, but require libraries of the same name. In this case, /lib32 and /lib64 might be the library directories, and /lib a symlink to one of them.

I think we can ignore /lib* but not /usr/lib*.  In Fedora's case there's /usr/lib and /usr/lib64 which are separate directories. There's no /usr/lib32. linkSystemLibrary does not look into /usr/lib64 at the moment.

**Comment by gamester0** [comment] 2019-05-28 14:43
I didn't see the TODO in build.zig. Here's my result for "ld --verbose | grep SEARCH_DIR":

> SEARCH_DIR("=/usr/x86_64-redhat-linux/lib64"); SEARCH_DIR("=/usr/lib64"); SEARCH_DIR("=/usr/local/lib64"); SEARCH_DIR("=/lib64"); SEARCH_DIR("=/usr/x86_64-redhat-linux/lib"); SEARCH_DIR("=/usr/local/lib"); SEARCH_DIR("=/lib"); SEARCH_DIR("=/usr/lib");

I assume that /usr/lib64 is the most important one to get, but I might be wrong.

**Comment by andrewrk** [comment] 2019-05-28 22:16
Related: #2041 

@tiehuis suggested that this functionality should also exist in the compiler itself and I agree. Here's my plan of action:

 * Redefine/clarify `--library [arg]` option to mean "link against the system library named [arg]". Maybe this redefinition/clarification comes with a corresponding CLI update. (Maybe `-lfoo`/`-l foo` to match c compilers).
 * Move the library searching logic from zig build into the self-hosted compiler.
 * Update the library searching logic with the improvements noted in this issue.
 * Expose the self-hosted library searching logic to stage1 via libuserland.a (even stage1 now is a hybrid of zig/c++ code)
 * Update link.cpp to never pass names to the linker; instead opting to pass absolute paths. Zig wants to be able to know exactly what files are being linked. This could be important for some planned features, and could prevent issues such as the one on Windows where the wrong .lib files are picked up.

**Comment by andrewrk** [comment] 2020-02-10 18:09
duplicate of #2041

**Closed by andrewrk** 2020-02-10 18:09 UTC
Labels: enhancement, zig build system
