### ISSUE TITLE
allocator free with unsupport slice type,  got terminated unexpectedly

### ISSUE THREAD

**Issue by maxzhao** [ziglang/zig#12953] opened 2022-09-24 14:16 UTC
### Zig Version

0.10.0-dev.4166+cae76d829.tar.xz

### Steps to Reproduce

```zig
test "simple test" {
    const some: [*:0]const u8 = "";
    std.testing.allocator.free(some);
}
````

### Expected Behavior

➜  zigbug zig build -fstage1
lib/zig/std/mem.zig:3150:9: error: expected []T or *[_]T, passed [*:0]const u8
        @compileError("expected []T or *[_]T, passed " ++ @typeName(sliceType));
        ^
lib/zig/std/mem.zig:3157:59: note: called from here
pub fn sliceAsBytes(slice: anytype) SliceAsBytesReturnType(@TypeOf(slice)) {
                                                          ^
lib/zig/std/mem.zig:3157:59: note: called from here
pub fn sliceAsBytes(slice: anytype) SliceAsBytesReturnType(@TypeOf(slice)) {
                                                          ^
./src/main.zig:21:31: note: called from here
    std.testing.allocator.free(some);
                              ^
./src/main.zig:19:20: note: called from here
test "simple test" {
                   ^

### Actual Behavior

➜  zigbug zig build
error: test...
error: The following command terminated unexpectedly:

**Comment by Vexu** [comment] 2022-09-24 14:31
Duplicate of #12927

**Closed by Vexu** 2022-09-24 14:31 UTC
Labels: bug
