### ISSUE TITLE
pub export fn foo() bool returns a 1-byte bool giving non-deterministic results to callers (like C#) that expect a 4-byte bool

### ISSUE THREAD

**Issue by PhaseMage** [ziglang/zig#10171] opened 2021-11-19 06:37 UTC
### Zig Version

0.9.0-dev.1444+e2a2e6c14

### Steps to Reproduce

Zig:
```
pub export fn isAlive(context: usize) bool {
    const self = @intToPtr(*MyStruct, context);
    return self.is_alive;
}
```

C#:
```
    [DllImport("MyStruct.dll")]
    public static extern bool isAlive(UIntPtr ctx);
```

### Expected Behavior

I expected the Zig ``export`` keyword to enforce C ABI types. And I assumed that C# would also use C ABI. So I assumed the above would work.

### Actual Behavior

There is no ``bool`` in the C ABI.
C# marshals ``bool`` as 4-bytes to have compatibility with Win32 ``BOOLEAN``.
Zig uses 1-byte ``bool``, so C# gets non-deterministic behavior when calling the above exported function.

Perhaps Zig should expand to 4-byte ``bool`` for return values or output parameters in an ``export`` context?

Workaround is to return a u32 type like so: ````
```
pub export fn isAlive(context: usize) u32 {
    const self = @intToPtr(*MyStruct, context);
    return if (self.is_alive) 1 else 0;
}
```

**Comment by LemonBoy** [comment] 2021-11-19 08:41
> There is no bool in the C ABI.

[Wrong](https://en.cppreference.com/w/c/language/arithmetic_types#Boolean_type).

> C# marshals bool as 4-bytes to have compatibility with Win32 BOOLEAN.

The aim is to be compatible with C, not C#.

> Zig uses 1-byte bool, so C# gets non-deterministic behavior when calling the above exported function.

This quote from the C standard matches the current Zig's behaviour:

> While the number of bits in a _Bool object is at least CHAR_BIT, the width (number of sign and value bits) of a _Bool may be just 1 bit.

**Comment by andrewrk** [comment] 2021-11-20 18:57
Closing as "working as designed" since the C ABI does define how `bool` should work. C# code that wants to interface with a `bool` in terms of the C ABI should use `byte`.

**Closed by andrewrk** 2021-11-20 18:57 UTC

**Comment by PhaseMage** [comment] 2021-11-21 22:01
Thanks for looking at this! You are right: C# should use 'byte' for P/Invoke when describing exported Zig functions in place of 'bool'.

Hopefully folks will find this issue if they run into problems with C# code P/Invoking into Zig code with boolean parameters or return values.

**Comment by alexrp** [comment] 2021-11-21 22:09
The correct answer is actually this, by the way:

```csharp
[DllImport("MyStruct.dll")]
[return: MarshalAs(UnmanagedType.U1)]
public static extern bool isAlive(UIntPtr ctx);
```

It's a common pitfall for people doing C interop in C#. The runtime's marshaling layer treats `bool` as the Win32 `BOOL` type by default for rather unfortunate historical reasons.

[More info here.](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1414)
