### ISSUE TITLE
Wrong error location on invalid `@as` coercion.

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#15047] opened 2023-03-22 13:19 UTC
### Zig Version

0.11.0-dev.1913+95f6a5935

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() !void {
	var x: usize = 0;
	var y: u32 = undefined;
	y = @as(u32, x);
}
```
Output:
```
$ zig run test.zig
test.zig:1:1: error: expected type 'u32', found 'usize'
pub fn main() !void {
^~~
```

### Expected Behavior

It should point to the right line, like it does when I remove the `@as`:
```
test.zig:4:6: error: expected type 'u32', found 'usize'
 y = x;
     ^
```

**Comment by Vexu** [comment] 2023-03-22 20:28
Duplicate of #14768

**Closed by Vexu** 2023-03-22 20:28 UTC
Labels: bug
