### ISSUE TITLE
zig build uninstall doesn't work

### ISSUE THREAD

**Issue by fprijate** [ziglang/zig#19491] opened 2024-03-30 10:12 UTC
### Zig Version

platform: Win10
0.12.0-dev.3496+a2df84d0f

### Steps to Reproduce Observed Behavior

run: 
**zig build uninstall**

### Expected Behavior

To reverse result of **zig build install**  (delete zig-out directory)

**Comment by fprijate** [comment] 2024-03-30 10:14
Platform: Win10

**Comment by Vexu** [comment] 2024-03-30 11:21
Related #14943

**Comment by andrewrk** [comment] 2024-08-16 07:00
duplicate of #14943

**Closed by andrewrk** 2024-08-16 07:00 UTC
Labels: bug
