### ISSUE TITLE
Rebuilding is broken

### ISSUE THREAD

**Issue by echoptic** [ziglang/zig#19415] opened 2024-03-24 06:26 UTC
### Zig Version

0.12.0-dev.3433+640acf862

### Steps to Reproduce and Observed Behavior

Running `zig build` works the first time when building a project, but when making some changes I get an error. The only way to make it compile again is to remove `zig-out` and `zig-cache` dirs. This was also a problem on yesterdays master.
```
install
└─ install json
   └─ zig build-exe json Debug native failure
error: the following command terminated unexpectedly:
/home/echoptic/zig/0.12.0-dev.3433+640acf862/files/zig build-exe -ODebug -Mroot=/home/echoptic/git/json/src/main.zig --cache-dir /home/echoptic/git/json/zig-cache --global-cache-dir /home/echoptic/.cache/zig --name json --listen=-
Build Summary: 2/5 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install json transitive failure
   └─ zig build-exe json Debug native failure
error: the following build command failed with exit code 1:
/home/echoptic/git/json/zig-cache/o/8d26201f6d1e968b47774713604b1635/build /home/echoptic/zig/0.12.0-dev.3433+640acf862/files/zig /home/echoptic/git/json /home/echoptic/git/json/zig-cache /home/echoptic/.cache/zig --seed 0xf4c6754d -Z107468181a87cd58
```

### Expected Behavior

Rebuilding a project should work without having to remove `zig-*` directories from it.

**Comment by squeek502** [comment] 2024-03-24 08:17
Duplicate of https://github.com/ziglang/zig/issues/19408

**Closed** 2024-03-24 08:17 UTC
Labels: bug
