### ISSUE TITLE
Proposal: translate-c should use typedef as type name if explicit name is missing

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#5347] opened 2020-05-15 14:30 UTC
This is a pretty common idiom in C:
```c
typdef enum { ... } CURLoption;
```

Current translation:
```zig
const enum_unnamed_17 = extern enum(c_int) { ... };
pub const CURLoption = enum_unnamed_17;
```

## Proposed change

We can detect a typedef + missing name and remove the need for a generated name:
```zig
pub const CURLoption = extern enum(c_int) { ... };
```

**Comment by Vexu** [comment] 2020-05-15 14:37
Duplicate of #4043

**Comment by FireFox317** [comment] 2020-05-15 14:37
Giving a bit more context why this caused confusion.

When an user tried to call `_  = c.curl_easy_setopt(curl, c.CURLOPT_URL, "http://example.com")` with an incorrect enumeration tag, the following error was printed:
```
./hello.zig:11:36: error: expected type '.cimport:4:11.enum_unnamed_17', found 'c_int'
```
From the error it is not clear that there is a `pub const CURLoption` that the user should use, instead of the `enum_unamed_17`, which is also non-public.

**Closed** 2020-05-15 14:37 UTC
