### ISSUE TITLE
symbol references suddenly have additional _ prefix

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#6766] opened 2020-10-22 07:34 UTC
Somechange changed between 21.10.2020 and 21.10.2020 which now yields the following errors on [cg-workbench](https://github.com/MasterQ32/cg-workbench) CI:

`zig build -Dtarget=x86_64-windows-gnu -Dstrip -Drelease-safe`:
```
lld: error: undefined symbol: __memset_chk
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/9e34ce3967a39fb707271173781f3685/imgui_draw.o:(ImFontAtlasBuildWithStbTruetype(ImFontAtlas*))
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/9e34ce3967a39fb707271173781f3685/imgui_draw.o:(ImFontAtlasBuildWithStbTruetype(ImFontAtlas*))

lld: error: undefined symbol: __memcpy_chk
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/24615589136e984d83eb3d23c55ae364/imgui_widgets.o:(DataTypeApplyOpFromText(char const*, char const*, int, void*, char const*))
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/24615589136e984d83eb3d23c55ae364/imgui_widgets.o:(ImGui::ColorPicker4(char const*, float*, int, float const*))
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/24615589136e984d83eb3d23c55ae364/imgui_widgets.o:(ImGui::ColorPickerOptionsPopup(float const*, int))
>>> referenced 8 more times
```

`zig build -Dtarget=i386-windows-gnu -Drelease-safe -Dstrip`:
```
lld: error: undefined symbol: ___memset_chk
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/37326e3cafe52db67ec37654f3242c9a/imgui_draw.o:(ImFontAtlasBuildWithStbTruetype(ImFontAtlas*))
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/37326e3cafe52db67ec37654f3242c9a/imgui_draw.o:(ImFontAtlasBuildWithStbTruetype(ImFontAtlas*))

lld: error: undefined symbol: ___memcpy_chk
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/11bbc70c08025ec7758db84c822a8bab/imgui_widgets.o:(DataTypeApplyOpFromText(char const*, char const*, int, void*, char const*))
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/11bbc70c08025ec7758db84c822a8bab/imgui_widgets.o:(ImGui::ColorPicker4(char const*, float*, int, float const*))
>>> referenced by /home/runner/work/cg-workbench/cg-workbench/zig-cache/o/11bbc70c08025ec7758db84c822a8bab/imgui_widgets.o:(ImGui::ColorPickerOptionsPopup(float const*, int))
>>> referenced 8 more times
```

It seems like symbols from normal c++ code suddenly have an additional `_` prefix which makes them no find the symbols from compiler_rt anymore

See the [full logs](https://github.com/MasterQ32/cg-workbench/runs/1290712153?check_suite_focus=true) for more details

**Comment by LemonBoy** [comment] 2020-10-22 08:32
WorksForMe, I've just finished building `cg-workbench` using this commandline `zig build -Dtarget=x86_64-windows-gnu --verbose-link -Dstrip -Drelease-safe`.
The `--verbose-link` is there to make sure `libssp` is linked in, if it's not there double-check the Zig compiler version.

> It seems like symbols from normal c++ code suddenly have an additional _ prefix which makes them no find the symbols from compiler_rt anymore

That's just Windows i386 name mangling weirdness.

**Comment by MasterQ32** [comment] 2020-10-22 09:25
> That's just Windows i386 name mangling weirdness.

I know, as you can see above, i386 symbols have three leading `_`, x86_64 symbols have two

> WorksForMe,

I can reproduce it locally with `0.6.0+e17297102` (which is current master build from the website)

**Comment by LemonBoy** [comment] 2020-10-22 10:06
> I know, as you can see above, i386 symbols have three leading _, x86_64 symbols have two

That looks ok to me, isn't it?

> I can reproduce it locally with 0.6.0+e17297102 (which is current master build from the website)

I can't reproduce the problem with a fresh build of master and a squeaky-clean zig cache. Try building with `--verbose-link` as I suggested before and check if libssp is built and if it's linked in the final executable.

**Comment by MasterQ32** [comment] 2020-10-22 11:36
Full output is this:
```
[felix@denkplatte-v2 cg-workbench]$ zig build -Dtarget=x86_64-windows-gnu -Dstrip -Drelease-safe --verbose-link 
lld -ERRORLIMIT:0 -NOLOGO -STACK:16777216 -MACHINE:X64 -OUT:/home/felix/projects/cg-workbench/zig-cache/o/c746bd4fa3c8d0322b4f36223ed45690/cg-workbench.exe /home/felix/projects/cg-workbench/zig-cache/o/3f8beafe19c59d19660ab365fa593bc0/nfd.lib /home/felix/projects/cg-workbench/lib/SDL2-2.0.12.mingw/x86_64-w64-mingw32/lib/libSDL2.a /home/felix/projects/cg-workbench/zig-cache/o/008bf7115e9410aac39e358cb83b9ba2/gl3w.o /home/felix/projects/cg-workbench/zig-cache/o/a1365b12ddab8e9545218413780a6eaa/imgui.o /home/felix/projects/cg-workbench/zig-cache/o/d17bb83891912ffab5f3c747d83e6dc5/imgui_demo.o /home/felix/projects/cg-workbench/zig-cache/o/9fcdc481f70aeeff0cf033a5a2a04c71/imgui_draw.o /home/felix/projects/cg-workbench/zig-cache/o/817a8a5b90409de9f1e4c00a35f0f38a/tiny_obj_loader.o /home/felix/projects/cg-workbench/zig-cache/o/df7860d2ed59e18770c01e3f55aac1ab/imgui_widgets.o /home/felix/projects/cg-workbench/zig-cache/o/3f8ca375bc6a7d4da67efeea42b94917/cgdatatype.o /home/felix/projects/cg-workbench/zig-cache/o/f7e8398b743dec743415b1eb3979a53e/imgui_impl.o /home/felix/projects/cg-workbench/zig-cache/o/c50117fbecc9acf9231cd91f34e39f7c/audiostream.o /home/felix/projects/cg-workbench/zig-cache/o/9a81a21a253c25192c014fc9a82a6e1c/event.o /home/felix/projects/cg-workbench/zig-cache/o/31d3bcf9add028808a36985207b4c2e5/fileio.o /home/felix/projects/cg-workbench/zig-cache/o/2521684eba7cfdc63bd1f42ede6617b6/geometry.o /home/felix/projects/cg-workbench/zig-cache/o/294eb3534084822d84db20a68f9b0bdf/imageloader.o /home/felix/projects/cg-workbench/zig-cache/o/a26edc4974ee04086f96e020da0cb771/resources.o /home/felix/projects/cg-workbench/zig-cache/o/fd3e5e50dbf1379b5ddb70e4ac8ac317/shaderprogram.o /home/felix/projects/cg-workbench/zig-cache/o/d7db78365793aa3e6a1405e696533e3a/sink.o /home/felix/projects/cg-workbench/zig-cache/o/e663ae4b828e9f2500088a44eb57520a/slot.o /home/felix/projects/cg-workbench/zig-cache/o/59655bf9b475b21714d252dc57d6184c/source.o /home/felix/projects/cg-workbench/zig-cache/o/bb8c56fe580aa909eb336031eb4d4e39/textureeditor.o /home/felix/projects/cg-workbench/zig-cache/o/cacd20861a3f514f6613aad5ddcf3e5b/time.o /home/felix/projects/cg-workbench/zig-cache/o/63c7d34e2932001153f43653c7734ac2/window.o /home/felix/projects/cg-workbench/zig-cache/o/4047f9547cce19678a8ebe371863e170/windowregistry.o /home/felix/projects/cg-workbench/zig-cache/o/c90c3b4c28e7f759743b09e86ed5fcd6/bpmnode.o /home/felix/projects/cg-workbench/zig-cache/o/4d93ccb8e522f9033c28a00df6ed0587/eventdelay.o /home/felix/projects/cg-workbench/zig-cache/o/dcacb3fd578609137dec4dd94e3c26be/trackernode.o /home/felix/projects/cg-workbench/zig-cache/o/6ab03e06772d4ef8289e7735e21674ed/trigger.o /home/felix/projects/cg-workbench/zig-cache/o/c2d421a02203f5222bf60091289fa850/shadereditor.o /home/felix/projects/cg-workbench/zig-cache/o/bd35f5b2d530d308b559e4e555603d01/gpuerrorlog.o /home/felix/projects/cg-workbench/zig-cache/o/99e6fa651da42b0a8bb6904d9b48cc6f/linearnoisenode.o /home/felix/projects/cg-workbench/zig-cache/o/21e436ceea1940782f8fba656e4f18c6/notewindow.o /home/felix/projects/cg-workbench/zig-cache/o/5dc9e5ea38b1591e46ef342e08c8bcb0/geometrywindow.o /home/felix/projects/cg-workbench/zig-cache/o/825091263e0935d21dd60d569729ea39/imagebuffer.o /home/felix/projects/cg-workbench/zig-cache/o/0c3a424e48faac214996cd56d14a5b6f/imagesource.o /home/felix/projects/cg-workbench/zig-cache/o/f8ad0a7171353d5091c8865175118727/renderwindow.o /home/felix/projects/cg-workbench/zig-cache/o/39ee43a531754aa74a9a8757382a67ec/arithmeticwindow.o /home/felix/projects/cg-workbench/zig-cache/o/7fc672c5eab917e02c19d6e9bd75f980/bufferwindow.o /home/felix/projects/cg-workbench/zig-cache/o/ff767c120e7f35360ecfa2e441b8a53b/colorwindow.o /home/felix/projects/cg-workbench/zig-cache/o/1cb3441cde2860216facbfcef913facc/graphwindow.o /home/felix/projects/cg-workbench/zig-cache/o/501ff1a8d05eaf798e9c21d6d53a0d97/matrixtransforms.o /home/felix/projects/cg-workbench/zig-cache/o/7e8754bfa4e2f976d7fb5015a24a5adb/timerwindow.o /home/felix/projects/cg-workbench/zig-cache/o/259798ca01f9f9761a2713c4dc511480/uniformwindow.o /home/felix/projects/cg-workbench/zig-cache/o/cb030b1e859e90a7a2bfe579360498bb/vectoradapter.o /home/felix/projects/cg-workbench/zig-cache/o/4235c58e13f74025bce9b81d81f7ac6c/main.o /home/felix/projects/cg-workbench/zig-cache/o/f61f773ffb74dd649e30d804496d3e2b/renderpassnode.o /home/felix/projects/cg-workbench/zig-cache/o/6842b9e6459c8b75fdc871ad441e5fd9/renderpass.o /home/felix/projects/cg-workbench/zig-cache/o/085eb472ff35117310c65877665035e1/utils.o /home/felix/projects/cg-workbench/zig-cache/o/34a8c475a1e98638ccc7467e190a90c5/eventcounter.o /home/felix/projects/cg-workbench/zig-cache/o/ef30ef2aa07fc0e48df671fe2451a8fc/edgedetector.o /home/felix/projects/cg-workbench/zig-cache/o/2836e52cb202dd914e2dec6c5c8c0d8f/pulsenode.o /home/felix/projects/cg-workbench/zig-cache/o/1961c29bae0eff33331784e36557e7ed/noisetexture.o /home/felix/projects/cg-workbench/zig-cache/o/73217b30c5982f610f6bc48fba01df21/audionode.o /home/felix/projects/cg-workbench/zig-cache/o/c746bd4fa3c8d0322b4f36223ed45690/cg-workbench.o -SUBSYSTEM:console -lldmingw -ALTERNATENAME:__image_base__=__ImageBase /home/felix/.cache/zig/o/b5ff45afe48079ddec89fa324edd1aef/crt2.o /home/felix/.cache/zig/o/f3f1619dbb21f3837dc63c9d14e259fa/mingw32.lib /home/felix/.cache/zig/o/bd3d992246cd05a5dc958e1fe6c9bd54/mingwex.lib /home/felix/.cache/zig/o/e4df42affc0c758e8085196482aad0ed/msvcrt-os.lib /home/felix/.cache/zig/o/d55118dc93ad70948ccfe2e618133c12/c++abi.lib /home/felix/.cache/zig/o/e18a70024a2597ba58c3c6a9756a2965/c++.lib /home/felix/.cache/zig/o/ccdf94fcbb4d5145aa641c67bf53b6da/unwind.lib /home/felix/.cache/zig/o/de1da1f59f590cfc7d5f3a5d6de9bfa5/compiler_rt.lib /home/felix/.cache/zig/o/6ce77cd0543eaa762906955e7ecbcb07/gdi32.lib /home/felix/.cache/zig/o/b3ca2d35e3f19a65984d3e3c31ccbeeb/kernel32.lib /home/felix/.cache/zig/o/7a259d5f18ec8644c7d9654e9dc9ccd3/ole32.lib /home/felix/.cache/zig/o/3f7ee32546decd9195732ba47931548a/oleaut32.lib /home/felix/.cache/zig/o/4faf0388b14f8a13792ee8cfe47d481f/opengl32.lib /home/felix/.cache/zig/o/f309a52b0d91d162dd240a39ff54091e/shell32.lib /home/felix/.cache/zig/o/cb862c9eeeb6920d496d43ff5a0b2065/shlwapi.lib /home/felix/.cache/zig/o/96815c12e68afbebb2f59bf4f54102c6/user32.lib /home/felix/.cache/zig/o/afc401c0e9eb7825ca07480cf9c0b46f/winmm.lib /home/felix/.cache/zig/o/1b99d0eb33d7b204dbc9cc6ad5d2cf7b/imm32.lib /home/felix/.cache/zig/o/dc71d445e93e25f54756bcd658c82f00/version.lib /home/felix/.cache/zig/o/40054a3a059e46179e6d0c5c804fc706/setupapi.lib /home/felix/.cache/zig/o/0d6d7e3853791e9e76a3c0142c7e1650/advapi32.lib /home/felix/.cache/zig/o/f42177dffad0b87a76e44190dc72b502/msvcrt.lib /home/felix/.cache/zig/o/8f6a7734deaa9dcf02d66893f5fb3459/ntdll.lib
lld: error: undefined symbol: __memset_chk
>>> referenced by /home/felix/projects/cg-workbench/zig-cache/o/9fcdc481f70aeeff0cf033a5a2a04c71/imgui_draw.o:(ImFontAtlasBuildWithStbTruetype(ImFontAtlas*))
>>> referenced by /home/felix/projects/cg-workbench/zig-cache/o/9fcdc481f70aeeff0cf033a5a2a04c71/imgui_draw.o:(ImFontAtlasBuildWithStbTruetype(ImFontAtlas*))

lld: error: undefined symbol: __memcpy_chk
>>> referenced by /home/felix/projects/cg-workbench/zig-cache/o/df7860d2ed59e18770c01e3f55aac1ab/imgui_widgets.o:(DataTypeApplyOpFromText(char const*, char const*, int, void*, char const*))
>>> referenced by /home/felix/projects/cg-workbench/zig-cache/o/df7860d2ed59e18770c01e3f55aac1ab/imgui_widgets.o:(ImGui::ColorPicker4(char const*, float*, int, float const*))
>>> referenced by /home/felix/projects/cg-workbench/zig-cache/o/df7860d2ed59e18770c01e3f55aac1ab/imgui_widgets.o:(ImGui::ColorPickerOptionsPopup(float const*, int))
>>> referenced 8 more times

lld: error: undefined symbol: __strcpy_chk
>>> referenced by /home/felix/projects/cg-workbench/zig-cache/o/31d3bcf9add028808a36985207b4c2e5/fileio.o:(FileIO::RemoveLastPathComponent(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))
>>> referenced by /home/felix/projects/cg-workbench/zig-cache/o/c2d421a02203f5222bf60091289fa850/shadereditor.o:(ShaderEditor::ShaderEditor())
>>> referenced by /home/felix/projects/cg-workbench/zig-cache/o/c2d421a02203f5222bf60091289fa850/shadereditor.o:(ShaderEditor::ShaderEditor())
>>> referenced 3 more times

lld: error: undefined symbol: __strncat_chk
>>> referenced by nfd.lib(nfd_win.o):(AddFiltersToDialog(IFileDialog*, char const*))
>>> referenced by nfd.lib(nfd_win.o):(AddFiltersToDialog(IFileDialog*, char const*))

lld: error: undefined symbol: __memmove_chk
>>> referenced by c++abi.lib(cxa_demangle.o):((anonymous namespace)::itanium_demangle::AbstractManglingParser<(anonymous namespace)::itanium_demangle::ManglingParser<(anonymous namespace)::DefaultAllocator>, (anonymous namespace)::DefaultAllocator>::parseEncoding())
>>> referenced by c++abi.lib(cxa_demangle.o):((anonymous namespace)::itanium_demangle::AbstractManglingParser<(anonymous namespace)::itanium_demangle::ManglingParser<(anonymous namespace)::DefaultAllocator>, (anonymous namespace)::DefaultAllocator>::parseTemplateArgs(bool))
error: LLDReportedFailure
cg-workbench...The following command exited with error code 1:
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/zig build-exe /home/felix/projects/cg-workbench/workbench/main.zig --library c --library c++ /home/felix/projects/cg-workbench/zig-cache/o/3f8beafe19c59d19660ab365fa593bc0/nfd.lib --library gdi32 --library kernel32 --library ole32 --library oleaut32 --library opengl32 --library shell32 --library shlwapi --library user32 --library winmm --library imm32 --library version --library setupapi /home/felix/projects/cg-workbench/lib/SDL2-2.0.12.mingw/x86_64-w64-mingw32/lib/libSDL2.a -cflags -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/ext/gl3w/gl3w.c -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/ext/imgui/imgui.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/ext/imgui/imgui_demo.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/ext/imgui/imgui_draw.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/ext/tinyobjloader/tiny_obj_loader.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/ext/imgui/imgui_widgets.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/cgdatatype.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/imgui_impl.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/audiostream.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/event.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/fileio.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/geometry.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/imageloader.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/resources.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/shaderprogram.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/sink.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/slot.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/source.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/textureeditor.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/time.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/window.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windowregistry.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/event/bpmnode.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/event/eventdelay.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/event/trackernode.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/event/trigger.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/graphic/shadereditor.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/graphic/gpuerrorlog.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/generic/linearnoisenode.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/generic/notewindow.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/graphic/geometrywindow.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/graphic/imagebuffer.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/graphic/imagesource.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/graphic/renderwindow.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/numeric/arithmeticwindow.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/numeric/bufferwindow.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/numeric/colorwindow.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/numeric/graphwindow.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/numeric/matrixtransforms.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/numeric/timerwindow.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/numeric/uniformwindow.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/numeric/vectoradapter.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/main.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/graphic/renderpassnode.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/renderpass.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/utils.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/event/eventcounter.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/event/edgedetector.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/event/pulsenode.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/windows/graphic/noisetexture.cpp -cflags -std=c++17 -fno-sanitize=undefined -- /home/felix/projects/cg-workbench/workbench/src/audionode.cpp --verbose-link --strip -OReleaseSafe --cache-dir /home/felix/projects/cg-workbench/zig-cache --name cg-workbench -target x86_64-windows-gnu -I /home/felix/projects/cg-workbench/lib/SDL2-2.0.12.mingw/x86_64-w64-mingw32/include/SDL2 -I /home/felix/projects/cg-workbench/workbench/src -I /home/felix/projects/cg-workbench/ext/gl3w -I /home/felix/projects/cg-workbench/ext/stb -I /home/felix/projects/cg-workbench/ext/imgui -I /home/felix/projects/cg-workbench/ext/json -I /home/felix/projects/cg-workbench/ext/nativefiledialog/src/include -I /home/felix/projects/cg-workbench/ext/tinyobjloader -I /home/felix/projects/cg-workbench/ext/tinydir -I /home/felix/projects/cg-workbench/ext/webcam-v4l2 -I /home/felix/projects/cg-workbench/ext/kiss_fft -I /home/felix/projects/cg-workbench/ext/kiss_fft/tools -I /home/felix/projects/cg-workbench/ext/rtmidi -I /home/felix/projects/cg-workbench/ext/glm-0.9.9.8 -D GLM_ENABLE_EXPERIMENTAL -D IMGUI_DISABLE_OBSOLETE_FUNCTIONS -D STB_VORBIS_HEADER_ONLY -D NOMINMAX -D WIN32_LEAN_AND_MEAN -D CGPLAT_WINDOWS -D WIN32 -D _CRT_SECURE_NO_WARNINGS -D DECLSPEC= --enable-cache 
error: the following build command failed with exit code 1:
/home/felix/projects/cg-workbench/zig-cache/o/2dcb2024c0873a3f5e49b7c21dcd2535/build /home/felix/software/zig-linux-x86_64-0.6.0+e17297102/zig /home/felix/projects/cg-workbench /home/felix/projects/cg-workbench/zig-cache -Dtarget=x86_64-windows-gnu -Dstrip -Drelease-safe --verbose-link
[felix@denkplatte-v2 cg-workbench]$ 
```

Looks like there is no `libssp` referenced in there

**Comment by LemonBoy** [comment] 2020-10-22 11:52
Oh well, that's where your problem is.
Try checking if the compiler tarball you've downloaded contains the `ssp.zig` file and, as last resort, try nuking all the zig caches.

**Comment by MasterQ32** [comment] 2020-10-22 12:29
```
[felix@denkplatte-v2 zig-current]$ find /home/felix/software/zig-linux-x86_64-0.6.0+e17297102 -iname "*ssp*"
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/musl/src/string/wcsspn.c
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/musl/src/ctype/isspace.c
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/qossp.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/sspserr.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/issperr.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/issper16.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/sspguid.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/credssp.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/ddk/classpnp.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/sspi.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/sspsidl.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libc/include/any-windows-any/scardssp.h
/home/felix/software/zig-linux-x86_64-0.6.0+e17297102/lib/zig/libunwind/src/AddressSpace.hpp
```
Looks like the official tarball doesn't contain `ssp.zig` and is thus not able to build cg-workbench. Has this changed in the course of the last 48h? The CI build was silent until this morning and the only thing changed was the tarball from the website

**Comment by LemonBoy** [comment] 2020-10-22 12:43
From what I can see `e17297102` was packaged on the 16 of October while `ssp.zig` landed the day after...

**Comment by MasterQ32** [comment] 2020-10-22 12:47
Okay, this could explain why the tar ball doesn't contain it right now… Looks like the issue is going to resolve itself over time

**Comment by andrewrk** [comment] 2020-10-26 03:05
the CI is not sophisticated to know if it is clobbering a newer build. so it's technically possible for an older CI run which is still running to somehow finish slower than a newer CI run. eventually the newer builds will land but it is pretty annoying when we get unlucky and it happens. I haven't tried to address it yet because it rarely happens and it's time consuming and hard to test a proper fix. And there's always the "wait until the next CI finishes" workaround, which happens almost every hour. Anyway there are all my excuses. Sorry about that.

**Comment by andrewrk** [comment] 2020-10-26 03:06
Closing because this appears to have been confusion about which master branch tarball was current. Please let me know if I misunderstood the situation and I'll reopen.

**Closed by andrewrk** 2020-10-26 03:06 UTC

**Comment by MasterQ32** [comment] 2020-10-26 08:05
Yeahs seems like it resolved "overnight". Everything fine on my end again
