### ISSUE TITLE
`zig cc -o` broken?

### ISSUE THREAD

**Issue by jedisct1** [ziglang/zig#6979] opened 2020-11-04 16:24 UTC
```sh
zig cc -o app app.c
```

```text
error: FileNotFound
```

`zig` doesn't get that `-o` requires a parameter and  is trying to open the nonexistent `app` file as if it were source code:

```text
openat(7, "app", O_RDONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by alexnask** [comment] 2020-11-05 07:19
I will take a look at this one soon : )  
Assigning it the 0.7.0 label since it's a pretty important thing for `zig cc` to have

**Comment by alexnask** [comment] 2020-11-05 13:53
I can't reproduce this on master

**Comment by jedisct1** [comment] 2020-11-05 14:29
100% reproducible here on macOS (Catalina):

```sh
$ zig version
0.6.0+17837affd
```

```sh
$ cat > a.c <<<EOT
#include <stdio.h>
int main(void){return 0;}
EOT

$ rm -f xyz
$ zig cc a.c -o xyz

attempt to unwrap error: FileNotFound
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/hash/wyhash.zig:126:52: 0x10c207fde in std.hash.wyhash.WyhashStateless.hash (zig1)
        const aligned_len = input.len - (input.len % 32);
                                                   ^
/Users/j/src/zig/lib/std/fs.zig:867:35: 0x10c0a8cbe in std.fs.Dir.createFileZ (zig1)
            (if (flags.exclusive) @as(u32, os.O_EXCL) else 0);
                                  ^
/Users/j/src/zig/lib/std/crypto/siphash.zig:220:65: 0x10c0a4a6b in std.crypto.siphash.SipHash(u128,1,3).final (zig1)
            mem.writeIntLittle(T, out, self.state.final(self.buf[0..self.buf_len]));
                                                                ^
/Users/j/src/zig/src/Compilation.zig:0:0: 0x10c141951 in Compilation.tmpFilePath (zig1)
/Users/j/src/zig/src/main.zig:1991:25: 0x10c0f6d9e in main.cmdTranslateC (zig1)
        return cleanExit();
                        ^
/Users/j/src/zig/src/main.zig:1704:17: 0x10c048d5c in main.buildOutputType (zig1)
                .print = comp.bin_file.options.emit.?.directory.path orelse ".",
                ^
/Users/j/src/zig/src/main.zig:163:37: 0x10c0211a4 in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .{ .build = .Obj });
                                    ^
/Users/j/src/zig/lib/std/fs.zig:962:27: 0x10c0af2f6 in std.fs.Dir.makePath (zig1)
                end_index += 1;
                          ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/io/reader.zig:188:50: 0x10c247082 in std.io.reader.Reader(*std.io.fixed_buffer_stream.FixedBufferStream([]const u8),std.io.fixed_buffer_stream.ReadError,std.io.fixed_buffer_stream.FixedBufferStream([]const u8).read).readByteSigned (zig1)
            return @bitCast(i8, try self.readByte());
                                                 ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/hash/wyhash.zig:126:52: 0x10c207fde in std.hash.wyhash.WyhashStateless.hash (zig1)
        const aligned_len = input.len - (input.len % 32);
                                                   ^
/Users/j/src/zig/lib/std/fs.zig:867:35: 0x10c0a8cbe in std.fs.Dir.createFileZ (zig1)
            (if (flags.exclusive) @as(u32, os.O_EXCL) else 0);
                                  ^
/Users/j/src/zig/lib/std/crypto/siphash.zig:220:65: 0x10c0a4a6b in std.crypto.siphash.SipHash(u128,1,3).final (zig1)
            mem.writeIntLittle(T, out, self.state.final(self.buf[0..self.buf_len]));
                                                                ^
/Users/j/src/zig/src/Cache.zig:459:35: 0x10c0d5108 in Cache.Manifest.addFilePost (zig1)
        assert(self.manifest_file != null);
                                  ^
/Users/j/src/zig/lib/std/fs/path.zig:896:22: 0x10c0d1fda in std.fs.path.basenamePosix (zig1)
        return &[_]u8{};
                     ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
/Users/j/src/zig/lib/std/io/reader.zig:188:50: 0x10c247082 in std.io.reader.Reader(*std.io.fixed_buffer_stream.FixedBufferStream([]const u8),std.io.fixed_buffer_stream.ReadError,std.io.fixed_buffer_stream.FixedBufferStream([]const u8).read).readByteSigned (zig1)
            return @bitCast(i8, try self.readByte());
                                                 ^
/Users/j/src/zig/lib/std/heap.zig:78:41: 0x10c01cfa9 in std.heap.cResize (zig1)
        const full_len = malloc_size(buf.ptr);
                                        ^
???:?:?: 0x10fd98a88 in ___zig_fail_unwrap (???)
/Users/j/src/zig/src/stage1.zig:28:0: 0x10c020980 in main (zig1)
pub export fn main(argc: c_int, argv: [*][*:0]u8) c_int {

???:?:?: 0x7fff6ccdacc8 in ??? (???)
???:?:?: 0x4 in ??? (???)
[1]    6328 abort      zig cc a.c -o xyz
```

**Comment by jedisct1** [comment] 2020-11-05 14:33
Mmm... looks like some kind of memory corruption...

This is on Linux/aarch64:

```sh
$ rm -f xyz
$ zig cc a.c -o xyz

-> fine!
```

```sh
$ rm -f xyzzy
$ zig cc a.c -o xyzz

attempt to unwrap error: FileNotFound
/home/j/src/zig/lib/std/fs.zig:1779:24: 0xaaaae0c56ebf in std.fs.Dir.updateFile (zig1)
        var src_file = try source_dir.openFile(source_path, .{});
                       ^
/home/j/src/zig/src/main.zig:1855:36: 0xaaaae0c12b43 in main.updateModule (zig1)
        .update => |full_path| _ = try comp.bin_file.options.emit.?.directory.handle.updateFile(
                                   ^
/home/j/src/zig/src/main.zig:1710:5: 0xaaaae0b6ec73 in main.buildOutputType (zig1)
    try updateModule(gpa, comp, zir_out_path, hook);
    ^
/home/j/src/zig/src/main.zig:169:9: 0xaaaae0b48e1b in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .cc);
        ^
/home/j/src/zig/lib/std/fs.zig:923:9: 0xaaaae0bd2ae7 in std.fs.Dir.makeDir (zig1)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/j/src/zig/lib/std/os.zig:2125:19: 0xaaaae0bd2daf in std.os.mkdiratZ (zig1)
        EEXIST => return error.PathAlreadyExists,
                  ^
/home/j/src/zig/lib/std/os.zig:2086:9: 0xaaaae0bd2c2f in std.os.mkdirat (zig1)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/j/src/zig/lib/std/fs.zig:923:9: 0xaaaae0bd2ae7 in std.fs.Dir.makeDir (zig1)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/mem/Allocator.zig:319:16: 0xaaaae0d39877 in std.mem.Allocator.resize (zig1)
    const rc = try self.resizeFn(self, old_byte_slice, Slice.alignment, new_byte_count, 0, @returnAddress());
               ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/os.zig:1196:23: 0xaaaae0d0c07b in std.os.openatZ (zig1)
            ENOENT => return error.FileNotFound,
                      ^
/home/j/src/zig/lib/std/fs.zig:754:13: 0xaaaae0bcb507 in std.fs.Dir.openFileZ (zig1)
            try os.openatZ(self.fd, sub_path, os_flags, 0);
            ^
/home/j/src/zig/lib/std/fs.zig:687:9: 0xaaaae0bc7327 in std.fs.Dir.openFile (zig1)
        return self.openFileZ(&path_c, flags);
        ^
/home/j/src/zig/lib/std/fs.zig:1527:20: 0xaaaae0bf5ccb in std.fs.Dir.readFileAllocOptions (zig1)
        var file = try self.openFile(file_path, .{});
                   ^
/home/j/src/zig/lib/std/fs.zig:1510:9: 0xaaaae0bf317f in std.fs.Dir.readFileAlloc (zig1)
        return self.readFileAllocOptions(allocator, file_path, max_bytes, null, @alignOf(u8), null);
        ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/mem/Allocator.zig:319:16: 0xaaaae0d39877 in std.mem.Allocator.resize (zig1)
    const rc = try self.resizeFn(self, old_byte_slice, Slice.alignment, new_byte_count, 0, @returnAddress());
               ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/heap.zig:83:5: 0xaaaae0b45f4b in std.heap.cResize (zig1)
    return error.OutOfMemory;
    ^
/home/j/src/zig/lib/std/os.zig:1196:23: 0xaaaae0d0c07b in std.os.openatZ (zig1)
            ENOENT => return error.FileNotFound,
                      ^
/home/j/src/zig/lib/std/fs.zig:754:13: 0xaaaae0bcb507 in std.fs.Dir.openFileZ (zig1)
            try os.openatZ(self.fd, sub_path, os_flags, 0);
            ^
/home/j/src/zig/lib/std/fs.zig:687:9: 0xaaaae0bc7327 in std.fs.Dir.openFile (zig1)
        return self.openFileZ(&path_c, flags);
        ^
???:?:?: 0xaaaae0b49b1f in ??? (???)
/home/j/src/zig/src/stage1.zig:45:43: 0xaaaae0b486d3 in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                                          ^
???:?:?: 0xffffa243d877 in ??? (???)
???:?:?: 0xaaaae0b459cb in ??? (???)
Aborted (core dumped)
```

**Comment by jedisct1** [comment] 2020-11-05 14:35
If `zig-cache` doesn't exist yet, any output name will work.

Then, now that a cache exists, trying to use `zig cc` with a different output name fails.

**Comment by alexnask** [comment] 2020-11-09 11:56
More generally, this bug happens when `enable_cache` is on (which it is by default for executable outputs of `zig cc`)  
The `linkWithLLD` functions will compute the cache hash, find that there was no update and return, and the post-compile hook will try to copy the linked output from the new path that does not exist.  

Possible fixes are adding the linker output basename to the cache hash (which doesn't make much sense) or storing the linker output basename in the `lld.id` symlink and using it when we detect no change in the cache hash.

**Closed** 2020-12-01 23:36 UTC
Labels: bug, zig cc
