### ISSUE TITLE
`root struct of file 'S' has no member named 'foo'` error missing note with link to file

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#17074] opened 2023-09-05 01:00 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() void {
    _ = S.foo;
}

const S = @import("S.zig");
```

+ `S.zig` exists but is empty

```
test2.zig:2:10: error: root struct of file 'S' has no member named 'foo'
    _ = S.foo;
        ~^~~~
referenced by:
    callMain: /home/meghan/.local/share/zig/lib/std/start.zig:564:17
    initEventLoopAndCallMain: /home/meghan/.local/share/zig/lib/std/start.zig:508:34
    callMainWithArgs: /home/meghan/.local/share/zig/lib/std/start.zig:458:12
    posixCallMainAndExit: /home/meghan/.local/share/zig/lib/std/start.zig:414:39
    _start: /home/meghan/.local/share/zig/lib/std/start.zig:327:40
```

### Expected Behavior

an extra note `struct defined here` note pointing to `S.zig:1:1:`

**Comment by WillLillis** [comment] 2024-07-18 06:12
This should've been closed as completed when #17163 was merged, no?

**Closed** 2024-07-18 06:28 UTC
Labels: error message

**Comment by jonasdiemer** [comment] 2024-09-02 12:32
Hi,

I have encountered a very similar problem.

Problem occurs here: https://github.com/mattfreire/zig-llm/commit/02836e22327565e0f5d4d4989d773c9ddba9c79f

To reproduce, run `zig build run` in `example` directory. 

Output:
```
run
└─ run example
   └─ zig build-exe example Debug native 1 errors
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/fmt.zig:632:21: error: cannot format slice without a specifier (i.e. {s} or {any})
                    @compileError("cannot format slice without a specifier (i.e. {s} or {any})");
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    format__anon_9848: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/fmt.zig:185:23
    print__anon_5772: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/io/Writer.zig:24:26
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

Reverting the latest commit (i.e. switching back to `"{any}"` fixes the issue) - but the problem is that zig is not pointing to the offending problem in the code.

Please let me know if this should be a new ticket.
