### ISSUE TITLE
Building PostgreSQL C Extension with Ziglang : libmathtest.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ranjanprj** [ziglang/zig#3617] opened 2019-11-06 19:41 UTC
This is a great project and I'm very excited about this. My interest lies in building high perf PostgreSQL extensions with Ziglang. Here is my workflow

1. Compile mathtest.zig as shared dynamic library
2. Embed the add function in C file for postgresql
3. Compile using Makefile for Postgresql 
4. Try to execute the file

Steps
1. mathtest.zig 
```zig
export fn add(a: i32, b: i32) i32 {
    return a + b;
}
```
2. `zig build-lib mathtest.zig`

3. funcs.c
```C
#include "postgres.h"
#include <string.h>
#include "fmgr.h"
#include "utils/geo_decls.h"
#include "mathtest.h"
#ifdef PG_MODULE_MAGIC
PG_MODULE_MAGIC;
#endif

/* by value */

PG_FUNCTION_INFO_V1(add_one);

Datum
add_one(PG_FUNCTION_ARGS)
{
    int32   arg = PG_GETARG_INT32(0);

    PG_RETURN_INT32(add(arg,arg));
}
```

4. Makefile
```
MODULES = funcs

PG_CONFIG = pg_config
PGXS = $(shell $(PG_CONFIG) --pgxs)
INCLUDEDIR = $(shell $(PG_CONFIG) --includedir-server)
include $(PGXS)


funcs.so: funcs.o
        cc  -shared -o funcs.so funcs.o /home/ranjanprj/zig/libmathtest.so.0.0.0

funcs.o: funcs.c
        cc -o funcs.o -c funcs.c $(CFLAGS) -I$(INCLUDEDIR)
```
5. `sudo make && sudo make install`
6. In postgresql create the extension
```sql
drop function if exists add_zig(integer);

CREATE or replace FUNCTION add_zig(integer) RETURNS integer
     AS '/home/ranjanprj/zig/funcs.so', 'add_one'
     LANGUAGE C STRICT;
```

7. ERROR
```sql
drop function if exists add_zig(integer);

CREATE or replace FUNCTION add_zig(integer) RETURNS integer
     AS '/home/ranjanprj/zig/funcs.so', 'add_one'
     LANGUAGE C STRICT;
```

8. Apparently it copies libmathtest.so.0 in /usr/lib/postgresql/11/lib directory, I tried to change the name in my current directory of libmathtest.so.0.0.0 to libmathtest.so.0 but it still didn't work
neither did copying  libmathtest.so.0.0.0 to /usr/lib/postgresql/11/lib directory work.

Please note that same workflow works fine with rustlang shared lib by just replacing the .so file path in Makefile

Any help appreciated !

**Comment by daurnimator** [comment] 2019-11-06 23:11
I think this is a dupe of #2230 and #2231?

See also #3462

**Comment by ranjanprj** [comment] 2019-11-07 07:15
> I think this is a dupe of #2230 and #2231?
> 
> See also #3462

Yes, I think I was looking for a way to skip the versioning generation stuff, is there a way that it can be skipped ?  It would be cool we could build high perf extensions to PostgreSQL using Ziglang, as it has the right properties exactly for this use case.

**Comment by andrewrk** [comment] 2019-11-27 00:12
OK looks like this is a dupe of  #2230 and #2231, both of which have been accepted, and are contributor friendly issues.

**Closed by andrewrk** 2019-11-27 00:12 UTC

**Comment by carwyn** [comment] 2024-03-23 09:16
May be of interest for those interested in using Zig for PostgreSQL extensions: https://github.com/xataio/pgzx
