### ISSUE TITLE
Cannot compile the dynamic library targets for x86-linux and x86-windows

### ISSUE THREAD

**Issue by gaogaogoo** [ziglang/zig#21136] opened 2024-08-19 09:11 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Output

Executing the following command will result in a compilation error:

```
mkdir abc
cd abc
zig init
zig build-lib .\src\root.zig -dynamic -target x86-linux
zig build-lib .\src\root.zig -dynamic -target x86-windows
```

### Expected Output

Error for target x86-linux:
```
error: ld.lld: relocation R_386_PC32 cannot be used against symbol '__udivmoddi4'; recompile with -fPIC
    note: defined in C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a(C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o)
    note: referenced by int.zig:139 (D:\Users\cheney\.zvm\0.13.0\lib\compiler_rt/int.zig:139)
    note:               C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o:(__divmoddi4) in archive C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a
error: ld.lld: relocation R_386_PC32 cannot be used against symbol '__udivmoddi4'; recompile with -fPIC
    note: defined in C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a(C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o)
    note: referenced by int.zig:139 (D:\Users\cheney\.zvm\0.13.0\lib\compiler_rt/int.zig:139)
    note:               C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o:(__divdi3) in archive C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a
error: ld.lld: relocation R_386_PC32 cannot be used against symbol '__udivmoddi4'; recompile with -fPIC
    note: defined in C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a(C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o)
    note: referenced by int.zig:208 (D:\Users\cheney\.zvm\0.13.0\lib\compiler_rt/int.zig:208)
    note:               C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o:(__udivdi3) in archive C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a
error: ld.lld: relocation R_386_PC32 cannot be used against symbol '__udivmoddi4'; recompile with -fPIC
    note: defined in C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a(C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o)
    note: referenced by int.zig:175 (D:\Users\cheney\.zvm\0.13.0\lib\compiler_rt/int.zig:175)
    note:               C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o:(__moddi3) in archive C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a
error: ld.lld: relocation R_386_PC32 cannot be used against symbol '__udivmoddi4'; recompile with -fPIC
    note: defined in C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a(C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o)
    note: referenced by int.zig:213 (D:\Users\cheney\.zvm\0.13.0\lib\compiler_rt/int.zig:213)
    note:               C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o:(__umoddi3) in archive C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a
error: ld.lld: relocation R_386_PC32 cannot be used against symbol '__divsf3'; recompile with -fPIC
    note: defined in C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a(C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o)
    note: referenced by divhf3.zig:10 (D:\Users\cheney\.zvm\0.13.0\lib\compiler_rt/divhf3.zig:10)
    note:               C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o:(__divhf3) in archive C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a
error: ld.lld: relocation R_386_PC32 cannot be used against symbol '__multf3'; recompile with -fPIC
    note: defined in C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a(C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o)
    note: referenced by powiXf2.zig:29 (D:\Users\cheney\.zvm\0.13.0\lib\compiler_rt/powiXf2.zig:29)
    note:               C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a.o:(__powitf2) in archive C:\Users\cheney\AppData\Local\zig\o\52f9273cf5d510b947bb054d4d28a08b\libcompiler_rt.a
```

Error for target x86-windows:
```
error: lld-link: <root>: undefined symbol: _DllMainCRTStartup@12
error: lld-link: <root>: undefined symbol: add
error: lld-link: <root>: undefined symbol: _tls_index
error: lld-link: <root>: undefined symbol: _tls_start
error: lld-link: <root>: undefined symbol: _tls_end
error: lld-link: <root>: undefined symbol: __xl_a
error: lld-link: <root>: undefined symbol: __xl_z
error: lld-link: <root>: undefined symbol: _tls_used
```

**Comment by MeerMusik** [comment] 2024-08-23 13:55
Interesting. Tried with the latest published nightly ``0.14.0-dev.1261+c26206112`` and dynamic compilation for 32-Bit is still broken.

I am still a Zig Beginner but following everything Zig since around 4 Months before the 0.11.0 Release, I think this could be part of the general Mess that is 32-Bit Support in Zig. Which is broken since at least 2016 as far as I can tell.

Personally, I do not count on it ever getting fixed - even though Tier 1 Support is currently on the 0.14 Milestone, other required work is set for 0.15, 0.16 etc. and the Zig Devs keep moving things around or closing Issues permanently. Which is fine in itself. Just do not rely on Zig ever getting full 32-Bit Support as of right now. Or ever.

I am not saying the Devs are lying or misleading but as everything is still in heavy flux, everything is possible.

32-Bit is old-ish at this point and the Zig Devs remove support for Operating Systems, Platforms, Architectures etc. shortly after they became obsolete. Here are the Zig Issues:
* 32-Bit Linux: https://github.com/ziglang/zig/issues/1929
* 32-Bit Windows: https://github.com/ziglang/zig/issues/537

*fingers crossed for at least working basic 32-Bit support in the future*

**Comment by gaogaogoo** [comment] 2024-08-23 16:42
> Interesting. Tried with the latest published nightly `0.14.0-dev.1261+c26206112` and dynamic compilation for 32-Bit is still broken.
> 
> I am still a Zig Beginner but following everything Zig since around 4 Months before the 0.11.0 Release, I think this could be part of the general Mess that is 32-Bit Support in Zig. Which is broken since at least 2016 as far as I can tell.
> 
> Personally, I do not count on it ever getting fixed - even though Tier 1 Support is currently on the 0.14 Milestone, other required work is set for 0.15, 0.16 etc. and the Zig Devs keep moving things around or closing Issues permanently. Which is fine in itself. Just do not rely on Zig ever getting full 32-Bit Support as of right now. Or ever.
> 
> I am not saying the Devs are lying or misleading but as everything is still in heavy flux, everything is possible.
> 
> 32-Bit is old-ish at this point and the Zig Devs remove support for Operating Systems, Platforms, Architectures etc. shortly after they became obsolete. Here are the Zig Issues:
> 
> * 32-Bit Linux: [Tier 1 Support for Linux i386 #1929](https://github.com/ziglang/zig/issues/1929)
> * 32-Bit Windows: [Tier 1 support for 32 bit windows (i386-windows target) #537](https://github.com/ziglang/zig/issues/537)
> 
> _fingers crossed for at least working basic 32-Bit support in the future_

Thank you for your reply. I started following Zig from version 0.12 and began actively using it with version 0.13. I really like Zig’s simple syntax and comptime; it’s definitely more comfortable to write in compared to Rust.

I previously used Rust to write some dynamic libraries for hooking 32-bit games, and I wanted to rewrite them in Zig. However, encountering this issue has forced me to return to Rust development. I hope that in the future, Zig will support 32-bit architecture and Intel syntax for ASM, as these are the two features I most need right now.

**Comment by alexrp** [comment] 2024-08-31 19:29
> and the Zig Devs remove support for Operating Systems, Platforms, Architectures etc. shortly after they became obsolete.

Just to be clear, that is not accurate. Just recently, there was a whole debate about *Windows XP support* where the conclusion was ultimately that we're fine with taking non-invasive patches to keep it working.

Also, it is explicitly a goal of Zig to support all hardware that has users, no matter how old.

**Comment by alexrp** [comment] 2024-08-31 19:39
In regards to the bug itself:

* The `x86-windows` issue is tracked in https://github.com/ziglang/zig/issues/11817.
* The `x86-linux` issue interestingly only happens with `-ODebug` and `-OReleaseSafe`.

**Comment by alexrp** [comment] 2024-08-31 20:22
Actually, the `x86-linux` part is a duplicate of https://github.com/ziglang/zig/issues/19342.

**Comment by alexrp** [comment] 2024-10-02 21:31
Closing since this appears to be a duplicate of #11817 and #19342.

**Closed by alexrp** 2024-10-02 21:31 UTC
Labels: error message
