### ISSUE TITLE
file.writeAll fails on linux "reached unreachable code"

### ISSUE THREAD

**Issue by Algo-ryth-mix** [ziglang/zig#5967] opened 2020-08-01 16:10 UTC
I am trying a program straight from the main page
```
const std = @import("std");

pub fn main() !void {
    const file = std.fs.cwd().openFile("test.txt",.{}) catch |err| label: {
        std.debug.warn("Unable to open file: {}\n", .{err});
        const stderr = std.io.getStdErr();
        break :label stderr;
    };
    try file.writeAll("all your codebase are belong to us \n");
}
```

only that I created a file called `test.txt` to see if it did the right thing if the file existed.
but instead of getting a file with the line "all your codebase are belong to us" I got this from my terminal:
```
$ zig run src/main.zig
reached unreachable code
/usr/lib/zig/std/os.zig:739:22: 0x2060a0 in std.os.write (run)
            EBADF => unreachable, // Always a race condition.
                     ^
/usr/lib/zig/std/fs/file.zig:505:28: 0x205f3d in std.fs.file.File.write (run)
            return os.write(self.handle, bytes);
                           ^
/usr/lib/zig/std/fs/file.zig:512:36: 0x236a4a in std.fs.file.File.writeAll (run)
            index += try self.write(bytes[index..]);
                                   ^
/home/algo-ryth-mix/repos/zig-helloworld/src/main.zig:9:22: 0x22eec0 in main (run)
    try file.writeAll("all your codebase are belong to us \n");
                     ^
/usr/lib/zig/std/start.zig:252:37: 0x204c5d in std.start.posixCallMainAndExit (run)
            const result = root.main() catch |err| {
                                    ^
/usr/lib/zig/std/start.zig:123:5: 0x20499f in std.start._start (run)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
[1]    46540 abort (core dumped)  zig run src/main.zig
```
as far as I can tell I am using the latest version of zig
```
$ zig version
0.6.0+0962cc5a3
```
this happens for x86_64 linux on pop-os
```
$ uname -a
Linux pop-os 5.4.0-7634-generic #38~1595345317~20.04~a8480ad-Ubuntu SMP Wed Jul 22 15:13:45 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

I am terribly sorry if I did something wrong, but I would assume the listings on ziglang.org to work, (even when they are meant to show off what a program does in the case of a missing file).

**Comment by Vexu** [comment] 2020-08-01 18:08
`EBADFD` on write means the file descriptor is invalid or the file is not open for writing. You need to add `.{ .write = true }` to your `openFile` call.

Duplicate of #3880.

**Closed by Vexu** 2020-08-01 18:08 UTC
