### ISSUE TITLE
0.8.1 tests fail to pass (Archlinux chroot build)

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#9784] opened 2021-09-16 14:54 UTC
As mentioned on Discord+IRC; trying to run the tests of the 0.8.1 release I get failures such as:
```
error: FileNotFound
The following command exited with error code 1:
/build/zig/src/zig-0.8.1/build/zig test /build/zig/src/zig-0.8.1/test/behavior.zig -lc --test-name-prefix behavior-i386-linux-gnu-Debug-c-multi  --cache-dir /build/zig/src/zig-0.8.1/zig-cache --global-cache-dir /build/.cache/zig --name test -target i386-linux-gnu -I /build/zig/src/zig-0.8.1/test --override-lib-dir /build/zig/src/zig-0.8.1/lib 
error: the following build command failed with exit code 1:
/build/zig/src/zig-0.8.1/zig-cache/o/dc7b6d21072c65add91e318ccd570c7e/build /build/zig/src/zig-0.8.1/build/zig /build/zig/src/zig-0.8.1 /build/zig/src/zig-0.8.1/zig-cache /build/.cache/zig test
```

[full build log](https://github.com/ziglang/zig/files/7178823/build.log)

**Comment by AliChraghi** [comment] 2021-09-16 15:27
Are you sure you did not do a weird thing during the installation?
May Reinstalling Arch solve it? I use arch btw

**Comment by matu3ba** [comment] 2021-09-16 17:32
This should be a duplicate of #9378 and I think it is both a build and linker bug.

**Comment by ifreund** [comment] 2021-09-16 17:40
@matu3ba I think you may have linked the wrong issue? That PR seems unrelated...

**Comment by AliChraghi** [comment] 2021-09-16 17:43
yes it's [issue](https://github.com/ziglang/zig/issues/9738)

**Comment by mikdusan** [comment] 2021-09-16 21:56
- can confirm the test/target combination succeeds on my vm with package `lib32-glibc` installed
- and after `pacman -R lib32-glibc` it fails with `error: FileNotFound`

looks like that's the error when `/lib/ld-linux.so.2` is missing for i386 executable

**Comment by matu3ba** [comment] 2021-09-17 07:24
I can confirm the behavior for current master of commit 6d37ae95edc06f15e4e77f64e8e637dd5d269183.

For reproducing I did the following steps:
```sh
git clone --depth 1 https://github.com/ziglang/zig-bootstrap
cd zig-bootstrap
rm -fr zig
git clone --depth 1 https://github.com/ziglang/zig
./build -j7 x86_64-linux-gnu native
cd zig
../out/zig-x86_64-linux-gnu-native/bin/zig build test
```

Is lib32-glibc not part of glibc, which can be build lazily for every release? It would be nice to have an error message rather than silent failure.
Does anyone know rough explanations of how the build system of zig works?

**Comment by daurnimator** [comment] 2021-09-17 14:22
I've worked around it for now by adding a testing dependency of `lib32-glibc`, but I think there *is* an underlying bug in either `zig build` or `zig test`, where it tries to run the cross target natively despite the architecture not matching.
Possibly this TODO in `cross_target.zig`?
```zig
        // TODO additionally match the CPU features. This `getExternalExecutor` function should
        // be moved to std.Target and match any chosen target against the native target.
```

**Closed** 2021-09-17 14:23 UTC
