### ISSUE TITLE
Unreachable code in zig-0.5.0

### ISSUE THREAD

**Issue by DonRyuDragoni** [ziglang/zig#3415] opened 2019-10-09 14:06 UTC
Attempting to compile [my mandelbrot generator](https://gitlab.com/DonRyuDragoni/mandelbrotgen/tree/zig-sdl2) (which worked fine under zig-0.4.0) in zig-0.5.0, generates this error:

```
[2019-10-09 10:32:40 ryu@Andromeda] mandelbrotgen [git zig-sdl2] 
$ zig5 build      
reached unreachable code
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/build.zig:1841:21: 0x245703 in std.build.LibExeObjStep.linkSystemLibrary (build)
            else => unreachable,
                    ^
/home/ryu/Programming/tmp/mandelbrotgen/build.zig:9:26: 0x23e035 in std.special.build (build)
    exe.linkSystemLibrary("SDL2");
                         ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/special/build_runner.zig:140:28: 0x235574 in runBuild (build)
        .Void => root.build(builder),
                           ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/special/build_runner.zig:122:17: 0x232b71 in main (build)
    try runBuild(builder);
                ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/special/start.zig:204:37: 0x2308e5 in std.special.posixCallMainAndExit (build)
            const result = root.main() catch |err| {
                                    ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/special/start.zig:102:5: 0x23075f in std.special._start (build)
    @noInlineCall(posixCallMainAndExit);
    ^

Build failed. The following command failed:
/home/ryu/Programming/tmp/mandelbrotgen/zig-cache/o/OGDylCMRJ3rXBsMAr7EkYe1RjJduCKpSCue_b3az645A8ATGA2NLRZon47Pq0trg/build /home/ryu/Downloads/programs/zig/zig-0.5.0/zig /home/ryu/Programming/tmp/mandelbrotgen /home/ryu/Programming/tmp/mandelbrotgen/zig-cache
[2019-10-09 10:32:45 ryu@Andromeda] mandelbrotgen [git zig-sdl2] 
$ 
```

Editing [this line](https://github.com/ziglang/zig/blob/master/lib/std/build.zig#L1849) to say `else => {}` removes this error, though the program won't compile because my code wasn't adapted to 0.5.0 yet. I then tried to use [my `build.zig`](https://gitlab.com/DonRyuDragoni/mandelbrotgen/blob/zig-sdl2/build.zig) file to compile the [sdl demo](https://github.com/andrewrk/sdl-zig-demo), though, and the results were the same before and after editing that line.

I have a feeling that this is a horrible solution, though.

**Comment by danielabbott** [comment] 2019-10-09 15:16
I downloaded your project and don't get any error in the build script - the first error is in main.zig and is about DirectAllocator being private. This is with 0.5.0. Building the SDL demo I get a different error about not finding the addCommand function (which doesn't seem to exist in 0.5.0).

**Comment by andrewrk** [comment] 2019-10-09 16:04
@DonRyuDragoni The error output you're getting is missing the error return trace, and is not as helpful as it should be. I filed #3418 for this.

As a workaround, can you try this patch?

```diff
--- a/lib/std/build.zig
+++ b/lib/std/build.zig
@@ -1846,7 +1846,7 @@ pub const LibExeObjStep = struct {
             error.PackageNotFound,
             => {},
 
-            else => unreachable,
+            else => err catch unreachable,
         }
 
         self.linkSystemLibraryName(name);
```

This will then cause the error output above to include an error return trace, which will hopefully take us to the next step of debugging this. This regression seems to be caused by the new feature of zig build integrating with pkg-config, which ultimately should be helpful, but maybe there is a little bug that needs to be fixed.

Thanks for your time.

**Comment by DonRyuDragoni** [comment] 2019-10-09 16:41
> the first error is in main.zig and is about DirectAllocator being private

That's the error I'm expecting to get too, but it isn't happening here. Also, I just realized that I forgot to mention that I'm running Antergos, that may be relevant.

> As a workaround, can you try this patch?

Sure thing, here's the new output:

```
[2019-10-09 13:30:59 ryu@Andromeda] mandelbrotgen [git zig-sdl2] 
$ zig5 build
attempt to unwrap error: StreamTooLong
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/io/in_stream.zig:82:53: 0x24d1e5 in std.io.in_stream.InStream(std.os.ReadError).readAllBuffer (build)
                if (new_buf_size == actual_buf_len) return error.StreamTooLong;
                                                    ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/build.zig:870:9: 0x24c208 in std.build.Builder.execAllowFail (build)
        try stdout_file_in_stream.stream.readAllBuffer(&stdout, max_output_size);
        ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/build.zig:933:24: 0x24c80c in std.build.Builder.execPkgConfigList (build)
        const stdout = try self.execAllowFail([_][]const u8{ "pkg-config", "--list-all" }, out_code, .Ignore);
                       ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/build.zig:961:25: 0x24be2c in std.build.Builder.getPkgConfigList (build)
                else => return err,
                        ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/build.zig:1744:26: 0x24865e in std.build.LibExeObjStep.linkSystemLibraryPkgConfigOnly (build)
            const pkgs = try self.builder.getPkgConfigList();
                         ^
???:?:?: 0x23bdbc in ??? (???)


/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/build.zig:1841:42: 0x24574a in std.build.LibExeObjStep.linkSystemLibrary (build)
            else => (anyerror!void)(err) catch unreachable,
                                         ^
/home/ryu/Programming/tmp/mandelbrotgen/build.zig:9:26: 0x23e035 in std.special.build (build)
    exe.linkSystemLibrary("SDL2");
                         ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/special/build_runner.zig:140:28: 0x235574 in runBuild (build)
        .Void => root.build(builder),
                           ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/special/build_runner.zig:122:17: 0x232b71 in main (build)
    try runBuild(builder);
                ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/special/start.zig:204:37: 0x2308e5 in std.special.posixCallMainAndExit (build)
            const result = root.main() catch |err| {
                                    ^
/home/ryu/Downloads/programs/zig/zig-0.5.0/lib/zig/std/special/start.zig:102:5: 0x23075f in std.special._start (build)
    @noInlineCall(posixCallMainAndExit);
    ^

Build failed. The following command failed:
/home/ryu/Programming/tmp/mandelbrotgen/zig-cache/o/RwqvAPZE9keVKr85-c1TUsPR2D7hB5cRrow00U5wxktdIUh2nj6GfQpb_eI62Eyb/build /home/ryu/Downloads/programs/zig/zig-0.5.0/zig /home/ryu/Programming/tmp/mandelbrotgen /home/ryu/Programming/tmp/mandelbrotgen/zig-cache
[2019-10-09 13:31:05 ryu@Andromeda] mandelbrotgen [git zig-sdl2] 
$ 
```

**Comment by andrewrk** [comment] 2019-10-09 17:46
OK thanks, that does indeed explain the problem! 

The pkg-config integration code is using this:

https://github.com/ziglang/zig/blob/2286003666e8216d809b30e164963a52cdb2d4f8/lib/std/build.zig#L856

And your `pkg-config --list-all` output is more than 100KB, which is actually pretty reasonable. I think we can safely bump this limit to be higher. Can you do me a favor and run this on your system, just to collect one data point?

```
pkg-config --list-all | wc -c
```

That will tell us how many bytes this is on your system, at least, which might inform the new limit to set.

**Comment by DonRyuDragoni** [comment] 2019-10-09 19:19
No problem, here it is:

```
[2019-10-09 16:10:41 ryu@Andromeda] ryu 
$ pkg-config --list-all | wc -c
105813
[2019-10-09 16:10:42 ryu@Andromeda] ryu 
$ 
```

Just slightly bigger.

**Comment by andrewrk** [comment] 2019-10-09 19:24
Thanks very much, I've bumped the default limit to 400KB, and I believe it will resolve this issue for you. Please let me know if you encounter another problem.

**Comment by DonRyuDragoni** [comment] 2019-10-09 19:40
Everything is working now, thanks a lot!

**Comment by s-ol** [comment] 2019-10-15 22:08
Hey, I got here because without the `catch unreachable` I am getting the same issue.
However my error return trace is different:

```
attempt to unwrap error: NotDir
/usr/lib/zig/std/child_process.zig:212:9: 0x250a8d in std.child_process.ChildProcess.waitPosix (build)
        return self.term.?;
        ^
/usr/lib/zig/std/child_process.zig:153:13: 0x24d137 in std.child_process.ChildProcess.wait (build)
            return self.waitPosix();
            ^
/usr/lib/zig/std/build.zig:872:22: 0x24c030 in std.build.Builder.execAllowFail (build)
        const term = try child.wait();
                     ^
/usr/lib/zig/std/build.zig:933:24: 0x24c5dc in std.build.Builder.execPkgConfigList (build)
        const stdout = try self.execAllowFail([_][]const u8{ "pkg-config", "--list-all" }, out_code, .Ignore);
                       ^
/usr/lib/zig/std/build.zig:961:25: 0x24bbfc in std.build.Builder.getPkgConfigList (build)
                else => return err,
                        ^
/usr/lib/zig/std/build.zig:1744:26: 0x2484ce in std.build.LibExeObjStep.linkSystemLibraryPkgConfigOnly (build)
            const pkgs = try self.builder.getPkgConfigList();
                         ^
???:?:?: 0x23bdbc in ??? (???)


/usr/lib/zig/std/build.zig:1841:42: 0x24571a in std.build.LibExeObjStep.linkSystemLibrary (build)
            else => (anyerror!void)(err) catch unreachable,
                                         ^
/home/s-ol/zig/build.zig:9:26: 0x23e022 in std.special.build (build)
    exe.linkSystemLibrary("SDL2");
                         ^
/usr/lib/zig/std/special/build_runner.zig:140:28: 0x235574 in runBuild (build)
        .Void => root.build(builder),
                           ^
/usr/lib/zig/std/special/build_runner.zig:122:17: 0x232b71 in main (build)
    try runBuild(builder);
                ^
/usr/lib/zig/std/special/start.zig:204:37: 0x2308e5 in std.special.posixCallMainAndExit (build)
            const result = root.main() catch |err| {
                                    ^
/usr/lib/zig/std/special/start.zig:102:5: 0x23075f in std.special._start (build)
    @noInlineCall(posixCallMainAndExit);
    ^
```
this is after applying the change you added above (400kb limit). `pkg-config --list-all` in the terminal works fine and wc reports ~103kb.

**Comment by andrewrk** [comment] 2019-10-15 22:57
Thanks for the report, @s-ol. I have a suspicion of what this may be. I suspect that you have a path in your PATH which is a file, not a directory (which is fine), and this code (or maybe std lib child process code) is failing to detect that as a case for skipping that PATH entry and moving to the next. I can double check this hunch in a bit and get back to you.

**Comment by s-ol** [comment] 2019-10-16 07:56
@andrewrk oh, that would be easy enough to fix, I will check it out and report back myself. I think it's probably not a file but a nonexistant directory.

**Comment by s-ol** [comment] 2019-10-16 10:12
yup, there was an old rubygems directory (`/home/s-ol/.gem/ruby/2.6.0/bin`) in PATH, and it, and all of its parent directories up to `~` didn't exist.

**Comment by andrewrk** [comment] 2019-10-16 19:30
8cf3a4d586b675a239c9cfa1ea07fa9f59ebf0a4 fixes handling of ENOTDIR on POSIX execvpe.

**Closed by andrewrk** 2019-10-16 19:30 UTC
Labels: zig build system
