### ISSUE TITLE
broken LLVM module in `if` statement with invalid optional value

### ISSUE THREAD

**Issue by AliChraghi** [ziglang/zig#9819] opened 2021-09-22 13:00 UTC
this code should error because `mychar` have't `.?`
```zig
const std = @import("std");

pub fn main() void {
  var mychar : ?u8 = null;
  if (mychar != null and mychar == 'a') std.debug.print("works", .{});
}
```
 but instead prints:
```
broken LLVM module found: PHI node entries do not match predecessors!
  %10 = phi i1 [ %2, %Entry ], [ %9, %BoolAndTrue ], !dbg !16485
label %BoolAndTrue
label %CmpOptionalNonOptionalEnd
Instruction does not dominate all uses!
  %9 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull ], [ %8, %CmpOptionalNonOptionalOptionalNotNull ], !dbg !16487
  %10 = phi i1 [ %2, %Entry ], [ %9, %BoolAndTrue ], !dbg !16485

This is a bug in the Zig compiler.thread 593218 panic: 
Unable to dump stack trace: debug info stripped
[1]    593218 IOT instruction (core dumped)  zig run test.zig
```

**Comment by Vexu** [comment] 2021-09-22 13:40
Duplicate of #6059.

**Closed by Vexu** 2021-09-22 13:40 UTC
