### ISSUE TITLE
broken LLVM module using spanZ inside of constructor

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#4904] opened 2020-04-01 21:49 UTC
Fun bug: if I inlined `mem.spanZ(mcpu_oz)` into the `CrossTarget.parse` expression I got:
```
broken LLVM module found: Call parameter type does not match function signature!
  %67 = getelementptr inbounds %std.zig.cross_target.ParseOptions, %std.zig.cross_target.ParseOptions* %10, i32 0, i32 1, !dbg !20878
 %"?[:0]const u8"*  call fastcc void @std.mem.spanZ.176(%"?[]const u8"* sret %67, i8* %68), !dbg !20880

This is a bug in the Zig compiler.
```

_Originally posted by @daurnimator in https://github.com/ziglang/zig/pull/4880_

**Comment by Vexu** [comment] 2022-12-31 11:33
No test case, closing as duplicate of #4907

**Closed by Vexu** 2022-12-31 11:33 UTC
Labels: bug, stage1
