### ISSUE TITLE
Comptime parameter matched to a runtime one causes ICE

### ISSUE THREAD

**Issue by maxsamukha** [ziglang/zig#14205] opened 2023-01-05 06:23 UTC
### Zig Version

0.11.0-dev.944+a193ec432

### Steps to Reproduce and Observed Behavior

fn foo(pred: fn(a: anytype) void) void
{
    _ = pred;
}

fn f(comptime t: anytype) void
{
    _ = t;
}

pub fn main() void
{
    foo(f);
}
----
thread 19691 panic: zig compiler bug: GenericPoison
Unable to dump stack trace: debug info stripped
Aborted (core dumped)

### Expected Behavior

I don't expect an ICE.

**Comment by Vexu** [comment] 2023-01-05 09:59
Duplicate of #14052

**Closed by Vexu** 2023-01-05 09:59 UTC
Labels: bug
