### ISSUE TITLE
Dangerous undefined value

### ISSUE THREAD

**Issue by nine-fox** [ziglang/zig#21970] opened 2024-11-12 07:08 UTC
### Zig Version

0.14.dev

### Steps to Reproduce and Observed Behavior

The following code is valid but extremely dangerous, because val is rubbish value. No any warnning messages.

When myfunc is from 3rd party, how do I know the returned value is valid？

Also, I can not even check val value using == undefined because 0.14 will emit an error.

I would suggest undefined value should not be returned when function marked with ?. At least a warning is needed？

fn myfunc() ?u32 {
    return undefined;
}
test "aa" {
    if (myfunc()) |val| {
        std.debug.print("{}\n", .{val});
    }
}

### Expected Behavior

emit an error

**Comment by andrewrk** [comment] 2024-11-12 07:13
duplicate of #63 (not a bug)

**Closed by andrewrk** 2024-11-12 07:13 UTC
Labels: bug

**Comment by nektro** [comment] 2024-11-12 07:15
related https://github.com/ziglang/zig/issues/211

`undefined` is not detectable at runtime and using it must be done with caution otherwise you may run into the aptly named *undefined behavior*. it is up to the programmer to use `undefined` safely in the cases where the compiler is not able to check it.

**Comment by nine-fox** [comment] 2024-11-12 07:26
hi @andrewrk @nektrnethanks for your comments and I know the background to introduce undefined. However, compare to null which is much safer,  then whats scenarios should use undefined？

If there are cases to be dangerous, I would think undefined should not be used in production. Make an option to turn undefined on/off？

**Comment by nine-fox** [comment] 2024-11-12 07:28
@nektro also in the code above, this case can be detected, bu no error？even a warning is better. Comptime undefined can be detected

**Comment by nektro** [comment] 2024-11-12 07:45
`undefined` is most often used to leave a value uninitialized for later use. for instance:

```zig
var buffer: [1024]u8 = undefined;
const slice = foo(&buffer);
```

happy to discuss more in a [Community](https://github.com/ziglang/zig/wiki/Community)
