### ISSUE TITLE
`@typeName(T)` returns the expression that generated it, not its name

### ISSUE THREAD

**Issue by heysokam** [ziglang/zig#20504] opened 2024-07-05 04:21 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```zig
// report.zig
const std = @import("std");

pub fn baseName(T: type) []const u8 {
    const N = @typeName(T); // Name
    const S = if (std.mem.lastIndexOfScalar(u8, N, '.')) |n| n + 1 else 0; // Start
    return N[S..]; // Return the name, cut from Start until its last char
}

pub fn join(list: []const type, comptime args: struct { prefix: bool = true }) type {
    var index: usize = 0;
    // Find the total Length of the enum
    var length: usize = 0;
    for (list) |E| {
        length += @typeInfo(E).Enum.fields.len;
    }
    // Find the list of enum fields
    var fields: [length]std.builtin.Type.EnumField = undefined;
    for (list) |E| {
        const E_fields = @typeInfo(E).Enum.fields;
        for (0..E_fields.len) |id| {
            defer index += 1;
            const name = if (args.prefix) (baseName(E) ++ "_" ++ E_fields[id].name) else E_fields[id].name;
            fields[index] = .{
                .name = name,
                .value = index,
            };
        }
    }
    // Return the resulting enum
    return @Type(.{ .Enum = .{
        .tag_type = std.math.IntFittingRange(0, fields.len -| 1),
        .fields = &fields,
        .decls = &.{},
        .is_exhaustive = true,
    } });
}

test "4321" {
    const T1 = enum { one1, two1, thr1 };
    const T2 = enum { one2, two2, thr2 };
    const T = join(&.{ T1, T2 }, .{ .prefix = true });
    const t1 = T1.one1;
    const t1_1 = T.T1_one1;
    std.debug.print("................\n", .{});
    std.debug.print("T1   : {any}\n", .{T1});
    std.debug.print("T2   : {any}\n", .{T2});
    std.debug.print("T    : {s}\n", .{@typeName(T)});
    std.debug.print("t1   : {any}\n", .{t1});
    std.debug.print("t1_1 : {any}\n", .{t1_1});
}
```
```zig
................
T1   : report.test.4321.T1
T2   : report.test.4321.T2
T    : report.join(&.{ report.test.4321.T1, report.test.4321.T2 }[0..2],.{ .prefix = true })
t1   : report.test.4321.T1.one1
t1_1 : report.join(&.{ report.test.4321.T1, report.test.4321.T2 }[0..2],.{ .prefix = true }).T1_one1
All 1 tests passed.
```
Run with `zig test report.zig` to see the behavior.

### Expected Behavior

```zig
std.testing.expect(std.mem.eql(u8, @typeName(T), "report.test.4321.T"))
```
I would expect this check to pass,
but `@typeName` is resolving `T` as the expression that generated the type instead of the typeName itself :thinking:

**Comment by Rexicon226** [comment] 2024-07-05 04:27
Happens on `0.14.0-dev.181+0f8561d09` as well.

**Comment by mlugg** [comment] 2024-07-05 05:28
Not a bug. Types are named based on a few heuristics, and a function call takes priority over what that function call happens to be assigned to. For instance, given `const A = std.ArrayListAligned(u32, null);`, we do not expect `@typeName(A)` to be `"A"`, because that would mean `@typeName(std.ArrayListAligned(u32, null))` is `"A"`, which is nonsensical.

Do not rely on `@typeName` for anything. Its behavior will likely change as the compiler evolves, and its output may be implementation-defined in the eventual language specification.

**Closed by mlugg** 2024-07-05 05:28 UTC
Labels: bug

**Comment by heysokam** [comment] 2024-07-05 05:43
> Not a bug. Types are named based on a few heuristics, and a function call takes priority over what that function call happens to be assigned to. For instance, given `const A = std.ArrayListAligned(u32, null);`, we do not expect `@typeName(A)` to be `"A"`, because that would mean `@typeName(std.ArrayListAligned(u32, null))` is `"A"`, which is nonsensical.

This argument is nonsensical.
If I -explicitly- specify that I want the typename of `std.ArrayListAligned(u32, null)` like your second instance... I would expect it to give me what I asked for, which is what you just said.
But if I have it aliased to something, the game is completely different. Because then it is not reporting back the typename, but its implementation.

If I say `const T = []u8`, I don't expect `@typeName(T)` to report `[]u8`, because that's not what I asked for.
I didn't ask for `@typeImpl(T)` (***Impl), I asked for `@typeName(T)` (***Name**)

**Comment by heysokam** [comment] 2024-07-05 05:46
Also, how do you expect people to do meta-programming reliably, if the builtin functions for it are not considered reliable?

**Comment by heysokam** [comment] 2024-07-05 06:02
@mlugg I think I found the TLDR of the problem I see:
Basically, `@typeName` has inconsistent behavior
1. If I declare an enum, it returns the name (left hand side of the `=`)
2. If I declare an alias, it returns the underlying implementation of the type (right hand side of `=`)

Should I make this into a different issue or something?

**Comment by mlugg** [comment] 2024-07-05 06:06
> This argument is nonsensical.
> If I -explicitly- specify that I want the typename of `std.ArrayListAligned(u32, null)` like your second instance... I would expect it to give me what I asked for, which is what you just said.

`A` and `std.ArrayListAligned(u32, null)` are the same type. They cannot have distinct names. The nonsensical thing would be for `T1 == T2` to not imply `@typeName(T1) == @typeName(T2)`.

> Also, how do you expect people to do meta-programming reliably, if the builtin functions for it are not considered reliable?

`@typeName` is a debugging tool, and nothing more. It should not under any circumstance be used to implement actual behavior. Its use cases are very limited; perhaps it will be removed from the language one day.

> Basically, `@typeName` has inconsistent behavior

Your analysis is incorrect. `@typeName` always returns the name of the underlying type. However, that type name can be determined in a few ways based on different heuristics.

> Should I make this into a different issue or something?

Such an issue would be a language proposal, and the Zig project is not generally accepting language proposals at the moment. In particular, if you do not have significant and obvious experience using Zig in an open-source project, a proposal will likely be immediately closed.
