### ISSUE TITLE
cross compiled macos binaries with LLD which depend on TLS fail at runtime

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#3295] opened 2019-09-22 17:54 UTC
```zig
threadlocal var x: i32 = 1;
test "tls macos cross compile" {
    x += 1;
}
```

```
$ ./zig test test.zig
(ok)
$ ./zig test test.zig -target x86_64-macosx
dyld: Symbol not found: __tlv_bootstrap
```

**Comment by andrewrk** [comment] 2019-09-22 18:30
I think this ultimately comes down to a deficiency in LLD. See #1535

**Comment by daurnimator** [comment] 2020-11-10 23:54
(continuing from https://github.com/ziglang/zig-bootstrap/issues/38): I think this may be caused by a too low OSX version. I can find similar issues elsewhere where wrong/low OSX version leads to `Symbol not found: __tlv_bootstrap`, e.g. https://github.com/rust-lang/rust/issues/10842

Can you try passing `-macosx_version_min 10.7.0` to lld?

**Comment by andrewrk** [comment] 2020-11-17 19:49
> Can you try passing `-macosx_version_min 10.7.0` to lld?


We do that here: https://github.com/ziglang/zig/blob/2eee0582f8654cb2b344ed8e2c43dcda3424dbe5/src/link/MachO.zig#L598-L614

**Comment by kubkon** [comment] 2020-12-22 11:19
Just an FYI that this one was fixed for cross-compiling C and Zig sources (C++ is still not in the clear) in #7318; however, ultimately this is a deficiency in LLD so I'm inclined to leave the issue open until LLD acknowledges and fixes it, or our self-hosted linker is up to the job.

**Comment by andrewrk** [comment] 2021-05-09 18:27
The plan to address this issue is #8727. Once that is done, this issue can be closed as well.

**Comment by kubkon** [comment] 2021-05-09 20:11
I will only add that cross-compilation is now exclusively handled by `zig ld` which handles TLVs properly on both x86_64 and arm64 architectures.

**Comment by kubkon** [comment] 2021-07-26 15:38
Given that we no longer rely on LLD when targeting macOS, I'm closing this issue regardless of whether it's been fixed in upstream since it's irrelevant for zig.

**Closed by kubkon** 2021-07-26 15:38 UTC
Labels: bug, os-macos, upstream
