### ISSUE TITLE
Liveness: assertion failed breaking from switch inside comptime expression

### ISSUE THREAD

**Issue by jacobly0** [ziglang/zig#22301] opened 2024-12-23 20:08 UTC
```zig
export fn entry(cond: bool) void {
    ret: switch (cond) {
        inline else => comptime break :ret,
    }
}
```
```
$ zig build-obj bug.zig
thread 566014 panic: attempt to use null value
```

> @mlugg *that* should be rejected by astgen, *and* there needs to be a check in sema for the same thing (for comptime scopes astgen isn't aware of, e.g. fn arg which is a comptime param), so there are multiple bugs here, how fun

**Comment by mlugg** [comment] 2024-12-24 02:11
Oops, my bad, this is a duplicate of #20588!

**Closed by mlugg** 2024-12-24 02:11 UTC
Labels: bug, frontend
