### ISSUE TITLE
`zig build` fails on x86-64 freestanding with functions whose return parameters contain anytype

### ISSUE THREAD

**Issue by jinzhongjia** [ziglang/zig#17636] opened 2023-10-20 08:20 UTC
### Zig Version

0.12.0-dev.1124+ec21da0d5

### Steps to Reproduce and Observed Behavior

1. run `zig init-exe` to init an project
2. set build.zig `target`  to the following values:
```zig
var target: std.zig.CrossTarget = .{
        .cpu_arch = .x86_64,
        .os_tag = .freestanding,
        .abi = .none,
    };
```
3. main.zig
```zig
export fn _start() void {
    const dd = core_dumped();
    dd();
}

fn core_dumped() *const fn (anytype) void {
    return struct {
        fn run(args: anytype) void {
            _ = args;
        }
    }.run;
}
```

output of running the compile instance without `build.zig`:
```sh
[1]    47032 segmentation fault (core dumped)  zig build-exe /home/jin/code/zig/src/main.zig --cache-dir  --global-cache-dir
```

### Expected Behavior

zig build should compile normally

**Comment by Rexicon226** [comment] 2023-10-20 08:42
This isn't a compiler bug, it's poor error message. This is supposed to be a error.
`inline fn` preserves the comptime attribute of the return value. if `inline` isn't what you want to use, you can just wrap it in a `comptime` block like so:

```rust
export fn _start() void {
    comptime {
        const dd = core_dumped();
        dd(1);
    }
}

fn core_dumped() *const fn (anytype) void {
    return struct {
        fn run(args: anytype) void {
            _ = args;
        }
    }.run;
}
```

forcing a runtime-known pointer to a comptime is illegal.

**Comment by jinzhongjia** [comment] 2023-10-20 08:51
> This isn't a compiler bug, it's a lack of a compiler error message. This is supposed to be a error. A solution is to use `inline` for the function. `inline fn` preserves the comptime attribute of the return value. if `inline` isn't what you want to use, you can just wrap it in a `comptime` block like so:
> 
> ```rust
> export fn _start() void {
>     comptime {
>         const dd = core_dumped();
>         dd(1);
>     }
> }
> 
> fn core_dumped() *const fn (anytype) void {
>     return struct {
>         fn run(args: anytype) void {
>             _ = args;
>         }
>     }.run;
> }
> ```
> 
> forcing a runtime-known pointer to a comptime is illegal.

yes, `inline` works well, but when the returned function not contains parameter `anytype`, it works well, why?

**Comment by Vexu** [comment] 2023-10-20 09:45
Duplicate of #17445

**Closed by Vexu** 2023-10-20 09:45 UTC
Labels: bug
