### ISSUE TITLE
workaroundable `error: dependency loop detected` 

### ISSUE THREAD

**Issue by xBZZZZ** [ziglang/zig#21884] opened 2024-11-02 12:48 UTC
### Zig Version

0.14.0-dev.2097+d30e28754

### Steps to Reproduce and Observed Behavior

<ol><li>create file <code>a.zig</code> with content:<pre lang="zig">const myfunctype=*const fn(arg: mystruct) callconv(.C) void;&#10;
const mystruct=extern struct{
	func_addr:myfunctype
};&#10;
//export fn workaround(x: mystruct) callconv(.C) void{
//_=x;
//}&#10;
comptime{
	_=myfunctype;
}</pre></li><li>run<pre lang="bash">zig build-obj a.zig</pre></li></ol><pre>a.zig:1:1: error: dependency loop detected
const myfunctype=*const fn(arg: mystruct) callconv(.C) void;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    mystruct: a.zig:3:23
    myfunctype: a.zig:1:33
    5 reference(s) hidden; use '-freference-trace=7' to see all references</pre>

### Expected Behavior

<code>a.o</code> file successfully created

**Comment by Vexu** [comment] 2024-11-02 19:40
Duplicate of #16932

**Closed by Vexu** 2024-11-02 19:40 UTC
Labels: bug
