### ISSUE TITLE
stage2: inferred optional not detected with two runtime checks

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#12607] opened 2022-08-24 00:06 UTC
### Zig Version

0.10.0-dev.3672+cd5a9ba1f

### Steps to Reproduce

```zig
const std = @import("std");

test {
    var a: u32 = 45;

    var runtime = true;
    var other = false;

    const x = if (runtime) blk: {
        break :blk a;
    } else if (other) {
        return;
    } else null;

    try std.testing.expectEqual(?u32, @TypeOf(x));
    // try std.testing.expect(x == 45); // see #12609
}
```

### Expected Behavior

```
All 1 tests passed.
```

### Actual Behavior

```
test.zig:11:12: error: value with comptime only type '@TypeOf(null)' depends on runtime control flow
    } else if (other) {
           ^~
test.zig:11:16: note: runtime control flow here
    } else if (other) {
               ^~~~~
```

**Comment by Vexu** [comment] 2022-08-24 11:55
Duplicate of #11969

**Closed by Vexu** 2022-08-24 11:55 UTC
Labels: bug, stage2
