### ISSUE TITLE
error trace can show additional, already handled errors

### ISSUE THREAD

**Issue by johnLate** [ziglang/zig#8061] opened 2021-02-24 22:56 UTC
### Bug

Error trace may show additional errors that already have been dealt with.

Demo program `error_trace2.zig`:
```zig
const std = @import("std");
fn dummy(want_error: bool) !usize {
    if (want_error) {
        return error.RedHerring;
    } else {
        return 42;
    }
}
pub fn main() !void {
    const value = dummy(true) catch 0;
    std.debug.warn("value: {}\n", .{value});
    return error.Foo;
}
```
compiled with `zig build-exe error_trace2.zig`.

`./error_trace2` yields:
```
value: 0
error: Foo
/stuff/error_trace2.zig:4:9: 0x2345d7 in dummy (error_trace2)
        return error.RedHerring;
        ^
/stuff/error_trace2.zig:13:5: 0x22d449 in main (error_trace2)
    return error.Foo;
```

(Found because `std.heap.GeneralPurposeAllocator` may use `error.OutOfMemory` internally even if a resize operation ultimately succeeds.)

### Version Info:
```
zig version                    | 0.8.0-dev.1160+8b9434871
git log -n 1 --format='%h %ci' | 8b9434871 2021-02-24 08:26:13 -0500
uname -m -o                    | x86_64 GNU/Linux
```

**Comment by daurnimator** [comment] 2021-02-24 22:58
Duplicate of #1923

**Closed by daurnimator** 2021-02-24 22:58 UTC
Labels: duplicate
