### ISSUE TITLE
Compilation error with Lua 5.4.7 when calling luaL_dostring

### ISSUE THREAD

**Issue by circle67** [ziglang/zig#21129] opened 2024-08-18 17:15 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

When I attempt to build the following:

```zig
const lua = @cImport({
    @cInclude("luaconf.h");
    @cInclude("lua.h");
    @cInclude("lualib.h");
    @cInclude("lauxlib.h");
});

pub fn main() !void {
    const state = lua.luaL_newstate();
    defer lua.lua_close(state);

    lua.luaL_dostring(state, "print(\"Hello, World!\")");
}
```

I get this:

```
lua_test/.zig-cache/o/641c11fdde4ac090003c86ff823fc860/cimport.zig:1646:119: error: expected type '?*const fn (?*cimport.struct_lua_State, c_int, isize) callconv(.C) c_int', found '?*anyopaque'
pub inline fn lua_pcall(L: anytype, n: anytype, r: anytype, f: anytype) @TypeOf(lua_pcallk(L, n, r, f, @as(c_int, 0), NULL)) {
                                                                                                                      ^~~~
lua_test/.zig-cache/o/641c11fdde4ac090003c86ff823fc860/cimport.zig:1646:119: note: pointer type child 'anyopaque' cannot cast into pointer type child 'fn (?*cimport.struct_lua_State, c_int, isize) callconv(.C) c_int'
lua_test/.zig-cache/o/641c11fdde4ac090003c86ff823fc860/cimport.zig:259:111: note: parameter type declared here
pub extern fn lua_pcallk(L: ?*lua_State, nargs: c_int, nresults: c_int, errfunc: c_int, ctx: lua_KContext, k: lua_KFunction) c_int;
                                                                                                              ^~~~~~~~~~~~~
lua_test/.zig-cache/o/641c11fdde4ac090003c86ff823fc860/cimport.zig:2005:103: note: called from here
pub inline fn luaL_dostring(L: anytype, s: anytype) @TypeOf((luaL_loadstring(L, s) != 0) or (lua_pcall(L, @as(c_int, 0), LUA_MULTRET, @as(c_int, 0)) != 0)) {
                                                                                             ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.zig:14:22: note: called from here
    lua.luaL_dostring(state, "print(Hello, World!)");
    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

I expected the build to work, where running the program would print _Hello, World!_

**Comment by Vexu** [comment] 2024-08-18 18:20
Duplicate of #5596, see comment https://github.com/ziglang/zig/issues/5596#issuecomment-978952813

**Closed by Vexu** 2024-08-18 18:20 UTC
Labels: bug
