### ISSUE TITLE
Broken LLVM module: PHI node entries do not match predecessors

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#8145] opened 2021-03-04 20:08 UTC
The below code results in an invalid LLVM module with both master and 0.7.1

## Code
```zig
pub fn main() void {
    const some_slice = "Blah Blah Blah";

    var i: usize = 0;

    const peek_one = atOrNull(some_slice, 1);
    const peek_two = atOrNull(some_slice, 2);

    if (peek_one == @as(u8, '\n')) {
        i = 1;
    } else if (peek_one == @as(u8, '\r') and peek_two == @as(u8, '\n')) {
        i = 2;
    } else {
        i = 3;
    }
}

fn atOrNull(slice: []const u8, ahead: usize) ?u8 {
    if (slice.len > ahead) return slice[ahead];
    return null;
}
```

## Error
```
broken LLVM module found: PHI node entries do not match predecessors!
  %18 = phi i1 [ %11, %Else ], [ %17, %BoolAndTrue ], !dbg !16014
label %Else
label %CmpOptionalNonOptionalEnd3
Instruction does not dominate all uses!
  %11 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull2 ], [ %10, %CmpOptionalNonOptionalOptionalNotNull1 ], !dbg !16013
  %18 = phi i1 [ %11, %Else ], [ %17, %BoolAndTrue ], !dbg !16014
Instruction does not dominate all uses!
  %17 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull5 ], [ %16, %CmpOptionalNonOptionalOptionalNotNull4 ], !dbg !16015
  %18 = phi i1 [ %11, %Else ], [ %17, %BoolAndTrue ], !dbg !16014

This is a bug in the Zig compiler.thread 5806 panic:
Unable to dump stack trace: debug info stripped
[1]    5806 abort      zig build-exe src/simple.zig
```

**Comment by LemonBoy** [comment] 2021-03-04 20:23
Duplicate of #6059

**Closed** 2021-03-05 12:12 UTC
