### ISSUE TITLE
zig cc -mcpu=? is pass-thru to clang driver and lists cpu model names incompatible with zig targets

### ISSUE THREAD

**Issue by locriacyber** [ziglang/zig#9988] opened 2021-10-20 17:43 UTC
### Zig Version

0.9.0-dev.1433+4a76523b9

### Steps to Reproduce

```
zig cc -o ./pony -O3 -march=x86-64 pony.o
```

Any object file will work.

### Expected Behavior

The program should compile. `clang` does work with the same arguments.

### Actual Behavior

```
> zig cc -o ./pony -O3 -march=x86-64 pony.o
info: Available CPUs for architecture 'x86_64':
...
 x86_64
 x86_64_v2
 x86_64_v3
 x86_64_v4
...

error: Unknown CPU: 'x86'
```

**Comment by andrewrk** [comment] 2021-11-27 03:48
Duplicate of #4911

**Closed by andrewrk** 2021-11-27 03:48 UTC
Labels: bug, zig cc
