### ISSUE TITLE
Windows PATH problem ZigLibDirNotFound

### ISSUE THREAD

**Issue by hgabe** [ziglang/zig#4742] opened 2020-03-15 04:13 UTC
Hello

zig targets
Unable to find zig lib directory: FileNotFound.
Reinstall Zig or use --zig-install-prefix.
unable to find zig installation directory: ZigLibDirNotFound

I have zig install in my hdd and added to the PATH bu I get this error, how does zig detect this folder on windows?

**Comment by andrewrk** [comment] 2020-03-15 04:14
Duplicate of #4634

**Closed by andrewrk** 2020-03-15 04:14 UTC
