### ISSUE TITLE
Branch miscompiled as if it were comptime known

### ISSUE THREAD

**Issue by adlerd** [ziglang/zig#9749] opened 2021-09-12 21:50 UTC
I tried running this program

```rust
const std = @import("std");
pub fn main() anyerror!void{
    var args = std.process.args();
    _ = args.skip();
    const flag = args.skip();
    return std.fmt.format(std.io.getStdOut().writer(), "{any}\n{s}\n", .{
        flag,
        if (flag) @as([]const u8, "YES") else "NO",
    });
}
```

`zig version`: `0.9.0-dev.874+4334dbb9a`

When running the program with no arguments, the expected output is:
```
false
NO
```

The observed output is:
```
false
YES
```

This example was minimized from another example; the general problem seems to be format arguments initialized by a branch between two constant strings, when the branch is not comptime known.

**Comment by rohlem** [comment] 2021-09-16 11:21
Probably a manifestation/duplicate of the nasty #3882 / #4491 / #5230 / #7097 .
The stage1 compiler is alarmingly buggy with conditional control flow filling tuples.
The current workaround is to write the values to variables first, and use those in the tuple.
```zig
const answer = if (flag) @as([]const u8, "YES") else "NO";
return std.fmt.format(std.io.getStdOut().writer(), "{any}\n{s}\n", .{
    flag,
    answer,
});
```
Not great. Would probably be better for stage1 to hard-error if we could reliably detect these scenarios.

**Closed** 2021-09-16 17:49 UTC
