### ISSUE TITLE
-Drelease-fast optimizes while(true) away;

### ISSUE THREAD

**Issue by The-Jon** [ziglang/zig#5526] opened 2020-06-03 23:25 UTC
The LLVM Optimizer optimizes a 

`while  ( true ) {
       foo();
} `

away where foo doesn't have side effects.
Debug mode works just fine.

Assumed trigger: while(true) is undefined behavior in C -> LLVM 

e.g.: https://godbolt.org/z/uZWVkb

**Comment by Snektron** [comment] 2020-06-03 23:48
As discussed on Discord, this is probably due to that LLVM was primarily made for the C family, where
```c
while (true) {}
```
is undefined behaviour.

Another problem is that doesn't occur just using --release-fast, but also in --release safe. An interesting observation is that the loop is only removed when invoking another function with the loop.

See https://godbolt.org/z/y7UJRM.
Note that this is UB in C out of optimization concern (see [here](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1528.htm)), so resolving it might not be as easy as simply telling LLVM to quit removing those loops (if that is even possible).

**Comment by SpexGuy** [comment] 2020-06-04 00:00
Specifically, this is the text in the C++ specification that allows it:
> An iteration statement that performs no input/output operations,
does not access volatile objects, and performs no
synchronization or atomic operations in its body, controlling
expression, or (in the case of a for statement) its expression-3,
may be assumed by the implementation to terminate.*
>
> *This is intended to allow compiler transformations such as
removal of empty loops even when termination cannot be
proven.

This is an important behavior for loop optimization.  Without it, loops can essentially never be merged, because proving that a loop terminates is literally the halting problem.

But this should probably be caught somehow in release-safe mode, potentially by asserting the loop condition after the loop finishes if the loop condition has no side effects.

**Comment by tadeokondrak** [comment] 2020-06-04 02:46
Related: https://github.com/rust-lang/rust/issues/28728 https://bugs.llvm.org/show_bug.cgi?id=965

**Comment by gereeter** [comment] 2020-06-04 05:42
As mentioned in some of the linked issues, LLVM's current answer to this problem is the [llvm.sideeffect](https://llvm.org/docs/LangRef.html#llvm-sideeffect-intrinsic) intrinsic. As discussed in some of the Rust issues, adding it blindly everywhere can cause [compile-time](https://perf.rust-lang.org/compare.html?start=66b0c97070f422cb82baaaafc79ee94cab4396c5&end=548b5e75afd6bad696920dfdb69c9812ce0488f1) and [runtime](https://docs.google.com/spreadsheets/d/1I5p0_ChO7xakIYUvbhVlgmaKnvDdvOnkpv7zDZAy-CQ/edit#gid=0) regressions, which makes it less desirable. See also the [Rust blog post](https://blog.rust-lang.org/inside-rust/2020/03/19/terminating-rust.html) on the topic.

Zig doesn't have the safety guarantees that Rust does, but it still seems appropriate to start with the safe option (e.g. inserting `llvm.sideeffect` on every backedge, at least in safe modes) and improve things from there.

**Comment by Vexu** [comment] 2024-06-01 10:17
This was fixed in LLVM 12

**Closed by Vexu** 2024-06-01 10:17 UTC
Labels: upstream
