### ISSUE TITLE
Running `zig fmt` duplicates parts of the code when dereferencing pointers incorrectly.

### ISSUE THREAD

**Issue by weltauseis** [ziglang/zig#20460] opened 2024-06-30 15:34 UTC
### Zig Version

0.14.0-dev.130+cb308ba3a

### Steps to Reproduce and Observed Behavior

Hey ! I am trying to learn zig, and have run into some weird behavior with the formatter when i was dereferencing pointers incorrectly using a C-like syntax.

1) Create a `test.zig` file with this content, which tries to dereference a pointer using `*ptr`, as someone coming from C would intuitively do : 
```zig
fn parse_string(source: []u8, at: *u64) void {
    while (source[*at] != '"') {}
}
```

2) Run `zig fmt` on it.
```
zig fmt test.zig
```

3) Zig formatter has duplicated some parts of it. 
```zig
fn parse_string(source: []u8, at: *u64) void {
    while (sourcesource[*at]at] != '"') {}
}
```

Of course, this code is not proper Zig, but this behavior might be indesirable so I decided to report it.

### Expected Behavior

The formatter fails and doesn't do anything, or at least doesn't mess with incorrect code.

**Comment by xdBronch** [comment] 2024-06-30 15:55
duplicate of https://github.com/ziglang/zig/issues/19440

**Closed** 2024-06-30 15:56 UTC
Labels: bug
