### ISSUE TITLE
access of union field 'func' while field 'cau' is active in comptime linked list iteration

### ISSUE THREAD

**Issue by tauoverpi** [ziglang/zig#21621] opened 2024-10-07 17:14 UTC
### Zig Version

0.14.0-dev.1820+ea527f7a8

### Steps to Reproduce and Observed Behavior

```zig
fn repeatN(comptime count: comptime_int, comptime value: anytype) type {
    if (count == 0) return {}; // void; // works if it's a type rather than void value
    return struct {
        pub const car = value;
        pub const cdr = repeatN(count - 1, value);
    };
}

comptime {
    const list = repeatN(2, {});
    @compileLog(list.cdr.cdr);
}
```

Run: `zig build-obj bug.zig`

```
thread 12733 panic: access of union field 'func' while field 'cau' is active
Analyzing bug.zig
      %9 = dbg_stmt(2, 21)
      %10 = block({
        %11 = restore_err_ret_index_unconditional(%10) node_offset:2:28 to :2:30
        %12 = break(%10, @void_value)
      }) node_offset:2:28 to :2:30
      %13 = restore_err_ret_index_unconditional(.none) node_offset:2:21 to :2:30
      %14 = dbg_stmt(2, 21)
    > %15 = ret_node(@void_value) node_offset:2:21 to :2:30
    For full context, use the command
      zig ast-check -t bug.zig

  in bug.zig
    > %7 = condbr(%6, {%9..%15}, {%16}) node_offset:2:5 to :2:30
  in bug.zig
    > %8 = block({%6, %7}) node_offset:2:5 to :2:30
  in bug.zig
    > %26 = call(.compile_time, %24, [
        {%27..%29},
        {%30, %31},
      ]) node_offset:5:25 to :5:50
  in bug.zig
    > %47 = field_val(%46, "cdr") node_offset:11:17 to :11:29

/home/tau/tmp/zig/src/Sema.zig:30354:74: 0x2373d5c in coerceExtra (zig)
            !zcu.test_functions.contains(zcu.funcInfo(sema.owner.unwrap().func).owner_nav))
                                                                         ^
/home/tau/tmp/zig/src/Sema.zig:20216:37: 0x2fb33ce in analyzeRet (zig)
    const operand = sema.coerceExtra(block, sema.fn_ret_ty, uncasted_operand, operand_src, .{ .is_ret = true }) catch |err| switch (err) {
                                    ^
```

### Expected Behavior

As far as I can tell, my cursed code should work.

**Comment by Rexicon226** [comment] 2024-10-07 17:27
duplicate of #21159

**Comment by tauoverpi** [comment] 2024-10-07 18:06
duplicate

**Closed** 2024-10-08 05:21 UTC
Labels: bug
