### ISSUE TITLE
Compiler segfault if using switch on a pointer

### ISSUE THREAD

**Issue by frmdstryr** [ziglang/zig#4171] opened 2020-01-13 18:10 UTC
I shouldn't have done this in the first place but it segfaults.

```zig
const std = @import("std");

pub const USART_TypeDef = struct {
    CR: u32,
};

pub const USART1_BASE = 0x400;
pub const USART2_BASE = 0x800;
pub const USART1 = @intToPtr(*volatile USART_TypeDef, USART1_BASE);
pub const USART2 = @intToPtr(*volatile USART_TypeDef, USART2_BASE);

pub fn main() void {
    var instance = USART1;
    // It should use @ptrToInt then use USARTx_BASE
    switch (instance) { 
        USART1 => std.debug.warn("UART1", .{}),
        USART2 => std.debug.warn("UART2", .{}),
        else => @panic("Invalid"),
    }
}

```

```
zig build
Segmentation fault at address 0x10
???:?:?: 0x7fbfc138a268 in ??? (???)


???:?:?: 0x5584f641cc27 in ??? (???)
```

**Comment by LemonBoy** [comment] 2020-01-13 18:30
Duplicate of #4074

**Comment by frmdstryr** [comment] 2020-01-13 18:31
Yes, looks the same, thanks.

**Closed** 2020-01-13 18:31 UTC
