### ISSUE TITLE
stage2: switch doesn't get proper type with inferred error set

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#11119] opened 2022-03-10 23:05 UTC
This happens only in runtime, _not_ comptime.

```zig
const std = @import("std");

test {
    q() catch |e| {
        switch (e) {
            error.Whatever => @panic("FAIL"),
        }
    };
}

fn q() !u8 {
    return error.Whatever;
}
```

```
test.zig:6:13: error: expected (inferred error set of q), found error{Whatever}
            error.Whatever => @panic("FAIL"),
```

**Comment by Vexu** [comment] 2022-03-10 23:14
Duplicate of #11046

**Closed by Vexu** 2022-03-10 23:14 UTC
