### ISSUE TITLE
"enum literals must be comptime known", but it is?

### ISSUE THREAD

**Issue by Tetralux** [ziglang/zig#2964] opened 2019-07-28 17:10 UTC
```zig
const E = enum {
    A,
    B
};

fn f(i: isize) E {
    return switch (i) {
        0 => .A,
        else => .B,
    };
}

pub fn main() void {
    warn("{}\n", f(42));
}
```
If I do
```zig
return switch (i) {
    0 => E.A,
    else => E.B, // Note the Es...
};
```
Then it's fine.
But it should know what `.A` and `.B` I'm talking about without me having to specify it.

**Comment by GoNZooo** [comment] 2019-07-28 17:20
If you use `comptime i: isize` instead it compiles fine.

**Comment by Tetralux** [comment] 2019-07-28 17:26
@GoNZooo If I do
```zig
return switch (i) {
    0 => E.A,
    else => E.B, // Note the Es...
};
```
Then it's also fine. :)

What seems wrong about it is that it does not seem like it needs `comptime`.
Like... it should know what `.A` and `.B` I mean.

**Comment by mikdusan** [comment] 2019-07-28 17:39
I also found that if you qualify **at least** 1 case return that it compiles.
```zig
const std = @import("std");

const E = enum { a,b,c,d,e };

fn f(i: isize) E {
    return switch (i) {
        0 => .a,
        1 => .b,
        2 => E.c,
        3 => .d,
        else => .e,
    };
}

pub fn main() void {
    std.debug.warn("{}\n", f(42));
}
```

**Comment by Tetralux** [comment] 2019-07-28 17:42
Indeed. Though, it should already know that - it's in the return type. xD

**Comment by dbandstra** [comment] 2019-07-28 18:42
Dupe of https://github.com/ziglang/zig/issues/2856 which will be fixed by https://github.com/ziglang/zig/issues/2749

**Comment by Tetralux** [comment] 2019-07-28 19:08
Will close when accepted proposal (#2749) is merged.

**Closed** 2019-07-29 20:42 UTC
