### ISSUE TITLE
Check types of inputs in inline asm statements

### ISSUE THREAD

**Issue by notYuriy** [ziglang/zig#8774] opened 2021-05-14 11:45 UTC
https://zig.godbolt.org/z/5P7WEeb4a
```zig
pub fn main() void {
    asm volatile("nop;"::[_]"{rax}"(u1));
}
```
Crashes zig compiler in `resolve_llvm_types` function
```
Unreachable at /home/vsts/work/1/s/src/stage1/analyze.cpp:9711 in resolve_llvm_types. This is a bug in the Zig compiler.thread 1 panic: 
Unable to dump stack trace: debug info stripped
ASM generation compiler returned: 139
Unreachable at /home/vsts/work/1/s/src/stage1/analyze.cpp:9711 in resolve_llvm_types. This is a bug in the Zig compiler.thread 1 panic: 
Unable to dump stack trace: debug info stripped
Execution build compiler returned: 139
```
Zig compiler should check what types are passed as inputs to inline asm statements and give an error if those types are compile-time only.

**Comment by g-w1** [comment] 2021-05-14 11:58
Dupe of https://github.com/ziglang/zig/issues/7843

**Closed** 2021-05-14 12:07 UTC
Labels: duplicate
