### ISSUE TITLE
Pinter to cyclic depended struct crashes compiler

### ISSUE THREAD

**Issue by tubo28** [ziglang/zig#17175] opened 2023-09-16 14:28 UTC
### Zig Version

0.12.0-dev.170+750998eef

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const print = std.debug.print;

test "Pinter to cyclic depended struct crashes compiler" {
    const s = newS();
    print("{}\n", .{s});
}

fn newS() S {
    unreachable;
}

const S = struct {
    ptrA: *A,
};

const A = struct {
    b: B,
};

const B = struct {
    a: A,
};
```

```console
> ~/ghq/github.com/ziglang/zig/build/stage3/bin/zig test src/main.zig
Semantic Analysis [1460] fish: Job 1, '~/ghq/github.com/ziglang/zig/bu…' terminated by signal SIGSEGV (Address boundary error)
> uname -a
Linux DESKTOP-HO2LEDU 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Expected Behavior

An error like `struct 'main.A' depends on itself`.

**Comment by tubo28** [comment] 2023-09-16 14:31
Replacing `ptrA: *A` to `ptrA: A` gives the "depends on itself" error correctly.

**Comment by rofrol** [comment] 2023-09-18 00:22
Pinter -> Printer?

**Comment by nektro** [comment] 2023-09-18 00:23
pointer

**Comment by andrewrk** [comment] 2023-09-18 00:24
Duplicate of https://github.com/ziglang/zig/issues/13724

**Closed by andrewrk** 2023-09-18 00:24 UTC
Labels: bug, frontend
