### ISSUE TITLE
Error message with builtin type has missing piece of hierarchy

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#7418] opened 2020-12-13 10:44 UTC
I got the error message:
```
error: expected type 'type', found '[]const std.builtin.EnumField'
```

However the field is actually `std.builtin.TypeInfo.EnumField`: somehow the error message is missing the `.TypeInfo` piece.

**Comment by SpexGuy** [comment] 2021-04-05 02:39
I think this might be a duplicate of #3693?

**Closed** 2021-04-05 07:31 UTC
Labels: bug, stage1
