### ISSUE TITLE
allowzero pointers don't work on wasm32-freestanding in release mode.

### ISSUE THREAD

**Issue by puzzleddev** [ziglang/zig#4668] opened 2020-03-07 15:29 UTC
When compiling for wasm32-freestanding, writes to `allowzero` pointers, which are known at compile time to point to 0x0000 result in `unreachable` instructions.

A minimal example tested on master #80ff549e2 (latest at the time of writing) can be found here: https://gist.github.com/puzzleddev/620c2ddd28cb9c7a1f1b0f01673364ff

This really isn't important, given that there is no real reason to write to 0x0000 in WASM. It does, however, support such writes and, as such `allowzero` should function or an exemption has to be made. The WASM people tried to do so a while ago as seen here: https://github.com/WebAssembly/design/issues/204

This seems to have gone nowhere, as today the memory instruction section mentions that accessible addresses start at 0 (https://webassembly.github.io/spec/core/syntax/instructions.html#syntax-instr-memory).

**Comment by LemonBoy** [comment] 2020-03-07 16:48
> result in unreachable instructions

Do you have a stack trace? Is the problem inside the compiler or in the generated binary?

**Comment by puzzleddev** [comment] 2020-03-07 16:58
It will generate a program no problem, just the write to 0x0000 is optimized as if it was invalid.

According to [this](https://gist.github.com/puzzleddev/d519d882603ce644f105c5c606021d9d) IR dump, Zig generates the proper instructions, so it may be LLVM that's the problem here.

**Comment by fengb** [comment] 2020-03-07 17:01
https://godbolt.org/z/FQk5t3 raw wasm dump shows this:
```wat
  (func $glue_startup (type 0) (result i32)
    unreachable
    unreachable)
```

**Comment by andrewrk** [comment] 2020-03-07 17:29
I think we have to do some annoying things with "address spaces" in LLVM to make the semantics correct. If you search http://llvm.org/docs/LangRef.html for "address space" you can find a bunch of separate things talking about this special address space 0, and how LLVM makes all kinds of assumptions about address 0 in this address space.

**Comment by joshgoebel** [comment] 2022-01-03 23:36
@puzzleddev I'm seeing the same thing you area... There is generated code, but it's marked as null by LLVM and in the compiled WASM it seems to disappear entirely:

```
@FRAMEBUFFER = internal unnamed_addr constant [16320 x i8]* null, align 4
@FRAMEBUFFER2 = internal unnamed_addr constant [16320 x i8]* inttoptr (i32 1 to [16320 x i8]*), align 4

...

 WhileBody:                                        ; preds = %WhileCond
   store i8 -103, i8* null, align 1
   %2 = load i32, i32* %i, align 4
   %3 = getelementptr inbounds [16320 x i8], [16320 x i8]* null, i32 0, i32 %2
   store i8 86, i8* %3, align 1
   %4 = load i32, i32* %i, align 4
   %5 = getelementptr inbounds [16320 x i8], [16320 x i8]* inttoptr (i32 1 to [16320 x i8]*), i32 0, i32 %     4
   store i8 103, i8* %5, align 1
```

**Comment by joshgoebel** [comment] 2022-01-03 23:40
Oh, wait... yes with a single discrete pointer I get the `unreachable` behavior, but with an array pointer I just get the code dropped...

```zig
pub const ZERO: *allowzero u8 = @intToPtr(*allowzero u8, 0);
pub const FRAMEBUFFER: *allowzero [16320]u8 = @intToPtr(*allowzero[16320]u8, 0);
pub const FRAMEBUFFER2: * [16320]u8 = @intToPtr(*[16320]u8, 1);
```

```zig
    // compiles to unreachable
    tic.ZERO.* = 0x99;
    // doesn'st appear in the generated WASM at all
    tic.FRAMEBUFFER.*[i]=0x56;
    // works as expected
    tic.FRAMEBUFFER2.*[i]=0x67;
```

**Comment by joshgoebel** [comment] 2022-01-04 01:40
I fixed my problem by adding `volatile` though I'm not 100% sure what voodoo this is doing...

```
pub const FRAMEBUFFER: *allowzero volatile [16320]u8 = @intToPtr(*allowzero volatile [16320]u8, 0);
```

But the behavior is now correct and I can address the VRAM from position 0 and forward.

**Comment by alexrp** [comment] 2024-10-31 01:23
Closing as duplicate of #4668 which has more information on how this should be resolved.

**Closed by alexrp** 2024-10-31 01:23 UTC
Labels: bug, backend-llvm

**Comment by xdBronch** [comment] 2024-10-31 01:30
this is #4668 :p, guessing you meant #15816

**Comment by alexrp** [comment] 2024-10-31 01:44
Oops, yes!
