### ISSUE TITLE
Mac OSX brew fails with --HEAD

### ISSUE THREAD

**Issue by andymans** [ziglang/zig#4949] opened 2020-04-05 18:50 UTC
Hi,

macos catalina 10.15.4 (19E266)

The bulk of a brew install --HEAD seems to be working; but it errors towards the end with:

Undefined symbols for architecture x86_64:
  "getPollyPluginInfo()", referenced from:
      (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) in libclangCodeGen.a(BackendUtil.cpp.o)
ld: symbol(s) not found for architecture x86_64

Using brew install sans HEAD (the standard release) works just fine :-)

**Comment by andrewrk** [comment] 2020-04-05 18:56
Duplicate of #4799; see that issue for a workaround

**Closed by andrewrk** 2020-04-05 18:56 UTC

**Comment by andymans** [comment] 2020-04-05 19:31
Aha OK. Thx! Hadn't seen #4799; closing.
