### ISSUE TITLE
Compiler segmentation fault on double inline

### ISSUE THREAD

**Issue by pascaldekloe** [ziglang/zig#16924] opened 2023-08-22 13:16 UTC
### Zig Version

0.12.0-dev.17+49244dc0c

### Steps to Reproduce and Observed Behavior

A `zig build-exe` with the following causes `segmentation fault  zig build-exe crash.zig`.

```
const std = @import("std");

pub fn main() !void {
    // arbitrary input string
    var buf: [8]u8 = undefined;
    var in = try std.os.getcwd(&buf);

    const escape_set = "bar";

    var count: u8 = 0;
    for (in) |c| count += switch (c) {
        inline 'A'...'Z', 'a'...'z' => inline for (escape_set) |o| {
            if (o == c) break 3;
        } else 1,
        else => 3,
    };

    std.mem.doNotOptimizeAway(count);
}
```

Removing one of the two `inline`s resolves the issue.

### Expected Behavior

If there is a reason for this not to work, then the compiler should explain why.

**Comment by Pyrolistical** [comment] 2023-08-22 23:12
I reduced the repo a tad:
```zig
pub fn main() !void {
    var x: u8 = 0;
    for ("i") |i| x += switch (i) {
        inline 'A'...'Z' => inline for ("j") |j| {
            if (j == i) break 1;
        } else 2,
        else => 3,
    };
}
```

**Comment by mpfaff** [comment] 2023-08-29 22:06
Reduced further:

```zig
pub fn main() !void {
    for ("i") |i| switch (i) {
        inline else => inline for ("j") |j| {
            if (j == i) break;
        },
    };
}
```

version: `0.12.0-dev.141+ddf5859c2`

**Comment by Vexu** [comment] 2023-09-07 10:38
Duplicate of #13428

**Closed by Vexu** 2023-09-07 10:38 UTC
Labels: bug
