### ISSUE TITLE
Invalid Paths in generated PDB files

### ISSUE THREAD

**Issue by AsgardXIV** [ziglang/zig#17501] opened 2023-10-12 22:23 UTC
### Zig Version

0.12.0-dev.890+8c6b0271c

### Steps to Reproduce and Observed Behavior

Create a shared library with a zig file in a subfolder (say `src/test/test.zig`) and ensure it is being used so it's not stripped.
Observe the generated PDB file, it will have a reference to say `D:\Development\ZigSandbox\src\test\test\test.zig` instead of `D:\Development\ZigSandbox\src\test\test.zig`, adding the final directory twice.

This worked correctly in `0.12.0-dev.817` so looks like some kind of regression.

### Expected Behavior

The embedded path should be correct.

**Comment by AsgardXIV** [comment] 2023-10-12 22:26
Looks like this may be a dupe of #17482, feel free to close out if so.

**Comment by andrewrk** [comment] 2023-10-13 01:15
Duplicate of #17482. The fix is cooking: #17503

**Closed by andrewrk** 2023-10-13 01:15 UTC
Labels: bug
