### ISSUE TITLE
zig fmt: preprocessing step to convert UTF-16 files to UTF-8

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#4267] opened 2020-01-22 09:21 UTC
_Originally posted by @daurnimator in https://github.com/ziglang/zig/issues/3453#issuecomment-576074456_
> Perhaps zig should emit a warning/note if file contents looks like a utf16 BOM

At the moment, if you pass a utf16 encoded zig file to the compiler you're likely to get an error that looks something like:
```
error: invalid character: '\xff'
 ■p
^
```

Lets add a note to this error that suggests incorrect encoding as the problem.

**Comment by jhenninger** [comment] 2020-06-21 18:43
Duplicate of #2820?

**Closed** 2020-06-22 14:54 UTC
Labels: contributor friendly, enhancement, stage2
