### ISSUE TITLE
Equality operator between ?T and T crashes the compiler

### ISSUE THREAD

**Issue by YizhePKU** [ziglang/zig#10283] opened 2021-12-06 05:46 UTC
### Zig Version

zig trunk (on the compiler explorer)

### Steps to Reproduce

Try to compile this code:

```zig
pub fn main() !void {
    var foo: i32 = 47;
    var bar: ?i32 = 47;
    if (foo == bar and true) {}
}
```

The `and true` part is essential to reproduce the bug.

### Expected Behavior

It should compiles without error. I believe PR #5161 is supposed to implement this.

### Actual Behavior

The compiler fails with the following error message:

```
broken LLVM module found: PHI node entries do not match predecessors!
  %9 = phi i1 [ %8, %Entry ], [ true, %BoolAndTrue ], !dbg !3697
label %BoolAndTrue
label %CmpOptionalNonOptionalEnd
Instruction does not dominate all uses!
  %8 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull ], [ %7, %CmpOptionalNonOptionalOptionalNotNull ], !dbg !3696
  %9 = phi i1 [ %8, %Entry ], [ true, %BoolAndTrue ], !dbg !3697

This is a bug in the Zig compiler.thread 1 panic: 
Unable to dump stack trace: debug info stripped
Compiler returned: 139
```

Demonstation: https://godbolt.org/z/fKExbr67M

**Comment by Vexu** [comment] 2021-12-06 10:32
Duplicate of #6059.

**Closed by Vexu** 2021-12-06 10:32 UTC
Labels: bug
