### ISSUE TITLE
Segmentation fault on switch with string slices

### ISSUE THREAD

**Issue by renatoathaydes** [ziglang/zig#11934] opened 2022-06-25 18:25 UTC
### Zig Version

0.10.0-dev.2577+5816d3eae

### Steps to Reproduce

```zig
const std = @import("std");

test "switch" {
    var x = "foo"[0..];
    const y = switch (x) {
        "foo"[0..] => "it is foo",
        "bar"[0..] => "no, bar",
        else => "unknown",
    };
    try std.testing.expectEqualStrings(@as([]const u8, "it is foo"[0..]), y);
}
```

Ru with `zig test file.zig`.

### Expected Behavior

Not sure, but definitely not segmentation fault, right?

### Actual Behavior

```
▶ zig test src/tests.zig
[1]    28339 segmentation fault  zig test src/tests.zig

```

**Comment by Vexu** [comment] 2022-06-25 18:32
Duplicate of #7357, switching on strings is not supported.

**Comment by renatoathaydes** [comment] 2022-06-25 18:32
The simplest example that causes this seems to be this:

```zig
const std = @import("std");

test "switch" {
    var x = "foo"[0..];
    _ = switch (x) {
        "foo"[0..] => "it is foo",
        "bar"[0..] => "no, bar",
        else => "unknown",
    };
}
```

**Closed by Vexu** 2022-06-25 18:32 UTC
Labels: bug
