### ISSUE TITLE
Symbol not found: _sincos when comparing c_int from c import to negative number

### ISSUE THREAD

**Issue by JDWilliamson** [ziglang/zig#10409] opened 2021-12-24 19:33 UTC
### Zig Version

0.8.1

### OS:
Mac Mojave
Version 10.14.6

### Steps to Reproduce

I am attempting to write some incredibly simplistic OpenGL code and have the following code snippets (there's obviously more, but I'm fairly certain its all unrelated):

```zig
// external/c.zig
pub usingnamespace @cImport({
    @cDefine("GLFW_INCLUDE_NONE", "");
    @cInclude("glad/glad.h");
    @cInclude("GLFW/glfw3.h");
});
```

```zig
// external/gl.zig
const c = @import("c.zig");

pub const Float = c.GLfloat;
pub const Int = c.GLint; // appears to be a c_int
pub const UInt = c.GLuint;
pub const Char = c.GLchar;

pub fn getUniformLocation(program: UInt, name: [*c]const Char) Int {
    const res = c.glGetUniformLocation(program, name);
    assertNoError();
    return res;
}
```

```zig
// main.zig
const gl = @import("external/gl.zig");

/// This gets called in essentially a while(true) loop
fn render(window: *glfw.Window, time: f64) void {
    const current_time = glfw.vars.getTime();
    std.debug.print("time: {}\n", .{current_time});

    // The thing it apparrently cannot link
    gl.clearColor(@floatCast(f32, @sin(current_time)), @floatCast(f32, @cos(current_time)), @floatCast(f32, @sin(current_time)), 1.0);
    
    gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT | gl.STENCIL_BUFFER_BIT);
    shader_set.use();
    
    // ERROR CAUSED BELOW:
    // This Case Fails:
    const myUniform = gl.getUniformLocation(shader_set.id, "myUniform"); // will be 0
    std.debug.print("What is this: {s}\n", .{ @typeName(@TypeOf(myUniform)) });
    std.debug.print("????? {} => {s}\n", .{ myUniform != -1, @typeName(@TypeOf(myUniform)) });
    
    // This Case Fails:
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform"); // will be 0
    // if (myUniform == -1) {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // This Case Fails:
    // const myUniform = gl.getUniformLocation(shader_set.id, "notFoundUniform"); // will be -1
    // if (myUniform == -1) {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // This Case Succeeds
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform"); // will be 0
    // if (myUniform == 0) { // I know that it will be zero in this test
    //     std.debug.print("The uniform WAS found!\n", .{});
    // }

    // This Case Succeeds
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform"); // will be 0
    // if (myUniform == 0) { // I know that it will be zero in this test
    //     std.debug.print("The uniform WAS found!\n", .{});
    // } else {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // This Case Succeeds
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform");
    // std.debug.print("What is this: {} = {s}\n", .{ myUniform != 1, @typeName(@TypeOf(myUniform)) });

    // This Case Fails
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform");
    // std.debug.print("What is this: {} = {s}\n", .{ myUniform != -2, @typeName(@TypeOf(myUniform)) });

    // This Case Fails
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform");
    // std.debug.print("What is this: {} = {s}\n", .{ myUniform != -2000, @typeName(@TypeOf(myUniform)) });

    // This Case Succeeds
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform");
    // std.debug.print("What is this: {} = {s}\n", .{ myUniform != 2000, @typeName(@TypeOf(myUniform)) });

    // This Case Succeeds (and confirms that myUniform is a `c_int` when it succeeds)
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform");
    // std.debug.print("What is this: {s}\n", .{ @typeName(@TypeOf(myUniform)) });

    // This Case Succeeds
    // const c: gl.Int = @as(gl.Int, 0);
    // if (c == -1) {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // This Case Succeeds
    // const c: gl.Int = @intCast(gl.Int, 0);
    // if (c == -1) {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // This Case Succeeds
    // const c: c_int = @intCast(c_int, 0);
    // if (c == -1) {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // This Case Fails
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform");
    // const c: gl.Int = @intCast(gl.Int, myUniform);
    // if (c == -1) {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // This Case Fails
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform");
    // const c: c_int = @intCast(c_int, myUniform);
    // if (c == -1) {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // This Case Succeeds only when the uniform is found and is non-negative...
    // const myUniform = gl.getUniformLocation(shader_set.id, "myUniform");
    // const c: c_uint = @intCast(c_uint, myUniform); // wtf
    // if (c == -1) {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // This Case Fails cause of a negative (with the expected error)
    // const myUniform = gl.getUniformLocation(shader_set.id, "notFound");
    // const c: c_uint = @intCast(c_uint, myUniform);
    // if (c == -1) {
    //     std.debug.print("The uniform was not found!\n", .{});
    // }

    // Doing or not doing anything with the uniform at this point appears irrelevant.

    entity.draw();

    window.swapBuffers();
}


pub fn main() !void {
    // Do all the setup crap and then start calling render() in a loop until we quit.
}
```

This all works correctly UNTIL I try to do a comparison on `myUniform` with a negative number. `c.glGetUniformLocation` should be returning a c_int (meaning signed) and debug statements appear to confirm it is a c_int. Printing the actual value also returns 0 and -1 as expected for a found and not found uniform in the shader respectively.

### Expected Behavior

I hoped for a beautiful triangle.

<img width="654" alt="Bildschirmfoto 2021-12-24 um 13 10 12" src="https://user-images.githubusercontent.com/13559026/147369789-1cbb99d2-6040-4caa-a0bd-ba5d1bf1bcfc.png">

### Actual Behavior

But was given (to my untrained eye) a linking error:

Output:

```shell
$ zig build open
GLFW 3.3.5
Hello!
BufferTarget.ARRAY_BUFFER
BufferTarget.ARRAY_BUFFER
window focus callback: 1
time: 1.41127382e-01
dyld: lazy symbol binding failed: Symbol not found: _sincos
  Referenced from: /__some/user/path/here__/game/zig-out/bin/game
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _sincos
  Referenced from: /__some/user/path/here__/game/zig-out/bin/game
  Expected in: /usr/lib/libSystem.B.dylib

The following command terminated unexpectedly:
cd /__some/user/path/here__/game && /__some/user/path/here__/game/zig-out/bin/game
error: the following build command failed with exit code 1:
/__some/user/path/here__/game/zig-cache/o/5834b2653be7577b4b4cc773fd847b4d/build /usr/local/Cellar/zig/0.8.1_1/bin/zig /__some/user/path/here__/game /__some/user/path/here__/game/zig-cache /Users/***/.cache/zig open
```

This appears to be failing to link whatever lib is needed for the `sin` and `cos` builtins that I was successfully using well before this started happening.

**Comment by tiehuis** [comment] 2021-12-25 01:38
Related https://github.com/ziglang/zig/issues/10318. I imagine the success/failure differences are just whichever heuristic happening to trigger from the negative compare. The linked issue is the underlying link cause.

**Comment by andrewrk** [comment] 2021-12-27 22:05
Closing as duplicate of #10318.

**Closed by andrewrk** 2021-12-27 22:05 UTC
Labels: bug
