### ISSUE TITLE
Proposal: Coerce error union with empty error set to value type

### ISSUE THREAD

**Issue by jessrud** [ziglang/zig#5798] opened 2020-07-05 19:39 UTC
Currently, one has to write error handling code for error union values who's error set is empty;

```zig
// infered return type of `error{}!usize`
fn foo() !usize {
    return 10;
}
fn bar() void {
  const x:usize = foo() catch unreachable;
}
```
If this proposal is accepted and implemented, one would beable to implement `bar()` above as:

```zig
fn bar() void {
    const x:usize = foo(); //OK `error{}!usize` coerces to `usize`
}
```

This has implications for consumers of generic interfaces like Reader and Writer that are constructed using an error set type, for which implementations may in reality have no error conditions to cover, and provide an empty error set to the type constructor:

```zig
const MyWriter = io.Writer(context,error {},writeFn);
var mywriter: MyWriter = ...;

fn doSomething() !void {
    _ = try mywriter.write() // propagating empty error set for no reason
}

fn doSomethingElse() void {
    _ = mywriter.write() catch ...; //noisy code for handling empty error sets
}
```

**Comment by Vexu** [comment] 2020-07-05 20:35
Duplicate of #5226.

**Closed by Vexu** 2020-07-05 20:35 UTC
