### ISSUE TITLE
varargs with pointer to stack array crashes the compiler

### ISSUE THREAD

**Issue by paperdave** [ziglang/zig#17494] opened 2023-10-12 09:35 UTC
### Zig Version

0.12.0-dev.888+130227491

### Steps to Reproduce and Observed Behavior

`zig build-exe main.zig`
```
fn loser(...) callconv(.C) void {}

pub fn main() !void {
    var tmp: [80]u8 = undefined;
    _ = loser("aloha", &tmp);
}
```

Below is the compiler output on a debug build of zig, which i compiled just now.

```
thread 2614405 panic: reached unreachable code
Analyzing main.zig: main.zig:main
    > %28 = validate_ref_ty(%25) token_offset:5:24 to :5:25
      %29 = break_inline(%25, %19)
    For full context, use the command
      zig ast-check -t main.zig

  in main.zig: main.zig:main
    > %25 = call(.auto, %23, [
        {%26, %27},
        {%28, %29},
      ]) node_offset:5:9 to :5:29
  in main.zig: main.zig:main
    > %12 = block({%13..%33}) node_offset:3:21 to :3:21
  in build/stage3/lib/zig/std/start.zig: start.zig:callMain
    > %2830 = is_non_err(%2829) 
  in build/stage3/lib/zig/std/start.zig: start.zig:callMain
    > %2832 = block({%2826..%2831}) 
  in build/stage3/lib/zig/std/start.zig: start.zig:callMain
    > %2823 = block({%2824..%2970}) 
  in build/stage3/lib/zig/std/start.zig: start.zig:callMain
    > %2734 = switch_block(%2732,
        else => {%2973..%2979},
        %2735 => {%2736..%2748},
        %2749 => {%2750..%2768},
        by_val %2769 => {%2770..%2820},
        %2821 => {%2822..%2972}) 
  in build/stage3/lib/zig/std/start.zig: start.zig:callMain
    > %2718 = block({%2719..%2983}) 
  in build/stage3/lib/zig/std/start.zig: start.zig:initEventLoopAndCallMain
    > %2441 = builtin_call(%2439, %2440, @InternPool.Index.empty_struct) 
  in build/stage3/lib/zig/std/start.zig: start.zig:initEventLoopAndCallMain
    > %2286 = block({%2287..%2448}) 
  in build/stage3/lib/zig/std/start.zig: start.zig:callMainWithArgs
    > %2063 = call(.auto, %2061, []) 
  in build/stage3/lib/zig/std/start.zig: start.zig:callMainWithArgs
    > %2026 = block({%2027..%2070}) 
  in build/stage3/lib/zig/std/start.zig: start.zig:main
    > %2221 = builtin_call(%2207, %2208, %2220) 
  in build/stage3/lib/zig/std/start.zig: start.zig:main
    > %2092 = block({%2093..%2228}) 

lib/std/debug.zig:342:14: 0x1024ee2cb in assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
src/Sema.zig:1903:11: 0x1032858e7 in resolveType (zig)
    assert(air_inst != .var_args_param_type);
          ^
src/Sema.zig:4374:40: 0x102e51a33 in zirValidateRefTy (zig)
    const ty_operand = sema.resolveType(block, src, un_tok.operand) catch |err| switch (err) {
                                       ^
src/Sema.zig:1424:42: 0x102a5f18b in analyzeBodyInner (zig)
                try sema.zirValidateRefTy(block, inst);
                                         ^
src/Sema.zig:934:45: 0x10281baf3 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
src/Sema.zig:883:50: 0x1032a8d07 in resolveBody (zig)
    const break_data = (try sema.analyzeBodyBreak(block, body)) orelse
                                                 ^
src/Sema.zig:7018:59: 0x1037416ab in analyzeArg (zig)
                const uncoerced_arg = try sema.resolveBody(block, arg_body, zir_call.call_inst);
                                                          ^
src/Sema.zig:7574:49: 0x1032b1c4f in analyzeCall (zig)
            arg_out.* = try args_info.analyzeArg(sema, block, arg_idx, param_ty, func_ty_info, func);
                                                ^
src/Sema.zig:6729:43: 0x102db2317 in zirCall__anon_160035 (zig)
    const call_inst = try sema.analyzeCall(block, func, func_ty, callee_src, call_src, modifier, ensure_result_used, args_info, call_dbg_node, .call);
                                          ^
src/Sema.zig:1029:62: 0x102a5371b in analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst, .direct),
                                                             ^
src/Sema.zig:5891:34: 0x103350f07 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
src/Sema.zig:5874:33: 0x102e6001b in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
src/Sema.zig:1578:49: 0x102a63867 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
src/Sema.zig:917:30: 0x102d55857 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
src/Module.zig:4822:21: 0x102a313fb in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
src/Module.zig:3398:40: 0x1027fdc9f in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func_index, sema_arena) catch |err| switch (err) {
                                       ^
src/Sema.zig:31681:31: 0x10336fd6f in ensureFuncBodyAnalyzed (zig)
    mod.ensureFuncBodyAnalyzed(func) catch |err| {
                              ^
src/Sema.zig:35426:40: 0x102e83cf3 in resolveInferredErrorSet (zig)
        try sema.ensureFuncBodyAnalyzed(func_index);
                                       ^
src/Sema.zig:32036:69: 0x102e5ceeb in analyzeIsNonErrComptimeOnly (zig)
                const resolved_ty = try sema.resolveInferredErrorSet(block, src, set_ty);
                                                                    ^
src/Sema.zig:32065:56: 0x1032c28b3 in analyzeIsNonErr (zig)
    const result = try sema.analyzeIsNonErrComptimeOnly(block, src, operand);
                                                       ^
src/Sema.zig:18321:32: 0x102dbfc2b in zirIsNonErr (zig)
    return sema.analyzeIsNonErr(block, src, operand);
                               ^
src/Sema.zig:1072:66: 0x102a55647 in analyzeBodyInner (zig)
            .is_non_err                   => try sema.zirIsNonErr(block, inst),
                                                                 ^
src/Sema.zig:5891:34: 0x103350f07 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
src/Sema.zig:5874:33: 0x102e6001b in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
src/Sema.zig:1578:49: 0x102a63867 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
src/Sema.zig:5891:34: 0x103350f07 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
src/Sema.zig:5874:33: 0x102e6001b in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
src/Sema.zig:1578:49: 0x102a63867 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
src/Sema.zig:5891:34: 0x103350f07 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
src/Sema.zig:10608:45: 0x1032df047 in resolveProngComptime (zig)
                return sema.resolveBlockBody(spa.parent_block, src, child_block, prong_body, spa.switch_block_inst, merges);
                                            ^
src/Sema.zig:11842:52: 0x102dcede7 in zirSwitchBlock (zig)
                    return spa.resolveProngComptime(
                                                   ^
src/Sema.zig:1095:69: 0x102a56753 in analyzeBodyInner (zig)
            .switch_block                 => try sema.zirSwitchBlock(block, inst, false),
                                                                    ^
src/Sema.zig:5891:34: 0x103350f07 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
src/Sema.zig:5874:33: 0x102e6001b in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
src/Sema.zig:1578:49: 0x102a63867 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
src/Sema.zig:917:30: 0x102d55857 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
src/Sema.zig:7510:33: 0x1032b0e8b in analyzeCall (zig)
                sema.analyzeBody(&child_block, fn_info.body) catch |err| switch (err) {
                                ^
src/Sema.zig:23954:28: 0x102e06bdb in zirBuiltinCall (zig)
    return sema.analyzeCall(
                           ^
src/Sema.zig:1147:69: 0x102a58dbf in analyzeBodyInner (zig)
            .builtin_call                 => try sema.zirBuiltinCall(block, inst),
                                                                    ^
src/Sema.zig:5891:34: 0x103350f07 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
src/Sema.zig:5874:33: 0x102e6001b in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
src/Sema.zig:1578:49: 0x102a63867 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
src/Sema.zig:917:30: 0x102d55857 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
src/Sema.zig:7510:33: 0x1032b0e8b in analyzeCall (zig)
                sema.analyzeBody(&child_block, fn_info.body) catch |err| switch (err) {
                                ^
src/Sema.zig:6729:43: 0x102db2317 in zirCall__anon_160035 (zig)
    const call_inst = try sema.analyzeCall(block, func, func_ty, callee_src, call_src, modifier, ensure_result_used, args_info, call_dbg_node, .call);
                                          ^
src/Sema.zig:1029:62: 0x102a5371b in analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst, .direct),
                                                             ^
src/Sema.zig:5891:34: 0x103350f07 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
src/Sema.zig:5874:33: 0x102e6001b in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
src/Sema.zig:1578:49: 0x102a63867 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
src/Sema.zig:917:30: 0x102d55857 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
src/Sema.zig:7510:33: 0x1032b0e8b in analyzeCall (zig)
                sema.analyzeBody(&child_block, fn_info.body) catch |err| switch (err) {
                                ^
src/Sema.zig:23954:28: 0x102e06bdb in zirBuiltinCall (zig)
    return sema.analyzeCall(
                           ^
src/Sema.zig:1147:69: 0x102a58dbf in analyzeBodyInner (zig)
            .builtin_call                 => try sema.zirBuiltinCall(block, inst),
                                                                    ^
src/Sema.zig:5891:34: 0x103350f07 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
src/Sema.zig:5874:33: 0x102e6001b in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
src/Sema.zig:1578:49: 0x102a63867 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
src/Sema.zig:917:30: 0x102d55857 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
src/Module.zig:4822:21: 0x102a313fb in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
src/Module.zig:3398:40: 0x1027fdc9f in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func_index, sema_arena) catch |err| switch (err) {
                                       ^
src/Compilation.zig:3469:42: 0x1027fc02f in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
src/Compilation.zig:3406:30: 0x10265048f in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
src/Compilation.zig:2211:31: 0x10264bebb in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
src/main.zig:4214:24: 0x102677997 in updateModule (zig)
        try comp.update(main_progress_node);
                       ^
src/main.zig:3617:17: 0x102697947 in buildOutputType (zig)
    updateModule(comp) catch |err| switch (err) {
                ^
src/main.zig:269:31: 0x1024d8f43 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
src/main.zig:213:20: 0x1024d67ab in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
lib/std/start.zig:583:37: 0x1024d63ab in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x1ab92ff27 in ??? (???)
???:?:?: 0x92587fffffffffff in ??? (???)
```

### Expected Behavior

Should compile, but compiler crashes.

I suspect this is due to this: https://github.com/ziglang/zig/commit/09a57583a4ccce30603ffc8d0e3d7359dc3cb978 (may be wrong, but the blame shows 3 weeks ago which is very recent)

This blocks Bun's zig upgrade from 0.12.0-dev.163+6780a6bbf

**Comment by paperdave** [comment] 2023-10-12 09:44
![image](https://github.com/ziglang/zig/assets/24465214/1cca2481-dfcc-483e-8ab5-f5540dfc6276)
using a temporary variable with a slice is the current workaround

**Comment by Vexu** [comment] 2023-10-12 09:48
Duplicate of #16197

**Comment by andrewrk** [comment] 2023-10-13 07:16
Thanks for the nice reduction and debug output. This is indeed a distinct crash from #16197.

**Closed** 2023-10-13 15:16 UTC
Labels: bug, frontend
