### ISSUE TITLE
vector overflow intrinsic behavior tests do not actually provide test coverage; llvm backend failing

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#13633] opened 2022-11-23 06:37 UTC
https://github.com/ziglang/zig/blob/32ce2f91a92c23d46c6836a6dd68ae0f08bb04c5/test/behavior/vector.zig#L972-L1090

The operands to `@addWithOverflow` and friends are comptime-known, making these tests only test this operation at comptime. It's supposed to also test it at runtime.

When this is fixed, such as doing the following diff, it crashes the LLVM backend:

```diff
--- a/test/behavior/vector.zig
+++ b/test/behavior/vector.zig
@@ -977,9 +977,11 @@ test "@addWithOverflow" {
         fn doTheTest() !void {
             {
                 var result: @Vector(4, u8) = undefined;
-                var overflow = @addWithOverflow(@Vector(4, u8), @Vector(4, u8){ 250, 250, 250, 250 }, @Vector(4, u8){ 0, 5, 6, 10 }, &result);
-                var expected: @Vector(4, bool) = .{ false, false, true, true };
-                try expect(mem.eql(bool, &@as([4]bool, overflow), &@as([4]bool, expected)));
+                var lhs = @Vector(4, u8){ 250, 250, 250, 250 };
+                var rhs = @Vector(4, u8){ 0, 5, 6, 10 };
+                var overflow = @addWithOverflow(@Vector(4, u8), lhs, rhs, &result);
+                var expected: @Vector(4, u1) = .{ 0, 0, 1, 1 };
+                try expect(mem.eql(u1, &@as([4]u1, overflow), &@as([4]u1, expected)));
             }
             {
                 var result: @Vector(4, i8) = undefined;
```

```
$ stage4/bin/zig test ../test/behavior.zig -I../test 
Semantic Analysis [4164] shuffleVectorIndex... thread 3438856 panic: reached unreachable code
Analyzing ../test/behavior/vector.zig: behavior/vector.zig:test.@addWithOverflow
      %10941 = dbg_block_begin()
      %10942 = dbg_stmt(2, 9)
      %10950 = block({
        %10943 = decl_val("builtin") token_offset:967:9 to :967:16
        %10944 = dbg_stmt(2, 16)
        %10945 = field_val(%10943, "zig_backend") node_offset:967:9 to :967:28
        %10946 = enum_literal("stage1") token_offset:967:33 to :967:39
        %10947 = cmp_eq(%10945, %10946) node_offset:967:9 to :967:39
        %10948 = as_node(@Zir.Inst.Ref.bool_type, %10947) node_offset:967:9 to :967:39
        %10949 = condbr(%10948, {
          %10951 = dbg_block_begin()
          %10958 = dbg_block_end()
          %10952 = block({
            %10953 = dbg_block_begin()
            %10954 = dbg_stmt(4, 9)
            %10955 = dbg_stmt(4, 9)
            %10957 = dbg_block_end()
            %10956 = ret_err_value("SkipZigTest") token_offset:969:22 to :969:33
          }) node_offset:967:41 to :967:42
          %10959 = break(%10950, @Zir.Inst.Ref.void_value)
        }, {
          %10960 = break(%10950, @Zir.Inst.Ref.void_value)
        }) node_offset:967:5 to :967:7
      }) node_offset:967:5 to :967:7
      %10961 = ensure_result_used(%10950) node_offset:967:5 to :967:7
      %10962 = dbg_stmt(6, 9)
      %10970 = block({
        %10963 = decl_val("builtin") token_offset:971:9 to :971:16
        %10964 = dbg_stmt(6, 16)
        %10965 = field_val(%10963, "zig_backend") node_offset:971:9 to :971:28
        %10966 = enum_literal("stage2_wasm") token_offset:971:33 to :971:44
        %10967 = cmp_eq(%10965, %10966) node_offset:971:9 to :971:44
        %10968 = as_node(@Zir.Inst.Ref.bool_type, %10967) node_offset:971:9 to :971:44
        %10969 = condbr(%10968, {
          %10971 = dbg_block_begin()
          %10972 = dbg_stmt(6, 46)
          %10973 = dbg_stmt(6, 46)
          %10975 = dbg_block_end()
          %10974 = ret_err_value("SkipZigTest") token_offset:971:59 to :971:70
        }, {
          %10976 = break(%10970, @Zir.Inst.Ref.void_value)
        }) node_offset:971:5 to :971:70
      }) node_offset:971:5 to :971:70
      %10977 = ensure_result_used(%10970) node_offset:971:5 to :971:70
      %10978 = dbg_stmt(7, 9)
      %10986 = block({
        %10979 = decl_val("builtin") token_offset:972:9 to :972:16
        %10980 = dbg_stmt(7, 16)
        %10981 = field_val(%10979, "zig_backend") node_offset:972:9 to :972:28
        %10982 = enum_literal("stage2_x86_64") token_offset:972:33 to :972:46
        %10983 = cmp_eq(%10981, %10982) node_offset:972:9 to :972:46
        %10984 = as_node(@Zir.Inst.Ref.bool_type, %10983) node_offset:972:9 to :972:46
        %10985 = condbr(%10984, {
          %10987 = dbg_block_begin()
          %10988 = dbg_stmt(7, 48)
          %10989 = dbg_stmt(7, 48)
          %10991 = dbg_block_end()
          %10990 = ret_err_value("SkipZigTest") token_offset:972:61 to :972:72
        }, {
          %10992 = break(%10986, @Zir.Inst.Ref.void_value)
        }) node_offset:972:5 to :972:72
      }) node_offset:972:5 to :972:72
      %10993 = ensure_result_used(%10986) node_offset:972:5 to :972:72
      %10994 = dbg_stmt(8, 9)
      %11002 = block({
        %10995 = decl_val("builtin") token_offset:973:9 to :973:16
        %10996 = dbg_stmt(8, 16)
        %10997 = field_val(%10995, "zig_backend") node_offset:973:9 to :973:28
        %10998 = enum_literal("stage2_aarch64") token_offset:973:33 to :973:47
        %10999 = cmp_eq(%10997, %10998) node_offset:973:9 to :973:47
        %11000 = as_node(@Zir.Inst.Ref.bool_type, %10999) node_offset:973:9 to :973:47
        %11001 = condbr(%11000, {
          %11003 = dbg_block_begin()
          %11004 = dbg_stmt(8, 49)
          %11005 = dbg_stmt(8, 49)
          %11007 = dbg_block_end()
          %11006 = ret_err_value("SkipZigTest") token_offset:973:62 to :973:73
        }, {
          %11008 = break(%11002, @Zir.Inst.Ref.void_value)
        }) node_offset:973:5 to :973:73
      }) node_offset:973:5 to :973:73
      %11009 = ensure_result_used(%11002) node_offset:973:5 to :973:73
      %11010 = dbg_stmt(9, 9)
      %11018 = block({
        %11011 = decl_val("builtin") token_offset:974:9 to :974:16
        %11012 = dbg_stmt(9, 16)
        %11013 = field_val(%11011, "zig_backend") node_offset:974:9 to :974:28
        %11014 = enum_literal("stage2_arm") token_offset:974:33 to :974:43
        %11015 = cmp_eq(%11013, %11014) node_offset:974:9 to :974:43
        %11016 = as_node(@Zir.Inst.Ref.bool_type, %11015) node_offset:974:9 to :974:43
        %11017 = condbr(%11016, {
          %11019 = dbg_block_begin()
          %11020 = dbg_stmt(9, 45)
          %11021 = dbg_stmt(9, 45)
          %11023 = dbg_block_end()
          %11022 = ret_err_value("SkipZigTest") token_offset:974:58 to :974:69
        }, {
          %11024 = break(%11018, @Zir.Inst.Ref.void_value)
        }) node_offset:974:5 to :974:69
      }) node_offset:974:5 to :974:69
      %11025 = ensure_result_used(%11018) node_offset:974:5 to :974:69
      %11026 = dbg_stmt(11, 5)
      %11027 = extended(struct_decl(dbg_var, Auto, {
        [20873] doTheTest line(11) hash(3a3c1148112394fd62bb5c593196f0f1): %11028 = ...
      }, {}, {}) node_offset:976:15 to :976:21
      %11391 = ref(%11027) token_offset:1006:9 to :1006:10
      %11389 = dbg_var_val(%11027, "S")
      %11390 = dbg_stmt(41, 5)
      %11392 = dbg_stmt(41, 10)
      %11393 = field_call_bind(%11391, "doTheTest") node_offset:1006:9 to :1006:20
      %11394 = dbg_stmt(41, 20)
      %11395 = call(.auto, %11393, []) node_offset:1006:9 to :1006:22
    > %11396 = try(%11395, {
        %11397 = err_union_code(%11395) node_offset:1006:5 to :1006:22
        %11398 = dbg_stmt(41, 5)
        %11399 = ret_node(%11397) node_offset:1006:5 to :1006:22
      }) node_offset:1006:5 to :1006:22
      %11400 = ensure_result_used(%11396) node_offset:1006:5 to :1006:22
      %11401 = dbg_stmt(42, 5)
      %11402 = field_call_bind(%11391, "doTheTest") node_offset:1007:18 to :1007:29
      %11403 = dbg_stmt(42, 29)
      %11404 = call(.compile_time, %11402, []) node_offset:1007:18 to :1007:31
      %11405 = try(%11404, {
        %11406 = err_union_code(%11404) node_offset:1007:14 to :1007:31
        %11407 = ret_node(%11406) node_offset:1007:14 to :1007:31
      }) node_offset:1007:14 to :1007:31
      %11409 = dbg_block_end()
      %11408 = ensure_result_used(%11405) node_offset:1007:5 to :1007:31
      %11410 = restore_err_ret_index(%10940, @Zir.Inst.Ref.none)
      %11411 = break(%10940, @Zir.Inst.Ref.void_value)
    For full context, use the command
      zig ast-check -t ../test/behavior/vector.zig

  in ../test/behavior/vector.zig: behavior/vector.zig:test.@addWithOverflow
    > %10940 = block({%10941..%11411}) node_offset:966:25 to :966:26

codegen/llvm.zig:3886:29: 0x56d058a in lowerValue (zig)
codegen/llvm.zig:4422:48: 0x5db9718 in resolveValue (zig)
codegen/llvm.zig:4415:40: 0x5db9cb1 in resolveInst (zig)
codegen/llvm.zig:5130:47: 0x5dd65c0 in airCmpVector (zig)
codegen/llvm.zig:4536:63: 0x5a149cd in genBody (zig)
codegen/llvm.zig:1209:35: 0x5a10bf4 in updateFunc (zig)
link/Elf.zig:2410:74: 0x5a19752 in updateFunc (zig)
/home/andy/dev/zig/src/link.zig:563:77: 0x5823abd in updateFunc (zig)
            .elf   => return @fieldParentPtr(Elf,   "base", base).updateFunc(module, func, air, liveness),
                                                                            ^
/home/andy/dev/zig/src/Module.zig:4381:37: 0x567864c in ensureFuncBodyAnalyzed (zig)
            comp.bin_file.updateFunc(mod, func, air, liveness) catch |err| switch (err) {
                                    ^
/home/andy/dev/zig/src/Sema.zig:27402:36: 0x5f5342f in ensureFuncBodyAnalyzed (zig)
    sema.mod.ensureFuncBodyAnalyzed(func) catch |err| {
                                   ^
/home/andy/dev/zig/src/Sema.zig:29550:44: 0x5b3ecad in resolveInferredErrorSet (zig)
        try sema.ensureFuncBodyAnalyzed(ies.func);
                                           ^
/home/andy/dev/zig/src/Sema.zig:27681:49: 0x5b0f7e3 in analyzeIsNonErrComptimeOnly (zig)
                try sema.resolveInferredErrorSet(block, src, ies);
                                                ^
/home/andy/dev/zig/src/Sema.zig:16245:60: 0x5b0e812 in zirTry (zig)
    const is_non_err = try sema.analyzeIsNonErrComptimeOnly(parent_block, operand_src, err_union);
                                                           ^
/home/andy/dev/zig/src/Sema.zig:1505:67: 0x584dff3 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirTry(block, inst);
                                                                  ^
/home/andy/dev/zig/src/Sema.zig:5135:34: 0x5ec60cc in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/andy/dev/zig/src/Sema.zig:5118:85: 0x5b0b30e in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                                                                    ^
/home/andy/dev/zig/src/Sema.zig:1351:69: 0x584b56e in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/andy/dev/zig/src/Sema.zig:702:30: 0x5a01778 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/andy/dev/zig/src/Module.zig:5641:43: 0x58212fb in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                                          ^
/home/andy/dev/zig/src/Module.zig:4340:40: 0x56780e2 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/andy/dev/zig/src/Compilation.zig:3142:42: 0x5675f6d in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/andy/dev/zig/src/Compilation.zig:3080:30: 0x5561b1e in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/andy/dev/zig/src/Compilation.zig:2389:31: 0x555da58 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/andy/dev/zig/src/main.zig:3351:20: 0x5589d66 in updateModule (zig)
    try comp.update();
                   ^
/home/andy/dev/zig/src/main.zig:3018:17: 0x54790b1 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/andy/dev/zig/src/main.zig:236:31: 0x5453b65 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/andy/dev/zig/src/main.zig:174:20: 0x5452fc0 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/dev/zig/lib/std/start.zig:614:37: 0x5455541 in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7fcdc8098236 in ??? (???)
???:?:?: 0x7ffdd5dadb76 in ??? (???)
???:?:?: 0x740067697a2f6e68 in ??? (???)
Aborted (core dumped)
```

**Comment by Vexu** [comment] 2022-11-23 12:27
Duplicate of #13201

**Closed by Vexu** 2022-11-23 12:27 UTC
Labels: bug, stage2, backend-llvm
