### ISSUE TITLE
stage2: enum declared with incorrect values causes segfault

### ISSUE THREAD

**Issue by ilmaria** [ziglang/zig#12955] opened 2022-09-24 16:44 UTC
### Zig Version

0.10.0-dev.4166+cae76d829

### Steps to Reproduce

The following code crashes the stage2 compiler with the LLVM backend:

```zig
pub const En = enum(u8) {
    a = 1,
    b = 1, // using same value twice causes segfault
};

test {
    var b: En = .a;
    _ = b;
}
```

I tested this on M1 mac.

### Expected Behavior

I expected to get some kind of error message like stage1 compiler gives:
```shell
$ zig test -fstage1 test.zig
./test.zig:3:5: error: enum tag value 1 already taken
    b = 1, // using same value twice causes segfault
    ^
./test.zig:2:5: note: other occurrence here
    a = 1,
```

### Actual Behavior

```shell
$ zig test test.zig
zsh: segmentation fault  zig test test.zig
```

**Comment by Vexu** [comment] 2022-09-24 16:54
Duplicate of #12805

**Closed by Vexu** 2022-09-24 16:54 UTC
Labels: bug
