### ISSUE TITLE
packed array bug

### ISSUE THREAD

**Issue by htqx** [ziglang/zig#12332] opened 2022-08-04 09:36 UTC
### Zig Version

0.10.0-dev.2977+7d2e14267

### Steps to Reproduce

```zig
  const p5 = &packed struct{a:u32=1,b:[3]u8=.{2}**3,c:[20]u8=.{3}**20};
   var p6 = p5.*{};
   var p7:[20]u8 align(@alignOf(@TypeOf(p6.c))) = p6.c;

std.testing.expect(p7[0] == p6.c[0]) catch print("p7[0] ~= p6.c[0]",.{});
```
output: p7[0] ~= p6.c[0]
vars: 3 2

### Expected Behavior

==

### Actual Behavior

~=

**Comment by Vexu** [comment] 2022-08-04 10:05
Duplicate of https://github.com/ziglang/zig/issues/2627

**Closed by Vexu** 2022-08-04 10:05 UTC
Labels: bug
