### ISSUE TITLE
Autodoc: Importing Unknown Module Causes Segmentation Fault with `-femit-docs`

### ISSUE THREAD

**Issue by Tesseract22** [ziglang/zig#17512] opened 2023-10-13 18:44 UTC
## Zig Version
```bash
$ zig version
0.12.0-dev.817+54e7f58fc
```
## Bug Reproduction
```zig
// main.zig
const unknown_module = @import("abc");
pub fn main() void {
  // unknown_module is never used
}
```

Compiling with `zig build-exe main.zig -femit-docs` results in:

```
$ zig build-exe src/main.zig -femit-docs
Generating documentation... Segmentation fault (core dumped)
```
### Expected behavior
Compile and generate docs succuessfully because `unknown_module` is never referenced (this is how `-femit-h` behaves right now).
Or perhaps something similar to:
```
main.zig:2:32: error: no package named 'abc' available within package 'root'
const unknown_module = @import("abc");
```

**Comment by ianprime0509** [comment] 2023-10-14 00:33
Duplicate of #13512

**Closed** 2023-10-14 08:21 UTC
Labels: autodoc
