### ISSUE TITLE
Build reproducibility on `aarch64-macos`: resulting binary depends on filename even with `-fstrip`.

### ISSUE THREAD

**Issue by bfreis** [ziglang/zig#19520] opened 2024-04-03 14:15 UTC
### Zig Version

- 0.12.0-dev.3518+d2be725e4
- 0.12.0-dev.3522+b88ae8dbd

### Steps to Reproduce and Observed Behavior

Create a simple "hello, world" application, build it twice with ReleaseSafe, compare the generated binaries:

```
$ cat <<EOF > main.zig
pub fn main() void {
    @import("std").debug.print("Hello, world!", .{});
}
EOF

$ zig build-exe -O ReleaseSafe -femit-bin=main1 -fstrip main.zig \
  && zig build-exe -O ReleaseSafe -femit-bin=main2 -fstrip main.zig \
  && sha256sum main1 main2
95506b1273e77b37222f04539d7d18fbbd7e8ba289a15489b5628d868aacf007  main1
3b0bd89d5aa8eaf64c0b49aee348f2d41ef65232591f39b59bbefd82912f2be1  main2
```

EDIT: added `-fstrip` based on this comment: https://github.com/ziglang/zig/issues/13919#issuecomment-1355299067 . Binaries still differ even with `-fstrip`

EDIT: this seems to happen on `-target aarch64-macos`, but not on some other targets tested (`x86_64-macos` is fine, so is `x86_64-linux-gnu`). The problem seems to be scoped to some very specific target or targets. See discussion below.

### Expected Behavior

The binaries should be identical.

This is pretty much the same issue as https://github.com/ziglang/zig/issues/13919 .

**Comment by RossComputerGuy** [comment] 2024-04-03 14:26
Binaries are almost never always the exact same.

**Comment by bfreis** [comment] 2024-04-03 14:33
> Binaries are almost never always the exact same.

It's not a matter of how often binaries are identical or not — the claim of reproducible builds implies that they should be exactly the same, which is an extremely useful property, for example, to validate builds.

**Comment by RossComputerGuy** [comment] 2024-04-03 14:38
> > Binaries are almost never always the exact same.
> 
> It's not a matter of how often binaries are identical or not — the claim of reproducible builds implies that they should be exactly the same, which is an extremely useful property, for example, to validate builds.

Reproducible builds doesn't mean reproducible binaries. Nix has the same issue.

**Comment by bfreis** [comment] 2024-04-03 14:43
@RossComputerGuy — thanks for your opinion, but the context of the linked issue seems to completely disagree with your interpretation. It clearly shows the exact same behavior I describe here, that's considered a regression; it finally gets to a state where binaries are bit-by-bit identical to close the issue.

**Comment by RossComputerGuy** [comment] 2024-04-03 14:49
> thanks for your opinion

It's not an opinion, ime often binaries aren't going to be but for bit the same.

> but the context of the linked issue seems to completely disagree with your interpretation. It clearly shows the exact same behavior I describe here, that's considered a regression; it finally gets to a state where binaries are bit-by-bit identical to close the issue.

I wasn't aware that Zig can produce bit by bit identical binaries with my knowledge of how binaries are. You probably should get the binary diff and share what's different.

**Comment by bfreis** [comment] 2024-04-03 14:53
> I wasn't aware that Zig can produce bit by bit identical binaries with my knowledge of how binaries are.

Let's try to keep this discussion production?

Please read the linked issue carefully, particularly the comment I directly linked. It shows Zig producing bit-by-bit identical binaries. Also, check the CI test that validates that stage3 and stage4 binaries are bit-by-bit identical.

**Comment by bfreis** [comment] 2024-04-03 15:18
I think I found the problem.

The flag `-fstrip` isn't enough for reproducible builds — it's also required that the `X` in `-femit-bin=X` have identical filenames.

With the initial example, I'm using `-femit-bin=main1` and then `-femit-bin=main2`. But apparently `-fstrip` isn't enough to eliminate some difference in the built binary.

Anyways, doing it this way makes the builds reproducible:
```
$ cat <<EOF > main.zig
pub fn main() void {
    @import("std").debug.print("Hello, world!", .{});
}
EOF

$ rm -rf build{1,2} \
  && mkdir -p build{1,2} \
  && zig build-exe -O ReleaseSafe -femit-bin=build1/foo -fstrip main.zig \
  && zig build-exe -O ReleaseSafe -femit-bin=build2/bar -fstrip main.zig \
  && sha256sum build{1,2}/main

81d9c9bb985b30189d7241502e3a72d319b995899b29aa5af21b1f43d68f18f5  build1/main
81d9c9bb985b30189d7241502e3a72d319b995899b29aa5af21b1f43d68f18f5  build2/main
```

It seems that the built binary contains the filename where it was initially written to. If I change the `-femit-bin` above to emit `build1/foo` and `build2/bar` (keeping the build arguments otherwise identical), I get this:

```
$ diff <(hexdump -C build1/foo) <(hexdump -C build2/bar)

886c886
< 0000c880  00 00 3a 88 00 00 00 00  00 00 00 01 66 6f 6f 00  |..:.........foo.|
---
> 0000c880  00 00 3a 88 00 00 00 00  00 00 00 01 62 61 72 00  |..:.........bar.|
```

What's the rationale?

**Comment by jayschwa** [comment] 2024-04-03 15:38
Using the example in your original post, I'm getting identical builds with Zig 0.12.0-dev.3522+b88ae8dbd:

``` sh
zig build-exe -O ReleaseSafe -femit-bin=main1 -fstrip main.zig   && zig build-exe -O ReleaseSafe -femit-bin=main2 -fstrip main.zig   && sha256sum main1 main2
22fed0ef9dc6fb4788fb42440bc1e549257a3f9704033cd23e468316231c45e0  main1
22fed0ef9dc6fb4788fb42440bc1e549257a3f9704033cd23e468316231c45e0  main2
```

**Comment by bfreis** [comment] 2024-04-03 15:45
@jayschwa — interesting! I just downloaded `Zig 0.12.0-dev.3522+b88ae8dbd` and I'm still getting the same issue.

This might be related to the specific platform. I'm on aarch64-macos. What are you using? If it's something else, can you try running the build targeting aarch64-macos to see if the issue happens as well?

**Comment by bfreis** [comment] 2024-04-03 15:49
Another finding: if I use some different targets (host is aarch64-macos), the issue doesn't happen:

```
zig build-exe -O ReleaseSafe -femit-bin=main1 -fstrip -target x86_64-linux-gnu main.zig \
  && zig build-exe -O ReleaseSafe -femit-bin=main2 -fstrip -target x86_64-linux-gnu main.zig \
  && sha256sum main1 main2
13da5a54012d2ab097ceeab79adc808c29f5e7edeb105a53de5137d6ca3392fb  main1
13da5a54012d2ab097ceeab79adc808c29f5e7edeb105a53de5137d6ca3392fb  main2
```

So in some targets, the filename used to initially write the binary to is inserted as part of the binary; but in other targets, it's not used anywhere.

This seems quite unexpected to me. Thoughts?

**Comment by jayschwa** [comment] 2024-04-03 15:50
Yep, it looks like the target has something to do with it. My native target is `x86_64-linux-gnu`. I can reproduce the problem if I target `aarch64-macos`:

``` sh
zig build-exe -target aarch64-macos -O ReleaseSafe -femit-bin=main1 -fstrip main.zig && zig build-exe -target aarch64-macos -O ReleaseSafe -femit-bin=main2 -fstrip main.zig && sha256sum main1 main2
f8a7226ea9e8a23c6231bad0c2c3bd6e29e8582744119a77e61761f465f4758c  main1
8b3ae73ff405266695a6e5477e1ea961564ad929ce781793801d6c15b56d5c89  main2
```

**Comment by bfreis** [comment] 2024-04-03 15:52
Another interesting finding:

- `-target aarch64-macos`: problem happens
- `-target x86_64-macos`: problem _doesn't_ happen.

So it seems _very_ specific!

**Comment by ianprime0509** [comment] 2024-04-03 22:51
I tried this on my x86_64 Linux machine, and the only difference in the resulting binaries I'm able to see is that the name of the executable is being embedded somewhere in the binary:

```
$ mv b.zig main.zig
$ zig build-exe -OReleaseSafe -femit-bin=main1 -fstrip -target aarch64-macos main.zig
$ zig build-exe -OReleaseSafe -femit-bin=main2 -fstrip -target aarch64-macos main.zig
$ diff -U3 <(xxd main1) <(xxd main2)
--- /dev/fd/63	2024-04-03 18:43:58.199952560 -0400
+++ /dev/fd/62	2024-04-03 18:43:58.200952567 -0400
@@ -3207,7 +3207,7 @@
 0000c860: 0000 0000 0000 0000 0000 0000 0000 0000  ................
 0000c870: 0000 0000 0000 0000 0000 0000 0000 0000  ................
 0000c880: 0000 3aa8 0000 0000 0000 0001 6d61 696e  ..:.........main
-0000c890: 3100 7d83 936f d493 cd8c 9396 1717 9e5e  1.}..o.........^
+0000c890: 3200 7d83 936f d493 cd8c 9396 1717 9e5e  2.}..o.........^
 0000c8a0: 8162 ac97 b7a7 9279 0777 f52d 5376 32cc  .b.....y.w.-Sv2.
 0000c8b0: 2bbd 4fe7 b59a f6de 3b66 5b67 788c c2f9  +.O.....;f[gx...
 0000c8c0: 9892 ab82 7efa e3a4 6734 2b3b b4e3 bc8e  ....~...g4+;....
```

#13919 used the approach of having each `build-exe` call output with the same name, and renamed to `main` after compilation. If I do the same, there is no longer any difference:

```
$ zig build-exe -OReleaseSafe -fstrip -target aarch64-macos main.zig && mv main main1
$ zig build-exe -OReleaseSafe -fstrip -target aarch64-macos main.zig && mv main main2
$ diff -U3 <(xxd main1) <(xxd main2)
```

Interestingly, when targeting `x86_64-macos`, even the original approach works (as noted earlier in this issue); it seems the name of the executable isn't making it into the executable itself that way.

I don't have any tools on my system (that I know of) to analyze Mach-O binaries, and I'm not familiar with the format myself, so unfortunately I can't say why exactly the executable name is making it into the binaries here.

**Comment by kubkon** [comment] 2024-04-05 06:52
If I am not mistaken, the basename (`-femit-bin` arg) always ends up in the code signature which is always emitted on `aarch64-macos`. There isn't much you could do except tell the linker to not emit a code signature but this renders your image not runnable/loadable on `aarch64-macos`. Also, I do not believe we currently expose that linker flag in the build system or `build-exe/lib` or `cc` subcommands.

**Comment by kubkon** [comment] 2024-04-05 06:57
I am going to close the issue now as it is not a bug given the explanation I provided above. If you feel otherwise, please feel free to re-open or open a new issue.

**Closed by kubkon** 2024-04-05 06:57 UTC
Labels: bug
