### ISSUE TITLE
translate-c failed to translate function pointer cast

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#8595] opened 2021-04-22 16:34 UTC
```C
typedef void (*sqlite3_destructor_type)(void*);
#define SQLITE_STATIC      ((sqlite3_destructor_type)0)
#define SQLITE_TRANSIENT   ((sqlite3_destructor_type)-1)
```

translate-c gives:
```zig
pub const sqlite3_destructor_type = ?fn (?*c_void) callconv(.C) void;
pub const SQLITE_STATIC = @import("std").meta.cast(sqlite3_destructor_type, @as(c_int, 0));
pub const SQLITE_TRANSIENT = sqlite3_destructor_type - @as(c_int, 1);
```

**Comment by daurnimator** [comment] 2021-04-22 16:40
> ```zig
> pub const SQLITE_TRANSIENT = sqlite3_destructor_type - @as(c_int, 1);
> ```

I think this should come out to:
```zig
const SQLITE_TRANSIENT = @intToPtr(sqlite.c.sqlite3_destructor_type, @bitCast(usize, @as(isize, -1)));
```

though perhaps some of that belongs in std.meta.cast

**Comment by Vexu** [comment] 2021-04-22 16:45
Duplicate of #4071.

**Comment by daurnimator** [comment] 2021-04-22 16:51
> Duplicate of #4071.

@Vexu there's a couple of issues here I think
  - Yes `SQLITE_TRANSIENT` is a dupe of #4071
  - But isn't `SQLITE_STATIC` showing a deficiency where `std.meta.cast` is missing a code path for functions?

**Comment by Vexu** [comment] 2021-04-22 16:55
Didn't realize that was also an issue, fixing that should be as easy as adding `.Fn` in all the places with `.Pointer`.

**Closed** 2021-06-15 04:59 UTC
Labels: contributor friendly, translate-c
