### ISSUE TITLE
stage2 Segmentation fault when using `.init(allocator)` in file scope

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#12675] opened 2022-08-29 19:57 UTC
### Zig Version

0.10.0-dev.3685+dae7aeb33

### Steps to Reproduce

`zig run test.zig` for the following file:
```zig
const std = @import("std");

var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
var allocator = arena.allocator();

var reverseIndices = std.ArrayList(u16).init(allocator);

pub fn main() void {
    std.log.info("{}", .{reverseIndices});
}
```

### Expected Behavior

stage1 gives the following error:
```
$ zig run test.zig -fstage1
./test.zig:6:46: error: unable to evaluate constant expression
var reverseIndices = std.ArrayList(u16).init(allocator);
                                             ^
```

### Actual Behavior

stage2 gives a segmentation fault:
```
$ zig run test.zig
Segmentation fault (core dumped)
```

**Comment by Vexu** [comment] 2022-08-30 10:03
Duplicate of #10886, etc.

**Closed by Vexu** 2022-08-30 10:03 UTC
Labels: bug

**Comment by IntegratedQuantum** [comment] 2022-10-05 12:34
This issue still happens in the latest public version 0.10.0-dev.4217+9d8cdb855.

Might be related to this newer issue: #13068

**Comment by Vexu** [comment] 2022-10-05 12:37
This is duplicate of #12765 which turned out to be different from #10886
