### ISSUE TITLE
Recursive generic function leads to compiler segfault

### ISSUE THREAD

**Issue by andrei-datcu** [ziglang/zig#13803] opened 2022-12-07 09:10 UTC
### Zig Version

0.11.0-dev.538+bf316e550

### Steps to Reproduce and Observed Behavior

`zig build-exe`
```zig
const TreeNode = struct {
    val: u32,
    left: ?*TreeNode,
    right: ?*TreeNode
};

fn visit(
    root: ?*const TreeNode,
    comptime Context: type,
    ctx: *Context,
    visitor: fn (ctx: *Context, *const TreeNode) void
) void {
    if (root) |r| {
        visit(r.left, Context, ctx, visitor);
        visit(r.right, Context, ctx, visitor);
        visitor(ctx, r);
    }
}

fn add(ctx: *u32, node: *const TreeNode) void {
    ctx.* += node.val;
}

pub fn main() void {
    var t: TreeNode = undefined;
    var sum: u32 = 0;
    visit(&t, u32, &sum, add);
}
```

Also, reproduces on 0.10.0
Passing `Context` as a struct with functions does not generate a crash. It seems to only be related to the function pointer parameter.

### Expected Behavior

No compiler crash.

**Comment by matu3ba** [comment] 2022-12-07 09:39
This looks like a duplicate of https://github.com/ziglang/zig/issues/13724 and https://github.com/ziglang/zig/issues/12973.

**Comment by andrei-datcu** [comment] 2022-12-07 10:15
It's not. Maybe I worded it wrong, but the issues you've linked are recursive w.r.t to function generation (one function per each type's value). In my case, there's only one function that gets generated.

**Comment by matu3ba** [comment] 2023-06-24 13:05
```zig
const TreeNode = struct { val: u32, left: ?*TreeNode, right: ?*TreeNode };

fn visit(root: ?*const TreeNode, comptime Context: type, ctx: *Context, visitor: fn (ctx: *Context, *const TreeNode) void) void {
    if (root) |r| {
        visit(r.left, Context, ctx, visitor);
        visit(r.right, Context, ctx, visitor);
        visitor(ctx, r);
    }
}

fn add(ctx: *u32, node: *const TreeNode) void {
    ctx.* += node.val;
}

pub fn main() void {
    var t: TreeNode = undefined;
    var sum: u32 = 0;
    visit(&t, u32, &sum, add);
}
```

No crash anymore, but instead exceeding backwards branches:
```
zig build-exe error2.zig
error2.zig:5:14: error: evaluation exceeded 1000 backwards branches
        visit(r.left, Context, ctx, visitor);
        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error2.zig:5:14: note: use @setEvalBranchQuota() to raise the branch limit from 1000
error2.zig:5:14: note: called from here (999 times)
error2.zig:18:10: note: called from here
    visit(&t, u32, &sum, add);
```

@andrei-datcu Can you confirm that it works as expected?

**Comment by andrei-datcu** [comment] 2023-06-24 13:37
There's only function that needs to be generated, right? If so, the program should compile.

**Comment by mlugg** [comment] 2023-06-24 13:44
Note that if you mark `visitor` as a `comptime` parameter - which in this case I think is meant to be required - it works as expected. The infinite evaluation is certainly a bug.

**Comment by andrei-datcu** [comment] 2023-06-24 13:57
> which in this case I think is meant to be required 

I definitely did not mean that. I was expecting it to work as is.

**Comment by Vexu** [comment] 2023-11-05 22:16
Fixed in master.

**Closed by Vexu** 2023-11-05 22:16 UTC
Labels: bug
