### ISSUE TITLE
return type of a function with a comptime argument becomes `var`

### ISSUE THREAD

**Issue by hiroakitakada** [ziglang/zig#5817] opened 2020-07-08 04:11 UTC
The following code gets a compile error saying `expected type 'fn(u32) u32', found 'fn(u32) var'`.

```
fn comptime_add1(comptime x: u32) u32 {
    return x + 1;
}

fn apply(func: fn(u32) u32, x: u32) u32 {
    return func(x);
}

export var v1 = apply(comptime_add1, 1);
```

So, I checked the type of `comptime_add1` with `@compileLog(@TypeOf(comptime_add1))` and found its type is `fn(u32) var`.  Is this a bug or an intended behavior?

**Comment by daurnimator** [comment] 2020-07-08 04:18
I think this is a dupe of #4984 and possibly #846?

**Comment by hiroakitakada** [comment] 2020-07-08 04:25
@daurnimator, thanks for the information.

I think #4984 is very similar, but I cannot decide they come from a same defect.  I will add my code to #4984 and close this issue.

**Closed** 2020-07-08 04:28 UTC
