### ISSUE TITLE
In function-declaration of structs causes an 'undeclared identifier' error upon method call

### ISSUE THREAD

**Issue by gballet** [ziglang/zig#9741] opened 2021-09-12 08:13 UTC
Declaring a structure with a method in the same code block calling that method, causes an 'undeclared identifier' error.

A simpler example reproduces the problem:

```zig
  1 const std = @import("std");  
  2  
  3 pub fn main() anyerror!void {  
  4     const Person = struct {
  5         name: []const u8,  
  6         age: u8,
  7                                              
  8         pub fn sayHello(self: Person) !void {
  9             std.debug.print("hello I'm {s} and I'm {}\n", .{ self.name, self.age });
 10         }
 11     };
 12     const jdoe = Person{ .name = "John Doe", .age = 57 };
 13  
 14     try jdoe.sayHello();
 15 }
 ```

output:

```
./src/main.zig:8:31: error: use of undeclared identifier 'Person'
        pub fn sayHello(self: Person) !void {
                              ^
./src/main.zig:14:13: note: referenced here
    try jdoe.sayHello();
            ^
crashtest...The following command exited with error code 1:
/usr/local/bin/zig build-exe /usr/home/gballet/src/crashtest/src/main.zig --cache-dir /usr/home/gballet/src/crashtest/zig-cache --global-cache-dir /home/gballet/.cache/zig --name crashtest --enable-cache 
error: the following build command failed with exit code 1:
/usr/home/gballet/src/crashtest/zig-cache/o/748f92e7311bb69408a874889228a7f1/build /usr/local/bin/zig /usr/home/gballet/src/crashtest /usr/home/gballet/src/crashtest/zig-cache /home/gballet/.cache/zig run
```

Moving the structure declaration outside the function body solves the problem:

```zig
  1 const std = @import("std");
  2 
  3 const Person = struct {      
  4     name: []const u8,    
  5     age: u8,    
  6     
  7     pub fn sayHello(self: Person) !void {    
  8         std.debug.print("hello I'm {s} and I'm {}\n", .{ self.name, self.age });    
  9     }    
 10 };    
 11 
 12 pub fn main() anyerror!void {
 13     const jdoe = Person{ .name = "John Doe", .age = 57 };
 14     
 15     try jdoe.sayHello();
 16 }
```

output:

```
hello I'm John Doe and I'm 57
```                                       

This makes for an annoying programming experience e.g. when writing tests that mock different behaviors for the same component, forcing the declaration of structures outside of the scope in which they are to be used, and requiring a lot of extra name-editing instead of a simple copy/paste.

This issue is potentially linked to #2285, although said link isn't immediately obvious to me.

`uname`: `FreeBSD 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64`
`zig version`: 0.8.0

**Comment by Vexu** [comment] 2021-09-12 08:18
Duplicate of #9699.

**Closed by Vexu** 2021-09-12 08:18 UTC
