### ISSUE TITLE
*isize argument to C varargs crashes the compiler

### ISSUE THREAD

**Issue by iacore** [ziglang/zig#17404] opened 2023-10-05 14:43 UTC
### Zig Version

0.12.0-dev.706+62a0fbdae 

I found the problem on 0.11.0 but I can't get it to reproduce with a simple example

### Steps to Reproduce and Observed Behavior

1. Create file `main.zig`

```
const std = @import("std");

pub extern fn foo(...) void;

pub fn main() !void {
    var code: isize = 0;
    foo(&code);
}
```

2. Run in shell:

```
❯ zig build-exe src/main.zig 
fish: Job 1, 'zig build-exe src/main.zig' terminated by signal SIGSEGV (Address boundary error)
```

### Expected Behavior

compiler should not crash

**Comment by Vexu** [comment] 2023-10-05 19:05
Duplicate of #16197

**Closed by Vexu** 2023-10-05 19:05 UTC
Labels: bug
