### ISSUE TITLE
`LineInfo.file_name` provides incorrect path

### ISSUE THREAD

**Issue by lawrence-laz** [ziglang/zig#19556] opened 2024-04-05 22:34 UTC
### Zig Version

0.12.0-dev.3439+31a7f22b8

### Steps to Reproduce and Observed Behavior

Arrange repro
```sh
mkdir repro-test-runner-wrong-line-info && cd repro-test-runner-wrong-line-info

cat <<EOF > tests.zig
const std = @import("std");
test "foo" {
    try std.testing.expectEqual(@as(u32, 123), 123);
}
EOF

mkdir subdir

cat <<EOF > subdir/test_runner.zig
const std = @import("std");
const builtin = @import("builtin");
pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    for (builtin.test_functions) |test_function| {
        const test_func: *const fn () anyerror!void = test_function.func;
        const debug_info = try std.debug.getSelfDebugInfo();
        const func_address = @intFromPtr(test_func);
        const module = try debug_info.getModuleForAddress(func_address);
        const test_symbol = try module.getSymbolAtAddress(gpa.allocator(), func_address);
        const test_line_info = test_symbol.line_info orelse continue;
        std.log.debug("Test func '{s}' is located in file '{s}'", .{ test_symbol.symbol_name, test_line_info.file_name });
    }
}
EOF
```

Run the test
```sh
zig test tests.zig --test-runner subdir/test_runner.zig
```

Observe output
```
debug: Test func 'test.foo' is located in file '/Users/<...>/zig/repro-test-runner-wrong-line-info/subdir/tests.zig'
```
Notice the end of the path `subdir/tests.zig`, that is incorrect, the `tests.zig` file is not in `subdir/`!

### Expected Behavior

Expected output:
```
debug: Test func 'test.foo' is located in file '/Users/<...>/zig/repro-test-runner-wrong-line-info/tests.zig'
```
The `tests.zig` file is **not** in `subdir/`

**Comment by Vexu** [comment] 2024-04-06 06:43
Probably related to #19371

**Comment by jacobly0** [comment] 2024-04-19 03:52
Duplicate of #19371

**Closed by jacobly0** 2024-04-19 03:52 UTC
Labels: bug
