### ISSUE TITLE
Issue: Casting `0x80000000` to `c_int` will causes the compiler to exploid

### ISSUE THREAD

**Issue by JustinRyanH** [ziglang/zig#5078] opened 2020-04-17 06:20 UTC
This is something I ran across when `@cImport(windows.h)` When c_translate translates `windows.h` 

``` c
#define CW_USEDEFAULT = 0x80000000
```
gets translated to 
``` zig
pub const CW_USEDEFAULT = (if (@typeInfo(c_int) == .Pointer) @intToPtr(c_int, 0x80000000) else @as(c_int, 0x80000000));
```

However the `@as(c_int, 0x80000000)` does grok `0x80000000` as `-2147483648` but as `2147483648`  

I don't know the exact solution to this problem. It seems like when printing out c_int to binary using `@import("std").math.minInt` we get `0x80000000`

for example

``` zig
const std = @import("std");

pub fn main() void {
    std.debug.warn("0x{}\n", .{std.math.minInt(c_int)});
}
```

**Comment by Vexu** [comment] 2020-04-17 10:06
Duplicate of #4479

**Closed by Vexu** 2020-04-17 10:06 UTC

**Comment by JustinRyanH** [comment] 2020-04-17 15:06
@Vexu I don't think it's honestly the issue with translation but casting a hex comptime int to an an unsigned. If you give non decimal number it should be casted. `0x80000000` is valid `c_int`

**Comment by Vexu** [comment] 2020-04-17 15:13
If you try running this you will get the same error message:
```zig
test "" {
    // error: integer value 2147483648 cannot be coerced to type 'c_int'
    var a: c_int = 0x80000000;
}
```

The issue is that `translate-c` doesn't know how to translate broken c macros.

**Comment by JustinRyanH** [comment] 2020-04-17 16:00
Okay I think I understand. So `translate-c` will need to identify when a developer was placing in the machine binary format of a given number instead of a the human readable number. 

![image](https://user-images.githubusercontent.com/571433/79589094-b7c16080-8089-11ea-8845-2340e9ff1462.png)

That makes sense. Thanks for your quick response.

**Comment by Vexu** [comment] 2020-04-17 17:31
The base of the number doesn't matter, C compilers just allow it overflow so that it becomes same as `std.math.minInt(c_int)`. Zig is generally much stricter about integer sizes than C.
```zig
std.debug.assert(std.math.minInt(c_int) == -0x80000000);
std.debug.assert(std.math.maxInt(c_int) == 0x7FFFFFFF);
```

**Comment by JustinRyanH** [comment] 2020-04-17 20:02
Oh okay. Oh I see. Cool Thank you.
