### ISSUE TITLE
Zig CC link errors (error: sub-compilation of compiler_rt failed)

### ISSUE THREAD

**Issue by uhthomas** [ziglang/zig#10157] opened 2021-11-16 02:02 UTC
### Zig Version

0.9.0-dev.1414+cde3dd365

### Steps to Reproduce

I'm not sure specifically what causes this behaviour, but I have observed it twice.

It's also important to note a similar issue https://github.com/ziglang/zig/issues/9439, but was specifically referencing `zig build-exe` rather than `zig cc`.

Using [bazel-zig-cc](https://sr.ht/~motiejus/bazel-zig-cc/)@[361fc42b](https://git.sr.ht/~motiejus/bazel-zig-cc/tree/361fc42b2e1282ed078bf9c1ad281642e19858d4), builds sometimes fail with various link errors. 

### Expected Behavior

Zig CC should correctly build and link.

### Actual Behavior

Zig CC _sometimes_ does not link as it should. These error logs are taken from a `linux/amd64` CI environment.

##### First failure

```log
[15:44:42) ERROR: <REDACTED>: GoLink <REDACTED> failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/k8-fastbuild/bin/<REDACTED>-0.params' -- -extld ... (remaining 8 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/linux_amd64/link: running /root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/tools/c++ failed: exit status 1
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:3:24: error: container 'builtin' has no member called 'is_test'
const is_test = builtin.is_test;
                       ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:11:21: note: referenced here
const linkage = if (is_test)
                    ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:25:67: note: referenced here
    @export(__extenddftf2, .{ .name = "__extenddftf2", .linkage = linkage });
                                                                  ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/start.zig:25:16: error: container 'builtin' has no member called 'zig_is_stage2'
    if (builtin.zig_is_stage2) {
               ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:644:16: error: container 'builtin' has no member called 'zig_is_stage2'
    if (builtin.zig_is_stage2) {
               ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt/extendXfYf2.zig:43:30: error: container 'builtin' has no member called 'is_test'
    @setRuntimeSafety(builtin.is_test);
                             ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt/extendXfYf2.zig:10:23: note: called from here
    return extendXfYf2(f128, f64, @bitCast(u64, a));
                      ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt/extendXfYf2.zig:9:48: note: called from here
pub fn __extenddftf2(a: f64) callconv(.C) f128 {
                                               ^

link: error running subcommand external/go_sdk/pkg/tool/linux_amd64/link: exit status 2
(15:44:42) ERROR: <REDACTED>: GoLink <REDACTED> failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/k8-fastbuild/bin/<REDACTED>-0.params' -- -extld ... (remaining 8 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/linux_amd64/link: running /root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/tools/c++ failed: exit status 1
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
error: sub-compilation of compiler_rt failed
    /root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:2:25: error: unable to load '/tmp/bazel-zig-cc/o/b181277d4b26ad376f210624d3d7dc9f/builtin.zig': UnexpectedEndOfFile

link: error running subcommand external/go_sdk/pkg/tool/linux_amd64/link: exit status 2
(15:44:42) ERROR: <REDACTED>: GoLink <REDACTED> failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/k8-fastbuild/bin/<REDACTED>-0.params' -- -extld ... (remaining 8 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/linux_amd64/link: running /root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/tools/c++ failed: exit status 1
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:3:24: error: container 'builtin' has no member called 'is_test'
const is_test = builtin.is_test;
                       ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:11:21: note: referenced here
const linkage = if (is_test)
                    ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:25:67: note: referenced here
    @export(__extenddftf2, .{ .name = "__extenddftf2", .linkage = linkage });
                                                                  ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/start.zig:25:16: error: container 'builtin' has no member called 'zig_is_stage2'
    if (builtin.zig_is_stage2) {
               ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:644:16: error: container 'builtin' has no member called 'zig_is_stage2'
    if (builtin.zig_is_stage2) {
               ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt/extendXfYf2.zig:43:30: error: container 'builtin' has no member called 'is_test'
    @setRuntimeSafety(builtin.is_test);
                             ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt/extendXfYf2.zig:10:23: note: called from here
    return extendXfYf2(f128, f64, @bitCast(u64, a));
                      ^
/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt/extendXfYf2.zig:9:48: note: called from here
pub fn __extenddftf2(a: f64) callconv(.C) f128 {
                                               ^

link: error running subcommand external/go_sdk/pkg/tool/linux_amd64/link: exit status 2
(15:44:44) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:45) INFO: From GoLink <REDACTED>:
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:47) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:48) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:50) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:51) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:53) INFO: From GoLink <REDACTED>:
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:54) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:54) [4,653 / 4,681] 137 / 153 tests, 3 failed; [Prepa] GoCompilePkg external/org_golang_x_crypto/hkdf/hkdf.a [for host]; 52s ... (53 actions, 34 running)
(15:44:57) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:59) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:59) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:44:59) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:45:00) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
warning(link): failed to write cache manifest when archiving: Unexpected
(15:45:00) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(link): failed to save archive hash digest file: PathAlreadyExists
warning(link): failed to write cache manifest when archiving: Unexpected
(15:45:00) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(link): failed to save archive hash digest file: PathAlreadyExists
warning(link): failed to write cache manifest when archiving: Unexpected
(15:45:00) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(link): failed to save archive hash digest file: PathAlreadyExists
warning(link): failed to write cache manifest when archiving: Unexpected
(15:45:02) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(link): failed to save archive hash digest file: PathAlreadyExists
warning(link): failed to write cache manifest when archiving: Unexpected
(15:45:03) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(link): failed to save archive hash digest file: PathAlreadyExists
warning(link): failed to write cache manifest when archiving: Unexpected
(15:45:03) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:45:03) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:45:04) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(15:45:04) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(15:45:04) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(15:45:04) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(15:45:04) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(15:45:17) [4,694 / 4,696] 151 / 153 tests, 3 failed; [Prepa] GoCompilePkg external/org_golang_x_crypto/hkdf/hkdf.a [for host]; 75s ... (21 actions, 4 running)
(15:45:25) INFO: Elapsed time: 184.561s, Critical Path: 84.63s
(15:45:25) INFO: 4695 processes: 1483 remote cache hit, 2957 internal, 255 processwrapper-sandbox.
(15:45:25) FAILED: Build did NOT complete successfully
```

##### Second failure

```
(16:23:43) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:23:43) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:23:44) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:45) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:23:45) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
warning(link): failed to write cache manifest when archiving: Unexpected
(16:23:45) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:46) INFO: From GoLink <REDACTED>:
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(link): failed to save archive hash digest file: PathAlreadyExists
warning(link): failed to write cache manifest when archiving: Unexpected
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:46) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:23:47) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:47) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:47) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:47) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:47) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(compilation): failed to save stage1 hash digest file: PathAlreadyExists
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:47) INFO: From GoLink <REDACTED>:
warning(compilation): failed to write cache manifest when linking: Unexpected
(16:23:47) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:23:47) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(link): failed to save archive hash digest file: PathAlreadyExists
warning(link): failed to write cache manifest when archiving: Unexpected
(16:23:48) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(link): failed to save archive hash digest file: PathAlreadyExists
warning(link): failed to write cache manifest when archiving: Unexpected
(16:24:04) ERROR: <REDACTED>: GoLink <REDACTED> failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/k8-fastbuild/bin/<REDACTED>-0.params' -- -extld ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/linux_amd64/link: running /root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/tools/c++ failed: exit status 1
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
error: sub-compilation of compiler_rt failed
    /root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:2:25: error: unable to load '/tmp/bazel-zig-cc/o/b181277d4b26ad376f210624d3d7dc9f/builtin.zig': UnexpectedEndOfFile

link: error running subcommand external/go_sdk/pkg/tool/linux_amd64/link: exit status 2
(16:24:04) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:24:05) INFO: From GoLink <REDACTED>:
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
(16:24:06) INFO: Elapsed time: 99.488s, Critical Path: 27.22s
(16:24:06) INFO: 4693 processes: 1643 remote cache hit, 2955 internal, 95 processwrapper-sandbox.
(16:24:06) FAILED: Build did NOT complete successfully
```

**Comment by uhthomas** [comment] 2021-11-18 13:23
Observed again today.

```
(13:03:14) ERROR: <REDACTED>: GoLink <REDACTED>: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/k8-fastbuild/bin/<REDACTED>.params' -- -extld ... (remaining 8 argument(s) skipped)
      
Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/linux_amd64/link: running /root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/tools/c++ failed: exit status 1
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
error: sub-compilation of compiler_rt failed
    /root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/lib/std/special/compiler_rt.zig:2:25: error: unable to load '/tmp/bazel-zig-cc/o/b181277d4b26ad376f210624d3d7dc9f/builtin.zig': UnexpectedEndOfFile

link: error running subcommand external/go_sdk/pkg/tool/linux_amd64/link: exit status 2
```

**Comment by uhthomas** [comment] 2021-11-22 01:31
Another, slightly different, failure.

```
external/go_sdk/pkg/tool/linux_amd64/link: running /root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/zig_sdk/tools/c++ failed: signal: segmentation fault
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(module): unexpected EOF reading cached ZIR for builtin.zig
```

**Comment by andrewrk** [comment] 2021-11-27 04:25
Duplicate of #9439.

**Closed by andrewrk** 2021-11-27 04:25 UTC
Labels: bug, zig cc

**Comment by andrewrk** [comment] 2021-12-07 07:34
#9439 is fixed in 274555be21ea756d8480a586f771274a79a58d80. I believe this issue is resolved too. Please let me know if you discover this is still a problem and I will re-open.

**Comment by uhthomas** [comment] 2021-12-07 10:14
Awesome @andrewrk! I'll pin Zig to https://github.com/ziglang/zig/commit/274555be21ea756d8480a586f771274a79a58d80 and monitor the results. Let's hope this helps things :) 

Thank you so much again. Zig CC has been a game changer.

**Comment by andrewrk** [comment] 2021-12-08 05:35
Glad to hear and I'm paying attention to those results :)
