### ISSUE TITLE
`zig build-exe` terminates unexpectedly when compiling struct with reference to array of same struct

### ISSUE THREAD

**Issue by omelancon** [ziglang/zig#17883] opened 2023-11-06 01:04 UTC
### Zig Version

0.12.0-dev.1270+6c9d34bce

### Steps to Reproduce and Observed Behavior

Minimal example:

```zig
const Foo = struct { x: *[2]Foo };

pub fn main() void {
    var f: Foo = undefined;
    _ = f;
}
```

When running `zig build` for this program I get the following error:

```
zig build-exe zigeme Debug native: error: the following command terminated unexpectedly:
/usr/local/zig/zig build-exe /somePath/src/main.zig --cache-dir /somePath/zig-cache --global-cache-dir /myHome/.cache/zig --name zigeme --listen=- 
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install zigeme transitive failure
   └─ zig build-exe zigeme Debug native failure
error: the following build command failed with exit code 1:
/somePath/zig-cache/o/32f15f55419546f3e7ccfe97451d53f8/build /usr/local/zig/zig /somePath /somePath/zig-cache /myHome/.cache/zig --seed 0x547e9acb
```

### Expected Behavior

The program compiles without error.

**Comment by nektro** [comment] 2023-11-06 01:22
`0.12.0-dev.1454+f24ceec35`

```
thread 3644620 panic: Segmentation fault at address 0x0
Killed
```

hit panic immediately then pegged single core at 100% and climbed RAM until OOM killed, peaked at 55GB on my system

**Comment by nektro** [comment] 2023-11-06 01:57
`0.12.0-dev.1481+1b0b46a8a`

attached mid rise and got a trace

```
#0  0x0000000000c84d27 in mem.Allocator.allocBytesWithAlignment__anon_59946 (self=..., byte_count=256, return_address=15916757) at /home/meghan/src/zig/lib/std/mem/Allocator.zig:228
#1  0x0000000001001b9b in mem.Allocator.allocWithSizeAndAlignment__anon_83019 (self=..., n=8, return_address=15916757) at /home/meghan/src/zig/lib/std/mem/Allocator.zig:211
#2  0x000000000124ac79 in mem.Allocator.allocAdvancedWithRetAddr () at /home/meghan/src/zig/lib/std/mem/Allocator.zig:205
#3  mem.Allocator.alignedAlloc__anon_92543 (self=..., n=8) at /home/meghan/src/zig/lib/std/mem/Allocator.zig:193
#4  0x0000000000f2ded5 in array_list.ArrayListAlignedUnmanaged(dwarf.Die.Attr,null).ensureTotalCapacityPrecise (self=0x7ffdddf80748, allocator=..., new_capacity=8) at /home/meghan/src/zig/lib/std/array_list.zig:1007
#5  0x0000000000c8b2cd in array_list.ArrayListAlignedUnmanaged(dwarf.Die.Attr,null).ensureTotalCapacity (self=0x7ffdddf80748, allocator=..., new_capacity=4) at /home/meghan/src/zig/lib/std/array_list.zig:983
#6  0x00000000009cbe09 in array_list.ArrayListAlignedUnmanaged(dwarf.Die.Attr,null).resize (self=0x7ffdddf80748, allocator=<error reading variable: Cannot access memory at address 0x0>, new_len=4) at /home/meghan/src/zig/lib/std/array_list.zig:922
#7  0x00000000009cb8a3 in dwarf.DwarfInfo.parseDie__anon_6797 (di=0x7ffdddf8a2a0, allocator=..., in_stream=..., abbrev_table=0x7fe6f9495f08, is_64=false) at /home/meghan/src/zig/lib/std/dwarf.zig:1233
#8  0x00000000009d5aea in dwarf.DwarfInfo.scanAllFunctions (di=0x7ffdddf8a2a0, allocator=...) at /home/meghan/src/zig/lib/std/dwarf.zig:822
#9  0x00000000009d9ad5 in dwarf.openDwarfDebugInfo (di=0x7ffdddf8a2a0, allocator=<error reading variable: Cannot access memory at address 0x0>) at /home/meghan/src/zig/lib/std/dwarf.zig:2244
#10 0x00000000009dbae8 in debug.readElfDebugInfo (allocator=..., elf_filename=..., build_id=..., expected_crc=..., parent_sections=0x7ffdddf8bbd8, parent_mapped_mem=...) at /home/meghan/src/zig/lib/std/debug.zig:1257
#11 0x00000000009ea86a in debug.DebugInfo.lookupModuleDl (self=0x34dc040 <debug.self_debug_info>, address=140683767574269) at /home/meghan/src/zig/lib/std/debug.zig:1914
#12 0x00000000009eae3a in debug.DebugInfo.getModuleForAddress (self=0x34dc040 <debug.self_debug_info>, address=140683767574269) at /home/meghan/src/zig/lib/std/debug.zig:1567
#13 0x00000000009f76b3 in debug.printSourceAtAddress__anon_4930 (debug_info=0x34dc040 <debug.self_debug_info>, out_stream=..., address=140683767574269, tty_config=...) at /home/meghan/src/zig/lib/std/debug.zig:903
#14 0x0000000001255af5 in debug.dumpStackTraceFromBase (context=0x7ffdddf8d140) at /home/meghan/src/zig/lib/std/debug.zig:241
#15 0x0000000000f56339 in crash_report.StackContext.dumpStackTrace (ctx=...) at crash_report.zig:287
#16 0x0000000000c973ed in crash_report.PanicSwitch.reportStack (state=0x7ff38ab79c08) at crash_report.zig:439
#17 0x00000000009f835f in crash_report.PanicSwitch.goTo () at crash_report.zig:513
#18 crash_report.PanicSwitch.goTo () at crash_report.zig:545
#19 crash_report.PanicSwitch.initPanic (state=<optimized out>, trace=<optimized out>, stack=..., msg=...) at crash_report.zig:537
#20 crash_report.PanicSwitch.initPanic (state=0x7ff38ab79c08, trace=0x0, stack=..., msg=...) at crash_report.zig:406
#21 0x00000000009be2e7 in crash_report.PanicSwitch.goTo () at crash_report.zig:513
#22 crash_report.PanicSwitch.dispatch (trace=0x0, stack_ctx=..., msg=...) at crash_report.zig:370
#23 0x0000000000c985cc in crash_report.handleSegfaultPosix (sig=11, info=0x7ffdddf8d270, ctx_ptr=0x7ffdddf8d140) at crash_report.zig:218
#24 <signal handler called>
#25 0x00007ff37dfdeefd in llvm::Metadata::getMetadataID (this=0xaaaaaaaaaaaaaaaa) at /home/meghan/src/llvm-17/llvm/include/llvm/IR/Metadata.h:101
#26 llvm::MDNode::classof (MD=0xaaaaaaaaaaaaaaaa) at /home/meghan/src/llvm-17/llvm/include/llvm/IR/Metadata.h:1313
#27 llvm::isa_impl<llvm::MDNode, llvm::Metadata, void>::doit (Val=...) at /home/meghan/src/llvm-17/llvm/include/llvm/Support/Casting.h:64
#28 llvm::isa_impl_cl<llvm::MDNode, llvm::Metadata const*>::doit (Val=0xaaaaaaaaaaaaaaaa) at /home/meghan/src/llvm-17/llvm/include/llvm/Support/Casting.h:110
#29 llvm::isa_impl_wrap<llvm::MDNode, llvm::Metadata const*, llvm::Metadata const*>::doit (Val=<optimized out>) at /home/meghan/src/llvm-17/llvm/include/llvm/Support/Casting.h:137
#30 llvm::isa_impl_wrap<llvm::MDNode, llvm::Metadata* const, llvm::Metadata const*>::doit (Val=<synthetic pointer>: 0xaaaaaaaaaaaaaaaa) at /home/meghan/src/llvm-17/llvm/include/llvm/Support/Casting.h:129
#31 llvm::CastIsPossible<llvm::MDNode, llvm::Metadata*, void>::isPossible (f=<synthetic pointer>: 0xaaaaaaaaaaaaaaaa) at /home/meghan/src/llvm-17/llvm/include/llvm/Support/Casting.h:257
#32 llvm::CastInfo<llvm::MDNode, llvm::Metadata*, void>::doCastIfPossible (f=<synthetic pointer>: 0xaaaaaaaaaaaaaaaa) at /home/meghan/src/llvm-17/llvm/include/llvm/Support/Casting.h:493
#33 llvm::dyn_cast<llvm::MDNode, llvm::Metadata> (Val=0xaaaaaaaaaaaaaaaa) at /home/meghan/src/llvm-17/llvm/include/llvm/Support/Casting.h:663
#34 llvm::ReplaceableMetadataImpl::getOrCreate (MD=...) at /home/meghan/src/llvm-17/llvm/lib/IR/Metadata.cpp:360
#35 0x00007ff37dfe5d85 in llvm::MetadataTracking::track (Ref=0x388f908, MD=..., Owner=...) at /home/meghan/src/llvm-17/llvm/lib/IR/Metadata.cpp:154
#36 0x00007ff37dfe6535 in llvm::MDNode::MDNode (this=0x388f930, Context=..., ID=<optimized out>, Storage=<optimized out>, Ops1=..., Ops2=...) at /home/meghan/src/llvm-17/llvm/lib/IR/Metadata.cpp:548
#37 0x00007ff37df25888 in llvm::DINode::DINode (Ops2=..., Ops1=..., Tag=13, Storage=llvm::Metadata::Uniqued, ID=12, C=..., this=0x388f930) at /home/meghan/src/llvm-17/llvm/include/llvm/IR/DebugInfoMetadata.h:137
#38 llvm::DIScope::DIScope (Ops=..., Tag=13, Storage=llvm::Metadata::Uniqued, ID=12, C=..., this=0x388f930) at /home/meghan/src/llvm-17/llvm/include/llvm/IR/DebugInfoMetadata.h:512
#39 llvm::DIType::DIType (Ops=..., Flags=llvm::DINode::FlagZero, OffsetInBits=0, AlignInBits=64, SizeInBits=64, Line=0, Tag=13, Storage=llvm::Metadata::Uniqued, ID=12, C=..., this=0x388f930) at /home/meghan/src/llvm-17/llvm/include/llvm/IR/DebugInfoMetadata.h:708
#40 llvm::DIDerivedType::DIDerivedType (Ops=..., Flags=llvm::DINode::FlagZero, DWARFAddressSpace=std::optional<unsigned int> [no contained value], OffsetInBits=0, AlignInBits=64, SizeInBits=64, Line=0, Tag=13, Storage=llvm::Metadata::Uniqued, C=..., this=0x388f930) at /home/meghan/src/llvm-17/llvm/include/llvm/IR/DebugInfoMetadata.h:978
#41 llvm::DIDerivedType::getImpl (Context=..., Tag=Tag@entry=13, Name=<optimized out>, File=File@entry=0x0, Line=Line@entry=0, Scope=Scope@entry=0x388f800, BaseType=0xaaaaaaaaaaaaaaaa, SizeInBits=64, AlignInBits=64, OffsetInBits=0, DWARFAddressSpace=std::optional<unsigned int> [no contained value], Flags=llvm::DINode::FlagZero, ExtraData=0x0, Annotations=0x0, Storage=llvm::Metadata::Uniqued, ShouldCreate=true) at /home/meghan/src/llvm-17/llvm/lib/IR/DebugInfoMetadata.cpp:741
#42 0x00007ff37def59eb in llvm::DIDerivedType::getImpl (ShouldCreate=true, Storage=llvm::Metadata::Uniqued, Annotations=..., ExtraData=0x0, Flags=llvm::DINode::FlagZero, DWARFAddressSpace=std::optional<unsigned int> [no contained value], OffsetInBits=0, AlignInBits=64, SizeInBits=64, BaseType=0xaaaaaaaaaaaaaaaa, Scope=0x388f800, Line=0, File=0x0, Name=..., Tag=13, Context=...) at /home/meghan/src/llvm-17/llvm/include/llvm/IR/DebugInfoMetadata.h:987
#43 llvm::DIDerivedType::get (Annotations=..., ExtraData=0x0, Flags=llvm::DINode::FlagZero, DWARFAddressSpace=std::optional<unsigned int> [no contained value], OffsetInBits=0, AlignInBits=64, SizeInBits=64, BaseType=0xaaaaaaaaaaaaaaaa, Scope=0x388f800, Line=0, File=0x0, Name=..., Tag=13, Context=...) at /home/meghan/src/llvm-17/llvm/include/llvm/IR/DebugInfoMetadata.h:1017
#44 llvm::DIBuilder::createMemberType (this=this@entry=0x376fa50, Scope=Scope@entry=0x388f800, Name=..., File=File@entry=0x0, LineNumber=LineNumber@entry=0, SizeInBits=64, AlignInBits=64, OffsetInBits=0, Flags=llvm::DINode::FlagZero, Ty=0xaaaaaaaaaaaaaaaa, Annotations=...) at /home/meghan/src/llvm-17/llvm/lib/IR/DIBuilder.cpp:368
#45 0x0000000002f800dd in ZigLLVMCreateDebugMemberType (dibuilder=0x376fa50, scope=0x388f800, name=0x386102f "x", file=0x0, line=0, size_in_bits=64, align_in_bits=64, offset_in_bits=0, flags=0, type=0xaaaaaaaaaaaaaaaa) at /home/meghan/src/zig/src/zig_llvm.cpp:495
#46 0x00000000010a986d in codegen.llvm.Object.lowerDebugTypeImpl (o=0x377cb20, gop=..., resolve=full, opt_fwd_decl=0x388f800) at /home/meghan/src/zig/src/codegen/llvm.zig:2596
#47 0x0000000000de73e9 in codegen.llvm.Object.lowerDebugType (o=0x377cb20, ty=..., resolve=full) at /home/meghan/src/zig/src/codegen/llvm.zig:1946
#48 0x00000000010a55e8 in codegen.llvm.Object.lowerDebugTypeImpl (o=0x377cb20, gop=..., resolve=fwd, opt_fwd_decl=0x0) at /home/meghan/src/zig/src/codegen/llvm.zig:2224
#49 0x0000000000de733e in codegen.llvm.Object.lowerDebugType (o=0x377cb20, ty=..., resolve=fwd) at /home/meghan/src/zig/src/codegen/llvm.zig:1953
#50 0x00000000010a41f9 in codegen.llvm.Object.lowerDebugTypeImpl (o=0x377cb20, gop=..., resolve=full, opt_fwd_decl=0x0) at /home/meghan/src/zig/src/codegen/llvm.zig:2185
#51 0x0000000000de733e in codegen.llvm.Object.lowerDebugType (o=0x377cb20, ty=..., resolve=full) at /home/meghan/src/zig/src/codegen/llvm.zig:1953
#52 0x00000000010a9570 in codegen.llvm.Object.lowerDebugTypeImpl (o=0x377cb20, gop=..., resolve=full, opt_fwd_decl=0x0) at /home/meghan/src/zig/src/codegen/llvm.zig:2594
#53 0x0000000000de733e in codegen.llvm.Object.lowerDebugType (o=0x377cb20, ty=..., resolve=full) at /home/meghan/src/zig/src/codegen/llvm.zig:1953
#54 0x00000000018bf393 in codegen.llvm.FuncGen.airDbgVarPtr (self=0x7ffdddf9bd00, inst=7) at /home/meghan/src/zig/src/codegen/llvm.zig:6641
#55 0x0000000001345056 in codegen.llvm.FuncGen.genBody (self=0x7ffdddf9bd00, body=...) at /home/meghan/src/zig/src/codegen/llvm.zig:5079
#56 0x000000000133b52e in codegen.llvm.Object.updateFunc (o=0x377cb20, mod=0x377b428, func_index=1744, air=..., liveness=...) at /home/meghan/src/zig/src/codegen/llvm.zig:1647
#57 0x000000000134eaaa in link.Elf.updateFunc (self=0x377c0a0, mod=0x377b428, func_index=1744, air=..., liveness=...) at /home/meghan/src/zig/src/link/Elf.zig:3043
#58 0x0000000001017551 in link.File.updateFunc (base=0x377c2c8, module=0x377b428, func_index=1744, air=..., liveness=...) at link.zig:621
#59 0x0000000000d961db in Module.ensureFuncBodyAnalyzed (mod=0x377b428, func_index=1744) at Module.zig:3423
#60 0x0000000000d939ae in Compilation.processOneJob (comp=0x377a020, job=..., prog_node=0x7ffdddf9ec38) at Compilation.zig:3516
#61 0x0000000000b61d6f in Compilation.performAllTheWork (comp=0x377a020, main_progress_node=0x7ffdddf9ec38) at Compilation.zig:3453
#62 0x0000000000b5d3ed in Compilation.update (comp=0x377a020, main_progress_node=0x7ffdddf9ec38) at Compilation.zig:2234
#63 0x0000000000b8c973 in main.updateModule (comp=0x377a020) at main.zig:4279
#64 0x0000000000baf53d in main.buildOutputType (gpa=..., arena=..., all_args=..., arg_mode=...) at main.zig:3680
#65 0x00000000009c0e80 in main.mainArgs (gpa=..., arena=..., args=...) at main.zig:287
#66 0x00000000009bde06 in main.main () at main.zig:223
```

**Comment by nektro** [comment] 2023-11-06 06:03
running in valgrind yields

```
==3666378== More than 1000 different errors detected.  I'm not reporting any more.
==3666378== Final error counts will be inaccurate.  Go fix your program!
==3666378== Rerun with --error-limit=no to disable this cutoff.  Note
==3666378== that errors may occur in your program without prior warning from
==3666378== Valgrind, because errors are no longer being displayed.
```

**Comment by Vexu** [comment] 2023-11-06 08:51
Duplicate of #16414

**Closed by Vexu** 2023-11-06 08:51 UTC
Labels: bug
