### ISSUE TITLE
windows: executables output by zig are non-deterministic by default

### ISSUE THREAD

**Issue by jacobly0** [ziglang/zig#14924] opened 2023-03-15 16:00 UTC
### Zig Version

0.11.0-dev.1977+db450bcad

### Steps to Reproduce and Observed Behavior

Example link invocation when building zig:
```
lld-link -ERRORLIMIT:0 -NOLOGO -DEBUG -PDB:<local-cache>\o\fa3f0a308c6878f003bddb65e7295e69\zig.pdb -PDBALTPATH:<local-cache>\o\fa3f0a308c6878f003bddb65e7295e69\zig.pdb -STACK:33554432 -MACHINE:X64 -INCLUDE:_tls_index -OUT:<local-cache>\o\fa3f0a308c6878f003bddb65e7295e69\zig.exe -IMPLIB:<local-cache>\o\fa3f0a308c6878f003bddb65e7295e69\zig.lib <local-cache>\o\fa3f0a308c6878f003bddb65e7295e69\zig.exe.obj -SUBSYSTEM:console -NODEFAULTLIB -ENTRY:wWinMainCRTStartup <global-cache>\o\a445fb2064ed6408d3371ba8965984e3\c.lib <global-cache>\o\099d7e42ed8f2bc9ddb0e0f9e93dc26c\compiler_rt.lib <global-cache>\o\9ec39fea57e46fafd26e97fb1115884c\kernel32.lib <global-cache>\o\a30d80965663a103db1483c7f9a36b11\shell32.lib <global-cache>\o\42b557fdfa8175035f91cf67e9ab1807\ole32.lib <global-cache>\o\26d6a909081f5bc58512e9b4415cc240\ntdll.lib <global-cache>\o\97d030c78ea59cc460c4aa7359df3271\crypt32.lib <global-cache>\o\2ac5c956ba796e186443cc15dbe7ed4a\ws2_32.lib <global-cache>\o\c5ad5d4ec3c3aa580b32185467069ac2\advapi32.lib
```

### Expected Behavior

```
OVERVIEW: LLVM Linker

USAGE: lld-link.exe [options] file...

OPTIONS:
  /Brepro                 Use a hash of the executable as the PE header timestamp
  /timestamp:<value>      Specify the PE header timestamp
```

**Comment by jacobly0** [comment] 2023-04-20 17:55
This is the same issue reported in #9432

**Comment by andrewrk** [comment] 2023-07-20 20:41
Closing as duplicate of #9432.

**Closed by andrewrk** 2023-07-20 20:41 UTC
Labels: bug, os-windows, linking
