### ISSUE TITLE
No compiler error when using `else |errr|` syntax on a test case not returning an error set

### ISSUE THREAD

**Issue by andi23rosca** [ziglang/zig#8150] opened 2021-03-05 11:06 UTC
The following code should warn/error the user that `functionThatReturnsBool()` does not have a return type that includes errors. 
```zig
if (functionThatReturnsBool()) {
    ...
} else |_| {
    ...
}
```
What it does instead is it silently always goes to the first branch in the if statement, even when the function returns false.

**Comment by LemonBoy** [comment] 2021-03-05 11:34
Duplicate of #8076

**Closed** 2021-03-05 11:35 UTC
