### ISSUE TITLE
ReleaseSmall output seems large (on MacOS anyway)

### ISSUE THREAD

**Issue by awmorgan** [ziglang/zig#10092] opened 2021-11-03 01:08 UTC
### Zig Version

0.9.0-dev.1553+f951bf8ae

### Steps to Reproduce

/Volumes/git/ziglearn $ cat main.zig
pub fn main() void {}
/Volumes/git/ziglearn $ zig build-exe --strip -O ReleaseSmall main.zig
/Volumes/git/ziglearn $ ls -lah ./main
-rwxr-xr-x  1 arthurmorgan  admin   336K Nov  2 20:00 ./main
/Volumes/git/ziglearn $ otool -L ./main
./main:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
/Volumes/git/ziglearn $ zig version
0.9.0-dev.1553+f951bf8ae
/Volumes/git/ziglearn $ uname -v
Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64

### Expected Behavior

executable produced that is smaller than 336KB.

### Actual Behavior

executable that is 336KB.

I actually don't know if this is the expected size or not but it does seem a little large for a program with nothing in it.

**Comment by tauoverpi** [comment] 2021-11-03 08:12
This sounds like a case of https://github.com/ziglang/zig/issues/6676, have you tried `--strip`?

**Comment by awmorgan** [comment] 2021-11-03 09:49
> This sounds like a case of #6676, have you tried `--strip`?

In the description above I wrote this 

/Volumes/git/ziglearn $ zig build-exe --strip -O ReleaseSmall main.zig

**Comment by tauoverpi** [comment] 2021-11-03 12:19
Ah, sorry, missed that part

**Comment by awmorgan** [comment] 2021-11-03 23:35
```
/Volumes/git/ziglearn $ bloaty main
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  97.0%   326Ki  96.0%   326Ki    [__TEXT]
   1.2%  3.99Ki   1.2%  3.99Ki    [__DATA_CONST]
   0.0%       0   1.1%  3.75Ki    [__LINKEDIT]
   1.0%  3.21Ki   0.9%  2.93Ki    [__DATA]
   0.4%  1.51Ki   0.4%  1.41Ki    [Mach-O Headers]
   0.1%     256   0.1%     256    __DATA,__la_symbol_ptr
   0.0%       0   0.1%     256    __DATA,__thread_bss
   0.1%     256   0.1%     256    __DATA,__thread_data
   0.1%     256   0.1%     256    __DATA,__thread_vars
   0.1%     192   0.1%     192    __TEXT,__stubs
   0.0%     112   0.0%     112    Symbol Table
   0.0%      64   0.0%      64    String Table
   0.0%      49   0.0%      49    __TEXT,__text
   0.0%      48   0.0%      48    Export Info
   0.0%      40   0.0%      40    __DATA,__data
   0.0%       0   0.0%      32    __DATA,__bss
   0.0%      24   0.0%      24    Binding Info
   0.0%      15   0.0%      15    __TEXT,__stub_helper
   0.0%       8   0.0%       8    Rebase Info
   0.0%       8   0.0%       8    __DATA_CONST,__got
   0.0%       4   0.0%       4    [1 Others]
 100.0%   336Ki 100.0%   340Ki    TOTAL
```

**Comment by andrewrk** [comment] 2021-11-20 20:30
Duplicate of #9990

**Closed by andrewrk** 2021-11-20 20:30 UTC
Labels: os-macos
