### ISSUE TITLE
Potentially undefined behaviour when passing "self: Self" as a method parameter

### ISSUE THREAD

**Issue by justin330** [ziglang/zig#17696] opened 2023-10-24 11:43 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Hi there,

I'm new to using Zig, and enjoying it so far (besides a couple issues here and there), its made me realise that a systems programming language need not be as complex and unintiuitive as I've grown to accept.

Anway, I experienced this issue as part of a larger project, and put together this small example to illustrate:

```
test "Corrupted read" {
  // print newline to seperate test output from test title
  print("\n", .{});

  const ElementalPet = struct {
    const Self = @This();
    
    // Yes I know it would be optimal to store the names externally...
    // also, is this the only way to construct a array with a default value that is smaller?
    name: [10:0]u8 = "Unnamed".* ++ ([_]u8{0} ** 3),
    
    pub fn nameGetA(self: Self) *const [10:0]u8 {
	    return &self.name;
    }
    
    pub fn nameGetB(self: *const Self) *const [10:0]u8 {
	    return &self.name;
    }
  
    pub fn nameSet(self: * Self, new_name: []const u8) void {
	    const len = @min(self.name.len, new_name.len);
	    @memcpy(self.name[0..len], new_name[0..len]);
	    @memset(self.name[len..], 0);
    }
  }
```

```
  var player_pet = ElementalPet{};
  player_pet.nameSet("Sparky");
  
  print("name via nameGetA: {s}\n", .{player_pet.nameGetA()}); // prints: "    med"
  print("name via nameGetB: {s}\n", .{player_pet.nameGetB()}); // prints: "Unnamed"
}
```

### Expected Behavior

From what is stated in the documentation, Zig will convert a parameter into a refrence depending on the structure size, 
(and while I appreciate the convenience of this, I can't help be feel it goes against Zig's design ethos, among other things).

However, I belive this may cause cases of undefined behaviour where if the object is copied then operations will be performed on a temporary.

In this example `nameGetA()` returns the address of the said temporary copy a invalid memory resulting in : "    ky" being printed.

But if I were to increase the size of the structure:
```
  name: [10:0]u8 = "Unnamed".* ++ ([_]u8{0} ** 3),
  desc: [256:0]u8 = "Unnamed".* ++ ([_]u8{0} ** 249),
```
now `nameGetA()` prints the same as `nameGetB()` as `self: Self` has been silently swapped to `self: *const Self`.

Lastly, I often see `self: Self` used in the Standard Library, where the intent may have been `self: *Self`, or `self: *const Self`, but due to those structs being larger this behaviour likely wasn't encountered.

**Comment by slonik-az** [comment] 2023-10-24 12:19
> However, I belive this may cause cases of undefined behaviour where if the object is copied then operations will be performed on a temporary.

No worries, in Zig function parameters are strictly read-only. Even if a temporary is created you cannot modify it. And returning an address of the function parameter is an antipattern, precisely because you may be returning address to a temorary on the stack.

**Comment by Vexu** [comment] 2023-10-24 13:33
Duplicate of #2646

**Closed by Vexu** 2023-10-24 13:33 UTC
Labels: bug
