### ISSUE TITLE
Initializing struct with anytype member crashes the compiler

### ISSUE THREAD

**Issue by maringuu** [ziglang/zig#8018] opened 2021-02-15 12:32 UTC
Minimal code to reproduce:
```zig
const Bar = struct {
    args: anytype,
};

pub fn main() !void {
    const bar: Bar = .{.args = .{.a = 5}};
}

```
Simelar code that also does not work:
```zig
const Bar = struct {
    args: anytype,
};

const Foo = struct {
    i: i32,
};

pub fn main() !void {
    const bar: Bar = .{
        .args = Foo {
            .i = 5
        },
    };
}
```

Error Message:
```
Assertion failed at /home/vsts/work/1/s/src/stage1/ir.cpp:22739 in ir_analyze_container_member_access_inner. This is a bug in the Zig compiler.thread 22473 panic: 
Unable to dump stack trace: debug info stripped
[1]    22473 abort      ~/opt/zig-linux-x86_64-0.8.0-dev.1140+9270aae07/zig build-exe other.zig
```
It works with primitive types such as pointers or integers. It only crashes with struct types for the anytype member.

I'm currently building llvm to compile the zig compiler with debug symbols.
If I dont forget I'll probably post more detailed logs later.

**Comment by Vexu** [comment] 2021-02-16 09:25
Duplicate of #5877.

**Closed by Vexu** 2021-02-16 09:25 UTC

**Comment by maringuu** [comment] 2021-02-16 09:28
Oh, thanks. I didn't find that one.
