### ISSUE TITLE
crash when printing `std.mem.asBytes` errors

### ISSUE THREAD

**Issue by alichraghi** [ziglang/zig#13628] opened 2022-11-22 15:26 UTC
### Zig Version

0.11.0-dev.4963+0697883d0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const S = struct {};
test {
    std.mem.asBytes(S{});
}
```
panics and outputs colorless errors:
```
/home/ali/dev/zig/lib/std/mem.zig:3191:9: error: expected single item pointer, passed z.S
        @compileError("expected single item pointer, passed " ++ @typeName(P));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ali/dev/zig/lib/std/mem.zig:3199:47: note: called from here
pub fn asBytes(ptr: anytype) AsBytesReturnType(@TypeOf(ptr)) {
                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
thread 153655 panic: Zig compiler bug: attempted to destroy declaration with an attached error
/home/ali/dev/zig/src/Module.zig:3487:13: 0x555f56bd6c6e in Module.destroyDecl (zig2)
            @panic("Zig compiler bug: attempted to destroy declaration with an attached error");
            ^
/home/ali/dev/zig/src/Sema.zig:6910:33: 0x555f57615e2c in Sema.instantiateGenericCall (zig2)
        errdefer mod.destroyDecl(new_decl_index);
                                ^
/home/ali/dev/zig/src/Sema.zig:6204:40: 0x555f572c9fcc in Sema.analyzeCall (zig2)
        if (sema.instantiateGenericCall(
                                       ^
/home/ali/dev/zig/src/Sema.zig:5983:42: 0x555f56fa5836 in Sema.zirCall (zig2)
            break :b try sema.analyzeCall(block, func, func_src, call_src, modifier, ensure_result_used, resolved_args, bound_arg_src);
                                         ^
/home/ali/dev/zig/src/Sema.zig:818:62: 0x555f56d8ca55 in Sema.analyzeBodyInner (zig2)
            .call                         => try sema.zirCall(block, inst),
                                                             ^
/home/ali/dev/zig/src/Sema.zig:5116:34: 0x555f572f31b6 in Sema.resolveBlockBody (zig2)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/ali/dev/zig/src/Sema.zig:5099:33: 0x555f5704ddcd in Sema.zirBlock (zig2)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/ali/dev/zig/src/Sema.zig:1351:69: 0x555f56d99a5a in Sema.analyzeBodyInner (zig2)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
```

### Expected Behavior

colorful errors without panic

**Comment by Vexu** [comment] 2022-11-22 15:35
Duplicate of #12927

**Closed by Vexu** 2022-11-22 15:35 UTC
Labels: bug
