### ISSUE TITLE
Access violations sometimes when creating structs inside structs

### ISSUE THREAD

**Issue by bpeake13** [ziglang/zig#11478] opened 2022-04-20 05:29 UTC
### Zig Version

0.9.1

### Steps to Reproduce

Not sure what the exact behavior is that causes this to happen, as stated in the title, this sometimes works. It seems to specifically have issues with depth and pointers. This example program causes the issue to repro:

```zig
const std = @import("std");

const A = struct {
    name: []const u8
};

const B = struct {
    size: u32,
};

pub fn main() anyerror!void {
    const str = try std.heap.page_allocator.alloc(u8, 100);

    const t = .{
        A {
            .name = str,
        },
        B {
            .size = 20,
        },
    };

    try std.json.stringify(t, .{}, std.io.getStdOut().writer());
}
```

### Expected Behavior

The example program should create the tuple with no issues and then print it to json (with maybe some issues, but this happens even with a valid string)

### Actual Behavior

The program crashes on assigning name with this print out:
```
Exception thrown at 0x00007FF6BC3F1E67 in zig_playground.exe: 0xC0000005: Access violation writing location 0x00007FF6BC452F68.
```

If A is made a local variable, and then assigned to the tuple, it works fine, this only happens when inlining. When looking at the disassembly, it seems to crash on this mov instruction:
```
mov qword ptr [strncmp+1AF8h (07FF6BC452F68h)],rax
```
Whenever i've seen this issue, it always crashes on an instruction like this (though the address is different as well as the symbol it is taking relative from). Im not sure why it would be doing this mov, and when i don't inline this instruction is gone.

**Comment by batiati** [comment] 2022-04-20 09:13
I guess it is related with nested tuples holding runtime values.

This code segfaults too:

https://godbolt.org/z/8Ta1f8cG7

**Comment by Vexu** [comment] 2022-04-28 15:05
Duplicate of #4597

**Closed by Vexu** 2022-04-28 15:05 UTC
Labels: bug
