### ISSUE TITLE
Bug: usingnamespace reexports symbols implicitly

### ISSUE THREAD

**Issue by yamirui** [ziglang/zig#6445] opened 2020-09-28 07:43 UTC
### Version
`master`, first observed `0.6.0+eab51b778` and still present in current latest `0.6.0+e60939bfa`.
### Minimal reproducible example
```zig
// private.zig

// some private symbol that we don't want to be
// exposed to end user of the library
pub const foo: u8 = 1;
```
```zig
// lib.zig

// should only be accessible in lib.zig because
// `pub` keyword does not precede this import
usingnamespace @import("private.zig");
```
```zig
// main.zig

// should be a compile error
const foo = @import("lib.zig").foo;

pub fn main() void {
    @import("std").debug.print("foo = {}\n", .{foo});
}
```
```bash
$ zig build-exe main.zig && ./main
foo = 1
```
### Attachments
[usingnamespace.zip](https://github.com/ziglang/zig/files/5290654/usingnamespace.zip)

**Comment by marler8997** [comment] 2020-11-12 17:49
I created #7085 but I've closed it as it seems like a duplicate of this.  I've minified your example to 1 file:
```zig
// we should not be able to access "private_foo" here
// becuase the "usingnamespace" is not "pub"
const foo = (struct {
    usingnamespace struct {
        pub const private_foo: u8 = 1;
    };
}).private_foo;

pub fn main() void {
    @import("std").debug.print("foo = {}\n", .{foo});
}

```

**Comment by marler8997** [comment] 2020-11-12 17:56
@andrewrk I see you moved this one to be fixed in 0.9.0 instead of 0.8.0.  Could we prioritize this one to be fixed in 0.8.0?  It's blocking me from completing my "complete windows bindings" project https://github.com/marler8997/zig-os-windows

**Comment by marler8997** [comment] 2020-11-13 19:33
FYI, I found a way to work around this issue in my zig-os-windows project for now.

**Comment by Vexu** [comment] 2024-03-28 11:31
Fixed in master.

**Closed by Vexu** 2024-03-28 11:31 UTC
Labels: bug, stage1
