### ISSUE TITLE
Any pointer should freely coerce to `?*anyopaque`

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#13331] opened 2022-10-28 09:42 UTC
### Zig Version

0.10.0-dev.4560+828735ac0

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() void {
    var val: [*:0]u8 = undefined;
    func(&val);
}

fn func(value: ?*anyopaque) void {
    _ = value;
}
```

```
<source>:3:10: error: expected type '?*anyopaque', found '*[*:0]u8'
    func(&val);
         ^~~~
<source>:3:10: note: pointer type child '[*:0]u8' cannot cast into pointer type child 'anyopaque'
referenced by:
    callMain: /opt/compiler-explorer/zig-master/lib/std/start.zig:568:17
    initEventLoopAndCallMain: /opt/compiler-explorer/zig-master/lib/std/start.zig:512:51
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

Compiler returned: 1
```

### Expected Behavior

Any pointer should be able to coerce to `?*anyopaque` without requiring a `@ptrCast`.

If `val` is not a pointer type it works fine:
```zig
pub fn main() void {
    var val: bool = undefined; // Any non-pointer type is fine
    func(&val);
}

fn func(value: ?*anyopaque) void {
    _ = value;
}
```

**Comment by Vexu** [comment] 2022-10-28 10:27
Duplicate of #12042

**Closed by Vexu** 2022-10-28 10:27 UTC
Labels: bug
