### ISSUE TITLE
Panic on multiple zig build runs

### ISSUE THREAD

**Issue by jecolon** [ziglang/zig#20015] opened 2024-05-20 19:39 UTC
### Zig Version

0.13.0-dev.211+6a65561e3

### Steps to Reproduce and Observed Behavior

Confirmed on macOS Sonoma 14.4.1 (M1) , Debian 12 (x86_64), Fedora 39, and Arch Linux.

```plain
❯ zig init
info: created build.zig
info: created build.zig.zon
info: created src/main.zig
info: created src/root.zig
info: see `zig build --help` for a menu of options

❯ zig build run
All your codebase are belong to us.
Run `zig build test` to run the tests.

❯ zig build run
All your codebase are belong to us.
Run `zig build test` to run the tests.
thread 5419594 panic: reached unreachable code
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/std/debug.zig:403:14: 0x104dde337 in assert (build)
    if (!ok) unreachable; // assertion failure
             ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/std/Build/Cache.zig:896:15: 0x104f14a63 in writeManifest (build)
        assert(self.have_exclusive_lock);
              ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/std/Build/Step.zig:554:26: 0x104f153d3 in writeManifest (build)
        man.writeManifest() catch |err| {
                         ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/std/Build/Step/Run.zig:713:31: 0x104eb990b in make (build)
        try step.writeManifest(&man);
                              ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/std/Build/Step.zig:182:13: 0x104e5596f in make (build)
    s.makeFn(s, prog_node) catch |err| switch (err) {
            ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/compiler/build_runner.zig:948:31: 0x104e1af83 in workerMakeOneStep (build)
    const make_result = s.make(&sub_prog_node);
                              ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/std/Thread/Pool.zig:102:39: 0x104e1b8ef in runFn (build)
            @call(.auto, func, closure.arguments);
                                      ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/std/Thread/Pool.zig:191:18: 0x104e7c9d3 in worker (build)
            runFn(&run_node.data);
                 ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/std/Thread.zig:408:13: 0x104e541bb in callFn__anon_14051 (build)
            @call(.auto, f, args);
            ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/lib/std/Thread.zig:674:30: 0x104e1a79b in entryFn (build)
                return callFn(f, args_ptr.*);
                             ^
???:?:?: 0x196c62f93 in ??? (libsystem_pthread.dylib)
???:?:?: 0xa549000196c5dd33 in ??? (???)
error: the following build command crashed:
/Users/jecolon/code/zig/bar/zig-cache/o/23d675102f29e840295a509e95c1dc7c/build /Users/jecolon/Downloads/zig-macos-aarch64-0.13.0-dev.211+6a65561e3/zig /Users/jecolon/code/zig/bar /Users/jecolon/code/zig/bar/zig-cache /Users/jecolon/.cache/zig --seed 0xe31685a8 -Zcc6aaeb301479d08 run
```

### Expected Behavior

zig uild run should run without problems.

**Comment by Rexicon226** [comment] 2024-05-20 19:44
Can confirm on `Ubuntu Noble Numbat` as well.

**Comment by Rexicon226** [comment] 2024-05-20 19:48
Doesn't happen on master branch for me 9f4f43cf7fdd2b2a50e475a1e7d740c9bcc2227e, but happens on 6a65561e3, so it might have been fixed?

**Comment by Rexicon226** [comment] 2024-05-20 20:00
Ah, there was this issue about the same thing #19947, and it was fixed by ad721722932b8cb0d22b2f0048d3bd952319ef97.

**Comment by Vexu** [comment] 2024-05-20 20:02
Duplicate of #19947

**Closed by Vexu** 2024-05-20 20:02 UTC
Labels: bug
