### ISSUE TITLE
arbitrary bit-width integers leads to an LLVM error

### ISSUE THREAD

**Issue by komuw** [ziglang/zig#2373] opened 2019-04-28 14:21 UTC
The following program works okay:
```zig
const std = @import("std");
const warn = std.debug.warn;
const assert = @import("std").debug.assert;

pub fn main() void {
    const message = "aa";

    var sum: u128 = 0;
    for (message) |byte| {
        assert(byte == 97);
        sum += byte;
    }

    assert(sum == 97 + 97);
    warn("\n sum:: {} ", sum);
}
```
```bash
zig fmt . && zig build-exe cool.zig && ./cool

 sum:: 194
```

However, trying to use arbitrary bit-width integers leads to an LLVM error with no stack trace.
```zig
const std = @import("std");
const warn = std.debug.warn;
const assert = @import("std").debug.assert;

pub fn main() void {
    const message = "aa";

    var sum: u256 = 0;
    for (message) |byte| {
        assert(byte == 97);
        sum += byte;
    }

    assert(sum == 97 + 97);
    warn("\n sum:: {} ", sum);
}
```
```bash
zig fmt . && zig build-exe cool.zig && ./cool
   LLVM ERROR: Unsupported library call operation!
```

my system:
*zig version:* 0.4.0+205e501
*uname -ra:* Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64

**Comment by komuw** [comment] 2019-04-28 14:29
just found;
https://github.com/ziglang/zig/issues/1485   
and   
https://github.com/ziglang/zig/issues/1534   
which are probably related.   

We can close this issue if someone can confirm whether this is a duplicate of the above two named issues

**Comment by andrewrk** [comment] 2019-04-28 15:46
Yes - I would consider this a duplicate of #1485.

**Closed by andrewrk** 2019-04-28 15:46 UTC
