### ISSUE TITLE
Unintuitive behavior of runtime-selected string literals in std.fmt

### ISSUE THREAD

**Issue by stellahymmne** [ziglang/zig#10695] opened 2022-01-26 01:14 UTC
### Zig Version

0.9.0

### Steps to Reproduce

```zig
const std = @import("std");
test "std.fmt bug" {
    const t = std.time.milliTimestamp();
    //the boolean must have some tiny chance of being true, but if it is, skip
    if (t & 1 != 0) return error.SkipZigTest;

    const true_is_false = t & 1 != 0;
    std.debug.assert(!true_is_false); //this is a runtime value of false

    try std.testing.expectFmt("true != false", "{s}", .{if (true_is_false) "true == false" else "true != false"});
}
```

### Expected Behavior

The format function should result in `true != false`.

### Actual Behavior

The format function instead results in `true == false` and the test fails.
The fact that this only compiles if the two literals are the same length suggests unintuitive type coercion is at play.
It also stops failing if the contents of the `if` statement are known at comptime.

**Comment by schmee** [comment] 2022-01-26 09:41
Duplicate of https://github.com/ziglang/zig/issues/9908?

**Comment by rohlem** [comment] 2022-01-26 23:21
More specifically the nasty #3882 / #4491 / #5230 / #7097 .

**Closed** 2022-01-29 16:20 UTC
Labels: bug
