### ISSUE TITLE
Compiler crash on if-expression with empty body followed by semicolon (`if (true);`)

### ISSUE THREAD

**Issue by fjallarefur** [ziglang/zig#3347] opened 2019-09-30 12:30 UTC
Compiling this program:
```zig
pub fn main() void {
    if (true);
}
```
with Zig 0.4.0 results in `Segmentation fault (core dumped)`.

I wanted to see if Zig would yell at me for doing silly things. At least it didn't accept the program. :)

**Comment by Vexu** [comment] 2019-09-30 13:01
Duplicate of #2309, fixed in master.

**Closed** 2019-09-30 13:07 UTC
