### ISSUE TITLE
Crash with "broken LLVM module found"

### ISSUE THREAD

**Issue by basile-henry** [ziglang/zig#10396] opened 2021-12-23 08:19 UTC
### Zig Version

0.9.0

### Steps to Reproduce

The following reduced bit of code replicates the issue:

```zig
fn just_null() ?usize {
    return null;
}

pub fn main() anyerror!void {
    if (just_null() == @as(usize, undefined) and true) unreachable;
}
```

### Expected Behavior

I expect `zig` to not crash. I actually now think this should be a type error (trying to do equality on `usize` and `?usize`).

### Actual Behavior

It crashes:

```
❯ zig build-exe bug.zig
broken LLVM module found: PHI node entries do not match predecessors!
  %8 = phi i1 [ %7, %Entry ], [ true, %BoolAndTrue ], !dbg !17090
label %Entry
label %CmpOptionalNonOptionalEnd
Instruction does not dominate all uses!
  %7 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull ], [ %6, %CmpOptionalNonOptionalOptionalNotNull ], !dbg !17089
  %8 = phi i1 [ %7, %Entry ], [ true, %BoolAndTrue ], !dbg !17090

This is a bug in the Zig compiler.thread 183760 panic:
Unable to dump stack trace: debug info stripped
Aborted (core dumped)
```

**Comment by Vexu** [comment] 2021-12-23 08:58
Duplicate of #6059.

**Closed by Vexu** 2021-12-23 08:58 UTC
Labels: bug

**Comment by basile-henry** [comment] 2021-12-23 09:06
Oh I should have looked before spending time making the repro smaller :sweat_smile:
