### ISSUE TITLE
`zig build-obj` generates `*.o.o` files

### ISSUE THREAD

**Issue by CrepeGoat** [ziglang/zig#17635] opened 2023-10-20 06:11 UTC
### Zig Version

0.12.0-dev.163+6780a6bbf

### Platform details
```sh
$ zig targets | jq .native
{
  "triple": "aarch64-macos.13.4.1...13.4.1-none",
  "cpu": {
    "arch": "aarch64",
    "name": "apple_a14",
    "features": [...]
  },
  "os": "macos",
  "abi": "none"
}
```

### Steps to Reproduce and Observed Behavior

1. take an arbitrary zig file, e.g. the following `main.zig`:
```zig
pub fn main() void {
    return;
}
```

2. generate an object file by running `zig build-obj main.zig`

This generates the object file `main.o`, which is what I wanted! It also generates a file `main.o.o`, which is not desirable. Note that `diff` claims the contents of these two files are identical.

### Expected Behavior

to not generate a `_.o.o` file.

**Comment by Vexu** [comment] 2023-10-20 09:43
Duplicate of #13179

**Closed by Vexu** 2023-10-20 09:43 UTC
Labels: bug
