### ISSUE TITLE
Slicing at compile time doesn't update backing array

### ISSUE THREAD

**Issue by N00byEdge** [ziglang/zig#10211] opened 2021-11-23 22:46 UTC
### Zig Version

0.9.0-dev.1700+b644d4936

### Steps to Reproduce
Godbolt playground: https://gcc.godbolt.org/z/37cEG7aW6
I used [the stdlib test for Salsa20](https://github.com/ziglang/zig/blob/master/lib/std/crypto/salsa20.zig#L552-L564). It works at runtime but not at comptime:
```zig
    const key = [_]u8{0x69} ** 32;
    const nonce = [_]u8{0x42} ** 8;
    const msg = [_]u8{0} ** 20;
    var c: [msg.len]u8 = undefined;
    Salsa20.xor(&c, msg[0..], 0, key, nonce);
```

The following diff somehow works around the compiler bug and makes it pass, even at comptime. I hope it helps narrow down what's failing here:
```diff
diff --git a/salsa20.zig b/salsa20.zig
index 0e7d67b..714f4a4 100644
--- a/salsa20.zig
+++ b/salsa20.zig
@@ -247,7 +247,9 @@ const Salsa20NonVecImpl = struct {

     fn hashToBytes(out: *[64]u8, x: BlockVec) void {
         for (x) |w, i| {
-            mem.writeIntLittle(u32, out[i * 4 ..][0..4], w);
+            var tmp : [4]u8 = undefined;
+            mem.writeIntLittle(u32, &tmp, w);
+            std.mem.copy(u8, out[i * 4 .. ][0..4], &tmp);
         }
     }

@@ -257,8 +259,8 @@ const Salsa20NonVecImpl = struct {
         var buf: [64]u8 = undefined;
         var i: usize = 0;
         while (i + 64 <= in.len) : (i += 64) {
-            salsa20Core(x[0..], ctx, true);
-            hashToBytes(buf[0..], x);
+            salsa20Core(&x, ctx, true);
+            hashToBytes(&buf, x);
             var xout = out[i..];
             const xin = in[i..];
             var j: usize = 0;
@@ -272,8 +274,8 @@ const Salsa20NonVecImpl = struct {
             ctx[9] += @boolToInt(@addWithOverflow(u32, ctx[8], 1, &ctx[8]));
         }
         if (i < in.len) {
-            salsa20Core(x[0..], ctx, true);
-            hashToBytes(buf[0..], x);
+            salsa20Core(&x, ctx, true);
+            hashToBytes(&buf, x);

             var xout = out[i..];
             const xin = in[i..];
@@ -305,7 +307,8 @@ const Salsa20NonVecImpl = struct {
     }
 };

-const Salsa20Impl = if (builtin.cpu.arch == .x86_64) Salsa20VecImpl else Salsa20NonVecImpl;
+//const Salsa20Impl = if (builtin.cpu.arch == .x86_64) Salsa20VecImpl else Salsa20NonVecImpl;
+const Salsa20Impl = Salsa20NonVecImpl; // DEBUG: Force non-vector implementation which we "fixed" above. The vector fix was even more complicated.

 fn keyToWords(key: [32]u8) [8]u32 {
     var k: [8]u32 = undefined;
```

### Expected Behavior

I expect the result array to be filled with the correct data

### Actual Behavior

The array isn't written to, the old value there is unchanged.

**Comment by N00byEdge** [comment] 2021-11-23 22:49
Imho this is quite a bad one since I've only seen it show up by silently failing while doing crypto, which seems like a bad thing.

**Comment by lithdew** [comment] 2021-12-03 20:33
Ran into this same issue as well while using SHA2-256 at comptime. Would it be worth submitting PR's to work around this issue for the time being?

Godbolt: https://zig.godbolt.org/z/EYvoavf8j

**Comment by N00byEdge** [comment] 2021-12-03 21:18
Yeah one could submit patches with those workarounds, but there's no guarantee that it will keep working.

**Comment by jcmoyer** [comment] 2021-12-07 08:05
I believe this is a duplicate of #8304. I also ran into the same problem with comptime md5.

**Closed** 2023-03-14 11:06 UTC
Labels: bug, stage1, miscompilation
