### ISSUE TITLE
Zig compiler bug: "broken LLVM module found: PHI node entries do not match predecessors!"

### ISSUE THREAD

**Issue by LewisGaul** [ziglang/zig#8535] opened 2021-04-14 22:55 UTC
Reproduce using https://github.com/LewisGaul/zig-nestedtext/tree/zig-compiler-bug (seen with fairly recently master branch build, `0.8.0-dev.1726+b4e3507f8`, WSL1).
```
$zig test tests/testsuite.zig --pkg-begin nestedtext src/nestedtext.zig --pkg-end -femit-bin=testsuite
broken LLVM module found: PHI node entries do not match predecessors!
  %93 = phi i1 [ %85, %Else4 ], [ %92, %UnwrapOptionalOk28 ], !dbg !13755
label %UnwrapOptionalOk28
label %CmpOptionalNonOptionalEnd
Instruction does not dominate all uses!
  %92 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull ], [ %91, %CmpOptionalNonOptionalOptionalNotNull ], !dbg !13759
  %93 = phi i1 [ %85, %Else4 ], [ %92, %UnwrapOptionalOk28 ], !dbg !13755
PHI node entries do not match predecessors!
  %103 = phi i1 [ %95, %Else9 ], [ %102, %UnwrapOptionalOk35 ], !dbg !13905
label %Else9
label %CmpOptionalNonOptionalEnd
Instruction does not dominate all uses!
  %102 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull ], [ %101, %CmpOptionalNonOptionalOptionalNotNull ], !dbg !13909
  %103 = phi i1 [ %95, %Else9 ], [ %102, %UnwrapOptionalOk35 ], !dbg !13905

This is a bug in the Zig compiler.thread 1010 panic:
/mnt/c/Users/legaul/Documents/personal/zig/src/stage1.zig:171:5: 0x7f35286cd8cc in stage2_panic (zig1)
    @panic(ptr[0..len]);
    ^
/mnt/c/Users/legaul/Documents/personal/zig/src/stage1/util.cpp:20:17: 0x7f35291c7bae in zig_panic (/mnt/c/Users/legaul/Documents/personal/zig/src/stage1/util.cpp)
    stage2_panic("", 0);
                ^
/mnt/c/Users/legaul/Documents/personal/zig/src/stage1/codegen.cpp:8478:18: 0x7f35291ed6c9 in do_code_gen (/mnt/c/Users/legaul/Documents/personal/zig/src/stage1/codegen.cpp)
        zig_panic("broken LLVM module found: %s\nThis is a bug in the Zig compiler.", error);
                 ^
/mnt/c/Users/legaul/Documents/personal/zig/src/stage1/codegen.cpp:9624:16: 0x7f35291f240a in codegen_build_object (/mnt/c/Users/legaul/Documents/personal/zig/src/stage1/codegen.cpp)
    do_code_gen(g);
               ^
/mnt/c/Users/legaul/Documents/personal/zig/src/stage1/stage1.cpp:130:25: 0x7f35291c3539 in zig_stage1_build_object (/mnt/c/Users/legaul/Documents/personal/zig/src/stage1/stage1.cpp)
    codegen_build_object(g);
                        ^
/mnt/c/Users/legaul/Documents/personal/zig/src/stage1.zig:143:32: 0x7f3528a72fa4 in Module.build_object (zig1)
        zig_stage1_build_object(mod);
                               ^
/mnt/c/Users/legaul/Documents/personal/zig/src/Compilation.zig:3426:31: 0x7f3528882931 in Compilation.updateStage1Module (zig1)
    stage1_module.build_object();
                              ^
/mnt/c/Users/legaul/Documents/personal/zig/src/Compilation.zig:1866:36: 0x7f35288395a2 in Compilation.performAllTheWork (zig1)
            self.updateStage1Module(main_progress_node) catch |err| {
                                   ^
/mnt/c/Users/legaul/Documents/personal/zig/src/Compilation.zig:1422:31: 0x7f352883321f in Compilation.update (zig1)
    try self.performAllTheWork();
                              ^
/mnt/c/Users/legaul/Documents/personal/zig/src/main.zig:2089:20: 0x7f35287c574f in main.updateModule (zig1)
    try comp.update();
                   ^
/mnt/c/Users/legaul/Documents/personal/zig/src/main.zig:1930:17: 0x7f35286f5837 in main.buildOutputType (zig1)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/mnt/c/Users/legaul/Documents/personal/zig/src/main.zig:176:31: 0x7f35286cc35b in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/mnt/c/Users/legaul/Documents/personal/zig/src/stage1.zig:45:24: 0x7f35286cbafe in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
???:?:?: 0x7f35228970b2 in ??? (???)
Aborted (core dumped)

**Comment by Vexu** [comment] 2021-04-15 05:26
Duplicate of #6059.

**Closed by Vexu** 2021-04-15 05:26 UTC
