### ISSUE TITLE
lazy decl analysis prevents doc comments from making it into generated html documentation

### ISSUE THREAD

**Issue by lolbinarycat** [ziglang/zig#7400] opened 2020-12-11 20:12 UTC
examples:
```
const NUL: u8 = 0;
const SOH: u8 = 1;
const STX: u8 = 2;
```

**Comment by MasterQ32** [comment] 2020-12-11 20:38
We already have this:
https://github.com/ziglang/zig/blob/master/lib/std/ascii.zig#L19-L57

**Comment by lolbinarycat** [comment] 2020-12-11 20:55
@MasterQ32 not in the docs.

**Comment by andrewrk** [comment] 2021-01-03 06:14
duplicate of #7415

**Closed by andrewrk** 2021-01-03 06:14 UTC
