### ISSUE TITLE
Reference trace is not printed with --color off

### ISSUE THREAD

**Issue by f0rget-the-sad** [ziglang/zig#16928] opened 2023-08-22 20:40 UTC
### Zig Version

0.12.0-dev.127+3dd439030

### Steps to Reproduce and Observed Output

Lets say we have an error:
```zig
const std = @import("std");
const print = std.debug.print;


pub fn main() void {
    print("{}\n", .{"string"});
}
```
Trying to compile - error with referenced all good
```console
$ zig build-exe main.zig
/home/f0rget/zig/build-release/stage3/lib/zig/std/fmt.zig:604:25: error: cannot format array ref without a specifier (i.e. {s} or {*})
                        @compileError("cannot format array ref without a specifier (i.e. {s} or {*})");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    format__anon_7675: /home/f0rget/zig/build-release/stage3/lib/zig/std/fmt.zig:184:23
    print__anon_4189: /home/f0rget/zig/build-release/stage3/lib/zig/std/io/writer.zig:28:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```
But if you disable `--color off` referenced trace will be not shown (even with explicitly enabled `-freference-trace`)
```console
$ zig build-exe main.zig --color off -freference-trace
/home/f0rget/zig/build-release/stage3/lib/zig/std/fmt.zig:604:25: error: cannot format array ref without a specifier (i.e. {s} or {*})
```
It's extremely critical to have the referenced trace, especially in errors like this, where without it - it's impossible to tell where the error actually happened. (path mentioned in error is not from the main.zig it's from zig format code)

### Expected Output

Have the referenced trace independent of color setting

```console
$ zig build-exe main.zig --color off -freference-trace
/home/f0rget/zig/build-release/stage3/lib/zig/std/fmt.zig:604:25: error: cannot format array ref without a specifier (i.e. {s} or {*})

referenced by:
    format__anon_7675: /home/f0rget/zig/build-release/stage3/lib/zig/std/fmt.zig:184:23
    print__anon_4189: /home/f0rget/zig/build-release/stage3/lib/zig/std/io/writer.zig:28:34
    print__anon_3495: /home/f0rget/zig/build-release/stage3/lib/zig/std/debug.zig:88:27
    main: main.zig:6:10
    callMain: /home/f0rget/zig/build-release/stage3/lib/zig/std/start.zig:564:17
    initEventLoopAndCallMain: /home/f0rget/zig/build-release/stage3/lib/zig/std/start.zig:508:34
    callMainWithArgs: /home/f0rget/zig/build-release/stage3/lib/zig/std/start.zig:458:12
    posixCallMainAndExit: /home/f0rget/zig/build-release/stage3/lib/zig/std/start.zig:414:39
    _start: /home/f0rget/zig/build-release/stage3/lib/zig/std/start.zig:327:40
```

**Comment by wooster0** [comment] 2023-08-22 21:40
Duplicate of #16376

**Closed** 2023-08-23 13:49 UTC
Labels: error message
