### ISSUE TITLE
TODO "" crash caused by c_longdouble literal

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#5493] opened 2020-05-31 16:12 UTC
```zig
comptime {
    _ = @as(c_longdouble, 1);
}
```
```
> zig build
TODO
Unable to dump stack trace: debug info stripped
```
Looking at #1188, it seems that assigning a literal value to a c_longdouble used to work.
```zig
comptime {
    _ = @as(c_longdouble, undefined);
}
```
This code works as expected.

**Comment by Vexu** [comment] 2020-05-31 16:49
Duplicate of #4997 and #1188.

Long doubles are pretty much completely unimplemented in stage 1 and will probably remain that way unless the eventual stage 2 implementation gets backported.

**Closed by Vexu** 2020-05-31 16:49 UTC
