### ISSUE TITLE
`zig test` doesn't show individual test output. Propose new --test-verbose flag.

### ISSUE THREAD

**Issue by lukekras** [ziglang/zig#10203] opened 2021-11-22 06:40 UTC
### Zig Version

0.9.0-dev.1679+6cf8a49bb

### Steps to Reproduce

`zig test` doesn't show individual test success/fail summaries.

E.g. testdecl_container_top_level.zig from zig [documentation](https://ziglang.org/documentation/master/#toc-Nested-Container-Tests).

Tested on MacBook Pro (Intel) Big Sur.

`This started as a bug and has been changed to a proposal for a --test-verbose flag for zig test. See comments below for details.`

### New Behavior with --test-verbose flag

$ zig test --test-verbose testdecl_container_top_level.zig
Test [1/5] test ""...
Test [2/5] S.test "S demo test"...
Test [3/5] U.test "U demo test"...
Test [4/5] introducing_zig_test.test "expect addOne adds one to 41"...
Test [5/5] US.test "U.US demo test"...
All 5 tests passed.

### Behavior without test verbose flag (current behaviour)

$ zig test testdecl_container_top_level.zig
All 5 tests passed.

**Comment by slimsag** [comment] 2021-11-22 07:18
If you use:

```
zig test testdecl_container_top_level.zig 2>&1|cat
```

Then you'll get the verbose output as described in the documentation. I don't know why this is, though, and I certainly find this to be confusing :)

**Comment by lukekras** [comment] 2021-11-22 07:29
@slimsag Thanks for that. I tested it and it works exactly like you say, but I don't understand why that works.

**Comment by VojtechStep** [comment] 2021-11-22 07:42
I would expect the command to check if it outputs to a TTY, and if so, it uses escape sequences to overwrite the text in the terminal.
Piping it to `cat` makes stdout and stderr regular files (not-a-TTY), so it produces regular text output.

**Comment by lukekras** [comment] 2021-11-22 08:04
@VojtechStep That makes sense. Thankyou.

**Comment by slimsag** [comment] 2021-11-22 18:19
I would change this issue into a feature request for a verbose flag.

I am fine with the TTY detection behavior, but as a newcomer it's very confusing IMO. The first thing one does is look for a `-v` or `--verbose` flag, which is what test suites do in other languages (e.g. Go) and it would be nice for people to not have to recall their shell's redirection logic I think.

**Comment by lukekras** [comment] 2021-11-23 00:36
Zig is not accepting new proposals at this time (i.e. via the New Issue button -> Language Proposal). I'll summarise, and an appropriate Zig maintainer can make a call.

1. Currently `zig test` outputs only the entire test suite summary, and not the individual test results as per the [zig master documentation](https://ziglang.org/documentation/master/#toc-Nested-Container-Tests). Just printing the test suite summary, probably is the correct behaviour, and from a usability perspective, is intuitive and inline with good decisions made in other languages (e.g. Go). Keeping this behaviour would turn this issue into a documentation bug.
2. There is a workaround, whereby the user can get individual test results e.g. `zig test testdecl_container_top_level.zig 2>&1 | cat`. I would consider this side effect behaviour of shells, and non-intuitive. It does lower the priority of any change, because there is a workaround.
3. For the longer term, perhaps a `--test-verbose` command line flag should be added to zig test and be grouped with the other `Test Options:` when using `zig test --help`. For example:

`zig test --test-verbose testdecl_container_top_level.zig`
Test [1/5] test ""...
Test [2/5] S.test "S demo test"...
Test [3/5] U.test "U demo test"...
Test [4/5] introducing_zig_test.test "expect addOne adds one to 41"...
Test [5/5] US.test "U.US demo test"...
All 5 tests passed.

`zig test testdecl_container_top_level.zig`
All 5 tests passed.

**Comment by andrewrk** [comment] 2021-11-23 00:39
Feel free to transform this issue into a proposal :+1:

**Comment by acarrico** [comment] 2023-10-22 12:46
I think this issue is fixed in the ```zig test``` context, but a similar issue has cropped up in ```zig build test```, which is addressed in issue #16673. Here is ```zig test```:

```
$ ./zig test test.zig
1/1 test.basic add functionality... OK
All 1 tests passed.

$ ./zig version
0.12.0-dev.306+a0968be83
```

**Comment by deadblackclover** [comment] 2023-11-01 13:01
@acarrico Yes, via `zig test` works and the output is quite informative. But just `zig build test` does not work as before. Maybe you need to fix the `build.zig` file somehow.

But using `zig test` is not really convenient, because you have to specify which file you want to test.

**Comment by acarrico** [comment] 2023-11-02 12:40
@deadblackclover, great that ```zig test``` is working for you now also; hopefully @lukekras will close this issue, and we can focus on ```zig build test``` in #16673.

**Closed** 2023-11-04 00:34 UTC
Labels: proposal

**Comment by zomglings** [comment] 2024-01-05 14:02
Was there some regression of this functionality in `zig test`?

This is my `zig` version:

```
$ zig version
0.12.0-dev.2043+6ebeb85ab
```

(Installed following suggestions from ziglings.org, but it might be an issue that I'm using the `dev` build)

Running these tests: https://ziglang.org/documentation/master/#Nested-Container-Tests

This is what I see:

```
$ zig test testing_nested_container_tests.zig 2>&1 | cat
1/5 test_0... OK
2/5 test.S demo test... OK
3/5 test.U demo test... OK
4/5 test.expect addOne adds one to 41... OK
5/5 decltest.addOne... OK
All 5 tests passed.
```

But:

```
$ zig test testing_nested_container_tests.zig
All 5 tests passed.
```

**Comment by marcoziti** [comment] 2025-03-20 12:25
I'd take it as a regression bug other than a feature.
