### ISSUE TITLE
Miscompilation setting packed struct field to undefined

### ISSUE THREAD

**Issue by jadedpasta** [ziglang/zig#21731] opened 2024-10-17 06:38 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

I am running x86_64 Linux

The following small program reproduces the issue:
```zig
const std = @import("std");

const P = packed struct {
    a: bool = false,
    b: bool = false,
};

pub fn main() void {
    var p = P{};
    p = P{
        .a = undefined,
        .b = true,
    };
    if (p.b) {
        std.debug.print("good\n", .{});
    } else {
        std.debug.print("bug\n", .{});
    }
}
```

```console
$ zig build-exe repro.zig
$ ./repro
bug
$ objdump -M intel --disassemble=repro.main repro.o

repro.o:     file format elf64-x86-64


Disassembly of section .text:

0000000000000bf0 <repro.main>:
     bf0:	55                   	push   rbp
     bf1:	48 89 e5             	mov    rbp,rsp
     bf4:	48 83 ec 10          	sub    rsp,0x10
     bf8:	c6 45 ff 00          	mov    BYTE PTR [rbp-0x1],0x0
     bfc:	8a 45 ff             	mov    al,BYTE PTR [rbp-0x1]
     bff:	24 02                	and    al,0x2
     c01:	d0 e8                	shr    al,1
     c03:	a8 01                	test   al,0x1
     c05:	75 08                	jne    c0f <repro.main+0x1f>
     c07:	eb 0d                	jmp    c16 <repro.main+0x26>
     c09:	48 83 c4 10          	add    rsp,0x10
     c0d:	5d                   	pop    rbp
     c0e:	c3                   	ret
     c0f:	e8 6c 20 00 00       	call   2c80 <debug.print__anon_3330>
     c14:	eb f3                	jmp    c09 <repro.main+0x19>
     c16:	e8 25 22 00 00       	call   2e40 <debug.print__anon_3331>
     c1b:	eb ec                	jmp    c09 <repro.main+0x19>
```

Replacing `undefined` with `true` or `false` causes the correct output to be generated.

### Expected Behavior

Zig should emit machine code such that `p.b` is set to `true`

**Comment by Vexu** [comment] 2024-10-17 08:58
Duplicate of #20938

**Closed by Vexu** 2024-10-17 08:58 UTC
Labels: bug
