### ISSUE TITLE
Hard tabs cause compile error

### ISSUE THREAD

**Issue by leighmcculloch** [ziglang/zig#11067] opened 2022-03-06 07:21 UTC
### Zig Version

0.10.0-dev.1026+87dc60e8d

### Steps to Reproduce

1. Create a zig file with hard tabs as indents. For example:

   ```
   const std = @import("std");
   
   pub fn main() !void {
   	const stdout = std.io.getStdOut().writer();
   	try stdout.print("Hello, {s}!\n", .{"world"});
   }
   ```

2. `zig run file.zig`

### Expected Behavior

```
$ zig run file.zig
Hello, world!
```

I expect the program to run because the zig documentation states:
https://github.com/ziglang/zig/blob/72992b6513b3c6f5d8bd0abffe0d08a2a7d6e7cd/doc/langref.html.in#L11685-L11686

Also visible at:
https://ziglang.org/documentation/master/#toc-Source-Encoding

### Actual Behavior

```
$ zig run file.zig
./file.zig:4:1: error: invalid character: '\t'
        const stdout = std.io.getStdOut().writer();
^
```

### Thoughts

Maybe the documentation is out of date?

**Comment by ominitay** [comment] 2022-03-06 09:26
Duplicate of #544

**Comment by pfgithub** [comment] 2022-03-06 15:06
The current stage1 compiler does not accept hard tabs, while the work-in-progress stage2 compiler does. This is written in a note below that line in the documentation

> HT hard tabs (byte value 0x09, code point U+0009, '\t') are interchangeable with SP spaces (byte value 0x20, code point U+0020, ' ') as a token separator, but use of hard tabs is discouraged. See [Grammar](https://ziglang.org/documentation/master/#Grammar).
>
> Note that running zig fmt on a source file will implement all recommendations mentioned here. Note also that the stage1 compiler does [not yet support CR or HT](https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs) control characters.

**Comment by andrewrk** [comment] 2022-03-07 03:18
oh my god please stop talking about tabs. I promise it will all be sorted out with 1.0 / lang spec.

**Closed by andrewrk** 2022-03-07 03:18 UTC
Labels: bug

**Comment by andrewrk** [comment] 2022-03-07 09:08
I apologize for the annoyed tone I took above. Please have a look at this FAQ entry:
https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs
