### ISSUE TITLE
enum backed by an integer under 8 bits causes compiler panic when used as a field in a packed struct

### ISSUE THREAD

**Issue by kcbanner** [ziglang/zig#12819] opened 2022-09-12 00:10 UTC
### Zig Version

0.10.0-dev.3984+e8df2da01

### Steps to Reproduce

Compile this code:

```zig
const std = @import("std");

pub const UnwindOpcode = enum(u4) {
    FOO,
    BAR,
};

pub const UnwindCode = packed struct(u16) {
    offset_in_prolog: u8,
    unwind_opcode: UnwindOpcode,
    operation_info: u4
};

pub fn main() !void {
    const unwind_codes: [2]UnwindCode = .{
        @bitCast(UnwindCode, @as(u16, 0x1234)),
        @bitCast(UnwindCode, @as(u16, 0x5678)),
    };

    _ = unwind_codes;
}
```

### Expected Behavior

The code compiles

### Actual Behavior

`thread 18888 panic: reached unreachable code`.

In the real code (too large to extract here), I was hitting `panic: index out of bounds` instead - but when reducing it to a test case I couldn't trigger that error, just the unreachable code one.

**Comment by nektro** [comment] 2022-09-12 01:55
should be using `@intToEnum` instead of `@bitCast`

**Comment by kcbanner** [comment] 2022-09-12 02:40
The `@bitCast` is intentional, since I'm casting to the packed struct `UnwindCode` (not the enum `UnwindOpcode`).

I should have picked less confusing names when reducing this test case from my code.

**Comment by Vexu** [comment] 2022-09-12 09:32
Duplicate of #12468

**Closed by Vexu** 2022-09-12 09:32 UTC
Labels: bug
