### ISSUE TITLE
Valid program gets strange error message for "generic" types mismatching

### ISSUE THREAD

**Issue by CurtisFenner** [ziglang/zig#5352] opened 2020-05-15 19:45 UTC
The following code receives a strange error when compiled in zig 0.6.0:

```zig
const std = @import("std");

pub const Choice = union(enum) {
    Option: usize,
};

pub fn Leaf(comptime unused: []const u8) type {
    return struct {
        const T = @This();
        // Replacing `@field(Choice, "Option")` with `Choice.Option` makes
        // error go away.
        value: std.meta.TagPayloadType(Choice, @field(Choice, "Option")),
    };
}

pub const Container = struct {
    myfield: Leaf("Option"),
};

// "Inlining" bad()'s body into the test makes error go away.
// Changing return type from Container makes error go away.
pub fn bad() Container {
    var result: Container = undefined;

    const raw = Leaf("Option"){ .value = 7 };
    result.myfield = raw;

    return undefined;
}

test "Parse simple variable declaration statement" {
    _ = bad;
}

```

The reported error is
```
.\src\bad.zig:26:22: error: expected type 'Leaf("Option")', found 'Leaf("Option")'
    result.myfield = raw;
                     ^
.\src\bad.zig:8:12: note: Leaf("Option") declared here
    return struct {
           ^
.\src\bad.zig:8:12: note: Leaf("Option") declared here
    return struct {
           ^
```

As far as I can tell, this code should compile and run fine. Many minor tweaks to the program makes the error go away:

* "Inlining" the `bad()` function into the test makes the error go away
* Changing the return type of `bad()` to anything else (e.g., `usize`, `void`) makes the error go away
* Replacing `@field(Choice, "Option")` with `Choice.Option`
* Replacing `Leaf("Option")` with `Leaf("f")` or any other string

The code that I reduced this from compiled without complaint before 0.6.0.

Beyond fixing this bug, I think it may be necessary to fix the error-message-generating code, since `expected type 'Leaf("Option")', found 'Leaf("Option")'` is clearly missing some information that Zig is using when it is comparing the types.

**Comment by pixelherodev** [comment] 2020-05-16 02:26
This isn't a bug, I think.

If you look at the [documentation for @field](https://ziglang.org/documentation/master/#field), you'll see that the usage shown is for accessing fields of an *object*, not of a *type*.

**Comment by CurtisFenner** [comment] 2020-05-16 03:24
@pixelherodev 

If you change the return type of `bad` to `usize` or change the argument to `Leaf` to `"foo"` , it compiles. Those changes have nothing to do with the `@field(Choice, "Option")` line; even if the given code is wrong, the compiler is either incorrectly accepting those variants or incorrectly rejecting this variant (it's "spooky action at a distance"). There _is_ a bug present here.

Further, the error message isn't in reference to the `@field` access being bad, it's just producing an invalid type.

And for what it's worth, the standard library does use `@field` to access constants in types.  For examples:
 * https://github.com/ziglang/zig/blob/f8b99331a2ca98f0e938c8caaf1cd232ad1e9fa3/lib/std/meta.zig#L601
* https://github.com/ziglang/zig/blob/f8b99331a2ca98f0e938c8caaf1cd232ad1e9fa3/lib/std/meta/trait.zig#L56
* https://github.com/ziglang/zig/blob/83c664eaa080669cff83f7c30046376f3399eafb/src-self-hosted/decl.zig#L26

**Comment by Vexu** [comment] 2022-02-18 11:30
Closing as duplicate of #7948 which has more discussion.

**Closed by Vexu** 2022-02-18 11:30 UTC
Labels: bug, stage1
