### ISSUE TITLE
Bug: broken LLVM module found: Expected no forward declarations! This is a bug in the Zig compiler.

### ISSUE THREAD

**Issue by gaultier** [ziglang/zig#6793] opened 2020-10-24 17:54 UTC
I am writing a small compiler and I have an AST which is a tagged union, reduced to:

```zig
pub const Node = union(enum) {
    BuiltinPrint: BuiltinPrint,
   // other options here but not necessary to trigger the bug

    pub const BuiltinPrint = struct {
        arg: *Node,
    };
};

pub fn parse() []*Node {
    return &[0]*Node{};
}

pub fn main() anyerror!void {
    _ = parse();
}
```

When compiling this file I get:

```sh
$ zig build-exe bug.zig
Code Generation [243/539] std.debug.Config.setColor... broken LLVM module found: Expected no forward declarations!
!1607 = <temporary!> !DICompositeType(tag: DW_TAG_structure_type, name: "Node", scope: !1591, file: !1591, line: 1, flags: DIFlagFwdDecl)

This is a bug in the Zig compiler.
/Users/pgaultier/code/zig/src/main.zig:157:26: 0x1012b2635 in main.mainArgs (zig1)
    const cmd_args = args[2..];
                         ^
???:?:?: 0x1063ccc8f in ??? (???)
???:?:?: 0x101c503fa in __ZL11do_code_genP7CodeGen (???)
???:?:?: 0x101c4d1a0 in __Z20codegen_build_objectP7CodeGen (???)
???:?:?: 0x101d56e8f in _zig_stage1_build_object (???)
/Users/pgaultier/code/zig/lib/std/fmt.zig:193:21: 0x1015ae6a4 in std.fmt.format (zig1)
                    try formatType(
                    ^
/Users/pgaultier/code/zig/src/Compilation.zig:2504:24: 0x101417150 in Compilation.buildStaticLibFromZig (zig1)
    const target = comp.getTarget();
                       ^
/Users/pgaultier/code/zig/src/Module.zig:0:0: 0x1013d358e in ??? (zig1)
/Users/pgaultier/code/zig/src/Cache.zig:187:9: 0x1013cd56c in Cache.Manifest.addFile (zig1)
        try self.files.ensureCapacity(self.cache.gpa, self.files.items.len + 1);
        ^
/Users/pgaultier/code/zig/src/main.zig:1984:9: 0x1013856d7 in main.cmdTranslateC (zig1)
        try io.getStdOut().writer().print("{}\n", .{full_zig_path});
        ^
/Users/pgaultier/code/zig/src/main.zig:1507:43: 0x1012d902d in main.buildOutputType (zig1)
    defer if (cleanup_root_dir) |*dir| dir.close();
                                          ^
/Users/pgaultier/code/zig/src/main.zig:132:23: 0x1012b1340 in main.mainArgs (zig1)
        var env_map = try std.process.getEnvMap(arena);
                      ^
/Users/pgaultier/code/zig/lib/std/debug.zig:267:29: 0x1012b0d5f in std.debug.panicExtra (zig1)
                stderr.print(format ++ "\n", args) catch os.abort();
                            ^
???:?:?: 0x7fff6f6a5cc8 in ??? (???)
???:?:?: 0x2 in ??? (???)
zsh: abort      zig build-exe bug.zig

```

My guess is that it is due to the AST Node being 'cyclic' and the LLVM IR is not generated correctly in the sense that forward declarations for the Node type is not generated first. 

In C one would forward declare the Node struct (rougly):
```c
union Node;

struct BuiltinPrint {
    union Node* arg;
};
union Node {
    struct BuiltinPrint builtinPrint;
};
```
And I think the LLVM IR works similarly, and the LLVM IR that Zig generates basically is missing the first line that forward declares.

Zig version: 0.6.0+91a1c20e7
Platform: macos, x86_64

**Comment by Vexu** [comment] 2020-12-04 18:37
Duplicate of #5197.

**Closed by Vexu** 2020-12-04 18:37 UTC
Labels: bug, stage1
