### ISSUE TITLE
compiler produces binary that segfaults

### ISSUE THREAD

**Issue by danielchasehooper** [ziglang/zig#13740] opened 2022-12-02 17:15 UTC
### Zig Version

0.11.0-dev.43+b2f8c1f2e

### Steps to Reproduce and Observed Behavior

switch_crash.zig:
```
const std = @import("std");

const data = 
\\B X
\\C Z
;

pub fn main() !void {
    var rounds = std.mem.split(u8, data, "\n");
    _  = switch (rounds.next().?[0..3]) {
        "B X" => 1,
        "B Y" => 5,
        else => 0,
    };
}
```

```
$ zig run ../../zigtests/switch_crash.zig 
LLVM Emit Object... Segmentation fault: 11
```

### Expected Behavior

shouldn't crash.

**Comment by nektro** [comment] 2022-12-02 17:22
as a workaround: you're not allowed to switch on strings btw. if you know the possible values you can use something like `std.meta.stringToEnum`

**Comment by Vexu** [comment] 2022-12-02 17:47
Duplicate of #7357

**Closed by Vexu** 2022-12-02 17:47 UTC
Labels: bug
