### ISSUE TITLE
Re-slicing and accessing array of zero-length slices backed by arrays causes segmentation fault.

### ISSUE THREAD

**Issue by lithdew** [ziglang/zig#5876] opened 2020-07-15 13:21 UTC
Stumbled upon this and curious if this is expected behavior.

## Test Case

```zig
test "slices" {
    var storage: [4][]u8 = undefined;
    for (storage) |*slice| {
        var buf: [10]u8 = undefined;
        slice.* = buf[0..0];
    }

    var idx: usize = 0;

    storage[idx] = storage[idx].ptr[0..1];
    storage[idx][0] = 1;
}
```

Expected it to compile and run fine, though got a segmentation fault instead.

## Output

```shell
$ zig test src/test.zig 
Test [1/1] test "slices"...Segmentation fault at address 0x0
/home/kenta/lithdew/monte-zig/src/test.zig:11:23: 0x205135 in test "slices" (test)
    storage[idx][0] = 1;
                      ^
/snap/zig/1896/lib/zig/std/special/test_runner.zig:48:28: 0x230c05 in std.special.main (test)
        } else test_fn.func();
                           ^
/snap/zig/1896/lib/zig/std/start.zig:252:37: 0x205f7d in std.start.posixCallMainAndExit (test)
            const result = root.main() catch |err| {
                                    ^
/snap/zig/1896/lib/zig/std/start.zig:123:5: 0x205cbf in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
```

## Alternative

Updating the test case to manually back slices in the array fixes the issue.

```zig
test "slices" {
    var storage: [4][]u8 = undefined;
    for (storage) |*slice| {
        var buf: [10]u8 = undefined;
        slice.*.ptr = @ptrCast([*]u8, &buf[0]);
        slice.*.len = 0;
    }

    var idx: usize = 0;

    storage[idx] = storage[idx].ptr[0..1];
    storage[idx][0] = 1;
}
```

**Comment by daurnimator** [comment] 2020-07-15 13:38
Why close this? I've run into it before too...
It seems that slicing with `0` length results in an entirely null slice; whereas it should been `.ptr` and change `.len` to 0.

**Comment by lithdew** [comment] 2020-07-15 13:42
> Why close this? I've run into it before too...
> It seems that slicing with `0` length results in an entirely null slice; whereas it should been `.ptr` and change `.len` to 0.

My bad! I had it clarified from Discord that the issue was that `buf`, the backing array to each slice, is deallocated from the stack which is why `storage[idx].ptr` points to invalid memory.

I did not notice that slicing with 0 length results in an entirely null slice though; I'll re-open this.

**Comment by Vexu** [comment] 2020-07-15 14:06
Duplicate of #4771.

**Closed by Vexu** 2020-07-15 14:06 UTC
