### ISSUE TITLE
undefined symbol: __muldc3 & __divdc3

### ISSUE THREAD

**Issue by plajjan** [ziglang/zig#12922] opened 2022-09-21 17:14 UTC
### Zig Version

0.9.1 & 0.10.0-dev.4060+61aaef0b0

### Steps to Reproduce

I'm trying to use zig as a drop in C compiler in Acton, a programming language that compiles to C. The use of zig is two-fold;
- compiling the Acton system, like builtins & run time system
- bundling zig with Acton so that when a user runs `actonc`, the acton compiler, it produces C which is then compiled to an executable using zig

It appears that the first part works just fine. The Acton builtins & RTS compiles using zig.

Trying to compile an acton program using `actonc` fails when it calls out to zig due to some undefined symbols.

This is my first time using zig so I'm sorry if I'm missing something obvious.

Anyway, to reproduce:
- setup zig somewhere and include in path
- on debian / ubuntu: `apt install gcc haskell-stack libbsd-dev libmd-dev libprotobuf-c-dev libutf8proc-dev libuv1-dev make pkg-config procps uuid-dev zlib1g-dev`
- or on mac: `brew install argp-standalone haskell-stack libuv pkg-config protobuf-c utf8proc`
- `git clone https://github.com/actonlang/acton.git`
- `cd acton && git checkout zig`
- `make -j`
- then compile an acton program, using --tempdir to have all the intermediate C output saved
  - `dist/bin/actonc --tempdir debugzig examples/helloworld.act`
  - the compilation will fail with the error documented below
- go look at the code in `debugzig` directory and see `debugzig/build.sh` which contains the commands to compile the intermediate C stuff to a binary
- the last command, which actually is supposed to produce an executable binary, will fail

How can I debug this further?

### Expected Behavior

zig should compile my program.

### Actual Behavior

```
ld.lld: error: undefined symbol: __muldc3
>>> referenced by builtin.c
>>>               builtin_rel.o:($Number$complex$__mul__) in archive /home/kll/terastream/acton/dist/lib/rel/libActon.a
>>> did you mean: __muldf3
>>> defined in: /home/kll/.cache/zig/o/1b0db14fbbddf55fa8f0d3283254bab5/libcompiler_rt.a

ld.lld: error: undefined symbol: __divdc3
>>> referenced by builtin.c
>>>               builtin_rel.o:($Div$complex$__truediv__) in archive /home/kll/terastream/acton/dist/lib/rel/libActon.a
>>> did you mean: __divdf3
>>> defined in: /home/kll/.cache/zig/o/1b0db14fbbddf55fa8f0d3283254bab5/libcompiler_rt.a
```

**Comment by williamstein** [comment] 2022-09-21 17:24
I have hit exactly the same problem in https://github.com/sagemathinc/zython

My guess is the zig devs just haven't got around to including these standard c library functions that are defined in musl, but I'll let them comment on this.  I'm mainly posting in the hopes of increasing the priority of this issue, since it's one I also am annoyed by.

For Zython, I found all the relevant code buried in emscripten or musl, and build another small C library specifically with this missing functionality.  Here's where that's done:

https://github.com/sagemathinc/zython/tree/main/packages/posix-wasm/src/lib/builtins

**Comment by Vexu** [comment] 2022-09-21 17:27
Duplicate of #9259

**Closed by Vexu** 2022-09-21 17:27 UTC
Labels: bug

**Comment by plajjan** [comment] 2022-09-21 17:47
Wow, cool, that was fast. @Vexu is there any form of workaround for this? ISTM that zig generated the code in the first place that it later fails to link. Guessing it has to do with underlying clang!?

I'd love a workaround.

Is there a way to tie a bounty to this particular issue?

**Comment by Vexu** [comment] 2022-09-21 18:01
> ISTM that zig generated the code in the first place that it later fails to link. Guessing it has to do with underlying clang!?

Those functions are being referenced to implement complex number arithmetic that is being used somewhere.

> I'd love a workaround.

If they aren't actually being called then you can just add stubs for them:
```zig
pub export fn __muldc3() void {
    @panic("TODO __muldc3 called");
}
```
For a more complicated but functional solution you can try to find GCC's or Clang's implementation for those functions and manually add them as dependencies.

> Is there a way to tie a bounty to this particular issue?

I don't know but @kristoff-it would probably be the person to ask.
Note that properly implementing these functions would also require solving #8465

**Comment by plajjan** [comment] 2022-09-21 18:08
Ouch, #8465 seems non trivial.

I wish I would be coming from a rich open source project that would be able to sponsor zig with a substantial amount on a continuous basis. However, that's not the case... But I'll donate $500 out of my own pocket when this is solved. I know it doesn't nearly cover the hours but it's something. Keep up the good work :)

**Comment by williamstein** [comment] 2022-09-21 18:18
> Wow, cool, that was fast. @Vexu is there any form of workaround for this? ISTM that zig generated the code in the first place that it later fails to link. Guessing it has to do with underlying clang!?
> 
> I'd love a workaround.

For what it is worth, I just described a workaround above that at least does work for me to exactly solve the issue of `ld.lld: error: undefined symbol: __muldc3` and similar errors.  It's just a couple of pages of C code, so you copy that code to your project, build it and link it in.  The code is all in 

https://github.com/sagemathinc/zython/tree/main/packages/posix-wasm/src/lib/builtins

and the makefile I use as part of the build process is 

https://github.com/sagemathinc/zython/blob/main/packages/posix-wasm/Makefile


I would be cautious with using stubs, since the fact you're having a link issue means the functions are referenced in some way.  Stubs can of course lead to crashes or incorrect results.  My project is building python, numpy, etc., so subtle math errors aren't an option for me.  They might be for you though.

**Comment by plajjan** [comment] 2022-09-21 20:35
@williamstein I dunno how but I misinterpreted your original reply - I just didn't get that you had a solution / workaround. I see now, that could indeed be a way forward for me! Will see if I can get that working..

**Comment by williamstein** [comment] 2022-09-21 21:23
I hope what I suggest works for you.  I realize what you're doing maybe has nothing to do with WebAssembly, but similar workarounds may work.  (Context:  I've been working on a painful (for me) project to get Python+packages+dynamic linking+subprocessor support+sockets building and working for WebAssembly *without using Emscripten*, and instead using only Zig.   It has involved many tricky workarounds like this.  Emscripten itself is also necessarily full of such things, but it's all kind of tangled up in there.)
