### ISSUE TITLE
stdlib: quaternions

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#19185] opened 2024-03-04 19:44 UTC
Discuss, whether quaternions should be deliberately out-of-scope for the stdlib and best left to third party geometry libraries, or if a rudimentary datatype could be added for other libraries to build upon?

**Comment by nektro** [comment] 2024-03-04 20:09
Duplicate https://github.com/ziglang/zig/issues/947

**Comment by slonik-az** [comment] 2024-03-05 13:26
Quaternions should NOT be in the sdtlib. It is too esoteric and multiple implementations exist for different use-cases. Clearly in the realm of specialized libraries.

**Comment by ajahraus** [comment] 2024-03-05 18:35
Are Complex numbers in the stdlib?

**Comment by slonik-az** [comment] 2024-03-05 20:11
Complex numbers naturally arise as an algebraic extension of real numbers when you take operations like `sqrt(-1)`. And set of complex numbers are algebraically closed, i.e. all algebraic operations on complex numbers result in complex numbers. Quaternions, on the other hand is a different construction all together. They are non-commutative and are an instance of Clifford algebra. They are very useful in graphics, for quaternions are naturally related to spacial rotations. Graphics, physics simulations, gaming libraries are the natural places to implement Quaternions.

**Comment by andrewrk** [comment] 2024-03-28 21:34
Duplicate of #947. This issue is also too vague. @expikr please keep your open non-bug issue count below 5. You are currently at 16, so you're already 11 over budget.

**Closed by andrewrk** 2024-03-28 21:34 UTC
