### ISSUE TITLE
Enum reification crashes compiler when having a duplicate field

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#13728] opened 2022-12-01 16:26 UTC
### Zig Version

0.11.0-dev.407+34fa6a1e0

### Steps to Reproduce and Observed Behavior

code:
```zig
const std = @import("std");

test {
    const enum_items = [_]std.builtin.Type.EnumField{
        .{ .name = "A", .value = 10 },
        .{ .name = "B", .value = 10 },
    };

    _ = @Type(std.builtin.Type{
        .Enum = .{
            .layout = .Auto,
            .tag_type = u32,
            .fields = &enum_items,
            .decls = &.{},
            .is_exhaustive = false,
        },
    });
}
```

invocation and output:
```
[felix@denkplatte-v2 zig]$ zig test ~/bug-repro/unreachable-in-zir.zig  --debug-compile-errors
thread 27950 panic: reached unreachable code
lib/std/debug.zig:278:14: 0x72c5446 in assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
lib/std/array_hash_map.zig:863:27: 0x7d822cc in putAssumeCapacityNoClobberContext (zig)
            assert(!result.found_existing);
                          ^
src/Sema.zig:18266:35: 0x793d36e in zirReify (zig)
                    .ty = enum_obj.tag_ty,
                                  ^
src/Sema.zig:1147:64: 0x7679225 in analyzeBodyInner (zig)
                    .reify                 => try sema.zirReify(             block, extended, inst),
                                                               ^
src/Sema.zig:5241:34: 0x7d2eb29 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
src/Sema.zig:5224:85: 0x79547e7 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                                                                    ^
src/Sema.zig:1449:69: 0x767d0e3 in analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
src/Sema.zig:798:30: 0x78433d8 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
src/Module.zig:5659:43: 0x764ff0c in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                                          ^
src/Module.zig:4342:40: 0x74952dd in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
src/Compilation.zig:3154:42: 0x7492e2c in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
src/Compilation.zig:3092:30: 0x7372317 in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
src/Compilation.zig:2401:31: 0x736ddbc in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
src/main.zig:3371:20: 0x739c91d in updateModule (zig)
    try comp.update();
                   ^
src/main.zig:3038:17: 0x72a9622 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
src/main.zig:236:31: 0x7287e94 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
src/stage1.zig:56:24: 0x74021df in main (zig)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
Aborted
exit code: 1
[felix@denkplatte-v2 zig]$
```

### Expected Behavior

Code to emit a compiler error similar to 
```
~/bug-repro/unreachable-in-zir.zig:6:9: error: enum tag value 10 already taken
        B = 10
```

**Comment by nektro** [comment] 2022-12-01 17:13
likely duplicate of #13606

**Closed** 2022-12-04 12:12 UTC
Labels: bug
