### ISSUE TITLE
build fails - 0.6.0 and master from 2020-06-18 19:30

### ISSUE THREAD

**Issue by ClaudeM** [ziglang/zig#5630] opened 2020-06-18 23:51 UTC
Hi,

Build fails with the following error.

[ 99%] Linking CXX executable zig0
/usr/bin/ld: /usr/lib/llvm-10/lib/libclangCodeGen.a(BackendUtil.cpp.o): in function `(anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >)':
(.text._ZN12_GLOBAL__N_118EmitAssemblyHelper30EmitAssemblyWithNewPassManagerEN5clang13BackendActionESt10unique_ptrIN4llvm17raw_pwrite_streamESt14default_deleteIS5_EE+0x1f15): undefined reference to `getPollyPluginInfo()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/zig0.dir/build.make:142: zig0] Error 1
make[1]: *** [CMakeFiles/Makefile2:205: CMakeFiles/zig0.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Ubuntu 20.04 (x86_64) with clang-10, lld-10, and llvm-10

FYI

**Comment by daurnimator** [comment] 2020-06-18 23:54
duplicate of https://github.com/ziglang/zig/issues/4799

**Closed by daurnimator** 2020-06-18 23:54 UTC
