### ISSUE TITLE
Zig binding to cURL

### ISSUE THREAD

**Issue by cup** [ziglang/zig#2056] opened 2019-03-13 12:06 UTC
other programming languages have this, for example:

- http://php.net/ref.curl
- https://dlang.org/library/std/net/curl.html
- https://github.com/Lua-cURL/Lua-cURLv3

Until a Zig HTTP client is implemented, I think this would be a better option.
I found a Zig example, but it seems kind of clunky:

~~~
const c = @cImport({
   @cInclude("curl/curl.h");
});
var curl = c.curl_easy_init();
~~~

https://nest.pijul.com/donpdonp/zigdeck:master/1ea61fc3bf48c64b39

compare to PHP:

~~~php
$cf = curl_init('http://nghttp2.org/httpbin/get');
~~~

or D:

~~~d
void main() {
   import std.stdio, std.net.curl;
   writeln(get("http://nghttp2.org/httpbin/get"));
}
~~~

**Comment by cup** [comment] 2019-03-13 12:06
https://github.com/ziglang/zig/issues/2007

**Comment by andrewrk** [comment] 2019-03-13 14:10
Duplicate of #988

**Closed by andrewrk** 2019-03-13 14:10 UTC

**Comment by cup** [comment] 2019-03-13 14:46
@andrewrk is it though?

it seems that the other issue would be: take C code, then convert it into Zig code similar to what i put above

However I am requesting for cURL *binding* - which would allow you to use essentially pure Zig code and idioms, while internally calling a C library

sorry in advance if i am misunderstanding

**Comment by andrewrk** [comment] 2019-03-13 14:49
> However I am requesting for cURL _binding_ - which would allow you to use essentially pure Zig code and idioms, while internally calling a C library

I'm saying "no" to this. The zig standard library will not depend on libcurl.

**Comment by cup** [comment] 2019-03-13 14:51
@andrewrk ok i respect that - will need to be 3rd party library then

thanks for confirming
