### ISSUE TITLE
cImport can not import static const unsigned char array

### ISSUE THREAD

**Issue by WoodyAtHome** [ziglang/zig#6065] opened 2020-08-16 07:19 UTC
zig version = 0.6.0+66d76cc4f

main.zig:
```
const c = @cImport({@cInclude("c.h");});

pub fn main() void {
 const x = c.TA0_DN;
}
```

c.h:
```
static const unsigned char TA0_DN[] = {
	0x30, 0x17, 0x31, 0x15, 0x30, 0x13, 0x06, 0x03, 0x55, 0x04, 0x03, 0x13,
	0x0C, 0x77, 0x77, 0x77, 0x2E, 0x68, 0x65, 0x69, 0x73, 0x65, 0x2E, 0x64,
	0x65
};
```

`zig build-exe -I. main.zig` gives this error:

```
zig-cache/o/cYyZbGCFDZFKb8qE8_xCVjNjOBZskDU0NjUxiLmZuAkohz5C5ZI-5sxm6rMYAQA_/cimport.zig:1:40: error: expected type '[*c]const u8', found '[25]u8'
pub const TA0_DN: [*c]const u8 = [25]u8{
                                       ^
./main.zig:4:13: note: referenced here
 const x = c.TA0_DN;
```

**Comment by Vexu** [comment] 2020-08-16 07:58
Duplicate of #4831.

**Closed by Vexu** 2020-08-16 07:58 UTC
