### ISSUE TITLE
Incorrect slice bounds detection in comptime `@ptrCast`

### ISSUE THREAD

**Issue by tgschultz** [ziglang/zig#1292] opened 2018-07-26 00:05 UTC
```
const std = @import("std");
const builtin = @import("builtin");
const debug = std.debug;

pub fn bytesOf(ptr: var) []u8 {
    const PtrType = @typeOf(ptr);
    const PtrTypeId = @typeId(PtrType);
    debug.assert(PtrTypeId == builtin.TypeId.Pointer);
    
    var aligned = @alignCast(@alignOf(*u8), ptr);
    return @ptrCast([*]u8, aligned)[0..@sizeOf(PtrType.Child)];
}

test "comptime *T to []u8" {
    comptime {
        var x = usize(200);
        var s = bytesOf(&x);
    }
}
```
```
error: out of bounds slice
    return @ptrCast([*]u8, aligned)[0..@sizeOf(PtrType.Child)];
                                   ^
```
Compiler seems to think that only `[0..1]` is valid. Outside of comptime this works fine.

**Comment by andrewrk** [comment] 2018-09-21 16:19
Simplified test case:

```zig
const std = @import("std");
const builtin = @import("builtin");
const assert = std.debug.assert;

comptime {
    var x: u32 = 0x1a2b3c4d;
    var s = @ptrCast([*]u8, &x)[0..@sizeOf(u32)];
    if (builtin.endian == builtin.Endian.Big) {
        assert(s[0] == 0x1a);
        assert(s[1] == 0x2b);
        assert(s[2] == 0x3c);
        assert(s[3] == 0x4d);
    } else {
        assert(s[0] == 0x4d);
        assert(s[1] == 0x3c);
        assert(s[2] == 0x2b);
        assert(s[3] == 0x1a);
    }
}
```

I started working on this, but I think it would be better for post-0.3.0, it's more an issue of "implement more compile-time pointer reinterpreting support" which is a tall order for 1 week before release.

**Comment by SamTebbs33** [comment] 2019-08-28 08:31
Duplicate of #1150

**Closed** 2022-12-19 06:11 UTC
Labels: bug, stage1
