### ISSUE TITLE
Bug in rnd and/or in the compiler

### ISSUE THREAD

**Issue by james-elliot** [ziglang/zig#13973] opened 2022-12-16 09:03 UTC
### Zig Version

0.11.0-dev.815+88b49ed00

### Steps to Reproduce and Observed Behavior

The following code fails with a SIGSEGV at compilation. Same behavior with 0.10.0
```
const std = @import("std");
var rnd = std.rand.DefaultPrng.init(0);
var r = rnd.random().int(u32);

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("{d}\n", .{r});
}
```
> 'zig build-exe -O Debug test2.zig' terminated by signal SIGSEGV (Address boundary error)

### Expected Behavior

No SIGSEGV...

**Comment by Vexu** [comment] 2022-12-16 14:34
Duplicate of #12765

**Closed by Vexu** 2022-12-16 14:34 UTC
Labels: bug
