### ISSUE TITLE
Segfault compiling recursive code

### ISSUE THREAD

**Issue by MFAshby** [ziglang/zig#17880] opened 2023-11-05 20:54 UTC
### Zig Version

0.12.0-dev.1396+f6de3ec96

### Steps to Reproduce and Observed Behavior

Compile and run this program with `zig run main.zig`

https://gist.github.com/MFAshby/e6c7ccb871b91f7b5e0ee8c99172cff7#file-main-zig

Output is this, the compiler gets a segfault:
```
mfa@mfa ~> zig run main.zig
Semantic Analysis [12240] fish: Job 1, 'zig run main.zig' terminated by signal SIGSEGV (Address boundary error)
```

### Expected Behavior

Program to compile and run, or emit an error message if there is invalid code.

**Comment by Vexu** [comment] 2023-11-05 22:22
Duplicate of #13724

**Closed by Vexu** 2023-11-05 22:22 UTC
Labels: bug

**Comment by MFAshby** [comment] 2023-11-07 23:04
In case it's interesting at all, I worked around this issue by changing the recursive function arguments so they are known types rather than requiring recursive comptime evaluation.
```
fn bdecodeInner(a: std.mem.Allocator, base_reader: anytype) !BValue {
```
swapped for 
```
fn bdecodeInner(a: std.mem.Allocator, base_reader: std.io.AnyReader) !BValue {
```
