### ISSUE TITLE
Array length of non-comptime valued arrays not comptime when passed to a function in stage2

### ISSUE THREAD

**Issue by ashpil** [ziglang/zig#12710] opened 2022-09-01 14:11 UTC
### Zig Version

0.10.0-dev.3838+77f31ebbb

### Steps to Reproduce

Compile 

```zig
const std = @import("std");

pub fn main() void {
    stuff(1);
}

pub fn stuff(thing: u8) void {
    const one = [3]u8 {
        0,
        thing, 
        2,
    };

    _ = comptime one.len;
    _ = [one.len]u8;
    _ = typeLooker([one.len]u8);
}

pub fn typeLooker(comptime T: type) void {
    _ = T;
}
```

### Expected Behavior

Compile successfully

### Actual Behavior

```zig
test.zig:16:21: error: cannot load runtime value in comptime block
    _ = typeLooker([one.len]u8);
                    ^~~
```
This is the only error that occurs in this program -- previous lines do not error.

This did not occur in stage 1.

**Comment by Vexu** [comment] 2022-09-01 14:46
Duplicate of #12240

**Closed by Vexu** 2022-09-01 14:46 UTC
Labels: bug

**Comment by ashpil** [comment] 2022-09-01 14:55
Ooops, didn't look that far back for duplicates. Though I think this does contain some additional info that might be useful for debugging.
