### ISSUE TITLE
`@import` is case-sensitive on case-insensitive filesystems, causing modules to instantiate multiple times 

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#19517] opened 2024-04-03 01:34 UTC
### Zig Version

0.12.0-dev.1830+779b8e259

### Steps to Reproduce and Observed Behavior

1. Paste this code in `repro.zig`
```zig
pub const Bar = struct {};
test {
    const Bar2 = @import("repro.zig").Bar;
    const Bar3 = @import("Repro.zig").Bar;
    try @import("std").testing.expectEqual(Bar3, Bar2);
    try @import("std").testing.expectEqual(Bar, Bar2);
}
```
2. Run `zig test repro.zig`
3. Receive output:
```zig
Test [1/2] test_0... expected type Repro.Bar, found type repro.Bar
Test [1/2] test_0... FAIL (TestExpectedEqual)
/Users/jarred/zig/0.12.0-dev.1830+779b8e259/files/lib/std/testing.zig:72:17: 0x100d90783 in expectEqual__anon_913 (test)
                return error.TestExpectedEqual;
                ^
/private/tmp/esm-test/repro.zig:5:5: 0x100d90923 in test_0 (test)
    try @import("std").testing.expectEqual(Bar3, Bar2);
    ^
Test [2/2] test_0... expected type Repro.Bar, found type repro.Bar
Test [2/2] test_0... FAIL (TestExpectedEqual)
/Users/jarred/zig/0.12.0-dev.1830+779b8e259/files/lib/std/testing.zig:72:17: 0x100d90783 in expectEqual__anon_913 (test)
                return error.TestExpectedEqual;
                ^
/private/tmp/esm-test/Repro.zig:5:5: 0x100d99b5f in test_0 (test)
    try @import("std").testing.expectEqual(Bar3, Bar2);
    ^
0 passed; 0 skipped; 2 failed.
error: the following test command failed with exit code 1:
/Users/jarred/.cache/zig/o/671cd7af27c0982718ac963922ef6968/test
```

### Expected Behavior

Test should pass

This issue is similar to https://github.com/ziglang/zig/issues/9786, but not a duplicate because this reproduces on macOS as well as Windows. 

On macOS, the default filesystem is case-insensitive (APFS). HFS+ can be case sensitive but it also defaults to case-insensitive. On Windows, the rules are more complicated.

**Comment by Cloudef** [comment] 2024-04-03 05:06
This sounds like the imports should be normalized so there can't be foo.zig and Foo.zig

**Comment by ifreund** [comment] 2024-04-03 08:45
Duplicate of #9786

**Closed by ifreund** 2024-04-03 08:45 UTC
Labels: bug

**Comment by ifreund** [comment] 2024-04-03 08:49
It's mentioned in #9786 that this reproduces on other systems than windows, e.g. linux filesystems with case-folding enabled. I don't see any reason to have a second issue open.
