### ISSUE TITLE
`attempt to unwrap error` missing the error in ReleaseSafe

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#19531] opened 2024-04-04 12:54 UTC
### Zig Version

0.12.0-dev.1830+779b8e259

### Steps to Reproduce and Observed Output

1. Code:
```zig
const std = @import("std");

pub fn main() !void {
    try doMath(std.math.add, std.math.maxInt(i32), 6);
}

fn doMath(comptime f: fn (type, i32, i32) error{Overflow}!i32, a: i32, b: i32) !void {
    const result = f(i32, a, b) catch unreachable;
    std.debug.print("Result: {}", .{result});
}
```

2. Run:
```zig
zig run -OReleaseSafe repro.zig
```

3. Error:
```
❯ zig run -OReleaseSafe repro.zig
thread 14126458 panic: attempt to unwrap error
fish: Job 1, 'zig run -OReleaseSafe repro.zig' terminated by signal SIGABRT (Abort)
```

### Expected Output

```
thread 14136199 panic: attempt to unwrap error: Overflow
fish: Job 1, 'zig run -OReleaseSafe repro.zig' terminated by signal SIGABRT (Abort)
```

Related:
- https://github.com/oven-sh/bun/issues/9835
- https://github.com/oven-sh/bun/issues/9931

This does not happen in debug builds

**Comment by Vexu** [comment] 2024-04-04 13:52
` -fformatted-panics` is only set by default in debug mode, see also #17969

```zig
// TODO: https://github.com/ziglang/zig/issues/17969
const formatted_panics = options.formatted_panics orelse (options.root_mod.optimize_mode == .Debug);
```

**Comment by andrewrk** [comment] 2024-08-16 06:52
Duplicate of #17969.

**Closed by andrewrk** 2024-08-16 06:52 UTC
Labels: error message
