### ISSUE TITLE
How to return anonymous struct in error union

### ISSUE THREAD

**Issue by marnix** [ziglang/zig#6749] opened 2020-10-20 06:22 UTC
I'd like to be able to return 'error or anonymous struct' from a function, like so:
```zig
const std = @import("std");

fn divmod(fraction: struct { num: usize, den: usize }) !struct { div: usize, mod: usize } {
    if (fraction.den == 0) return error.DivByZero;
    return .{ .div = fraction.num / fraction.den, .mod = fraction.num % fraction.den };
}

const expect = std.testing.expect;

test "" {
    const dm = try divmod(.{ .num = 23, .den = 4 });
    expect(dm.div == 5);
    expect(dm.mod == 3);
}
```

However, at least with 0.6.0 and fairly recent master 0.6.0+cff14dc2c, this results in
```
/anonstructerr.zig:5:15: error: type '@TypeOf(divmod).ReturnType.ErrorSet!struct:3:57' does not support struct initialization syntax
    return .{ .div = fraction.num / fraction.den, .mod = fraction.num % fraction.den };
              ^
./anonstructerr.zig:11:16: note: referenced here
    const dm = try divmod(.{ .num = 23, .den = 4 });
               ^
```

(Removing `!` and `if ...;` and `try` makes the above code run cleanly.)

**Comment by Vexu** [comment] 2020-10-20 10:57
This will work as expected in stage2, until then you're going to have to name your struct (or a bunch of `@typeInfo`s).

**Comment by dbandstra** [comment] 2020-10-20 17:23
Dupe of #3662

**Closed** 2020-10-20 17:24 UTC
Labels: bug, stage1

**Comment by marnix** [comment] 2020-10-20 21:22
I searched for this and failed, apologies for logging a duplicate issue, thanks for the info about how stage2 will make this work!

**Comment by dbandstra** [comment] 2020-10-20 21:40
Np, and the dupe should make it easier for the next person to find :)
