### ISSUE TITLE
Wrong extern name causes compiler hang

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#4796] opened 2020-03-24 16:54 UTC
```zig
const std = @import("std");

///https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamea?redirectedfrom=MSDN
extern "Kernel32" fn GetModuleFileNameA(
    hModule: ?std.os.windows.HANDLE,
    lpFilename: [*]u8,
    nSize: std.os.windows.DWORD,
) callconv(.Stdcall) std.os.windows.DWORD;

pub fn main() !void {
    var path_buffer: [260:0]u8 = undefined;
    if (GetModuleFileNameA(null, &path_buffer, 260) == 0)
        return error.CouldntGetSelfFileName;
}
```
This innocent looking code causes the compiler to wait forever with 0% cpu usage. Replace "Kernel32" with "kernel32" and all works as normal. Ideally we'd get an error.

Running windows, latest master release, compiled with `zig build-exe .\main.zig`

Something more minimal:
```zig
extern "Kernel32" fn hmm();

pub fn main() void {
    hmm();
}
```

**Comment by JesseRMeyer** [comment] 2020-03-24 17:02
Duplicate of https://github.com/ziglang/zig/issues/4308.

**Closed** 2020-03-24 17:10 UTC
