### ISSUE TITLE
translate-c problem with casted constants

### ISSUE THREAD

**Issue by WoodyAtHome** [ziglang/zig#5434] opened 2020-05-25 14:33 UTC
zig version 0.6.0+4b1a84647

test.h:
```
#define VALUE ((unsigned int)0x40000000)
```
main.zig:
```
const c = @cImport(@cInclude("test.h"));

pub fn main() void {
    const x = c.VALUE;
}
```
Compiling with ```zig build-exe main.zig -I. ``` give this error:

```zig-cache/o/uueAvOl4if5p_j40noYZ6i0yJp8T5Lt54Y_1g8DhR5efn2bPtasuay_5LmXz8F6W/cimport.zig:28:19: error: unable to translate C expr: expected ')'' instead got: Keyword_int
pub const VALUE = @compileError("unable to translate C expr: expected ')'' instead got: Keyword_int"); // ./test.h:1:9```

**Comment by Vexu** [comment] 2020-05-25 14:47
Duplicate of #4168.

**Closed by Vexu** 2020-05-25 14:47 UTC
