### ISSUE TITLE
Returning value from block inside comptime block triggers assertion in stage1/ir.cpp, ir_start_bb

### ISSUE THREAD

**Issue by michaelbartnett** [ziglang/zig#7386] opened 2020-12-10 21:46 UTC
This happens inside functions as well, but only a file-scope comptime block is necessary to repro.

```zig
comptime {
    var val = blk: {
        if (false) { // if (true) also asserts
            break :blk false;
        }
        break :blk true;
    };
}
```

```
when analyzing <source>:2:20 in compiler source at /deps/zig/src/stage1/ir.cpp:13377: assertion failed. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
ASM generation compiler returned: 255
when analyzing <source>:2:20 in compiler source at /deps/zig/src/stage1/ir.cpp:13377: assertion failed. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Execution build compiler returned: 255
```

Error log from https://godbolt.org/z/61hTG4

Source context:

```cpp
static void ir_start_bb(IrAnalyze *ira, IrBasicBlockSrc *old_bb, IrBasicBlockSrc *const_predecessor_bb) {
    ir_assert(!old_bb->suspended, (old_bb->instruction_list.length != 0) ? &old_bb->instruction_list.at(0)->base : nullptr);
    ira->instruction_index = 0;
    ira->old_irb.current_basic_block = old_bb;
    ira->const_predecessor_bb = const_predecessor_bb;
    ira->old_bb_index = old_bb->index;
}
```

**Comment by Vexu** [comment] 2021-04-20 17:07
Duplicate of #3376.

**Closed by Vexu** 2021-04-20 17:07 UTC
Labels: bug, stage1
