### ISSUE TITLE
Expression inside an anonymous struct literal causes invalid LLVM module

### ISSUE THREAD

**Issue by di-ant** [ziglang/zig#9908] opened 2021-10-06 19:19 UTC
```zig
test "repr" {

    var a: usize = 4321;
    var b: usize = 1234;

    const func = struct {
        fn func(arg: anytype) void {}
    }.func;

    func(.{ if (a < b) a else b });

}
```
Produces:
```
broken LLVM module found: Instruction does not dominate all uses!
  %6 = getelementptr inbounds %"struct:121:11", %"struct:121:11"* %1, i32 0, i32 0, !dbg !2628
  store i64 %7, i64* %6, align 8, !dbg !2629

This is a bug in the Zig compiler.thread 223064 panic: 
Unable to dump stack trace: debug info stripped
```

**Comment by schmee** [comment] 2021-11-15 11:22
Just ran in to this, the booleans being wrong is still a thing as of `0.9.0-dev.1625+d3a099c14` 👍

**Comment by Vexu** [comment] 2023-01-13 18:04
Duplicate of #3882

**Closed by Vexu** 2023-01-13 18:04 UTC
Labels: bug, stage1, backend-llvm
