### ISSUE TITLE
stage2 compiler crash (printing sizeof packed struct)

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#12791] opened 2022-09-09 07:21 UTC
### Zig Version

0.10.0-dev.3900+ab4b26d8a

### Steps to Reproduce

```zig
// ps.zig
const std = @import("std");
const print = std.debug.print;

const Object = packed struct {
    x: u8 = 0,
    y: u32 = 0,
};

pub fn main() void {
    var o = Object{};
    print("{}\n", .{@sizeOf(@TypeOf(o))});
}
```
Compile with `zig build-exe`

### Expected Behavior

Successful compilation

### Actual Behavior

Compiler crashes:
```
strace /opt/zig/zig build-exe ps.zig
....
getcwd("/home/zed/2-coding/zig-lang/00", 4096) = 36
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff550397000
munmap(0x7ff550397000, 4096)            = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff550397000
munmap(0x7ff550397000, 4096)            = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff550397000
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55038f000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55038e000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55038d000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55038c000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55038b000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55038a000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff550388000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff550387000
munmap(0x7ff550387000, 4096)            = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff550387000
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55037f000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55037e000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55037d000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55037c000
munmap(0x7ff55037c000, 4096)            = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55037c000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff55037b000
--- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL} ---
+++ killed by SIGTRAP (core dumped) +++
```

Note: with usual struct (non-packed) everything is ok.

**Comment by dee0xeed** [comment] 2022-09-09 07:39
It is interesting... following example does not trigger the crash despite the fact epoll_event is packed

```zig
// ee.zig
const std = @import("std");
const print = std.debug.print;
const EpollEvent = std.os.linux.epoll_event;

pub fn main() !void {
    print("sizeof(EpollEvent) = {}\n", .{@sizeOf(EpollEvent)});
}
```

Run

```
$ ./ee 
sizeof(EpollEvent) = 12
```

Everything as expected.

**Comment by dee0xeed** [comment] 2022-09-09 08:15
Minimal example:

```zig
const std = @import("std");
const print = std.debug.print;

const Object = packed struct {
    x: u8 = 0,
};

pub fn main() void {
    print("{}\n", .{@sizeOf(Object)});
}
```

Always crashes regardless of type of `x` field (I tried u32 and usize).

**Comment by Vexu** [comment] 2022-09-09 09:46
Duplicate of #12488

**Closed by Vexu** 2022-09-09 09:46 UTC
Labels: bug

**Comment by dee0xeed** [comment] 2022-09-09 09:58
@Vexu Could you please explain why this is duplicate of #12488? That issue about `@alignOf`, but I did not use this built-in function here, only `@sizeOf`, in 'minimal example'

**Comment by Vexu** [comment] 2022-09-09 10:00
The crash is caused by unresolved lazy values, it doesn't really matter whether those lazy values come from sizeof or alignof.

**Comment by dee0xeed** [comment] 2022-09-09 10:02
@Vexu thanks for clarification
