### ISSUE TITLE
Inconsistent sentinel and non sentinel slice to pointer coercion.

### ISSUE THREAD

**Issue by Araminosian** [ziglang/zig#16182] opened 2023-06-24 14:16 UTC
### Zig Version
0.10.1

### Steps to Reproduce and Observed Behavior
``` zig
// Slice to pointer casting
var pointer: [*]u8 = slice.ptr;

// Sentinel slice to sentinel pointer casting
var sentinel_pointer: [*:0]u8 = sentinel_slice;
```

### Expected Behavior
``` zig
// Variant 1. Slice is a subclass of pointer. Sentinel slice is a subclass of sentinel pointer. 
var pointer: [*]u8 = slice;
var sentinel_pointer: [*:0]u8 = sentinel_slice;

// Variant 2. Considering that explicit is better
var pointer: [*]u8 = slice.ptr;
var sentinel_pointer: [*:0]u8 = sentinel_slice.ptr;
```

**Comment by andrewrk** [comment] 2023-06-24 19:20
1. Please report bugs against master branch only.
2. This is not valid steps to reproduce / expected behavior. I can't run these commands and get the same output as you.

Please respect the bug report template. It's here to help you not get your issues closed by me.

**Closed by andrewrk** 2023-06-24 19:20 UTC
Labels: bug

**Comment by Araminosian** [comment] 2023-06-25 20:47
> 1. Please report bugs against master branch only.
> 
>     2. This is not valid steps to reproduce / expected behavior. I can't run these commands and get the same output as you.
> 
> 
> Please respect the bug report template. It's here to help you not get your issues closed by me.

Sorry.I am not familiar with rules. Variant 1 or Variant 2 work for master branch?

**Comment by trgwii** [comment] 2023-08-28 06:10
I believe this is the bug being reported here, I think sentinel slices should not implicitly coerce to sentinel pointers without .ptr, since normal slices don't (or both should coerce).

Retested on 0.12.0-dev.82+2ceeade99
```zig
const std = @import("std");

var sentinel_slice: [:0]const u8 = "hey";
var sentinel_ptr: [*:0]const u8 = undefined;

test "sentinel" {
    // OK: sentinel slice CAN coerce to many-item sentinel ptr
    sentinel_ptr = sentinel_slice;
}

var slice: []const u8 = "hey";
var ptr: [*]const u8 = undefined;

test "normal" {
    // compile error: slice CAN NOT coerce to many-item ptr

    // 16182.zig:14:11: error: expected type '[*]const u8', found '[]const u8'
    // ptr = slice;
    //       ^~~~~
    ptr = slice;
}
```

`zig test 16182.zig`
