### ISSUE TITLE
std.fmt: Add {q} format specifier

### ISSUE THREAD

**Issue by Tetralux** [ziglang/zig#6756] opened 2020-10-21 08:06 UTC
`q` meaning "quoted", handy for printf-debugging; especially where `\r`s are involved.
Generally useful when writing string manipulation code.
```zig
var s: []const u8 = "hello\x00world\r\n";
std.debug.warn("Content: {q}\n", .{s});
// Content: "hello\x00world\r\n"
```

**Comment by MasterQ32** [comment] 2020-10-21 08:10
Sadly, this is only trivial for ASCII characters. There might be [unicode spaces](http://jkorpela.fi/chars/spaces.html) that should be escaped in such a string, especially stuff like `U+200B` (zero width space). Or we can ignore this and just display the control characters (< 0x20, 0x7F)

**Comment by LemonBoy** [comment] 2020-10-21 08:19
According to #1358 we could use the `?` specifier instead of minting a new one.

> Or we can ignore this and just display the control characters (< 0x20, 0x7F)

:+1:

**Comment by daurnimator** [comment] 2020-10-21 08:37
Practically a dupe of https://github.com/ziglang/zig/pull/6218

**Comment by andrewrk** [comment] 2020-10-26 03:08
> Practically a dupe of #6218

Yes this looks like a dupe of #6218.

**Closed by andrewrk** 2020-10-26 03:08 UTC
Labels: standard library
