### ISSUE TITLE
No error for sub-function cases

### ISSUE THREAD

**Issue by charlesrocket** [ziglang/zig#20003] opened 2024-05-19 15:05 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

```
pub fn main() !void {
    fn foo(bar: usize) void {};
}
```
-> 
```
src/main.zig:8:8: error: function type cannot have a name
    fn foo(bar: usize) void {};
       ^
```

### Expected Output

The error should describe an illegal sub-function declaration instead.

**Comment by Vexu** [comment] 2024-05-19 16:12
Duplicate of #17440

**Closed by Vexu** 2024-05-19 16:12 UTC
Labels: error message
