### ISSUE TITLE
Infinite loop in Semantic Analysis step

### ISSUE THREAD

**Issue by paulsmith** [ziglang/zig#8534] opened 2021-04-14 21:36 UTC
The following code triggers a seemingly infinite Semantic Analysis step that never completes.

``` zig
const std = @import("std");

const Node = union(enum) {
    leaf: u8,
    node: ?*Node,

    pub fn format(self: Node, comptime fmt: []const u8, options: std.fmt.FormatOptions, writer: anytype) @TypeOf(writer).Error!void {
        switch (self) {
            .leaf => {
                try writer.writeAll("leaf=\"");
                try std.fmt.format(writer, "{}", .{self.leaf});
                try writer.writeAll("\"");
            },
            .node => {
                try writer.writeAll("node=[");
                if (self.node) |n| try n.format("{}", std.fmt.FormatOptions{}, writer);
                try writer.writeAll("]");
            },
        }
    }
};

pub fn main() anyerror!void {
    var leaf = Node{ .leaf = 127 };
    var node = Node{ .node = &leaf };
    var root = Node{ .node = &node };
    std.debug.print("{}\n", .{root});
}
```

I expect `node=[node=[leaf="127"]]` to be printed.

![zig-infinite-poc](https://user-images.githubusercontent.com/1210/114782139-34d7f200-9d3f-11eb-91c6-7197cf70f1af.gif)

If you comment out either the call to `std.fmt.format` in the `.leaf` arm or the recursive call to `Node.format` in the `.node` arm, the code compiles.

**Comment by Vexu** [comment] 2021-04-15 05:24
Duplicate of #4572.

**Closed by Vexu** 2021-04-15 05:24 UTC
