### ISSUE TITLE
Proposal: target/optimization-specific dependencies

### ISSUE THREAD

**Issue by alichraghi** [ziglang/zig#17914] opened 2023-11-07 17:29 UTC
Mach depends on Dawn/WebGPU, and although the final linked binaries are much smaller the static library of Dawn can be 30-60MB per platform, making downloading the prebuilt binary for every platform prohibitive, and as a result we can't use the package manager to fetch these binaries today. If there were target/optimization-specific dependencies that would only be fetched when building for that target, it would fix this for us:
```zig 
.{
    .name = "example",
    .version = "0.1.0",
    .dependencies = .{
        .dawn = .{
            .{
                .target = "x86_64-linux",
                .optimize = .Debug,
                .url = "https://github.com/hexops/mach-gpu-dawn/releases/download/release-6273d7f/x86_64-linux-gnu_release-fast.tar.gz",
                .hash = ...,
            },
            .{
                .target = "x86_64-windows",
                .optimize = .Debug,
                .url = "https://github.com/hexops/mach-gpu-dawn/releases/download/release-6273d7f/x86_64-windows-gnu_debug.tar.gz",
                .hash = ...,
            },
            .{
                .target = "aarch64-macos",
                .optimize = .Debug,
                .url = "https://github.com/hexops/mach-gpu-dawn/releases/download/release-6273d7f/aarch64-macos-none_debug.tar.gz",
                .hash = ...,
            },
            .{
                .target = "x86_64-linux",
                .optimize = .ReleaseFast,
                .url = "https://github.com/hexops/mach-gpu-dawn/releases/download/release-6273d7f/x86_64-linux-gnu_debug.tar.gz",
                .hash = ...,
            },
            .{
                .target = "x86_64-windows",
                .optimize = .ReleaseFast,
                .url = "https://github.com/hexops/mach-gpu-dawn/releases/download/release-6273d7f/x86_64-windows-gnu_release-fast.tar.gz",
                .hash = ...,
            },
            .{
                .target = "aarch64-macos",
                .optimize = .ReleaseFast,
                .url = "https://github.com/hexops/mach-gpu-dawn/releases/download/release-6273d7f/aarch64-macos-none_release-fast.tar.gz",
                .hash = ...,
            },
            
            ...

        },
    },
}
```

**Comment by xdBronch** [comment] 2023-11-07 17:35
related/duplicate of #14597

**Closed** 2023-11-07 17:40 UTC
