### ISSUE TITLE
Unexpected compiler error when switching on `enum literal`

### ISSUE THREAD

**Issue by fyrchik** [ziglang/zig#7303] opened 2020-12-04 15:37 UTC
Hello!
While trying to write JSON parser as a first zig project, I have encountered some strange behaviour when switching on enums. I saw related issues #3750, #5769, but here I also have invalid code generation, so I created a new issue.
Platform: Linux 5.0.0-32-generic x86_64 GNU/Linux
Compiler version: found on `0.7.0`, reproduced on current master (`0.7.0+58241364c`).

This code fails to compile with an error:
```zig
const std = @import("std");

const SomeEnum = enum {
  State1,
  State2,
};

fn advance(s: SomeEnum, c: u8) SomeEnum {
  return switch (s) {
    .State1 => switch (c) {
      '0'...'9' => .State1,
      ',' => .State2,
      else => .State2,
    },
    .State2 => .State1,
  };
}
```
```
./src/kek.zig:10:16: error: values of type '(enum literal)' must be comptime known
    .State1 => switch (c) {
```

However, if I change the `else` branch from `.State2` to `return .State2`, everything is ok.
But then if I change `'0'...'9'` to `'0','1',...` (enumerate by hand), it fails to compile again!
But then if I change `','` to `','...','`it again compiles successfully.
And if I use both `','...','` and `'0'...'9'` it fails to compile.

The second issue is related to code generation.
In the example with the first change (`.State2` to `return .State2`) this test fails (though the branch in switch is visited, this can be seen if debug print is added):
```zig
test "next state" {
  std.testing.expect(advance(.State1, ',') == SomeEnum.State2);
}
```

I am eager to look at the compiler internals, so if you point me to where to start my search, I can try to fix it myself.

**Comment by Vexu** [comment] 2020-12-04 15:51
Duplicate of #4255, etc.

This is already fixed in the self-hosted compiler, in the meanwhile there are multiple workarounds:

```zig
  return switch (s) {
    .State1 => switch (c) {
      '0'...'9' => SomeEnum.State1,
      ',' => .State2,
      else => .State2,
    },
    .State2 => .State1,
  };
```

```zig
  return switch (s) {
    .State1 => return switch (c) {
      '0'...'9' => .State1,
      ',' => .State2,
      else => .State2,
    },
    .State2 => .State1,
  };
```

```zig
  return switch (s) {
    .State1 => @as(SomeEnum, switch (c) {
      '0'...'9' => .State1,
      ',' => .State2,
      else => .State2,
    }),
    .State2 => .State1,
  };
```

**Closed by Vexu** 2020-12-04 15:51 UTC
