### ISSUE TITLE
Compiler hangs on function declared as returning `!noreturn`

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#4698] opened 2020-03-09 09:22 UTC
```zig
fn fail() !noreturn {
    return error.Dang;
}

pub fn main() void {
    fail() catch {};
}
```
The compiler seems to hang indefinitely.

**Comment by LemonBoy** [comment] 2020-03-09 09:44
Duplicate of #3461, the `!noreturn` combo should be disallowed.

**Closed** 2020-03-09 10:32 UTC
Labels: duplicate
