### ISSUE TITLE
Trying to iterate over TypeInfo.Struct.fields without inline for causes SIGSEGV

### ISSUE THREAD

**Issue by eduardosm** [ziglang/zig#1229] opened 2018-07-13 17:30 UTC
```
pub const S = struct {
    x: i32,
    y: i32,
};

test "test" {
    for (@typeInfo(S).Struct.fields) |field, i| {}
}
```

**Comment by andrewrk** [comment] 2018-07-14 04:00
This might be a dupe of #740

**Comment by dbandstra** [comment] 2018-08-29 04:55
I'm not sure which commit fixed it, but this doesn't segfault for me. I get a proper compile error. Unfortunately the error message is not very helpful so maybe it could be improved.

```
/home/dbandstra/oxid/test.zig:7:39: error: variable of type 'StructField' must be const or comptime
    for (@typeInfo(S).Struct.fields) |field, i| {}
                                      ^
```

**Comment by tiehuis** [comment] 2018-08-29 04:56
Maybe a hint suggesting the loop be `inline` would also be helpful here.

**Comment by tiehuis** [comment] 2018-08-29 04:59
Fixed by https://github.com/ziglang/zig/commit/09cc1dc66067f378a1508e34c0714b659b445724.

**Closed by tiehuis** 2018-08-29 04:59 UTC
Labels: bug
