### ISSUE TITLE
Compiler segfault on program containing self-referential struct

### ISSUE THREAD

**Issue by fishsayhelo** [ziglang/zig#22048] opened 2024-11-22 19:32 UTC
### Zig Version

0.14.0-dev.2253+3a6a8b8aa

### Steps to Reproduce and Observed Behavior

Compiling the following "program" with `zig build-exe main.zig`, or by using a build.zig, while the boolean w/ name "strangebool" is *uncommented*, results in compiler segfault. Proceeding to comment/remove the field results in the expected error message (`struct 'main.BadStruct' depends on itself`).

```zig
const s = @import("std");

pub fn main () !void
{
    const a: BadStruct = undefined;
    _ = a;
}

pub const BadStruct = struct {
    const badfield: type = badfn(@This());
    strangebool: bool, // offending field
    _: badfield,
};

pub fn badfn (comptime strct: type) type
{ 
    const fields = comptime @typeInfo(strct).Struct.fields;
    return @TypeOf(fields[fields.len]);
}
```
(same program attached)
[main.zig.txt](https://github.com/user-attachments/files/17875283/main.zig.txt)

(video of error occuring, for completeness)
https://github.com/user-attachments/assets/7662edce-a710-4722-9aad-f092cbd1df34

### Expected Behavior

expected to observe following error message (as is present for commented/removed case):
```
main.zig:9:23: error: struct 'main.BadStruct' depends on itself
pub const BadStruct = struct {
                      ^~~~~~
referenced by:
    BadStruct: main.zig:9:23
    main: main.zig:5:14
```

**Comment by Vexu** [comment] 2024-11-22 22:29
Duplicate of #21436

**Closed by Vexu** 2024-11-22 22:29 UTC
Labels: bug
