### ISSUE TITLE
make `zig cc` use clang-compatible -target and -mcpu parameters

### ISSUE THREAD

**Issue by Vurich** [ziglang/zig#7360] opened 2020-12-09 11:25 UTC
If you run clang with `--target=arm64-unknown-linux-gnu` it will understand it to mean the same as `arm64-linux-gnu`, but with `zig cc` it returns `UnknownOperatingSystem`. I wanted to use `zig cc` in a Rust build script, and this is an issue as Rust _only_ uses 4-part target triples - and so `<arch>-unknown-<sys>-<abi>` is by far the most common format for targets. While I can work around this in my particular case, I wouldn't expect it to be particularly difficult to implement in Zig and it would make `zig cc` compatible with clang in more contexts.

**Comment by LemonBoy** [comment] 2020-12-14 15:28
I've hit this very same problem today and indeed having to patch the triple every time is annoying.
This said, Zig has no concept of vendors yet so we could:
* Parse and ignore the field,
* Parse the field and relay it to LLVM, Zig is still oblivious to the vendor part,
* Same as above, but only when running `zig cc`,
* Enhance Zig's triple to include the vendor part too.

**Comment by andrewrk** [comment] 2021-11-16 00:49
Currently the `-target` and `-mcpu` CLI parameters are parsed according to zig's understanding of these values rather than LLVM's, including in `zig cc` mode. This is intentional because Zig has a different set of targets than LLVM does, and we do want you to be able to specify operating systems, architectures, and CPU features according to zig's model rather than LLVM's model.

Of course it does have the downside noted by this issue.

It's annoying but I think the best solution to the problem is to parse the triple according to LLVM rules, *only in zig cc* (as @LemonBoy notes in the 3rd option), which involves a more onerous process than simply omitting the vendor, because the CPU model names and CPU features have different syntax (underscore instead of dash, for instance, but also the sets of features are not the same).

**Comment by Vurich** [comment] 2021-11-16 12:24
Maybe if there was some standard way to convert between LLVM and Zig triples (and `-mcpu` arguments) that existed outside of Zig then it wouldn't be so bad? You could then have a really thin script called, like `zig clang` or whatever that does the conversion and passes it to `zig cc`. Seems kinda silly to convert twice but it could lead to more flexibility in `zig cc`'s argument syntax if you have an entirely separate binary whose only purpose is converting the arguments.

**Comment by andrewrk** [comment] 2021-11-23 05:57
Duplicate of #4911

**Closed by andrewrk** 2021-11-23 05:57 UTC
Labels: proposal, stage2, zig cc
