### ISSUE TITLE
Result type lost when nesting multiple expressions

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#7324] opened 2020-12-07 08:34 UTC
This was found by @devzero.  I'm not sure if this is a bug report or a proposal, but it seems pretty clear to me that this should compile:
```zig
const Enum = enum { a, b };

pub fn main() !void {
    var x: usize = 4;
    var y = false;
    var e: Enum = switch(x) {
        else => blk: {
            if (y) {
                break :blk .a;
            }
            break :blk .b;
        }
    };
}
```

Instead it reports this error:
```
.\src\day08.zig:7:22: error: values of type '(enum literal)' must be comptime known
        else => blk: {
                     ^
C:\Program Files\Zig\Current\lib\zig\std\start.zig:334:40: note: referenced here
            const result = root.main() catch |err| {
                                       ^
```

---

It seems like the problem is that the named block in the switch is not inferring the result type from the switch expression.  So when the compiler tries to compile the break statements, it does peer type resolution instead of result type inference and comes up with EnumLiteral.  Since EnumLiterals can't be runtime values, compilation fails.

The specific behavior I think should work is:
- result types should be inferred through `if`, `else`, and `switch` expressions into their sub-expressions.
- result types should be inferred through `while`, `for`, and block expressions into their associated `break` statements.

**Comment by dbandstra** [comment] 2020-12-07 08:48
I think this is https://github.com/ziglang/zig/issues/5557

**Comment by Vexu** [comment] 2020-12-07 10:19
Duplicate of #5557, #3750, #4255 and. #4629, already fixed in stage2.

**Closed by Vexu** 2020-12-07 10:19 UTC
