### ISSUE TITLE
Proposal: procedural comptime type manipulation

### ISSUE THREAD

**Issue by lucascharlesmyers** [ziglang/zig#2890] opened 2019-07-13 20:24 UTC
I'm rather new to Zig, so apologies if this is something that's already in the works or has already been discussed before.

I was surprised and happy to see the `@field()` builtin function, but it seems like only the start of what could be a much larger set of features. In particular:
- The ability to enumerate, inspect, and look up _all_ public members of a `type`, not just fields.
- The ability to add and remove members, fields, enum cases, etc. from types. Since `type`s are immutable, this would probably take the form of builtins that produce new anonymous types from existing ones.

There are a number of use cases I can think of:
- Automatically parsing and generating type definitions for schemas for external markup languages at `comptime`.
- Postprocessing the `struct` from an `@cImport` and generating a new "glue" interface. For instance, a `comptime` OpenGL extension loader generator that learns about available procedures by browsing the Zig definitions generated from the headers.
- Any embedded DSL where you need to generate types with computed member names.

**Comment by hryx** [comment] 2019-07-13 20:33
Related: https://github.com/ziglang/zig/issues/383

**Comment by komuw** [comment] 2019-07-16 20:28
probably also related; https://github.com/ziglang/zig/issues/2907

**Comment by andrewrk** [comment] 2020-02-10 22:41
I believe this is a duplicate of #383.

**Closed by andrewrk** 2020-02-10 22:41 UTC
Labels: proposal
