### ISSUE TITLE
Compilation error: broken LLVM module found: Expected no forward declarations!

### ISSUE THREAD

**Issue by Sh4pe** [ziglang/zig#10963] opened 2022-02-21 21:03 UTC
### Zig Version

0.10.0-dev.874+a4df443f9

### Steps to Reproduce

To reproduce the problem, you need `build.zig` and `main.zig` from [this gist](https://gist.github.com/Sh4pe/23e3fdd96df79f3ae817a9b0b6d3a3e4). `zig build` fails with this error message:

```
Code Generation [803/824] std.mem.bytesAsSlice... broken LLVM module found: Expected no forward declarations!
!29645 = <temporary!> !DICompositeType(tag: DW_TAG_structure_type, name: "ResolvableEntity", scope: !17697, file: !17697, line: 63, flags: DIFlagFwdDecl)

This is a bug in the Zig compiler.thread 223664 panic:
Unable to dump stack trace: debug info stripped
schema2data...The following command terminated unexpectedly:
/nix/store/l33rmlw4wzq87gnr0cqngqy0nsbnwwz0-zig-nightly/bin/zig build-exe /home/sh4pe/devel/zig/schema2data/zig_compile_debug/src/main.zig --cache-dir /home/sh4pe/devel/zig/schema2data/zig_compile_debug/zig-cache --global-cache-dir /home/sh4pe/.cache/zig --name schema2data --enable-cache
error: the following build command failed with exit code 6:
/home/sh4pe/devel/zig/schema2data/zig_compile_debug/zig-cache/o/b7b92b37cada5c4bfc775ee4c8159f23/build /nix/store/l33rmlw4wzq87gnr0cqngqy0nsbnwwz0-zig-nightly/bin/zig /home/sh4pe/devel/zig/schema2data/zig_compile_debug /home/sh4pe/devel/zig/schema2data/zig_compile_debug/zig-cache /home/sh4pe/.cache/zig
```

This has been observed both on zig `0.9.1` and `0.10.0-dev.874+a4df443f9`. Compilation works if you comment out lines [63-65](https://gist.github.com/Sh4pe/23e3fdd96df79f3ae817a9b0b6d3a3e4#file-main-zig-L63-L65) and comment in lines [66-68](https://gist.github.com/Sh4pe/23e3fdd96df79f3ae817a9b0b6d3a3e4#file-main-zig-L66-L68). In my actual project, this is a workaround, but I'd rather not have compilation fail :)

### Expected Behavior

I'd expect to have the compiler compile the program or reject it.

### Actual Behavior

Compiler crashes.

**Comment by ominitay** [comment] 2022-02-28 14:54
Possible duplicate of #5197?

**Comment by Sh4pe** [comment] 2022-08-15 11:31
Checked it today with Zig version `0.10.0-dev.3559+d2342370f`. Still fails in the same way.

**Comment by nektro** [comment] 2022-08-15 15:37
please include the code in the issue instead of linking to gist

**Comment by Vexu** [comment] 2024-03-28 10:50
Not reproducible with `std.json` changes, assuming fixed in master.

**Closed by Vexu** 2024-03-28 10:50 UTC
Labels: bug, stage1
