### ISSUE TITLE
support VLAs at end of structs link in extern

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1433] opened 2018-08-27 23:40 UTC
```
pub const dirent64 = extern struct {
    d_ino: u64,
    d_off: u64,
    d_reclen: u16,
    d_type: u8,
    d_name: u8, // field address is the address of first byte of name
};
```
not sure what syntax to use.

**Comment by andrewrk** [comment] 2018-08-28 01:04
duplicate of #173

**Closed by andrewrk** 2018-08-28 01:04 UTC
