### ISSUE TITLE
missing header file when exporting zig function to be used by c code

### ISSUE THREAD

**Issue by edyu** [ziglang/zig#15575] opened 2023-05-04 16:25 UTC
### Zig Version

0.10.1 and 0.11.0-dev.2969+855493bb8

### Steps to Reproduce and Observed Behavior

Testing out [ziglang.org/learn](https://ziglang.org/learn/overview/) build test on **mathtest.zig** and receiving errors both on 0.10.1 and the master dev 0.11.0-dev on 2 different machines. I'm getting `LLVM Emit Object... error(compilation): clang failed with stderr: /home/ed/ws/zig/test.c:1:10: fatal error: 'mathtest.h' file not found`

### Expected Behavior

I'm assuming that **mathtest.zig** would automatically provide the .h file requirement using zig build because zig itself doesn't require .h file.

**Comment by edyu** [comment] 2023-05-04 16:47
zig build-exe test Debug native: error: error(compilation): clang failed with stderr: /home/ed/ws/zig/test.c:1:10: fatal error: 'mathtest.h' file not found

<pre>
zig build-exe test Debug native: error: the following command failed with 1 compilation errors:
/snap/zig/7310/zig build-exe -cflags -std=c99 -- /home/ed/ws/zig/test.c /home/ed/ws/zig/zig-cache/o/58ad99e8221a63ce5089d1a1c330b3a8/libmathtest.so.1.0.0 -rpath /home/ed/ws/zig/zig-cache/o/58ad99e8221a63ce5089d1a1c330b3a8 -lc --cache-dir /home/ed/ws/zig/zig-cache --global-cache-dir /home/ed/.cache/zig --name test --listen=-
Build Summary: 1/4 steps succeeded; 1 failed (disable with -fno-summary)
test transitive failure
└─ run test transitive failure
   └─ zig build-exe test Debug native 1 errors
      └─ zig build-lib mathtest Debug native success 2s MaxRSS:166M
/home/ed/ws/zig/test.c:1:1: error: unable to build C object: clang exited with code 1
</pre>

**Comment by edyu** [comment] 2023-05-04 17:14
#6753

**Comment by edyu** [comment] 2023-05-04 17:42
Still doesn't work unfortunately. I've been using the master. It's the missing header file that's causing problems.

**Comment by edyu** [comment] 2023-05-04 17:44
In fact even the master documentation needs to add 
<pre>
const target = b.standardTargetOptions(.{});
const optimize = b.standardOptimizeOption(.{});

const lib = b.addSharedLibrary(.{
     .name = "mathtest",
    .root_source_file = .{ .path = "mathtest.zig" },
    .version = .{ .major = 1, .minor = 0, .patch = 0 },
   .target = target,
   .optimize = optimize,
});
</pre>

**Comment by edyu** [comment] 2023-05-04 17:45
Also the line:
`const run_cmd = exe.run();`
needs to be changed to 
`const run_cmd = b.addRunArtifact(exe);`

**Comment by edyu** [comment] 2023-05-04 17:46
But even with these changes, still can't get header file to be auto-generated and used by build.

**Comment by kassane** [comment] 2023-05-04 17:48
See:
https://ziglang.org/documentation/master/std/#A;std:Build.CompileStep

Missing `lib.emit_h=true;`

**Comment by edyu** [comment] 2023-05-04 18:06
> See: https://ziglang.org/documentation/master/std/#A;std:Build.CompileStep
> 
> Missing `lib.emit_h=true;`

<pre>
zig build-exe test Debug native: error: error(compilation): clang failed with stderr: In file included from /home/ed/ws/zig/test.c:1:
/home/ed/ws/zig/mathtest.h:1:10: fatal error: 'zig.h' file not found


zig build-exe test Debug native: error: the following command failed with 1 compilation errors:
/snap/zig/7310/zig build-exe -cflags -std=c99 -- /home/ed/ws/zig/test.c /home/ed/ws/zig/zig-cache/o/780c64770eaaa67f6c1b6f3cd906c2dd/libmathtest.so.1.0.0 -rpath /home/ed/ws/zig/zig-cache/o/780c64770eaaa67f6c1b6f3cd906c2dd -lc --cache-dir /home/ed/ws/zig/zig-cache --global-cache-dir /home/ed/.cache/zig --name test -isystem /home/ed/ws/zig/zig-cache/o/780c64770eaaa67f6c1b6f3cd906c2dd --listen=-
Build Summary: 1/4 steps succeeded; 1 failed (disable with -fno-summary)
test transitive failure
└─ run test transitive failure
   └─ zig build-exe test Debug native 1 errors
      └─ zig build-lib mathtest Debug native success 683ms MaxRSS:129M
/home/ed/ws/zig/test.c:1:1: error: unable to build C object: clang exited with code 1
</pre>

**Comment by kassane** [comment] 2023-05-04 18:06
> But even with these changes, still can't get header file to be auto-generated and used by build.

After generating the header. Add on executable: `exe.addIncludePath("includePath");`

**Comment by edyu** [comment] 2023-05-04 18:17
Well, now I'm using `/snap/zig/current/lib` as the include path and although it found zig.h, it's now complaining the following:
<pre>
zig build-exe test Debug native: error: error(compilation): clang failed with stderr: In file included from /home/ed/ws/zig/test.c:1:
In file included from /home/ed/ws/zig/mathtest.h:1:
/snap/zig/current/lib/zig.h:1709:26: error: use of undeclared identifier 'ZIG_TARGET_MAX_INT_ALIGNMENT'


zig build-exe test Debug native: error: the following command failed with 1 compilation errors:
/snap/zig/7310/zig build-exe -cflags -std=c99 -- /home/ed/ws/zig/test.c /home/ed/ws/zig/zig-cache/o/780c64770eaaa67f6c1b6f3cd906c2dd/libmathtest.so.1.0.0 -rpath /home/ed/ws/zig/zig-cache/o/780c64770eaaa67f6c1b6f3cd906c2dd -lc --cache-dir /home/ed/ws/zig/zig-cache --global-cache-dir /home/ed/.cache/zig --name test -I /snap/zig/current/lib -isystem /home/ed/ws/zig/zig-cache/o/780c64770eaaa67f6c1b6f3cd906c2dd --listen=-
</pre>

**Comment by kassane** [comment] 2023-05-04 18:20
> Well, now I'm using `/snap/zig/current/lib` as the include path and although it found zig.h, it's now complaining the following:
> 
> zig build-exe test Debug native: error: error(compilation): clang failed with stderr: In file included from /home/ed/ws/zig/test.c:1:
> In file included from /home/ed/ws/zig/mathtest.h:1:
> /snap/zig/current/lib/zig.h:1709:26: error: use of undeclared identifier 'ZIG_TARGET_MAX_INT_ALIGNMENT'
> 
> 
> zig build-exe test Debug native: error: the following command failed with 1 compilation errors:
> /snap/zig/7310/zig build-exe -cflags -std=c99 -- /home/ed/ws/zig/test.c /home/ed/ws/zig/zig-cache/o/780c64770eaaa67f6c1b6f3cd906c2dd/libmathtest.so.1.0.0 -rpath /home/ed/ws/zig/zig-cache/o/780c64770eaaa67f6c1b6f3cd906c2dd -lc --cache-dir /home/ed/ws/zig/zig-cache --global-cache-dir /home/ed/.cache/zig --name test -I /snap/zig/current/lib -isystem /home/ed/ws/zig/zig-cache/o/780c64770eaaa67f6c1b6f3cd906c2dd --listen=-

Ref: https://github.com/ziglang/zig/pull/14576

**Comment by andrewrk** [comment] 2023-07-23 03:49
duplicate of #9698

**Closed by andrewrk** 2023-07-23 03:49 UTC
Labels: bug
