### ISSUE TITLE
'zig fmt' not seeing its 'on' comment

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#13254] opened 2022-10-21 22:09 UTC
### Zig Version

0.10.0-dev.4476+0f0076666

### Steps to Reproduce

```zig
test {
    const a = [_]u8{
        // zig fmt: off
        1,2,3,4,5,6,7,8,9
        // zig fmt: on
    };




    _=a;
}
```

### Expected Behavior

```zig
test {
    const a = [_]u8{
        // zig fmt: off
        1,2,3,4,5,6,7,8,9
        // zig fmt: on
    };

    _ = a;
}
```

### Actual Behavior

file is unchanged

**Comment by r00ster91** [comment] 2022-10-22 10:22
Duplicate of #10418

**Closed** 2022-10-22 11:21 UTC
Labels: bug
