### ISSUE TITLE
`// zig fmt: on` doesn't work when inside an array

### ISSUE THREAD

**Issue by scheibo** [ziglang/zig#11225] opened 2022-03-19 03:54 UTC
### Zig Version

0.10.0-dev.3272+5fbae9cd6

### Steps to Reproduce

Run `zig fmt` on the following file

```zig
pub const A = [_]u8{
    // zig fmt: off
   1, 2, 3,
    4, 5,
   // zig fmt: on 
};

pub const B = struct {
 pub const c = 0;
};
```

### Expected Behavior

```zig
pub const A = [_]u8{
    // zig fmt: off
   1, 2, 3,
    4, 5,
   // zig fmt: on 
};

pub const B = struct {
    pub const c = 0;
};
```

`B.c` should be indented after running `zig fmt`, but it seems like the `// zig fmt: on` is not recognized and the code things that `// zig fmt: off` still applies.

### Actual Behavior

Nothing.

---

It seems to specifically be the case that `// zig fmt: on` within the trailing brace is the issue, if you pull the `// zig fmt: on` outside of the array and then run `zig fmt` on this file it should work as expected:

```zig
pub const A = [_]u8{
    // zig fmt: off
   1, 2, 3,
    4, 5,
};
    // zig fmt: on

pub const B = struct {
 pub const c = 0;
};
```

**Comment by schmee** [comment] 2022-03-19 08:24
Duplicate of https://github.com/ziglang/zig/issues/10418.

**Closed** 2022-03-19 08:42 UTC
Labels: bug, contributor friendly, zig fmt
