### ISSUE TITLE
Bad `try` inside function that doesn't return error union not caught for function with `!T` return type

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#11795] opened 2022-06-05 16:01 UTC
### Zig Version

0.10.0-dev.2398+b08d32ceb

### Steps to Reproduce

```zig
pub fn main() void {
    _ = try getNothing();
}

fn getNothing() !void {}
```

### Expected Behavior

```
./x.zig:2:9: error: expected type 'void', found 'anyerror'
    _ = try getNothing();
        ^
./x.zig:1:15: note: function cannot return an error
pub fn main() void {
              ^
```

### Actual Behavior

It compiles and does nothing. The error only shows up when changing `!void` to `anyerror!void` (or similar). Looks like a little oversight.

This happens in stage1 and stage2.

**Comment by Vexu** [comment] 2022-06-05 16:35
Duplicate of #7541

**Closed by Vexu** 2022-06-05 16:35 UTC
Labels: bug
