### ISSUE TITLE
stage3 crash when using enum nested in (otherwise unused) packed struct

### ISSUE THREAD

**Issue by bfredl** [ziglang/zig#13284] opened 2022-10-24 13:49 UTC
### Zig Version

0.10.0-dev.4561+4f04759c8

### Steps to Reproduce

```
pub const Insn = packed struct {
    code: u8,
    pub const Reg = enum(u4) { r0, r1 };
};

pub fn main() void {
    const reg: Insn.Reg = .r1;
    _ = reg;
}
```

and compile normally with stage3 zig: `zig build-exe -O Debug test.zig`

### Expected Behavior

This attempts to generate debug info for `Insn` which depends on the layout of `Insn` itself, but it is missing (as only `Insn.Reg` is used/analyzed, not `Insn` itself), thus ` struct_obj.backing_int_ty` is not available yet, and `Type.intInfo` panics.

### Actual Behavior

```
#6  0x0000000009663774 in builtin.default_panic () at /home/bfredl/dev/zig/lib/std/builtin.zig:839
#7  0x0000000009a90de8 in type.Type.intInfo () at type.zig:4671
#8  0x000000000974324b in codegen.llvm.Object.lowerDebugTypeImpl () at codegen/llvm.zig:1920
#9  0x0000000009a21cff in codegen.llvm.Object.lowerDebugType () at codegen/llvm.zig:1442
#10 0x0000000009a8d9a7 in codegen.llvm.Object.namespaceToDebugScope () at codegen/llvm.zig:2336
#11 0x000000000973eb5b in codegen.llvm.Object.lowerDebugTypeImpl () at codegen/llvm.zig:1511
#12 0x0000000009a21cff in codegen.llvm.Object.lowerDebugType () at codegen/llvm.zig:1442
#13 0x000000000a0f06b5 in codegen.llvm.FuncGen.airDbgVarVal () at codegen/llvm.zig:5950
#14 0x0000000009df74d9 in codegen.llvm.FuncGen.genBody () at codegen/llvm.zig:4641
#15 0x0000000009def8ea in codegen.llvm.Object.updateFunc () at codegen/llvm.zig:1223
#16 0x0000000009df7be3 in link.Elf.updateFunc () at link/Elf.zig:2411
#17 0x0000000009c0d61e in link.File.updateFunc () at link.zig:558
#18 0x00000000099f2111 in Module.ensureFuncBodyAnalyzed () at Module.zig:4375
#19 0x00000000099efe3e in Compilation.processOneJob () at Compilation.zig:3060
#20 0x00000000098d2a5b in Compilation.performAllTheWork () at Compilation.zig:2998
#21 0x00000000098cf256 in Compilation.update () at Compilation.zig:2326
#22 0x00000000098fbe87 in main.updateModule () at main.zig:3323
#23 0x0000000009688017 in main.buildOutputType () at main.zig:3008
#24 0x0000000009665d67 in main.mainArgs () at main.zig:230
#25 0x000000000996c4f8 in main () at stage1.zig:56
```

**Comment by Vexu** [comment] 2022-10-24 13:57
Duplicate of #13159

**Closed by Vexu** 2022-10-24 13:57 UTC
Labels: bug
