### ISSUE TITLE
Segmentation fault when breaking to outer loop label from inline for

### ISSUE THREAD

**Issue by A1Liu** [ziglang/zig#11781] opened 2022-06-03 01:46 UTC
### Zig Version

0.10.0-dev.2211+f32928c50

### Steps to Reproduce
Run `zig test` with

```zig
const std = @import("std");
const Tag = enum(u32) { head, maxp, _ };

test {
    table_loop: {
        inline for (std.meta.fields(Tag)) |field| {
            if (std.mem.eql(u8, "maxp", field.name)) {
                std.debug.print("found\n", .{});
                break :table_loop;
            }
        }
    }
}
```

### Expected Behavior

```
found
```

### Actual Behavior

```
zsh: segmentation fault  zig test simple.zig
```

**Comment by A1Liu** [comment] 2022-06-03 01:59
This works:

```zig
const std = @import("std");
const Tag = enum(u32) { head, maxp, _ };

test {
    inline for (std.meta.fields(Tag)) |field| {
        if (std.mem.eql(u8, "maxp", field.name)) {
            std.debug.print("found\n", .{});
        }
    }
}
```

as does this:

```zig
const std = @import("std");
const Tag = enum(u32) { head, maxp, _ };

test {
    table_loop: {
        inline for (std.meta.fields(Tag)) |field| {
            if (field.name.len < 10) {
                std.debug.print("found {s}\n", .{field.name});
                break :table_loop;
            }
        }
    }
}
```

**Comment by Vexu** [comment] 2022-06-03 09:58
Duplicate of #7364 (and probably others).

**Closed by Vexu** 2022-06-03 09:58 UTC
Labels: bug
