### ISSUE TITLE
broken LLVM module found: Instruction does not dominate all uses!

### ISSUE THREAD

**Issue by Cobertos** [ziglang/zig#7471] opened 2020-12-17 07:44 UTC
Still not quite sure how to concatenate stuff properly when different lengths, but I stumbled upon this while messing around.

EDIT: Retested in latest, `zig-windows-x86_64-0.7.1+6dfe9cc83`

```zig
const std = @import("std");
const print = @import("std").debug.print;

const a = std.heap.page_allocator;

pub fn main() !void {
  print("{}\n", .{
    if (std.time.milliTimestamp() > 100000) std.cstr.addNullByte(a, "+") else std.cstr.addNullByte(a, "-")
  });
}
```

... emits ...

```bash
$ /c/Users/cobertos/Downloads/zig-windows-x86_64-0.7.1+6dfe9cc83/zig.exe run main2.zig
Code Generation [290/513] std.fs.path.basenameWindows... broken LLVM module found: Instruction does not dominate all uses!
  %4 = getelementptr inbounds %"struct:7:18", %"struct:7:18"* %1, i32 0, i32 0, !dbg !5685
  call fastcc void @std.cstr.addNullByte({ %"[]u8.18", i16 }* sret %4, %std.builtin.StackTrace.19* %0, %std.mem.Allocator* @page_allocator_state, %"[]u8.18"* @201), !dbg !5686
Instruction does not dominate all uses!
  %4 = getelementptr inbounds %"struct:7:18", %"struct:7:18"* %1, i32 0, i32 0, !dbg !5685
  %7 = bitcast { %"[]u8.18", i16 }* %4 to i8*, !dbg !5686
Instruction does not dominate all uses!
  %4 = getelementptr inbounds %"struct:7:18", %"struct:7:18"* %1, i32 0, i32 0, !dbg !5685
  %8 = bitcast { %"[]u8.18", i16 }* %4 to i8*, !dbg !5686

This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
```

**Comment by LemonBoy** [comment] 2020-12-17 09:37
kinky.

But a duplicate of #7467, both of them caused by an `if` expression in a `.{}` block. Try pulling the `if` out of that.

> Still not quite sure how to concatenate stuff properly when different lengths

`mem.join` ?

**Closed** 2020-12-17 15:53 UTC
