### ISSUE TITLE
Local package hash different between Windows and WSL Linux

### ISSUE THREAD

**Issue by sergeypdev** [ziglang/zig#18891] opened 2024-02-10 20:46 UTC
### Zig Version

0.12.0-dev.2665+919a3bae1

### Steps to Reproduce and Observed Behavior

Do this on Linux (I'm using Ubuntu inside WSL) and Windows:
1. `zig init`
2. Download `zmath` from https://github.com/zig-gamedev/zig-gamedev/tree/main/libs/zmath
3. Save it to libs/zmath
4. `zig fetch --save ./libs/zmath`

Package hash on Windows and Linux is different.

```
Windows:  1220aaeeb4f4dc5e83e4525979daf07300e926f921e1e74957a793d0468350c9963c
Linux:    1220ed0cc5c336768fa18630f16aa6e14fbbee3843a373f0d61582038ac8a599fdd8
```

### Expected Behavior

Package hash will be the same on Linux and Windows

**Comment by schmee** [comment] 2024-02-10 20:48
Duplicate of https://github.com/ziglang/zig/issues/18089.

**Comment by sergeypdev** [comment] 2024-02-10 20:50
Whoops, sorry.

**Comment by sergeypdev** [comment] 2024-02-10 20:57
@schmee actually it's not because of FS case sensitivity, all filenames are lowercase and there's no tar unpacking or git fetch, because it's a local dependency.

**Comment by sergeypdev** [comment] 2024-02-10 21:11
This somehow happens even if I only leave README.md in build.zig.zon file array of zmath

**Comment by ianprime0509** [comment] 2024-02-10 22:16
Could you share the output of `zig fetch --debug-hash ./libs/zmath`? I'm getting the same hash you reported for Windows on my Fedora 39 system:

```
file: 87e0a042703b03552fb5732c98e1f38104c9c8b3bafcfa0a36aa2ecf6b6c3a1c: README.md
file: e16b5665e70deab82aae2e390c50ef54d85749c44eb27053fe12b9268943f321: build.zig
file: da4fc44403dad232eb855859e7b8171a931cc12639a1da931378c460ded1b4c7: build.zig.zon
file: 00cf0248f14109c40e7230de7505a4205f6836fcdd8e92c92d50bcc7f71c9bf8: src/benchmark.zig
file: 481d4b37d00fc8a9c550bc8225ae4498b1aad7abc32855644dde837bae31808b: src/main.zig
file: e52396b98ad347727575c92eaa6b97ce89aaaa50a953f2423532f08129128eb3: src/util.zig
file: 1019e4be6a0bd7d1c4ca50d3ef0bc06e9716a654873ed9e0d291b1e467037066: src/zmath.zig
1220aaeeb4f4dc5e83e4525979daf07300e926f921e1e74957a793d0468350c9963c
```

**Comment by sergeypdev** [comment] 2024-02-10 22:31
Windows:
```
$ zig fetch --debug-hash ./libs/zmath
file: 87e0a042703b03552fb5732c98e1f38104c9c8b3bafcfa0a36aa2ecf6b6c3a1c: README.md
file: e16b5665e70deab82aae2e390c50ef54d85749c44eb27053fe12b9268943f321: build.zig
file: da4fc44403dad232eb855859e7b8171a931cc12639a1da931378c460ded1b4c7: build.zig.zon
file: 00cf0248f14109c40e7230de7505a4205f6836fcdd8e92c92d50bcc7f71c9bf8: src/benchmark.zig
file: 481d4b37d00fc8a9c550bc8225ae4498b1aad7abc32855644dde837bae31808b: src/main.zig
file: e52396b98ad347727575c92eaa6b97ce89aaaa50a953f2423532f08129128eb3: src/util.zig
file: 1019e4be6a0bd7d1c4ca50d3ef0bc06e9716a654873ed9e0d291b1e467037066: src/zmath.zig
1220aaeeb4f4dc5e83e4525979daf07300e926f921e1e74957a793d0468350c9963c
```

WSL Ubuntu same dir as windows using /mnt/c (virtiofs 9p mount):
```
$ zig fetch --debug-hash ./libs/zmath
file: 7387f4a633c9db7e2f4be2b4422010bd65a3dcdc679d6341340bf32d0c770213: README.md
file: 297f8d1e2d38898a976751d13a4aac41ffbc4cebcec868990d6db2582a729278: build.zig
file: 7991a19c760836d0d19dce16d3f1f4a34911829cf5bc322d90e158815de49bf8: build.zig.zon
file: d2f753984479145b0e6f73c8fb904a0bd853af36001d01b911a32b9ffdfa467d: src/benchmark.zig
file: ce86a5598419664066247e20769e1789a7aca8fcc7a45c98cb85248cbfcbadfe: src/main.zig
file: 129e2d3840638c09bb9967c9af40113c16cf07be47aeea1b5f25bfdef869cc8c: src/util.zig
file: ba55d798a11c37fb0493123622317127087f424e0b051270f4da8ac766fa8a89: src/zmath.zig
1220ed0cc5c336768fa18630f16aa6e14fbbee3843a373f0d61582038ac8a599fdd8
```

Ok, I think I found the problem maybe. File permissions are different when I access it from the mount:

WSL /mnt/c/
```
$ ls -la
total 12
drwxrwxrwx 1 ubuntu ubuntu 4096 Feb 11 02:18 .
drwxrwxrwx 1 ubuntu ubuntu 4096 Feb 11 02:18 ..
-rwxrwxrwx 1 ubuntu ubuntu 4842 Feb 11 02:18 README.md
-rwxrwxrwx 1 ubuntu ubuntu 2920 Feb 11 02:18 build.zig
-rwxrwxrwx 1 ubuntu ubuntu  155 Feb 11 02:18 build.zig.zon
drwxrwxrwx 1 ubuntu ubuntu 4096 Feb 11 02:18 src
```

WSL native fs, extracted zip inside WSL:
```
$ ls -la
total 28
drwxr-xr-x 3 ubuntu ubuntu 4096 Feb 10 20:03 .
drwxr-xr-x 3 ubuntu ubuntu 4096 Feb 11 02:23 ..
-rw-r--r-- 1 ubuntu ubuntu 4842 Feb 10 20:03 README.md
-rw-r--r-- 1 ubuntu ubuntu 2920 Feb 10 20:03 build.zig
-rw-r--r-- 1 ubuntu ubuntu  155 Feb 10 20:03 build.zig.zon
drwxr-xr-x 2 ubuntu ubuntu 4096 Feb 10 20:03 src
```

When I copy from /mnt/c to WSL native fs I get different permissions:
```
$ ls -la
total 28
drwxr-xr-x 3 ubuntu ubuntu 4096 Feb 11 02:25 .
drwxr-xr-x 3 ubuntu ubuntu 4096 Feb 11 02:25 ..
-rwxr-xr-x 1 ubuntu ubuntu 4842 Feb 11 02:25 README.md
-rwxr-xr-x 1 ubuntu ubuntu 2920 Feb 11 02:25 build.zig
-rwxr-xr-x 1 ubuntu ubuntu  155 Feb 11 02:25 build.zig.zon
drwxr-xr-x 2 ubuntu ubuntu 4096 Feb 11 02:25 src
```

**Comment by ianprime0509** [comment] 2024-02-10 23:15
Ah, that makes sense. I can reproduce the WSL hash you're getting on my system by adding the executable permission to all the files under `zmath`, since the executable status of the file is considered when computing the file hash: https://github.com/ziglang/zig/blob/d18f52197d3e796858b79a70bfc6b6911b4f92ff/src/Package/Fetch.zig#L1549

**Comment by sergeypdev** [comment] 2024-02-11 00:33
@ianprime0509 thanks for investigating! This is a WSL issue so I guess it can be closed. 

This is probably not going to come up that often cause you have to use a pretty unusual setup to encounter this.

**Closed** 2024-02-11 00:34 UTC
Labels: bug
