### ISSUE TITLE
Compiler memory leak when using std.mem.zeros([X]u8)  

### ISSUE THREAD

**Issue by sadesakaswl** [ziglang/zig#17674] opened 2023-10-22 17:37 UTC
### Zig Version

0.12.0-dev.1168+54a4f24ea

### Steps to Reproduce and Observed Behavior

I observed high memory usage (11GB+) on my system and then compiler stuck without console output.
Tested on x86_64-windows.

It works:
```zig
fn readToFile(file: std.fs.File, reader: anytype) !void {
    var buf = std.mem.zeroes([4 * 1024]u8);
    while (true) {
        var n = try reader.readAll(&buf);
        if (buf.len != n) {
            _ = try file.write(buf[0..n]);
            break;
        }
        _ = try file.write(&buf);
    }
}
```

It doesn't work:
```zig
fn readToFile(file: std.fs.File, reader: anytype) !void {
    var buf = std.mem.zeroes([16 * 1024 * 1024]u8);
    while (true) {
        var n = try reader.readAll(&buf);
        if (buf.len != n) {
            _ = try file.write(buf[0..n]);
            break;
        }
        _ = try file.write(&buf);
    }
}
```

### Expected Behavior

It should compile normally

**Comment by Vexu** [comment] 2024-01-27 19:46
Duplicate of #15266

Use `comptime std.mem.zeroes(T)` as a workaround.

**Closed by Vexu** 2024-01-27 19:46 UTC
Labels: bug
