### ISSUE TITLE
Arrays init: error: dependency loop detected

### ISSUE THREAD

**Issue by jiangbo** [ziglang/zig#16407] opened 2023-07-14 08:13 UTC
### Zig Version

0.11.0-dev

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub const Object = struct {
    desc: []const u8,
    tag: []const u8,
    location: ?*Object = null,
};

pub const objs = [_]Object{
    .{ .desc = "an open field", .tag = "field" },
    .{ .desc = "a little cave", .tag = "cave" },
    .{ .desc = "a silver coin", .tag = "silver", .location = &objs[0] },
    .{ .desc = "a gold coin", .tag = "gold", .location = &objs[1] },
    .{ .desc = "a burly guard", .tag = "guard", .location = &objs[0] },
    .{ .desc = "yourself", .tag = "yourself", .location = &objs[0] },
};

pub fn main() !void {
    for (objs) |value| {
        std.debug.print("print: {s}", .{value});
    }
}
```

### Expected Behavior

should be successful

**Comment by Vexu** [comment] 2023-07-14 11:15
Duplicate of #131

**Closed by Vexu** 2023-07-14 11:15 UTC
Labels: bug
