### ISSUE TITLE
Truncated called-by trace with error in generic function return expression

### ISSUE THREAD

**Issue by ifreund** [ziglang/zig#14412] opened 2023-01-22 13:54 UTC
### Zig Version

0.11.0-dev.1414+c0284e242

### Steps to Reproduce and Observed Behavior

```zig
test {
    _ = foo();
}
fn foo() void {
    bar();
}
fn bar() void {
    _ = span(42);
}
fn span(p: anytype) Span(@TypeOf(p)) {
    return p;
}
fn Span(comptime t: type) type {
    _ = t;
    @compileError("t is bad: ");
}
```
```
❯ ~/projects/zig/build/stage3/bin/zig test /tmp/foo.zig 
/tmp/foo.zig:19:5: error: t is bad: 
    @compileError("t is bad: ");
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/foo.zig:13:25: note: called from here
fn span(p: anytype) Span(@TypeOf(p)) {
                    ~~~~^~~~~~~~~~~~
```

### Expected Behavior

The called-by trace should include `bar()` and `foo()`. The current state makes it very difficult to track down the callsite of functions like `span()` where the wrong type is passed.

**Comment by rohlem** [comment] 2023-01-22 14:54
potential rephrasing/duplicate of #14335

**Closed** 2023-01-22 15:05 UTC
Labels: bug, stage2
