### ISSUE TITLE
sorting a list of structures makes zig compiler segfaults

### ISSUE THREAD

**Issue by e0328eric** [ziglang/zig#20415] opened 2024-06-24 17:30 UTC
### Zig Version

0.14.0-dev.112+9be9b8ca9

### Steps to Reproduce and Observed Behavior

This zig code makes zig compiler segfaults.

```zig
const std = @import("std");

pub fn main() !void {
    var infos = [_]struct { u64, u64 }{
        .{ 1, 23 },
        .{ 2, 28 },
        .{ 3, 24 },
        .{ 4, 27 },
        .{ 5, 25 },
        .{ 6, 26 },
    };

    std.sort.pdq(struct { u64, u64 }, &infos, {}, struct {
        fn lessThan(context: void, lhs: struct { u64, u64 }, rhs: @TypeOf(lhs)) bool {
            _ = context;
            return lhs[1] < rhs[1];
        }
    }.lessThan);

    for (infos) |info| {
        std.debug.print("({}, {})\n", .{ info[0], info[1] });
    }
}
```

Here is the message in the terminal on  x86_64 intel linux
```console
$ zig build-exe bug.zig
fish: Job 1, 'zig build-exe bug.zig' terminated by signal SIGSEGV (Address boundary error)
```

### Expected Behavior

This code should compile and sort appropriately.

**Comment by Vexu** [comment] 2024-06-24 20:04
Duplicate of #19497

**Closed by Vexu** 2024-06-24 20:04 UTC
Labels: bug
