### ISSUE TITLE
Symlink creation in caching system fails on windows

### ISSUE THREAD

**Issue by rebb** [ziglang/zig#6608] opened 2020-10-08 02:32 UTC
Somewhat a continuation of https://github.com/ziglang/zig/issues/6199

Formerly i had the Issue above, but it has now been replaced with this one.
I'm on Windows, my UserData Dir is a Junction/Symlink.

Following errors occur :

```
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
```

This happens also when running the prompt as administrator.

**Comment by tadeokondrak** [comment] 2020-10-08 03:14
Note that's just a warning, it still compiles things fine. Only the caching system is affected.

See https://github.com/ziglang/zig/issues/6480 https://github.com/ziglang/zig/issues/6500

**Comment by rebb** [comment] 2020-10-08 03:33
Oh looks like you're right, sorry.

Those warnings were followed by an actual error though about ntdll.lib missing. I figured the warnings where the cause of this, and the error would indicate a failed compilation.

**Comment by rebb** [comment] 2020-10-08 08:21
Just to be clear, the .exe files are being created and they run. Not sure if they are "properly" compiled though due to the linker error.

**Comment by marler8997** [comment] 2020-10-08 09:44
Been experiencing the same thing on my Windows 7 box for the past few days.
```
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save linking hash digest symlink: AccessDenied
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save linking hash digest symlink: AccessDenied
```
I still get the resulting exe, but now each invocation of `zig build` takes no less than 8 seconds...sigh

**Comment by Sahnvour** [comment] 2020-10-09 17:55
This is because windows forbids creation of symbolic links with default privileges cf #6182.
To workaround, you can either run zig with admin rights (not great) or enable the developer mode (on windows 10).

**Comment by Sahnvour** [comment] 2020-10-09 18:00
Duplicate of #6500.

**Closed by Sahnvour** 2020-10-09 18:00 UTC
Labels: bug, os-windows, stage2

**Comment by rebb** [comment] 2020-10-09 19:53
As mentioned it also happens when running the Command-Prompt as Administrator though and calling zig there.
I'll wait until #6500 is fixed :)

**Comment by overtinkering** [comment] 2020-11-16 00:35
I get the same behaviour on Linux (Arch) on a FAT32 partition. My understanding is that there are no symlinks on FAT32 partitions. So this happens even as root. I just wanted to add this environment to the report in case it is useful for https://github.com/ziglang/zig/issues/6500
