### ISSUE TITLE
provide a way to format structs in a nested manner.

### ISSUE THREAD

**Issue by lolbinarycat** [ziglang/zig#7403] opened 2020-12-11 23:44 UTC
currently if you use `std.debug.print`, it only prints the struct one level, which is understandable as a default, but it would be nice if there was some other way.

One idea would be to use the `precision` of the format parameter, but I don't know how that interacts with structs of floats.

**Comment by Vexu** [comment] 2020-12-18 09:44
Duplicate of #2370.

**Closed by Vexu** 2020-12-18 09:44 UTC
