### ISSUE TITLE
bw.flush(); will cause 'zig build test' hang

### ISSUE THREAD

**Issue by PegasusPlusUS** [ziglang/zig#21984] opened 2024-11-14 00:56 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

1. Use 'zig init' to generate default project
2. Append a test to src/main.zig:
```zig
test "bw.flush() has to be commentted out" {
    try main();
}
```
3. Run test with 'zig build test'
4. zig test runner hangs:
[3/5] steps
└─ [1/2] run test
   └─ main.test.bw.flush() has to be commentte

### Expected Behavior

If comment out the 'bw.flush();', test can run normally.
Since the generated code emphasized 'don't forget to flush!', it might be something wrong within implementation of std.io.bufferedWriter?

**Comment by nektro** [comment] 2024-11-14 01:07
duplicate of https://github.com/ziglang/zig/issues/15091

**Comment by PegasusPlusUS** [comment] 2024-11-14 03:42
Thank a lot!
Checking #15091, it was marked as "added this to the [0.11.0](https://github.com/ziglang/zig/milestone/17) milestone [on Apr 10, 2023](https://github.com/ziglang/zig/issues/15091#event-8965509178)"
So still not resolved?

It's really confusing because if zig want to update building progress, I guess before build complete, test runner already started? Maybe after zig complete building, then test runner start, there will be no conflict on stdout.

**Closed** 2024-11-19 15:12 UTC
Labels: bug
