### ISSUE TITLE
Trying to use an opaque type in a struct or union crashes the compiler

### ISSUE THREAD

**Issue by eduardosm** [ziglang/zig#1223] opened 2018-07-12 17:43 UTC
```
const Test = struct {
    x: @OpaqueType(),
};

test "test" {
    var x: Test = undefined;
}
```
Produces:
```
unreachable: /home/eduardosm/.cache/pacaur/zig-git/src/zig/src/analyze.cpp:type_requires_comptime:5028
```

**Comment by hryx** [comment] 2018-07-22 02:07
In case it helps, I've also found that the compiler properly catches use of a non-pointer opaque type in a function argument...

```zig
const Opaque = @OpaqueType();

fn f(o: Opaque) void {} // error: parameter of type 'Opaque' not allowed

test "use of non-pointer opaque argument" {
    _ = f;
}
```

..._unless_ that function is assigned to a function pointer struct member.

```zig
const Opaque = @OpaqueType();

const S = struct {
    bad: fn (o: Opaque) void,
};

fn f(o: Opaque) void {}

test "use of non-pointer opaque argument (fn as struct member)" {
    const s = S{
        .bad = f,
    }; // hits unreachable
}
```

**Comment by roobie** [comment] 2018-11-17 01:03
Not sure whether it helps or not, but this results in a very similar error message:

```
const std = @import("std");

pub fn main() void {
    var a: ?*c_void = undefined;
    if (a) |b| {
        std.debug.warn("{}: Uh oh\n", b.*);
    }
}
```

```
zig build-obj ../temp/test1.zig
unreachable: /deps/zig/src/analyze.cpp:type_requires_comptime:5096
[1]    3860 abort      zig build-obj ../temp/test1.zig
```

However, when I change the name of the function to something other than `main`, it compiles without an error or unexpected termination.


OK:
```
const std = @import("std");

pub fn anotherName() void {
    var a: ?*c_void = undefined;
    if (a) |b| {
        std.debug.warn("{}: Uh oh\n", b.*);
    }
}
```

also OK:
```
var c: *c_void = undefined;
pub fn main() void {
    var a: ?*c_void = undefined;
    if (a) |b| {
        c = b;
    }
}
```

**Comment by andrewrk** [comment] 2019-03-23 23:36
#1862 was a duplicate of this and this is now fixed.

**Closed by andrewrk** 2019-03-23 23:36 UTC
Labels: bug
