### ISSUE TITLE
Zig compiler crash (both with and without llvm)

### ISSUE THREAD

**Issue by sfiedler0** [ziglang/zig#22008] opened 2024-11-17 15:26 UTC
### Zig Version

0.14.0-dev.2245+4fc295dc0 (master)

### Steps to Reproduce and Observed Behavior

I was originally writing a parser for the so-called "struct block" of a device tree (for my RISC-V kernel)…

My file looked like this:

```zig
// crash.zig

const std = @import("std");

const Self = @This();

/// Structure Block Token Type
pub const TokenType = enum(u32) {
    begin_node = 0x1,
    end_node = 0x2,
    prop = 0x3,
    nop = 0x4,
    end = 0x9,
};

/// Begin Node
pub const BeginNode = struct {
    name: [*:0]const u8,
};

/// Structure Block Token
pub const Token = union(TokenType) {
    begin_node: BeginNode,
    end_node: void,
    prop: void,
    nop: void,
    end: void,
};

/// Buffer
buf: []const u8,
/// Counter
i: usize,

/// Initialize the structure block parser
pub fn init(self: *Self, struct_block_addr: usize, struct_block_len: usize) void {
    self.buf = @as([*]const u8, @ptrFromInt(struct_block_addr))[0..struct_block_len];
    self.i = 0;
}

/// Next Token
pub fn next(self: *Self) Token {
    const token_type: TokenType = @enumFromInt(std.mem.readInt(u32, self.buf[self.i..][0..4], .big));
    const token: Token = undefined;
    self.i += 4;
    switch (token_type) {
        .begin_node => {
            token = .{
                .begin_node = BeginNode{
                    .name = @ptrFromInt(@intFromPtr(self.buf.ptr) + self.i),
                },
            };
        },
        else => {
            // unhandled
            // original code from me throws error here
        },
    }
    return token;
}

test "test" {
    const buf: []const u8 = &.{ 0, 0, 0, 1, 65, 0 };
    var struct_block_parser: Self = undefined;
    struct_block_parser.init(@intFromPtr(buf.ptr), buf.len);
    _ = struct_block_parser.next();
}
```

When you test it ( `zig test crash.zig`) with a debug build (without llvm), you get the following crash:

```
thread [xxxxxxx] panic: reached unreachable code
Analyzing crash.zig
      %118 = dbg_stmt(7, 13)
      %120 = opt_eu_base_ptr_init(%119) node_offset:46:21 to :46:21
    > %121 = struct_init_field_ptr(%120, "begin_node") node_offset:47:31 to :47:31
      %122 = block_comptime({
        %123 = decl_val("BeginNode") token_offset:47:31 to :47:40
        %124 = break(%122, %123)
      }) node_offset:47:31 to :47:40
      %125 = validate_struct_init_ty(%122) node_offset:47:31 to :47:31
      %126 = struct_init_field_type(%122, name) node_offset:48:29 to :48:76
      %127 = dbg_stmt(9, 57)
      %128 = field_val(%69, "buf") node_offset:48:53 to :48:61
      %129 = dbg_stmt(9, 61)
      %130 = field_val(%128, "ptr") node_offset:48:53 to :48:65
      %131 = dbg_stmt(9, 41)
      %132 = int_from_ptr(%130) node_offset:48:41 to :48:66
      %133 = dbg_stmt(9, 73)
      %134 = field_val(%69, "i") node_offset:48:69 to :48:75
      %135 = dbg_stmt(9, 67)
      %136 = add(%132, %134) node_offset:48:41 to :48:75
      %137 = dbg_stmt(9, 29)
      %138 = ptr_from_int(%126, %136) node_offset:48:29 to :48:76
      %139 = struct_init([%126, %138]) node_offset:47:31 to :47:31
      %140 = store_node(%121, %139) node_offset:47:31 to :47:31
      %141 = validate_ptr_struct_init({
        %121 = struct_init_field_ptr(%120, "begin_node") node_offset:47:31 to :47:31
      }) node_offset:46:21 to :46:21
      %142 = break(%116, @void_value)
    For full context, use the command
      zig ast-check -t crash.zig

  in crash.zig
    > %116 = switch_block(%96,
        else => {%143},
        %117 => {%118..%142}) node_offset:44:5 to :44:11

Unwind error at address `exe:0x26355dc` (error.AddressOutOfRange), trace may be incomplete

/home/sfiedler/exec/zig/src/Sema.zig:32052:27: 0x353fc2e in storePtrVal (main.zig)
        .runtime_store => unreachable, // use sites check this
                          ^
/home/sfiedler/exec/zig/src/Sema.zig:29304:37: 0x3c0c04d in unionFieldPtr (main.zig)
                try sema.storePtrVal(block, src, union_ptr_val, new_union_val, union_ty);
                                    ^
/home/sfiedler/exec/zig/src/Sema.zig:28724:53: 0x352e742 in fieldPtr (main.zig)
            const field_ptr = try sema.unionFieldPtr(block, src, inner_ptr, field_name, field_name_src, inner_ty, initializing);
                                                    ^
/home/sfiedler/exec/zig/src/Sema.zig:10643:33: 0x3658c3d in zirStructInitFieldPtr (main.zig)
            return sema.fieldPtr(block, src, object_ptr, field_name, field_name_src, true);
                                ^
/home/sfiedler/exec/zig/src/Sema.zig:1158:76: 0x2dac318 in analyzeBodyInner (main.zig)
            .struct_init_field_ptr        => try sema.zirStructInitFieldPtr(block, inst),
                                                                           ^
/home/sfiedler/exec/zig/src/Sema.zig:917:26: 0x3634aad in analyzeBodyRuntimeBreak (main.zig)
    sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                         ^
/home/sfiedler/exec/zig/src/Sema.zig:11390:52: 0x42ebfec in analyzeProngRuntime (main.zig)
                return sema.analyzeBodyRuntimeBreak(case_block, prong_body);
                                                   ^
/home/sfiedler/exec/zig/src/Sema.zig:13087:49: 0x3cca7b4 in analyzeSwitchRuntimeBlock (main.zig)
            break :h try spa.analyzeProngRuntime(
                                                ^
/home/sfiedler/exec/zig/src/Sema.zig:12911:62: 0x362ee2e in zirSwitchBlock (main.zig)
    const air_switch_ref = try sema.analyzeSwitchRuntimeBlock(
                                                             ^
/home/sfiedler/exec/zig/src/Sema.zig:1141:69: 0x2dab607 in analyzeBodyInner (main.zig)
            .switch_block                 => try sema.zirSwitchBlock(block, inst, false),
                                                                    ^
/home/sfiedler/exec/zig/src/Sema.zig:937:26: 0x2d1aac8 in analyzeFnBody (main.zig)
    sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                         ^
/home/sfiedler/exec/zig/src/Zcu/PerThread.zig:2211:23: 0x2d1e53f in analyzeFnBody (main.zig)
    sema.analyzeFnBody(&inner_block, fn_info.body) catch |err| switch (err) {
                      ^
/home/sfiedler/exec/zig/src/Zcu/PerThread.zig:832:35: 0x271d71d in ensureFuncBodyAnalyzedInner (main.zig)
    var air = try pt.analyzeFnBody(func_index);
                                  ^
/home/sfiedler/exec/zig/src/Zcu/PerThread.zig:735:81: 0x21260bd in ensureFuncBodyAnalyzed (main.zig)
    const ies_outdated, const analysis_fail = if (pt.ensureFuncBodyAnalyzedInner(func_index, func_outdated)) |result|
                                                                                ^
/home/sfiedler/exec/zig/src/Compilation.zig:3657:38: 0x1c32ab1 in processOneJob (main.zig)
            pt.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                     ^
/home/sfiedler/exec/zig/src/Compilation.zig:3604:30: 0x1911ea4 in performAllTheWorkInner (main.zig)
            try processOneJob(@intFromEnum(Zcu.PerThread.Id.main), comp, job, main_progress_node);
                             ^
/home/sfiedler/exec/zig/src/Compilation.zig:3464:36: 0x16bf5f2 in performAllTheWork (main.zig)
    try comp.performAllTheWorkInner(main_progress_node);
                                   ^
/home/sfiedler/exec/zig/src/Compilation.zig:2233:31: 0x156710e in update (main.zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/sfiedler/exec/zig/src/main.zig:4409:20: 0x15a0389 in updateModule (main.zig)
    try comp.update(prog_node);
                   ^
/home/sfiedler/exec/zig/src/main.zig:3601:21: 0x15cd276 in buildOutputType (main.zig)
        updateModule(comp, color, root_prog_node) catch |err| switch (err) {
                    ^
/home/sfiedler/exec/zig/src/main.zig:268:31: 0x1613749 in mainArgs (main.zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/sfiedler/exec/zig/src/main.zig:200:20: 0x14d49bb in main (main.zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/sfiedler/zig/0.14.0-dev.2245+4fc295dc0/files/lib/std/start.zig:617:37: 0x14d25a6 in posixCallMainAndExit (std.zig)
            const result = root.main() catch |err| {
                                    ^
/home/sfiedler/zig/0.14.0-dev.2245+4fc295dc0/files/lib/std/start.zig:248:5: 0x14d2016 in _start (std.zig)
    asm volatile (switch (native_arch) {
    ^
```

### Expected Behavior

I expected `zig test` to throw either an error or succeed. 

### Further Information

`zig2` from `./bootstrap` gives me the following error:

```
crash.zig:47:40: error: bit-pointer target exceeds host size
                .begin_node = BeginNode{
                              ~~~~~~~~~^
```

As I have no idea about what happened exactly, it would be a good idea to update the issue title…

**Comment by Vexu** [comment] 2024-11-17 17:16
Duplicate of https://github.com/ziglang/zig/issues/19832#issuecomment-2267113103

**Closed by Vexu** 2024-11-17 17:16 UTC
Labels: bug
