### ISSUE TITLE
Compiler crash with @bitReverse

### ISSUE THREAD

**Issue by schmee** [ziglang/zig#2752] opened 2019-06-25 16:21 UTC
I'm sure this example is nonsense (this is not how you're supposed to use `@bitReverse`) but it does crash the compiler so I'll go ahead and post it anyway:

crash.zig
```zig
pub fn main() void {
    var foo = [_]u8{0};
    @bitReverse(u8, foo.*);
}
```

```
➜  src git:(aes) ✗ zig build-exe crash.zig
Assertion failed. This is a bug in the Zig compiler.
Unable to dump stack trace: FileNotFound
[1]    62328 abort      zig build-exe crash.zig
```

Versions:

```
➜  src git:(aes) ✗ zig version
0.4.0+9153b17c
```

macOS Mojave 10.14.3

**Comment by SamTebbs33** [comment] 2019-06-25 19:58
Reproduced on ubuntu
```
#17 0x000055555650d8f9 in assert (ok=false) at /home/sam/repos/zig/src/util.cpp:28
#18 0x00005555564a4989 in ir_implicit_cast (ira=0x5555609eed10, value=0x55555c614dc0, expected_type=0x55555c612ea0) at /home/sam/repos/zig/src/ir.cpp:12123
#19 0x00005555564cf966 in ir_analyze_instruction_bit_reverse (ira=0x5555609eed10, instruction=0x5555609ee800) at /home/sam/repos/zig/src/ir.cpp:23577
#20 0x00005555564d052f in ir_analyze_instruction_nocast (ira=0x5555609eed10, instruction=0x5555609ee800) at /home/sam/repos/zig/src/ir.cpp:23815
#21 0x00005555564d0f2e in ir_analyze_instruction (ira=0x5555609eed10, old_instruction=0x5555609ee800) at /home/sam/repos/zig/src/ir.cpp:24029
#22 0x00005555564d1220 in ir_analyze (codegen=0x55555c602840, old_exec=0x5555609eaa48, new_exec=0x5555609eab38, expected_type=0x55555c6124c0, expected_type_source_node=0x55555c64ac80)
    at /home/sam/repos/zig/src/ir.cpp:24080
#23 0x000055555651997a in analyze_fn_ir (g=0x55555c602840, fn_table_entry=0x5555609ea9e0, return_type_node=0x55555c64ac80) at /home/sam/repos/zig/src/analyze.cpp:3665
#24 0x0000555556519dd1 in analyze_fn_body (g=0x55555c602840, fn_table_entry=0x5555609ea9e0) at /home/sam/repos/zig/src/analyze.cpp:3752
#25 0x000055555651ac86 in semantic_analyze (g=0x55555c602840) at /home/sam/repos/zig/src/analyze.cpp:3999
#26 0x000055555646f1dd in gen_root_source (g=0x55555c602840) at /home/sam/repos/zig/src/codegen.cpp:8704
#27 0x0000555556472a4d in codegen_build_and_link (g=0x55555c602840) at /home/sam/repos/zig/src/codegen.cpp:9634
#28 0x000055555644aaf1 in main (argc=3, argv=0x7fffffffe868) at /home/sam/repos/zig/src/main.cpp:1147
```

**Comment by shawnl** [comment] 2019-06-29 19:45
Works for me

```
/home/shawn/git/zig-simd/src/t.zig:3:24: error: attempt to dereference non-pointer type '[1]u8'
    @bitReverse(u8, foo.*);
                       ^
```

**Comment by andrewrk** [comment] 2019-07-08 19:39
Appears to be fixed in master.

**Closed by andrewrk** 2019-07-08 19:39 UTC
Labels: bug
