### ISSUE TITLE
Unexpected "value stored in comptime field does not match the default value of the field"

### ISSUE THREAD

**Issue by MasonRemaley** [ziglang/zig#20310] opened 2024-06-16 00:35 UTC
### Zig Version

0.14.0-dev.453+eda846b86

### Steps to Reproduce and Observed Behavior

The following code does not compile:
```zig
    const Enum = @Type(.{
        .Enum = .{
            .tag_type = u0,
            .fields = &.{.{
                .name = "a",
                .value = 0,
            }},
            .decls = &.{},
            .is_exhaustive = true,
        },
    });
    const Wrapper = struct { Enum };
    const wrapper: Wrapper = .{Enum.a};
    _ = wrapper;
```
```
zig3 build run
run
└─ run zengine
   └─ install zengine
      └─ zig build-exe zengine Debug x86_64-linux.4.19...6.5.7-gnu.2.28 1 errors
src/main.zig:102:36: error: value stored in comptime field does not match the default value of the field
    const wrapper: Wrapper = .{Enum.a};
                               ~~~~^~
referenced by:
    callMain: /home/mason/Documents/zon/zig/lib/std/start.zig:524:32
    callMainWithArgs: /home/mason/Documents/zon/zig/lib/std/start.zig:482:12
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
error: the following command failed with 1 compilation errors:
/home/mason/Documents/zon/zig/build/stage3/bin/zig build-exe /home/mason/Documents/zengine/.zig-cache/o/6fb735450a2339dbceb95bf47e8d6663/libglfw.a -ODebug -target x86_64-linux.4.19...6.5.7-gnu.2.28 -mcpu baseline --dynamic-linker /lib64/ld-linux-x86-64.so.2 -I /home/mason/Documents/zengine/.zig-cache/o/28adb866bdb221452115394d139b47a4 -Mroot=/home/mason/Documents/zengine/src/main.zig -lc++ --cache-dir /home/mason/Documents/zengine/.zig-cache --global-cache-dir /home/mason/.cache/zig --name zengine --listen=-
Build Summary: 2/6 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run zengine transitive failure
   ├─ zig build-exe zengine Debug x86_64-linux.4.19...6.5.7-gnu.2.28 1 errors
   └─ install zengine transitive failure
      └─ zig build-exe zengine Debug x86_64-linux.4.19...6.5.7-gnu.2.28 (+2 more reused dependencies)
error: the following build command failed with exit code 1:
/home/mason/Documents/zengine/.zig-cache/o/e72f62dd38fce50d6946abf6cc782bc5/build /home/mason/Documents/zon/zig/build/stage3/bin/zig /home/mason/Documents/zengine /home/mason/Documents/zengine/.zig-cache /home/mason/.cache/zig --seed 0xcd6dc4eb -Z91f0086ae20dae30 run
```

This is the minimal case I was able to come up with to cause the error. If I create the enum via `enum { a }` it works as expected. Same if I set the enum's tag type to `u1` instead of `u0`, or get rid of the wrapper struct.

### Expected Behavior

I expected the given code to compile without errors and produce the same behavior as if I had declared the enum as `enum { a }` instead of creating it through `@Type(...)`.

**Comment by xdBronch** [comment] 2024-06-16 00:40
duplicate of https://github.com/ziglang/zig/issues/19985

**Closed** 2024-06-16 09:35 UTC
Labels: bug
