### ISSUE TITLE
std.json.Parser should also work with Reader

### ISSUE THREAD

**Issue by Opioid** [ziglang/zig#9518] opened 2021-08-04 08:40 UTC
I think it would be good if std.json.Parser would also work with the Reader interface instead of supplying the full buffer directly. Alternatively or in addition it would be good ta have an "in-situ" variant, where the json tree is constructed in the memory of the already allocated buffer that is used for parsing.
What do you think?

**Comment by Vexu** [comment] 2021-08-04 08:53
Duplicate of #8207.

**Closed** 2021-08-04 09:51 UTC
Labels: duplicate
