### ISSUE TITLE
unused function(, struct, ...) does not cause compile error

### ISSUE THREAD

**Issue by Traxar** [ziglang/zig#11948] opened 2022-06-28 07:16 UTC
### Zig Version

0.10.0-dev.2751+08459ff1c

### Steps to Reproduce

Currently the zig-compiler throws an error if a variable is declared but never used. As an example:

```
test "unused variable" {
    const foo: u8 = 0;
}
```

does not compile as `foo` is never used.

However if similarly a function `bar` is defined, which is never used:

```
fn bar() u8 {
	return 0;
}

test "unused function" {

}
```

the code is being compiled and no error is thrown.

### Expected Behavior

Handle unused functions, structs, unions and enums similar to unused variables, aka. throw a compile error if anything is defined but never used.

* Only non-`pub`, non-`export` functions, structs, unions, enums need to be checked, as they can't be used from a different context.
* Checking for unused things can happen on just the lexial structure.
* The syntax `_ = bar;` is already implemented to allow compilation.

### Actual Behavior

As of now the unused errors are only implemented for variables (const and var). However as a zig user one would expect the compiler to also throw errors for unsused functions, structs, unions and enums. This behaviour would complement proposal #1717 well and make behaviour more consistent.

**Comment by Vexu** [comment] 2022-06-28 07:51
Duplicate of #335

**Closed by Vexu** 2022-06-28 07:51 UTC
Labels: bug

**Comment by nektro** [comment] 2022-06-29 18:35
this behavior is implemented in https://github.com/nektro/ziglint
