### ISSUE TITLE
Compiler SIGSEGV when testing a file that doesn't exist

### ISSUE THREAD

**Issue by pfgithub** [ziglang/zig#21089] opened 2024-08-15 18:56 UTC
### Zig Version

zig-linux-x86_64-0.14.0-dev.1078+0f0f543a9

### Steps to Reproduce and Observed Behavior

```
$> zig test notfound.zig # (notfound.zig doesn't exist)
fish: Job 1, 'zig test a.zig' terminated by signal SIGSEGV (Address boundary error)comptime
Exited with code [SIGSEGV]
```

### Expected Behavior

Shouldn't crash, should probably say something like `build-exe` does

```
/zig/zig-linux-x86_64-0.14.0-dev.1078+0f0f543a9/lib/std/Build.zig:1924:34: error: unable to load './filenotfound.zig': FileNotFound
    const build_runner = @import("root");
                                 ^~~~~~
```

**Comment by Rexicon226** [comment] 2024-08-15 19:03
duplicate of #20954

**Closed** 2024-08-15 19:57 UTC
Labels: bug
