### ISSUE TITLE
zig compiler panic when invalid code (?) and stuff in panic handler

### ISSUE THREAD

**Issue by sm2n** [ziglang/zig#16943] opened 2023-08-24 04:17 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```
➤ ls
reproducer.zig  zig/
➤ ./zig/bin/zig version
0.11.0
➤ ./zig/bin/zig build-exe -target x86_64-freestanding reproducer.zig
thread 67019 panic: reached unreachable code
/builds/zig/src/Module.zig:1832:26: 0x5aa1ac4 in span (zig)
            .unneeded => unreachable,
                         ^
/builds/zig/src/Compilation.zig:2876:55: 0x5ab9727 in addModuleErrorMsg (zig)
        const span = try module_reference.src_loc.span(gpa);
                                                      ^
/builds/zig/src/Compilation.zig:2706:42: 0x5abf98d in getAllErrorsAlloc (zig)
                    try addModuleErrorMsg(module, &bundle, entry.value_ptr.*.*);
                                         ^
/builds/zig/src/main.zig:4033:44: 0x5ac610b in updateModule (zig)
    var errors = try comp.getAllErrorsAlloc();
                                           ^
/builds/zig/src/main.zig:3451:17: 0x5ae962a in buildOutputType (zig)
    updateModule(comp) catch |err| switch (err) {
                ^
/builds/zig/src/main.zig:270:31: 0x594dc2f in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/builds/zig/src/main.zig:214:20: 0x594afb5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/builds/zig/lib/std/start.zig:574:37: 0x594a99e in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7ff8bb027ccf in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7ff8bb027ccf` was not available, trace may be incomplete

fish: Job 1, './zig/bin/zig build-exe -target…' terminated by signal SIGABRT (Abort)
```

reproducer.zig:
```zig
const std = @import("std");
const builtin = @import("builtin");

var kernel_panic_allocator_bytes: [100 * 1024]u8 = undefined;
var kernel_panic_allocator_state = std.heap.FixedBufferAllocator.init(kernel_panic_allocator_bytes[0..]);
const kernel_panic_allocator = kernel_panic_allocator_state.allocator();

const assert = std.debug.assert;

export var stack_bytes: [16 * 1024]u8 align(16) linksection(".bss") = undefined;

export fn _start() callconv(.Naked) noreturn {}
pub fn getSelfDebugInfo() !std.dwarf.DwarfInfo {
    var dwarf_info = std.dwarf.DwarfInfo{
        .endian = builtin.target.cpu.arch.endian(),
        .debug_abbrev = &.{},
        .debug_str = &.{},
        .debug_str_offsets = null,
        .debug_line = &.{},
        .debug_line_str = null,
        .debug_ranges = &.{},
        .debug_loclists = null,
        .debug_rnglists = null,
        .debug_addr = null,
        .debug_names = null,
        .debug_frame = &.{},
    };
    try std.dwarf.openDwarfDebugInfo(&dwarf_info, kernel_panic_allocator);
    return dwarf_info;
}

pub fn panic(message: []const u8, maybe_stack_trace: ?*std.builtin.StackTrace, ret_addr: ?usize) noreturn {
    _ = ret_addr;
    _ = message;
    _ = getSelfDebugInfo() catch unreachable;
    _ = maybe_stack_trace;
    halt();
}

pub fn halt() noreturn {
    asm volatile ("cli");
    while (true) {}
}
export fn kernel_main() noreturn {
    const multiboot_info: *const MultibootInfo = @ptrFromInt(1312);
    const mem_map_len = @divExact(multiboot_info.mmap_length, @sizeOf(MultibootMemoryMapEntry));
    _ = mem_map_len;

    halt();
}

const MultibootInfo = packed struct {
    flags: u32,
    mem_lower: u32,
    mem_upper: u32,
    boot_device: u32,
    cmdline: u32,
    mods_count: u32,
    mods_addr: u32,
    num: u32,
    size: u32,
    addr: u32,
    shndx: u32,
    mmap_length: u32,
    mmap_addr: u32,
    drives_length: u32,
    drives_addr: u32,
    config_table: u32,
    boot_loader_name: u32,
    apm_table: u32,
    vbe_control_info: u32,
    vbe_mode_info: u32,
    vbe_mode: u16,
    vbe_interface_seg: u16,
    vbe_interface_off: u16,
    vbe_interface_len: u16,
    framebuffer_addr: u64,
    framebuffer_pitch: u32,
    framebuffer_width: u32,
    framebuffer_height: u32,
    framebuffer_bpp: u8,
    framebuffer_type: u8,
    color_info: u36,
};

const MultibootMemoryMapEntry = packed struct {
    size: u32,
    base_addr: u64,
    length: u64,
    type: Type,
    const Type = enum(u32) {
        available = 1,
        acpi = 3,
        reserved = 4,
        defective = 5,
    };
};
```

As far as I can tell, everything here seems weirdly load-bearing, so this is as far as I was able to reduce it. This is on linux x86_64.

### Expected Behavior

The compiler to not segfault but rather error out (the DwarfInfo struct is wrong).

**Comment by ianprime0509** [comment] 2023-08-25 00:11
Duplicate of #16327 (which should be closed, since the issue is fixed on master)

This is the output I get on Zig 0.12.0-dev.161+6a5463951:

```
test.zig:16:10: error: no field named 'debug_abbrev' in struct 'dwarf.DwarfInfo'
        .debug_abbrev = &.{},
         ^~~~~~~~~~~~
/home/ian/src/zig/lib/std/dwarf.zig:662:23: note: struct declared here
pub const DwarfInfo = struct {
                      ^~~~~~
referenced by:
    panic: test.zig:35:9
    kernel_main: test.zig:46:25
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Comment by jacobly0** [comment] 2023-08-25 19:42
Duplicate of #16327

**Closed** 2023-08-25 19:42 UTC
Labels: bug
