### ISSUE TITLE
compiler segmentation fault when tagged unions in custom logging function

### ISSUE THREAD

**Issue by texmex76** [ziglang/zig#21704] opened 2024-10-15 15:34 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
pub const std_options = .{
    .logFn = myLogFn,
};
const UnionEnum = union(enum) {};
pub fn myLogFn(
    comptime l: anytype,
    comptime s: anytype,
    comptime f: anytype,
    a: UnionEnum,
) void {
    _ = l;
    _ = s;
    _ = f;
    _ = a;
}
pub fn main() void {}
```

When trying to build the above code using `zig build-exe`, the compiler segfaults:

```
[1]    13323 segmentation fault  zig build-exe main.zig
```

### Expected Behavior

Expected the compiler to give any output and exit gracefully.

I looked a bit around and [18518](https://github.com/ziglang/zig/issues/18518) looks similar, but that one was already resolved and the compiler does not crash anymore for the input given in that bug report.

**Comment by rohlem** [comment] 2024-10-15 16:38
Still reproduces for me on newer version `0.14.0-dev.1579+f3445f8f6`.
FYI, the issue is with your `union` type: Since it has no possible states, it is an uninstantiable type (aka `noreturn`-like), see also https://github.com/ziglang/zig/issues/15909 for planned behavior.
As you've stated though, the compiler crashing is a bug, it should instead result in a compile error pointing out the problem.

**Comment by Vexu** [comment] 2024-10-15 16:40
Duplicate of #21099

**Closed by Vexu** 2024-10-15 16:40 UTC
Labels: bug
