### ISSUE TITLE
arrays in inline for array of types

### ISSUE THREAD

**Issue by BarabasGitHub** [ziglang/zig#1321] opened 2018-08-02 20:17 UTC
This doesn't seem to work. A quick look with the visual studio debugger seems to indicate that it only has one a and one b. So the float one works, but the i32 uses the same memory?

```    
inline for ([]type{f32, i32}) |t| {
        const a = []t{1, 2, 3};
        const b = []t{3, 4, 5};
        // do something with a and b.
}
```

And when you do this, the compiler does 100% cpu and doesn't seem to exit.
``` 
inline for ([]type{f32, i32, u15}) |t| {
        const a = []t{1, 2, 3};
        const b = []t{3, 4, 5};
        // do something with a and b.
}
```` 

It works with ``[]type{f32, f64}`` though. But ``[]type{f16, f32}`` not. :thinking: 

Just in case, I'm trying to test my dotProduct function on multiple types:

```
fn dotProduct(comptime T: type, a: []const T, b: []const T) T {
    assert(a.len == b.len);
    var s = T(0);
    for(a) |e,i| {
        s += e * b[i];
    }
    return s;
}
```

**Comment by andrewrk** [comment] 2018-09-04 19:46
dupe of #917, fixed by 09cc1dc66067f378a1508e34c0714b659b445724

**Closed by andrewrk** 2018-09-04 19:46 UTC
Labels: bug
