### ISSUE TITLE
Incorrect error location when integer type doesn't match into target integer size

### ISSUE THREAD

**Issue by dec05eba** [ziglang/zig#16688] opened 2023-08-05 02:15 UTC
### Zig Version

0.12.0-dev.3+9c05810be

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

fn nothing() void {} // error is incorrectly displayed here

fn toSeeHere() void {}

fn resize(allocator: std.mem.Allocator, size: i32) !void {
    const data = try allocator.alloc(u8, size); // error should be displayed here, alloc expects usize but we give it i32
    defer allocator.free(data);
}

test "incorrect error location on integer cast" {
    try resize(std.testing.allocator, 32);
}
```
error:
```
src/main.zig:3:1: error: expected type 'usize', found 'i32'
fn nothing() void {} // error is incorrectly displayed here
^~~~~~~~~~~~~~~~~
src/main.zig:3:1: note: unsigned 64-bit int cannot represent all possible signed 32-bit values
referenced by:
    test.incorrect error location on integer cast: src/main.zig:13:9
```
it mentions line 13, which is the call to resize, but it doesn't mention where in resize the error is.
It seems to always point the error at the first function in the file (that includes functions inside structs).

### Expected Behavior

Show correct compile error location

**Comment by jacobly0** [comment] 2023-08-05 08:23
Duplicate of #16601

**Closed by jacobly0** 2023-08-05 08:23 UTC
Labels: bug, frontend, error message, regression
