### ISSUE TITLE
Problem with _fseeki64 function on Windows (mingw-w64)

### ISSUE THREAD

**Issue by michal-z** [ziglang/zig#9765] opened 2021-09-14 19:54 UTC
mingw-w64 9.0.0 implements ```_fseeki64``` function in ```mingw-w64-crt/stdio/fseeki64.c``` file. This function is also implemented by Microsoft CRT on Windows.

Some libraries use it so I think zig cc should also expose it for compatibility with MSVC.

Currently zig cc does not expose this function because it does not include ```mingw-w64-crt/stdio/fseeki64.c``` file in ```zig/lib/libc/mingw/stdio``` folder.

**Comment by marler8997** [comment] 2021-09-14 20:07
duplicate of https://github.com/ziglang/zig/issues/9402

**Closed** 2021-09-14 20:13 UTC
