### ISSUE TITLE
Compiler crash when using std.mem.bytesAsValue/bytesToValue

### ISSUE THREAD

**Issue by zxubian** [ziglang/zig#13298] opened 2022-10-25 14:13 UTC
### Zig Version

0.10.0-dev.4562+b3cd38ea4 (Windows)

### Steps to Reproduce

1. create repro.zig with the following contents:
``` zig
/// repro.zig
const std = @import("std");
const expect = std.testing.expect;
const assert = std.debug.assert;

const EthernetHeader = packed struct {
    // 6 bytes
    destination_address: u48,
    // 6 bytes
    source_address: u48,
    // 2 bytes
    ether_type: u16,
};

test "compiler crash" {
    const file = try std.fs.cwd().openFile("repro.zig", .{});
    const reader = file.reader();
    while (reader.readBytesNoEof(@bitSizeOf(EthernetHeader) / 8)) |ethernet_header_bytes| {
        // this line causes crash
        const ethernet_header = std.mem.bytesAsValue(EthernetHeader, ethernet_header_bytes);
        std.log.info("{}", .{ethernet_header});
    } else |_| {
        return;
    }
}
```

2. run .`/zig test repro.zig --zig-lib-dir ./lib`

### Expected Behavior

File compiles and test runs to completion.

### Actual Behavior

- zig.exe has stopped working

### Notes:

confirmed that crash also happens if I use `bytesToValue`

**Comment by Vexu** [comment] 2022-10-25 15:28
Fixed by #13017 so this is a duplicate of one of the linked issues.

**Closed by Vexu** 2022-10-25 15:28 UTC
Labels: bug
