### ISSUE TITLE
Odd error when using `BoundedArray` at comptime, but not runtime due to `@memcpy`

### ISSUE THREAD

**Issue by euclidianAce** [ziglang/zig#15633] opened 2023-05-09 17:12 UTC
### Zig Version

0.11.0-dev.3031+f40539e5d

### Steps to Reproduce and Observed Behavior

run the following `tmp.zig`

```zig
pub fn main() anyerror!void {
    std.log.info("{}", .{array});
}

const array = blk: {
    var b = std.BoundedArray(u8, 8){};
    b.appendSlice("hello") catch unreachable;
    break :blk b;
};

const std = @import("std");
```

which produces the following error:
```
$ zig run tmp.zig
zig-0.11.0-dev/lib/std/bounded_array.zig:248:13: error: element access of non-indexable type 'u8'
            @memcpy(self.slice()[old_len..][0..items.len], items);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zig-0.11.0-dev/lib/std/bounded_array.zig:240:43: note: called from here
            self.appendSliceAssumeCapacity(items);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
tmp.zig:7:18: note: called from here
    b.appendSlice("hello") catch unreachable;
    ~~~~~~~~~~~~~^~~~~~~~~
```

but moving the `comptime` block inside of `main` is fine:

```zig
pub fn main() anyerror!void {
    const array = blk: {
        var b = std.BoundedArray(u8, 8){};
        b.appendSlice("hello") catch unreachable;
        break :blk b;
    };

    std.log.info("{}", .{array});
}

const std = @import("std");
```

```
$ zig run tmp.zig
info: bounded_array.BoundedArrayAligned(u8,1,8){ .buffer = { 104, 101, 108, 108, 111, 0, 0, 0 }, .len = 5 }
```

### Expected Behavior

The code at compile time to produce the correct value without erroring

**Comment by jacobly0** [comment] 2023-05-12 19:44
Unrelated to the bug, but `b.appendSliceAssumeCapacity("hello");` is the usual way to assert that it can't overflow.

**Comment by Vexu** [comment] 2023-05-13 09:47
Duplicate of #15634

**Comment by Vexu** [comment] 2023-05-14 12:03
Sorry, not a duplicate, didn't notice the slice.

**Closed** 2023-05-16 05:39 UTC
Labels: bug
