### ISSUE TITLE
Failing test suite with 0.4.0 release on MacOS

### ISSUE THREAD

**Issue by cubranic** [ziglang/zig#2421] opened 2019-05-03 19:21 UTC
WIth Zig 0.4.0 built from source on macOS 10.14.4 (Mojave), I get the following error when running `bin/zig build --build-file ../build.zig test -Dskip-release`:
```
Assertion failed: ((uint64_t)loc % alignof(T) == 0 && "invalid pointer alignment"), function read64, file /Users/davor/projects/ziggly/zig/deps/lld/lib/ReaderWriter/MachO/MachONormalizedFileBinaryUtils.h, line 86.
The following command terminated unexpectedly:
/Users/davor/projects/ziggly/zig/build/bin/zig test /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/foo.zig --object /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/zig-cache/o/SUe_YiPh1_Ew6fiegQeR8ME86r6PNe-adxCtuWf8bVaQx3w_6ftZmy4uax5-vaqd/libfoo.a --cache-dir /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/zig-cache --name test -isystem /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/zig-cache/o/SUe_YiPh1_Ew6fiegQeR8ME86r6PNe-adxCtuWf8bVaQx3w_6ftZmy4uax5-vaqd -isystem /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib
```
Is this a known failure, or a possible problem with my setup? There are 5,718 passing tests (counted by their printing "...OK").

**Comment by mikdusan** [comment] 2019-05-03 19:24
I have been getting this same failure on macOS 10.11, 10.13 and 10.14 against different versions of Xcode but haven't really investigated.

**Comment by andrewrk** [comment] 2019-05-03 19:54
Does the problem occur with master branch?

**Comment by mikdusan** [comment] 2019-05-03 20:10
> Does the problem occur with master branch?

yes. In fact I cannot recall ever having success runing full test on macOS. On linux, yes, I get good result. Off hand I'm thinking why does it work with CI builds? Primary diff is CI uses gcc8 to build zig's LLVM toolchain, I'm using Xcode-clang. If memory serves custom-clang also gave me same failure.

**Comment by andrewrk** [comment] 2019-05-03 20:26
Hmm. Unfortunately it works on my fully updated 10.14.4 macOS laptop as well so I cannot reproduce the issue. I need some help figuring out what's different about our systems.

**Comment by andrewrk** [comment] 2019-05-03 20:28
I will note the assertion is in LLD, the linker, which is [known to be problematic for the macOS target](https://ziglang.org/download/0.4.0/release-notes.html#macOSMach-O-Linker-Status).

**Comment by cubranic** [comment] 2019-05-03 20:43
Yes:
```
Assertion failed: ((uint64_t)loc % alignof(T) == 0 && "invalid pointer alignment"), function read64, file /Users/davor/projects/ziggly/zig/deps/lld/lib/ReaderWriter/MachO/MachONormalizedFileBinaryUtils.h, line 86.
The following command terminated unexpectedly:
/Users/davor/projects/ziggly/zig/build/bin/zig test /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/foo.zig --object /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/zig-cache/o/o5L8eEhBLQTVzmg8zEVN20-UmhYp5v753OP30PuJ2DNoJ9yIggEtSdicH4O2EYIN/libfoo.a --cache-dir /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/zig-cache --name test -isystem /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/zig-cache/o/o5L8eEhBLQTVzmg8zEVN20-UmhYp5v753OP30PuJ2DNoJ9yIggEtSdicH4O2EYIN -isystem /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib

Build failed. The following command failed:
/Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/zig-cache/o/gNZfNp5X8svdTkLz5e_tsmhdpqIG8PGIYsH7YPBHRb-djo-7VcgWzzatSmaieC2F/build /Users/davor/projects/ziggly/zig/build/bin/zig /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/zig-cache test
The following command exited with error code 1:
cd /Users/davor/projects/ziggly/zig && build/bin/zig build --build-file /Users/davor/projects/ziggly/zig/test/standalone/static_c_lib/build.zig test

Build failed. The following command failed:
/Users/davor/projects/ziggly/zig/zig-cache/o/XyKkE9WQu-rXGS9zS1-Rxpx3rC3ZOSwTSFWPWsbXSa31LnQ4upnkBLxBR6YPg2EW/build /Users/davor/projects/ziggly/zig/build/bin/zig /Users/davor/projects/ziggly/zig /Users/davor/projects/ziggly/zig/zig-cache test -Dskip-release
```

**Comment by mikdusan** [comment] 2019-05-03 20:52
ok I've reduced it down to this but have yet to find out why `-DCMAKE_BUILD_TYPE=Release` is a factor.

##### TEST FAILURE
```
cmake -G Ninja /Users/mike/project/zig/master -DCMAKE_INSTALL_PREFIX=/opt/zig -DCMAKE_PREFIX_PATH=/opt/llvm-8.0.0
```

##### TEST SUCCESS
```
cmake -G Ninja /Users/mike/project/zig/master -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/zig -DCMAKE_PREFIX_PATH=/opt/llvm-8.0.0
```

**Comment by cubranic** [comment] 2019-05-03 20:54
@andrewrk it sounds like our setups are very similar. Same OS version, and I also build with Homebrew. I used the exact directions from the README:

- Homebrew llvm@8
- cmake with -DCMAKE_PREFIX_PATH=/usr/local/Cellar/llvm/8.0.0

I'd be happy to dig in deeper to find differences between our two configurations.

**Comment by andrewrk** [comment] 2019-05-03 20:55
@mikdusan I can explain that one: `-DCMAKE_BUILD_TYPE=Release` disables asserts. This issue is about an assertion failure. The LLD code probably ends up working fine in practice even though it tripped an assertion failure.

**Comment by mikdusan** [comment] 2019-05-03 23:16
This looks to be a bug in lld. What's happening is the `.a` is loaded into `MemoryBuffer` and the managed buffer is not aligned. Then the usual pointer casting into `mach_header` which is offset-zero in the buffer. And the first field `magic` is 32-bit and lld code asserts with generic read functions this must be 4-byte aligned.

**Comment by kristate** [comment] 2019-05-04 16:52
Hi all -- I have a fix for this bug, but even after contributing much to the project most of my PRs have been rejected as of late, so I am less inclined to share it via this repo for fear of my authorship being stripped once again (see below). Please send me an email and I will try to share it.

I entered into this community in the hopes to share the dream with Andrew and become a member of the core team. My company and I have invested both time (currently the [5th largest contributor](https://github.com/ziglang/zig/graphs/contributors)) and money (over $3500 to Andrew via patreon and over $10,000 to new engineers on the project inside of our company) into this project, but I still have not been asked by Andrew to become a member.

What hurts the most is that on more than one occasion, Andrew has committed my patches in such a way where my authorship was stripped from the commit log. This has not been done to any other contributor. I hope the Andrew can see the light and hopefully change his ways. I don't feel comfortable sharing patches inside of this repo.

----

commit 2828a9695f088f5454f445fdd0544d805a33837b
Merge: dfbc063f 67bd45f0
Author: Andrew Kelley <andrew@ziglang.org>
Date:   Mon Feb 4 15:27:44 2019 -0500
    Merge branch 'kristate-zig-backport-std.mem.separate'

commit f44ce7836a2f1d29e4f4718d45d6dca3c44ed919
Merge: dfbc063f ff1b2889
Author: Andrew Kelley <andrew@ziglang.org>
Date:   Mon Feb 4 13:29:17 2019 -0500
    Merge branch 'zig-backport-std.mem.separate' of https://github.com/kristate/zig into kristate-zig-backport-std.mem.separate

**Comment by andrewrk** [comment] 2019-05-04 19:55
I'm not sure whether kristate understands how git works or not, but either way, he's already been warned about spreading false information about my character. I don't have time to deal with this, so he's perma-banned and I'm no longer accepting his donations. Zig is an ambitious project, and I have no tolerance for this kind of distracting nonsense along the way.

**Closed** 2019-05-27 23:25 UTC
Labels: bug, os-macos
