### ISSUE TITLE
clang diagnostics broken in release modes

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#17952] opened 2023-11-10 08:45 UTC
### Zig Version

0.12.0-dev.1571+03adafd80

### Steps to Reproduce and Observed Behavior

```c
int main() {
	int x = 0;
	float y = 1;
	float z = x & y;
}
```
`zig build-exe repro.c`
running this directly i get a compiler segfault, if using build.zig it says `error(compilation): error.InvalidAbbrevId: failed to parse clang diagnostics`
with a debug build of the compiler it works as presented in #17947

### Expected Behavior

successful diagnostic parsing and no segfault

**Comment by jacobly0** [comment] 2023-11-10 17:50
reduced:
```zig
const testing = @import("std").testing;

test "pass nested union with rls" {
    const Union = union(enum) {
        a: u32,
        b: union(enum) {
            c: u7,
            d: u3,
        },

        fn expectCEqual32(u: @This()) !void {
            try testing.expectEqual(@as(u7, 32), u.b.c);
        }
    };

    var c: u7 = 32;
    try Union.expectCEqual32(.{ .b = .{ .c = c } });
}
```
```
$ zig test repro.zig -ODebug
All 1 tests passed.
$ zig test repro.zig -OReleaseSafe
Test [1/1] test.pass nested union with rls... expected 32, found 0
Test [1/1] test.pass nested union with rls... FAIL (TestExpectedEqual)
lib/std/testing.zig:88:17: 0x20dbd7 in test.pass nested union with rls (test)
                return error.TestExpectedEqual;
                ^
repro.zig:12:13: 0x20dbdf in test.pass nested union with rls (test)
repro.zig:17:5: 0x20dbe7 in test.pass nested union with rls (test)
0 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
zig-cache/o/5553b48f14dbd00c1285a49dc1084c38/test
```

**Comment by jacobly0** [comment] 2023-11-10 19:50
Duplicate of #16392

**Closed by jacobly0** 2023-11-10 19:50 UTC
Labels: bug, backend-llvm
