### ISSUE TITLE
Docs of @cmpxchgWeak and @cmpxchgStrong are wrong

### ISSUE THREAD

**Issue by lassade** [ziglang/zig#20634] opened 2024-07-15 03:36 UTC
### Zig Version

master

### Steps to Reproduce and Observed Behavior

Hey in the @cmpxchgWeak https://ziglang.org/documentation/master/#cmpxchgWeak docs states: "... returning null if the current value is *NOT* the given expected value ..."

I put the *NOT* in highlight because the pseudo code in the same section is telling me otherwise: it should return null if the value is the expected value.

### Expected Behavior

@cmpxchgWeak and @cmpxchgStrong returns null if the value *IS* the expected value.

**Comment by xdBronch** [comment] 2024-07-15 06:57
duplicate of https://github.com/ziglang/zig/issues/19979

**Closed** 2024-07-15 07:51 UTC
Labels: docs
