### ISSUE TITLE
TailQueue functions missing from docs

### ISSUE THREAD

**Issue by chr-1x** [ziglang/zig#7434] opened 2020-12-13 20:11 UTC
A casual visitor to https://ziglang.org/documentation/master/std/#std;TailQueue might be fooled into thinking the type has no associated functions and that all manipulation is manual, since none of its associated functions are included in the documentation. (Also: the TailQueue(T).Node type linked on this page is a dead link).

I'm aware the current documentation generator has limitations based on active symbol analysis by the compiler, but the tests use these functions, so there's no reason they shouldn't be included in the docs as far as I can tell.

**Comment by chr-1x** [comment] 2020-12-13 20:15
Not a duplicate of https://github.com/ziglang/zig/issues/7054 as these functions do have doc comments

**Comment by andrewrk** [comment] 2021-01-03 06:20
duplicate of #7400

**Closed by andrewrk** 2021-01-03 06:20 UTC
