### ISSUE TITLE
Building with `Drelease-fast=true` causes extern C structs to contain garbage

### ISSUE THREAD

**Issue by AlxHnr** [ziglang/zig#14262] opened 2023-01-10 22:08 UTC
### Zig Version

0.11.0-dev.1253+fcee1bf99

### Steps to Reproduce and Observed Behavior

Self-contained testcase can be found here: https://github.com/AlxHnr/zig-compiler-testcase

Building the code with `zig build -Drelease-fast=true test` causes the tests to fail due to scrambled data. Building without optimizations (`zig build test`) works just fine.

Here is the offending code which you can find in the repo linked above.

```zig
const std = @import("std");

pub const Vector3 = extern struct {
    x: f32,
    y: f32,
    z: f32,
};

pub extern fn Vector3RotateByAxisAngle(v: Vector3, axis: Vector3, angle: f32) Vector3;

test {
    const vector = Vector3{ .x = 12, .y = 9, .z = 3 };
    const up = Vector3{ .x = 0, .y = 1, .z = 0 };
    const result = Vector3RotateByAxisAngle(vector, up, 0.001);

    try std.testing.expectApproxEqRel(@as(f32, 12.0029945), result.x, 0.00001);
    try std.testing.expectApproxEqRel(@as(f32, 9), result.y, 0.00001);
    try std.testing.expectApproxEqRel(@as(f32, 2.98799848), result.z, 0.00001);
}
```

### Expected Behavior

Optimized release builds behave the same as debug builds.

### More informations

Platform: Fedora Linux 36

This seems to be a regression of https://github.com/ziglang/zig/issues/1481. There it claims the following:

> [X] x86_64: struct & union parameters <= 16 bytes which are all floats

**Comment by Vexu** [comment] 2023-01-11 13:12
Likely duplicate of #13830

**Closed by Vexu** 2023-01-11 13:12 UTC
Labels: bug

**Comment by AlxHnr** [comment] 2023-01-11 20:23
Can we be sure it is f32 specific? This behavior doesn't occur with larger structs containing 4, 6, 7 or 16 floats.

**Comment by Vexu** [comment] 2023-01-11 20:29
It's not f32 specific but caused by alignment differences between f32 and f64. The failure only happens on release modes because LLVM sees that we're doing sketchy stuff and goes to town on removing instructions.
