### ISSUE TITLE
Pointer to global variable of zero bit type cannot be mutable

### ISSUE THREAD

**Issue by ieeemma** [ziglang/zig#12843] opened 2022-09-14 21:39 UTC
### Zig Version

0.10.0-dev.4060+61aaef0b0

### Steps to Reproduce

```zig
var x = {};

fn foo(_: *void) void { }

pub fn main() void { foo(&x); }
```

### Expected Behavior

The compiler should accept this code.

### Actual Behavior

The value `&x` has the type `*const void`, when it should have type `*void`, so it cannot be passed to `foo`. Moving `x` to be a local variable fixes this.

**Comment by Vexu** [comment] 2022-09-14 21:42
Duplicate of #12275

**Closed by Vexu** 2022-09-14 21:42 UTC
Labels: bug
