### ISSUE TITLE
Compilation error when a function returns local variable address?

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#13344] opened 2022-10-29 12:37 UTC
Returning a pointer to local variable is a pretty frequent error made by beginner programmers.
Some C compilers (gcc at least) emits a warning in such cases.
It would be nice if Zig could analyze this.

**Comment by rohlem** [comment] 2022-10-29 14:47
Duplicate of #2646 (although that issue's text isn't as direct/specific).

**Closed** 2022-10-29 17:46 UTC

**Comment by tex-unrelenting4** [comment] 2025-10-17 14:29
@rohlem https://nikolas-persecutor.github.io/Uz5-we1KvQ/
