### ISSUE TITLE
Recursive function cause compiler freeze

### ISSUE THREAD

**Issue by hwoy** [ziglang/zig#14246] opened 2023-01-09 00:59 UTC
### Zig Version

0.10

### Steps to Reproduce and Observed Behavior

```Zig
const std = @import("std");

fn find(comptime t: type, arr: []const t, f: anytype) ?*const t {
    return switch (arr.len) {
        0 => null,
        1 => &arr[0],
        else => blk: {
            const r = find(t, arr[1..], f) orelse break :blk null;
            break :blk if (f.call(r, &arr[0])) r else &arr[0];
        },
    };
}

pub fn main() !void {
    const arr: []const i32 = &[_]i32{ 5, 7, 8, 9, 1, 3 };
    const r = find(i32, arr, struct {
        fn call(a: anytype, b: @TypeOf(a)) bool {
            return a.* < b.*;
        }
    });
    const w = std.io.getStdOut().writer();
    try w.print("{}\n", .{r.?.*});
}

```

```
zig x86_64 windows
```
```
zig build-exe z.zig
Semantic Analysis [1418] max3...
```

### Expected Behavior

Compiler not freeze

**Comment by Vexu** [comment] 2023-01-09 14:25
Duplicate of #13380 (or at least fails in the same way as one of the examples there)

**Comment by hwoy** [comment] 2023-01-10 03:07
```Zig
const std = @import("std");

const Closure = struct {
    const Self=@This();
    fn call(_:Self,a: anytype, b: @TypeOf(a)) bool {
        return a.* < b.*;
    }
};

fn find(comptime t: type, arr: []const t, f: anytype) ?*const t {
    return switch (arr.len) {
        0 => null,
        1 => &arr[0],
        else => blk: {
            const r = find(t, arr[1..], f) orelse break :blk null;
            break :blk if (f.call(r, &arr[0])) r else &arr[0];
        },
    };
}

pub fn main() !void {
    const arr: []const i32 = &[_]i32{ 5, 7, 8, 9, 1, 3 };
    const r = find(i32, arr, Closure{});
    const w = std.io.getStdOut().writer();
    try w.print("{}\n", .{r.?.*});
}


```

```
Compile successfully
Suggestion: this issue is about anytype and anonymous struct.
Everytime when pass anonymous struct to anytype, A new type of anoymous struct is created. Lead to new function generics instantiation.
```

**Comment by Vexu** [comment] 2023-11-05 22:17
Fixed in master.

**Closed by Vexu** 2023-11-05 22:17 UTC
Labels: bug
