### ISSUE TITLE
Unreachable in analyze.cpp:7329 in const_values_equal

### ISSUE THREAD

**Issue by wtrmute** [ziglang/zig#10477] opened 2021-12-31 23:48 UTC
### Zig Version

0.9.0

### Steps to Reproduce

[bug.txt](https://github.com/ziglang/zig/files/7797214/bug.txt)

Hello,

I was writing a set of objects for PDF creation (the "bug.txt" file attached is actually the `object.zig` source file I was writing) when I came to implement the `Array` type, which suddenly becomes recursive on the `format` function (since it must write out its children). I got an error saying the compiler couldn't infer the error set, so I wrote a small `ErrorSetOfFunction` function to get the error set of the `writer` parameter. Then I annotated the return of `array_escape` with `ErrorSetOfFunction(writer.write)|void` and ran `zig test src\object.zig`.

### Expected Behavior

The completion of the compilation, whatever it would be.

### Actual Behavior

I got the following message:

```
> zig test src\object.zig
Semantic Analysis [159/864] Unreachable at /home/andy/dev/bootstrap-zig/zig/src/stage1/analyze.cpp:7329 in const_values_equal. This is a bug in the Zig compiler.thread 12420 panic:
Unable to dump stack trace: debug info stripped
```
I would probably not have posted this bug if the compiler itself did not confidently assert it is a compiler bug, so in the interest of making the compiler more robust, if the self-hosted doesn't solve the problem.

**Comment by Vexu** [comment] 2022-01-09 10:05
The issue is caused by `BoundFn` being buggy which is being fixed by removing them from the language #9484.

You can work around the issue by using the standard way of getting a writer's error set with `@TypeOf(writer).Error`.

**Closed** 2022-12-10 11:15 UTC
Labels: bug, stage1
