### ISSUE TITLE
LibC errors when adding C source to shared library

### ISSUE THREAD

**Issue by tonymarklove** [ziglang/zig#5842] opened 2020-07-10 21:19 UTC
I'm getting some confusing behaviour when trying to compiler some C source code into a DLL on Windows.

It's quite possible I'm completly misunderstanding something, but here's what I've got:

```zig
# build.zig
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void {
    const lib = b.addSharedLibrary("test", "src/main.zig", b.version(0, 0, 1));
    lib.addCSourceFile("src/test.c", &[_][]const u8{"--std=c99"});
    lib.linkLibC();
    lib.install();
}
```

With the above build file, even with an empty `main.zig` and `test.c` I get a bunch of errors like:
```
lld: error: undefined symbol: __security_cookie
>>> referenced by D:\Code\zig\lib\zig\std\heap.zig:184
>>>               D:\Users\Tony Marklove\Desktop\zig\test\zig-cache\o\hm9pNpFAX8NY3hbqRRqN3ewjy76h-1S7yPUNtSu9HBb_svrNxhDd4eCP4jE3mXRY\test.obj:(std.heap.PageAllocator.realloc)

lld: error: undefined symbol: memcpy
>>> referenced by D:\Code\zig\lib\zig\std\heap.zig:204
>>>               D:\Users\Tony Marklove\Desktop\zig\test\zig-cache\o\hm9pNpFAX8NY3hbqRRqN3ewjy76h-1S7yPUNtSu9HBb_svrNxhDd4eCP4jE3mXRY\test.obj:(std.heap.PageAllocator.realloc)
```

Removing `lib.linkLibC();` will allow the code to compile, but then adding `#include <math.h>` into the C file results in a `math.h not found` error.

If I change `addSharedLibrary` to `addExecutable` everything works as expected.

**Comment by michal-z** [comment] 2020-07-10 23:12
Have you tried lib.linkSystemLibrary("c"); ?

**Comment by wozeparrot** [comment] 2020-07-11 02:21
iirc, `linkSystemLibrary("c")` calls `linkLibC()`.

**Comment by tonymarklove** [comment] 2020-07-11 09:27
Yeah, I did try `linkSystemLibrary("c")` as well, with the same result. As @wozeparrot says, it ends up calling `linkLibC()` internally anyway.

I'm guessing it's something like the wrong version of the native libc library is getting linked? Maybe the DLL rather than the static library? But I'm not sure how to debug exactly what's getting linked.

**Comment by FireFox317** [comment] 2020-07-11 09:35
Yeah, I've experienced this issue before. This use case should be solved.
Internally a DLL is handled quite differently than a EXE, however they should probably share some more codepaths, because a DLL on Windows is quite similar to a EXE, IIRC

**Comment by tonymarklove** [comment] 2020-07-12 20:10
I have now also tried the same code on OSX, and the dylib is built successfully. So it looks like something Windows specific is causing the problem.

If anyone has any hint where I should start looking I would be happy to try to dig into what's going on.

**Comment by Sobeston** [comment] 2020-07-14 18:59
Duplicate of #5748?

**Comment by tonymarklove** [comment] 2020-07-14 20:56
Yes, definitely a duplicate of #5748. My proposed solution over in #5870 is very similar to the one in that issue. The only difference being that it only forces the linking of CRT for DLLs on Windows, not all libraries.

**Closed** 2020-07-15 14:08 UTC
Labels: bug, os-windows
