### ISSUE TITLE
Coerce single item pointers to slices

### ISSUE THREAD

**Issue by BarabasGitHub** [ziglang/zig#6391] opened 2020-09-21 17:07 UTC
To get a length 1 slice from a single item pointer today you have to do something like:
```
@ptrCast([*]u64, &number)[0..1]
```
Which is not the end of the world, but it feels like taking the long way around. Plus it goes via an unsafe path. That is, you can also do:
```
@ptrCast([*]u64, &number)[0..10]
```
And nothing will complain.

Since a single item pointer is not all that different from a single item array, I'd propose to allow:
```
@as([]u64, &number)
```
Or something similar. 
Another option is to implement this in the `std.mem.span` function.

**Comment by Vexu** [comment] 2020-09-21 17:19
Duplicate of #3156, also see #5912 and  #5626.

**Closed by Vexu** 2020-09-21 17:19 UTC

**Comment by BarabasGitHub** [comment] 2020-09-21 17:24
Thanks. I tried looking if it already existed, but the search didn't turn up anything relevant on the first page.
