### ISSUE TITLE
bootstrap.zig:131 expression value is ignored on catch

### ISSUE THREAD

**Issue by SamTebbs33** [ziglang/zig#2721] opened 2019-06-20 22:13 UTC
While investigating #2662, I found that the compiler emits an error when building the following code.

```
const Err = error {
    Foo
};

fn err_fn() !void {
    return Err.Foo;
}

pub fn main() !u8 {
    try err_fn();
    return 0;
}
```
```
/home/sam/repos/zig/build/lib/zig/std/special/bootstrap.zig:131:25: error: expression value is ignored
            root.main() catch |err| {
```
This could be a duplicate of #2662 but that issue seems to be more of a feature request rather than a bug report.

**Comment by tiehuis** [comment] 2019-06-20 22:28
Looks like the error union case in `callMain` is a too lenient and doesn't explicitly check the return value is `!void`, rather it just assumes it is. This can be fixed alongside #2662 when it is implemented.

**Comment by andrewrk** [comment] 2019-06-27 04:25
I'm going to call this a duplicate of #2662. Until that is solved, this compile error is what you get for using an unsupported return type of `main()`.

**Closed by andrewrk** 2019-06-27 04:25 UTC

**Comment by SamTebbs33** [comment] 2019-06-27 06:50
@andrewrk there is a PR open that addresses this issue and #2622
