### ISSUE TITLE
compiler panic after probably incorrect "must be declared comptime" argument

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#13829] opened 2022-12-08 20:35 UTC
### Zig Version

0.11.0-dev.635+225ed65ed

### Steps to Reproduce and Observed Behavior

updated to latest, got an error in similar code as in #13823

repro:
1. `gh repo clone oven-sh/bun -- --branch=jarred/attempt-upgrade`
2. `zig build obj --debug-compiler-errors`

stdout/stderr:
```zig
Console is in 'commands' mode, prefix expressions with '?'.
Launching: /home/ubuntu/zig/stage3/bin/zig build-obj /home/ubuntu/code/bun/src/main.zig -lc -fno-strip --eh-frame-hdr --emit-relocs -ffunction-sections --cache-dir /home/ubuntu/code/bun/zig-cache --global-cache-dir /home/ubuntu/.cache/zig --name bun-debug -fcompiler-rt -fno-omit-frame-pointer -target native-native-gnu.2.27 -mcpu haswell --pkg-begin async_io /home/ubuntu/code/bun/src/io/io_linux.zig --pkg-begin bun /home/ubuntu/code/bun/src/bun_redirect.zig --pkg-end --pkg-end --pkg-begin javascript_core /home/ubuntu/code/bun/src/jsc.zig --pkg-begin bun /home/ubuntu/code/bun/src/bun_redirect.zig --pkg-end --pkg-end --pkg-begin bun /home/ubuntu/code/bun/src/bun_redirect.zig --pkg-end --pkg-begin build_options /home/ubuntu/code/bun/zig-cache/options/-qetKSq8EGLkR9LYhajN4uc55G_HX6z2II7dMrY0CwFe0NvbMfn3MSNu6FdWG5ah --pkg-end -I /home/ubuntu/code/bun/src/deps -I /home/ubuntu/code/bun/src/deps --main-pkg-path /home/ubuntu/code/bun --enable-cache --debug-compile-errors
Launched process 592188
AST Lowering [330] math/big/rational.zig... [44D[0KAST Lowering [418] crypto/utils.zig... [39D[0KAST Lowering [496] os/uefi/protocols/shell_parameters_protocol.zig... [70D[0KAST Lowering [541] crypto/pcurves/common.zig... [48D[0KAST Lowering [569] base64.zig... [33D[0KAST Lowering [614] atomic/stack.zig... [39D[0KAST Lowering [644] target/spirv.zig... [39D[0KAST Lowering [672] [19D[0KSemantic Analysis [139] usingnamespace_0... [44D[0KSemantic Analysis [411] HashMapUnmanaged... [44D[0KSemantic Analysis [644] finished... [36D[0KSemantic Analysis [896] [24D[0KSemantic Analysis [975] appendAssumeCapacity... [48D[0KSemantic Analysis [978] scanIdentifierWithEscapes... [53D[0KSemantic Analysis [1005] mergeExternal... [42D[0KSemantic Analysis [1017] isWhitespace... [41D[0KSemantic Analysis [1085] deinit... [35D[0KSemantic Analysis [1198] len... compile error during Sema:
src/js_printer.zig:4625:13: error: parameter of type 'src.js_printer.Options' must be declared comptime
            opts: Options,

thread 592188 panic: unexpected compile error occurred
Analyzing src/js_printer.zig: src/js_printer.zig:NewPrinter(false,src.js_printer.NewWriter(src.js_printer.FileWriterInternal,(function 'writeByte'),(function 'writeAll'),(function 'getLastByte'),(function 'getLastLastByte'),(function 'reserveNext'),(function 'advanceBy')),void,false,false,false,true,false).init
      %32104 = param("writer", {
        %32102 = closure_get(%3279) node_offset:4621:21 to :4621:27
        %32103 = break_inline(%32104, %32102)
      }) token_offset:4621:13 to :4621:19
      %32108 = param("tree", {
        %32105 = decl_val("Ast") token_offset:4622:26 to :4622:29
        %32106 = ptr_type(%32105, const, One) node_offset:4622:19 to :4622:29
        %32107 = break_inline(%32108, %32106)
      }) token_offset:4622:13 to :4622:17
      %32113 = param("source", {
        %32109 = decl_val("logger") token_offset:4623:28 to :4623:34
        %32110 = field_val(%32109, "Source") node_offset:4623:28 to :4623:41
        %32111 = ptr_type(%32110, const, One) node_offset:4623:21 to :4623:41
        %32112 = break_inline(%32113, %32111)
      }) token_offset:4623:13 to :4623:19
      %32117 = param("symbols", {
        %32114 = decl_val("Symbol") token_offset:4624:22 to :4624:28
        %32115 = field_val(%32114, "Map") node_offset:4624:22 to :4624:32
        %32116 = break_inline(%32117, %32115)
      }) token_offset:4624:13 to :4624:20
      %32120 = param("opts", {
        %32118 = decl_val("Options") token_offset:4625:19 to :4625:26
        %32119 = break_inline(%32120, %32118)
      }) token_offset:4625:13 to :4625:17
      %32125 = param("linker", {
        %32121 = closure_get(%3245) node_offset:4626:23 to :4626:29
        %32122 = ptr_type(%32121, One) node_offset:4626:22 to :4626:29
        %32123 = optional_type(%32122) node_offset:4626:21 to :4626:29
        %32124 = break_inline(%32125, %32123)
      }) token_offset:4626:13 to :4626:19
      %32130 = param("allocator", {
        %32126 = decl_val("std") token_offset:4627:24 to :4627:27
        %32127 = field_val(%32126, "mem") node_offset:4627:24 to :4627:31
        %32128 = field_val(%32127, "Allocator") node_offset:4627:24 to :4627:41
        %32129 = break_inline(%32130, %32128)
      }) token_offset:4627:13 to :4627:22
    > %32286 = func_inferred(ret_ty={
        %32131 = decl_val("Printer") token_offset:4628:12 to :4628:19
        %32132 = break_inline(%32286, %32131)
      }, inferror, body={
        %32133 = block({
          %32134 = dbg_block_begin()
          %32135 = dbg_stmt(10, 17)
          %32139 = block({
            %32136 = decl_val("imported_module_ids_list_unset") token_offset:4629:17 to :4629:47
            %32137 = as_node(@Zir.Inst.Ref.bool_type, %32136) node_offset:4629:17 to :4629:47
            %32138 = condbr(%32137, {
              %32140 = dbg_block_begin()
              %32165 = dbg_block_end()
              %32141 = block({
                %32142 = dbg_block_begin()
                %32143 = dbg_stmt(11, 17)
                %32144 = decl_ref("imported_module_ids_list") token_offset:4630:17 to :4630:41
                %32145 = decl_ref("std") token_offset:4630:44 to :4630:47
                %32146 = dbg_stmt(11, 47)
                %32147 = field_call_bind(%32145, "ArrayList") node_offset:4630:44 to :4630:57
                %32148 = dbg_stmt(11, 57)
                %32149 = call(.auto, %32147, [
                  {
                    %32150 = break_inline(%32149, @Zir.Inst.Ref.u32_type)
                  },
                ]) node_offset:4630:44 to :4630:62
                %32151 = ref(%32149) token_offset:4630:44 to :4630:47
                %32152 = dbg_stmt(11, 62)
                %32153 = field_call_bind(%32151, "init") node_offset:4630:44 to :4630:67
                %32154 = dbg_stmt(11, 67)
                %32155 = call(.auto, %32153, [
                  {
                    %32156 = decl_val("default_allocator") token_offset:4630:68 to :4630:85
                    %32157 = break_inline(%32155, %32156)
                  },
                ]) node_offset:4630:44 to :4630:86
                %32158 = store_node(%32144, %32155) node_offset:4630:17 to :4630:86
                %32159 = dbg_stmt(12, 17)
                %32160 = decl_ref("imported_module_ids_list_unset") token_offset:4631:17 to :4631:47
                %32162 = dbg_block_end()
                %32161 = store_node(%32160, @Zir.Inst.Ref.bool_false) node_offset:4631:17 to :4631:55
                %32163 = restore_err_ret_index(%32141, @Zir.Inst.Ref.none)
                %32164 = break(%32141, @Zir.Inst.Ref.void_value)
              }) node_offset:4629:49 to :4629:50
              %32166 = break(%32139, @Zir.Inst.Ref.void_value)
            }, {
              %32167 = break(%32139, @Zir.Inst.Ref.void_value)
            }) node_offset:4629:13 to :4629:15
          }) node_offset:4629:13 to :4629:15
          %32168 = ensure_result_used(%32139) node_offset:4629:13 to :4629:15
          %32169 = dbg_stmt(15, 13)
          %32170 = decl_ref("imported_module_ids_list") token_offset:4634:13 to :4634:37
          %32171 = dbg_stmt(15, 37)
          %32172 = field_call_bind(%32170, "clearRetainingCapacity") node_offset:4634:13 to :4634:60
          %32173 = dbg_stmt(15, 60)
          %32174 = call(nodiscard .auto, %32172, []) node_offset:4634:13 to :4634:62
          %32175 = dbg_stmt(17, 13)
          %32176 = decl_val("SourceMap") token_offset:4636:37 to :4636:46
          %32177 = field_val(%32176, "Chunk") node_offset:4636:37 to :4636:52
          %32178 = field_val(%32177, "Builder") node_offset:4636:37 to :4636:60
          %32179 = alloc_mut(%32178) node_offset:4636:13 to :4636:72
          %32180 = store_node(%32179, @Zir.Inst.Ref.undef) node_offset:4636:63 to :4636:72
          %32181 = dbg_var_ptr(%32179, "source_map_builder")
          %32182 = dbg_stmt(19, 17)
          %32186 = block({
            %32183 = closure_get(%5342) node_offset:4638:26 to :4638:45
            %32184 = as_node(@Zir.Inst.Ref.bool_type, %32183) node_offset:4638:26 to :4638:45
            %32185 = condbr(%32184, {
              %32187 = dbg_block_begin()
              %32241 = dbg_block_end()
              %32188 = block({
                %32189 = dbg_block_begin()
                %32190 = dbg_stmt(20, 17)
                %32191 = decl_val("SourceMap") token_offset:4639:38 to :4639:47
                %32192 = field_val(%32191, "Chunk") node_offset:4639:38 to :4639:53
                %32193 = field_val(%32192, "Builder") node_offset:4639:38 to :4639:61
                %32194 = validate_struct_init_ty(%32193) node_offset:4639:38 to :4639:62
                %32195 = coerce_result_ptr(%32193, %32179) node_offset:4639:38 to :4639:62
                %32196 = field_ptr_init(%32195, "source_map") node_offset:4640:35 to :4640:104
                %32197 = decl_ref("SourceMap") token_offset:4640:35 to :4640:44
                %32198 = dbg_stmt(21, 44)
                %32199 = field_ptr(%32197, "Chunk") node_offset:4640:35 to :4640:50
                %32200 = dbg_stmt(21, 50)
                %32201 = field_ptr(%32199, "Builder") node_offset:4640:35 to :4640:58
                %32202 = dbg_stmt(21, 58)
                %32203 = field_ptr(%32201, "SourceMapper") node_offset:4640:35 to :4640:71
                %32204 = dbg_stmt(21, 71)
                %32205 = field_call_bind(%32203, "init") node_offset:4640:35 to :4640:76
                %32206 = dbg_stmt(21, 76)
                %32207 = call(.auto, %32205, [
                  {
                    %32208 = break_inline(%32207, %32130)
                  },
                  {
                    %32209 = closure_get(%3832) node_offset:4640:88 to :4640:103
                    %32210 = break_inline(%32207, %32209)
                  },
                ]) node_offset:4640:35 to :4640:104
                %32211 = store_node(%32196, %32207) node_offset:4640:35 to :4640:104
                %32212 = field_ptr_init(%32195, "cover_lines_without_mappings") node_offset:4641:53 to :4641:57
                %32213 = store_node(%32212, @Zir.Inst.Ref.bool_true) node_offset:4641:53 to :4641:57
                %32214 = field_ptr_init(%32195, "prepend_count") node_offset:4642:38 to :4642:53
                %32215 = closure_get(%3832) node_offset:4642:38 to :4642:53
                %32216 = store_node(%32214, %32215) node_offset:4642:38 to :4642:53
                %32217 = validate_struct_init({
                  %32196 = field_ptr_init(%32195, "source_map") node_offset:4640:35 to :4640:104
                  %32212 = field_ptr_init(%32195, "cover_lines_without_mappings") node_offset:4641:53 to :4641:57
                  %32214 = field_ptr_init(%32195, "prepend_count") node_offset:4642:38 to :4642:53
                }) node_offset:4639:38 to :4639:62
                %32218 = dbg_stmt(25, 17)
                %32219 = dbg_stmt(25, 35)
                %32220 = field_ptr(%32179, "line_offset_tables") node_offset:4644:17 to :4644:54
                %32221 = decl_ref("SourceMap") token_offset:4644:57 to :4644:66
                %32222 = dbg_stmt(25, 66)
                %32223 = field_ptr(%32221, "LineOffsetTable") node_offset:4644:57 to :4644:82
                %32224 = dbg_stmt(25, 82)
                %32225 = field_call_bind(%32223, "generate") node_offset:4644:57 to :4644:91
                %32226 = dbg_stmt(25, 91)
                %32227 = call(.auto, %32225, [
                  {
                    %32228 = break_inline(%32227, %32130)
                  },
                  {
                    %32229 = dbg_stmt(25, 109)
                    %32230 = field_val(%32113, "contents") node_offset:4644:103 to :4644:118
                    %32231 = break_inline(%32227, %32230)
                  },
                  {
                    %32232 = dbg_stmt(25, 120)
                    %32233 = dbg_stmt(25, 138)
                    %32234 = field_val(%32108, "approximate_newline_count") node_offset:4644:134 to :4644:164
                    %32235 = int_cast(@Zir.Inst.Ref.i32_type, %32234) node_offset:4644:120 to :4644:165
                    %32236 = break_inline(%32227, %32235)
                  },
                ]) node_offset:4644:57 to :4644:166
                %32238 = dbg_block_end()
                %32237 = store_node(%32220, %32227) node_offset:4644:17 to :4644:166
                %32239 = restore_err_ret_index(%32188, @Zir.Inst.Ref.none)
                %32240 = break(%32188, @Zir.Inst.Ref.void_value)
              }) node_offset:4638:47 to :4638:48
              %32242 = break(%32186, @Zir.Inst.Ref.void_value)
            }, {
              %32243 = break(%32186, @Zir.Inst.Ref.void_value)
            }) node_offset:4638:13 to :4638:15
          }) node_offset:4638:13 to :4638:15
          %32244 = ensure_result_used(%32186) node_offset:4638:13 to :4638:15
          %32245 = dbg_stmt(28, 13)
          %32246 = ret_ptr() node_offset:4647:13 to :4647:19
          %32247 = decl_val("Printer") token_offset:4647:20 to :4647:27
          %32248 = validate_struct_init_ty(%32247) node_offset:4647:20 to :4647:28
          %32249 = coerce_result_ptr(%32247, %32246) node_offset:4647:20 to :4647:28
          %32250 = field_ptr_init(%32249, "import_records") node_offset:4648:35 to :4648:54
          %32251 = dbg_stmt(29, 39)
          %32252 = field_val(%32108, "import_records") node_offset:4648:35 to :4648:54
          %32253 = store_node(%32250, %32252) node_offset:4648:35 to :4648:54
          %32254 = field_ptr_init(%32249, "options") node_offset:4649:28 to :4649:32
          %32255 = store_node(%32254, %32120) node_offset:4649:28 to :4649:32
          %32256 = field_ptr_init(%32249, "symbols") node_offset:4650:28 to :4650:35
          %32257 = store_node(%32256, %32117) node_offset:4650:28 to :4650:35
          %32258 = field_ptr_init(%32249, "writer") node_offset:4651:27 to :4651:33
          %32259 = store_node(%32258, %32104) node_offset:4651:27 to :4651:33
          %32260 = field_ptr_init(%32249, "linker") node_offset:4652:27 to :4652:33
          %32261 = store_node(%32260, %32125) node_offset:4652:27 to :4652:33
          %32262 = field_ptr_init(%32249, "imported_module_ids") node_offset:4653:40 to :4653:64
          %32263 = decl_val("imported_module_ids_list") token_offset:4653:40 to :4653:64
          %32264 = store_node(%32262, %32263) node_offset:4653:40 to :4653:64
          %32265 = field_ptr_init(%32249, "renamer") node_offset:4654:28 to :4654:64
          %32266 = decl_ref("rename") token_offset:4654:28 to :4654:34
          %32267 = dbg_stmt(35, 34)
          %32268 = field_ptr(%32266, "Renamer") node_offset:4654:28 to :4654:42
          %32269 = dbg_stmt(35, 42)
          %32270 = field_call_bind(%32268, "init") node_offset:4654:28 to :4654:47
          %32271 = dbg_stmt(35, 47)
          %32272 = call(.auto, %32270, [
            {
              %32273 = break_inline(%32272, %32117)
            },
            {
              %32274 = break_inline(%32272, %32113)
            },
          ]) node_offset:4654:28 to :4654:64
          %32275 = store_node(%32265, %32272) node_offset:4654:28 to :4654:64
          %32276 = field_ptr_init(%32249, "source_map_builder") node_offset:4655:39 to :4655:57
          %32277 = load(%32179) node_offset:4655:39 to :4655:57
          %32278 = store_node(%32276, %32277) node_offset:4655:39 to :4655:57
          %32279 = validate_struct_init({
            %32250 = field_ptr_init(%32249, "import_records") node_offset:4648:35 to :4648:54
            %32254 = field_ptr_init(%32249, "options") node_offset:4649:28 to :4649:32
            %32256 = field_ptr_init(%32249, "symbols") node_offset:4650:28 to :4650:35
            %32258 = field_ptr_init(%32249, "writer") node_offset:4651:27 to :4651:33
            %32260 = field_ptr_init(%32249, "linker") node_offset:4652:27 to :4652:33
            %32262 = field_ptr_init(%32249, "imported_module_ids") node_offset:4653:40 to :4653:64
            %32265 = field_ptr_init(%32249, "renamer") node_offset:4654:28 to :4654:64
            %32276 = field_ptr_init(%32249, "source_map_builder") node_offset:4655:39 to :4655:57
          }) node_offset:4647:20 to :4647:28
          %32280 = restore_err_ret_index(@Zir.Inst.Ref.none, @Zir.Inst.Ref.none)
          %32281 = dbg_stmt(28, 13)
          %32283 = dbg_block_end()
          %32282 = ret_load(%32246) node_offset:4647:13 to :4647:19
        }) node_offset:4628:20 to :4628:21
        %32284 = restore_err_ret_index(@Zir.Inst.Ref.none, @Zir.Inst.Ref.none)
        %32285 = ret_implicit(@Zir.Inst.Ref.void_value) token_offset:4657:9 to :4657:10
      }) (lbrace=9:20,rbrace=38:9) node_offset:4620:9 to :4620:15
      %32287 = break_inline(%32101, %32286)
    For full context, use the command
      zig ast-check -t src/js_printer.zig

  in src/js_printer.zig: src/js_printer.zig:printJSON__anon_11281
    > %35220 = field_call_bind(%35218, "init") node_offset:5106:23 to :5106:39
  in src/js_printer.zig: src/js_printer.zig:printJSON__anon_11281
    > %35124 = block({%35125..%35323}) node_offset:5096:10 to :5096:11
  in src/cli/init_command.zig: src/cli/init_command.zig:InitCommand.exec
    > %2147 = is_non_err(%2109) node_offset:309:15 to :309:20
  in src/cli/init_command.zig: src/cli/init_command.zig:InitCommand.exec
    > %2149 = block({%2105..%2148}) node_offset:309:15 to :309:20
  in src/cli/init_command.zig: src/cli/init_command.zig:InitCommand.exec
    > %2051 = block({%2052..%2217}) node_offset:298:9 to :298:30
  in src/cli/init_command.zig: src/cli/init_command.zig:InitCommand.exec
    > %616 = block({%617..%2904}) node_offset:101:66 to :101:67
  in src/cli.zig: src/cli.zig:Command.start
    > %6791 = try(%6783, {%6792..%6794}) node_offset:959:36 to :959:80
  in src/cli.zig: src/cli.zig:Command.start
    > %6728 = switch_block(%6725,
        else => {%6801..%6806},
        %6730 => {%6731..%6749},
        %6752 => {%6753..%6771},
        %6774 => {%6775..%6799}) node_offset:956:9 to :956:15
  in src/cli.zig: src/cli.zig:Command.start
    > %6714 = block({%6715..%9159}) node_offset:953:72 to :953:73
  in src/cli.zig: src/cli.zig:Cli.start__anon_3529
    > %304 = is_non_err(%300) node_offset:76:9 to :76:44
  in src/cli.zig: src/cli.zig:Cli.start__anon_3529
    > %306 = block({%296..%305}) node_offset:76:9 to :76:44
  in src/cli.zig: src/cli.zig:Cli.start__anon_3529
    > %249 = block({%250..%440}) node_offset:67:110 to :67:111
src/Sema.zig:2202:35: 0xabcfc1 in failWithOwnedErrorMsg (zig)
src/Sema.zig:8744:42: 0x1654c67 in analyzeParameter (zig)
src/Sema.zig:8435:62: 0x1306f52 in funcCommon (zig)
src/Sema.zig:8212:24: 0xece482 in zirFunc (zig)
src/Sema.zig:950:62: 0xc95543 in analyzeBodyInner (zig)
src/Sema.zig:815:45: 0xad0211 in analyzeBodyBreak (zig)
src/Module.zig:4635:50: 0xacc31f in semaDecl (zig)
src/Module.zig:4256:38: 0x949b99 in ensureDeclAnalyzed (zig)
src/Sema.zig:27544:32: 0x13367f2 in ensureDeclAnalyzed (zig)
src/Sema.zig:27586:32: 0xfa8cd1 in analyzeDeclRef (zig)
src/Sema.zig:27514:45: 0x12ff3c4 in analyzeDeclVal (zig)
src/Sema.zig:23164:35: 0x165193a in namespaceLookupVal (zig)
src/Sema.zig:22678:56: 0x1302e2f in fieldVal (zig)
src/Sema.zig:22997:37: 0x1304a15 in fieldCallBind (zig)
src/Sema.zig:9007:30: 0xecd9e7 in zirFieldCallBind (zig)
src/Sema.zig:948:71: 0xc9537e in analyzeBodyInner (zig)
src/Sema.zig:5240:34: 0x13309c9 in resolveBlockBody (zig)
src/Sema.zig:5223:85: 0xf8598c in zirBlock (zig)
src/Sema.zig:1449:69: 0xca2bf1 in analyzeBodyInner (zig)
src/Sema.zig:798:30: 0xe77258 in analyzeBody (zig)
src/Module.zig:5659:43: 0xc7593a in analyzeFnBody (zig)
src/Module.zig:4342:40: 0xaaf7ed in ensureFuncBodyAnalyzed (zig)
src/Sema.zig:27555:36: 0x13be7d7 in ensureFuncBodyAnalyzed (zig)
src/Sema.zig:29908:44: 0xfbe449 in resolveInferredErrorSet (zig)
src/Sema.zig:27834:49: 0xf8a0d1 in analyzeIsNonErrComptimeOnly (zig)
src/Sema.zig:27861:56: 0x130c37c in analyzeIsNonErr (zig)
src/Sema.zig:16290:53: 0xed332b in zirIsNonErr (zig)
src/Sema.zig:959:66: 0xc95d11 in analyzeBodyInner (zig)
src/Sema.zig:5240:34: 0x13309c9 in resolveBlockBody (zig)
src/Sema.zig:5223:85: 0xf8598c in zirBlock (zig)
src/Sema.zig:1449:69: 0xca2bf1 in analyzeBodyInner (zig)
src/Sema.zig:5240:34: 0x13309c9 in resolveBlockBody (zig)
src/Sema.zig:5223:85: 0xf8598c in zirBlock (zig)
src/Sema.zig:1449:69: 0xca2bf1 in analyzeBodyInner (zig)
src/Sema.zig:5240:34: 0x13309c9 in resolveBlockBody (zig)
src/Sema.zig:5223:85: 0xf8598c in zirBlock (zig)
src/Sema.zig:1449:69: 0xca2bf1 in analyzeBodyInner (zig)
src/Sema.zig:798:30: 0xe77258 in analyzeBody (zig)
src/Module.zig:5659:43: 0xc7593a in analyzeFnBody (zig)
src/Module.zig:4342:40: 0xaaf7ed in ensureFuncBodyAnalyzed (zig)
src/Sema.zig:27555:36: 0x13be7d7 in ensureFuncBodyAnalyzed (zig)
src/Sema.zig:29908:44: 0xfbe449 in resolveInferredErrorSet (zig)
src/Sema.zig:27834:49: 0xf8a0d1 in analyzeIsNonErrComptimeOnly (zig)
src/Sema.zig:16392:60: 0xf890cd in zirTry (zig)
src/Sema.zig:1603:67: 0xca5653 in analyzeBodyInner (zig)
src/Sema.zig:779:30: 0x132be0b in analyzeBodyRuntimeBreak (zig)
src/Sema.zig:10567:45: 0xee6dcc in zirSwitchBlock (zig)
src/Sema.zig:981:69: 0xc9703b in analyzeBodyInner (zig)
src/Sema.zig:5240:34: 0x13309c9 in resolveBlockBody (zig)
src/Sema.zig:5223:85: 0xf8598c in zirBlock (zig)
src/Sema.zig:1449:69: 0xca2bf1 in analyzeBodyInner (zig)
src/Sema.zig:798:30: 0xe77258 in analyzeBody (zig)
src/Module.zig:5659:43: 0xc7593a in analyzeFnBody (zig)
src/Module.zig:4342:40: 0xaaf7ed in ensureFuncBodyAnalyzed (zig)
src/Sema.zig:27555:36: 0x13be7d7 in ensureFuncBodyAnalyzed (zig)
src/Sema.zig:29908:44: 0xfbe449 in resolveInferredErrorSet (zig)
src/Sema.zig:27834:49: 0xf8a0d1 in analyzeIsNonErrComptimeOnly (zig)
src/Sema.zig:27861:56: 0x130c37c in analyzeIsNonErr (zig)
src/Sema.zig:16290:53: 0xed332b in zirIsNonErr (zig)
src/Sema.zig:959:66: 0xc95d11 in analyzeBodyInner (zig)
src/Sema.zig:5240:34: 0x13309c9 in resolveBlockBody (zig)
src/Sema.zig:5223:85: 0xf8598c in zirBlock (zig)
src/Sema.zig:1449:69: 0xca2bf1 in analyzeBodyInner (zig)
src/Sema.zig:5240:34: 0x13309c9 in resolveBlockBody (zig)
src/Sema.zig:5223:85: 0xf8598c in zirBlock (zig)
src/Sema.zig:1449:69: 0xca2bf1 in analyzeBodyInner (zig)
src/Sema.zig:798:30: 0xe77258 in analyzeBody (zig)
src/Module.zig:5659:43: 0xc7593a in analyzeFnBody (zig)
src/Module.zig:4342:40: 0xaaf7ed in ensureFuncBodyAnalyzed (zig)
src/Compilation.zig:3123:42: 0xaad36c in processOneJob (zig)
src/Compilation.zig:3061:30: 0x98dec4 in performAllTheWork (zig)
src/Compilation.zig:2385:31: 0x989983 in update (zig)
src/main.zig:3423:20: 0x9b814d in updateModule (zig)
src/main.zig:3085:17: 0x899992 in buildOutputType (zig)
src/main.zig:259:31: 0x873e13 in mainArgs (zig)
src/main.zig:199:20: 0x873375 in main (zig)
lib/std/start.zig:614:37: 0x8759a7 in main (zig)
Stop reason: signal SIGABRT
```

<img width="444" alt="image" src="https://user-images.githubusercontent.com/709451/206561647-a1498b99-e71a-4569-82f7-a04530a683c8.png">

err_loc:

```zig
        pub fn init(
            writer: Writer,
            tree: *const Ast,
            source: *const logger.Source,
            symbols: Symbol.Map, 
            opts: Options, // <--- this line number, assuming that `line` is 0-indexed
            linker: ?*Linker,
            allocator: std.mem.Allocator,
        ) !Printer {
```

### Expected Behavior

no panic, show more errors

**Comment by Jarred-Sumner** [comment] 2022-12-08 20:38
Incase it's helpful, here is the code for `Options` struct:

```zig
pub const Options = struct {
    transform_imports: bool = true,
    to_module_ref: Ref = Ref.None,
    require_ref: ?Ref = null,
    indent: usize = 0,
    externals: []u32 = &[_]u32{},
    runtime_imports: runtime.Runtime.Imports = runtime.Runtime.Imports{},
    module_hash: u32 = 0,
    source_path: ?fs.Path = null,
    bundle_export_ref: ?Ref = null,
    rewrite_require_resolve: bool = true,
    allocator: std.mem.Allocator = default_allocator,
    source_map_handler: ?SourceMapHandler = null,
    css_import_behavior: Api.CssInJsBehavior = Api.CssInJsBehavior.facade,
    prepend_part_key: ?*anyopaque = null,
    prepend_part_value: ?*js_ast.Part = null,

    pub inline fn unindent(self: *Options) void {
        self.indent -|= 1;
    }
};
```

The weirdest type here is probably `Ref`, which is a single-field enum with a 62-bit unsigned int representation. Done this way mostly as a workaround for buggy packed structs in stage1

```zig

pub const Ref = enum(TotalSize) {
    default = std.math.maxInt(TotalSize),
    _,

    pub const TotalSize = u62;

    pub fn format(ref: Ref, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(
            writer,
            "Ref: sourceIndex = {d}, innerIndex = {d}, is_source_contents_slice = {}",
            .{
                ref.sourceIndex(),
                ref.innerIndex(),
                ref.isSourceContentsSlice(),
            },
        );
    }

    const max_ref_int = std.math.maxInt(Ref.Int);
    pub const BitInt = std.meta.Int(.unsigned, @bitSizeOf(Ref));

    pub inline fn asBitInt(this: Ref) BitInt {
        return @bitCast(BitInt, this);
    }

    // 2 bits of padding for whatever is the parent
    pub const Int = u30;
    pub const None = Ref.init(std.math.maxInt(u30), std.math.maxInt(u30), false);
    pub const RuntimeRef = Ref.init(std.math.maxInt(u30), std.math.maxInt(u30) - 1, false);

    const source_index_offset = 1;
    const inner_index_offset = 1 + 30;

    pub inline fn sourceIndex(this: Ref) Int {
        return @truncate(Int, getBits(TotalSize, @enumToInt(this), source_index_offset, 30));
    }

    pub inline fn innerIndex(this: Ref) Int {
        return @truncate(Int, getBits(TotalSize, @enumToInt(this), inner_index_offset, 30));
    }

    pub inline fn isSourceContentsSlice(this: Ref) bool {
        return (getBits(TotalSize, @enumToInt(this), 0, 1) & 1) != 0;
    }

    pub fn atIndex(value: anytype) Ref {
        return @intToEnum(Ref, setBits(TotalSize, 0, inner_index_offset, 30, @truncate(Int, value)));
    }

    pub fn init(inner_index: Int, source_index: Int, is_source_contents_slice: bool) Ref {
        return @intToEnum(
            Ref,
            setBits(
                TotalSize,
                0,
                0,
                1,
                @as(
                    TotalSize,
                    @boolToInt(is_source_contents_slice),
                ),
            ) | setBits(
                TotalSize,
                0,
                source_index_offset,
                30,
                source_index,
            ) | setBits(
                TotalSize,
                0,
                inner_index_offset,
                30,
                inner_index,
            ),
        );
    }

    const Old = struct {
        inner_index: Int = 0,
        source_index: Int = std.math.maxInt(Int),
        is_source_contents_slice: bool = false,
    };
    pub fn initSourceEnd(old: Old) Ref {
        return init(old.inner_index, old.source_index, old.is_source_contents_slice);
    }

    pub fn toInt(int: anytype) Int {
        return @intCast(Int, int);
    }

    pub fn hash(key: Ref) u32 {
        return @truncate(u32, key.hash64());
    }

    pub inline fn asU64(key: Ref) u64 {
        // This type isn't quite a u64 because it is used in a few other packed structs which have variables in them
        // But, there are some footguns with the stage1 implementation of packed structs
        // so it is safer to do comparisons as u64
        // but we want to ensure that the value of the unused bits in the u64 are 0
        // i have not looked at the assembly to verify that the unused bits default to 0
        // so we set it to u64 0 just to be sure
        return @as(u64, @enumToInt(key));
    }

    pub inline fn hash64(key: Ref) u64 {
        return std.hash.Wyhash.hash(0, &@bitCast([8]u8, key.asU64()));
    }

    pub fn eql(ref: Ref, b: Ref) bool {
        return asU64(ref) == b.asU64();
    }
    pub inline fn isNull(self: Ref) bool {
        return self.eql(Ref.None);
    }

    pub fn isSourceIndexNull(int: anytype) bool {
        return int == max_ref_int;
    }

    pub fn jsonStringify(self: *const Ref, options: anytype, writer: anytype) !void {
        return try std.json.stringify([2]u32{ self.sourceIndex(), self.innerIndex() }, options, writer);
    }
};
```

**Comment by InKryption** [comment] 2022-12-08 20:51
It seems like `SourceMapHandler` is the culprit (or at least a culprit). It has a field `callback: Callback`, where `Callback` is a function type, but should probably be a function pointer (`fn` -> `*const fn`), or be using `std.meta.FnPtr`.

**Comment by Vexu** [comment] 2022-12-08 21:01
Still a duplicate of #13713 and the error is correct since `Callback` contains a function type.

The call back type can be fixed with my patch in https://github.com/ziglang/zig/issues/13815#issuecomment-1342330789

**Closed by Vexu** 2022-12-08 21:01 UTC
Labels: bug
