### ISSUE TITLE
Some function names cannot be imported by wasm32-standalone

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6156] opened 2020-08-24 10:00 UTC
includes `log` `exp` etc math function...

poc:
```zig
extern "whatever" fn log(anyparam: i32) void;
```

will turn to log:unreachable in wasm

**Comment by Vexu** [comment] 2020-08-24 10:10
Duplicate of #5468

**Closed by Vexu** 2020-08-24 10:10 UTC
