### ISSUE TITLE
LLVM ERROR when attempting to format integer with > 128 bits

### ISSUE THREAD

**Issue by rgreenblatt** [ziglang/zig#7924] opened 2021-01-31 18:24 UTC
```zig
const debug = @import("std").debug;

pub fn main() void {
    const any_size_over_128: u129 = 0;

    debug.print("{}\n", .{any_size_over_128});
}
```
```bash
>  zig build-exe big_int.zig
LLVM ERROR: Unsupported library call operation!
[1]    1710683 abort (core dumped)  zig build-exe big_int.zig
```

**Comment by data-man** [comment] 2021-01-31 18:26
Duplicate of #7748.

**Closed** 2021-01-31 18:26 UTC

**Comment by Vexu** [comment] 2021-01-31 18:27
Also #1485.
