### ISSUE TITLE
comptime pointer weirdness

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#5399] opened 2020-05-22 04:52 UTC
At runtime this code works:
```zig
const std = @import("std");

pub fn main() anyerror!void {
    var st = std.crypto.gimli.Hash.init();
    st.update("foo");

    var out: u64 = undefined;
    const slice = std.mem.asBytes(&out);
    st.final(slice);

    std.debug.warn("out: {}\n", .{out});
    std.debug.warn("slice: {x}\n", .{slice});
}
```
```
$ zig run runtime.zig 
out: 10674780387515474063
slice: 8fa02a7d34702494
```

Modified for comptime execution (which I would expect to work), results in an `out of bounds slice` error.
```zig
const std = @import("std");

pub fn main() anyerror!void {
    comptime var st = std.crypto.gimli.Hash.init();
    st.update("foo");

    comptime var out: u64 = undefined;
    const slice = comptime std.mem.asBytes(&out);
    comptime st.final(slice);

    @compileLog("out: ", out);
    @compileLog("slice: ", slice);
}
```
```
$ zig build-exe comptime.zig 
/usr/lib/zig/std/mem.zig:1935:40: error: out of bounds slice
    return @ptrCast(cast_target, slice)[0 .. slice.len * @sizeOf(meta.Elem(Slice))];
                                       ^
/usr/lib/zig/std/crypto/gimli.zig:28:32: note: called from here
        return mem.sliceAsBytes(self.data[0..]);
                               ^
/usr/lib/zig/std/crypto/gimli.zig:147:39: note: called from here
        const buf = self.state.toSlice();
                                      ^
./comptime.zig:9:22: note: called from here
    comptime st.final(slice);
                     ^
./comptime.zig:3:29: note: called from here
pub fn main() anyerror!void {
                            ^
/usr/lib/zig/std/crypto/gimli.zig:28:32: note: referenced here
        return mem.sliceAsBytes(self.data[0..]);
                               ^
/usr/lib/zig/std/crypto/gimli.zig:147:39: note: referenced here
        const buf = self.state.toSlice();
                                      ^
./comptime.zig:9:22: note: referenced here
    comptime st.final(slice);
                     ^
```

Meanwhile, the following snippet might have some comptime vs runtime pointer confusion?
```
const std = @import("std");

pub fn main() anyerror!void {
    var st = std.crypto.gimli.Hash.init();
    st.update("foo");

    comptime var out: u64 = undefined;
    const slice = comptime std.mem.asBytes(&out);
    st.final(slice);
}
```
```
Segmentation fault at address 0x2029b0
/usr/lib/zig/std/mem.zig:269:19: 0x210ccc in std.mem.copy (run)
        dest[i] = s;
                  ^
/usr/lib/zig/std/crypto/gimli.zig:73:21: 0x231197 in std.crypto.gimli.State.squeeze (run)
            mem.copy(u8, out[i..], self.toSliceConst()[0..leftover]);
                    ^
/usr/lib/zig/std/crypto/gimli.zig:154:27: 0x22f088 in std.crypto.gimli.Hash.final (run)
        self.state.squeeze(out);
                          ^
/tmp/tmp.cJTlxVf81U/foo.zig:9:13: 0x22aa46 in main (run)
    st.final(slice);
            ^
/usr/lib/zig/std/start.zig:253:37: 0x20482d in std.start.posixCallMainAndExit (run)
            const result = root.main() catch |err| {
                                    ^
/usr/lib/zig/std/start.zig:123:5: 0x20456f in std.start._start (run)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
Aborted (core dumped)
```

**Comment by Vexu** [comment] 2020-05-22 09:58
Duplicate of #1292 and #1150.

**Closed by Vexu** 2020-05-22 09:58 UTC
