### ISSUE TITLE
Segmentation fault when returning var

### ISSUE THREAD

**Issue by AndreaOrru** [ziglang/zig#829] opened 2018-03-13 07:44 UTC
Minimal example:
```
fn metafoo(comptime function: var) var {
    return function;
}

fn foo() void {}

pub fn main() void {
    _ = metafoo(foo);
}
```

For context, specifying the return value explicitly works:
```
fn metafoo(comptime function: var) @typeOf(function) {
    return function;
}
```

**Comment by andrewrk** [comment] 2018-03-13 14:43
this is #447

but I'll leave this open, at least I can make it print a compile error instead of segfaulting.

**Comment by dbandstra** [comment] 2018-09-06 05:16
This is still crashing in some cases

## First case: gives compile error
```
fn badFunction() var { return 0; }
test "" { _ = badFunction(u32); }
```
Output:
```
/home/dbandstra/oxid/test.zig:1:1: error: TODO implement inferred return types https://github.com/ziglang/zig/issues/447
fn badFunction() var {
^
The following command exited with error code 1 [...]
```

## Second case: crashes with message
```
fn badFunction(comptime T: type) var { return 0; }
test "" { _ = badFunction(u32); }
```
Output:
```
TODO implement inferred return types https://github.com/ziglang/zig/issues/447
The following command exited with error code 1 [...]
```

## Third case: crashes with no message
```
fn badFunction(comptime T: type) var { return 0; }
test "" { _ = comptime badFunction(u32); }
```
Output:
```
The following command exited with error code 1 [...]
```

**Comment by bb010g** [comment] 2020-07-10 02:18
#5834 is a duplicate of this. (Thanks, @Snektron.)

On the side, Godbolt reported this as error code 255, not error code 1. Not sure if that's how it tries to report segfaults?

**Closed** 2020-07-12 07:35 UTC
Labels: bug
