### ISSUE TITLE
Error union of opaque type crashes compiler instead of erroring out

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#6422] opened 2020-09-25 23:30 UTC
```zig
const Opaque = @Type(.Opaque);
comptime { _ = @as(anyerror!Opaque, undefined); }
```
`Assertion failed at /deps/zig/src/analyze.cpp:745 in get_error_union_type. This is a bug in the Zig compiler.`

**Comment by Vexu** [comment] 2020-09-26 06:58
Duplicate of #5227.

**Closed by Vexu** 2020-09-26 06:58 UTC
Labels: bug, stage1
