### ISSUE TITLE
Build Failure on Windows 11: zig2 Compilation Errors with Visual Studio and Ninja

### ISSUE THREAD

**Issue by jayjaye01** [ziglang/zig#22348] opened 2024-12-29 16:51 UTC
### **Steps to Reproduce and Observed Behavior:**
I am encountering a build failure when attempting to compile Zig from source on Windows 11 using CMake and Microsoft Visual Studio (Option 2: Using CMake and Microsoft Visual Studio). The build process consistently fails during the zig2 build phase with errors related to inconsistent DLL linkage and compiler termination.

### **Environment:**

Operating System: Windows 11
CMake Version: 3.31.3
Git Version: 2.45.2.windows.1
LLVM/Clang Version: 19.1.6
Visual Studio Build Tools: 2022 (Including "Desktop Development with C++" and C++ Build Tools)

### **Steps Followed:**

- Installed required dependencies and build tools via Visual Studio Installer.
- Set up the environment as per the Zig Wiki instructions.
- Forked / Pulled Ziglang Git (Delete and redo included)
- Build a new build-release folder and then performced steps mentioned in the below source.
- Rechecked Zig version to ensure the latest is use
- Tried both Ninja and VS build systems
- Reinstalled dependencies mentioned on the Wiki pages to see if it made a difference.
- Changed environment variable paths to check if it made a difference
- Tried checking the Zig version ensuring it is the latest build
- Source: https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows / https://github.com/ziglang/zig/wiki/Contributing etc.

### **Visual Studio Build System:**

C:\zig-dep\CMake\bin\cmake.exe .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=C:\zig-dep\llvm-19.1.6 -DCMAKE_BUILD_TYPE=Release
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release INSTALL.vcxproj
**Ninja Build System:**

C:\zig-dep\CMake\bin\cmake.exe .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=C:\zig-dep\llvm-19.1.6
C:\zig-dep\ninja\ninja.exe install

### **Error Logs:**
**From Visual Studio:**

C:\zig\build-release\zig2.c(309973,22): warning C4273: '_msize': inconsistent dll linkage [C:\zig\build-release\zig2.vcxproj]
C:\zig\build-release\zig2.c(310301,18): warning C4273: 'malloc': inconsistent dll linkage [C:\zig\build-release\zig2.vcxproj]
C:\zig\build-release\zig2.c(310302,17): warning C4273: 'free': inconsistent dll linkage [C:\zig\build-release\zig2.vcxproj]
error MSB6006: "CL.exe" exited with code -1073741571.
44 Warning(s), 1 Error(s)

**From Ninja:**

FAILED: CMakeFiles/zig2.dir/zig2.c.obj
C:\zig\build-release\zig2.c(309973): warning C4273: '_msize': inconsistent dll linkage
C:\zig\build-release\zig2.c(310301): warning C4273: 'malloc': inconsistent dll linkage
C:\zig\build-release\zig2.c(310302): warning C4273: 'free': inconsistent dll linkage
ninja: build stopped: subcommand failed.

### **Steps Tried:**

- Followed all build instructions from the Zig Wiki, including both Visual Studio and Ninja methods.
- Verified paths, environment variables, and dependencies.
- Cleaned the build environment and attempted fresh builds.
- Ensured all dependencies, including LLVM and Clang (v19.1.6), are correctly installed and updated.

### **Questions:**

Is there a known compatibility issue with LLVM 19.1.6 or MSVC versions used in the build process?
Is there a way to fix this?

### **Attached Log Files:**

[Zig - Build -NINJA-Error Log.txt](https://github.com/user-attachments/files/18270353/Zig.-.Build.-NINJA-Error.Log.txt)

[Zig - Build -VS -Error Log.txt](https://github.com/user-attachments/files/18270354/Zig.-.Build.-VS.-Error.Log.txt)

**Comment by rohlem** [comment] 2024-12-29 17:36
might be a duplicate of https://github.com/ziglang/zig/issues/22196, https://github.com/ziglang/zig/pull/22054#issuecomment-2495744901

**Comment by alexrp** [comment] 2024-12-29 17:46
Almost certainly a duplicate. You can work around it by building with VS 2019 (or patching the stack size of `cl.exe` if you really want). The good news is that it has been fixed and we're just waiting for Microsoft to ship the fix.

**Closed** 2024-12-29 17:46 UTC
Labels: bug

**Comment by jayjaye01** [comment] 2024-12-29 18:04
Appreciate it, clear. Will have a better lookout next time. 
Doing VS 2019 in the meantime.
