### ISSUE TITLE
stage3: No stack trace for formatting error union with {}

### ISSUE THREAD

**Issue by LordMZTE** [ziglang/zig#12538] opened 2022-08-20 22:20 UTC
### Zig Version

0.10.0-dev.3659+e5e6eb983

### Steps to Reproduce

Create a file `test.zig`:
```zig
const std = @import("std");

pub fn main() void {
    const error_union: anyerror!u8 = error.Foo;
    std.debug.print("{}", .{error_union});
}
```

Run `zig run test.zig`.

### Expected Behavior

The compiler emits an error regarding the invalid formatting of the error union, including a stack trace back to the call to `std.debug.print`.

### Actual Behavior

The compiler emits this error:
```
/home/lordmzte/zig/0.10.0-dev.3659+e5e6eb983/files/lib/std/fmt.zig:508:17: error: cannot format error union without a specifier (i.e. {!} or {any})
                @compileError("cannot format error union without a specifier (i.e. {!} or {any})");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Since this error includes no stack trace, it is virtually impossible to debug this on a larger code base, when it is unknown where the error might be originating.

**Comment by Vexu** [comment] 2022-08-21 09:27
Duplicate of  #12141

**Closed by Vexu** 2022-08-21 09:27 UTC
Labels: bug, enhancement, stage2, error message
