### ISSUE TITLE
A short code causing LLVM error during compilation.

### ISSUE THREAD

**Issue by gegogi** [ziglang/zig#6468] opened 2020-09-30 06:33 UTC
This issue made me take some time to find the exact position of error.
I came up with a simple code to reproduce it.
Can this be fixed easily?

The function return type is wrong and the zig compiler couldn't pinpoint the position.
It just gave me "broken LLVM module found" error.

```
const std = @import("std");
const Allocator = std.mem.Allocator;

//fn getSlice(allocator: *Allocator) ![][*:0]const u8 {  // correct code
fn getSlice(allocator: *Allocator) ![][*]const u8 {     // mismatched element type      
    const elems = [_][*:0] const u8{"qwerty", "def", "gh"};
    var a = std.ArrayList([*:0]const u8).init(allocator);
    errdefer a.deinit();
    try a.appendSlice(elems[0..2]);
    return a.toOwnedSlice();
}

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = &arena.allocator;
    var slice = getSlice(allocator);
}
```

**Comment by Vexu** [comment] 2020-09-30 07:13
Duplicate of #6147.

The cast is actually perfectly valid we're just failing to generate proper LLVM ir.

**Closed by Vexu** 2020-09-30 07:13 UTC
