### ISSUE TITLE
local struct variable not initialize to zero when undefined

### ISSUE THREAD

**Issue by wojciechmurimi** [ziglang/zig#20252] opened 2024-06-10 08:31 UTC
### Zig Version

0.13.0-dev.365+332fbb4b0

### Steps to Reproduce and Observed Behavior

```zig 
const std = @import("std");
const Item = struct {
    arry: [2]u8
};

var a: Item = undefined;
test "global var" {
    try std.testing.expect(std.mem.eql(u8, std.mem.asBytes(&a), std.mem.asBytes(&[_]u8{0, 0})));
}

test "local var" {
    var b: Item = undefined;
    try std.testing.expect(std.mem.eql(u8, std.mem.asBytes(&b), std.mem.asBytes(&[_]u8{0, 0})));
}
```

```bash
2/2 main.test.local var...FAIL (TestUnexpectedResult)
/home/vic/Desktop/zig-linux-x86_64-0.13.0-dev.365+332fbb4b0/lib/std/testing.zig:540:14: 0x103ba7f in expect (test)
    if (!ok) return error.TestUnexpectedResult;
             ^
/home/vic/Desktop/zig_pad/main.zig:14:5: 0x103bd5a in test.local var (test)
    try std.testing.expect(std.mem.eql(u8, std.mem.asBytes(&b), std.mem.asBytes(&[_]u8{0, 0})));
    ^
1 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
/home/vic/.cache/zig/o/fa80b4c82c9c38b3f35947c882fc117e/test
```

### Expected Behavior

expect global and local var to be equal

**Comment by Vexu** [comment] 2024-06-10 13:36
Both tests should fail, duplicate of #1987

**Closed by Vexu** 2024-06-10 13:36 UTC
Labels: bug
