### ISSUE TITLE
 crash on: integer cast truncated bits

### ISSUE THREAD

**Issue by maxzhao** [ziglang/zig#14031] opened 2022-12-22 10:13 UTC
### Zig Version

zig-windows-x86_64-0.11.0-dev.923+a52dcdd3c

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
pub const ColorEditFlags = packed struct(c_int) {
    pub usingnamespace CFlagNamespace(@This());
    pub const none = @This().fromUInt(0);

    _unused_bits0: u0 = 0,
     _: u32 = 0,

};
pub fn CFlagNamespace(comptime FlagType: type) type {

    return struct {
        pub inline fn fromUInt(uint: c_uint) FlagType {
            return @bitCast(FlagType, uint);
        }
    };
} ```


compiler crash with : Semantic Analysis [9286] ensureTotalCapacity... thread 10384 panic: integer cast truncated bits
the stack trace is here: 
 C:\Projects\zig\zig\lib\std\mem.zig:1316:47: 0x7ff663ae8586 in readVarPackedInt__anon_171810 (zig.exe.obj)
    const pad = @intCast(Log2N, @bitSizeOf(T) - bit_count);
                                              ^
C:\Projects\zig\zig\src\value.zig:1576:97: 0x7ff66384bc90 in readFromPackedMemory (zig.exe.obj)
                    .unsigned => return Value.Tag.int_u64.create(arena, std.mem.readVarPackedInt(u64, buffer, bit_offset, bits, endian, .unsigned)),
                                                                                                ^
C:\Projects\zig\zig\src\value.zig:1618:100: 0x7ff66384b86a in readFromPackedMemory (zig.exe.obj)
                        field_vals[i] = try readFromPackedMemory(field.ty, mod, buffer, bit_offset + bits, arena); 

### Expected Behavior

compile success

**Comment by Vexu** [comment] 2022-12-22 10:37
Duplicate of #13942

**Closed by Vexu** 2022-12-22 10:37 UTC
Labels: bug
