### ISSUE TITLE
stage3: error message line number is always 1 with invalid default value on toplevel field

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#12834] opened 2022-09-13 14:27 UTC
### Zig Version

0.10.0-dev.3986+e323cf126

### Steps to Reproduce

Create `bug.zig`:
```zig
pub fn main() void {
    var s = @This(){ };
    _ = s;
}
path: []const u8 = null,
```
Run (with the stage3 compiler)
```sh
$ zig build-obj bug.zig
bug.zig:1:1: error: expected type '[]const u8', found '@TypeOf(null)'
```

### Expected Behavior

Expect the error message to point to line 5 column 20.  If you compile with stage1 you get:
```sh
$ zig build-obj bug.zig -fstage1
./bug.zig:5:20: error: expected type '[]const u8', found '@Type(.Null)'
path: []const u8 = null,
                   ^
```

### Actual Behavior

The error message when compiling with stage3 always points to line 1 column 1:
```
bug.zig:1:1: error: expected type '[]const u8', found '@TypeOf(null)'
```

## Extra Notes

Note that the error location remains at line 1 column 1 even if you add blank lines to the beginning of the file.  The stage3 compiler just seems to lose the location of this error somehow.

**Comment by Vexu** [comment] 2022-09-13 17:17
Duplicate of #12752

**Closed by Vexu** 2022-09-13 17:17 UTC
Labels: bug
