### ISSUE TITLE
Allow underscores in numeric literals for improved readability?

### ISSUE THREAD

**Issue by scottjmaddox** [ziglang/zig#4108] opened 2020-01-08 04:41 UTC
In Rust, underscores can be inserted in numeric literals to improve readability, e.g. `1_000` is the same as `1000`, and `0.000_001` is the same as `0.000001`. This can be especially helpful for large binary and hex literals, e.g. `0b0101000100001001` vs. `0b0101_0001_0000_1001`.

Supporting this would be a pretty minor change to the grammar and lexer, and would be backwards compatible (i.e. it would not break currently working code).

**Comment by daurnimator** [comment] 2020-01-08 04:46
Duplicate of #3983

**Closed by daurnimator** 2020-01-08 04:46 UTC
