### ISSUE TITLE
compiler segfaults/crashes when breaking from nested inline for loops at runtime

### ISSUE THREAD

**Issue by PixelPhoton** [ziglang/zig#18369] opened 2023-12-25 12:38 UTC
### Zig Version

0.12.0-dev.1814+5c0d58b71

### Steps to Reproduce and Observed Behavior

it seems to occur when breaking from a nested inline for-loop at runtime
```
$ zig build-exe main.zig 
zsh: segmentation fault (core dumped)  zig build-exe main.zig
```
here is some code that triggers it
```zig
const std = @import("std");

fn func(str: []const u8, comptime cmp: []const []const u8) bool {
    const i: usize = 0;
    inline for (cmp) |v| {
        inline for (v) |_| {
            if (str.len <= i) break;
        }
    }
    if (i < str.len) return false;
    return true;
}

pub fn main() void {
    const fmt = &[_][]const u8{ "Hello ", "there ", ", world", "!" };

    if (func("Hello, world!", fmt)) std.log.info("match!", .{}) else std.log.info("no match", .{});
}
```
the crash does not occur when the innermost loop is not inline

### Expected Behavior

I expected the innermost inline for loop to be `break`ed in the same way as a runtime for loop, or, at the very least, provide a compilation error/warning if this code is wrong

**Comment by nektro** [comment] 2023-12-25 20:11
`0.12.0-dev.1849+bb0f7d55e`

```
thread 2241143 panic: attempt to use null value
Analyzing test.zig: test.zig:func__anon_934
      %103 = dbg_stmt(5, 20)
      %104 = field_val(%66, "len") node_offset:13:17 to :13:24
      %105 = cmp_lte(%104, %74) node_offset:13:17 to :13:29
      %106 = as_node(@bool_type, %105) node_offset:13:17 to :13:29
    > %107 = condbr(%106, {
        %109 = dbg_block_begin()
        %110 = restore_err_ret_index(%94.none)
        %111 = break_inline(%94, @void_value)
      }, {
        %112 = break(%108, @void_value)
      }) node_offset:13:13 to :13:36
    For full context, use the command
      zig ast-check -t test.zig

  in test.zig: test.zig:func__anon_934
    > %108 = block({%103..%107}) node_offset:13:13 to :13:36
  in test.zig: test.zig:func__anon_934
    > %100 = block({%101..%116}) node_offset:12:28 to :12:28
  in test.zig: test.zig:func__anon_934
    > %97 = condbr_inline(%96, {%99..%118}, {%119}) node_offset:12:9 to :12:19
  in test.zig: test.zig:func__anon_934
    > %98 = block_inline({%96, %97}) node_offset:12:9 to :12:19
  in test.zig: test.zig:func__anon_934
    > %94 = block_inline({%95..%122}) node_offset:12:9 to :12:19
  in test.zig: test.zig:func__anon_934
    > %88 = block({%89..%126}) node_offset:11:26 to :11:26
  in test.zig: test.zig:func__anon_934
    > %83 = condbr_inline(%82, {%85..%128}, {%129}) node_offset:11:5 to :11:15
  in test.zig: test.zig:func__anon_934
    > %84 = block_inline({%82, %83}) node_offset:11:5 to :11:15
  in test.zig: test.zig:func__anon_934
    > %80 = block_inline({%81..%132}) node_offset:11:5 to :11:15
  in test.zig: test.zig:func__anon_934
    > %71 = block({%72..%158}) node_offset:9:65 to :9:65

/home/meghan/src/zig/src/Sema.zig:18532:71: 0x13994aa in addRuntimeBreak (zig)
        const labeled_block = sema.post_hoc_blocks.get(new_block_inst).?;
                                                                      ^
/home/meghan/src/zig/src/Sema.zig:901:37: 0x1a1ef58 in analyzeBodyRuntimeBreak (zig)
            try sema.addRuntimeBreak(block, .{
                                    ^
/home/meghan/src/zig/src/Sema.zig:18347:37: 0x146a8af in zirCondbr (zig)
    try sema.analyzeBodyRuntimeBreak(&sub_block, then_body);
                                    ^
/home/meghan/src/zig/src/Sema.zig:1685:61: 0x104b717 in analyzeBodyInner (zig)
                if (!block.is_comptime) break sema.zirCondbr(block, inst);
                                                            ^
/home/meghan/src/zig/src/Sema.zig:5853:34: 0x1a20037 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/meghan/src/zig/src/Sema.zig:5836:33: 0x14705af in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/meghan/src/zig/src/Sema.zig:1577:49: 0x104df17 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[@intFromEnum(inst)] == .block_comptime);
                                                ^
/home/meghan/src/zig/src/Sema.zig:5853:34: 0x1a20037 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/meghan/src/zig/src/Sema.zig:5836:33: 0x14705af in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/meghan/src/zig/src/Sema.zig:1577:49: 0x104df17 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[@intFromEnum(inst)] == .block_comptime);
                                                ^
/home/meghan/src/zig/src/Sema.zig:933:45: 0xdb6b84 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/meghan/src/zig/src/Sema.zig:1728:62: 0x104c260 in analyzeBodyInner (zig)
                const break_data = (try sema.analyzeBodyBreak(block, inline_body)) orelse
                                                             ^
/home/meghan/src/zig/src/Sema.zig:933:45: 0xdb6b84 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/meghan/src/zig/src/Sema.zig:1632:55: 0x104af09 in analyzeBodyInner (zig)
                    break :b try sema.analyzeBodyBreak(&child_block, inline_body);
                                                      ^
/home/meghan/src/zig/src/Sema.zig:933:45: 0xdb6b84 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/meghan/src/zig/src/Sema.zig:1632:55: 0x104af09 in analyzeBodyInner (zig)
                    break :b try sema.analyzeBodyBreak(&child_block, inline_body);
                                                      ^
/home/meghan/src/zig/src/Sema.zig:5853:34: 0x1a20037 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/meghan/src/zig/src/Sema.zig:5836:33: 0x14705af in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/meghan/src/zig/src/Sema.zig:1577:49: 0x104df17 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[@intFromEnum(inst)] == .block_comptime);
                                                ^
/home/meghan/src/zig/src/Sema.zig:933:45: 0xdb6b84 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/meghan/src/zig/src/Sema.zig:1728:62: 0x104c260 in analyzeBodyInner (zig)
                const break_data = (try sema.analyzeBodyBreak(block, inline_body)) orelse
                                                             ^
/home/meghan/src/zig/src/Sema.zig:933:45: 0xdb6b84 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/meghan/src/zig/src/Sema.zig:1632:55: 0x104af09 in analyzeBodyInner (zig)
                    break :b try sema.analyzeBodyBreak(&child_block, inline_body);
                                                      ^
/home/meghan/src/zig/src/Sema.zig:933:45: 0xdb6b84 in analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/meghan/src/zig/src/Sema.zig:1632:55: 0x104af09 in analyzeBodyInner (zig)
                    break :b try sema.analyzeBodyBreak(&child_block, inline_body);
                                                      ^
/home/meghan/src/zig/src/Sema.zig:5853:34: 0x1a20037 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/meghan/src/zig/src/Sema.zig:5836:33: 0x14705af in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/meghan/src/zig/src/Sema.zig:1577:49: 0x104df17 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[@intFromEnum(inst)] == .block_comptime);
                                                ^
/home/meghan/src/zig/src/Sema.zig:916:30: 0x133e8f8 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/meghan/src/zig/src/Module.zig:4616:21: 0x1019b00 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/meghan/src/zig/src/Module.zig:3324:40: 0xd9a09d in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func_index, sema_arena) catch |err| switch (err) {
                                       ^
/home/meghan/src/zig/src/Compilation.zig:3761:42: 0xd9846d in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/meghan/src/zig/src/Compilation.zig:3698:30: 0xb6a328 in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
/home/meghan/src/zig/src/Compilation.zig:2505:31: 0xb65b82 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/meghan/src/zig/src/main.zig:4283:24: 0xb96282 in updateModule (zig)
        try comp.update(main_progress_node);
                       ^
/home/meghan/src/zig/src/main.zig:3684:17: 0xbb8e42 in buildOutputType (zig)
    updateModule(comp) catch |err| switch (err) {
                ^
/home/meghan/src/zig/src/main.zig:284:31: 0x9c26c7 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/meghan/src/zig/src/main.zig:222:20: 0x9bf6c5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/meghan/src/zig/lib/std/start.zig:585:37: 0x9bf146 in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7fbeb883dacd in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7fbeb883dacd` was not available, trace may be incomplete

Aborted (core dumped)
```

**Comment by Vexu** [comment] 2023-12-25 22:43
Duplicate of https://github.com/ziglang/zig/issues/13428#issuecomment-1302205175

**Closed by Vexu** 2023-12-25 22:43 UTC
Labels: bug

**Comment by PixelPhoton** [comment] 2023-12-27 16:39
> Duplicate of [#13428 (comment)](https://github.com/ziglang/zig/issues/13428#issuecomment-1302205175)

sorry, I'd tried to search but somehow didn't find that.
