### ISSUE TITLE
Zig crashes when calling @sizeOf on an optional pointer of a generic type

### ISSUE THREAD

**Issue by omaraaa** [ziglang/zig#17511] opened 2023-10-13 17:51 UTC
### Zig Version

0.12.0-dev.891+2254882eb

### Steps to Reproduce and Observed Behavior

Running `zig test` on the following code :-
```zig
fn A() type {
    return struct {};
}

test {
    const a = @sizeOf(?*A());
    _ = a;
}
```
produces the following (thanks cryptocode) :-
```
thread 12552215 panic: attempt to use null value
Analyzing tests/crash.zig: crash.zig:test_0
      %23 = dbg_block_begin()
      %24 = dbg_stmt(2, 5)
      %25 = block_comptime({
        %26 = decl_val("A")
        %27 = dbg_stmt(2, 26)
        %28 = call(.compile_time, %26, [])
        %29 = ptr_type(%28, One)
        %30 = optional_type(%29)
        %31 = break(%25, %30)
      })
    > %32 = size_of(%25)
      %33 = dbg_var_val(%32, "a")
      %34 = dbg_stmt(3, 5)
      %35 = ensure_result_non_error(%32)
      %36 = dbg_block_end()
      %37 = restore_err_ret_index(%22, %4294967211)
      %38 = break(%22, @InternPool.Index.void_value)
    For full context, use the command
      zig ast-check -t tests/crash.zig

  in tests/crash.zig: crash.zig:test_0
    > %22 = block({%23..%38})

zig/src/type.zig:2678:50: 0x10577b9c6 in comptimeOnlyAdvanced (zig)
                            const sema = opt_sema.?;
                                                 ^
zig/src/type.zig:2601:69: 0x10577b1cf in comptimeOnlyAdvanced (zig)
                        else => return child_ty.comptimeOnlyAdvanced(mod, opt_sema),
                                                                    ^
zig/src/type.zig:2583:39: 0x105b95e1d in comptimeOnly (zig)
        return ty.comptimeOnlyAdvanced(mod, null) catch unreachable;
                                      ^
zig/src/type.zig:478:41: 0x10577d638 in hasRuntimeBitsAdvanced (zig)
                    return !comptimeOnly(ty, mod);
                                        ^
zig/src/type.zig:1490:46: 0x105791dbb in abiSizeAdvancedOptional (zig)
        if (!(child_ty.hasRuntimeBitsAdvanced(mod, false, strat) catch |err| switch (err) {
                                             ^
zig/src/type.zig:1285:63: 0x1054db609 in abiSizeAdvanced (zig)
                .opt_type => return ty.abiSizeAdvancedOptional(mod, strat),
                                                              ^
zig/src/type.zig:1204:39: 0x1060361ad in lazyAbiSize (zig)
        switch (try ty.abiSizeAdvanced(mod, .lazy)) {
                                      ^
zig/src/Sema.zig:16576:35: 0x105aff811 in zirSizeOf (zig)
    const val = try ty.lazyAbiSize(mod);
                                  ^
zig/src/Sema.zig:1098:64: 0x105768572 in analyzeBodyInner (zig)
            .size_of                      => try sema.zirSizeOf(block, inst),
                                                               ^
zig/src/Sema.zig:5891:34: 0x1060b203c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
zig/src/Sema.zig:5874:33: 0x105b8a626 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
zig/src/Sema.zig:1578:49: 0x105776043 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
zig/src/Sema.zig:917:30: 0x105a59299 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
zig/src/Module.zig:4822:21: 0x105741a17 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
```

### Expected Behavior

Expected Behavior is test passing.

**Comment by Vexu** [comment] 2023-10-13 20:28
Regressed with #17471

**Comment by DilithiumNitrate** [comment] 2023-10-20 18:29
I've been trying to do an amateur investigation into this issue – from what I can currently tell, the gist of it is that static analysis of the returned type from `A()` wrapped in an optional fails to resolve whether or not it's comptime-only, whereas `Type.comptimeOnlyAdvanced` is designed to expect that either the type is already resolved or a `Sema` is supplied (which is not the case in `Type.lazyAbiSize`). The same happens if `?*A()` is replaced with an error union like `std.fmt.ParseIntError!*A()`, but not if we eschew the optional or error type altogether and use `*A()` instead.

I have no idea what the best way to fix it could be, but I can see multiple avenues for that, including enabling semantic analysis inside type evaluation in more cases or (possibly the worse solution given that this method doesn't look like it's meant to do this sort of recursive descent?) making sure `Sema.resolveType` fully resolves comptimeness.

**Comment by DilithiumNitrate** [comment] 2023-10-27 13:08
On a closer look and further reading of how the lazy case works, I'm convinced the issue is in `hasRuntimeBitsAdvanced` not properly covering the lazy strategy and calling `comptimeOnly`, which only applies to the `.eager` case (and `comptimeOnlyAdvanced only covers that and `.sema`), even in the lazy case. The ways I see to approach this are either to:

1. replace every call to `comptimeOnly` and related in `hasRuntimeBitsAdvanced` with recursion,
2. modify some or all of the 12 functions – or at least the 4 in `src/type.zig` – that take an `opt_sema: ?*Sema` parameter, such as `comptimeOnlyAdvanced`, to take an `AbiAlignmentAdvancedStrat` instead (also that's a cumbersome name, I wonder if it could be readily renamed to a shorter and/or more general name in a PR fixing this issue). Then handle the lazy cases there and add `NeedLazy` to their error set.

I'm leaning towards submitting a PR that applies solution 2 to the four functions in `src/type.zig` and renaming the `AbiAlignmentAdvancedStrat`.

**Comment by mlugg** [comment] 2023-10-27 13:16
You've diagnosed the problem right, but I think you're tripping yourself up a little on the solution. All we actually need to do AFAICT is make proper use of the `lazy` strategy by returning `error.NeedLazy`, since we don't know whether or not `comptimeOnly` has been resolved. There's no real harm to making things lazier than they need to be here - we'll just end up resolving things a bit later if necessary.

I'm happy to make this change, but if you'd like to try and do it yourself as a first compiler contribution, by all means go ahead!

**Comment by DilithiumNitrate** [comment] 2023-10-27 13:53
I assume you mean that only `hasRuntimeBitsAdvanced` has to be modified – are you saying I should return `error.NeedLazy` ahead of time? I'd lean towards recursing over returning `error.NeedLazy`, given that the function already has a fair amount of recursion, but doing so for pointers would involve copying or moving code out of `comptimeOnlyAdvanced` and adapting `fnHasRuntimeBitsAdvanced`, so I might do that for pointers specifically.

**Comment by mlugg** [comment] 2023-10-27 15:01
Yeah, "no runtime bits" is a distinct concept from "comptime only". Runtime bits is also concerned with whether a type is zero-bit, i.e. equivalent to `void`

**Closed** 2023-10-29 21:12 UTC
Labels: bug, frontend, regression
