### ISSUE TITLE
stage2: Segmentation fault compiling call to type function, etc.

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#13079] opened 2022-10-05 13:30 UTC
### Zig Version

0.10.0-dev.4213+91b05ad47

### Steps to Reproduce

Compile test program with `zig test generic_alignof_struct_error.zig`.

`generic_alignof_struct_error.zig`:
```zig
const Config = struct { alignment: u64 };

fn Generic(comptime _: Config) type {
    return struct {};
}
const Special = Generic(.{ .alignment = @alignOf(struct {}) });

test {
    _ = @as(Special, undefined);
}
```

### Expected Behavior

As is:
```
$ zig test generic_alignof_struct_error.zig
Segmentation fault
```

### Actual Behavior

As with stage 1:
```
$ zig test -fstage1 generic_alignof_struct_error.zig
All 1 tests passed.
```

**Comment by Vexu** [comment] 2022-10-05 13:42
Duplicate of #12488

**Closed by Vexu** 2022-10-05 13:42 UTC
Labels: bug
