### ISSUE TITLE
ArrayHashMap loses insertion order upon delete

### ISSUE THREAD

**Issue by kbd** [ziglang/zig#7696] opened 2021-01-05 17:19 UTC
```zig
const std = @import("std");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    var A = &arena.allocator;

    var map = std.StringArrayHashMap([]const u8).init(A);

    try map.putNoClobber("a", "a");
    try map.putNoClobber("b", "b");
    try map.putNoClobber("c", "c");
    try map.putNoClobber("d", "d");
    try map.putNoClobber("e", "e");

    _ = map.remove("c");

    var it = map.iterator();
    while (it.next()) |pair| {
        std.debug.print("{}\n", .{pair.key});
    }
}
```

prints:

```
a
b
e
d
```

**Comment by ifreund** [comment] 2021-01-05 18:11
This is expected behavior. From the doc comment on `std.ArrayHashMap()`:
```
/// Insertion order is preserved.
/// Deletions perform a "swap removal" on the entries list.
```

**Comment by kbd** [comment] 2021-01-05 18:22
I didn't realize the second statement invalidates the first.

> maintaining order is one of the main reasons to use this container.

Yeah, the behavior was surprising to me. It was unclear what was meant by "swap removal".

Other languages' ordered dicts maintain order with deletes:

```python
In [1]: d = {}

In [2]: for c in 'abcde': d[c] = c

In [3]: del d['c']

In [4]: for k in d.keys(): print(k)
a
b
d
e
```

**Comment by ifreund** [comment] 2021-01-05 18:26
> Yeah, the behavior was surprising to me. It was unclear what was meant by "swap removal".

This uses `std.ArrayList().swapRemove()` which gives `O(1)` removal instead of `O(n)` removal by replacing the removed element with the last element in the list.

IMO `std.ArrayHashMap()`'s API should mirror that of `std.ArrayList()` and provide both `remove()` (ordered/ `O(n)`) and `swapRemove()` (unordered `O(1)`) functions.

**Comment by andrewrk** [comment] 2021-01-05 19:37
duplicate of  #7391 and we already have an open PR #7622

**Closed by andrewrk** 2021-01-05 19:37 UTC
