### ISSUE TITLE
Thread.Pool cannot be spawned with !void function

### ISSUE THREAD

**Issue by GreyAerin** [ziglang/zig#20127] opened 2024-05-30 16:10 UTC
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

When spawning std.Thread.Pool with a !void function, the error is ignored.

```zig
const std = @import("std");
const Thread = std.Thread;
const Pool = Thread.Pool;
const GPA = std.heap.GeneralPurposeAllocator;

pub fn main() !void {
    var gpa = GPA(.{}){};
    const allocator = gpa.allocator();
    defer {
        const status = gpa.deinit();
        if (status == .leak) @panic("Failure");
    }
    var pool = Pool{ .allocator = allocator, .threads = &[_]Thread{} };
    defer pool.deinit();
    try pool.spawn(errs, .{});
}

pub fn errs() !void {
    const not_valid_float = "1;00";
    _ = try std.fmt.parseFloat(f32, not_valid_float);
}
```

This minimal example returns the following error:

```
error: error is ignored
            @call(.auto, func, closure.arguments);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

Thread.Pool.spawn should handle errors similarly to Thread.spawn, returning the error to the main function to handle it. 

```zig
const std = @import("std");
const Thread = std.Thread;

pub fn main() !void {
    var thread = try Thread.spawn(.{}, errs, .{});
    thread.join();
}

pub fn errs() !void {
    const not_valid_float = "1;00";
    _ = try std.fmt.parseFloat(f32, not_valid_float);
}
```

This minimal example shows how one might expect Thread.Pool.spawn to behave, returning
```
error: InvalidCharacter
```

A similar issue was noted and fixed for Thread.Spawn in #4756.

**Comment by Vexu** [comment] 2024-05-30 17:32
Duplicate of #18810 (which is hard to find due to the title, I'll fix that)

**Closed by Vexu** 2024-05-30 17:32 UTC
Labels: bug
