### ISSUE TITLE
<Complex> and Quaternions/Vectors

### ISSUE THREAD

**Issue by BraedonWooding** [ziglang/zig#947] opened 2018-04-23 01:18 UTC
I think currently one of the big places Zig could be really useful is in data science, for this to occur Zig needs damn good math functionality including stuff like Quaternions and Vectors along with some good complex number support (quaternions are 4 tuple complex numbers if you don't know, furthermore quaternions do need good euler angle support for game dev).

I currently have a brief hackish solution for vectors, which currently only supports a single 3D vector though of course that means it supports 2D vectors (and has a few optimisations in place for those cases such as for getting the angle or doing a cross product).  Currently I implemented a quick invsqrt with a doom like fast inv sqrt which is more for game development where you only care about 1-2 decimal points of precision in some cases.

You can find it [here](https://github.com/BraedonWooding/zig/blob/Vec/std/math/vector.zig).

Anyways at minimum I'm going to make a library that holds them for my stuff, but I think they would be very valuable for the std lib.

**Comment by fithisux** [comment] 2018-04-24 09:34
I also believe that Zig can shine in scientific computing in general. There is a lot of code abandoned or written once and forgotten in universities or by post-grads for research purposes that carries a lot of value but is written in C or C++(in the C with objects style) or desperately slow Java in a very clumsy manner or after a fierce fight with compiler.

Zig can help here to do an incremental port from C-whatever to Zig and apply proper development best practices (without spending time to rewrite the code from scratch or manually transpile). There are other languages out there but Zig can focus on this area, from proteins, genomics to computational fluid dynamics or climate science. Computing is not only or webapps or mobileapps (people got it wrong).

**Comment by fithisux** [comment] 2018-04-25 07:35
@BraedonWooding : You have it right. Keep Zig a core part and make everything a library. Community should be able to build everything with Zig. The only requirements of Zig is ergonomics and enablement, no bloat not swiss army knife in the true spirit of C and Scheme.

**Comment by isaachier** [comment] 2018-07-01 01:33
@lerno I agree that might make more sense, but my own preference would be to keep fundamental types to those exposed by the LLVM IR. Otherwise, they are just additional features that need not be in the compiler. Furthermore, you might consider allowing operator overloads (like C++ and Ruby) if you prefer that syntax.

**Comment by lerno** [comment] 2018-07-01 07:09
I assumed operator overloading was out for Zig?

**Comment by lerno** [comment] 2018-07-01 12:18
From what I understand C is doing some form of overloading too in its support of complex numbers. The use case is not general operator overloading but specific overloading for certain basic math operations. General operator overloading is a bad idea.

**Comment by monouser7dig** [comment] 2018-07-01 12:29
Thats just super weird IMO, I did not know this but you're definitely right that its a "feature". 
But  c also has "generics" ... 

IMO if zig would acknowledge that op overloading is a useful feature, it should go all the way and make it accessible to all users (what about my own finite field arithmetic?) not only compiler supported types. Thus I don't think this fits onto zig anymore.

Maybe one possible option might be to allow op overloading for * / + - ^ or some subset of operations.

**Comment by isaachier** [comment] 2018-07-01 13:00
I think the issue with operator overloading is that it is too prone to abuse. So as I said originally, it is probably best to avoid relying on operators unless the type is fundamental. When it comes to fundamentals, the LLVM IR is probably the best way to decide.

**Comment by binary132** [comment] 2018-07-01 18:04
It seems like a lot of people want various built-in features that, while interesting, don't seem to fit with the spirit of Zig as a lean, mean C competitor.  I sometimes wonder if the right way to let them all get what they want is to support language extension via third-party package, a bit like Haskell's LANGUAGE pragma, but with an API that can support third-party extension and resolution of third-party LANGUAGE packages.

I certainly don't care for built-in operator-overloaded linear algebraic features, and I would prefer not to waste the time of core developers with many nice-to-have features.  But it _would_ be awesome if there way a way for interested parties to develop syntax packages.

**Comment by kyle-github** [comment] 2018-07-01 19:37
One problem with operator overloading, even for things like matrices, is that you so easily hide what is going on.   C++ takes this to an extreme where just seeing "a + b" gives you no real idea of what is going on.   Matrix addition?  String concatenation?  Set union?

Since Zig already started down the path of having + and +% and so on, perhaps there is a way to provide for some amount of operator overloading to make these things a little nicer on the eyes but still keep basic operations clear.   Perhaps names like "\_+\_" could be overloaded or something (do not take that particular syntax as a real proposal).   Then matrices could be added with "a \_+\_ b".  

Not a serious proposal, but perhaps there is some happy medium that allows external packages to provide almost the same syntax as built in things but still allow a very clear indication of when some operation needed more investigation before you automatically assume what it does.   If I see "add()", I know it is a function and I need to go look up what it does.  If I see "+", I have to know the types of both arguments in C++ and even then this gets hard with all the automatic coercion that goes on.  If I saw "\_+\_" I could treat it like "add()" and make the effort to find out what it really calls.

**Comment by phase** [comment] 2018-07-01 20:18
In [Why Zig When There is Already CPP, D, and Rust?](https://github.com/ziglang/zig/wiki/Why-Zig-When-There-is-Already-CPP%2C-D%2C-and-Rust%3F), Zig prides itself for not having hidden control flow, which I believe is a good decision. Something that can help users who want operator overloading but don't want the hidden function calls would be **explicit overloaded operators**.

`@` could be used as a prefix for operators that have been overloaded.

```zig
var c = a @+ b;
```

This tells the user that there _are_ hidden functions being called here, but we are _explicitly_ stating they are. Allowing structures to override these can make using libraries like a 3rd party Bignum library usable without being painful.

**Comment by 0joshuaolson1** [comment] 2018-07-01 20:59
I used to be a fan of mixfix operators (where overloaded `+` is a more common example). One issue is how to explicitly communicate what module the operator function came from:
```
a matrix_math.+ b;
```
is hardly better than
```
matrix_math.add(a, b)
```

**Comment by lerno** [comment] 2018-07-01 22:06
I think that @kyle-github raises a very important thing: overloaded operators end up being very confusing because they look fundamental yet they are not. I fully agree with that being a problem.

Also, overloading a few operators will still mean quite a few are either using ”wrong” symbols or has to be represented as functions.

As an example, consider the dot and cross product of two vectors. The dot product might use ’*’ but what of the cross product? Unless we’re adding crazy stuff like unicode operators (which swift already demonstrated is a horrible idea)

I don’t have a perfect solution for this, but if we look at Fortran it already has specialized ways to perform operations across slices of a matrix, eg `A(1:7, 4:9) = A(2:8, 4:9) + B(2:8, 2:7)` which essentially means that for each element i the range col 1-7, row 4-9 we perform `A[col, row] = A[col + 1, row] + B[col + 1, row - 2]`

This is not to suggest Zig copy Fortran, but to show what it would be up against if trying to compete in that domain.

**Comment by isaachier** [comment] 2018-07-01 22:39
@lerno the lucky thing with Fortran matrices is that those operations actually correspond to compiler intrinsics. They can be represented as vectors (https://llvm.org/docs/LangRef.html#vector-type), which have special SIMD support (#444, #903). In those cases I strongly recommend the compiler support the type as a fundamental.

**Comment by mantielero** [comment] 2019-06-13 16:04
Despite it is chinese to me, I found [this thread](https://news.ycombinator.com/item?id=13205899) pretty interesting. It is about what makes Fortran so good for numerical computation, and why it continues to be used instead of C, C++, Rust, ... 

They say things like:

> Multi-dimensional arrays, non-aliasing arrays and pointers, multi-dimensional array intrinsics, intrinsic array binary operators... all come with Fortran right out of the box

> Rust has great potential to challenge Fortran in this domain, but numerics is mostly an afterthought in Rust.

So maybe, even if it is not implemented anytime soon, it looks like it might be a good idea to bear in mind this sort of things in mind.

**Comment by jeremyong** [comment] 2019-10-17 13:56
I'd like to chime in and say that I think allowing users to define numeric types (not just complex, quaternion, but also dual units, dual quaternions, bivectors, etc) would be hugely beneficial (science, math, computer graphics).

Operator overloading can certainly be abused, but for numeric types, they really are the most (and some may say only) way to realistic express more complicated expressions, They obey laws of associativity, commutivity, and precedence as you would expect, and can be self-documenting used judiciously.

I'm looking at porting over some code from C++ now, and I have to say, the operator part is the only thing that makes me nervous (compare even `a * b * ~a` vs `product(a, product(b, reverse(a)))`). Expressions much longer than this (I have many) will veer on the unreadable side unfortunately.

**Comment by emekoi** [comment] 2019-10-17 15:42
related #427

**Comment by momumi** [comment] 2020-01-01 12:43
For math heavy code, it would be really nice to have some form of operator overloading. I'd really rather write `z + z*y + y*y + 1` instead of `z.add((y.mul(y)).add(z.mul(y))).add(1)`.

Instead of adding full blown operator overloading, how about introducing a new type say the `MathType`.  The `MathType` would essential be identical to a struct but certain methods could be used to overload the basic operators.

Also, similar to how `var` keyword matches any type, the `MathType` would match the primitive numeric types as well as other `MathType`. Here's an example of how it might look:

```
const Complex = MathType {
    pub real: i64 = 0,
    pub imag: i64 = 0,

    pub fn add_left(self: Complex, rhs: MathType) Complex {
        // Complex + rhs
    }

    pub fn add_right(lhs: MathType, self: Complex) Complex {
        // lhs + Complex
        //
        // if lhs is a MathType but doesn't provide lhs.add_left, use this func
    }

    pub fn mul_left(self: Complex, rhs: MathType) Complex {
        // Complex * rhs
    }

    pub fn mul_right(lhs: MathType, self: Complex) Complex {
        // lhs * Complex
    }

    pub fn equal(self: Complex, other: MathType) bool {
        // lhs == Complex
        // Complex == lhs
    }

    pub fn assign(self: Complex, rhs: MathType) void {
        // Complex = rhs
    }
};

test "complex" {
    var z: Complex = 1;
    var y: Complex = Complex {.real = 1, .imag = 1};

    // calls all the right functions based on standard operator precedence
    z = z + z*y + y*y + 1; // z = z.add_left(y.mul_left(y).add_left(z.mul_left(y))).add_left(1)
    z = 1 + z; // z = z.add_right(1)
    assert(z == Complex{.real=3, .imag=1});
}
```

The `MathType` would help prevent operator overloading abuse since overloading would be restricted to only the `MathType`, and I doubt people would replace all their structs with `MathType` to abuse it either. For example this would prevent code like this:

```
var cout = Outstream.init();
cout << "hello world" << .Endl; // not possible: no way to overload << for []const u8 type
```

This would make the functions in `std.math` nicer too imo, since they could use function signatures like `fn max(a:MathType, b:MathType) MathType` instead of `fn max(a:var, b:var) var`.

I think the biggest issue is error handling.  In most cases I think it is fine to require the use to validate input and just panic on bad values, e.g:

```
if (scale != 0) {
    var result = vector / scale;
}
```

However types like BigInt which might allocate memory to grow in size would probably need some way to fail while returning an error. For this case, maybe it could work like this:

```
const BigInt = MathType {
    // ...
    pub fn init(alloc: Allocator, MathType) !BigInt {
        //
    }

    pub fn add_left(self: !BigInt, rhs: MathType) !BigInt {
        if (self) |val| {
            // do calculation
            if (no_memory) {
                return error.OutOfMemory;
            }
            return new_val;
        } else |err| {
            // if we got an error forward it on to the caller
            return err;
        }
    }

    pub fn equal(self: BigInt, rhs: MathType) bool {
        // check equal
    }
}

test "bigint" {
    var a = BigInt.init(allocator, 1);
    var b = BigInt.init(allocator, 1);
    defer a.free();
    defer b.free();

    // if one of these math functions fails, it will propagate the error all
    // the way back to `a`
    var c = a*a + 2*a*b + b*b;
    defer c.free();

    // fails to compile, didn't unwrap the error
    // assert(c == 2);

    if (c) |val| {
        assert(val == 2);
    } else |err| {
        assert(false); // got some error
    }
}
```

This last example seems like it has issues since this expression `var c = a*a + 2*a*b + b*b;` would need to allocate memory for `c`. How do intermediate values get handled?  Does the BigInt class need a destructor??

Anyway just throwing some ideas out there; I'm not fully sure on all this myself. Things look fine for objects with a static memory requirements, but objects with dynamic memory requirements seem a bit hairy.

**Comment by tauoverpi** [comment] 2020-09-13 19:25
Could be possible to constrain overloading to anything without function calls which makes what you can do at the mercy of base operators. That at least forces a complete definition of the overload in one place and makes it painful enough to not go crazy on abuse. It's then not possible to allocate, concat, call out to magic procedures, etc, yet possible to gain convenience in operator use for at least some of the usecases while not violating the hidden control-flow rule.

**Comment by ityonemo** [comment] 2020-10-29 01:31
for some reason I was thinking about this today.  There is something clean about zig not allowing operator overloading for basic operators (each one implies no hidden function calls).  But I think the issue is really "maybe we should have some functions that can have infix calls).  I'd suggest, say allowing something like "a <+> b" for a generalized addition that you must import into the local scope by "usingnamespace" or something or other.  It might be nice if you could also have unicode operators, like "a <⊕> b".  You could also require such a thing to have parenthesis https://github.com/ziglang/zig/issues/114

Only problem is that this is not necessarily composable, if you have say, a matrix direct sum, and wanted to overload the internal +/- operators for this function (like let's say you want to do matrices over quaternions or GF256)...  But I feel like there might be a clever way of doing this with comptime, even.

**Comment by andrewrk** [comment] 2024-03-28 21:31
Proposal is too vague; closing.

**Closed by andrewrk** 2024-03-28 21:31 UTC
Labels: standard library, proposal
