### ISSUE TITLE
"This is a bug in the Zig compiler."

### ISSUE THREAD

**Issue by recombinant** [ziglang/zig#7306] opened 2020-12-04 18:33 UTC
```
$ uname -a
Linux recombinant-virtualbox 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux

$ zig version
0.7.0+b6b7a6401

$ zig test World.zig
Code Generation [550/734] std.mem.Allocator.allocAdvancedWithRetAddr... broken LLVM module found: Expected no forward declarations!
!2811 = <temporary!> !DICompositeType(tag: DW_TAG_structure_type, name: "Light.Light", scope: !2812, file: !2812, line: 5, flags: DIFlagFwdDecl)

This is a bug in the Zig compiler.
/home/stephen/3rdParty/zig/src/stage1.zig:168:5: 0x5584eac4924c in stage2_panic (zig1)
    @panic(ptr[0..len]);
    ^
../src/stage1/util.cpp:20:17: 0x5584eb5ef6cd in zig_panic (../src/stage1/util.cpp)
../src/stage1/codegen.cpp:8413:18: 0x5584eb614c9f in do_code_gen (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:9553:16: 0x5584eb6198bb in codegen_build_object (../src/stage1/codegen.cpp)
../src/stage1/stage1.cpp:127:25: 0x5584eb5eb1d2 in zig_stage1_build_object (../src/stage1/stage1.cpp)
/home/stephen/3rdParty/zig/src/stage1.zig:140:32: 0x5584eaf5f0d4 in Module.build_object (zig1)
        zig_stage1_build_object(mod);
                               ^
/home/stephen/3rdParty/zig/src/Compilation.zig:2962:31: 0x5584eadb8c90 in Compilation.updateStage1Module (zig1)
    stage1_module.build_object();
                              ^
/home/stephen/3rdParty/zig/src/Compilation.zig:1502:36: 0x5584ead7433e in Compilation.performAllTheWork (zig1)
            self.updateStage1Module(main_progress_node) catch |err| {
                                   ^
/home/stephen/3rdParty/zig/src/Compilation.zig:1198:31: 0x5584ead6e577 in Compilation.update (zig1)
    try self.performAllTheWork();
                              ^
/home/stephen/3rdParty/zig/src/main.zig:1910:20: 0x5584ead1c1a6 in main.updateModule (zig1)
    try comp.update();
                   ^
/home/stephen/3rdParty/zig/src/main.zig:1772:17: 0x5584eac7012a in main.buildOutputType (zig1)
    updateModule(gpa, comp, zir_out_path, hook) catch |err| switch (err) {
                ^
/home/stephen/3rdParty/zig/src/main.zig:166:31: 0x5584eac48096 in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/stephen/3rdParty/zig/src/stage1.zig:45:24: 0x5584eac478ae in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
zsh: abort (core dumped)  zig test World.zig
~/OORT.bug >>> zig test World.zig                                                                                                                                   [134]
Code Generation [557/734] std.mem.Allocator.allocAdvancedWithRetAddr... broken LLVM module found: Expected no forward declarations!
!2811 = <temporary!> !DICompositeType(tag: DW_TAG_structure_type, name: "Light.Light", scope: !2812, file: !2812, line: 5, flags: DIFlagFwdDecl)

This is a bug in the Zig compiler.
/home/stephen/3rdParty/zig/src/stage1.zig:168:5: 0x5616743ca24c in stage2_panic (zig1)
    @panic(ptr[0..len]);
    ^
../src/stage1/util.cpp:20:17: 0x561674d706cd in zig_panic (../src/stage1/util.cpp)
../src/stage1/codegen.cpp:8413:18: 0x561674d95c9f in do_code_gen (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:9553:16: 0x561674d9a8bb in codegen_build_object (../src/stage1/codegen.cpp)
../src/stage1/stage1.cpp:127:25: 0x561674d6c1d2 in zig_stage1_build_object (../src/stage1/stage1.cpp)
/home/stephen/3rdParty/zig/src/stage1.zig:140:32: 0x5616746e00d4 in Module.build_object (zig1)
        zig_stage1_build_object(mod);
                               ^
/home/stephen/3rdParty/zig/src/Compilation.zig:2962:31: 0x561674539c90 in Compilation.updateStage1Module (zig1)
    stage1_module.build_object();
                              ^
/home/stephen/3rdParty/zig/src/Compilation.zig:1502:36: 0x5616744f533e in Compilation.performAllTheWork (zig1)
            self.updateStage1Module(main_progress_node) catch |err| {
                                   ^
/home/stephen/3rdParty/zig/src/Compilation.zig:1198:31: 0x5616744ef577 in Compilation.update (zig1)
    try self.performAllTheWork();
                              ^
/home/stephen/3rdParty/zig/src/main.zig:1910:20: 0x56167449d1a6 in main.updateModule (zig1)
    try comp.update();
                   ^
/home/stephen/3rdParty/zig/src/main.zig:1772:17: 0x5616743f112a in main.buildOutputType (zig1)
    updateModule(gpa, comp, zir_out_path, hook) catch |err| switch (err) {
                ^
/home/stephen/3rdParty/zig/src/main.zig:166:31: 0x5616743c9096 in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/stephen/3rdParty/zig/src/stage1.zig:45:24: 0x5616743c88ae in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
zsh: abort (core dumped)  zig test World.zig
~/OORT.bug >>> zig test World.zig                                                                                                                                   [134]
./World.zig:67:6: error: no member named 'setDepthLimit' in struct 'World'
    w.setDepthLimit(3);
     ^
~/OORT.bug >>> zig test World.zig                                                                                                                                     [1]
Code Generation [540/734] std.mem.Allocator.resize... broken LLVM module found: Expected no forward declarations!
!2811 = <temporary!> !DICompositeType(tag: DW_TAG_structure_type, name: "Light.Light", scope: !2812, file: !2812, line: 5, flags: DIFlagFwdDecl)

This is a bug in the Zig compiler.
/home/stephen/3rdParty/zig/src/stage1.zig:168:5: 0x558a25b7024c in stage2_panic (zig1)
    @panic(ptr[0..len]);
    ^
../src/stage1/util.cpp:20:17: 0x558a265166cd in zig_panic (../src/stage1/util.cpp)
../src/stage1/codegen.cpp:8413:18: 0x558a2653bc9f in do_code_gen (../src/stage1/codegen.cpp)
../src/stage1/codegen.cpp:9553:16: 0x558a265408bb in codegen_build_object (../src/stage1/codegen.cpp)
../src/stage1/stage1.cpp:127:25: 0x558a265121d2 in zig_stage1_build_object (../src/stage1/stage1.cpp)
/home/stephen/3rdParty/zig/src/stage1.zig:140:32: 0x558a25e860d4 in Module.build_object (zig1)
        zig_stage1_build_object(mod);
                               ^
/home/stephen/3rdParty/zig/src/Compilation.zig:2962:31: 0x558a25cdfc90 in Compilation.updateStage1Module (zig1)
    stage1_module.build_object();
                              ^
/home/stephen/3rdParty/zig/src/Compilation.zig:1502:36: 0x558a25c9b33e in Compilation.performAllTheWork (zig1)
            self.updateStage1Module(main_progress_node) catch |err| {
                                   ^
/home/stephen/3rdParty/zig/src/Compilation.zig:1198:31: 0x558a25c95577 in Compilation.update (zig1)
    try self.performAllTheWork();
                              ^
/home/stephen/3rdParty/zig/src/main.zig:1910:20: 0x558a25c431a6 in main.updateModule (zig1)
    try comp.update();
                   ^
/home/stephen/3rdParty/zig/src/main.zig:1772:17: 0x558a25b9712a in main.buildOutputType (zig1)
    updateModule(gpa, comp, zir_out_path, hook) catch |err| switch (err) {
                ^
/home/stephen/3rdParty/zig/src/main.zig:166:31: 0x558a25b6f096 in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/stephen/3rdParty/zig/src/stage1.zig:45:24: 0x558a25b6e8ae in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
zsh: abort (core dumped)  zig test World.zig
```

[bug.zip](https://github.com/ziglang/zig/files/5644662/bug.zip)

**Comment by Vexu** [comment] 2020-12-04 18:40
Duplicate of #5197.

**Closed by Vexu** 2020-12-04 18:40 UTC
