### ISSUE TITLE
Compilation error in std library

### ISSUE THREAD

**Issue by donaldcallen** [ziglang/zig#16868] opened 2023-08-18 02:15 UTC
### Zig Version

0.12.0-dev.109+f3f554b9b

### Steps to Reproduce and Observed Behavior

````
dca@giovanni:/home/dca/Software/newcash_zig/verifier$ make
zig build-exe  -freference-trace=100 --main-pkg-path .. -fsingle-threaded -L/usr/local/lib -L/usr/lib -lc -lsqlite3 -l'glib-2.0' src/verifier.zig
/usr/home/dca/bin/FreeBSD/lib/zig/std/mem.zig:4143:9: error: expected []T or *[_]T, passed *const u8
        @compileError("expected []T or *[_]T, passed " ++ @typeName(Slice));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/home/dca/bin/FreeBSD/lib/zig/std/mem.zig:4150:59: note: called from here
pub fn sliceAsBytes(slice: anytype) SliceAsBytesReturnType(@TypeOf(slice)) {
                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
make: *** [makefile:7: verifier] Error 1

````

### Expected Behavior

I don't expect to see compilation errors in the std library.

I would also note that I added -freference-trace=100 to the invocation of the compiler to increase the number of lines of backtrace in an attempt to see where in my code the library was called. This didn't work either.

**Comment by ianprime0509** [comment] 2023-08-18 02:33
Duplicate of #16580

**Comment by jacobly0** [comment] 2023-08-18 08:33
Duplicate of #14335

**Closed by jacobly0** 2023-08-18 08:33 UTC
Labels: bug

**Comment by jacobly0** [comment] 2023-08-25 18:08
Duplicate of #15124
