### ISSUE TITLE
Spurious "field name must be comptime-known" error

### ISSUE THREAD

**Issue by ifreund** [ziglang/zig#14850] opened 2023-03-08 21:32 UTC
### Zig Version

0.11.0-dev.1905+e3cf9d165

### Steps to Reproduce and Observed Behavior

```zig
const system = @import("std").os.system;

fn genSignalNames() void {
    for (@typeInfo(system.SIG).Struct.decls) |decl| {
        _ = @field(system.SIG, decl.name);
    }
}
test {
    _ = comptime genSignalNames();
}
```
```
/tmp/foo.zig:5:36: error: unable to resolve comptime value
        _ = @field(system.SIG, decl.name);
                               ~~~~^~~~~
/tmp/foo.zig:5:36: note: field name must be comptime-known
referenced by:
    test_0: /tmp/foo.zig:10:18
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```
I was unable to reproduce this with a trivial struct, I assume that this error occurs with `std.os.system` due to something `usingnamespace` related.

### Expected Behavior

The compilation should succeed.

**Comment by Vexu** [comment] 2023-03-08 21:49
Duplicate of #6256

**Closed by Vexu** 2023-03-08 21:49 UTC
Labels: bug, stage2

**Comment by ifreund** [comment] 2023-03-08 21:52
@Vexu the fact that this compiles made me think that the issue is something else:
```

const Foo = struct {
    a: u32,
};

fn genSignalNames() void {
    for (@typeInfo(Foo).Struct.decls) |decl| {
        _ = @field(Foo, decl.name);
    }
}

test {
    _ = comptime genSignalNames();
}
```

**Comment by Vexu** [comment] 2023-03-08 21:54
> this compiles

Not if you add a declaration to `Foo`.

**Comment by ifreund** [comment] 2023-03-08 21:55
> Not if you add a declaration to `Foo`.

ah whoops, that was dumb. Thanks!
