### ISSUE TITLE
Failed to compile a "Hello World" program on Windows

### ISSUE THREAD

**Issue by hronro** [ziglang/zig#10457] opened 2021-12-30 16:14 UTC
### Zig Version

0.9.0

### Steps to Reproduce

```zig
// src/main.zig

const std = @import("std");
const stdout = std.io.getStdOut().writer();

pub fn main() anyerror!void {
  try stdout.print("Hello World\n", .{});
}
```

Run `zig build` on Windows or run `zig build -Dtarget=x86_64-windows-gnu` on Linux.

### Expected Behavior

Build successfully.

### Actual Behavior

Got an error:

```
/lib/std/os/windows.zig:1733:20: error: unable to evaluate constant expression
        .x86_64 => asm volatile (
                   ^
```

**Comment by Vexu** [comment] 2021-12-31 18:16
Duplicate of #6845, `getStdOut` only works at runtime on windows.

**Closed by Vexu** 2021-12-31 18:16 UTC
Labels: bug
