### ISSUE TITLE
Bug in the zig compiler

### ISSUE THREAD

**Issue by alexpana** [ziglang/zig#7496] opened 2020-12-19 10:19 UTC
Using the following program (WIP solution for advent of code day 18): https://gist.github.com/alexpana/e47c462e5a48c0edf3ddc8908d391605

I get the following error:

```
broken LLVM module found: PHI node entries do not match predecessors!
  %31 = phi i1 [ %24, %WhileCond1 ], [ %30, %BoolAndTrue ], !dbg !5764
label %BoolAndTrue
label %WhileCond1
Instruction does not dominate all uses!
  %30 = phi i1 [ true, %CmpOptionalNonOptionalOptionalNull ], [ %29, %CmpOptionalNonOptionalOptionalNotNull ], !dbg !5766
  %31 = phi i1 [ %24, %WhileCond1 ], [ %30, %BoolAndTrue ], !dbg !5764

This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
```

Zig compiler version: `0.7.1+506af7e52`
Platform: windows
Executing the program with `zig run main.zig`

**Comment by alexpana** [comment] 2020-12-19 10:21
Issue appears to be with https://gist.github.com/alexpana/e47c462e5a48c0edf3ddc8908d391605#file-advent18-zig-L159

Removing `!ops.isEmpty()` from the condition makes the error go away.

**Comment by Vexu** [comment] 2020-12-19 10:33
Duplicate of #6059.

**Closed by Vexu** 2020-12-19 10:33 UTC
