### ISSUE TITLE
Segfault with function as return type

### ISSUE THREAD

**Issue by ii8** [ziglang/zig#19600] opened 2024-04-10 14:25 UTC
`F4` below segfaults even when called with `L == 10`.
Is it possible to do the same as `F1` except return the function directly instead of a struct containing the function?

```zig
const std = @import("std");

fn child(comptime T: type) type {
  return @typeInfo(T).Array.child;
}

fn len(comptime T: type) comptime_int {
  return @typeInfo(T).Array.len;
}

// This works as expected.
pub fn F1(comptime I: comptime_int,
          comptime O: comptime_int) type
{
  return struct {
    //     apply(in: [I][L]f32) [O][L]f32
    pub fn apply(in: anytype) [O]child(@TypeOf(in)) {
      std.debug.assert(len(@TypeOf(in)) == I);
      const L = len(child(@TypeOf(in)));
      return std.mem.zeroes([O][L]f32);
    }
  };
}

//src/main.zig:26:48: error: expected return type expression, found 'anytype'
//          comptime O: comptime_int) fn(anytype) anytype
//                                                ^~~~~~~
pub fn F2(comptime I: comptime_int,
          comptime O: comptime_int) fn(anytype) anytype
{
  return struct {
    pub fn apply(in: anytype) [O]child(@TypeOf(in)) {
      std.debug.assert(len(@TypeOf(in)) == I);
      const L = len(child(@TypeOf(in)));
      return std.mem.zeroes([O][L]f32);
    }
  }.apply;
}

//src/main.zig:42:69: error: use of undeclared identifier 'in'
//          comptime O: comptime_int) fn(in: anytype) [O]child(@TypeOf(in))
//                                                                     ^~
pub fn F3(comptime I: comptime_int,
          comptime O: comptime_int) fn(in: anytype) [O]child(@TypeOf(in))
{
  return struct {
    pub fn apply(in: anytype) [O]child(@TypeOf(in)) {
      std.debug.assert(len(@TypeOf(in)) == I);
      const L = len(child(@TypeOf(in)));
      return std.mem.zeroes([O][L]f32);
    }
  }.apply;
}

// segfault
pub fn F4(comptime I: comptime_int,
          comptime O: comptime_int) fn(anytype) [O][10]f32
{
  return struct {
    pub fn apply(in: anytype) [O]child(@TypeOf(in)) {
      std.debug.assert(len(@TypeOf(in)) == I);
      const L = len(child(@TypeOf(in)));
      return std.mem.zeroes([O][L]f32);
    }
  }.apply;
}
```

zig version: 0.12.0-dev.3610+9d27f34d0

**Comment by Rexicon226** [comment] 2024-04-10 14:32
Issue stems from the `anytype` in the function proto.
Minimal repro:
```zig
fn Foo() fn (anytype) void {
    return undefined;
}

pub fn main() void {
    Foo();
}
```

**Comment by Rexicon226** [comment] 2024-04-10 17:03
also, likely a duplicate of #17445

**Closed** 2024-04-11 06:34 UTC
Labels: bug
