### ISSUE TITLE
`zig cc -target aarch64-macos-gnu` fails with `FrameworkNotFound` when used with cgo

### ISSUE THREAD

**Issue by charleskorn** [ziglang/zig#10513] opened 2022-01-05 05:19 UTC
### Zig Version

0.9.0

### Steps to Reproduce

I've created a repository https://github.com/charleskorn/zig-cgo-libs that contains a sample project, build script (`./build.sh`) and GitHub Actions workflow ([sample build](https://github.com/charleskorn/zig-cgo-libs/actions/runs/1656915873)) that demonstrates the problem. 

To reproduce this for yourself, clone the repository and run `./build.sh`. 

The tl;dr appears to be: when using Zig as a C compiler for Golang's cgo, Zig fails to find the CoreFoundation framework if `-target` is specified explicitly. ie. `zig cc -target aarch64-macos-gnu ...` fails, but if I compile on my M1 Mac with no `-target`, the build succeeds.

I've passed `--sysroot` with the path provided by `xcrun --show-sdk-path`, as suggested in https://github.com/ziglang/zig/issues/10299#issuecomment-989046151.

### Expected Behavior

Build succeeds.

### Actual Behavior

Build fails with a `FrameworkNotFound` error, and a warning that the framework could not be found (and that there are no framework search paths):

```
warning(link): framework not found for '-framework CoreFoundation'
warning(link): Framework search paths:
error: FrameworkNotFound
```

I can see `zig` is being invoked with the expected arguments, for example:

```
zig cc -target aarch64-macos-gnu --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -I /opt/homebrew/Cellar/go/1.17.5/libexec/src/runtime/cgo -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7t/_rsz39554vvgvq2t6b4ztktc0000gn/T/go-build3089540943/b017=/tmp/go-build -gno-record-gcc-switches -fno-common -o $WORK/b017/_cgo_.o $WORK/b017/_cgo_main.o $WORK/b017/_x001.o $WORK/b017/_x002.o $WORK/b017/_x003.o $WORK/b017/_x004.o $WORK/b017/_x005.o $WORK/b017/_x006.o $WORK/b017/_x007.o $WORK/b017/_x008.o $WORK/b017/_x009.o -g -O2 -framework CoreFoundation
```

I see the same behaviour on both M1 and Intel hosts.

**Comment by kubkon** [comment] 2022-01-05 12:39
You need to manually specify include, library and framework search dirs for this to work. In cross-compilation mode, which Zig enters when you explicitly specify the target, no search paths are populated since we don't know where to expect them. Passing the sysroot is one thing, the next should be specifying `-I/usr/include`, `-F/System/Library/Frameworks` and `-L/usr/lib`. Have a look at [github.com/kubkon/zig-ios-example](https://github.com/kubkon/zig-ios-example/blob/dbaf621051e9ae151bf9909673a62baad6a41e2b/build.zig#L32) to see how this can be done in `build.zig`. For CGO, I guess you will need to either pass those manually, or put them in some CGO flags, perhaps?

**Comment by charleskorn** [comment] 2022-01-06 00:54
Thanks for the tip @kubkon - I had to use `-I<sysroot>/usr/include`, `-F<sysroot>/System/Library/Frameworks` and `-L<sysroot>/usr/lib`, but that was enough to get things working. 

Are there any other settings set by default when not specifying `-target` that I should be using? I also had to add `-Wno-expansion-to-defined -Wno-availability -Wno-nullability-completeness` to suppress a bunch of warnings that aren't generated when not specifying `-target`.

**Comment by andrewrk** [comment] 2022-02-02 22:14
Duplicate of #1349 and #10660.

**Closed by andrewrk** 2022-02-02 22:14 UTC
Labels: question

**Comment by charleskorn** [comment] 2022-02-04 05:54
@andrewrk it looks like there are two issues here:

* the original issue, which was that specifying `-target` isn't enough, which is a duplicate of #1349 and #10660
* the issue I encountered after fixing that problem, which is that a number of warnings are generated when specifying `-target` and all the necessary directory arguments, and these warnings aren't emitted if compiling without `-target`, which seem unrelated to #1349 and #10660 unless I'm missing something

Do you want me to open a separate issue for the second part?

**Comment by andrewrk** [comment] 2022-02-04 05:56
Yes please :+1:

**Comment by kubkon** [comment] 2022-02-04 08:29
> @andrewrk it looks like there are two issues here:
> 
> * the original issue, which was that specifying `-target` isn't enough, which is a duplicate of [ability to link against darwin frameworks (such as CoreFoundation) when cross compiling #1349](https://github.com/ziglang/zig/issues/1349) and [When I cross compile cgo to macos, undefined reference to symbols inside frameworks #10660](https://github.com/ziglang/zig/issues/10660)
> * the issue I encountered after fixing that problem, which is that a number of warnings are generated when specifying `-target` and all the necessary directory arguments, and these warnings aren't emitted if compiling without `-target`, which seem unrelated to [ability to link against darwin frameworks (such as CoreFoundation) when cross compiling #1349](https://github.com/ziglang/zig/issues/1349) and [When I cross compile cgo to macos, undefined reference to symbols inside frameworks #10660](https://github.com/ziglang/zig/issues/10660) unless I'm missing something
> 
> Do you want me to open a separate issue for the second part?

Is it by any chance related to and fixed by https://github.com/ziglang/zig/pull/10568? If so, this fix should land in 0.9.1 I believe - cc'ing @andrewrk to confirm he cherry-picked the commit from the linked PR.

**Comment by andrewrk** [comment] 2022-02-04 17:53
Confirmed, it's in the 0.9.x branch as 3542dcad33f5e2021caeb897857b7cc3a57f2c23.

**Comment by charleskorn** [comment] 2022-02-04 23:11
> Yes please 👍

Done: https://github.com/ziglang/zig/issues/10790
