### ISSUE TITLE
Vector comparisons should not have result type bool

### ISSUE THREAD

**Issue by andersfr** [ziglang/zig#2884] opened 2019-07-13 15:07 UTC
Vector types generates special mask-like results for their comparisons.
Below is an example of the problem and a software emulation that LLVM can optimise into the appropriate hardware instruction.

```zig
const V = @Vector(16, i8);

fn equal_zig_assumes_result_is_bool(left: V, right: V) V {
    return left == right;
}

fn equal_emulate_hardware(left: V, right: V) V {
    const vl = @ptrCast([*]const i8, &left);
    const vr = @ptrCast([*]const i8, &right);
    var v: V = undefined;
    const arr = @ptrCast([*]i8, &v);

    var i: usize = 0;
    while (i < 16) : (i += 1) {
        if (vl[i] == vr[i]) {
            arr[i] = -1;
        } else {
            arr[i] = 0;
        }
    }

    return v;
}
```

**Comment by andrewrk** [comment] 2019-07-13 16:26
This is a not-yet-implemented part of SIMD (#903)

**Comment by shawnl** [comment] 2019-07-26 19:23
Duplicate of #2698, for which there is a proposed patch.

**Comment by andrewrk** [comment] 2019-09-20 22:05
Yeah dupe of #2698

**Closed by andrewrk** 2019-09-20 22:05 UTC
