### ISSUE TITLE
compiler crash evaluating sizeOf packed struct

### ISSUE THREAD

**Issue by billzez** [ziglang/zig#13447] opened 2022-11-05 05:25 UTC
### Zig Version

0.11.0-dev.63+8c4faa5f3

### Steps to Reproduce and Observed Behavior

```
const Header = packed struct {
    x: u32,
};

fn check(src: []const u8) void {
    if (src.len < @sizeOf(Header)) {}
}

pub fn main() void {
    check("");
}
```

### Expected Behavior

Compiles.

**Comment by Vexu** [comment] 2022-11-05 11:01
Duplicate of #12498

**Closed by Vexu** 2022-11-05 11:01 UTC
Labels: bug, stage2
