### ISSUE TITLE
when handling a returned error, if the expression/block does not try/return error, reset error return trace index to 0

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#1923] opened 2019-02-06 20:10 UTC
When trying to run the first example code from #1813 with an executable that can't be found, the error trace is weird. It looks like the return address array is filled with addresses from `windowsCreateProcess`.
I believe this is due to the loop in `spawnWindows` that tries every directory from `PATH` and returns a lot of errors because the file doesn't exist.

As for why it is sometimes `PATH_NOT_FOUND` and others `FILE_NOT_FOUND`, I assume my `PATH` contains some old directories that don't exist anymore.

Example output:
```
$ zig run childprocess.zig
error: Unexpected
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\index.zig:2253:5: 0x7ff663aa3442 in unexpectedErrorWindows (run.obj)
    return error.Unexpected;
    ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:696:21: 0x7ff663ac4a5d in windowsCreateProcess (run.obj)
            else => return os.unexpectedErrorWindows(err),
                    ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:611:21: 0x7ff663ac34d6 in ChildProcess::ChildProcess_spawnWindows (run.obj)
                    return err;
                    ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:127:13: 0x7ff663ac09ce in ChildProcess::ChildProcess_spawn (run.obj)
            return self.spawnWindows();
            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:209:9: 0x7ff663ac01bb in ChildProcess::ChildProcess_exec (run.obj)
        try child.spawn();
        ^
D:\DEV\Zig\error-traces\childprocess.zig:5:18: 0x7ff663abff2a in main (run.obj)
  const result = try std.os.ChildProcess.exec(
                 ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
```

**Comment by andrewrk** [comment] 2019-02-06 23:35
I think there are 2 components to this issue:
 * bug: the stack trace printer is printing the error return trace in backwards (or otherwise incorrect) order
 * enhancement: "caught" errors still show up in errror return traces. This is a little tricky because we can definitely change the behavior but it has performance implications to consider.

**Comment by Sahnvour** [comment] 2019-02-07 12:46
`catch` and `if else` don't decrement `stack_trace.index` at the moment ?

**Comment by andrewrk** [comment] 2019-02-07 15:11
That's correct - and intentional. The example in the docs here shows how this is useful: https://ziglang.org/documentation/master/#Error-Return-Traces

If we wanted to avoid giving this up, what we could do is "reset" the error return trace when a function returns a non-error, by setting the index to 0. This would solve the problem, but require an extra memory store for every `return` in functions which return error unions. (Maybe that is OK and worth it)

**Comment by Sahnvour** [comment] 2019-02-07 17:52
I think that would be insufficient, in my example as the executable is never found, it would still keep all of `windowsCreateProcess`'s errors since it always returned an error, but the first line we want to see in the error trace is https://github.com/ziglang/zig/blob/7843c96df87007561c107d11afa2fa74b46667fd/std/os/child_process.zig#L613-L616

How about this : in a `catch` or `else` (handling a returned error), if the block does not `try` or `return error.xyz`, set the index to 0 ?

**Comment by andrewrk** [comment] 2019-02-08 04:40
> How about this : in a `catch` or `else` (handling a returned error), if the block does not `try` or `return error.xyz`, set the index to 0 ?

I like this idea a lot! And I think it will be straightforward to implement too. :100: from me

**Comment by andrewrk** [comment] 2019-02-08 05:13
BTW I believe this is a duplicate of #1810

**Comment by andrewrk** [comment] 2019-02-26 23:15
Closing as a duplicate of #1810 but with the note that @Sahnvour's proposed fix in https://github.com/ziglang/zig/issues/1923#issuecomment-461530246 is planned.

**Comment by andrewrk** [comment] 2019-02-27 15:53
I don't know why I thought this was a duplicate of #1810. The issues are entirely unrelated.

**Comment by FireFox317** [comment] 2020-10-02 08:15
I'm implementing this (have working code that resets the index), but it's not clear to me where to put that code in the catch/else block. There are a few options:
1. If no try/error then place the reset index code at the beginning of a block
    However this breaks the error return trace printing in start.zig:
```zig
           loop.init() catch |err| {
                std.log.err("{}", .{@errorName(err)});
                if (@errorReturnTrace()) |trace| {
                    std.debug.dumpStackTrace(trace.*);
                }
                return 1;
            };
```
To solve that we might want to check for a `@errorReturnTrace` in the block too?

2. If no try/error then place the code at the end of a block
      In that case a catch could return early (still success) but then the index is not reset to zero.

I'm not sure what would be the best solution.

**Comment by Sahnvour** [comment] 2020-10-03 08:43
I think we could emit a single control flow block to do the reset to 0 (it's only a constant write to a static variable right ?), and have all returns and such jump to it. It shouldn't need any stack or registers so that's fine ? However I don't know if that is possible as is with LLVM.

If not, I would go for 3. and put a redundant block before any return/break/end of zig block. The optimizer should be able to get away with it, and at least that is a simple implementation we can still reevaluate in the future if need be.

**Comment by danielchasehooper** [comment] 2022-05-06 14:44
FWIW: I made a super simple repro case of this in issue #11593. Might make for a good automated test

**Comment by danielchasehooper** [comment] 2022-06-14 20:43
Until this bug is fixed, Is there a way to manually clear the error return trace? Having all the irrelevant traces is making debugging code really annoying.

**Comment by squeek502** [comment] 2022-07-31 08:12
> Is there a way to manually clear the error return trace?

After an error is handled without returning it, you can do
```
@errorReturnTrace().?.index = 0;
```

Your reproduction can be 'fixed' with this:

```zig
const std = @import("std");

fn alwaysErrors() !void {
    return error.BUG_ThisErrorShouldNotAppearInAnyTrace;
}

test "test expected error" {
    try std.testing.expectError(error.BUG_ThisErrorShouldNotAppearInAnyTrace, alwaysErrors());
    @errorReturnTrace().?.index = 0;
}

test "trigger error trace" {
    return error.WeExpectToSeeThisInTheTrace;
}
```
(note that unwrapping with `.?` will fail on targets that don't support error return traces, or in functions that don't call any functions that return errors)

**Comment by Techcable** [comment] 2022-08-13 16:01
Yes. I have encountered this issue using `std.testing.expectError`

Some earlier tests (successfully) used `expectError`, causing later tests to unexpectedly include those previous errors in the error trace. This was extremely confusing to me.

@squeek502 's solution of using
```zig
If (@errorReturnTrace()) |trace| {
    trace.index = 0;
}
```
successfully fixed the problem for me.

At the very least we should do this between different tests. It's not a fix for all cases, but error-cases while testing are super important to get right.

**Comment by nektro** [comment] 2022-08-13 16:39
this should be fixed in the compiler, but nice find of a workaround

**Comment by topolarity** [comment] 2022-08-17 18:57
This seems to be complicated by patterns like this (taken from clap):
```zig
 // Initalize our diagnostics, which can be used for reporting useful errors.
 // This is optional. You can also pass `.{}` to `clap.parse` if you don't
 // care about the extra information `Diagnostics` provides.
 var diag = clap.Diagnostic{};
 var res = clap.parse(clap.Help, &params, clap.parsers.default, .{
     .diagnostic = &diag,
 }) catch |err| {
     // Report useful error and exit
     diag.report(io.getStdErr().writer(), err) catch {};
     return err;
 };
```

Should the error from `diag.report` be included in the error trace, even though it was caught?

**Comment by topolarity** [comment] 2022-08-17 21:13
One viable solution is to save the index value before any function call that generates an error return trace, and then "pop" the contributions of the error return trace from recent function calls in certain cases:
  1. A non-error return from a catch/error-else block
  2. Control flow leaves a catch/error-else block
  3. An error value is received from a function call and not immediately passed to `return`/`try`/`catch`/`else`

Here are some examples:
```zig
fn bar() !void {
  // (1) Returning a non-error from within catch/else |err|
  foo() catch {
     if (cond) return 1;  // non-error return, restore index from function entry
  };
  
  // (2) Successfully handling an error in catch/else |err|
  foo() catch { ... };    // left catch {} block, restore index from block entry
  return error.Foo; 
  
  // (3) "Holding onto" an error - this requires us to drop part of the trace
  const x = foo();        // unconditionally restore trace index from before foo() call
  const y = baz();        // unconditionally restore trace index from before baz() call
  if (cond) {
      return x;           // trace here starts fresh, if x is an error
  } else {
      return y;           // trace here starts fresh, if y is an error
  }
}
```
This is similar to what @FireFox317 proposed above, but handles nested `catch {}` blocks and doesn't allow errors stored in local variables to contribute to error traces, so that the trace follows a strict stack discipline.

**Closed** 2022-10-22 03:24 UTC
Labels: proposal, accepted
