### ISSUE TITLE
build-lib with target wasm32-emscripten doesnt support libc++

### ISSUE THREAD

**Issue by 3ddelano** [ziglang/zig#22246] opened 2024-12-15 16:39 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Unable to link with libc++ when using -Dtarget=wasm32-emscripten
Create a new file `main.cpp` with the following code:
```cpp
#include <iostream>
int main() {
  std::cout << "Hello World!\n";
  return 0;
}
```
Then run the command: `zig build-lib main.cpp -Dtarget=wasm32-emscripten -lc++`

It gives the following error:
```
...more error messages
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/functional:529:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/functional:529:
#include <__functional/function.h>
         ^
<command line>:9:22: note: expanded from macro 'target'
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__functional/function.h:904:30: error: member 'wasm32' declared as a template
  _LIBCPP_HIDE_FROM_ABI _Tp* target() _NOEXCEPT;
                             ^
main.cpp:1:10: note: in file included from main.cpp:1:
#include <iostream>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/iostream:44:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/iostream:44:
#include <istream>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/istream:170:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/istream:170:
#include <ostream>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/ostream:189:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/ostream:189:
#include <format>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/format:195:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/format:195:
#include <__format/container_adaptor.h>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__format/container_adaptor.h:24:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__format/container_adaptor.h:24:
#include <queue>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/queue:272:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/queue:272:
#include <deque>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/deque:2602:12: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/deque:2602:
#  include <functional>
           ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/functional:529:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/functional:529:
#include <__functional/function.h>
         ^
<command line>:9:16: note: expanded from macro 'target'
:1:1: error: too many errors emitted, stopping now
```

Running the same file in **emcc** (emscripten) works fine. (Command `emcc -c main.cpp`)

But running a similar example in C works fine.
```c
#include "stdio.h"
int main() {
  printf("hello world\n");
  return 0;
}
```

Command: `zig build-lib main.c -Dtarget=wasm32-emscripten`

### Expected Behavior

Expected that zig would compile the main.cpp to an .a library file.

**Comment by alexrp** [comment] 2024-12-15 16:59
`-Dtarget=...` is for `zig build`. For the other Zig commands, you want `-target ...`.

**Comment by 3ddelano** [comment] 2024-12-15 17:47
@alexrp Tried with this too `zig build-lib main.cpp -target wasm32-emscripten -lc++`
```warning(compilation): failed to delete '/project/.zig-cache/tmp/df17c63d1e45e3ce-main.o.d': FileNotFound
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/stdlib.h:145:30: error: unknown type name 'ldiv_t'
inline _LIBCPP_HIDE_FROM_ABI ldiv_t div(long __x, long __y) _NOEXCEPT { return ::ldiv(__x, __y); }
                             ^
main.cpp:1:10: note: in file included from main.cpp:1:
#include <iostream>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/iostream:43:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/iostream:43:
#include <ios>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/ios:223:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/ios:223:
#include <__locale>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__locale:15:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__locale:15:
#include <__memory/shared_ptr.h> // __shared_count
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__memory/shared_ptr.h:24:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__memory/shared_ptr.h:24:
#include <__memory/allocation_guard.h>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__memory/allocation_guard.h:15:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__memory/allocation_guard.h:15:
#include <__memory/allocator_traits.h>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__memory/allocator_traits.h:14:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__memory/allocator_traits.h:14:
#include <__memory/construct_at.h>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__memory/construct_at.h:23:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/__memory/construct_at.h:23:
#include <new>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/new:364:12: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/new:364:
#  include <cstdlib>
           ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/cstdlib:87:10: note: in file included from /opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/cstdlib:87:
#include <stdlib.h>
         ^
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/libcxx/include/stdlib.h:145:82: error: no member named 'ldiv' in the global namespace```

**Comment by alexrp** [comment] 2024-12-16 05:19
```
/home/alexrp/Source/ziglang/zig/lib/libcxx/include/__mbstate_t.h:40:12: fatal error: 'bits/alltypes.h' file not found
   40 | #  include <bits/alltypes.h>
      |            ^~~~~~~~~~~~~~~~~
5 errors generated.
```

This seems like the relevant error. It appears that we have no support for providing libc for Emscripten at the moment. This is effectively a duplicate of #20090.

**Closed by alexrp** 2024-12-16 05:19 UTC
Labels: bug

**Comment by 3ddelano** [comment] 2024-12-16 06:23
@alexrp I have emscripten installed. Is there a way I can provide the libc to zig when compiling for wasm32-emscripten. I found that perhaps --sysroot might be the flag which might work but I haven't been able to get it to work.

**Comment by alexrp** [comment] 2024-12-16 06:24
See `zig libc` and the `--libc` flag. Those might work.

**Comment by 3ddelano** [comment] 2024-12-16 06:26
ok thanks ill check this out.

**Comment by 3ddelano** [comment] 2024-12-16 06:41
Thanks @alexrp  I was able to get it to work by using `zig build-lib main.cpp -lc++ -target wasm32-emscripten -isystem PATH_TO_EMSCRIPTEN/upstream/emscripten/cache/sysroot/include`
