### ISSUE TITLE
Remove Windows `*A` declarations

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9054] opened 2021-06-09 16:20 UTC
Zig has (correctly) moved away from calling the legacy `*A` versions of functions and moved onto the `*W` versions (see https://github.com/ziglang/zig/issues/534).  In light of that, it seems appropriate to remove these `*A` declarations from `std`.

The only hesitation would be that if applications actually need these declarations that we make it easy to get them, so maybe we will want to wait for the package manager first?

**Comment by notviri** [comment] 2021-06-09 18:21
I was actually considering this while writing #9037 and I can personally vouch for this, however there was some disagreement about it already [previously](https://github.com/ziglang/zig/commit/1cdefeb10b7496126bbb7d00709235abfee56a4a#commitcomment-37214089) and it seems it's been thought about in #4426 and was ruled out.

**Comment by andrewrk** [comment] 2021-06-10 17:27
I'm in favor of completely removing the A declarations. This issue is a duplicate of #4426

**Closed by andrewrk** 2021-06-10 17:27 UTC
Labels: breaking, standard library
