### ISSUE TITLE
broken LLVM module casting sentinel slice to non-sentinel

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#6147] opened 2020-08-23 17:25 UTC
```zig
const std = @import("std");
const testing = std.testing;

test "zig bug" {
    const Foo = struct {
        fn foo() ?[:0]const u8 {
            return "bar";
        }
    };
    testing.expectEqual(@as(?[]const u8, "bar"), Foo.foo());
}
```

```
Code Generation [830/877] std.fmt.format...broken LLVM module found: Call parameter type does not match function signature!
  %1 = alloca %"?[:0]const u8", align 8
 %"?[]const u8"*  call fastcc void @std.testing.expectEqual(%"?[]const u8"* bitcast ({ %"[]u8", i1, [7 x i8] }* @69 to %"?[]const u8"*), %"?[:0]const u8"* %1), !dbg !2481

This is a bug in the Zig compiler.
/home/daurnimator/src/zig/src-self-hosted/stage2.zig:36:5: 0x563aef15c7fc in stage2_panic (zigstage2)
    @panic(ptr[0..len]);
    ^
/home/daurnimator/src/zig/src/util.cpp:20:17: 0x563aef10d04b in zig_panic (/home/daurnimator/src/zig/src/util.cpp)
    stage2_panic("", 0);
                ^
/home/daurnimator/src/zig/src/codegen.cpp:8313:18: 0x563aef010b58 in do_code_gen (/home/daurnimator/src/zig/src/codegen.cpp)
        zig_panic("broken LLVM module found: %s\nThis is a bug in the Zig compiler.", error);
                 ^
/home/daurnimator/src/zig/src/codegen.cpp:11067:24: 0x563aef01c0ce in codegen_build_and_link (/home/daurnimator/src/zig/src/codegen.cpp)
            do_code_gen(g);
                       ^
/home/daurnimator/src/zig/src/main.cpp:1786:39: 0x563aeefe99cf in main0 (/home/daurnimator/src/zig/src/main.cpp)
                codegen_build_and_link(g);
                                      ^
/home/daurnimator/src/zig/src/main.cpp:1864:24: 0x563aeefe9e62 in main (/home/daurnimator/src/zig/src/main.cpp)
    auto result = main0(argc, argv);
                       ^
Aborted (core dumped)
```

**Comment by Vexu** [comment] 2023-01-16 14:28
Duplicate of #4123

**Closed by Vexu** 2023-01-16 14:28 UTC
Labels: bug, stage1
