### ISSUE TITLE
Unexpected error when using if / else if in return expression.

### ISSUE THREAD

**Issue by dgottner** [ziglang/zig#5769] opened 2020-07-01 18:55 UTC
Trying to test this code:
<pre>
const assert = @import("std").debug.assert;

inline fn sgn(n: i64) i8 {
    return if (n < 0)
        -1
    else if (n == 0)
        0
    else
        1;
}

test "sign function" {
    assert(sgn(49) == 1);
    assert(sgn(-49) == -1);
    assert(sgn(0) == 0);
}
</pre>
results in a compilation error:
<pre>
$ zig test bug.zig
./bug.zig:6:10: error: values of type 'comptime_int' must be comptime known
    else if (n == 0)
</pre>

Note that rewriting the above to not use an expression-based if statement does not provoke an error:

<pre>
const assert = @import("std").debug.assert;

inline fn sgn(n: i64) i8 {
    if (n < 0)
        return -1
    else if (n == 0)
        return 0
    else
        return 1;
}

test "sign function" {
    assert(sgn(49) == 1);
    assert(sgn(-49) == -1);
    assert(sgn(0) == 0);
}
</pre>
<pre>
zig test nobug.zig
All 1 tests passed.
</pre>

**Comment by Vexu** [comment] 2020-07-01 19:11
Duplicate of #5557, #3750, #4255 and. #4629

**Closed by Vexu** 2020-07-01 19:11 UTC
