### ISSUE TITLE
Confusing error message with colliding struct fn and struct member names

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#2000] opened 2019-02-23 10:55 UTC
I was surprised to find that this snippet
```zig
const Foo = struct {
    bar: u32,

    pub fn bar(self: *Foo) u32 {
        return self.bar;
    }
};

test "bar" {
    var b = Foo{ .bar = 0 };
    _ = b.bar();
}
```
gives the following error
```bash
$ zig test typeIsNotAFunction.zig
typeIsNotAFunction.zig:11:10: error: type 'u32' not a function
    _ = b.bar();
         ^
```

I think Zig should first warn of an identifier clash, instead of choosing the struct member, and trying to use its type (??).

**Comment by tiehuis** [comment] 2019-02-23 11:10
Duplicate of #705.

**Closed by tiehuis** 2019-02-23 11:10 UTC
