### ISSUE TITLE
[build] ld.lld: error: undefined symbol: crypt

### ISSUE THREAD

**Issue by McSinyx** [ziglang/zig#8125] opened 2021-03-02 13:02 UTC
Hi all, I'm trying to build slock using Zig and so far almost everything went smoothly as intended.  Well, *almost*.  What I couldn't be able to figure out was that Zig can't seem to find `crypt` and thus can't link it:

```console
$ zig build
ld.lld: error: undefined symbol: crypt
```

In `build.zig` I did specified `exe.linkSystemLibrary("crypt")` and the generated command seems to be correct:

    zig build-exe -cflags -std=c99 -- $PWD/slock.c -cflags -std=c99 -- $PWD/explicit_bzero.c --library c --library crypt --library X11 --library Xext --library Xrandr --cache-dir $PWD/zig-cache --global-cache-dir $HOME/.cache/zig --name zlocc -I $PWD -I /usr/include -L /usr/lib -L /usr/lib/x86_64-linux-gnu --enable-cache

I've tried to reposition `--library crypt` but apparently it has no effect.  I'm on Debian Sid with prebuilt Zig 0.7.1, and [the problem persists on Arch with Zig (also 0.7.1) from its repo](https://builds.sr.ht/~cnx/job/445878).

**Comment by daurnimator** [comment] 2021-03-02 22:44
Duplicate of https://github.com/ziglang/zig/issues/5990 ?

FYI crypt was moved to libxcrypt, try  `-l xcrypt` (you may need to install it first?)

**Comment by andrewrk** [comment] 2021-03-02 22:47
Duplicate of #5990. I'll add an additional comment there.

**Closed by andrewrk** 2021-03-02 22:47 UTC
