### ISSUE TITLE
Using `mem.zeroes` on Array of Type, C_struct reports compiler bug stage1

### ISSUE THREAD

**Issue by PrimaIVoid** [ziglang/zig#10309] opened 2021-12-10 13:45 UTC
### Zig Version

0.9.0-dev.1926+803178353

### Steps to Reproduce

```
const std = @import("std");
const ray = @cImport({
    @cInclude("raylib.h");
});
const mem = std.mem;

pub fn main() !void {

    var fonts = mem.zeroes([1]ray.Font);
    // var fonts: [1]ray.Font = undefined;      <--- works
    _= fonts;
}
```
This is the definition of 'Font' in the C header
```
typedef struct Font {
    int baseSize;
    int glyphCount;
    int glyphPadding;
    Texture2D texture;
    Rectangle *recs;
    GlyphInfo *glyphs;
} Font;
```

### Expected Behavior

The code should compile without errors, as shown by changing line 9 with:
`var fonts: [1]ray.Font = undefined;`

### Actual Behavior

```
Unreachable at ../src/stage1/ir.cpp:23013 in buf_write_value_bytes. This is a bug in the Zig compiler.thread 15236 panic: 
Unable to dump stack trace: debug info stripped
```

**Comment by S0urc3C0de** [comment] 2021-12-10 23:21
Simpler example that triggers the faulty behaviour:
```zig
const std = @import("std");

const SomeStruct = extern struct {
    some_ptr: *c_int,
};

pub fn main() anyerror!void {
    var r = std.mem.zeroes([1]SomeStruct);
    _ = r;
}
```
It seems, the trigger is the pointer in the extern struct.

**Comment by Vexu** [comment] 2021-12-11 10:16
Duplicate of #7865.

**Closed by Vexu** 2021-12-11 10:16 UTC
Labels: bug, stage1
