### ISSUE TITLE
Zig CC With `-E` Targetting macOS Creates Empty Object Files

### ISSUE THREAD

**Issue by dan-smetana** [ziglang/zig#20464] opened 2024-07-01 14:09 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Create a C file `test.c`:

```c
#define NUM 42
int test() {
    return NUM;
}
```

run the preprocessor on it:
```bash
zig cc -target x86_64-macos -E ./test.c 
```

You will see an empty `test.o` file created in your current dir. If your current directory happens to be read-only, you will get an `Unexpected` error as the file fails to get created (I had to get a debug build of Zig to figure out what was going on).

### Expected Behavior

No files being created.

This patch seems to fix the issue for me:
```patch
diff --git a/src/main.zig b/src/main.zig
index 21f7281d74..e36607d0ef 100644
--- a/src/main.zig
+++ b/src/main.zig
@@ -2552,6 +2552,7 @@ fn buildOutputType(
                             clang_preprocessor_mode = .yes;
                         } else {
                             clang_preprocessor_mode = .stdout;
+                            emit_bin = .no;
                         }
                     }
                 },
```

**Comment by rohlem** [comment] 2024-07-01 15:21
duplicate of https://github.com/ziglang/zig/issues/20359; the patch looks useful (though I have no insight on whether it works)

**Closed** 2024-07-04 13:15 UTC
Labels: bug
