### ISSUE TITLE
`zig build run --watch` creates a lot of cache files in .zig-cache eating up drive space

### ISSUE THREAD

**Issue by rupakhetibinit** [ziglang/zig#20929] opened 2024-08-03 20:55 UTC
### Zig Version

0.14.0-dev.839+a931bfada, windows

### Steps to Reproduce and Observed Behavior

`zig build run --watch` continuously watches for file changes and rebuilds the executable but it never seems to delete the previously cached files. 
I just had over 300 MB build up in about 2 hours on a stupidly simple project(<500 LOC). This will be even worse for someone working in a larger project.

### Expected Behavior

I expect cache to be cleaned up.

**Comment by andrewrk** [comment] 2024-08-08 01:12
Duplicate of #15358

**Closed by andrewrk** 2024-08-08 01:12 UTC
Labels: bug
