### ISSUE TITLE
std.testing.expectEqual arguments are reversed

### ISSUE THREAD

**Issue by smokku** [ziglang/zig#12447] opened 2022-08-14 19:24 UTC
### Zig Version

0.10.0-dev.3475+b3d463c9e

### Steps to Reproduce

Following test
```zig
    const r: usize = 1;
    try std.testing.expectEqual(r, 5);
```
results in
```
Test [1/1] test "expectEqual"... expected 1, found 5
Test [1/1] test "expectEqual"... FAIL (TestExpectedEqual)
```

### Expected Behavior

The expected value was `5` and tested value was `1`, so the message should say:
```
Test [1/1] test "expectEqual"... expected 5, found 1
```

### Actual Behavior

Reversing the arguments in test:
```zig
try std.testing.expectEqual(r, 5);
```
does not help as it fails with:
```
error: expected type 'comptime_int', found 'usize'
```
as the first argument to expectEqual is the one defining types.

**Comment by Vexu** [comment] 2022-08-14 19:57
Duplicate of #4437

**Closed by Vexu** 2022-08-14 19:57 UTC
Labels: bug
