### ISSUE TITLE
Segmentation Fault when compiling std.mem.swap of anonymous tuple

### ISSUE THREAD

**Issue by bartbaer** [ziglang/zig#20746] opened 2024-07-22 21:49 UTC
### Zig Version

0.14.0-dev.208+854e86c56

### Steps to Reproduce and Observed Behavior

When I tried to swap two anonymous tuples, the build failed. (on linux x86_64)
```zig
const std = @import("std");
pub fn main() void {
    var a = [_]struct{i32, i32}{.{1, 2}, .{3, 4}};
    std.mem.swap(struct{i32, i32}, &a[0], &a[1]);
}
```
Trying to compile it, you get:
```
$ cat main.zig
const std = @import("std");
pub fn main() void {
    var a = [_]struct{i32, i32}{.{1, 2}, .{3, 4}};
    std.mem.swap(struct{i32, i32}, &a[0], &a[1]);
}
$ zig build-exe main.zig
Segmentation fault
```
However, if I give the tuple a name, it works.
This compiles fine:
```zig
const std = @import("std");
const Pair = struct{i32, i32};
pub fn main() void {
    var a = [_]Pair{.{1, 2}, .{3, 4}};
    std.mem.swap(Pair, &a[0], &a[1]);
}
```

I tried looking for issues with segfault and swap, but did not find anything.

### Expected Behavior

The compiler should not segfault, it should output a program or an error.

**Comment by Vexu** [comment] 2024-07-22 22:22
Duplicate of #19497

**Closed by Vexu** 2024-07-22 22:22 UTC
Labels: bug
