### ISSUE TITLE
Format error doesn't say which source code line was wrong

### ISSUE THREAD

**Issue by joelonsql** [ziglang/zig#16892] opened 2023-08-20 13:52 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

The problem is this line:
```zig
                 var temp_file_path = std.fmt.allocPrint(allocator, "{}.{}", .{ file_path, unique_id }) catch unreachable;
```

Here is the entire function:
```zig
const UUID = @import("libs/zig-uuid/uuid.zig").UUID;
const std = @import("std");
const Allocator = std.mem.Allocator;

pub fn get_or_create_uuid_from_file(allocator: Allocator, file_path: []const u8) !UUID {
    var unique_id = UUID.init();
    if (std.fs.cwd().statFile(file_path)) |x| {
        _ = x;
    } else |err| {
        switch (err) {
            error.FileNotFound => {
                var temp_file_path = std.fmt.allocPrint(allocator, "{}.{}", .{ file_path, unique_id }) catch unreachable;
                std.debug.print("File: {any}", .{temp_file_path});
            },
            else => {
                // Re-throw any other error
                return err;
            },
        }
    }
    return unique_id;
}
```

However, the `zig build`'s error message doesn't say anything at all about what line in my code that causes the error, it only points to lines in the std lib.

```shell
joel@Joels-MBP src % zig build
zig build-exe zig Debug native: error: the following command failed with 2 compilation errors:
/Users/joel/zig/zig build-exe /Users/joel/src/pg-uniphant/worker/zig/src/main.zig --cache-dir /Users/joel/src/pg-uniphant/worker/zig/zig-cache --global-cache-dir /Users/joel/.cache/zig --name zig --listen=-
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install zig transitive failure
   └─ zig build-exe zig Debug native 2 errors
/Users/joel/zig/lib/std/fmt.zig:648:21: error: cannot format slice without a specifier (i.e. {s} or {any})
                    @compileError("cannot format slice without a specifier (i.e. {s} or {any})");
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/joel/zig/lib/std/fmt.zig:648:21: error: cannot format slice without a specifier (i.e. {s} or {any})
                    @compileError("cannot format slice without a specifier (i.e. {s} or {any})");
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Output

The file:line in my code that causes the error

**Comment by nektro** [comment] 2023-08-20 14:00
this is fixed in master, duplicate of https://github.com/ziglang/zig/issues/14335

**Comment by jacobly0** [comment] 2023-08-25 18:04
Duplicate of #14335

**Closed by jacobly0** 2023-08-25 18:04 UTC
Labels: error message
