### ISSUE TITLE
Proposal: An analogue to gcc's __builtin_expect

### ISSUE THREAD

**Issue by mrakh** [ziglang/zig#6837] opened 2020-10-27 12:46 UTC
In GNU C, one can use the `__builtin_expect` construct in a conditional statement as a hint to the compiler, where the resulting assembly is arranged in a way that reduces the expected number of jumps and thus minimizes CPU pipeline stalls. It's often used in hot code where branching is unavoidable. I believe that exposing similar functionality to Zig would be useful, either as a built-in, or as a qualifier keyword used with conditional flow constructs (e.g. `if`, `while`).

**Comment by rohlem** [comment] 2020-10-27 13:25
duplicate of #489

**Closed** 2020-10-27 13:47 UTC
