### ISSUE TITLE
syntax flaw: return type

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#760] opened 2018-02-09 05:38 UTC
Fundamentally we have this ambiguity:

```zig
fn foo() A { }
```

Is this a function that returns A with an empty body? Or is this a function that returns the struct literal `A{}` and we're about to parse the body?

Another example

```zig
fn foo() error {}
```

Function that returns an error, or empty error set, and we're about to find the function body?

```zig
fn foo() error{}!void {
}
```

The above is not allowed because zig thinks the return value is `error` and the function has an empty body, and then is surprised by the `!`. So we have to do this:

```zig
fn foo() (error{}!void) {
}
```

Unfortunate. And the compile errors for forgetting to put a return type on a function point at the wrong place.

Let's come up with a better syntax for return types. All of these issues are potentially on the table:
 * could reintroduce `->` or `=>` if it helps.
 * could change the struct literal syntax / error set declaration syntax
 * multiple return values are potentially in zig's future. but also maybe not.
 * could potentially go back to allowing leaving off the return type for `void` return types.
 * error set inference - which currently looks like this:  `fn foo() !T {}`  - is special syntax that belongs to a function definition that marks the function as having an inferred error set. It doesn't necessarily have to be specified as it currently is by leaving off the error set of the `!` binary operator.

The syntax change should be satisfying, let's make this the last time everybody has to update all their return type code.

**Comment by bnoordhuis** [comment] 2018-02-10 10:19
I'm mentioning it for the sake of completeness, not as a serious suggestion, but the ambiguity can be resolved with arbitrary look-ahead / back-tracking.

For tooling reasons though you probably want zig's grammar to be LL(1) or LR(1).

**Comment by hasenj** [comment] 2018-02-10 13:41
As an aside, I do like having the `->` before the return type, just for consistency with similarly recent languages (Swift, Rust) that employ this syntax. It makes reading code a bit easier; I find.

That said, for this issue it seems the problem is figuring out where the type declaration ends and the bod begins. The main flaw is that `{` is a valid token inside the return type declaration.

Possible solutions I see:

1) Introduce a token to designate the end of return type and start of body. For example, `=`, as in:

    const abc = fn(x: X, y: Y) -> Z = {
        // function body
    }

I don't think this is a very good idea. It deviates too much from what everyone is used to in similar languages, and adds a needless clutter to a lot of code just to avoid an ambiguity that only arises some of the time.

3) Forbid `{` inside the return type, unless surrounded by parenthesis. For example:

    fn(...) -> (A{}) {
    }

This avoid the ambiguity without requiring the `(..)` to be always present in the return type, but potentially violates the "only one obvious way of doing things", and can cause "code style" wars, with one camp saying "you should always use parenthesis around your return types" and another one saying "never put parenthesis around return types, and never put `{` inside the return types; always use type aliases".

Which brings me to the next idea:

3) Forbid `{` inside the return type completely; require the use of type aliases.

If you need a function return a type that requires `{` in its definition, the only way to return such a type is to give an alias first. This can be good for readability.

I don't have other ideas at the moment.

**Comment by raulgrell** [comment] 2018-02-27 14:58
@hasenj Your first suggestion is pretty ok if we can declutter it a bit. With number 3, readability can be hindered by forcing everything to have a name/alias. Number 2 seems like a good compromise.

As an iteration on the first:

```
const S = struct {
    someFn: fn(x: X, y: Y) error{} ! Z,
    foo: u8
}

fn bar(x: X, y: Y) error{} ! Z => {
     // function body
}

// Single expression functions!
fn barWhenXEquals2(y: Y)  !Z => try bar(2, y);

const s = S {.someFn = bar, .foo = 0 };
```

**Comment by andrewrk** [comment] 2018-02-27 18:46
@raulgrell taking your `=>` suggestion to its natural conclusion:

```zig
if x + y > 10 => {

} else {

}

if foo() => |value| {

} else |err| {

}

while it : |node| it = node.next => {

}

while x < 10 : x += 1 => {

}
```

switch expressions already match this pattern.

I'm not so sure about this. I'd like to explore changing container initialization syntax and container declaration syntax to disambiguate.

**Comment by andrewrk** [comment] 2018-02-27 18:56
To clarify:

`()` on `if`, `while`, `switch`, `for`, etc is solving the same syntactic ambiguity. So for certain we will do one of these two things:
 * require `()` on return types, just like `if` and friends
 * solve the syntactic ambiguity a different way, and drop the `()` on `if` and friends

**Comment by raulgrell** [comment] 2018-02-27 19:59
I'd love to rid `if` and friends of their parentheses, so my vote is strongly for the `=>`.

The curly brackets for container initialization is common in C, C++, Rust, C#.  On the other hand, of those, only Rust allows the omission of the parentheses in if statements.

Alternative container initialization methods include:

```
const S = struct {a: u8, b: u8};

// Some of these would probably mean adding named parameters in function calls

// keyword
const s = new S(.a = 0, .b = 1};

// builtin type function
const s = S.new(.a = 0, .b = 1};

// Callable type with named parameters
const s = S(.a = 0, .b = 1);

// Square brackets on type
const s = S[.a = 0, .b = 1];

// We could probably do with compile time enforcement of Capitalized struct names if
// calling with parentheses or square brackets

// named initializers
const T = struct {
      a: u8,
      b: u8,

      new zeroes => { .a = 0, .b = 0 }
}

const t_zeroes = T::zeroes;

// builtin function
const t_ones = @new(T) { .a = 1, .b = 1};

```

**Comment by raulgrell** [comment] 2018-02-27 22:10
This is the cleanest iteration of the above ideas I have found:

```
const S = struct(a: u8, b: u8);
const s = new(S) {.a = 0, .b = 0};

fn G(comptime T: type) type { return struct( a: T ); }
const g = new (G(S)) { .a = s };

const E = enum(A, B);
const TE = enum[u8] (A = 3, B = 4);

const C = union[E] ( A: u8, B: void);
const c = new (C) { .A = 0 };

const U = union[enum] (Number: f64, String: []const u8, None)
const n = new (U) { .Number = 0.99};

```

**Comment by andrewrk** [comment] 2018-03-05 01:37
Here's my proposal:

 * Add the requirement of `.` before the `{` when instantiating types and values
 * Remove the requirement of `()` for `if`, `while`, `for`, `switch`, etc.

```zig
const Foo = struct.{
    a: i32,
    b: i32,
};

const Id = enum.{
    One,
    Two,
};

const Blah = union(enum).{
    Derp,
    Bar: struct.{
        aoeu: f64,
    },
};

const FileError = error.{
    OutOfMemory,
    AccessDenied,
};

test "aoeu" {
    var array = []u8.{'a', 'b', 'c', 'd'};

    var x = Foo.{
        .a = 1234,
        .b = 5678,
    };

    if x.a == 1234 {
        while true {
            eatStinkyCheese();
        }
    }
}
```

This fixes all the parsing ambiguity. Now `{` proceeded by a `.` is always type/value instantiation, and `{` not proceeded by a `.` is always the beginning of a block.

**Comment by bnoordhuis** [comment] 2018-03-05 05:52
It looks a little awkward but I guess that's no reason not to do it.  That said, I didn't see discussion on reintroducing `->`.  Are there drawbacks besides extra typing?

**Comment by andrewrk** [comment] 2018-03-05 06:01
> Are there drawbacks besides extra typing?

Not really. I removed `->` because with mandatory return types, it was rendered unnecessary.

`->` does not solve the return type syntax problem though. Whether or not we have `->`, there is still the `fn foo() -> error { } { }` ambiguity.

**Comment by bnoordhuis** [comment] 2018-03-05 06:03
Ah right.  And mandating parens around the return type makes for bad error messages if you forget them.  I see the issue now.

**Comment by raulgrell** [comment] 2018-03-05 17:46
I was wondering whether it would be beneficial to change the built in field/reflection syntax from using the regular field accessor `.` to a new operator like `::`, ie:

`Function.return_type` becomes `Function::return_type` and `slice.len` becomes `slice::len`. This signals to the reader that whatever you're accessign is something built-in.

Then keep your proposal and make container instantiation requiring a `::` followed by a `{`

```
const Blah = union(enum)::{
    Derp,
    Bar: struct::{
        aoeu: f64,
    },
};
```

**Comment by jido** [comment] 2018-03-08 11:13
Ok with the proposal, but:

```
var x = Foo.{
        .a = 1234,
        .b = 5678,
    };
```

Do we still need dot a, dot b here? We already have a dot after Foo.

**Comment by raulgrell** [comment] 2018-03-30 17:50
Only because this was mentioned in a separate issue, I just wanted to voice my support for your most recent proposal - disregard my `::` suggestions as I've come to appreciate the value of the universal `.` operator.

Regarding @jido's point about the dot (ha, pun), I think they are consistent with the rest of the language. 

```
// Here there is no dot because the identifier is being declared
const Foo = struct.{
    a: i32,
    b: i32,
};

// Here, we would have a dot because the name already exists
var x = Foo.{
    .a = 1234,
    .b = 5678;
};
```

If we look at consider the enum type inference in switches proposed in #683, they mention of issues with shadowing without the `.`. This would also be consisten with other parts of the language

```
const Value = enum(u32).{
    Hundred = 100,
    Thousand = 1000,
    Million = 1000000,
};

const v = Value.Hundred;
switch (v) {
    .Hundred => {},
    .Thousand => {},
    .Million => {}
}
```

**Closed** 2018-10-15 13:51 UTC
Labels: breaking

**Comment by andrewrk** [comment] 2018-10-15 19:28
Thanks for doing that work, @Hejsil .

To those who prefer the previous syntax, I empathize because I also prefer the previous syntax. However parsing ambiguities are simply not acceptable. And so we're stuck with the least worst solution. Proposals for different syntax/solutions are welcome, provided that they are better than status quo and do not introduce any syntax ambiguities.

**Comment by allochi** [comment] 2018-10-15 20:36
@andrewrk as I mention in my previous comment in #1628, using the dot here harm readability, as it's used usually as a member access operators, here it's overloaded with two extra meaning `define` and `new`.

If I'm getting this right, the problem is to solve the ambiguity of expressions like this
```c
fn foo() A {}
fn foo() error{}!void {}
```
All what we need is to surround the return type with symbols that are not used somewhere else, how about 
```c
fn foo() `A {}`
fn foo() `error{}!void` {}
```

> To clarify:
> 
> `()` on `if`, `while`, `switch`, `for`, etc is solving the same syntactic ambiguity. So for certain we will do one of these two things:
> 
> * require `()` on return types, just like `if` and friends
> * solve the syntactic ambiguity a different way, and drop the `()` on `if` and friends

I much prefer to require `()` on return types and keep it with `if`, `while`, `switch`, `for`, etc, like it is with `C` like languages than create a new meaning for `.`

**Comment by andrewrk** [comment] 2018-10-15 20:53
@allochi I'm going to amend your proposal and change it from surrounding the return type with backticks to surrounding it with parentheses.  I think that's actually a reasonable proposal. If we end up doing named return values to solve #287, then parentheses around return values is especially reasonable.

**Comment by UniqueID1** [comment] 2018-10-15 21:34
How about in case of ambiguity use a dot?

fn foo() A {} // function returns A
fn foo() A{} {} // compile error
fn foo() A.{} {} // function returns A{} struct literal

Now everything stays the same for the most part, assuming this works

**Comment by UniqueID1** [comment] 2018-10-15 22:04
Here's how I'm thinking it:

{} is always the body of what's to the left of it.

const A = struct {} // works fine
fn foo() {} // easily detects that return type is missing

The function decl parsing code is special cased to expect the {} to refer to its body, and it must be escaped if you want to refer to something else.

fn foo() A.{} {}

**Comment by jido** [comment] 2018-10-15 22:05
If you are not using the dot I would use inset operators e.g.

```
const FileError = error in {
    OutOfMemory,
    AccessDenied,
};

test "aoeu" {
    var array = []u8 of {'a', 'b', 'c', 'd'};

    var x = Foo with {
        .a = 1234,
        .b = 5678,
    };

    if x.a == 1234 {
        while true {
            eatStinkyCheese();
        }
    }
}
```

**Comment by UniqueID1** [comment] 2018-10-16 01:47
> I don't think this is compatible with the best way of solving the problem, which is that the parser is independent of the type system. Otherwise known as Context Free Grammar.

All that's changed (I think) is types in function signatures have a different grammar, .{} instead of {}. I don't know language theory and I haven't thought this through either, but the change sounds benign.

**Comment by allochi** [comment] 2018-10-16 06:31
> @allochi I'm going to amend your proposal and change it from surrounding the return type with backticks to surrounding it with parentheses. I think that's actually a reasonable proposal. If we end up doing named return values to solve #287, then parentheses around return values is especially reasonable.

@andrewrk which is better than what I have proposed, I suggested backticks cause I though the parentheses are out of question to make parsing easier.

I use parentheses with Go, and it doesn't bother me, although in Go it's only required if you have multiple return values (named or not), with parentheses we will have the following, which is quite reasonable
```c
fn foo() (A{})
fn foo() (error{}!void) {}

pub fn main() (!void) {
   var i: i32 = 42;
}
```

We can also make zig artistic by introducing
```c
fn foo() ._=|A{}|=_.
fn foo() ._=|error{}!void|=_. {}
```

Just joking, or maybe not, humm... 😄

**Comment by Hejsil** [comment] 2018-10-17 10:40
Here is another way we could go. What causes ambiguity is initializers and error sets. struct/union/enum type decls are not ambiguous, as it is required that they a followed by a lbrace.
```rust
fn a() struct {} {}
fn b() union {} {}
fn c() enum {} {}
```

Error sets are ambiguous because the `error` type is a thing.
```rust
// is this fn()error or fn()error{} ?
fn d() error {}
```

We could rename `error` to `anyerror` or something, and now, error sets are also not ambiguous.

Now, we just need to solve initializers. @andrewrk and I discussed removing our current initializers, in favor of [inferred initializers](https://github.com/ziglang/zig/issues/208#issuecomment-430371786) and implicit cast.
```rust
Point(.{.x = 1, .y = 2})
```

**Comment by allochi** [comment] 2018-10-17 11:12
@Hejsil nice!

But the language allows for this anonymous struct definition in a return type of a function

```c
fn something() ?struct{ x:i32 } {
    return null;
}
```

I don't know the point and use cases of this, I'm not aware of all Zig rules yet, but this compilers, and it shouldn't IMHO.

**Comment by allochi** [comment] 2018-10-17 11:17
> @andrewrk and I discussed removing our current initializers, in favor of inferred initializers and implicit cast.

```c
Point(.{.x = 1, .y = 2})
```

I hope you mean this
```c
Point{.x = 1, .y = 2}
```
back to the original form, `(.{})` is slightly clutter.

**Comment by Hejsil** [comment] 2018-10-17 12:09
@allochi Your first example is unambiguous. The first pair of braces always has to be part of the struct decl. There is no other way to parse this code.

We can't have `Point{.x = 1, .y = 2}`, with my proposal, because it is ambiguous.
```rust
// Is this a fn()Point or is it a fn()Point{} ?
fn a() Point {} {}
```

**Comment by allochi** [comment] 2018-10-17 12:57
I feel I'm missing couple of points here:

1. are we talking about initializing when we talk about `Point(.{.x = 1, .y = 2})`? like we can't have this back?
```c
const point = Point{.x = 1, .y = 2};
```
we will have this instead?
```c
const point = Point(.{.x = 1, .y = 2});
```

2. are return types only ambiguous when they have empty brackets? like this
```c
fn foo() A{} {
  ...
}
```
but not like this?
```c
fn foo() A{ x: i32 } {
  ...
}
```

What I mean:

a. is struct definition not a problem when it's not empty?
b. but it's a problem when it's empty, because we don't know if it's an empty struct `A{}` or an initialization `A{}`?

But then in the context of a function definition at return types, why would we have an initializer? and why would we have empty structs/union/enum as return types? what would be the use of them?

Why allow this in the compiler?
```c
fn something() ?struct{} {
    return null;
}
```

**Comment by Hejsil** [comment] 2018-10-17 13:16
1. Yes, that's what we're talking about. We can't have `Point{.x = 1, .y = 2}` currently because it is ambiguous during parsing.

2. Well, in theory, yes, return types are only ambiguous with empty brackets, but it is a little more complicated than this. We're trying to keep the grammar of the language simple, so we keep the lookahead requirements as small as possible (currently, we need 2 token lookahead to parse Zig).

a. No, struct/union/enum is never a problem. The reason for this is that they are required to have braces. You can have the struct/union/enum keywords without them being followed by braces, as that is the invalid syntax. Therefore, we always know where the braces belong:
```rust
// I'll add parens to show why this is not ambiguous
fn a() struct {} // error: expected function body
// fn a() (struct {})

fn a() struct {} {}
// fn a() (struct {}) {}
```

Now, let's look at initializers:
```rust
fn a() A {}
// fn a() (A) {}
// fn a() (A {})
// ^ Ambiguous because an initializer is optional 

fn a() A {} {}
// fn a() (A) {} {}
// fn a() (A {}) {}
// ^ Ambiguous because an initializer is optional
```

The reason this is allowed is because the gramma is something like this:
```
"fn" <Ident> "(" List("name" ":" <Expr>) ")" <Expr> <Body>
```

We need the gramma to be like this, because any expression could be `@typeOf(expr) == type`, and the function require that the expression of the return type is of type `type`. This allows Zig generics to work the way they do. A generic data structure in Zig is a struct returned from a function taking a type.
```rust
fn Point(comptime T: type) type {
    return struct { x: T, y: T };
}
```

As for the last example. Any programming language allows alot of weird programs to compile. A programming language cannot be turning complete, if you cannot write an ugly hack in it (I have no proof for this, but I'm pretty sure this is true).

**Comment by allochi** [comment] 2018-10-17 13:37
So can't we just come up with an initialization for empty struct only? 

I'm assuming in the parsing phase (I really need to dig more into Zig grammer and compiler) if we find a dot after the bracket `{.` we conclude it's an initialization, if not it's a definition (am I sort of right?), so:

empty vs non-empty struct definition would look like
```c
A{} // empty struct definition
B{ x: i32} // non-empty struct definition
```
while initialization looks like
```
A{.} // empty struct initialization
B{ .x = 42 } // non-empty struct initialization
``` 
This way I think we don't even need parentheses around return type, we already now know that `A{}` is a definition and `A{.}` is an initialization.

What do you think? and thanks for you patience 😄

**Comment by Hejsil** [comment] 2018-10-17 13:45
@allochi No problem. We have these issues so we can discuss and come up with solutions for Zigs problems :)

I still think there is a problem. Consider if we had inferred initializers as they are currently proposed:
```rust
fn a() A { .{}; }
```

We would need more than the `.` to solve this (or we could change the inferred initializer syntax)

**Comment by Manuzor** [comment] 2018-10-17 13:52
What about moving the return type definition into the parens of the function declaration?

```
// status quo
fn sum(a: i32, b: i32) i32 { return a + b; }

// return type moved into the parens
fn sum(a: i32, b: i32 -> i32) { return a + b; }

// longer signature
fn quiteTheLongFunctionName(
    the_first_argument: SomeElaborateType,
    another_argument: AnotherType,
-> TheResultType) {
    return /* ... */;
}

// Again with inline error sets
fn quiteTheLongFunctionName(
    the_first_argument: SomeElaborateType,
    another_argument: AnotherType,
-> error {
    FirstFailure,
    SecondFailure,
}!TheResultType) {
    return /* ... */;
}
```

**Comment by Hejsil** [comment] 2018-10-17 13:59
@Manuzor This indeed does solve the problem.
Idk if this deviates too much from calling a function, but it's definitely not bad :thinking:

**Comment by allochi** [comment] 2018-10-17 14:34
@Hejsil Thanks, if the dot is a problem in `{.}`, maybe another symbole (`{0}` or `{..}` or `{~}`) for empty initializer. This way we can remove the leading dot before braces for initializers.

@Manuzor PostgrSQL functions use similar style, I can't say it's nice to read
```sql
CREATE OR REPLACE FUNCTION fn_sqltestout(param_subject text, 
    OUT subject_scramble text, OUT subject_char text)
```
This could easily lead to have clutter between parentheses:
1. allocator
2. function parameters
3. generics types
4. return type
4b. or multiple return types (when we have it)

it could take some time to read and understand a function signature, and find out which is which.

**Comment by Manuzor** [comment] 2018-10-17 21:38
@allochi I'm not sure how far syntax can help you reduce clutter in function signatures. We didn't even look at qualifiers such as `extern "kernel32"` or the function calling convention here yet. They all add clutter.

Another alternative was mentioned before which enforces parens for the return type. It solves the ambiguity but it requires me to chase parens to figure out where the set of input parameters ends and the return types begin. I chose the arrow because it stands out.

In the case of multiple return values, my arrow-inside-parens version allows the syntax to extend naturally. You just continue specifying stuff separated by commas.

```
fn getMultipleResults(
    a: FirstType,
    b: SecondType,
-> error {
    FirstError,
    SecondError
}
! FirstResult,
  SecondResult,
) {
    // ...
}
```

Now that I'm looking at this, maybe we should consider swapping how return types and the error set are declared... I guess that's another proposal, though.

```
fn getMultipleResults(
    a: FirstType,
    b: SecondType,
->  FirstResult,
    SecondResult,
! error {
    FirstError,
    SecondError
}) {
    // ...
}
```

**Comment by Hejsil** [comment] 2018-10-18 09:33
And, we could make the syntax for `try` this:
```
"try" <TypeExpr>
```

Which allows this:
```rust
try somefunc() + 1
// parsed as (try somefunc()) + 1
```

Maybe `TypeExpr` is the wrong name. It is basicly an expression who can return all types, including `type`, where `Expr` also includes expression which are limited to returning only certain types.
`<Expr> + <Expr>` always returns `uN` or `iN`.
`<TypeExpr>{<FieldInit>}` never returns `type`, `errorset`, `uN`, `iN` ect

**Comment by jido** [comment] 2018-10-18 09:55
> We split the expression syntax into two parts: `TypeExpr` and `Expr`. A `TypeExpr` is an expression that can return the type `type`.
> 
> An `Expr` is all other expressions + `TypeExpr`.
> 
> ```
> <Expr> + <Expr>
> ...
> <TypeExpr> "{" <Exprs> "}"
> <TypeExpr> "{" <FieldInits> "}"
> <TypeExpr>
> ...
> ```
> 
> We then change the function syntax to this:
> 
> ```
> "fn" <Symbol> "(" <Params> ")" <TypeExpr> "{" <Statements> "}"
> ```
> 
> And now, this is a compiler error:
> 
> ```rust
> fn a() A{} {} // error: expected top level decl, found "{"
> // (fn a() (A) {}) {} // parens, to show how it was parsed
> 
> // Now, if a literal should be parsed for function return type, parens are required:
> fn a() (A{}) {}
> 
> // Note, that <Expr> "." <Symbol> is a <TypeExpr>. This is therefor possible:
> fn a() A{.T = u8}.T {}
> ```

That looks quite sane.

**Comment by andrewrk** [comment] 2018-10-18 15:32
I approve of https://github.com/ziglang/zig/issues/760#issuecomment-430938743. `anyerror` is a great name for the primitive type that represents the global error set.

**Comment by UniqueID1** [comment] 2018-10-18 20:21
So it's "fn foo() anyerror {}"?

For shorter typing you could have "fn foo() error {}" and "const FileOpenError = errorset {};"

**Comment by Hejsil** [comment] 2018-10-18 20:27
@UniqueID1 It is encouraged/good style to use error sets more than `error`, so I think it makes sense to change `error`.

**Comment by Manuzor** [comment] 2018-10-18 20:40
If the standalone `error` is the only case that causes ambiguity then I also think special casing it is a much better solution than anything else mentioned here before. The identifier `anyerror` states the intent very clearly.

**Comment by UniqueID1** [comment] 2018-10-18 21:06
@Hejsil Wanting to have (subjectively) uglier syntax for encouragement reasons is a valid viewpoint, if I'm not simplifying your viewpoint too much. I think it's in a way risky. I think it'll encourage people to switch over from the global error set at the wrong time for the wrong reason.

**Comment by UniqueID1** [comment] 2018-10-19 11:15
Ahh okay, also anyerror is very descriptive so that's a plus for it. It's actually not bad at all and it tells the newbies exactly what it does.

**Comment by Hejsil** [comment] 2018-10-19 12:29
Alright, seems like we might have found a [better solution](https://github.com/ziglang/zig/issues/760#issuecomment-430938743) than what was merged in #1628. Any objections should be voiced as soon as possible, as I wanna revert #1628, as soon as possible and start implementing the proposed solution.

One downside to this is that that we have to reject #1659.

**Comment by thejoshwolfe** [comment] 2018-10-19 13:00
> ```
> // Note, that <Expr> "." <Symbol> is a <TypeExpr>. > This is therefor possible:
> fn a() A{.T = u8}.T {}
> ```

This doesn't seem right. Everything else about the proposed TypeExpr seems good, but I think this example should fail to parse.

The formal grammar specification for Zig isn't always up to date, but it might be able to shed light on this if it's updated with this proposal.

This is also not very important and shouldn't block any forward progress. This is just something to iron out before 1.0.0.

**Comment by Hejsil** [comment] 2018-10-19 13:36
I don't think we can have that example fail as simple cases like `fn a() A.B {}` and `fn a() A().B {}` should work.

My plan was to work on #208, but it seems we still haven't reached a conclusion on this (and this issue seemed to be related, so I switched my focus to this).

I'll probably work towards having the grammar up to date, as that will help with the stage2 parser rewrite when that is gonna happen. Then add some kind of test that ensures that it stays up to date (have the grammar as a bison parser, and run this parser on all Zig src code in this repo on every commit). This will also help when prototyping new syntax.

**Comment by Hejsil** [comment] 2018-10-19 14:52
@binary132 [docs](https://ziglang.org/documentation/master/#Errors) and [error set issue](https://github.com/ziglang/zig/issues/632) :)

**Comment by allochi** [comment] 2018-10-19 15:20
@Hejsil thanks a lot for being so communicative and agile toward this issue.

I'm glad that we are getting to agree on a solution for this, I don't mind parentheses in if, for, ..., I admit I got used not to use them in Go for example, but I don't mind them in other languages, and since these are expressions in zig it kind of works well, take for example this from the standard library
```c
const n = if (self.pos + bytes.len <= self.slice.len)
    bytes.len
  else
    self.slice.len - self.pos;

// -- vs --

const n = if self.pos + bytes.len <= self.slice.len
    bytes.len
  else
    self.slice.len - self.pos;

```
I don't know about the others, but with parentheses it seems to be easier to read.

Now regarding the global error set, why name it `anyerror`? why not `errorset` or `errors` wouldn't that be more descriptive of what it is?

**Comment by Hejsil** [comment] 2018-10-19 16:07
@allochi There are a few reasons for `anyerror`:
* `error{A,B}` is an error set, so I don't think we should rename the `error` to `errorset` as that is just confusing.
* There is a low chance of `anyerror` to collid with identifiers, as the standard style is snake_case (any_error).
* `anyerror` communicates quite well if you don't know the language:
```
// `a` could return any error or u8. 
fn a() anyerror!u8 { ... }

// `a` could return errors or u8. (I could read `fn a() !u8` the same way)
fn a() errors!u8 { ... }

// `a` could return all errors or u8. (It could return all errors at the same time?)
fn a() allerrors!u8 { ... }
```

**Comment by allochi** [comment] 2018-10-19 16:46
@Hejsil Thanks, no strong feeling against`anyerror`, it seems to be fine.

**Comment by UniqueID1** [comment] 2018-10-19 20:27
`error{A,B} is an error set, so I don't think we should rename the error to errorset as that is just confusing.`
I mean I don't know about that.

const A = struct {}; // a struct
const A = errorset {}; // an error set

**Comment by Hejsil** [comment] 2018-10-19 20:55
@UniqueID1 Sorry, that was a confusing statement. I'm talking about this rename:
```
fn a() error{}!u8 {} -> fn a() error{}!u8 {}  
fn a() error!u8 {}   -> fn a() anyerror!u8 {}
```

We could even rename both keywords:
```
fn a() error{}!u8 {} -> fn a() errorset{}!u8 {}  
fn a() error!u8 {}   -> fn a() anyerror!u8 {}
```

But that's not the goal of this issue.

**Comment by Hejsil** [comment] 2018-10-19 21:56
Or maybe best:
```rust
// Leave `error` as is. This allows error.A to work without parser hacks
fn a() error { return error.A; }

// Rename `error` for error sets
const E = errorset {A, B};

**Comment by allochi** [comment] 2018-10-19 23:18
@Hejsil Yeah, this is what I was thinking of too, it make sense this way.

**Comment by UniqueID1** [comment] 2018-10-20 00:41
That was my proposal.

`For shorter typing you could have "fn foo() error {}" and "const FileOpenError = errorset {};"`

**Comment by Manuzor** [comment] 2018-10-20 07:12
Let me get this straight. The __new__ keyword `errorset` would be used to declare a new error set, just like `struct` and friends. The __existing__ keyword `error` would be used to return a specific error, like `return error.OutOfMemory`.

If that is correct, then I think there is no need for `anyerror` anymore.
```
// no errors from this function.
fn foo() void {
    // ...
}

// inferred errorset from this function.
fn bar() !void {
    // ...
}

// explicit errorset that is declared inline.
fn baz() errorset{ OutOfMemory, FileNotFOund }!void {
    // ...
}

// new explicit errorset
const TheErrors = errorset{ OutOfMemory, FileNotFound };
fn qux() TheErrors!void {
    // ...
}

// status quo to return "any error" still works.
fn corge() error!void {
    // ...
}

// Not sure about this one, but it's certainly not ambiguous.
fn waldo() error.OutOfMemory!void {
    // ...
}
```

**Comment by UniqueID1** [comment] 2018-10-20 11:34
I believe that there are 3 options
```
// keywords are error and errorset
fn foo() error {}
const E = errorset {};
```

```
// keywords are anyerror and error
fn foo() anyerror {}
const E = error {};

```
```
// just the error keyword
fn foo() error {}
fn foo() (error {A,B}) { ... }
const E = error {};
```
I prefer error + errorset over anyerror + error. However, with functions accepting TypeExpr instead of Expr, I believe we could also just have the error keyword and use parenthesis in some cases as shown above.

**Comment by Hejsil** [comment] 2018-11-13 13:16
The `.` syntax has been reverted as of #1685, which implements [option 2 in this comment](https://github.com/ziglang/zig/issues/760#issuecomment-431572495)
