### ISSUE TITLE
`x: Type` parameter is mistaken as anytype parameter

### ISSUE THREAD

**Issue by wooster0** [ziglang/zig#16663] opened 2023-08-03 09:49 UTC
### Zig Version

0.11.0-dev.4404+4f6013bf5

### Steps to Reproduce and Observed Behavior

Probably a duplicate but
```zig
test {
    writeIntLittle(u64, @bitCast(packed struct { hi: u32, lo: u32 }{ .hi = 0, .lo = 0 }));
}

fn writeIntLittle(comptime Type: type, x: Type) void {
    _ = x;
}
```
```
$ zig test x.zig
x.zig:2:25: error: @bitCast must have a known result type
    writeIntLittle(u64, @bitCast(packed struct { hi: u32, lo: u32 }{ .hi = 0, .lo = 0 }));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x.zig:2:25: note: result type is unknown due to anytype parameter
x.zig:2:25: note: use @as to provide explicit result type
```

### Expected Behavior

Test passes.

**Comment by mlugg** [comment] 2023-08-03 09:56
Duplicate of #16258, resolved by #16604

**Closed** 2023-08-03 09:57 UTC
Labels: bug
