### ISSUE TITLE
wlroots - pointers cannot point to opaque types

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#5447] opened 2020-05-26 21:47 UTC
`@cImport`ing wlroots results in:
```
error: C pointers cannot point to opaque types
    formats: [*c][*c]struct_wlr_drm_format,
```

Source of problem [header](https://github.com/swaywm/wlroots/blob/master/include/wlr/render/drm_format_set.h)

### Snippet of original header
``` c
struct wlr_drm_format {
    uint32_t format;
    size_t len, cap;
    uint64_t modifiers[];
};

struct wlr_drm_format_set {
    size_t len, cap;
    struct wlr_drm_format **formats;
};
```

### Snippet of translate-c output
``` zig
pub const struct_wlr_drm_format = @Type(.Opaque); // drm_format_set.h:11:11: warning: struct demoted to opaque type - has variable length array
pub const struct_wlr_drm_format_set = extern struct {
    len: usize,
    cap: usize,
    formats: [*c][*c]struct_wlr_drm_format,
};
```

Is there any way of getting this working?

**Comment by Vexu** [comment] 2020-05-26 22:03
Duplicate of #4686, related #4775.

Easiest workaround would be to manually translate that header.

**Closed by Vexu** 2020-05-26 22:03 UTC
