### ISSUE TITLE
translate-c subcommand fails with 'out of memory'

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#4028] opened 2020-01-02 06:16 UTC
I accidentally ran `translate-c` on an empty .zig file:
```
$ touch foo.zig
$ zig translate-c foo.zig
unable to parse C file: out of memory
```

**Comment by LemonBoy** [comment] 2020-01-02 11:16
#4003 made the error path not crash and burn, for some reason the clang frontend exits early without recording any diagnostic error.

**Comment by Vexu** [comment] 2020-01-16 10:55
Running `translate-c` on a non-existing file with c file ending (c, h, hpp, cpp) prints garbage.
```bash
$ zig translate-c a.h
error: pa_4�U
```

**Comment by Sobeston** [comment] 2020-01-21 23:22
I encountered the same error `unable to parse C file: out of memory`, but by using translate-c on a folder by mistake

**Comment by andrewrk** [comment] 2020-02-16 21:52
#4455 is a duplicate of this, but I'm going to close this one instead since the diagnosis and related links are in the other issue

**Closed by andrewrk** 2020-02-16 21:52 UTC
Labels: bug, translate-c
