### ISSUE TITLE
broken packed struct initialization

### ISSUE THREAD

**Issue by Traxar** [ziglang/zig#21235] opened 2024-08-28 21:56 UTC
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```ts
const std = @import("std");
const expect = std.testing.expect;

const SliceAtHome = packed struct {
    const Slice = @This();
    ptr: [*]bool = undefined,
    len: usize = 0,

    pub inline fn init(n: usize) !Slice {
        var slice = Slice{ .len = n };
        slice = slice;
        return slice;
    }
};

test "MultiSlice" {
    const ms = try SliceAtHome.init(10);
    try expect(ms.len == 0); // passes
    try expect(ms.len == 10); // fails
}
```

### Expected Behavior

test passes

**Comment by ianprime0509** [comment] 2024-08-28 22:42
Here's a related example:

```zig
const std = @import("std");

const S = packed struct {
    a: usize = undefined,
    b: usize,
};

pub fn main() void {
    const s_const: S = .{ .b = 123 };
    std.debug.print("{}\n", .{s_const.b});

    var s_var: S = .{ .b = 123 };
    _ = &s_var;
    std.debug.print("{}\n", .{s_var.b});
}
```

As of 0.14.0-dev.1349+6a21875dd, this prints

```
123
17007316
```

(at least for me; the second value will not necessarily be consistent since it appears to be uninitialized memory: https://godbolt.org/z/PM85achM7)

This example works as expected (prints 123 twice) if any of the following changes are made:

1. Make `S` a regular (non-packed) struct
2. Reorder the field `b` before `a`
3. Choose any other default value for `a` besides `undefined`

**Comment by sno2** [comment] 2024-08-28 22:52
Seems like a duplicate of https://github.com/ziglang/zig/issues/20938

**Comment by Traxar** [comment] 2024-08-29 06:09
4. The example also works with the following replacement:
```ts
    // var s_var: S = .{ .b = 123 };
    var s_var: S = undefined;
    s_var.b = 123;
```

**Comment by Vexu** [comment] 2024-09-01 15:55
Duplicate of #20938

**Closed by Vexu** 2024-09-01 15:55 UTC
Labels: bug
