### ISSUE TITLE
zig build -Dtarget=i386-linux-gnu fail.

### ISSUE THREAD

**Issue by zhaozg** [ziglang/zig#7440] opened 2020-12-14 03:45 UTC
run `zig build -Dtarget=i386-linux-gnu` fail, but `zig build -Dtarget=x86_64-linux-gnu` ok.
Output error message
```
ld.lld: error: undefined hidden symbol: __x86.get_pc_thunk.bx
>>> referenced by crti.S:68 (/usr/local/lib/zig/libc/glibc/sysdeps/i386/crti.S:68)
>>>               /Users/zhaozg/.cache/zig/o/29d3416c5bad5a04b4546e71b6b03bc2/crti.o:(.init+0x5)
>>> referenced by crti.S:88 (/usr/local/lib/zig/libc/glibc/sysdeps/i386/crti.S:88)
>>>               /Users/zhaozg/.cache/zig/o/29d3416c5bad5a04b4546e71b6b03bc2/crti.o:(.fini+0x5)
error: LLDReportedFailure
test...The following command exited with error code 1:
```

**Comment by LemonBoy** [comment] 2020-12-14 09:37
Duplicate of #4926

**Closed** 2020-12-14 13:14 UTC
