### ISSUE TITLE
Bug with non-trivial usage of unnamed struct, optional types and switch over tagged union

### ISSUE THREAD

**Issue by sivukhin** [ziglang/zig#10514] opened 2022-01-05 09:27 UTC
### Zig Version

0.9.0-dev.1815+20e19e75f

### Steps to Reproduce

Try to compile following code (godbolt link: https://godbolt.org/z/8MqKo6P9W):
```zig
const std = @import("std");
const Two = struct { a: ?i32, b: i32 };
const Complex = union(enum) { two: Two };

fn get() Complex {
    return Complex{ .two = Two{ .a = null, .b = 1 } };
}

pub fn main() void {
    const x = get();
    switch (x) {
        Complex.two => |two| std.debug.print("{}\n", .{two.a orelse two.b}),
    }
}
```

### Expected Behavior

Code is perfectly valid and should output string `1`

### Actual Behavior

Zig compiler crashes with the following error:
```
broken LLVM module found: Instruction does not dominate all uses!
  %9 = getelementptr inbounds %"struct:12:55", %"struct:12:55"* %0, i32 0, i32 0, !dbg !16575
  store i32 %11, i32* %9, align 4, !dbg !16574

This is a bug in the Zig compiler.thread 11096 panic: 
Unable to dump stack trace: debug info stripped
```

**Comment by locriacyber** [comment] 2022-01-07 19:06
Zig version 0.10.0-dev.40+303bad998, can reproduce.

When I changed the type of `b` to `?i32`, it broke more.
```
const std = @import("std");
const Two = struct { a: ?i32, b: ?i32 };
const Complex = union(enum) { two: Two };

fn get() Complex {
    return Complex{ .two = Two{ .a = null, .b = 1 } };
}

pub fn main() void {
    const x = get();
    switch (x) {
        .two => |two| std.debug.print("{}\n", .{two.a orelse two.b}),
    }
}
```

```
broken LLVM module found: Instruction does not dominate all uses!
  %9 = getelementptr inbounds %"struct:12:48", %"struct:12:48"* %0, i32 0, i32 0, !dbg !17078
  %14 = getelementptr inbounds %"?i32", %"?i32"* %9, i32 0, i32 1, !dbg !17077
Instruction does not dominate all uses!
  %9 = getelementptr inbounds %"struct:12:48", %"struct:12:48"* %0, i32 0, i32 0, !dbg !17078
  %15 = getelementptr inbounds %"?i32", %"?i32"* %9, i32 0, i32 0, !dbg !17077

This is a bug in the Zig compiler.thread 5194 panic: 
Unable to dump stack trace: debug info stripped
```

**Comment by cryptocode** [comment] 2022-01-07 22:40
Quick note that this can be further reduced to:

```zig
const std = @import("std");

const Wrapper = struct { val: ?u8};
pub fn get() Wrapper {
    return .{ .val = null };
}

pub fn main() u8 {
    const x = get();
    var b = @as(u8,1);
    return .{x.val orelse b}[0];
}
```

Introducing a temporary for the array item "solves" the issue, which may give some indication as to where the culprit is.

```zig
var tmp = x.val orelse b;
return .{tmp}[0];
```

**Comment by Vexu** [comment] 2023-01-16 14:22
Duplicate of #3882

**Closed by Vexu** 2023-01-16 14:22 UTC
Labels: bug, stage1
