### ISSUE TITLE
@frameSize(func) returns a different value than @sizeOf(@Frame(func))

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#5638] opened 2020-06-19 22:22 UTC
```zig
const std = @import("std");

pub fn main() void {
    std.debug.print("{} != {}\n", .{@frameSize(foo), @sizeOf(@Frame(foo))});
}

fn foo() void {
    std.debug.print("Hi!", .{});
}
```

This will print
```
8658703 != 32
```

Tested on win64, MacOS and WSL

**Comment by Vexu** [comment] 2020-06-20 06:17
Duplicate of #3654

**Closed by Vexu** 2020-06-20 06:17 UTC
