### ISSUE TITLE
compilation bug when inspecting @typeInfo@TypeOf(struct{next: ?*@This()}) : "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by speed2exe** [ziglang/zig#14426] opened 2023-01-23 07:11 UTC
### Zig Version

0.11.0-dev.1364+72c09b7b3

### Steps to Reproduce and Observed Behavior

file:

```zig
const std = @import("std");

fn inspect(arg: anytype, comptime _: []const u8) !void {
    switch (@typeInfo(@TypeOf(arg))) {
        .Struct => |s| {
            inline for (s.fields) |field| {
                try inspect(@field(arg, field.name), "");
            }
        },
        .Pointer => try inspect(arg.*, ""),
        .Optional => |_| {
            if (arg) |value| {
                try inspect(value , "");
            } else {
                std.debug.print("value is null",.{});
            }
        },
        else => {},
    }
}

const LinkedNode = struct {
    next: ?*@This() = null,
};

pub fn main() void {
    const linked_node: ?LinkedNode = .{};
    inspect(linked_node, "") catch unreachable;
}



```

command:
```bash
zig build-exe main.zig
```

output:
```
Segmentation fault (core dumped)
```

### Expected Behavior

compile successfully with output when ran:
```
value is null
```

**Comment by Vexu** [comment] 2023-01-23 12:20
Duplicate of #13803

**Closed by Vexu** 2023-01-23 12:20 UTC
Labels: bug
