### ISSUE TITLE
compile error on wrong line when using array initialization syntax to initialize a user-defined struct.

### ISSUE THREAD

**Issue by srijan-paul** [ziglang/zig#17612] opened 2023-10-19 08:03 UTC
### Zig Version

0.12.0-dev.800+a9b37ac63

### Steps to Reproduce and Observed Behavior

In the following code:
```zig
const std = @import("std");
const T = std.testing;

pub const Struct = struct {
    A: bool = true,
    B: bool = false,
};

test "test1" {
    var a = Struct{};
    T.expectEqual(a, .{ true, false });
}
```

I'm initializing `Struct` using an array initializer syntax on the second line of the test block.
This should raise a compile error on line 11 of the file.

However, when I run `zig test struct.zig`, I get:

```
src/foo.zig:1:1: error: type 'foo.Struct' does not support array initialization syntax
const std = @import("std");
^~~~~
```

Image: 
<img width="680" alt="Screenshot 2023-10-19 at 1 32 39 PM" src="https://github.com/ziglang/zig/assets/50487716/a9b5c44d-4e7f-46e4-9579-2c736ef47809">

### Expected Behavior

I expect the compile error to be on line 11, since that is the line where I'm using the array init syntax.

**Comment by Vexu** [comment] 2023-10-19 11:24
Duplicate of #17127

**Closed by Vexu** 2023-10-19 11:24 UTC
Labels: bug
