### ISSUE TITLE
`export const ...` inside `struct { ... }` is analyzed ignoring conditional execution

### ISSUE THREAD

**Issue by yvt** [ziglang/zig#5453] opened 2020-05-27 09:01 UTC
```zig
fn Ty(comptime value: var) type {
    if (@TypeOf(value) == u32) {
        return struct {
            export const exported_variable: u32 = value;
        };
    } else {
        return void;
    }
}

export const a: Ty({}) = undefined;
```

Expected: No compile error

Actual:
```
./test.zig:4:51: error: expected type 'u32', found 'void'
            export const exported_variable: u32 = value;
                                                  ^
```

# Other examples

A more compressed example:

```zig
export const a = if (true) "" else struct {
    export const x = unreachable; // error: unable to evaluate constant expression
};
```

A crashing example:

```zig
export const a = if (true) "" else b: {
    const x_value: u32 = 42;
    break :b struct {
        export const x = x_value;
    };
};
```

```
Assertion failed at /Users/runner/runners/2.166.4/work/1/s/src/codegen.cpp:1797 in codegen_report_errors_and_exit. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
```

# Version

```
% zig version
0.6.0+d44c9bdbd
```

**Comment by Vexu** [comment] 2022-12-30 21:10
Duplicate of #3778

**Closed by Vexu** 2022-12-30 21:10 UTC
Labels: bug, stage1
