### ISSUE TITLE
`fflush` hangs when running C tests in `test.zig`

### ISSUE THREAD

**Issue by IvanVnucec** [ziglang/zig#17725] opened 2023-10-26 08:44 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

I have a C library that uses the [minunit](https://github.com/siu/minunit) testing framework.
I want to use Zig build to build the C library and run minunit tests.
I've managed to implement `build.zig` script that builds C library and Zig test. Zig test links with C library and calls minunit test runner.
Zig test is defined as:
```zig
const std = @import("std");
const testing = std.testing;
const test_runner = @cImport({
    @cInclude("test_runner.h");
});

test "test runner" {
    try testing.expectEqual(@as(i32, 0), test_runner.test_runner());
}
```
and `test_runner` test runner is defined in `test_runner.h` as `int test_runner(void)` and returns how many tests have failed with by returning `MU_EXIT_CODE` minunit macro.
Example of a library test:
```c
#include "minunit.h"

MU_TEST(test_example) {
    mu_check(0 == 0);
}

MU_TEST_SUITE(test_suite) {
	MU_RUN_TEST(test_example);
}

int test_runner(void) {
	MU_RUN_SUITE(test_suite);
	MU_REPORT();
	return MU_EXIT_CODE;
}

```
When I call `zig build test --verbose`, the output hangs at:
```sh
/home/ivan/zig-linux-x86_64-0.11.0/zig build-lib -cflags -Wall -pedantic -- /home/ivan/Desktop/fms/src/fms_example.c --cache-dir /home/ivan/Desktop/fms/zig-cache --global-cache-dir /home/ivan/.cache/zig --name fms -static -I /home/ivan/Desktop/fms/include --listen=- 
/home/ivan/zig-linux-x86_64-0.11.0/zig test /home/ivan/Desktop/fms/test/test.zig -cflags -Wall -pedantic -- /home/ivan/Desktop/fms/test/test_fms_example.c /home/ivan/Desktop/fms/zig-cache/o/ceafcc0bb6d2897080e8e4c810ee2cc7/libfms.a -lc --cache-dir /home/ivan/Desktop/fms/zig-cache --global-cache-dir /home/ivan/.cache/zig --name test -I /home/ivan/Desktop/fms/test -I /home/ivan/Desktop/fms/include --listen=- 
steps [2/4] zig test Debug native... LLVM Emit Object... /home/ivan/Desktop/fms/zig-cache/o/5478d392a073a878b61002eee49e285e/test --listen=- 
```
With trial and error, I've concluded that the problem is somewhere in `MU_RUN_TEST` minunit test runner.
`MU_RUN_TEST` is declared as:
```c
#define MU_RUN_TEST(test) MU__SAFE_BLOCK(\
	if (minunit_real_timer==0 && minunit_proc_timer==0) {\
		minunit_real_timer = mu_timer_real();\
		minunit_proc_timer = mu_timer_cpu();\
	}\
	if (minunit_setup) (*minunit_setup)();\
	minunit_status = 0;\
	test();\
	minunit_run++;\
	if (minunit_status) {\
		minunit_fail++;\
		printf("F");\
		printf("\n%s\n", minunit_last_message);\
	}\
	(void)fflush(stdout);\
	if (minunit_teardown) (*minunit_teardown)();\
)
```
I've tried to modify `MU_RUN_TEST` with early return values to find out where the problem is and I've concluded that Zig test hangs at `(void)fflush(stdout);\` line. When I comment out mentioned line, `zig build test` returns as expected.

### Expected Behavior

`zig build test` will not hang in `MU_RUN_TEST` at `(void)fflush(stdout);\` line.

P.S.: I'm using Ubuntu 22.04.

**Comment by rootbeer** [comment] 2023-10-26 15:54
Can you confirm that if you compile the mintest example code without Zig (at least the equivalent of it -- a C program that invokes `test_runner()`), then it does not hang?

How is the 'test' step defined in your build.zig?  You might try running the test binary directly (I think its the `/home/ivan/Desktop/fms/zig-cache/o/5478d392a073a878b61002eee49e285e/test` file) and see if that reproduces the problem.  Or run `zig test foo.zig -lc` to run the test without using the builder might also help narrow things down.

**Comment by IvanVnucec** [comment] 2023-10-27 05:34
@rootbeer 
> Can you confirm that if you compile the mintest example code without Zig (at least the equivalent of it -- a C program that invokes `test_runner()`), then it does not hang?

Yes, compiled C code does not hang.

> How is the 'test' step defined in your build.zig? You might try running the test binary directly (I think its the `/home/ivan/Desktop/fms/zig-cache/o/5478d392a073a878b61002eee49e285e/test` file) and see if that reproduces the problem. Or run `zig test foo.zig -lc` to run the test without using the builder might also help narrow things down.

When I run `/home/ivan/Desktop/fms/zig-cache/o/5478d392a073a878b61002eee49e285e/test`, the test indeed does not hang.
Running `zig test test/test.zig -lc` also did not hang.

**Comment by rootbeer** [comment] 2023-10-27 16:15
Can you upload your `build.zig`?  I'm not sure how it could interact oddly with an extra `fflush` in the test, but that seems to be happening ...

**Comment by IvanVnucec** [comment] 2023-10-31 06:58
> Can you upload your `build.zig`? I'm not sure how it could interact oddly with an extra `fflush` in the test, but that seems to be happening ...

Ok. I'will try to show my project setup so one can replicate it.
Project structure:
```
.
├── build.zig
├── src
│   └── lib.c
├── test
│   ├── minunit.h
│   ├── test_lib.c
│   ├── test_runner.h
│   └── test.zig
```
`build.zig`:
```zig
const std = @import("std");
const Step = std.build.Step;
const LazyPath = std.build.LazyPath;

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addStaticLibrary(.{
        .name = "library",
        .target = target,
        .optimize = optimize,
    });
    lib.addCSourceFiles(&.{
            "src/lib.c",
        }, &.{
        "-Wall",
        "-pedantic"
    });
    lib.addIncludePath(.{ .path = "include" });
    b.installArtifact(lib);

    const unit_test = b.addTest(.{
        .root_source_file = .{ .path = "test/test.zig" },
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    unit_test.addCSourceFiles(&.{
            "test/test_lib.c",
        }, &.{
            "-Wall",
            "-pedantic"
    });
    unit_test.addIncludePath(.{ .path = "test" });
    unit_test.linkLibrary(lib);
    unit_test.addIncludePath(.{ .path = "include" });

    const run_unit_tests = b.addRunArtifact(unit_test);

    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_unit_tests.step);
}
```
`src/lib.c` I cannot unfortunately show but I assure you its only math manipulations and It is NOT linked with LibC so it isn't interfering with IO or whatever.
`test/minunit.h` is copied Minunit test library from [here](https://github.com/siu/minunit/blob/master/minunit.h) and it's not modified.
`test/test_lib.c` is dummy file just to replicate the error:
```c
#include "minunit.h"

MU_TEST(test_example) {
    mu_check(0 == 0);
}

MU_TEST_SUITE(test_suite) {
	MU_RUN_TEST(test_example);
}

int test_runner(void) {
	MU_RUN_SUITE(test_suite);
	MU_REPORT();
	return MU_EXIT_CODE;
}
```
`test/test_runner.h` exposes the test runner function definition so it can be included in the zig test runner:
```c
int test_runner(void);
```
`test/test.zig` calls the test runner in a test:
```zig
const std = @import("std");
const testing = std.testing;
const test_runner = @cImport({
    @cInclude("test_runner.h");
});

test "test runner" {
    try testing.expectEqual(@as(i32, 0), test_runner.test_runner());
}
```

That is all one needs to replicate this bug.

**Comment by rootbeer** [comment] 2023-10-31 17:14
I've reproduced the problem with a current Zig (0.12.0-dev.1365+313d1cc69, the `addCSourceFiles` signature changed in the build.zig sometime since v11, but that is the only change required.)

And running the test binary on its own, it works correctly:
```
$ ./zig-cache/o/75f308020b14a47a9407c748bfe0528a/test
Test [1/1] test.test runner... .

1 tests, 1 assertions, 0 failures

Finished in 0.00015092 seconds (real) 0.00014942 seconds (proc)

All 1 tests passed.
```

So, its something about the Zig test-runner interacting poorly with this test (and with the 'fflush' in the test?).

**Comment by rootbeer** [comment] 2023-10-31 17:56
Narrowed it down to just a C stdout fputs/fflush (both seem to be required):

build.zig:
```
const std = @import("std");

pub fn build(b: *std.Build) void {
    const unit_test = b.addTest(.{
        .root_source_file = .{ .path = "test.zig" },
        .link_libc = true,
    });

    const run_unit_tests = b.addRunArtifact(unit_test);

    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_unit_tests.step);
}

```

test.zig:
```
const stdio = @cImport({
    @cInclude("stdio.h");
});

test "fputs-fflush" {
    // Remove either of these lines to avoid the hang
    _ = stdio.fputs("status", stdio.stdout);
    _ = stdio.fflush(stdio.stdout);
}
```

**Comment by rootbeer** [comment] 2023-10-31 19:28
So, a "real" Zig test isn't expected to use stdin/stdout??  Those are used by the Zig test-runner to coordinate the multiple processes it starts.  (I think, I'm new to all of this, and I'm using this bug as an excuse to learn about Zig ...).

The reason "fflush" triggers a problem is because buffered output doesn't get written to stdout, so the fflush is causing the test's output to be seen by the Zig infrastructure.

One work-around seems to be to disable `test_server_mode` on the test executable, as in:
```
    ...
    unit_test.test_server_mode = false;
    const run_unit_tests = b.addRunArtifact(unit_test);
    ...
```

Alternatively, instead of using Zig's `test {}` blocks (and pretending to be a Zig unit test) you can just have a normal Zig binary with a `main()` function that calls the minunit test runner.   Then in your build.zig, you `addExecutable` (instead of `addTest`), and use `expectExitCode(0)` to check the artifact executes correctly.

AFAICT, this can be reproduced without any C code or libraries:
```
test "print" {
    try std.io.getStdOut().writer().print("stdout\n", .{});
}
```
(It could be the build.zig is doing something unsavory, but I don't think so ... AFAICT, any write to stdout will gum up the protocol.)

This all seems very surprising to me, so I'd suggest this is really a bug in the Zig test runner.

**Comment by andrewrk** [comment] 2023-10-31 23:51
Duplicate of #15091

**Closed by andrewrk** 2023-10-31 23:51 UTC
