### ISSUE TITLE
Generated @compileError missing semicolon

### ISSUE THREAD

**Issue by Diltsman** [ziglang/zig#4983] opened 2020-04-09 03:22 UTC
Using the latest build (4/8/2020), I have the following code:

    const std = @import("std");
    const win = @cImport({
        @cInclude("Windows.h");
    });
    
    pub fn main() !void {
        win.RegisterClassExW(null);
    }

I get the following error:

    .\zig-cache\o\efzXXrvTXf_gcKIyG0QKyGyJzfaNgN3EfbmS5AgR30pazMyD5dL_X5pwmr5JQ2gi\cimport.zig:7346:1: error: expected token ';', found 'pub'
    pub const NtCurrentTeb = @compileError("unable to translate function"); // C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\..\um\winnt.h:22627:1
    ^
    ZigVulkan...The following command exited with error code 1:
    C:\Users\dilts\OneDrive\Documents\Zig\zig\zig.exe build-exe C:\Users\dilts\OneDrive\Documents\Zig\ZigVulkan\src\main.zig --library c --cache-dir C:\Users\dilts\OneDrive\Documents\Zig\ZigVulkan\zig-cache --name ZigVulkan --cache on
    
    Build failed. The following command failed:
    C:\Users\dilts\OneDrive\Documents\Zig\ZigVulkan\zig-cache\o\_2fabpGegvT2pO8VBD-7V745YChbDKh-cqkT-SfNCQecmkGN2Qm4DPWKn05igJ0c\build.exe C:\Users\dilts\OneDrive\Documents\Zig\zig\zig.exe C:\Users\dilts\OneDrive\Documents\Zig\ZigVulkan C:\Users\dilts\OneDrive\Documents\Zig\ZigVulkan\zig-cache

At the location that the error is occurring, the surrounding lines are:

    pub const PTP_IO = ?*struct__TP_IO;
    pub const GetCurrentFiber = @compileError("unable to translate function")
    pub const NtCurrentTeb = @compileError("unable to translate function");

Note that the second line is missing a trailing semicolon, and that is the cause of the build error.

**Comment by FireFox317** [comment] 2020-04-09 09:35
Duplicate of #3453

**Comment by Vexu** [comment] 2021-02-25 07:37
Fixed by #7479.

**Closed by Vexu** 2021-02-25 07:37 UTC
Labels: bug, contributor friendly, stage2, translate-c
