### ISSUE TITLE
Panicked during panic during building zig hello world project

### ISSUE THREAD

**Issue by nerodono** [ziglang/zig#18442] opened 2024-01-03 16:44 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

On asahi linux (aarch64, M1 Pro, `Fedora Linux Asahi Remix 39 (Thirty Nine) aarch64`)
1. Download either zig master's prebuilt binary or zig 0.11.0
2. create example project by running `mkdir test-helloworld`, change directory, `zig init-exe`
3. run `zig build`

Also build fails on stage2, while building stage3. lldb shows nothing, I don't know how to provide more info about failure, so I'll be happy if you provide additional guidance!

### Expected Behavior

You'll see build process, and then the following error message:
```
nerodono@fedora:~/Dev/Zig/zig/build/d$ zig build
thread 13251 panic: reached unreachable code
Panicked during a panic. Aborting.
error: the following build command crashed:
/home/nerodono/Dev/Zig/zig/build/d/zig-cache/o/362532143189cb2855a61cdc759dd4f6/build /opt/zig/zig /home/nerodono/Dev/Zig/zig/build/d /home/nerodono/Dev/Zig/zig/build/d/zig-cache /home/nerodono/.cache/zig
```

For stage3 build process:
```
[100%] Building stage3
thread 13785 panic: reached unreachable code
Panicked during a panic. Aborting.
error: the following build command crashed:
/home/nerodono/Dev/Zig/zig/zig-cache/o/e0921c74b72314c4b77dbb562620893f/build /home/nerodono/Dev/Zig/zig/build/zig2 /home/nerodono/Dev/Zig/zig /home/nerodono/Dev/Zig/zig/zig-cache /home/nerodono/.cache/zig --seed 0x97efa293 --prefix /home/nerodono/Dev/Zig/zig/build/stage3 --zig-lib-dir /home/nerodono/Dev/Zig/zig/lib -Dconfig_h=/home/nerodono/Dev/Zig/zig/build/config.h -Denable-llvm -Dno-langref -Dno-autodocs -Dtarget=native -Dcpu=native -Dversion-string=0.12.0-dev.2018+9a56228c2
make[2]: *** [CMakeFiles/stage3.dir/build.make:73: stage3/bin/zig] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/stage3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by nektro** [comment] 2024-01-03 19:53
Duplicate of #16331

**Closed** 2024-01-04 14:22 UTC
Labels: bug
