### ISSUE TITLE
Release builds aren't reproducible unless target is specified

### ISSUE THREAD

**Issue by tavi-vi** [ziglang/zig#12458] opened 2022-08-16 21:16 UTC
### Zig Version

0.10.0-dev.3041+de62bd064

### Steps to Reproduce

- Build a project with the template build.zig file using `-Drelease-{safe,fast}`, or compile a file with `zig build-{exe,lib,obj}` with the flags `-ORelease{Safe,Fast}` on CPUs that have different feature sets
- Compare the results

### Expected Behavior

Zig release builds [should be reproducible](https://ziglang.org/documentation/master/#Build-Mode) by default, not dependent on environment. Not specifying a target should either result in an error or return the same result across platforms.

### Actual Behavior

Zig defaults to using the native CPU model's feature set if 'target' isn't specified via `-target=` or `-Dtarget=` because the `cpu_model` field in the `CrossTarget` struct returned by `standardTargetOptions` is `determined_by_cpu_arch` instead of `baseline` (at least, this is true for `zig build`)

**Comment by andrewrk** [comment] 2022-08-16 21:24
Thank you for the report.

This is by design and not planned to change. Builds are reproducible, however, the "native" target is being resolved into a specific set of CPU feature flags depending on the environment. A build would be reproduced by passing a equivalent -target and -mcpu arguments. An application such as Godbolt should be passing a -target argument 100% of the time.

**Closed by andrewrk** 2022-08-16 21:24 UTC
Labels: question

**Comment by tavi-vi** [comment] 2022-08-16 21:51
Should this be documented somewhere? Because while I understand the reasoning, it comes as a surprise since other compilers require you to explicitly set the arch to native, `-march=native` for gcc and clang, `-C target-cpu=native` for rust, etc.

**Comment by andrewrk** [comment] 2022-08-16 22:53
Yes; everything should be documented somewhere. However, this is also the natural default. C compilers and Rust have it backwards. They already do this for operating system, but inconsistently don't do it for the other 2 parts of the target triple: CPU and ABI.
