### ISSUE TITLE
Segfault upon creation of enum in comptime function with type argument

### ISSUE THREAD

**Issue by SuperAuguste** [ziglang/zig#13727] opened 2022-12-01 08:20 UTC
### Zig Version

0.11.0-dev.399+44ee1c885

### Steps to Reproduce and Observed Behavior

```zig
pub fn abc(comptime T: type) type {
    return enum(T) { a = 0, _ };
}

pub fn main() !void {
    _ = abc(u16);
}
```

```
error: zls-experiments...
error: The following command exited with error code 5
```

Removing the non-exhaustive indicator doesn't change anything :)

### Expected Behavior

Compiler does not segfault.

**Comment by Vexu** [comment] 2022-12-01 08:31
Duplicate of #12272

**Closed by Vexu** 2022-12-01 08:31 UTC
Labels: bug
