### ISSUE TITLE
unused value false positive

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#11704] opened 2022-05-24 02:52 UTC
### Zig Version

0.10.0-dev.2344+1f5b0c115

### Steps to Reproduce

```zig
const std = @import("std");

const S = struct {};

pub fn main() void {
    _ = S{};
    return;
}
```

### Expected Behavior

no output. successful run.

### Actual Behavior

```
./test.zig:6:10: error: expected type 'S', found 'void'
    _ = S{};
         ^
./test.zig:3:11: note: S declared here
const S = struct {};
          ^
```

**Comment by andrewrk** [comment] 2022-05-24 02:54
Does not affect stage2

**Comment by Vexu** [comment] 2023-01-19 16:12
Duplicate of #3054

**Closed by Vexu** 2023-01-19 16:12 UTC
Labels: bug, stage1
