### ISSUE TITLE
Compiler crashes when trying to `comptime break` out of labeled block

### ISSUE THREAD

**Issue by bitterbloom** [ziglang/zig#21080] opened 2024-08-15 00:51 UTC
### Zig Version

0.14.0-dev.1057+76f062690 but also 0.13.0 and 0.12.0

### Steps to Reproduce and Observed Behavior

Trying to compile
```zig
const std = @import("std");

pub fn main() void {
    blk: {
        if (std.time.timestamp() > 0) comptime break :blk;
    }
}
```
with `zig build-exe` crashes (segmentation fault).

### Expected Behavior

The compiler should reject the code as invalid.

Seems similar to #20588 but that produces an LLVM error instead of segfaulting, so my guess is that they are different bugs?

**Comment by mlugg** [comment] 2024-08-15 00:53
Duplicate of #20588 -- the error will be inconsistent since it triggers UB in the compiler.

**Closed by mlugg** 2024-08-15 00:53 UTC
Labels: bug
