### ISSUE TITLE
add compile error hint when if error-union missing else-capture

### ISSUE THREAD

**Issue by ZigC-Lang** [ziglang/zig#16128] opened 2023-06-21 04:41 UTC
### Zig Version

`0.11.0-dev.4186+c72a9feab`

### Steps to Reproduce and Observed Output

```zig
const std = @import("std");

const e1 = error { ErrX };
 
pub fn main() !void {
    if (errorable(5)) |x| {
        std.debug.print("{}\n", .{x});
    } 
    //else |e| {
    //    std.debug.print("{}\n", .{e});
    //}
}

fn errorable(a: u8) !u8 {
    if (a < 3) {
        return a * 3;
    } else { 
        return error.ErrX;
    }
}
```

```
$ zig run test.zig
test.zig:6:27: error: expected optional type, found '@typeInfo(@typeInfo(@TypeOf(test.errorable)).Fn.return_type.?).ErrorUnion.error_set!u8'
    if (errorable(5)) |x| {
                          ^
```

### Expected Output

should point out that `else |err| {}` is missing

**Comment by Vexu** [comment] 2023-10-03 12:57
Duplicate of #8679

**Closed by Vexu** 2023-10-03 12:57 UTC
Labels: enhancement, error message
