### ISSUE TITLE
Local variable incorrectly flagged as never mutated

### ISSUE THREAD

**Issue by clarityflowers** [ziglang/zig#20520] opened 2024-07-07 00:06 UTC
### Zig Version

0.13.0-dev.360+7f6ec51c8

### Steps to Reproduce and Observed Behavior

The following program

```zig
const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = &gpa.allocator();
    var buffer = try allocator.alloc(u8, 1);
    defer allocator.free(buffer);

    // uncomment to fix compile error
    // buffer[0] = undefined;

    var stream = std.io.fixedBufferStream(buffer);
    const writer = stream.writer();

    try writer.writeByte(110);
    std.debug.print("Result: {s}\n", .{std.fmt.fmtSliceHexLower(buffer)});
}
```

Produces the compile error:
```
src/main.zig:6:9: error: local variable is never mutated
    var buffer = try allocator.alloc(u8, 1);
        ^~~~~~
src/main.zig:6:9: note: consider using 'const'
```

Uncommenting the marked line allows it to compile successfully.

### Expected Behavior

It should compile without needing the commented line. This program doesn't have any issues and marking the variable as `const` as recommended causes it to fail to compile.

**Comment by Rexicon226** [comment] 2024-07-07 00:17
It compiles when making `buffer` constant. `alloc` returns a slice to mutable memory. `buffer` itself doesn't need to be mutable to modify the contents that it's pointing at. See: [here](https://ziglang.org/documentation/master/#Slices).

Another note is that you shouldn't do `&gpa.allocator()`, instead just do `const allocator = gpa.allocator();`. The `std.mem.Allocator` interface contains a pointer to the mutable state of the allocator.

And another note, you don't need `fmtSliceHexLower`, using `{x}` will achieve the same result iirc.

**Comment by squeek502** [comment] 2024-07-07 01:07
Not a bug. There is probably a more correct explanation, but my understanding is that the `const` applies only the the variable here, not the type, so:

```
    const buffer = try allocator.alloc(u8, 1);
    defer allocator.free(buffer);

    @compileLog(@TypeOf(buffer));
```

outputs `[]u8` just the same as if `buffer` were var, and

```
    const buffer = try allocator.alloc(u8, 1);
    defer allocator.free(buffer);

    buffer[0] = 1;
```

works just fine.

By marking it as `const`, you only disallow the following:

```
buffer.len = <something>;
buffer.ptr = <something>;
```

which will fail to compile with `cannot assign to constant`.

---

In the future, it's better to direct questions like this to [one of the community spaces](https://github.com/ziglang/zig/wiki/Community) first.

**Closed by squeek502** 2024-07-07 01:07 UTC
Labels: question

**Comment by clarityflowers** [comment] 2024-07-07 01:09
Ohh yeah I mixed up `const` variables with `const ptrs`, you're right.
