### ISSUE TITLE
Discarding a void-returning function call is allowed

### ISSUE THREAD

**Issue by MatthiasPortzel** [ziglang/zig#22120] opened 2024-12-02 03:31 UTC
### Zig Version

0.14.0-dev.2370+5c6b25d9b

### Steps to Reproduce and Observed Behavior

Given `22120-repo.zig`:
```
fn foo() void {

}

pub fn main() void {
    _ = foo();
}
```
`zig run 22120-repo.zig` completes without issue.

### Expected Behavior

Compiler error, like `pointless discard of void function`. Since I know that Zig errors on pointless discards of used variables, and for the same reason that Zig requires discards of non-void functions, I expected Zig to compile-error on this pointless discard. (I had inadvertently introduced the discard in a refactor.)

**Comment by rohlem** [comment] 2024-12-02 13:22
The current regularity of `void` compared to other types is highly useful in generic code.
You can f.e. provide a callback returning `T`, and have the same code paths work for `T` carrying information as for `void`,
because `void` is a type like any other, so can be assigned to `var`, `const`, used as function arguments, struct/union fields etc. .

Requiring special-casing around `void` would probably mean I have to work around this restriction
by rewriting my code to instead use a custom `const Void = struct{};`, so highly dislike this proposed change.

**Comment by Vexu** [comment] 2024-12-02 14:26
Duplicate of #16642

**Closed by Vexu** 2024-12-02 14:26 UTC
Labels: bug

**Comment by MatthiasPortzel** [comment] 2024-12-02 23:56
I still think this change should be made.

First, I think you lose a lot of the clarity from requiring discarding non-void return values by allowing void functions returns to be discarded. I view this not as an additional special-casing of void, but the natural extension of the fact that void doesn't require a discard when other types do. This is why I view this as a bug and not a proposal.

Second, I think cases where someone like me accidentally discards a void function result are a lot more common than instances where someone is calling a function a) that has a void or not-void return type depending on comptime logic b) is discarding the return value and c) doesn't have easy access to the comptime condition that determines whether it discards or not. I'm skeptical that even @rohlem would actually hit this—I'd love to see your code.

The theoretical case that would be effected looks like:

```zig
fn shouldReturn() bool {
    // Or other comptime logic
    return @import("builtin").os.tag == .freestanding);
}
fn decideReturnType() type {
    if (comptime shouldReturn()) void else usize;
}

fn foo() decideReturnType() {
    if (comptime shouldReturn()) {
        return 5;
    }
}

pub fn main() void {
    _ = foo();
}

extern secondCallSite void {
    if (shouldReturn()) {
        const std_out = std.io.getStdOut().writer();
        try std_out.print("{}", foo());
    }
}
```
If this issue was addressed, the first call site of `foo` would need to be updated to the below. Even in this contrived case, it makes sense (IMO) to require the extra condition to make it clear that the function may or may not return a value.
```zig
pub fn main() void {
    if (shouldReturn()) {
        _ = decideReturnType();
    } else {
        decideReturnType();
    }
}
```

Does it make sense for me to open a proposal to discuss further? I don't want to bike-shed programming language design; this was something that I actually hit refactoring my code that I think Zig could detect.

https://tildegit.org/matthias/Micromouse/src/commit/3dfa6802a63a53b7a066ef1011e6fe4772631610/src/sd.zig#L238 The guilty line in my program (although it is not apparent until you check the function definition).

**Comment by rohlem** [comment] 2024-12-03 00:48
There are several points I extrapolated from the initial post, half-remembering the previous issue #16642 .
It was opened as bug, and I still believe the current behavior is intentional.

> Does it make sense for me to do the work of writing up a proposal to discuss further?

Note that the github issue template tells people not to open language proposals.
(This is sometimes ignored, by maintainers and random people alike, to varying results. When in doubt, it can be seen as advice to invest people's time and energy elsewhere.)

As for my personal opinion, while `f();` clearly shows that `f` returns `void`, it factually does the same as `_ = f();`, so neither code is incorrect, just one is stylistically clearer.
A reader might think `_ = f();` discards a non-`void` value, but when changing code to use the value they will realize that it is of type `void`.
I don't think there is a scenario where discarding syntax for `void` could ever lead to a bug, nor where non-discarding syntax for `void` could ever prevent a bug.

If your intended outcome is that changing a return type from `void` to some other `T` should point you to update all callsites,
note that changing a return type `T` to some other `S` doesn't necessarily point you to all callsites either, only the ones were the callsite's code breaks from the change.
Exhaustively listing all usage sites of something would be a useful feature (whether provided by the compiler or IDE),
but I think an orthogonal generic form like `@showAllUses(x);` would cover more use cases than just `void` vs non-`void`.
