### ISSUE TITLE
Unreachable in stage1/analyze.cpp

### ISSUE THREAD

**Issue by zenspider** [ziglang/zig#12782] opened 2022-09-08 10:54 UTC
### Zig Version

0.10.0-dev.3457+5c9826630

### buggy.zig:
```zig
const std = @import("std");
const alloc = std.testing.allocator;
pub fn expectEqualDeep(expected: anytype, actual: @TypeOf(expected)) error{}!void {
    switch (@typeInfo(@TypeOf(actual))) {
        .Pointer => |pointer| switch (pointer.size) {
            .Slice => @panic(""),
            else => return try expectEqualDeep(expected.*, actual.*),
        },
        .Struct => |structType| inline for (structType.fields) |field| {
            try expectEqualDeep(@field(expected, field.name), @field(actual, field.name));
        },
        .Union => inline for (std.meta.fields(@TypeOf(actual))) |fld| {
            return try expectEqualDeep(@field(expected, fld.name), @field(actual, fld.name));
        },
        else => {},
    }
}
const Stmt = union(enum) {
    stmts: std.ArrayList(*Stmt), // NOTE: existance needed for bug!
    expr: *const Expr,
    pub fn expr(e: *const Expr) *Stmt {
        var p = alloc.create(Stmt) catch @panic("");
        p.* = Stmt{ .expr = e };
        return p;
    }
};
const Expr = union(enum) {
    literal: bool,
    pub fn lit_true() *const Expr {
        var p = alloc.create(Expr) catch @panic("");
        return p;
    }
};
test "Parser.exprStmt" {
    const a = Stmt.expr(Expr.lit_true());
    const b = Stmt.expr(Expr.lit_true());
    try expectEqualDeep(a, b);
}
```

Then run `zig test buggy.zig`

### Expected Behavior

Not get a stage 2 panic

### Actual Behavior

```
Unreachable at /Users/ryan/Work/git/ziglang/zig/src/stage1/analyze.cpp:5460 in handle_is_ptr. This is a bug in the Zig compiler.thread 6003841 panic: 
???:?:?: 0x1022d4f73 in _stage2_panic (???)
???:?:?: 0x10794954b in __Z9zig_panicPKcz (???)
???:?:?: 0x1034ea9c3 in __Z13handle_is_ptrP7CodeGenP7ZigType (???)
???:?:?: 0x10355f283 in __ZL16get_handle_valueP7CodeGenP15LLVMOpaqueValueP7ZigTypeS4_ (???)
???:?:?: 0x10356ef17 in __ZL18ir_render_load_ptrP7CodeGenP9Stage1AirP20Stage1AirInstLoadPtr (???)
???:?:?: 0x10356bf3b in __ZL21ir_render_instructionP7CodeGenP9Stage1AirP13Stage1AirInst (???)
???:?:?: 0x10356b003 in __ZL9ir_renderP7CodeGenP5ZigFn (???)
???:?:?: 0x10355aabf in __ZL11do_code_genP7CodeGen (???)
???:?:?: 0x103557fcb in __Z20codegen_build_objectP7CodeGen (???)
???:?:?: 0x103621faf in _zig_stage1_build_object (???)
???:?:?: 0x10269dffb in _Module.build_object (???)
???:?:?: 0x10242f12b in _Compilation.updateStage1Module (???)
???:?:?: 0x10242246f in _Compilation.performAllTheWork (???)
???:?:?: 0x10241c3b3 in _Compilation.update (???)
???:?:?: 0x1023bcc0b in _main.updateModule (???)
???:?:?: 0x102329163 in _main.buildOutputType (???)
???:?:?: 0x1022d3b47 in _main.mainArgs (???)
???:?:?: 0x1022d33f7 in _main (???)
???:?:?: 0x10dfa508b in ??? (???)
???:?:?: 0xde337fffffffffff in ??? (???)
```

**Comment by Vexu** [comment] 2022-09-08 11:25
Duplicate of #11588

**Closed by Vexu** 2022-09-08 11:25 UTC
Labels: bug
