### ISSUE TITLE
better error message or make @compileError to be able to point to the error source location?

### ISSUE THREAD

**Issue by taikoo** [ziglang/zig#16222] opened 2023-06-26 09:01 UTC
### Zig Version

0.11.0-dev.3817+a31ba25a3

### Steps to Reproduce and Observed Output

```zig
const print = @import("std").debug.print;

const number: i32 = 1234;
const string = "foo";

test "print too many arguments" {
    print("here is a string: '{s}' here is a number: {}\n", .{
        string,
        number,
        number,
        "hello",
    });
}
```
zig test test.zig
```
lib/zig/std/fmt.zig:203:21: error: 2 unused arguments in 'here is a string: '{s}' here is a number: {}
                                            '
            else => @compileError(comptimePrint("{d}", .{missing_count}) ++ " unused arguments in '" ++ fmt ++ "'"),
```

### Expected Output

improve `print` to report error like the following:
```
$ rustc unused_arg.rs 
error: multiple unused formatting arguments
 --> unused_arg.rs:3:35
  |
3 |     println!("hello {}", "world", 1, 2, 3);
  |              ----------           ^  ^  ^ argument never used
  |              |                    |  |
  |              |                    |  argument never used
  |              |                    argument never used
  |              multiple missing formatting specifiers

error: aborting due to previous error
```

or
can we update `@compileError(<error-message>)` to something like this `@compileError(<error-message>, <error-source-location>)`?

**Comment by Vexu** [comment] 2023-06-26 12:54
I proposed a fix for this in https://github.com/ziglang/zig/issues/12093#issuecomment-1585340480

**Comment by andrewrk** [comment] 2023-07-22 23:26
Duplicate of #12093

**Closed by andrewrk** 2023-07-22 23:26 UTC
Labels: error message
