### ISSUE TITLE
std.mem.zeroes compilation issue

### ISSUE THREAD

**Issue by jgh713** [ziglang/zig#18705] opened 2024-01-27 08:35 UTC
### Zig Version

0.12.0-dev.2334+aef1da163

### Steps to Reproduce and Observed Behavior

Relevant AoC code for reference: https://github.com/jgh713/aoc-2023/blob/main/src/day25.zig

When initializing large array types with std.mem.zeroes, such as:
`var components: [32768]Component = std.mem.zeroes([32768]Component);`

Debug builds run without issue, but when compiling to any release build, std.mem.zeroes will attempt to pass 32768 separate initialize memory instructions to LLVM, which takes a 2 second debug compile time to around 17 minutes of LLVM compilation, and also results in a much larger and slower binary (about 14.4x slower than debug build).

### Expected Behavior

There's two solutions to this currently. One is to mark the std.mem.zeroes call as comptime in the calling function, like so:
`var components: [32768]Component = comptime std.mem.zeroes([32768]Component);`

This drops compile time to around 11 seconds and makes ReleaseFast perform as expected (much faster than debug build).

Since the type for std.mem.zeroes is known at comptime, I was investigating how easy it would be to just force all calls to be comptime. Changing the std.mem.zeroes function to an inline function and make the entire switch block comptime, which surprisingly brought the compile time down to 6 seconds, and allowed for even further optimizations on LLVM's part, increasing the ReleaseFast build's performance further, though that's almost certainly due to similar improvements made across ther std.mem.zeroes calls.

I'm not sure if there's reasons you'd want std.mem.zeroes to have separate initialization instructions for optimizations with smaller array types, but making this one change to the standard library improved compile times across all scripts using std.mem.zeroes (anecdotal, for sure, but I have both large and small allocations with it). Since std.mem.zeroes is always known at comptime, it might be worth ensuring that this function is always calculated as a comptime block, to avoid these extreme LLVM optimization times.

Edit: ps don't judge the trash code linked above. It was very much a version 1 without cleanup, I just wanted to preserve the unfortunate behaviour until I could isolate why it was happening.

**Comment by jgh713** [comment] 2024-01-27 08:38
Or if this unfortunate behaviour needs to remain as-is for some reason, there should probably be some very big notes in bright red letters on the function description that say "you should almost certainly mark this function as comptime for any non-trivial allocations".

**Comment by notcancername** [comment] 2024-01-27 15:31
You could also use
```zig
@memset(&components, 0)
```
.

**Comment by jgh713** [comment] 2024-01-27 19:31
> You could also use
> 
> ```zig
> @memset(&components, 0)
> ```
> 
> .

Yeah, my bad, I meant to mention this as the second solution above. The comptime solution seemed slightly more performant but that might be just slight variation, and there might be reasons to use memset instead. I haven't looked down into the IR to compare the two. Just seems like an odd quirk of how the ** operator expands into IR and might cause issues in strange places. Ideally unrolling ** would work in a similar way to memset, rather than inlining a bunch of instructions, especially since memset can't be used to initialise const values (seems like a very niche use case, but I think there's a few edge cases you might want it for). I'm not sure if that's an optimization that can be made at the compiler level, though, so at the very least modifying the std.mem.zeroes (and possibly zeroInit) functions to be explicitly comptime is going to (seemingly) speed up build times across the board.

**Comment by Vexu** [comment] 2024-01-27 19:46
Duplicate of #15266

**Closed by Vexu** 2024-01-27 19:46 UTC
Labels: bug
