### ISSUE TITLE
Build instructions for MacOS do not work with llvm 11. Homebrew install currently llvm 10.0.1_2

### ISSUE THREAD

**Issue by jsyrjala** [ziglang/zig#6665] opened 2020-10-13 16:44 UTC
Build instructions for [MacOS in README.md](https://github.com/ziglang/zig/blob/master/README.md#macos) do not work after llvm11 branch was merged. Homebrew installs currently llvm 10.0.1_2, and code seems to except llvm11.

**Comment by wozeparrot** [comment] 2020-10-13 18:21
You either have to wait for homebrew to update llvm or compile llvm11 from source.

**Comment by jayschwa** [comment] 2020-10-13 19:20
Upstream PR: https://github.com/Homebrew/homebrew-core/pull/62798

**Comment by timmyjose** [comment] 2020-10-14 04:21
It's heartening to see the Zig community working in tandem with the Homebrew folks on such releases. It's a much quicker turnaround time now compared to even the last release of LLVM. Kudos!

**Comment by gaultier** [comment] 2020-10-16 06:04
You can download an already built llvm for macOS here: https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0.
Assuming you extracted and put this folder in `$HOME/code/clang+llvm-11.0.0-x86_64-apple-darwin`, you can compile `zig` with:
 `cmake .. -DCMAKE_PREFIX_PATH="$HOME/code/clang+llvm-11.0.0-x86_64-apple-darwin;/usr/local"; make`

If you get the annoying linking error: `ld: library not found for -llibxml2.tbd`, the workaround is:
`brew install libxml2 &&  ln -s /usr/local/opt/libxml2/lib/libxml2.dylib /usr/local/lib/liblibxml2.tbd.dylib` and then re-run cmake and make.

**Comment by DanB91** [comment] 2020-10-17 14:17
@gaultier I tried your steps (including the libxml2 step) and I'm getting the following linking error:
```
ld: warning: ignoring file zigcpp/libzigstage1.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file zigcpp/libopt_c_util.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
ld: warning: ignoring file zigcpp/libembedded_softfloat.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
ld: warning: ignoring file zigcpp/libzigcpp.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
Undefined symbols for architecture x86_64:
  "_ZigLLVMGetHostCPUName", referenced from:
      target_parse_triple(ZigTarget*, char const*, char const*, char const*) in zig0.cpp.o
  "_ZigLLVMGetNativeFeatures", referenced from:
      target_parse_triple(ZigTarget*, char const*, char const*, char const*) in zig0.cpp.o
  "_ZigLLVMGetNativeTarget", referenced from:
      get_native_target(ZigTarget*) in zig0.cpp.o
  "target_parse_os(Os*, char const*, unsigned long)", referenced from:
      target_parse_triple(ZigTarget*, char const*, char const*, char const*) in zig0.cpp.o
  "target_parse_abi(ZigLLVM_EnvironmentType*, char const*, unsigned long)", referenced from:
      target_parse_triple(ZigTarget*, char const*, char const*, char const*) in zig0.cpp.o
  "target_parse_arch(ZigLLVM_ArchType*, char const*, unsigned long)", referenced from:
      target_parse_triple(ZigTarget*, char const*, char const*, char const*) in zig0.cpp.o
  "SplitIterator_next(SplitIterator*)", referenced from:
      target_parse_triple(ZigTarget*, char const*, char const*, char const*) in zig0.cpp.o
  "os_fetch_file_path(Buf*, Buf*)", referenced from:
      _stage2_fetch_file in zig0.cpp.o
  "target_default_abi(ZigLLVM_ArchType, Os)", referenced from:
      target_parse_triple(ZigTarget*, char const*, char const*, char const*) in zig0.cpp.o
      get_native_target(ZigTarget*) in zig0.cpp.o
  "err_str(Error)", referenced from:
      _main in zig0.cpp.o
  "memSplit(Slice<unsigned char>, Slice<unsigned char>)", referenced from:
      target_parse_triple(ZigTarget*, char const*, char const*, char const*) in zig0.cpp.o
  "zig_panic(char const*, ...)", referenced from:
      get_zig_os_type(ZigLLVM_OSType) in zig0.cpp.o
      zig_assert(bool, char const*, int, char const*) in zig0.cpp.o
  "heap::c_allocator", referenced from:
      _main in zig0.cpp.o
      ZigList<char>::ensure_capacity(unsigned long) in zig0.cpp.o
  "_zig_stage1_build_object", referenced from:
      _main in zig0.cpp.o
  "_zig_stage1_create", referenced from:
      _main in zig0.cpp.o
  "_zig_stage1_destroy", referenced from:
      _main in zig0.cpp.o
  "_zig_stage1_os_init", referenced from:
      _main in zig0.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I assume the undefined symbols are because of the ignored .a files

**Comment by gaultier** [comment] 2020-10-17 16:07
Hmm, interesting. At least the errors are now coming from the project 😅
Have you maybe tried to delete every file inside the build directory and re-running the commands? Sometimes it can happen with cmake.
If that does not help, your guess is as good as mine...those .a files that are being ignored should not be ignored... you can try with ‘nm’ to check if they indeed contain the symbols being required.

**Comment by jedisct1** [comment] 2020-10-17 16:48
Homebrew is soon going to have the update, that includes a fix for the libxml2 issue.

**Comment by DanB91** [comment] 2020-10-17 19:48
> Hmm, interesting. At least the errors are now coming from the project 😅
> Have you maybe tried to delete every file inside the build directory and re-running the commands? Sometimes it can happen with cmake.
> If that does not help, your guess is as good as mine...those .a files that are being ignored should not be ignored... you can try with ‘nm’ to check if they indeed contain the symbols being required.

Yea I tried deleting the build folder and running a `git clean -fd` and same issue.  And confirmed the undefined symbols are in those .a files.  Probably of no use, but, here is the contents of my llvm11 installation.   Thank you for the help

```
$ ls $HOME/code/clang+llvm-11.0.0-x86_64-apple-darwin
bin     include lib     libexec share
```

**Comment by DanB91** [comment] 2020-10-17 23:01
Figured out the issue.  Looks like it was using `ar` in my binutils installation in homebrew.  So I just removed binutils with `brew uninstall binutils`.  Also needed to remove all llvm installations from homebrew and remove any straggling `libLLVM*.a` library files in `/usr/local/lib`.

**Comment by slimsag** [comment] 2020-10-24 21:54
Upstream PR was merged: https://github.com/Homebrew/homebrew-core/pull/62798

**Comment by jsyrjala** [comment] 2020-10-25 14:43
Build instructions are now working.

**Closed** 2020-10-25 15:33 UTC
Labels: os-macos, upstream
