### ISSUE TITLE
broken LLVM module with mem.span of string literals

### ISSUE THREAD

**Issue by bark2** [ziglang/zig#7467] opened 2020-12-16 21:37 UTC
code:
`print("Hello from {}!\n", .{ if (pid == 0) std.mem.span("child") else std.mem.span("parent") });`

building:
```
~/src/kernel zig version
0.7.1
~/src/kernel zig build user
broken LLVM module found: Instruction does not dominate all uses!
  %16 = getelementptr inbounds %"struct:14:36", %"struct:14:36"* %1, i32 0, i32 0, !dbg !630
  call fastcc void @std.mem.span.4(%"[]u8"* sret %16, [7 x i8]* @25), !dbg !631
Instruction does not dominate all uses!
  %16 = getelementptr inbounds %"struct:14:36", %"struct:14:36"* %1, i32 0, i32 0, !dbg !630
  %19 = bitcast %"[]u8"* %16 to i8*, !dbg !631
Instruction does not dominate all uses!
  %16 = getelementptr inbounds %"struct:14:36", %"struct:14:36"* %1, i32 0, i32 0, !dbg !630
  %20 = bitcast %"[]u8"* %16 to i8*, !dbg !631

This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
user...The following command terminated unexpectedly:
/usr/bin/zig build-exe /home/bar/src/kernel/src/user.zig --cache-dir /home/bar/src/kernel/zig-cache --global-cache-dir /home/bar/.cache/zig --name user -target aarch64-freestanding -mcpu cortex_a53 --script /home/bar/src/kernel/src/user.debug.ld --enable-cache 
error: the following build command failed with exit code 6:
/home/bar/src/kernel/zig-cache/o/db6c4c29fde60bb4e429b84be3ed459f/build /usr/bin/zig /home/bar/src/kernel /home/bar/src/kernel/zig-cache /home/bar/.cache/zig user
```

**Comment by Vexu** [comment] 2020-12-17 15:56
Duplicate of #6755.

**Closed by Vexu** 2020-12-17 15:56 UTC
