### ISSUE TITLE
Zig compiler build failure on macOS(Ventura 13.3)

### ISSUE THREAD

**Issue by EndlessArch** [ziglang/zig#15121] opened 2023-03-30 07:59 UTC
### Zig Version

0.10.0 (from homebrew)

### Steps to Reproduce and Observed Behavior

```
cmake -S . -B out -DCMAKE_BUILD_TYPE=Release
cmake --build out --parallel
```
above commands showed this:
```
[ 10%] Built target zig-wasm2c
[ 30%] Built target zig1
[ 70%] Built target zigcpp
[ 95%] Built target zig2
[100%] Building stage3
zig build-exe zig ReleaseFast native: error: the following command terminated unexpectedly:
/Users/hep/Documents/DL/zig/out/zig2 build-exe --stack 33554432 /Users/hep/Documents/DL/zig/src/main.zig /Users/hep/Documents/DL/zig/out/zigcpp/libzigcpp.a /usr/local/Cellar/llvm@15/15.0.7/lib/libclang-cpp.dylib /usr/local/Cellar/llvm@15/15.0.7/lib/liblldMinGW.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldELF.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldCOFF.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldWasm.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldMachO.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldCommon.a -lLLVM-15 -lz -lzstd -lcurses -lxml2 -lc++ -lc -fstrip -OReleaseFast --cache-dir /Users/hep/Documents/DL/zig/zig-cache --global-cache-dir /Users/hep/.cache/zig --name zig -headerpad_max_install_names --mod build_options::/Users/hep/Documents/DL/zig/zig-cache/c/67f5edb06a962800b576d02954deda5e/options.zig --deps build_options -I /usr/local/Cellar/llvm@15/15.0.7/include -I /usr/local/Cellar/llvm@15/15.0.7/include -L /usr/local/Cellar/llvm@15/15.0.7/lib -fno-build-id --zig-lib-dir /Users/hep/Documents/DL/zig/lib --enable-cache --listen=- 
Build Summary: 1/3 steps succeeded; 1 failed (disable with -fno-summary)
compile transitive failure
└─ zig build-exe zig ReleaseFast native failure
   └─ options cached
error: the following build command failed with exit code 1:
/Users/hep/Documents/DL/zig/zig-cache/o/220db9214037afb5461e1e8e78ffef01/build /Users/hep/Documents/DL/zig/out/zig2 /Users/hep/Documents/DL/zig /Users/hep/Documents/DL/zig/zig-cache /Users/hep/.cache/zig compile --zig-lib-dir /Users/hep/Documents/DL/zig/lib -Dconfig_h=/Users/hep/Documents/DL/zig/out/config.h -Denable-llvm -Drelease -Dstrip -Dtarget=native -Dcpu=native -Dversion-string=0.11.0-dev.2298+5d63d1115
gmake[2]: *** [CMakeFiles/stage3.dir/build.make:71: CMakeFiles/stage3] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/stage3.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```
I doubt if the library linking has a problem
```
# libzstd.a(/dylib) are at /usr/local/lib
# libz, libcurses, libxml2, libc++, libc are at .../MacOSX13.sdk/usr/lib/
export LD_LIBRARY_PATH=/usr/local/lib;/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/lib
rm -rf out
cmake -S . -B out -DCMAKE_BUILE_TYPD=Release
cmake --build out --parallel
```
<details>
<summary>but it showed same log</summary>

```
[ 10%] Built target zig-wasm2c
[ 30%] Built target zig1
[ 70%] Built target zigcpp
[ 95%] Built target zig2
[100%] Building stage3
zig build-exe zig ReleaseFast native: error: the following command terminated unexpectedly:
/Users/hep/Documents/DL/zig/out/zig2 build-exe --stack 33554432 /Users/hep/Documents/DL/zig/src/main.zig /Users/hep/Documents/DL/zig/out/zigcpp/libzigcpp.a /usr/local/Cellar/llvm@15/15.0.7/lib/libclang-cpp.dylib /usr/local/Cellar/llvm@15/15.0.7/lib/liblldMinGW.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldELF.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldCOFF.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldWasm.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldMachO.a /usr/local/Cellar/llvm@15/15.0.7/lib/liblldCommon.a -lLLVM-15 -lz -lzstd -lcurses -lxml2 -lc++ -lc -fstrip -OReleaseFast --cache-dir /Users/hep/Documents/DL/zig/zig-cache --global-cache-dir /Users/hep/.cache/zig --name zig -headerpad_max_install_names --mod build_options::/Users/hep/Documents/DL/zig/zig-cache/c/67f5edb06a962800b576d02954deda5e/options.zig --deps build_options -I /usr/local/Cellar/llvm@15/15.0.7/include -I /usr/local/Cellar/llvm@15/15.0.7/include -L /usr/local/Cellar/llvm@15/15.0.7/lib -fno-build-id --zig-lib-dir /Users/hep/Documents/DL/zig/lib --enable-cache --listen=- 
Build Summary: 1/3 steps succeeded; 1 failed (disable with -fno-summary)
compile transitive failure
└─ zig build-exe zig ReleaseFast native failure
   └─ options cached
error: the following build command failed with exit code 1:
/Users/hep/Documents/DL/zig/zig-cache/o/220db9214037afb5461e1e8e78ffef01/build /Users/hep/Documents/DL/zig/out/zig2 /Users/hep/Documents/DL/zig /Users/hep/Documents/DL/zig/zig-cache /Users/hep/.cache/zig compile --zig-lib-dir /Users/hep/Documents/DL/zig/lib -Dconfig_h=/Users/hep/Documents/DL/zig/out/config.h -Denable-llvm -Drelease -Dstrip -Dtarget=native -Dcpu=native -Dversion-string=0.11.0-dev.2298+5d63d1115
gmake[2]: *** [CMakeFiles/stage3.dir/build.make:71: CMakeFiles/stage3] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/stage3.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```
</details>

I also tested `clang -l(libraries above) test.c` with `LD_LIBRARY_PATH` defined, but I couldn't find any problem.
And I tried compiling with zig2 from message, `zig2 run --stack ...` led me to kernel panic(shutdown; it was necessary for me to remove ./zig-cache and ./zig-out to try more zig2 commands. Otherwise, shutdown happened even with other arguments)

I accidently entered `zig2 build compile` and compile could be done but with some memory warning(?error).
With this defectively produced zig(0.11.0-dev.2298+5d63d1115), zls blamed <details><summary>this errror:</summary>

```
error: (store ): Failed to execute build runner to collect build configuration, command:
/usr/local/bin/zig build --build-runner /Users/hep/Library/Caches/zls/build_runner.zig
Error: thread 37092 panic: attempt to use null value
/Users/hep/Documents/DL/zig/src/link/MachO.zig:2324:57: 0x101d2b226 in getDeclOutputSection (zig)
                break :blk self.data_const_section_index.?;
                                                        ^
/Users/hep/Documents/DL/zig/src/link/MachO.zig:2290:49: 0x101d2aec1 in getOrCreateAtomForDecl (zig)
            .section = self.getDeclOutputSection(decl_index),
                                                ^
/Users/hep/Documents/DL/zig/src/link/MachO.zig:2235:55: 0x101d3ee66 in updateDecl (zig)
    const atom_index = try self.getOrCreateAtomForDecl(decl_index);
                                                      ^
/Users/hep/Documents/DL/zig/src/link.zig:537:77: 0x101b7db3b in updateDecl (zig)
            .macho => return @fieldParentPtr(MachO, "base", base).updateDecl(module, decl_index),
                                                                            ^
/Users/hep/Documents/DL/zig/src/Module.zig:6404:29: 0x101b7d5ce in linkerUpdateDecl (zig)
    comp.bin_file.updateDecl(mod, decl_index) catch |err| switch (err) {
                            ^
/Users/hep/Documents/DL/zig/src/Compilation.zig:3100:52: 0x101cbb750 in processOneJob (zig)
                        try module.linkerUpdateDecl(decl_index);
                                                   ^
/Users/hep/Documents/DL/zig/src/Compilation.zig:3054:30: 0x101bc0545 in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
/Users/hep/Documents/DL/zig/src/Compilation.zig:2011:31: 0x101bbc7bd in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/Users/hep/Documents/DL/zig/src/main.zig:3913:24: 0x101bedeaf in updateModule (zig)
        try comp.update(main_progress_node);
                       ^
/Users/hep/Documents/DL/zig/src/main.zig:4589:21: 0x101ad0951 in cmdBuild (zig)
        updateModule(gpa, comp, .none) catch |err| switch (err) {
                    ^
/Users/hep/Documents/DL/zig/src/main.zig:298:24: 0x101a9a41e in mainArgs (zig)
        return cmdBuild(gpa, arena, cmd_args);
                       ^
/Users/hep/Documents/DL/zig/src/main.zig:211:20: 0x101a99007 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/hep/Documents/DL/zig/lib/std/start.zig:617:37: 0x101a9b6bd in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7ff809c1141e in ??? (???)
???:?:?: 0x0 in ??? (???)

error: (store ): Failed to load build configuration for file:///Users/hep/Documents/DL/zig/build.zig (error: error.RunFailed)
```
</details>

### Expected Behavior

No problem should be occured

**Comment by EndlessArch** [comment] 2023-03-30 08:07
Above zls error message is shown from other project directory, ~/Documents/DL/zig is where the zig compiled.

**Comment by kubkon** [comment] 2023-03-31 09:16
Did you follow this guide when building Zig from source https://github.com/ziglang/zig/wiki/Building-Zig-From-Source ? FWIW I am running macOS 13.3 and have no problem in building Zig from source. If the issue will still persist after trying the official guide, it would be good if you provided a more detailed description of your local setup and step-by-step repro guide, as from the attached stack traces I cannot work out what the problem could be.

**Comment by EndlessArch** [comment] 2023-04-01 14:48
I tried the guide, but I failed for a few times.
However I could successfully build:
`cmake .. -DCMAKE_PREFIX_PATH="$(brew --prefix llvm@15);$(brew --prefix zstd)" -DCMAKE_BUILD_TYPE=Release`
Thanks :) closing the bug

**Comment by EndlessArch** [comment] 2023-04-01 15:13
Thought almost figure out, but failed no longer after closing the issue,
Here is the kernel error message https://github.com/ziglang/zig/issues/14508#issuecomment-1492999813

**Comment by kubkon** [comment] 2023-04-01 15:44
Could you try with latest Zig master?

**Comment by Miloas** [comment] 2023-04-07 10:12
Just providing some infomations:
```
chip: Apple M1
macOS: 13.4
```
Latest zig master works fine.

<img width="810" alt="Screenshot 2023-04-07 at 18 07 48" src="https://user-images.githubusercontent.com/11530682/230590921-78ffe88e-339e-442d-9c93-bf695b8d2941.png">

But if you build it from homebrew may meet other issues, since latest zig (13aa7871b274fd22c7fdf277174a43d09788bd27) depends on llvm 16, but the official homebrew formula does not update (https://github.com/Homebrew/homebrew-core/blob/master/Formula/zig.rb#L21).

**Comment by andrewrk** [comment] 2023-06-20 20:08
Duplicate of #12591

**Closed by andrewrk** 2023-06-20 20:08 UTC
Labels: bug, os-macos
