### ISSUE TITLE
Error return trace contains unrelated errors

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#7323] opened 2020-12-07 07:51 UTC
This may be an expected behavior, but it was surprising to me.  Error return traces contain unrelated caught errors.

Repro program:
```zig
pub fn returnError() !void {
    return error.Foo;
}

pub fn returnUnrelatedError() !void {
    return error.Bar;
}

pub fn main() !void {
    returnError() catch {};
    try returnUnrelatedError();
}
```
Output:
```
error: Bar
C:\test.zig:2:5: 0x7ff7f13eab44 in returnError (test.obj)
    return error.Foo;
    ^
C:\test.zig:6:5: 0x7ff7f13eab64 in returnUnrelatedError (test.obj)
    return error.Bar;
    ^
C:\test.zig:12:5: 0x7ff7f13d3558 in main (test.obj)
    try returnUnrelatedError();
    ^
```

---

If this is the expected behavior, then this is an issue for the standard library.  `std.ArrayList.append` apparently handles an `OutOfMemory` error during normal operation, when the system is not actually out of memory.  Under the above behavior, the following common loop will give misleading error messages:

```zig
var list_of_nums = std.ArrayList(u32).init(some_allocator);
for (list_of_strings) |str| {
    list_of_nums.append(try std.fmt.parseInt(u32, str, 10));
}
```
If the item that trips the `try` is late in the list (say around index 550), the reported error trace contains a bunch of misleading garbage that seems to indicate (incorrectly) that the system is out of memory.  Here's a report from a similar situation:
```
error: InvalidCharacter
C:\Program Files\Zig\Current\lib\zig\std\heap\general_purpose_allocator.zig:573:13: 0x7ff61750c229 in std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant))::std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant)).resize (day07.obj)
            return error.OutOfMemory;
            ^
C:\Program Files\Zig\Current\lib\zig\std\heap\general_purpose_allocator.zig:573:13: 0x7ff61750c229 in std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant))::std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant)).resize (day07.obj)
            return error.OutOfMemory;
            ^
C:\Program Files\Zig\Current\lib\zig\std\heap\general_purpose_allocator.zig:573:13: 0x7ff61750c229 in std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant))::std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant)).resize (day07.obj)
            return error.OutOfMemory;
            ^
C:\Program Files\Zig\Current\lib\zig\std\heap.zig:367:13: 0x7ff6174f1607 in std.heap.PageAllocator::std.heap.PageAllocator.resize (day07.obj)
            return error.OutOfMemory;
            ^
C:\Program Files\Zig\Current\lib\zig\std\heap\general_purpose_allocator.zig:450:32: 0x7ff61750da0f in std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant))::std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant)).resizeLarge (day07.obj)
            const result_len = try self.backing_allocator.resizeFn(self.backing_allocator, old_mem, old_align, new_size, len_align, ret_addr);
                               ^
C:\Program Files\Zig\Current\lib\zig\std\heap\general_purpose_allocator.zig:495:17: 0x7ff61750bc20 in std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant))::std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant)).resize (day07.obj)
                return self.resizeLarge(old_mem, old_align, new_size, len_align, ret_addr);
                ^
C:\Program Files\Zig\Current\lib\zig\std\heap.zig:367:13: 0x7ff6174f1607 in std.heap.PageAllocator::std.heap.PageAllocator.resize (day07.obj)
            return error.OutOfMemory;
            ^
C:\Program Files\Zig\Current\lib\zig\std\heap\general_purpose_allocator.zig:450:32: 0x7ff61750da0f in std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant))::std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant)).resizeLarge (day07.obj)
            const result_len = try self.backing_allocator.resizeFn(self.backing_allocator, old_mem, old_align, new_size, len_align, ret_addr);
                               ^
C:\Program Files\Zig\Current\lib\zig\std\heap\general_purpose_allocator.zig:495:17: 0x7ff61750bc20 in std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant))::std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant)).resize (day07.obj)
                return self.resizeLarge(old_mem, old_align, new_size, len_align, ret_addr);
                ^
C:\Program Files\Zig\Current\lib\zig\std\heap.zig:367:13: 0x7ff6174f1607 in std.heap.PageAllocator::std.heap.PageAllocator.resize (day07.obj)
            return error.OutOfMemory;
            ^
C:\Program Files\Zig\Current\lib\zig\std\heap\general_purpose_allocator.zig:450:32: 0x7ff61750da0f in std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant))::std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant)).resizeLarge (day07.obj)
            const result_len = try self.backing_allocator.resizeFn(self.backing_allocator, old_mem, old_align, new_size, len_align, ret_addr);
                               ^
C:\Program Files\Zig\Current\lib\zig\std\heap\general_purpose_allocator.zig:495:17: 0x7ff61750bc20 in std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant))::std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std.heap.general_purpose_allocator.Config constant)).resize (day07.obj)
                return self.resizeLarge(old_mem, old_align, new_size, len_align, ret_addr);
                ^
C:\Program Files\Zig\Current\lib\zig\std\fmt.zig:1306:25: 0x7ff61751c6c9 in std.fmt.charToDigit (day07.obj)
    if (value >= radix) return error.InvalidCharacter;
                        ^
C:\Program Files\Zig\Current\lib\zig\std\fmt.zig:1235:23: 0x7ff61750f690 in std.fmt.parseWithSign (day07.obj)
        const digit = try charToDigit(c, buf_radix);
                      ^
C:\Program Files\Zig\Current\lib\zig\std\fmt.zig:1150:5: 0x7ff61750c7ca in std.fmt.parseInt (day07.obj)
    return parseWithSign(T, buf, radix, .Pos);
    ^
C:\Users\Martin\Projects\AoC-2020\src\day07.zig:56:27: 0x7ff6174f3736 in main (day07.obj)
            const count = try std.fmt.parseInt(usize, part[0..split], 10);
                          ^
```

**Comment by daurnimator** [comment] 2020-12-07 07:55
duplicate of https://github.com/ziglang/zig/issues/1923

**Closed by daurnimator** 2020-12-07 07:55 UTC
