### ISSUE TITLE
Assigning anon struct to union variable causes trace/breakpoint trap

### ISSUE THREAD

**Issue by chung-leong** [ziglang/zig#19890] opened 2024-05-07 18:28 UTC
### Zig Version

0.13.0-dev.73+db890dbae

### Steps to Reproduce and Observed Behavior

Run test on the following code:
```zig
const BareUnion = union {
    dog: i32,
    cat: i32,
};
var bare_union: BareUnion = .{ .dog = 123 };

fn useDog() void {
    bare_union = .{ .dog = 777 };
}

test "useDog" {
    useDog();
}
```
Compilation bails out with the following message:
```
Trace/breakpoint trap (core dumped)
```
No error when the following variants are used instead:
```zig
fn useDog() void {
    bare_union = BareUnion{ .dog = 777 };
}

fn useDog() void {
    const c = .{ .dog = 777 };
    bare_union = c;
}
```

### Expected Behavior

No error

**Comment by xdBronch** [comment] 2024-05-07 20:05
looks like duplicate of #19832

**Comment by chung-leong** [comment] 2024-05-07 20:35
I believe so.

**Closed** 2024-05-08 09:26 UTC
Labels: bug
