### ISSUE TITLE
Reassigning struct using fields from existing assignment produces unexpected behavior

### ISSUE THREAD

**Issue by dsemi** [ziglang/zig#11331] opened 2022-03-27 21:32 UTC
### Zig Version

0.9.1

### Steps to Reproduce

Unclear if this is documented anywhere (I couldn't find anything), but at best this feels like very confusing behavior.

```
const std = @import("std");

const Coord = struct {
    x: i32,
    y: i32,
};

pub fn main() void {
    var dir = Coord{ .x = 0, .y = 1 };
    std.debug.print("{any}\n", .{dir});
    dir = Coord{ .x = -dir.y, .y = dir.x };
    std.debug.print("{any}\n", .{dir});
}
```

### Expected Behavior

Expected output:
```
Coord{ .x = 0, .y = 1 }
Coord{ .x = -1, .y = 0 }
```

### Actual Behavior

Actual output
```
Coord{ .x = 0, .y = 1 }
Coord{ .x = -1, .y = -1 }
```

It's as if `dir.x` and `dir.y` are being passed by reference to the struct assignment and the assignment is not atomic.

**Comment by schmee** [comment] 2022-03-27 21:59
Related: https://github.com/ziglang/zig/issues/4021, https://github.com/ziglang/zig/issues/3696

**Comment by daurnimator** [comment] 2022-03-28 03:35
Closing as duplicate of above mentioned issues.

**Closed by daurnimator** 2022-03-28 03:35 UTC
Labels: bug
