### ISSUE TITLE
"brew install zig --HEAD" fails on osx ventura 13.4

### ISSUE THREAD

**Issue by weihsiu** [ziglang/zig#15979] opened 2023-06-08 06:49 UTC
### Zig Version

0.11.0-dev.3384+00ff65357

### Steps to Reproduce and Observed Behavior

on mac osx ventura 13.4:
% brew install zig --HEAD
...
error: the following build command failed with exit code 1:
/private/tmp/zig-20230608-72250-1d1v2mh/zig-cache/o/e57701418410ab865bda4f9c3dfc035b/build /private/tmp/zig-20230608-72250-1d1v2mh/build/zig2 /private/tmp/zig-20230608-72250-1d1v2mh /private/tmp/zig-20230608-72250-1d1v2mh/zig-cache /private/tmp/zig-20230608-72250-1d1v2mh/.brew_home/.cache/zig --prefix /tmp/zig-20230608-72250-1d1v2mh/build/stage3 --zig-lib-dir /tmp/zig-20230608-72250-1d1v2mh/lib -Dconfig_h=/tmp/zig-20230608-72250-1d1v2mh/build/config.h -Denable-llvm -Doptimize=ReleaseFast -Dstrip -Dtarget=native -Dcpu=native -Dversion-string=0.11.0-dev.3384+00ff65357
make[2]: *** [stage3/bin/zig] Error 1
make[2]: *** Deleting file `stage3/bin/zig'
make[1]: *** [CMakeFiles/stage3.dir/all] Error 2
make: *** [all] Error 2

### Expected Behavior

zig installs properly

**Comment by weihsiu** [comment] 2023-06-08 06:54
btw, this is a different error than the one reported in https://github.com/ziglang/zig/issues/15956.  i got further along than #15956

**Comment by marcelroed** [comment] 2023-06-14 10:58
Having the same issue

**Comment by marcelroed** [comment] 2023-06-14 11:23
Additionally, my PATH looks like this:

```
> echo $PATH
/opt/homebrew/Caskroom/miniforge/base/envs/3.11/bin /opt/homebrew/Caskroom/miniforge/base/condabin /opt/homebrew/opt/llvm/bin /Users/marcel/.config/emacs/bin /Users/marcel/.cargo/bin /opt/homebrew/sbin /opt/homebrew/bin /Users/marcel/.fzf/bin /Users/marcel/.local/bin /usr/local/bin /System/Cryptexes/App/usr/bin /usr/bin /bin /usr/sbin /sbin /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin /Library/Apple/usr/bin /Library/TeX/texbin
```

so I'm not sure where Homebrew is setting the path from for install.

**Comment by marcelroed** [comment] 2023-06-14 12:09
I figured out a temporary fix. You can force the Homebrew shim to use the local LLVM install rather than AppleClang by setting the environment variable `HOMEBREW_CC` like this:

```
> HOMEBREW_CC=llvm_clang brew install zig --HEAD
```

**Comment by andrewrk** [comment] 2023-06-20 20:05
Duplicate of #16102

**Closed by andrewrk** 2023-06-20 20:05 UTC
