### ISSUE TITLE
complex math yields wrong result when overwriting as in b = b.mul(a)

### ISSUE THREAD

**Issue by BlueAlmost** [ziglang/zig#12254] opened 2022-07-27 11:10 UTC
### Zig Version

0.10.0-dev.3023+9c66fdadc

### Steps to Reproduce

const std = @import("std");
const Complex = std.math.complex.Complex;
const print = std.debug.print;

pub fn main() void {

    const CF: type = Complex(f64);

    var a = CF.init(1, 2);
    var b = CF.init(3, 4);
    var c = CF.init(0, 0);

    c = b.mul(a);
    b = b.mul(a);

    print("c: {d}\n", .{c});  // correct result here
    print("b: {d}\n", .{b});  // incorrect result here
}

### Expected Behavior

With a = 1+2i and b = 3+4i,

b = b*a produces incorrect result of -5-6i,

the correct result is -5+10i

### Actual Behavior

correct result is -5+10i.

This error occurs only when overwriting one of the inputs (used as an input also, ie. b=b.mul(a) ).  Related to other struct overwrite errors that have been discussed recently.

Yeah, this is in stdlib ... but relates a bit to core issues being discussed.

**Comment by Vexu** [comment] 2022-07-27 11:13
Duplicate of #3696

**Closed by Vexu** 2022-07-27 11:13 UTC
Labels: bug
