### ISSUE TITLE
Using switch on comptime value to define enum attempts to access fields from other branches

### ISSUE THREAD

**Issue by frmdstryr** [ziglang/zig#6420] opened 2020-09-25 18:48 UTC
I'm trying to define enum that has a different set of values based on which chip it is being compiled for but hit an error: 

```zig
const std = @import("std");

// Select chip
const ChipID = enum{
    g4,
    h7
};
const chip: ChipID = .g4;

// Fields Specific to G4 chip
const G4F = struct {
    const FA = 1;
    const FB = 2;
};

// Fields Specific to H7 chip
const H7F = struct {
    const FC = 1;
    const FB = 2;
};


const fields = switch (chip) {
    .g4 => G4F,
    .h7 => H7F,
};


pub const Mapping = switch (chip) {
        .g4 => enum(u32) {
            D1 = fields.FA,
            D2 = fields.FB,
        },
        .h7 => enum(u32) {
            D1 = fields.FC, // Why does it access this when chip == .g4 ???
            D2 = fields.FD,  
        },
    };

pub export fn main() void {
    var val: Mapping = .D1;
    std.debug.warn("{}\n", .{val});
}

```
The above code https://godbolt.org/z/exGeMv fails to compile because it attempts to access the h7 specific field despite the switch only matching the g4 branch.

```zig
<source>:35:24: error: container 'G4F' has no member called 'FC'
            D1 = fields.FC, // Why does it access this when chip == .g4 ???
                       ^
<source>:36:24: error: container 'G4F' has no member called 'FD'
            D2 = fields.FD,  
```

The error is correct in that G4F doesn't have that field but that switch branch should not be used in the first place so I think this may be a bug.

This is a simplified example, in the actual code attempting to use this the "fields" is header defines translated from c for different chips so repeating the full path explicitly is not desired (as some chips re-use the same fields).

**Comment by Vexu** [comment] 2020-09-26 06:56
Duplicate of #3778.

**Closed by Vexu** 2020-09-26 06:56 UTC
