### ISSUE TITLE
broken LLVM module when enabling io_mode evented

### ISSUE THREAD

**Issue by vrischmann** [ziglang/zig#5525] opened 2020-06-03 23:18 UTC
Hi,

the following code:
```zig
const std = @import("std");

pub const io_mode = .evented;

pub fn main() anyerror!void {
    std.debug.warn("All your codebase are belong to us.\n", .{});
}
```

fails to build on 6524a64bda71a2eed9a3160562fd6da7232f9720:
```
Code Generation [357/630] std.event.loop.Loop.initThreadPool...broken LLVM module found: Instruction does not dominate all uses!
  %149 = load { %std.fs.file.File, i16 }*, { %std.fs.file.File, i16 }** %29, align 8, !dbg !6161
  %148 = phi { %std.fs.file.File, i16 }* [ %272, %OkResume ], [ %149, %OkResume27 ], !dbg !6161

This is a bug in the Zig compiler.
/home/vincent/dev/devtools/zig/src-self-hosted/stage2.zig:36:5: 0xa8e35c in stage2_panic (zigstage2)
    @panic(ptr[0..len]);
    ^
../src/util.cpp:20:17: 0xa4db2a in zig_panic (../src/util.cpp)
../src/codegen.cpp:8254:18: 0x9900bb in do_code_gen (../src/codegen.cpp)
../src/codegen.cpp:11001:24: 0x99ace6 in codegen_build_and_link (../src/codegen.cpp)
../src/main.cpp:1671:39: 0x96ce4c in main0 (../src/main.cpp)
../src/main.cpp:1858:24: 0x96d965 in main (../src/main.cpp)
```

You can reproduce it on [godbolt](https://gcc.godbolt.org/z/CMX5fq) too.

**Comment by Vexu** [comment] 2020-06-04 10:22
This should now build correctly with fd067fb , rest of the issue should be a duplicate of #4188.

**Closed by Vexu** 2020-06-04 10:22 UTC
Labels: bug, stage1
