### ISSUE TITLE
Missing builtin result type inference due to generic function

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#16283] opened 2023-07-01 12:36 UTC
### Zig Version

0.11.0-dev.3892+0a6cd257b

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    var value: u32 = std.math.maxInt(u32);
    generic(8, @truncate(value)); // error: @truncate must have a known result type
    nonGeneric(@truncate(value)); // works fine
}

fn generic(
    comptime number_of_bits: comptime_int,
    value: std.meta.Int(.unsigned, number_of_bits),
) void {
    std.debug.print("{}\n", .{value});
}

fn nonGeneric(value: std.meta.Int(.unsigned, 8)) void {
    std.debug.print("{}\n", .{value});
}
```

Error:
```
src/main.zig:5:16: error: @truncate must have a known result type
    generic(8, @truncate(value)); // error: @truncate must have a known result type
               ^~~~~~~~~~~~~~~~
src/main.zig:5:16: note: result type is unknown due to anytype parameter
src/main.zig:5:16: note: use @as to provide explicit result type
```

Removing the builtin from the generic call (`generic(8, value);`) shows an error message regarding the correct type `u32`:
```
src/main.zig:5:16: error: expected type 'u8', found 'u32'
    generic(8, value);
               ^~~~~
src/main.zig:5:16: note: unsigned 8-bit int cannot represent all possible unsigned 32-bit values
```

### Expected Behavior

Zig knows the type of the parameter for this instantiation of the generic function, so it should be able to determine the builtins result type.

**Comment by Vexu** [comment] 2023-07-01 12:44
Duplicate of #16258

**Closed by Vexu** 2023-07-01 12:44 UTC
Labels: bug
