### ISSUE TITLE
making var comptime yields SIGBUS (Misaligned address error) during runtime

### ISSUE THREAD

**Issue by benmkw** [ziglang/zig#3996] opened 2019-12-29 09:52 UTC
I am attempting to create a trie during compile time and use it for string matching (similar to the perfekt hashing approach from [Andrews blog post](https://andrewkelley.me/post/string-matching-comptime-perfect-hashing-zig.html)) but ran into this problem.

[source](https://gist.github.com/benmkw/4c3d04ec87dd7668e4af972d5ae6971b)

on [line 158](https://gist.github.com/benmkw/4c3d04ec87dd7668e4af972d5ae6971b#file-main-zig-L158) changing the var to be comptime results in runtime crash, while omitting the comptime works fine (whole program just executed at runtime). `comptime var nodes = [_]TrieNode{TrieNode{}} ** size;`

The crash happens [on line 54](https://gist.github.com/benmkw/4c3d04ec87dd7668e4af972d5ae6971b#file-main-zig-L54) `child.*.?.value = .{ .char = character };`

I need `nodes` to be comptime in order to make `const trie = create_trie_from(&input, &trie_node_pool);` comptime and the idea is that LLVM can do something useful with that information.

zig version 0.5.0+bda355d97 (current master)

**Comment by benmkw** [comment] 2020-01-14 16:07
I played a bit with creduce and created this minimal example (some manual editing was done but creduce did some really cool things as well)

```zig
const b = struct {
    c: [1]?*b = [_]?*b{null},
};

pub fn main() void {
    comptime var e = [_]b{b{}};
    var j = &e[0];
    j.c[0] = &e[0];
}
```

`'zig run 5reduce.zig' terminated by signal SIGBUS (Misaligned address error)`

I also tried the [ir-clean-up-vars](https://github.com/ziglang/zig/pull/4152) branch at 01c2eba64 where this issue remains

**Comment by andrewrk** [comment] 2020-01-14 18:05
That's good to know that creduce can create zig test cases! Do you think you would be willing to write a tutorial on how to use creduce with zig?

**Comment by benmkw** [comment] 2020-01-14 18:33
I don't have a website or such, feel free to use/ distriubute as you want, I basically just did the following after looking at [this](https://nickdesaulniers.github.io/blog/2019/01/18/finding-compiler-bugs-with-c-reduce/), (the official website would somehow not load for me):
```bash
creduce ./reduce.rb main.zig # yeah really, don't like bash, could use anything here, e.g. zig
```

where reduce.rb is
```ruby
#! /usr/bin/env ruby

ret = `zig run main.zig 2>&1`

# or 
# ret = `zig fmt main.zig && zig run main.zig 2>&1`


status =  $?.exitstatus

if status == 138 # SIGBUS
    exit 0 # zero means, continue reducing 
else
    exit 1 # means, this is a branch which lost the bug we wanted to find
end

```

It's really fun to watch main.zig in your editor while creduce works on it.

I had some issues where creduce would reduce to an empty file after just a few seconds but my return value checks were wrong in these cases, writing the right reduce.rb script was actually a bit tricky although it seems easy now.

the`-not-c` see [here](https://github.com/csmith-project/creduce/issues/153#issuecomment-361826345)

I think if creduce would understand functions and could inline them that would help a lot (I presume the c version would be able to do this), or if zig could preprocess code and inline functions (not recursive ones) that may also be an (easier) option. The reason for this is that it seems as if it can't really delete function arguments at the moment so these are a barrier which stops propagation of deletions.

**Comment by andrewrk** [comment] 2020-01-14 19:55
Thank you so much! This is really useful. I'll compile this information and put it into either the wiki or CONTRIBUTING.md.

**Comment by benmkw** [comment] 2020-01-14 20:05
Your welcome!

Maybe you could add to it by converting the ruby script to zig and adding the option/ an example to search stdout/ stderr such that its really easy to combine textual things and return value. I find myself spending a bit of time figuring these things out every time they reoccur.

**Comment by Vexu** [comment] 2022-12-28 13:56
Duplicate of #1487

**Closed by Vexu** 2022-12-28 13:56 UTC
Labels: bug, stage1
