### ISSUE TITLE
Segmentation fault when compiling

### ISSUE THREAD

**Issue by dvmason** [ziglang/zig#13638] opened 2022-11-23 18:08 UTC
### Zig Version

0.11.0-dev.251+7c527c6df

### Steps to Reproduce and Observed Behavior

$ git clone https://github.com/dvmason/Zag-Smalltalk
$ cd Zag-Smalltalk
$ git checkout 7137cce39fea9c927ec67f8f8d977a19190239a
$ cd zig
$ zig test fibonacci.zig
Segmentation fault: 11

(same result with 0.10.0)
(on 0.9.1: thread 3337159 panic: Darwin is handled separately via std.zig.system.darwin module
Unable to dump stack trace: debug info stripped
Abort trap: 6)

### Expected Behavior

This is work in progress, so there may be errors that should be flagged.

It would be incredibly helpful if there was a (possibly very verbose) flag that printed what the compiler was attempting to resolve, so I could at least get some idea of what was causing the crash!

Previously I was triggering a bug with similar symptoms, that was because I wasn't initializing one of the fields of a struct, so I went through the code and checked everywhere I return a structure to make sure it was all being initialized. That produced checkout aacafc010e1d916d70d6ce40941cfd2d19f088d7 and it compiled!!! and the tests ran!! and when I undid the change at line 412 of heap.zig, it failed..... but when I **redid** that change, it still failed!!!! I'm mystified!!!

Thanks for Zig.... I love it. I just wish I could debug better while you stabilize the compiler.

**Comment by Vexu** [comment] 2022-11-23 18:28
Duplicate of #12765, if you have a debug build of the compiler you can get the error message with `--debug-compile-errors`:
```
$ zig3 test fibonacci.zig --debug-compile-errors
compile error during Sema: unable to evaluate comptime expression, src: mem.zig:Module.LazySrcLoc{ .node_offset = Module.TracedOffset{ .x = 22, .trace = 

 } }
thread 3220 panic: unexpected compile error occurred
Analyzing zig/lib/std/mem.zig: mem.zig:copy
      %1178 = dbg_block_begin()
      %1179 = elem_val(%1150, %1170) 
      %1180 = dbg_var_val(%1179, "s")
      %1181 = dbg_var_val(%1167, "i")
      %1182 = dbg_stmt(8, 9)
      %1183 = ref(%1147) 
      %1184 = load(%1167) 
      %1185 = as_node(@Zir.Inst.Ref.usize_type, %1184) 
      %1186 = dbg_stmt(8, 13)
      %1187 = elem_ptr_node(%1183, %1185) 
      %1189 = dbg_block_end()
    > %1188 = store_node(%1187, %1179) 
      %1190 = break(%1173, @Zir.Inst.Ref.void_value)
    For full context, use the command
      zig ast-check -t zig/lib/std/mem.zig

... lots of irrelevant output

  in zig/lib/std/fmt.zig: fmt.zig:bufPrint
    > %14444 = block({%14445..%14485}) 
  in zag/utilities.zig: zag/utilities.zig:checkEqual
    > %80 = call(.auto, %78, [
        {%82..%86},
        {%87, %88},
        {%89, %90},
      ]) 
  in zag/utilities.zig: zag/utilities.zig:checkEqual
    > %93 = block({%73..%92}) 
  in zag/utilities.zig: zag/utilities.zig:checkEqual
    > %44 = block({%45..%103}) 
  in zag/arenas.zig: zag/arenas.zig:NurseryArena.comptime_0
    > %285 = call(.compile_time, %283, [
        {%286..%288},
        {%289..%293},
      ]) node_offset:49:13 to :49:75
  in zag/arenas.zig: zag/arenas.zig:NurseryArena.comptime_0
```

Crash goes away with this diff:
```diff
diff --git a/zig/zag/arenas.zig b/zig/zag/arenas.zig
index f4d1f46..5259ed2 100644
--- a/zig/zag/arenas.zig
+++ b/zig/zag/arenas.zig
@@ -46,8 +46,8 @@ pub const NurseryArena = extern struct {
     heapArea: [nursery_size-field_size/@sizeOf(Header)]Header,
     const field_size = @sizeOf(HeaderArray)+@sizeOf([*]Object);
     comptime {
-        if (checkEqual(@sizeOf(NurseryArena),nursery_size*@sizeOf(Header))) |s|
-            @compileError("Modify NurseryArena.heap to make @sizeOf(NurseryArena) == " ++ s);
+        // if (checkEqual(@sizeOf(NurseryArena),nursery_size*@sizeOf(Header))) |s|
+        //     @compileError("Modify NurseryArena.heap to make @sizeOf(NurseryArena) == " ++ s);
     }
     pub fn new() NurseryArena {
         return NurseryArena {
```

**Closed by Vexu** 2022-11-23 18:28 UTC
Labels: bug
