### ISSUE TITLE
big int mul assertion hit for large ints

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#6636] opened 2020-10-10 03:46 UTC
In discord #zig-help user Gerbil posted a big int factorial function which fails with the following for factorial(36) but not for factorial(35).  Not sure what zig version he was using, but using most recent pull (0.6.0+a31b70c4b) which includes #6633 i get the same: 

```sh
.../zig/std/math/big/int.zig:1733:15: 0x234175 in std.math.big.int.Managed.mul (tmp)
        assert(alias_count == 0 or rma.limbs.len >= a.limbs.len + b.limbs.len + 1);
```

here is a simpler reproduction

```zig
const std = @import("std");
test "mul" {
    var a = try math.big.int.Managed.initSet(std.testing.allocator, 10333147966386144929666651337523200000000);
    var b = try math.big.int.Managed.initSet(std.testing.allocator, 36);
    defer a.deinit();
    defer b.deinit();
    try a.mul(a.toConst(), b.toConst());
    std.debug.print("{}\n", .{a});

}
```
i notice this can be avoided if assert is moved one line down.  no idea if this is a good idea. 
```zig
// zig/std/math/big/int.zig:1733
try rma.ensureMulCapacity(a, b);
assert(alias_count == 0 or rma.limbs.len >= a.limbs.len + b.limbs.len + 1);
```

**Comment by LemonBoy** [comment] 2020-10-10 06:17
Since the result and the first operand are the same bigint you have to call `ensureMulCapacity` on `a` to make sure it has enough space. This is a wart in the API that I've fixed in a different way in `pow` and `sqr`: whenever the parameters are found to alias the result a fresh bigint is allocated and the old one is destroyed when it's not needed anymore.

**Comment by andrewrk** [comment] 2020-10-13 03:43
Is this https://github.com/ziglang/zig/issues/6167#issuecomment-680456728 ?

**Comment by Snektron** [comment] 2021-10-02 10:38
Seems like this can be resolved by performing the assert on `len()` instead of the buffer length. In general, some confusion is added by the different methods to fetch the length of an integer in terms of digits versus buffer size. I think at some point it would be best to adapt the same scheme as std.Arraylist, where `limbs` holds the normalized limbs and a separate value `capacity` holding the total size of the backing memory.

**Comment by andrewrk** [comment] 2021-10-02 22:36
Sounds great @Snektron.

**Comment by tau-dev** [comment] 2024-07-15 15:33
That assert is gone, can no longer reproduce

**Closed** 2024-07-15 16:04 UTC
Labels: bug, standard library
