### ISSUE TITLE
Compiler segfaults when breaking out of a labeled while loop sandwiched between inline while loops

### ISSUE THREAD

**Issue by Validark** [ziglang/zig#13427] opened 2022-11-03 12:47 UTC
### Zig Version

0.11.0-dev.38+b40fc7018

### Steps to Reproduce and Observed Behavior

In an empty folder, run:
```
zig init-exe
```

Paste this into `main.zig`:
```zig
pub fn main() !void {
    var n: u32 = 0;
    comptime var b = false;

    inline while (true) : (b = true) {
        MID_LOOP: while (true) {
            comptime var a: u2 = 2;
            inline while (true) {
                if (!b and n == 0) break :MID_LOOP;
                a -= 1;
                if (a == 0) break;
                if (n == 0) break;
            }
        }
        if (b) break;
    }
}
```
Upon trying to run `zig build`, the compiler will segfault.

### Expected Behavior

no segfault, and probably an error like "unable to resolve comptime value" and "note: condition in comptime branch must be comptime-known"

For reference for anyone else who runs into this, the workaround I used in my real code is to wrap the innermost inline while loop in a block and use a labeled break.

**Comment by Vexu** [comment] 2022-11-03 12:48
Duplicate of  #13175

**Closed by Vexu** 2022-11-03 12:49 UTC
Labels: bug
