### ISSUE TITLE
All of `std` should be fully auto-completable by tools like zls

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#14209] opened 2023-01-05 11:21 UTC
### Zig Version

0.11.0-dev.1095+8bd734d60

### Steps to Reproduce and Observed Behavior

1. Type `std.os.sockaddr`
2. No completions appear. Data types don't either. Go-to definition doesn't help

Video:

https://user-images.githubusercontent.com/709451/210762562-1d4befe6-ea46-4547-88bb-d8e9bf577d50.mp4

### Expected Behavior

All of `std` should be fully auto-completable from the text editor.

When you use Rust, completions work relatively consistently. In-editor feedback reports when the wrong number of arguments are passed to a function. It doesn't take more than a second or two to update the red squiggly lines. This improves developer productivity.

Video:

https://user-images.githubusercontent.com/709451/210764636-91f4c140-822b-4229-9d67-32f5fa6fb385.mp4

When you use Go, completions work too.

https://user-images.githubusercontent.com/709451/210766932-f4d3432e-890c-4c89-a3bf-80350c04b454.mp4

**Comment by ifreund** [comment] 2023-01-05 13:11
Closing as a duplicate of #615. Specific things that zls does not complete are zls bugs/limitations, likely due to zls not (yet?) implementing a complete comptime evaluation engine.

The only thing we can do on the Zig compiler side is to expose the analysis done by the compiler over some API to make things easier for zls and other completion engines.

**Closed by ifreund** 2023-01-05 13:11 UTC
Labels: bug
