### ISSUE TITLE
BoundedArray.fromSlice() returns error `type 'u8' does not support indexing` due to @memcpy

### ISSUE THREAD

**Issue by Deins** [ziglang/zig#15694] opened 2023-05-13 19:26 UTC
### Zig Version

0.11.0-dev.3107+6547d2331

### Steps to Reproduce and Observed Behavior

```zig
// when global variable or struct member, worked as local variable, but might be that it got optimized maybe out
var string : std.BoundedArray(u8, 32) = std.BoundedArray(u8, 32).fromSlice("hello world") catch unreachable;
```
[snippet in godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:zig,selection:(endColumn:52,endLineNumber:4,positionColumn:52,positionLineNumber:4,selectionStartColumn:52,selectionStartLineNumber:4,startColumn:52,startLineNumber:4),source:'const+std+%3D+@import(%22std%22)%3B%0A%0Aconst+message+:+%5B%5Dconst+u8+%3D+%22hello+world%22%3B%0Avar+string+:+std.BoundedArray(u8,+32)+%3D+std.BoundedArray(u8,+32).fromSlice(message)+catch+unreachable%3B%0A%0Apub+fn+main()+!!void+%7B%0A++++string.pop()%3B%0A++++std.debug.print(%22%7Bs%7D%22,+.%7Bstring.slice()%7D)%3B%0A%7D%0A'),l:'5',n:'0',o:'Zig+source+%231',t:'0')),k:50,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:ztrunk,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:zig,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+zig+trunk+(Editor+%231)',t:'0')),header:(),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'zig+trunk',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+zig+trunk+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)
returns error:
```bash
bounded_array.zig:76:13: error: type 'u8' does not support indexing
            @memcpy(list.slice(), m);
            ^~~~~~~~~~~~~~~~~~~~~~~~
W:\dev\zig\tools\zig-master\lib\std\bounded_array.zig:76:13: note: operand must be an array, slice, tuple, or vector
src\server\main.zig:8:72: note: called from here
    map : std.BoundedArray(u8, 32) = std.BoundedArray(u8, 32).fromSlice("default 9x12") catch unreachable,
                                     ~~~~~~~~~~~~~~~~~~~
```
I think it worked few versions back, so  possibly regression.

### Expected Behavior

Just works

**Comment by jacobly0** [comment] 2023-05-14 05:17
Duplicate of #15633

**Closed** 2023-05-14 09:17 UTC
Labels: bug
