### ISSUE TITLE
Result of sizeOf passed as anon struct reaches unreachable code 

### ISSUE THREAD

**Issue by martinhath** [ziglang/zig#12564] opened 2022-08-21 20:15 UTC
### Zig Version

0.10.0-dev.3664+02070ae26

### Steps to Reproduce

```zig
const Empty = struct {};

fn foo(n: anytype) void {
    _ = n;
}

test {
    const size = @sizeOf(Empty);
    foo(.{size});
}
```

### Expected Behavior

File should run when `zig test` is executed.

### Actual Behavior

<details>
<summary>Here's all the output:</summary>

```
$ s2/bin/zig test bugs/12525.zig
panic: reached unreachable code
Analyzing bugs/12525.zig: 12525.zig:test_0
      %14 = dbg_block_begin())
      %15 = dbg_stmt(2, 5)
      %16 = decl_val("Empty") token_offset:8:26 to :8:31
      %17 = size_of(%16) node_offset:8:18 to :8:32
      %18 = dbg_var_val(%17, "size")
      %19 = dbg_stmt(3, 5)
      %20 = decl_val("foo") token_offset:9:5 to :9:8
      %21 = dbg_stmt(3, 8)
      %25 = dbg_block_end())
    > %22 = call(nodiscard .auto, %20, [
        {
          %23 = array_init_anon(%17{}) node_offset:9:9 to :9:16
          %24 = break_inline(%22, %23)
        },
      ]) node_offset:9:5 to :9:17
      %26 = ret_tok(@Zir.Inst.Ref.void_value) token_offset:10:1 to :10:2
    For full context, use the command
      zig ast-check -t bugs/12525.zig


/home/mht/src/zig/lib/std/debug.zig:281:14: 0x829f43 in assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
/home/mht/src/zig/src/type.zig:5525:49: 0xdfe334 in structFieldCount (zig)
                assert(struct_obj.haveFieldTypes());
                                                ^
/home/mht/src/zig/src/type.zig:3241:60: 0xc2e8b2 in abiSizeAdvanced (zig)
                    const field_count = ty.structFieldCount();
                                                           ^
/home/mht/src/zig/src/type.zig:3162:32: 0x94d158 in abiSize (zig)
        return (abiSizeAdvanced(ty, target, .eager) catch unreachable).scalar;
                               ^
/home/mht/src/zig/src/value.zig:1101:37: 0xf5f698 in toBigIntAdvanced (zig)
                const x = ty.abiSize(target);
                                    ^
/home/mht/src/zig/src/value.zig:1058:36: 0xd915b7 in toBigInt (zig)
        return val.toBigIntAdvanced(space, target, null) catch unreachable;
                                   ^
/home/mht/src/zig/src/value.zig:2492:37: 0x106dcd0 in hashInt (zig)
        const big = int_val.toBigInt(&buffer, target);
                                    ^
/home/mht/src/zig/src/value.zig:2548:30: 0x106e0fc in hashPtr (zig)
            => return hashInt(ptr_val, hasher, target),
                             ^
/home/mht/src/zig/src/value.zig:2323:66: 0xeb689f in hash (zig)
                else => return hashPtr(val, hasher, mod.getTarget()),
                                                                 ^
/home/mht/src/zig/src/type.zig:1165:35: 0xebf41b in hashWithHasher (zig)
                    field_val.hash(field_ty, hasher, mod);
                                  ^
/home/mht/src/zig/src/Sema.zig:6398:38: 0x1557c1f in instantiateGenericCall (zig)
                arg_ty.hashWithHasher(&hasher, mod);
                                     ^
/home/mht/src/zig/src/Sema.zig:5782:40: 0x135a803 in analyzeCall (zig)
        if (sema.instantiateGenericCall(
                                       ^
/home/mht/src/zig/src/Sema.zig:5573:28: 0x10b6969 in zirCall (zig)
    return sema.analyzeCall(block, func, func_src, call_src, modifier, ensure_result_used, resolved_args, bound_arg_src);
                           ^
/home/mht/src/zig/src/Sema.zig:719:62: 0xef624b in analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst),
                                                             ^
/home/mht/src/zig/src/Sema.zig:604:30: 0xef4898 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/mht/src/zig/src/Module.zig:5529:21: 0xd54e4c in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/mht/src/zig/src/Module.zig:4240:40: 0xb66e14 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/mht/src/zig/src/Compilation.zig:2974:42: 0xb65372 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/mht/src/zig/src/Compilation.zig:2912:30: 0xa6336a in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/mht/src/zig/src/Compilation.zig:2253:31: 0xa5ff9a in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/mht/src/zig/src/main.zig:3334:20: 0xa895a6 in updateModule (zig)
    try comp.update();
                   ^
/home/mht/src/zig/src/main.zig:3008:17: 0x84c678 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/mht/src/zig/src/main.zig:236:31: 0x8279fb in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/mht/src/zig/src/main.zig:174:20: 0x826e40 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/mht/src/zig/lib/std/start.zig:574:37: 0x829379 in main (zig)
        },
                                    ^
fish: Job 1, 's2/bin/zig test bugs/12525.zig' terminated by signal SIGABRT (Abort)
```
</details>

**Comment by Vexu** [comment] 2022-08-28 10:44
Duplicate of #12488

**Closed by Vexu** 2022-08-28 10:44 UTC
Labels: bug, stage2
