### ISSUE TITLE
Compiler Bug - When use ArrayListe.toOwnedSliceSentinel(null)

### ISSUE THREAD

**Issue by Izimic** [ziglang/zig#11076] opened 2022-03-07 11:04 UTC
### Zig Version

0.10.0-dev.1107+7deadf430

### Steps to Reproduce

Hi, when I use toOwnedSliceSentinel, I got a error at the compile-time.
```zig
const std = @import("std");
const ArrayList = std.ArrayList;

pub fn main() !void {
  var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
  var list = ArrayList(?[:0]const u8).init(arena.allocator());

  try list.append("bidule");
  try list.append("truc");

  var slice = try list.toOwnedSliceSentinel(null);
  std.debug.print("{s}\n",.{slice});
}
```

### Expected Behavior

output: `{bidule, truc, null}`

### Actual Behavior

```
broken LLVM module found: Invalid operand types for ICmp instruction
  %28 = icmp eq %"?[:0]const u8" %27, { %"[]u8" undef, i1 false }, !dbg !19168

This is a bug in the Zig compiler.thread 4510 panic:
Unable to dump stack trace: debug info stripped
```

**Comment by Vexu** [comment] 2022-03-07 11:15
Duplicate of #10898

**Closed by Vexu** 2022-03-07 11:15 UTC
Labels: bug
