### ISSUE TITLE
comptime @ptrToInt gives error

### ISSUE THREAD

**Issue by dvmason** [ziglang/zig#15884] opened 2023-05-28 14:26 UTC
### Zig Version

0.11.0-dev.3312+ab37ab33c

### Steps to Reproduce and Observed Behavior

: May28 ; cat foo.zig 
fn bar() void {
    @panic("error");
}
const foo = @ptrToInt(&bar);
test "foo" {
    _ = foo;
}
: May28 ; ~/Downloads/zig-macos-aarch64-0.11.0-dev.3312+ab37ab33c/zig test foo.zig 
foo.zig:4:13: error: unable to evaluate comptime expression
foo.zig:4:23: note: operation is runtime due to this operand
: May28 ; 

### Expected Behavior

Should just work. No value is being computed, just the type is being aliased.

Not the end of the world, since doing the cast at the reference site doesn't generate any instructions, but it's ugly to have it in a bunch of referencing sites, rather than at the definition site.

**Comment by Vexu** [comment] 2023-05-28 15:37
Duplicate of #15080

**Closed by Vexu** 2023-05-28 15:37 UTC
Labels: bug
