### ISSUE TITLE
Compiler segfault when missing catch operator on struct field default value

### ISSUE THREAD

**Issue by danielabbott** [ziglang/zig#11003] opened 2022-02-27 11:40 UTC
### Zig Version

0.10.0-dev.1009+4d658f83e

### Steps to Reproduce

main.zig:

```zig
const std = @import("std");

fn errFn(x: u32) !u32 {
    if(x == 5) {
        return error.e;
    }
    return x;
}

const X = struct {
    x: u32 = errFn(2),
    // x: u32 = errFn(2) catch unreachable,
};

pub fn main() !void {
    var x = X{};
    _=x;
}
```

### Expected Behavior

Compiler error for line `x: u32 = errFn(2),` (missing catch)

### Actual Behavior

test...The following command terminated unexpectedly:
/home/daniel/Downloads/zig-linux-x86_64-0.10.0-dev.1009+4d658f83e/zig build-exe /home/daniel/test/src/main.zig --cache-dir /home/daniel/test/zig-cache --global-cache-dir /home/daniel/.cache/zig --name test --enable-cache 
error: the following build command failed with exit code 11:
/home/daniel/test/zig-cache/o/926c7dc498f2da4fe7332438e93e02eb/build /home/daniel/Downloads/zig-linux-x86_64-0.10.0-dev.1009+4d658f83e/zig /home/daniel/test /home/daniel/test/zig-cache /home/daniel/.cache/zig run

**Comment by Vexu** [comment] 2022-02-27 11:51
Duplicate of #10357

**Closed by Vexu** 2022-02-27 11:51 UTC
Labels: bug
