### ISSUE TITLE
Build failing with undefined references to clang functions

### ISSUE THREAD

**Issue by samrat** [ziglang/zig#5156] opened 2020-04-24 04:35 UTC
Hi,

When I run `make install` I get a bunch of errors like these:

```
/usr/bin/ld: /home/samrat/code/zig/src/zig_clang_driver.cpp:347: undefined reference to `clang::driver::ToolChain::getTargetAndModeFromProgramName(llvm::StringRef)'
```

Full error: https://gist.github.com/samrat/9c7aaa5c92e0ba5ad2ea03027d84276c

Clang and LLVM versions:
```
> clang -v                                                                                                           
clang version 10.0.0 
Target: x86_64-pc-linux-gnu

> llvm-config --version
10.0.0
```

Please let me know if I can provide any more information.

**Comment by MasterQ32** [comment] 2020-04-24 09:23
Same here, using `Linux 5.6.6-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux`

```
[felix@denkplatte-v2 ~]$ clang -v 
clang version 10.0.0 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
[felix@denkplatte-v2 ~]$ llvm-config --version
10.0.0
```

**Comment by dimenus** [comment] 2020-04-24 12:39
I was able to resolve this only by linking with clang-cpp dynamically.
eg, `ZIG_PREFER_CLANG_CPP_DYLIB`

**Comment by andrewrk** [comment] 2020-05-30 01:22
I'm pretty sure this is a duplicate of #4799.

In summary, LLVM 10 made it confusing/impossible for package maintainers to package llvm/clang/ldd 10 correctly, so that they can all be linked together in the same process, as Zig requires.

So we're basically stuck with compiling llvm, clang, and lld from source for version 10. Here's hoping things will be less messed up in version 11.

https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source

**Closed** 2020-05-30 01:22 UTC
