### ISSUE TITLE
std.fs: deleteTree in dir with open file hangs in loop

### ISSUE THREAD

**Issue by ianic** [ziglang/zig#19233] opened 2024-03-09 12:43 UTC
### Zig Version

0.12.0-dev.1800+559e216f3

### Steps to Reproduce and Observed Behavior

This test fails on Windows when run with `-target aarch64-windows-gnu` on other platforms and on Windows without target flag passes.

Created file is not closed and then in `tmp.cleanup()` deleteTree loops in trying to delete that file.

Closing created file makes test pass.
Removing line `tmp.dir.close()` also makes test pass without closing file.

```Zig
test "not closing file" {
    var tmp = std.testing.tmpDir(.{});

    // This file is not closed !!!
    _ = try tmp.dir.createFile("file1", .{ .exclusive = true });

    // Next lines are from tmp.cleanup();
    tmp.dir.close();
    // This produces endless loop
    tmp.parent_dir.deleteTree(&tmp.sub_path) catch {};
    tmp.parent_dir.close();
}
```

### Expected Behavior

deleteTree should return an error instead of trying forever to delete the same file.

**Comment by ianic** [comment] 2024-03-09 22:17
When run with `-target aarch64-windows-gnu` it reports minimal windows version `WindowsVersion.win8_1` without flag it is `WindowsVersion.win10_fe`. That makes difference [here](https://github.com/ziglang/zig/blob/master/lib/std/os/windows.zig#L916) 

Without entering that 'Deletion with posix semantics' deleteTree loops:
- first [deleteFile](https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a45cbee609d3b/lib/std/fs/Dir.zig#L1967) succeeds, but [deleteDir](https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a45cbee609d3b/lib/std/fs/Dir.zig#L2012) fails with error.DirNotEmpty which [appends](https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a45cbee609d3b/lib/std/fs/Dir.zig#L2084) dir 
- others deleteFile returns on [DELETE_PENDING](https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a45cbee609d3b/lib/std/os/windows.zig#L905), dir is not empty and appended again

**Comment by squeek502** [comment] 2024-03-10 01:29
Duplicate of https://github.com/ziglang/zig/issues/15465. Would be fixed by https://github.com/ziglang/zig/pull/15467 but a different approach was requested.

**Closed by squeek502** 2024-03-10 01:29 UTC
Labels: bug
