### ISSUE TITLE
stage1: Implicit conversion from `?[:0]T` to `?[]T` causes compiler panic

### ISSUE THREAD

**Issue by gracefuu** [ziglang/zig#11636] opened 2022-05-11 17:33 UTC
### Zig Version

0.10.0-dev.2179+6608fa135

Only broken on stage 1, this works on stage 2.

### Steps to Reproduce

stage1: Implicit conversion from `?[:0]T` to `?[]T` crashes due to bad llvm codegen

(For searchability: conversion from optional zero sentinel terminated slice to optional slice with llvm backend)

```
// ohno.zig
const S = struct {
    path: ?[]u8,
};

fn f() ?[:0]u8 {
    return null;
}

pub fn main() !void {
    var s = S{ .path = f() };
    _ = s;
}
```

```
/tmp> zig-debug build-exe ohno.zig
```

### Expected Behavior

This should not compiler panic.

### Actual Behavior

This compiles properly on stage 2, but panics on stage 1.

```
/tmp> zig-debug version
0.10.0-dev.2179+6608fa135
/tmp> zig-debug build-exe -fno-stage1 ohno.zig
/tmp> zig-debug build-exe ohno.zig
broken LLVM module found: Call parameter type does not match function signature!
  %1 = getelementptr inbounds %S, %S* %s, i32 0, i32 0, !dbg !14960
 %"?[:0]u8"*  call fastcc void @f(%"?[]u8"* sret(%"?[:0]u8") %1), !dbg !14961

This is a bug in the Zig compiler.thread 2421708 panic:
~/src/zig/src/stage1.zig:178:5: 0x55acedacca07 in stage2_panic (zig1)
    @panic(ptr[0..len]);
    ^
???:?:?: 0x55aceeba1bca in zig_panic (~/src/zig/src/stage1/stage1.cpp)
???:?:?: 0x55aceebcb5b3 in do_code_gen (~/src/zig/src/stage1/stage1.cpp)
???:?:?: 0x55aceebd0c3a in codegen_build_object (~/src/zig/src/stage1/stage1.cpp)
???:?:?: 0x55aceeb9d843 in zig_stage1_build_object (~/src/zig/src/stage1/stage1.cpp)
~/src/zig/src/stage1.zig:149:32: 0x55acede5cc64 in Module.build_object (zig1)
        zig_stage1_build_object(mod);
                               ^
~/src/zig/src/Compilation.zig:5038:31: 0x55acedc382fe in Compilation.updateStage1Module (zig1)
    stage1_module.build_object();
                              ^
~/src/zig/src/Compilation.zig:2700:32: 0x55acedc2bfae in Compilation.performAllTheWork (zig1)
        comp.updateStage1Module(main_progress_node) catch |err| {
                               ^
~/src/zig/src/Compilation.zig:2107:31: 0x55acedc2521d in Compilation.update (zig1)
    try comp.performAllTheWork(main_progress_node);
                              ^
~/src/zig/src/main.zig:3104:20: 0x55acedbb4b0f in main.updateModule (zig1)
    try comp.update();
                   ^
~/src/zig/src/main.zig:2793:17: 0x55acedb11835 in main.buildOutputType (zig1)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
~/src/zig/src/main.zig:219:31: 0x55acedacaf67 in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
~/src/zig/src/stage1.zig:48:24: 0x55acedaca979 in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
fish: Job 1, 'zig-debug build-exe ohno.zig' terminated by signal SIGABRT (Abort)
```

**Comment by Vexu** [comment] 2022-05-11 19:45
Duplicate of #6147

**Closed by Vexu** 2022-05-11 19:45 UTC
Labels: bug, stage1
