### ISSUE TITLE
Setting `output_dir` on `std.build.LibExeObjStep` copies object file twice: `name.o` and `name.o.o`

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#14080] opened 2022-12-27 06:06 UTC
### Zig Version

0.11.0-dev.947+cf822c6dd

### Steps to Reproduce and Observed Behavior

1. `zig init-exe`
2. Copy the following into build.zig:
```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    // Standard target options allows the person running `zig build` to choose
    // what target to build for. Here we do not override the defaults, which
    // means any target is allowed, and the default is native. Other options
    // for restricting supported target set are available.
    const target = b.standardTargetOptions(.{});

    // Standard release options allow the person running `zig build` to select
    // between Debug, ReleaseSafe, ReleaseFast, and ReleaseSmall.
    const mode = b.standardReleaseOptions();

    const exe = b.addObject("zls-missing-root-obj", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);
    b.default_step.dependOn(&exe.step);
    exe.output_dir = b.pathFromRoot("bin");
    const exe_tests = b.addTest("src/main.zig");
    exe_tests.setTarget(target);
    exe_tests.setBuildMode(mode);

    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&exe_tests.step);
}
```
3. Run `zig build`
4.
```zig

❯ ls -l bin

.rw-r--r-- 1.1M jarred 26 Dec 21:53 zls-missing-root-obj.o
.rw-r--r-- 1.1M jarred 26 Dec 21:53 zls-missing-root-obj.o.o

❯ shasum bin/zls-missing-root-obj.o bin/zls-missing-root-obj.o.o

1f67e4c1224d44e6e91e674913770f371c645d97  bin/zls-missing-root-obj.o
1f67e4c1224d44e6e91e674913770f371c645d97  bin/zls-missing-root-obj.o.o
```

### Expected Behavior

There should only be one object file in the `output_dir` and it should be named `zls-missing-root-obj.o`, without the extra `.o` at the end.

**Comment by Vexu** [comment] 2022-12-27 10:50
Duplicate of #13179

**Closed by Vexu** 2022-12-27 10:50 UTC
Labels: bug
