### ISSUE TITLE
zig translate-c outputs @OpaqueType() for C structs with bitfields

### ISSUE THREAD

**Issue by qbradley** [ziglang/zig#3835] opened 2019-12-03 05:30 UTC
Create file repro.h with contents:

```c
struct Repro {     
    unsigned flag :1;
};
```

Run `zig translate-c repro.h`

Unexpected output:

```zig
pub const struct_Repro = @OpaqueType();
```

**Comment by daurnimator** [comment] 2020-01-02 04:49
Duplicate of #1499, #4001

**Closed by daurnimator** 2020-01-02 04:49 UTC
Labels: contributor friendly, stage2, translate-c
