### ISSUE TITLE
Segfault using anonymous tuple struct

### ISSUE THREAD

**Issue by FnControlOption** [ziglang/zig#20759] opened 2024-07-23 19:40 UTC
### Zig Version

0.14.0-dev.367+a57479afc

### Steps to Reproduce and Observed Behavior

In the following code, replacing any usage of `IntRange` with `struct { i32, i32 }` will result in a segmentation fault:

```zig
const std = @import("std");
const debug = std.debug;
const math = std.math;
const sort = std.sort;

const IntRange = struct { i32, i32 };

pub fn main() void {
    const items = [_]IntRange{ // segfaults with struct { i32, i32 }
        .{ 1, 25 },
        .{ 26, 50 },
        .{ 51, 75 },
        .{ 76, 100 },
    };
    const key: i32 = 42;
    const index = sort.binarySearch(IntRange, key, &items, {}, compareFn); // segfaults with struct { i32, i32 }
    debug.print("{?}\n", .{index});
}

fn compareFn(_: void, key: i32, mid_item: struct { i32, i32 }) math.Order {
    const lo, const hi = mid_item;
    return if (key < lo) .lt else if (key > hi) .gt else .eq;
}
```

### Expected Behavior

No segfault

**Comment by xdBronch** [comment] 2024-07-23 20:14
looks like a duplicate of https://github.com/ziglang/zig/issues/19497

**Comment by FnControlOption** [comment] 2024-07-23 20:35
None of the examples in that issue are giving me a segfault 🤔

**Comment by xdBronch** [comment] 2024-07-23 20:42
interesting, testing myself and yeah youre right. seems @Vexu mightve been wrong about the others being duplicates?

**Comment by Vexu** [comment] 2024-07-24 16:13
Only the third example in #19497 crashes now but it is different from this. The other two are the same as this one.

**Closed** 2024-12-06 03:19 UTC
Labels: bug, frontend
