### ISSUE TITLE
llvm segfault while lowering tagged union debug info

### ISSUE THREAD

**Issue by ewoudje** [ziglang/zig#18935] opened 2024-02-14 22:29 UTC
### Zig Version

0.12.0-dev.2741+d7563a775

### Steps to Reproduce and Observed Behavior

Make a zig file ex. `test.zig` with code:
```zig
const std = @import("std");

const Fizz = struct {
    pub const FooBar = union(enum) {
        b: ?*[2]FooBar,
    };

    pub fn foo() !void {
        var foos: [1]FooBar = .{FooBar{ .b = null }};

        for (&foos) |*n| {
            n.* = FooBar{ .b = null };
        }
    }
};

test "simple test" {
    try Fizz.foo();
}
```

Run `zig test test.zig` a couple of times,
On my windows 10 pc this only executes every so often? Seemingly works only when I let it be for a couple of minutes...

### Expected Behavior

Giving me a compile error, or saying a test succeeded or failed.

**Comment by Rexicon226** [comment] 2024-02-14 22:59
duplicate of #16414?

**Comment by ewoudje** [comment] 2024-02-14 23:03
> duplicate of #16414?

I don't think so, since it doesn't give any error, it just fully exits and nothing is being compiled.
The issue reference does have errors, altough the non pointer version also exits the same way. But that doesn't happen here since we still have pointers.

**Comment by Rexicon226** [comment] 2024-02-14 23:04
It *does* segfault, and with an identical trace when compiled with a debug compiler.

**Comment by ewoudje** [comment] 2024-02-14 23:07
If thats the case then probably? Or at least the same fix would apply

**Comment by jacobly0** [comment] 2024-02-15 01:42
Duplicate of #16414

**Closed by jacobly0** 2024-02-15 01:42 UTC
Labels: bug, backend-llvm
