### ISSUE TITLE
Erroneous compile error coercing ?i18 to ?i32

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#11463] opened 2022-04-18 20:46 UTC
### Zig Version

0.10.0-dev.1816+d66c61a2c

### Steps to Reproduce

```zig
fn something() ?i32 {
    const a: ?i18 = 1;
    return a;
}

test {
    _ = something();
}
```

### Expected Behavior

Succesfully compiles

### Actual Behavior

```
$ zig test cast.zig
./cast.zig:3:12: error: expected type '?i32', found '?i18'
    return a;
           ^
./cast.zig:3:12: note: optional type child 'i18' cannot cast into optional type child 'i32'
    return a;
           ^
./cast.zig:3:12: note: signed 32-bit int cannot represent all possible signed 18-bit values
    return a;
           ^
```

Some more notes:
- Making `a` non-optional fixes the compile error
- Returning `a orelse null` fixes the compile error
- Also errors with any smaller-than-32-bits sized signed integer (and fails if both are optional unsigned ints as well)
- In this particular case, `@sizeOf(?i32)` and `@sizeOf(?i18)` are both 8

**Comment by Vexu** [comment] 2022-04-28 15:13
Duplicate of #4529

**Closed by Vexu** 2022-04-28 15:13 UTC
Labels: bug
