### ISSUE TITLE
`std.debug.print`  specifier error hint

### ISSUE THREAD

**Issue by xihale** [ziglang/zig#16801] opened 2023-08-13 10:43 UTC
### Zig Version

0.11.0-dev.4410+76f7b40e1

### Steps to Reproduce and Observed Output

When I use `debug.print` with the print error occurred, I cannot simply find where it occurs.
```zig
pub fn main() void {
    const s = "hello";
    std.debug.print("{}\n", .{s});
}
```
It will cause problem, but it won't print where problem is.

### Expected Output

Like other error hint, it should print out where the problem occurred.

**Comment by jacobly0** [comment] 2023-08-13 10:48
Duplicate of #16725

**Closed by jacobly0** 2023-08-13 10:48 UTC
Labels: error message
