### ISSUE TITLE
Stage1 bug: Cannot assign anonymous struct literal to `_`

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#6848] opened 2020-10-28 11:03 UTC
stage1 test case:
```zig
test "assign anonymous struct literal to _" {
    const unnamed = .{@as(u32, 3), true}; //works
    _ = unnamed; //works
    _ = .{@as(u32, 3), true}; //error: array access of non-array type 'void'
}
```
Not really a limitation, I assume this is a stage1 oddity and stage2 is planned to support this.

**Comment by Vexu** [comment] 2020-10-28 12:45
Duplicate of #3054.

**Closed by Vexu** 2020-10-28 12:45 UTC
