### ISSUE TITLE
Parser fails to parse single-statement assignment in for loop in switch case

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#19138] opened 2024-03-01 01:30 UTC
### Zig Version

0.12.0-dev.3033+031f23117

### Steps to Reproduce and Observed Behavior

Parse the following:

```zig
test {
    const foo = undefined;
    switch (true) {
        // Does not parse:
        true => for (0..5) |_| _ = foo(),

        // Parses:
        true => for (0..5) |_| foo(),
        true => for (0..5) |_| {
            _ = foo();
        },
    }

    // Parses:
    for (0..5) |_| foo();
    for (0..5) |_| _ = foo();
    for (0..5) |_| {
        _ = foo();
    }
}
```

Note that specifically on this line does not parse:

```zig
 true => for (0..5) |_| _ = foo(),
```

Everything else parses. If you comment that line out, the whole file parses fine.

### Expected Behavior

I believe this should parse. It makes sense what is happening, and it works fine outside of a switch case.

**Comment by Rexicon226** [comment] 2024-03-01 02:00
Duplicate of #5731 i think.

**Comment by mlugg** [comment] 2024-03-01 12:42
Not a duplicate. As detailed in the issue text, placing the same loop outside of a switch prong parses successfully.

**Comment by Vexu** [comment] 2024-03-01 14:52
It is a duplicate, placing the same body outside of a switch prong causes it to be parsed as a statement rather than a expression.

**Closed by Vexu** 2024-03-01 14:52 UTC
Labels: bug
