### ISSUE TITLE
Compiler error when comparing an optional enum with an enum in an if/or statement

### ISSUE THREAD

**Issue by Ominitay** [ziglang/zig#8274] opened 2021-03-16 18:13 UTC
My cut-down example is below. Note how removing the `or foobar == Foo.Bar` part makes the code compile fine. This can be replaced with any other comparison (i.e. `true == true`) and the error will persist.
```zig
const std = @import("std");

const Foo = enum {
    Foo,
    Bar,
    Fizz,
};

pub fn main() void {
    var foobar: ?Foo = Foo.Foo;
    
    if (foobar == Foo.Foo or foobar == Foo.Bar) {
        std.log.debug("FooBar", .{});
    }
}
```

With the above example, the compiler will give us a cryptic error:
```
broken LLVM module found: PHI node entries do not match predecessors!
  %8 = phi i1 [ %7, %Entry ], [ true, %BoolOrFalse ], !dbg !16038
label %Entry
label %CmpOptionalNonOptionalEnd
Instruction does not dominate all uses!
  %7 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull ], [ %6, %CmpOptionalNonOptionalOptionalNotNu
ll ], !dbg !16037
  %8 = phi i1 [ %7, %Entry ], [ true, %BoolOrFalse ], !dbg !16038

This is a bug in the Zig compiler.
```

I hope my (first) issue explains this well enough!

**Comment by Vexu** [comment] 2021-03-16 18:20
Duplicate of #6059.

**Closed by Vexu** 2021-03-16 18:20 UTC

**Comment by Ominitay** [comment] 2021-03-16 18:22
Thanks for pointing me!
