### ISSUE TITLE
  std.debug.print without new line doesn't display correctly in test

### ISSUE THREAD

**Issue by User65-87-11** [ziglang/zig#17977] opened 2023-11-12 13:13 UTC
### Zig Version

0.12.0-dev.1482+e74ced21b

### Steps to Reproduce and Observed Behavior

```
test "no new line" {
    std.debug.print("{c}", .{@as(u8, 66)});
}
test "yes new line" {
    std.debug.print("{c}\n", .{@as(u8, 66)});
}

test "end new line" {
    std.debug.print("\n", .{});
    std.debug.print("{c}", .{@as(u8, 66)});
}


```

output:

TTest [2/3] test.yes new line... B
Test [3/3] test.end new line... 
All 3 tests passed.

Test [1/3] name is partly is missing 
Test[3/3] doesn't output 'B'

### Expected Behavior

Expected all output.

**Comment by N00byEdge** [comment] 2023-11-12 15:20
intended, testa shouldn't print

**Comment by nektro** [comment] 2023-11-12 19:17
printing directly to stdout/stderr is currently illegal behavior in tests. use `std.log` or a `main()` function. duplicate of https://github.com/ziglang/zig/issues/15091 and related

**Closed** 2023-11-13 09:04 UTC
Labels: bug
