### ISSUE TITLE
comparison with `undefined` produces unexpected valid behaviour

### ISSUE THREAD

**Issue by PastMoments** [ziglang/zig#10703] opened 2022-01-27 04:19 UTC
### Zig Version

0.9.0

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() void {
    var a : u32 = undefined;

    std.log.info("{}", .{a == undefined});
    std.log.info("{}", .{a == undefined});
    std.log.info("{}", .{a != undefined});
}
```

### Expected Behavior

There should be a compilation error, as the documentation for `undefined` says:

https://ziglang.org/documentation/master/#undefined
`undefined` can be coerced to any type. Once this happens, it is no longer possible to detect that the value is `undefined`. `undefined` means the value could be anything, even something that is nonsense according to the type. Translated into English, `undefined` means "Not a meaningful value. Using this value would be a bug. The value will be unused, or overwritten before being used."

Thus, any comparison with `undefined` should be invalid. This could be a silent footgun from confusing `null` and `undefined`. A compiler message recommending optionals + null instead may be useful.

### Actual Behavior

Using `undefined` in a comparison expression such as `a == undefined` produces a valid boolean value. However, this boolean value doesn't seem to actually describe whether a variable is defined or not.

For 0.9.0 (on godbolt)
```
info: false
info: false
info: false
```

Interestingly, for the trunk version on godbolt (some 0.10.0 dev version), you have this result:
```
info: true
info: false
info: false
```

**Comment by squeek502** [comment] 2022-01-27 05:43
Related to / duplicate of https://github.com/ziglang/zig/issues/211 and https://github.com/ziglang/zig/issues/1947

**Comment by Vexu** [comment] 2022-01-29 16:47
I think it would make sense for any operation between a runtime value and undefined to result in undefined where currently the check only exists if both values are comptime known.

**Comment by VoilaNeighbor** [comment] 2023-09-18 09:24
I would say we forbid this tricky comparison, and add another intrinsics `@isUndefined` which can only be used in Debug builds.

**Comment by wrongnull** [comment] 2023-11-27 08:41
Related to https://github.com/ziglang/zig/issues/17798 (and already has unmerged fix)

**Closed** 2024-09-17 13:34 UTC
Labels: bug, frontend
