### ISSUE TITLE
Support fetching arbitrary files via package manager.

### ISSUE THREAD

**Issue by VisenDev** [ziglang/zig#21677] opened 2024-10-12 02:27 UTC
Sometimes I've had the need to fetch a file with the zig package manager, but the package manager only supports compressed tarballs/zips and git repositories at the moment. I would be nice if we had a "simple" fetch mode where the package manager just fetched any file and stored it. 

For example,

```zig
.my_arbitrary_file = .{
    .path = "raw_file+https://raw.githubusercontent.com/ziglang/zig/refs/heads/master/.mailmap",
    .hash = "HASH_HERE",
},
```

This fetch mode would effectively fetch the file in the same way `wget` or `curl` would fetch a file from a uri.

**Comment by xdBronch** [comment] 2024-10-12 02:34
duplicate of https://github.com/ziglang/zig/issues/17895

**Closed** 2024-10-12 02:37 UTC
