### ISSUE TITLE
@ptrCast of optional slice causes compiler panic

### ISSUE THREAD

**Issue by kcbanner** [ziglang/zig#19168] opened 2024-03-03 19:57 UTC
### Zig Version

0.12.0-dev.3152+90c1a2c41

### Steps to Reproduce and Observed Behavior

Attempt to compile the following code:

```zig
const std = @import("std");

pub fn main() void {
    const glsl_version: ?[:0]const u8 = undefined;
    const ptr: *const anyopaque = @ptrCast(glsl_version);
    _ = ptr;
}
```

```
c:\cygwin64\home\kcbanner\temp>zig-debug build-exe ptrcast_optional_slice.zig
thread 10408 panic: reached unreachable code
Analyzing ptrcast_optional_slice.zig: ptrcast_optional_slice.zig:main
      %5 = dbg_stmt(2, 5)
      %6 = block_comptime({
        %7 = ptr_type(@u8_type, const, Slice, @zero_u8) node_offset:4:26 to :4:38
        %8 = optional_type(%7) node_offset:4:25 to :4:38
        %9 = break(%6, %8)
      }) node_offset:4:25 to :4:38
      %10 = as_node(%6, @undef) node_offset:4:41 to :4:50
      %11 = dbg_var_val(%10, "glsl_version")
      %12 = dbg_stmt(3, 5)
      %13 = block_comptime({
        %14 = ptr_type(@anyopaque_type, const, One) node_offset:5:16 to :5:32
        %15 = break(%13, %14)
      }) node_offset:5:16 to :5:32
      %16 = dbg_stmt(3, 35)
    > %17 = ptr_cast(%13, %10) node_offset:5:35 to :5:57
      %18 = as_node(%13, %17) node_offset:5:35 to :5:57
      %19 = dbg_var_val(%18, "ptr")
      %20 = dbg_stmt(4, 5)
      %21 = ensure_result_non_error(%18) node_offset:6:9 to :6:12
      %22 = restore_err_ret_index_unconditional(.none) node_offset:3:1 to :3:7
      %23 = ret_implicit(@void_value) token_offset:7:1 to :7:1
    For full context, use the command
      zig ast-check -t ptrcast_optional_slice.zig


C:\cygwin64\home\kcbanner\kit\zig\src\InternPool.zig:6979:17: 0x693161 in slicePtrType (zig.exe.obj)
        else => unreachable, // not a slice type
                ^
C:\cygwin64\home\kcbanner\kit\zig\src\type.zig:1756:62: 0x3cd8e1 in slicePtrFieldType (zig.exe.obj)
        return Type.fromInterned(mod.intern_pool.slicePtrType(ty.toIntern()));
                                                             ^
C:\cygwin64\home\kcbanner\kit\zig\src\Sema.zig:32558:49: 0xd7170f in analyzeSlicePtr (zig.exe.obj)
    const result_ty = slice_ty.slicePtrFieldType(mod);
                                                ^
C:\cygwin64\home\kcbanner\kit\zig\src\Sema.zig:22782:44: 0x163e371 in ptrCastFull (zig.exe.obj)
        break :ptr try sema.analyzeSlicePtr(block, operand_src, operand, operand_ty);
                                           ^
C:\cygwin64\home\kcbanner\kit\zig\src\Sema.zig:22516:28: 0x119365f in zirPtrCast (zig.exe.obj)
    return sema.ptrCastFull(
                           ^
C:\cygwin64\home\kcbanner\kit\zig\src\Sema.zig:1134:65: 0xc6618c in analyzeBodyInner (zig.exe.obj)
            .ptr_cast                     => try sema.zirPtrCast(block, inst),
                                                                ^
C:\cygwin64\home\kcbanner\kit\zig\src\Sema.zig:901:26: 0xc60493 in analyzeFnBody (zig.exe.obj)
    sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                         ^
C:\cygwin64\home\kcbanner\kit\zig\src\Module.zig:4518:23: 0x931837 in analyzeFnBody (zig.exe.obj)
    sema.analyzeFnBody(&inner_block, fn_info.body) catch |err| switch (err) {
                      ^
C:\cygwin64\home\kcbanner\kit\zig\src\Module.zig:3190:32: 0x665952 in ensureFuncBodyAnalyzed (zig.exe.obj)
    var air = zcu.analyzeFnBody(func_index, sema_arena) catch |err| switch (err) {
                               ^
C:\cygwin64\home\kcbanner\kit\zig\src\Compilation.zig:3505:42: 0x663a51 in processOneJob (zig.exe.obj)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
C:\cygwin64\home\kcbanner\kit\zig\src\Compilation.zig:3434:30: 0x436f1a in performAllTheWork (zig.exe.obj)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
C:\cygwin64\home\kcbanner\kit\zig\src\Compilation.zig:2191:31: 0x43244f in update (zig.exe.obj)
    try comp.performAllTheWork(main_progress_node);
                              ^
C:\cygwin64\home\kcbanner\kit\zig\src\main.zig:4439:24: 0x460779 in updateModule (zig.exe.obj)
        try comp.update(main_progress_node);
                       ^
C:\cygwin64\home\kcbanner\kit\zig\src\main.zig:3348:17: 0x4c7c0c in buildOutputType (zig.exe.obj)
    updateModule(comp, color) catch |err| switch (err) {
                ^
C:\cygwin64\home\kcbanner\kit\zig\src\main.zig:258:31: 0x2cf59c in mainArgs (zig.exe.obj)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
C:\cygwin64\home\kcbanner\kit\zig\src\main.zig:204:20: 0x2ccd4e in main (zig.exe.obj)
    return mainArgs(gpa, arena, args);
                   ^
C:\cygwin64\home\kcbanner\kit\zig\lib\std\start.zig:484:75: 0x2cca45 in main (zig.exe.obj)
    return callMainWithArgs(@as(usize, @intCast(c_argc)), @as([*][*:0]u8, @ptrCast(c_argv)), envp);
                                                                          ^
c:\cygwin64\home\kcbanner\kit\zig\lib\libc\mingw\crt\crtexe.c:267:0: 0x2bf34b5 in __tmainCRTStartup (crt2.obj)
    mainret = _tmain (argc, argv, envp);

c:\cygwin64\home\kcbanner\kit\zig\lib\libc\mingw\crt\crtexe.c:188:0: 0x2bf350b in mainCRTStartup (crt2.obj)
  ret = __tmainCRTStartup ();

???:?:?: 0x7ffb4b1f7343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffb4d1626b0 in ??? (ntdll.dll)
```

### Expected Behavior

It seems like a `@ptrCast` on an optional slice should not be allowed, so a compiler error.

Otherwise, perhaps if the pointer type itself is optional, this should be allowed?

**Comment by nektro** [comment] 2024-03-03 23:50
related/potential duplicate: https://github.com/ziglang/zig/issues/18913

**Comment by nektro** [comment] 2024-03-03 23:51
imo this example should be a compile error since you're attempting to cast to a non-optional and non-allowzero pointer

**Comment by N00byEdge** [comment] 2024-03-04 11:51
does ptrCast even need to handle optional pointers at all? `if(ptr) |p| @ptrCast(p) else null;`?

**Comment by mlugg** [comment] 2024-03-04 12:48
@N00byEdge It'd be confusing for it not to, since optional pointers are just our representation of nullable pointers. I think this part of the language design is pretty decided.

**Comment by kcbanner** [comment] 2024-03-04 14:27
This wasn't a proposal, but a big report about a panic.

**Comment by Vexu** [comment] 2024-03-04 18:40
Yes but it's a duplicate of #18913

**Closed** 2024-03-04 20:44 UTC
Labels: bug, frontend
