### ISSUE TITLE
Ternary if works incorrectly inside tuple

### ISSUE THREAD

**Issue by wvlab** [ziglang/zig#13583] opened 2022-11-18 17:51 UTC
### Zig Version

0.9.1-2

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const testing = @import("std").testing;
const RndGen = std.rand.DefaultPrng;

test "anonymous struct ternary if" {
    var list = std.ArrayList(u8).init(testing.allocator);
    defer list.deinit();
   
    var rnd = RndGen.init(2).random();
    var n: usize = 0;

    while (rnd.int(i8) != 5) {
        n += 1;
    }
    std.debug.print("\nn: {}\n", .{n});
    
    var sign = "-";
    if (@mod(n, 2) == 1) {
        sign = "+";
    }

    try list.writer().print(
        "{s}",
        .{ if (@mod(n, 2) == 1) "+" else "-"},
    );
    testing.expect(std.mem.eql(u8, list.items, sign)) catch |err| {
        std.debug.print("\ngot: {s}\n", .{list.items});
        std.debug.print("expected: {s}\n", .{sign});
        return err;
    };
 
    sign = "-";
    if (@mod(n - 1, 2) == 1) {
        sign = "+";
    }

    try list.writer().print(
        "{s}",
        .{ if (@mod(n - 1, 2) == 1) "+" else "-"},
    );
    testing.expect(std.mem.eql(u8, list.items, sign)) catch |err| {
        std.debug.print("got: {s}\nexpected: {s}", .{list.items, sign});
        return err;
    };
}
```

### Expected Behavior

I expected to have runtime ternary if inside tuple or at least compilation error, nothing happened and it returned value if condition was true. I think it can easily cause bugs in some projects

**Comment by Vexu** [comment] 2022-11-18 18:01
Duplicate of #3882, fixed in self-hosted which ships by default in the latest release 0.10.0

**Closed by Vexu** 2022-11-18 18:01 UTC
Labels: bug
