### ISSUE TITLE
fn memoized with incorrect value from parent scope when value is from `inline else` of a `switch`

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#19586] opened 2024-04-08 10:37 UTC
### Zig Version

0.12.0-dev.1828+225fe6ddb

### Steps to Reproduce and Observed Behavior

1. Code
```zig
const std = @import("std");
const LogLevel = enum {
    verbose,
    default,
};

pub fn main() void {
    const argv = std.os.argv;
    const last = argv[argv.len - 1];

    std.debug.print("       Last arg: {s}\n", .{last});
    var log_level: LogLevel = .default;
    if (last[0] == '1') {
        log_level = .verbose;
    }

    switch (log_level) {
        inline else => |level| {
            std.debug.print(" before closure: {s}\n", .{@tagName(level)});
            const Closure = struct {
                pub fn run() void {
                    std.debug.print(" within closure: {s}\n", .{@tagName(level)});
                }
            };
            Closure.run();
        },
    }
}
```

2. Run:
```zig
> zig run repro.zig -- 0
       Last arg: 0
 before closure: default
 within closure: default

> zig run repro.zig -- 1
       Last arg: 1
 before closure: verbose
 within closure: default
```

### Expected Behavior

It should output the following:

```zig
> zig run repro.zig -- 0
       Last arg: 0
 before closure: default
 within closure: default

> zig run repro.zig -- 1
       Last arg: 1
 before closure: verbose
 within closure: verbose
```

It should not choose the last value from the `inline else` for each invocation. It also shouldn't be a compiler error since `log_level` is unambiguously comptime-known due to the `inline else`.

**Comment by rohlem** [comment] 2024-04-08 11:34
Data point: Does not reproduce for me on old version `0.12.0-dev.3182+f3227598e`.
That means the type deduplication https://github.com/ziglang/zig/issues/18816 , implemented in https://github.com/ziglang/zig/pull/19190 , didn't cause this initially; it must have broken since then.

**Comment by Jarred-Sumner** [comment] 2024-04-08 12:17
@rohlem that version is newer than the one I tested with `0.12.0-dev.1828+225fe6ddb`

**Comment by mlugg** [comment] 2024-04-08 12:44
Fixed on master (tested by @rohlem, plus I tested on `0.12.0-dev.3563+129de47a7`). This was probably an old bug with capture scopes.

**Closed by mlugg** 2024-04-08 12:44 UTC
Labels: bug
