### ISSUE TITLE
zig test crashes with 'zig test tests/test.zig' (ie, if the tests are in own tests directory)

### ISSUE THREAD

**Issue by TapioT** [ziglang/zig#10134] opened 2021-11-11 09:06 UTC
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0-dev.1601+e89e3735f

### Steps to Reproduce

Do the following:
1. In a new directory, run `zig init-exe`
2. On top level, create directory called tests
3. Create file test.zig in tests:
```
const std = @import("std");

const my_defs = @import("../src/main.zig");

test "Sanity check" {
    try std.testing.expect(true);
}
```

As a motivation, I wanted to create structs and functions in the src directory, and keep the tests for them in a different directory.

### Expected Behavior

All 1 tests passed

### Actual Behavior

'zig test tests/test.zig' terminated by signal SIGSEGV (Address boundary error)

**Comment by LemonBoy** [comment] 2021-11-13 11:18
Duplicate of #9404

**Comment by TapioT** [comment] 2021-11-15 07:27
Closing as duplicate

**Closed** 2021-11-15 07:27 UTC
Labels: bug
