### ISSUE TITLE
Missing anonymous union support in @cImport / @cInclude

### ISSUE THREAD

**Issue by belse-de** [ziglang/zig#3949] opened 2019-12-19 23:01 UTC
When I import a C header in zig with
```
use @cImport({
    @cInclude("rgb.h");
});
```
containing following structure:
```
typedef struct{
    union {
        struct {
            union {
                uint8_t r;
                uint8_t red;
            };
            union {
                uint8_t g;
                uint8_t green;
            };
            union {
                uint8_t b;
                uint8_t blue;
            };
        };
        uint8_t raw[3];
    };
}  CRGB ;
```
I get following error from the compiler: 
```
assertion failed. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
```
Compiling with `--verbose --verbose-cimport` did not show anything except the above error.

If I use translate-c I finally get the following error:
```
error: duplicate struct field: ''
    @"": extern union {
```

I would expected a more verbose error like: 
> header rgb.h contains not supported C feature in line: 256

Found in:
```
$ zig version
0.5.0
```
related to #985 (https://github.com/ziglang/zig/issues/985)

**Comment by daurnimator** [comment] 2019-12-20 01:19
I think this is a duplicate of #985 and maybe #1214. You've already added a comment over in #985, so I think that's sufficient to track.

**Closed by daurnimator** 2019-12-20 01:19 UTC

**Comment by belse-de** [comment] 2019-12-20 14:07
My point was more about a proper error message containing file and line number, 
since it took me quite a while to find this route cause.
