### ISSUE TITLE
error: unable to unpack tarball to temporary directory: EndOfStream

### ISSUE THREAD

**Issue by hazeycode** [ziglang/zig#20256] opened 2024-06-10 20:33 UTC
### Zig Version

0.13.0-dev.351+64ef45eb0

### Steps to Reproduce and Observed Behavior

```
zig fetch --save https://github.com/zig-gamedev/system-sdk/archive/refs/tags/v0.2.0.tar.gz
error: unable to unpack tarball to temporary directory: EndOfStream
```

### Expected Behavior

Package is downloaded and build.zig.zon dependency entry is added.

**Comment by squeek502** [comment] 2024-06-11 01:20
I get `Unexpected end of data` when trying to extract with 7-zip.

**Comment by hazeycode** [comment] 2024-06-11 20:50
Weird. I can open and extract this archive using the Windows 11 File Explorer builtin thing and with `tar` on Linux but not with the builtin thing on MacOS 14.5.

**Comment by Paul-Dempsey** [comment] 2024-06-11 20:58
Windows 11 recent updates added more compression formats.

**Comment by hazeycode** [comment] 2024-06-11 21:03
Even weirder, I downloaded from the same url twice and got 2 different results on macOS (no Zig involved). One is 42.6 MB and the other is 3.5 MB.

Something is truncating the archives so I'll close this on the basis that this is not a Zig issue.

**Comment by hazeycode** [comment] 2024-06-11 21:34
A similar issue: https://github.com/NixOS/nix/issues/4533

**Comment by hazeycode** [comment] 2024-06-11 21:37
A similar issue: https://github.com/NixOS/nix/issues/4533

Maybe Zig could retry downloading a couple of times if the archive is truncated?

**Comment by hippietrail** [comment] 2024-06-12 02:59
Maybe `zig fetch` is not correctly detecting that the download fails and/or not checking that actual and expected download lengths match before trying to unpack. Could also be the server not (correctly) reporting download aborting or expected length.

**Comment by marler8997** [comment] 2024-06-12 03:08
> Even weirder, I downloaded from the same url twice and got 2 different results on macOS (no Zig involved). One is 42.6 MB and the other is 3.5 MB.
> https://github.com/zig-gamedev/system-sdk/archive/refs/heads/main.tar.gz if anyone wants to try it.

That URL you linked is pointing to the main branch which does change.

**Comment by hazeycode** [comment] 2024-06-12 08:49
> > Even weirder, I downloaded from the same url twice and got 2 different results on macOS (no Zig involved). One is 42.6 MB and the other is 3.5 MB.
> 
> > https://github.com/zig-gamedev/system-sdk/archive/refs/heads/main.tar.gz if anyone wants to try it.
> 
> 
> 
> That URL you linked is pointing to the main branch which does change.

You can download from the url multiple times without the main branch changing. Sometimes the archive is truncated and other times is isn't. This comment is just noise.

**Comment by rofrol** [comment] 2024-06-12 11:51
> In case of the server or proxy server is SIGKILLed during data transfer, Linux kernel will terminated the TCP connection by FIN+ACK. And if the server doesn't provide Content-Length (eg. GitHub tarball archive URLs), our current behavior is to exit without error, leaving incomplete data.

https://github.com/curl/curl/pull/6736

**Comment by andrewrk** [comment] 2024-08-14 07:09
Seems to be working as designed. Perhaps this can be considered a duplicate of #17472.

**Closed by andrewrk** 2024-08-14 07:09 UTC
