### ISSUE TITLE
bug: arm v7m build broken: inline asm / predicated instructions must be in IT block

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#4425] opened 2020-02-10 15:48 UTC
When building for arm-v7m the build is broken due to parsing errors in compiler_rt inline assembler:

```
Build Dependencies...compiler_rt [3] Code Generation [187/233] compiler_rt.truncXfYf2.tru...<inline asm>:14:2: error: predicated instructions must be in IT block
 movne r0, r2
 ^
<inline asm>:15:2: error: predicated instructions must be in IT block
 addeq r1, #16
 ^
<inline asm>:18:2: error: predicated instructions must be in IT block
 movne r0, r2
 ^
<inline asm>:19:2: error: predicated instructions must be in IT block
 addeq r1, #8
 ^
<inline asm>:22:2: error: predicated instructions must be in IT block
 movne r0, r2
 ^
<inline asm>:23:2: error: predicated instructions must be in IT block
 addeq r1, #4
 ^
<inline asm>:26:2: error: predicated instructions must be in IT block
 movne r0, r2
 ^
<inline asm>:27:2: error: predicated instructions must be in IT block
 addeq r1, #2
 ^
LLVM ERROR: Error parsing inline asm
```

Just initialize a default project with `zig init-exe` and add the following:
```zig
const cortex_m3_arch = std.Target.Arch{ .arm = .v7m };
exe.setTheTarget(.{
    .Cross = .{
        .arch = cortex_m3_arch,
        .os = .freestanding,
        .abi = .eabi,
        .cpu_features = std.Target.CpuFeatures.initFromCpu(cortex_m3_arch, &std.Target.arm.cpu.cortex_m3),
    },
});
```

Zig Version: 0.5.0+014f66e6d

**Comment by LemonBoy** [comment] 2020-02-10 16:02
#4266 come on, the search button is there!

**Comment by andrewrk** [comment] 2020-02-10 16:07
fwiw I didn't realize they were the same issue either

**Comment by MasterQ32** [comment] 2020-02-10 16:18
> #4266 come on, the search button is there!

I used the [search](https://github.com/ziglang/zig/search?q=predicated+instructions+must+be+in+IT+block&unscoped_q=predicated+instructions+must+be+in+IT+block&type=Issues), but maybe it was a bit too specific....

**Comment by LemonBoy** [comment] 2020-02-10 16:55
This can be closed then? If you need a "workaround" just compile in thumb mode. I'm not even sure this can be considered a bug, it's more of a configuration error on the user end.

**Comment by andrewrk** [comment] 2020-02-10 16:56
duplicate of #4266

**Closed by andrewrk** 2020-02-10 16:56 UTC
Labels: arch-arm32, bug, stage1

**Comment by vegecode** [comment] 2020-02-10 19:51
Maybe this subarch should be removed from the arm and armeb architectures
so that it can't be selected since it is an invalid combo.
