### ISSUE TITLE
`@cImport` fails with `out of memory` on "native"-object to "cross-compiled-to-native"-executable mismatch

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#3520] opened 2019-10-23 23:35 UTC
**UPDATE2**: I think I've now figured out the root cause (for the initial failure, though not for the invalid error code):
I had instructed the `build.zig` file to cross-compile the executable _for the target reported as "native"_, but _hadn't specified_ the `main.zig` object's target (-> presumably compiled as "*natively native*"). This means the libc paths/files for `main.zig` wouldn't have matched the executable's (assuming they might have been the system files? Though note `zig run main.zig -lc` compiled Zig's own libc) - although the executable has no other sources. So I still don't quite get it.
`zig run` without libc exhibiting the error seems just as strange.
And I also don't understand how the error code was `out of memory` - at **compile time**, so it can't have been a link-time ABI/libc mismatch. Could glibc detection (reported as `2.17`) on the old kernel be compromised, and that propagates undefined behaviour throughout?

**UPDATE**: I've since found out, AFTER typing up this issue, (`uname -r` > `3.10.0-1062.4.1.el7.x86_64`) that the system is running an unsupportedly old Linux kernel according to the support table, though maybe newer kernels can trigger the same bug.
The fact that one configuration works correctly makes me believe that there's something that could be done on Zig's end (i.e. using the other branch's logic as fallback), however if that's not deemed worth it, then I guess not.

This was encountered on a `Linux/GNU` university server via ssh (the same as #3518 ); I don't know configuration details, but am willing to find out, given some directions.

After agonizing quite a while over why `@cImport` always failed in one project and not in another, I tested it locally to find out that Zig seems to outputs the wrong error message on the remote server:
Remote output (x86_64-linux-gnu):
```
.../main.zig:1:12: error: C import failed: out of memory
const oc = @cImport({
           ^
.../main.zig:7:9: note: referenced here
    _ = oc.printf(c"All your base are belong to us.\n");
        ^
```
Local output (x86_64-windows-msvc):
```
...\main.zig:1:12: error: C import failed
const oc = @cImport({
           ^
...\main.zig:1:12: note: libc headers not available; compilation does not link against libc
const oc = @cImport({
           ^
(Local Appdata)l\zig\stage1\o\...\cimport.h:1:10: note: 'stdio.h' file not found
#include <stdio.h>
         ^
...\main.zig:7:9: note: referenced here
    _ = oc.printf(c"All your base are belong to us.\n");
        ^
```
(both running `zig version` of `0.5.0+cb8dacabd` from `ziglang.org/download/`)

So while I know now what failed, it still seems a bug that the primary error returned was `out of memory` on the remote system, but not on the local system. (I assume whether the  `note` is displayed is directly linked to the error code.)
This __might__ be some Windows vs Linux thing, but as Zig is primarily developed on Linux this looks like a very uncommon bug.

These are the scenarios I've tested:
- `zig run main.zig`:
  - `error: C import failed: out of memory` on remote system
- `zig run main.zig -lc`:
  - successful build on remote system
- `zig build` with root source file (`const exe = b.addExecutable("main", "main.zig")`)
  - without linking libc (no `exe.linkSystemLibrary("c")`):
     - **correct error and note on remote system**
  - linking libc:
     - **SUCCESSFUL build**
- `zig build` without root source file (`const exe = b.addExecutable("main", null)`) and source file as object (`const obj = b.addObject("main", "main.zig"); exe.addObject(obj);`):
  - without linking libc (no `.linkSystemLibrary("c")`);
    - `error: C import failed: out of memory` on remote system
  - linking libc to the object:
    - `error: C import failed: out of memory` on remote system
    - (local system: compilation succeeds, lld fails linking with `unknown symbol` for referenced symbols)
  - linking libc to the executable:
    - `error: C import failed: out of memory` on remote system
  - linking libc to both object and executable:
    - __ALSO FAILS with `error: C import failed: out of memory` on remote system__
    - _(EDIT: local system: works both natively and cross-compiling (previously forgot to set the object's target to cross-compile as well))_

I thought this might have to do with the fact I have to on-system cross-compile (see #3518 ), but when testing on Windows the error message was always consistently correct whether cross-compiling or not.
As stated ad top, the kernel is unsupportedly old; maybe it's actually a bug on their side. (It also seems to some custom compilation: `uname -v` > `#1 SMP Fri Oct 18 17:15:30 UTC 2019
`.)
The fact that one configuration manages to compile and one configuration outputs the correct error makes me think there's a solution, though a fix might only be interesting if it is found affecting newer kernel versions.

**Comment by andrewrk** [comment] 2020-02-21 19:03
I believe this is a duplicate of #4455. The "out-of-memory" was a bug in diagnosing why clang failed to report diagnostics, and was fixed in #4467.

**Closed by andrewrk** 2020-02-21 19:03 UTC
