### ISSUE TITLE
build windows ReleaseSmall pdb copy error

### ISSUE THREAD

**Issue by xywf221** [ziglang/zig#15742] opened 2023-05-17 11:58 UTC
### Zig Version

0.11.0-dev.3132+465272921

### Steps to Reproduce and Observed Output

```bash
➜  zig-test zig init-exe
info: Created build.zig
info: Created src/main.zig
info: Next, try `zig build --help` or `zig build run`
➜  zig-test zig build -Dtarget=x86_64-windows -Doptimize=ReleaseSmall
install zig-test: error: unable to update file from '/private/tmp/zig-test/zig-cache/o/4b0d8df40cd6958f9e8607605afbca46/zig-test.pdb' to '/private/tmp/zig-test/zig-out/bin/zig-test.pdb': FileNotFound
Build Summary: 1/3 steps succeeded; 1 failed (disable with -fno-summary)
install transitive failure
└─ install zig-test failure
   └─ zig build-exe zig-test ReleaseSmall x86_64-windows success 1s MaxRSS:138M
error: the following build command failed with exit code 1:
/private/tmp/zig-test/zig-cache/o/4e8ba43b98120fccba4e8d5ff38dc64c/build /usr/local/Cellar/zig/0.11.0/zig /private/tmp/zig-test /private/tmp/zig-test/zig-cache /Users/dmls/.cache/zig -Dtarget=x86_64-windows -Doptimize=ReleaseSmall
```

### Expected Output

no error

**Comment by squeek502** [comment] 2023-05-17 23:22
This should be labeled bug. Can reproduce this on Windows:

```
C:\Users\Ryan\Programming\Zig\tmp\15742> zig init-exe
info: Created build.zig
info: Created src\main.zig
info: Next, try `zig build --help` or `zig build run`

C:\Users\Ryan\Programming\Zig\tmp\15742> zig build -Doptimize=ReleaseSmall
install 15742: error: unable to update file from 'C:\Users\Ryan\Programming\Zig\tmp\15742\zig-cache\o\ffb580b194906b444167c1c892eec701\15742.pdb' to 'C:\Users\Ryan\Programming\Zig\tmp\15742\zig-out\bin\15742.pdb': FileNotFound
Build Summary: 1/3 steps succeeded; 1 failed (disable with -fno-summary)
install transitive failure
+- install 15742 failure
   +- zig build-exe 15742 ReleaseSmall native success 255ms MaxRSS:103M
error: the following build command failed with exit code 1:
C:\Users\Ryan\Programming\Zig\tmp\15742\zig-cache\o\55156d082742d2ab14658cd77dd08270\build.exe C:\Users\Ryan\Programming\Zig\zig\build\stage3\bin\zig.exe C:\Users\Ryan\Programming\Zig\tmp\15742 C:\Users\Ryan\Programming\Zig\tmp\15742\zig-cache C:\Users\Ryan\AppData\Local\zig -Doptimize=ReleaseSmall
```

**Comment by Vexu** [comment] 2023-05-18 08:28
Duplicate of #13405

**Closed** 2023-05-18 08:28 UTC
Labels: bug
