### ISSUE TITLE
Tuples containing if/else expressions result in "duplicate struct field"

### ISSUE THREAD

**Issue by pixelherodev** [ziglang/zig#3944] opened 2019-12-19 11:00 UTC
Smallest reproducing example: 

```zig
const std = @import("std");

pub fn main() void {
    var a: usize = 3;
    std.debug.warn("Hello: {}\n", .{if (a == 2) 1 else 0});
}
```

Note: If you do e.g. `if (true)` or `if (1 == 1)` it gets optimized out; by using a separate variable, the error remains.

Using e.g. `zig run a.zig`:
```zig
Semantic Analysis [744/751] /home/noam/t/a.zig:5:49: error: duplicate struct field: '0'
    std.debug.warn("Hello: {}\n", .{if (a == 2) 1 else 0});
                                                ^
/home/noam/t/a.zig:5:49: note: other field here
    std.debug.warn("Hello: {}\n", .{if (a == 2) 1 else 0});
```

**Comment by Vexu** [comment] 2019-12-19 11:23
Duplicate of #3882

**Comment by pixelherodev** [comment] 2019-12-19 11:41
Whoops! Sorry about that!

**Closed** 2019-12-19 11:40 UTC
