### ISSUE TITLE
Compiler error printing struct containing slice of `format`table elements

### ISSUE THREAD

**Issue by mbolis** [ziglang/zig#18743] opened 2024-01-30 10:19 UTC
### Zig Version

0.12.0-dev.2341+92211135f

### Steps to Reproduce and Observed Behavior

Have a struct containing a slice field, and have the child element of the slice declare a `format` function.

Initialize and print the struct:

```zig
const std = @import("std");

const Char = struct {
    char: u8,

    pub fn format(self: Char, comptime _: []const u8, _: std.fmt.FormatOptions, w: anytype) !void {
        try w.print("<{c}>", .{self.char});
    }
};

const String = struct {
    chars: []const Char,
};

pub fn main() !void {
    const string = String{
        .chars = &.{
            .{ .char = 'f' },
            .{ .char = 'o' },
            .{ .char = 'o' },
        },
    };
    std.debug.print("{any}\n", .{string});
}
```

Compilation fails with:

```
/.../zig-linux-.../lib/std/fmt.zig:493:25: error: no field or member function named 'format' in '[]const main.Char'
        return try value.format(actual_fmt, options, writer);
                   ~~~~~^~~~~~~
```

---

The culprit lies between lines 492 and 494 of `std/fmt.zig`:

```zig
    if (std.meta.hasMethod(T, "format")) {
        return try value.format(actual_fmt, options, writer);
    }
```

As it turns out, `std.meta.hasMethod(T, "format")` returns `true` even if `T` is a pointer type to a `format`table type, but AFAIK there is no way to add a `format` method to a slice, so in this case the method is detected on the child type, but it cannot be called, since `value` is a slice.

### Expected Behavior

I'd expect the program to compile and produce the following output:

```
main.String{ .chars = { <f>, <o>, <o> } }
```

**Comment by Vexu** [comment] 2024-01-30 10:21
Duplicate of #18708

**Closed** 2024-01-30 10:21 UTC
Labels: bug
