### ISSUE TITLE
Segmentation fault compiling `@splat` for vector type with one possible value

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#21299] opened 2024-09-04 02:47 UTC
### Zig Version

0.14.0-dev.1411+a670f5519

### Steps to Reproduce and Observed Behaviour

Compile example program with `zig build-obj hash_undef_ref_storage_error.zig`
`hash_undef_ref_storage_error.zig`:
```zig
comptime {
    _ = @as(@Vector(1, u0), @splat(0));
}
```
Output:
```
zig build-obj hash_undef_ref_storage_error.zig
Segmentation fault
```

**Comment by xdBronch** [comment] 2024-09-04 02:58
looks like duplicate of https://github.com/ziglang/zig/issues/21204

**Comment by amp-59** [comment] 2024-09-04 03:04
> looks like duplicate of #21204

Thanks.

**Closed** 2024-09-04 12:35 UTC
