### ISSUE TITLE
Mixed up error tracing between independent tests

### ISSUE THREAD

**Issue by elbow-jason** [ziglang/zig#12466] opened 2022-08-17 16:49 UTC
### Zig Version

0.10.0-dev.3587+9d85335de

### Steps to Reproduce

In a new project created with `zig init-lib` paste the following code into `src/main.zig` and run `zig build test`:

```zig
const std = @import("std");
const expect = std.testing.expect;

const List1Error = error{ List1Overflow };

fn List1(comptime T: type, comptime N: usize) type {
    return struct {
        items: [N]T,
        len: usize,
        const Self = @This();
    
        fn init() Self {
            return std.mem.zeroes(Self);
        }

        fn push(self: *@This(), item: T) List1Error!void {
            if (self.len == N) {
                return List1Error.List1Overflow;
            }
            self.items[self.len] = item;
            self.len += 1;
        }
    };
}

const List2Error = error{ List2Overflow };

fn List2(comptime T: type, comptime N: usize) type {
    return struct {
        items: [N]T,
        len: usize,

        const Self = @This();
    
        fn init() Self {
            return std.mem.zeroes(Self);
        }

        fn push(self: *@This(), item: T) List2Error!void {
            if (self.len == N) {
                return List2Error.List2Overflow;
            }
            self.items[self.len] = item;
            self.len += 1;
        }
    };
}


test "List1 push error" {
    var l = List1(i32, 2).init();
    try l.push(1);
    try l.push(2);
    // comment out this push-and-catch to see the expected behavior.
    l.push(3) catch |e| {
        try expect(e == List1Error.List1Overflow);
    };
}

test "List2 push 1 and check items" {
    // expect(1 == 2);
    var l2 = List2(i32, 2).init();
    try l2.push(1);
    var e = [_]i32{3};
    try expect(std.mem.eql(i32, l2.items[0..l2.len], e[0..l2.len]));
}
```

### Expected Behavior

In the `test "List2 push 1 and check items"` block we expect a failure because we are comparing a slice that should contain a single `1i32` with a slice that should contain a single `3i32`:

NOTE: to reproduce this expected result comment out the specified lines in the `test "List1 push error"` block:

```zig
test "List1 push error" {
    var l = List1(i32, 2).init();
    try l.push(1);
    try l.push(2);
    // comment out this push-and-catch to see the expected behavior.
    // l.push(3) catch |e| {
    //     try expect(e == List1Error.List1Overflow);
    // };
}
```

And run `zig build test`:

```
zig build test
Test [2/2] test "List2 push 1 and check items"... FAIL (TestUnexpectedResult)
/Users/jason/.asdf/installs/zig/master/lib/zig/std/testing.zig:351:14: 0x104c9f46b in std.testing.expect (test)
    if (!ok) return error.TestUnexpectedResult;
             ^
/Users/jason/Workspace/zigs/wrong_error/src/main.zig:65:5: 0x104c9f677 in test "List2 push 1 and check items" (test)
    try expect(std.mem.eql(i32, l2.items[0..l2.len], e[0..l2.len]));
    ^
1 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
/Users/jason/Workspace/zigs/wrong_error/zig-cache/o/a2dc5a05ba422534035b29521c52e799/test /Users/jason/.asdf/installs/zig/master/zig
error: test...
error: The following command exited with error code 1:
/Users/jason/.asdf/installs/zig/master/zig test /Users/jason/Workspace/zigs/wrong_error/src/main.zig --cache-dir /Users/jason/Workspace/zigs/wrong_error/zig-cache --global-cache-dir /Users/jason/.cache/zig --name test --enable-cache 
error: the following build command failed with exit code 1:
/Users/jason/Workspace/zigs/wrong_error/zig-cache/o/b4c70385e6a381fe0c19cd7aef46b11e/build /Users/jason/.asdf/installs/zig/master/zig /Users/jason/Workspace/zigs/wrong_error /Users/jason/Workspace/zigs/wrong_error/zig-cache /Users/jason/.cache/zig test
```

### Actual Behavior

The error trace for `test "List2 push 1 and check items"` points to `return List1Error.List1Overflow;`. `List1` and `List2` share no common code and `List1Error` is not used in `List2`.

With the push-and-catch block in `test "List1 push error"` intact:

```zig
test "List1 push error" {
    var l = List1(i32, 2).init();
    try l.push(1);
    try l.push(2);
    // comment out this push-and-catch to see the expected behavior.
    l.push(3) catch |e| {
        try expect(e == List1Error.List1Overflow);
    };
}
```
Run `zig build test`:

```
❯ zig build test
Test [2/2] test "List2 push 1 and check items"... FAIL (TestUnexpectedResult)
/Users/jason/Workspace/zigs/wrong_error/src/main.zig:18:17: 0x10418d443 in List1(i32,2).push (test)
                return List1Error.List1Overflow;
                ^
/Users/jason/.asdf/installs/zig/master/lib/zig/std/testing.zig:351:14: 0x10418b3cb in std.testing.expect (test)
    if (!ok) return error.TestUnexpectedResult;
             ^
/Users/jason/Workspace/zigs/wrong_error/src/main.zig:65:5: 0x10418b66b in test "List2 push 1 and check items" (test)
    try expect(std.mem.eql(i32, l2.items[0..l2.len], e[0..l2.len]));
    ^
1 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
/Users/jason/Workspace/zigs/wrong_error/zig-cache/o/38b5fc2d563c21dceead5642bd7b78bb/test /Users/jason/.asdf/installs/zig/master/zig
error: test...
error: The following command exited with error code 1:
/Users/jason/.asdf/installs/zig/master/zig test /Users/jason/Workspace/zigs/wrong_error/src/main.zig --cache-dir /Users/jason/Workspace/zigs/wrong_error/zig-cache --global-cache-dir /Users/jason/.cache/zig --name test --enable-cache 
error: the following build command failed with exit code 1:
/Users/jason/Workspace/zigs/wrong_error/zig-cache/o/b4c70385e6a381fe0c19cd7aef46b11e/build /Users/jason/.asdf/installs/zig/master/zig /Users/jason/Workspace/zigs/wrong_error /Users/jason/Workspace/zigs/wrong_error/zig-cache /Users/jason/.cache/zig test
```

**Comment by Vexu** [comment] 2022-08-17 16:55
Duplicate of #1923, see also #12439 which is intended to mitigate the issue on this exact use case.

**Closed by Vexu** 2022-08-17 16:55 UTC
Labels: bug
