### ISSUE TITLE
@splat should be able to get result type through binop

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#17492] opened 2023-10-12 07:29 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    const a = @Vector(8, f32){ 0, 1, 2, 3, 4, 5, 6, 7 };
    const b = a * @splat(8);
    std.debug.print("{d}\n", .{b});
}
```

```
test.zig:5:19: error: @splat must have a known result type
    const b = a * @splat(8);
                  ^~~~~~~~~
test.zig:5:19: note: use @as to provide explicit result type
```

### Expected Behavior

vector sizes MUST match so `@splat` should be able to get the result type through regular binops. this error does not surface through assignment, eg `*=`

**Comment by alichraghi** [comment] 2023-10-12 09:24
duplicate of #17274

**Closed** 2023-10-12 09:50 UTC
Labels: bug
