### ISSUE TITLE
improve error message for `try` when return type is not an error or error union

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#4432] opened 2020-02-11 13:22 UTC
Using this project+branch: https://github.com/daurnimator/zig-autolua/compare/weird-bug?expand=0
```
$ zig test -I /usr/include/ -L /usr/lib -l lua -lc src/autolua.zig 
Semantic Analysis [1181/1265] ./src/autolua.zig:114:48: error: expected type 'void', found 'error:186:33'
                .Fn => lua.lua_pushcclosure(L, try wrap(@field(value, d.name)), 0),
                                               ^
./src/autolua_test.zig:183:20: note: called from here
    autolua.pushlib(L, struct {
                   ^
./src/autolua_test.zig:171:26: note: called from here
test "wrap struct works" {
                         ^
```

I don't know why its expecting `void`...

**Comment by LemonBoy** [comment] 2020-02-12 11:55
You're the one that's confused :smile: 

```zig
pub fn pushlib(L: ?*lua.lua_State, comptime value: type) void
```

Did you forget a `!` before `void`?

**Comment by daurnimator** [comment] 2020-02-12 12:14
> Did you forget a `!` before `void`?

Ah ha!
Should I leave this open as an error message that should be improved? There was no note pointing to the return type as a cause for it.

**Comment by andrewrk** [comment] 2020-02-13 22:00
Duplicate of #3230

**Closed by andrewrk** 2020-02-13 22:00 UTC
Labels: enhancement, stage1
