### ISSUE TITLE
Unexpected OutOfMemory error in stack trace under test

### ISSUE THREAD

**Issue by mlawren** [ziglang/zig#8199] opened 2021-03-10 16:18 UTC
I did not quite expect an `OutOfMemory` error from `std.heap` here:

```zig
const err_file_not_found = error.FileNotFound;

test "out_of_memory" {
    return err_file_not_found;
}
```

```
1/1 test "out_of_memory"... [default] (err): FileNotFound
lib\zig\std\heap.zig:720:17: 0x7ff79ce5195e in std.heap.FixedBufferAllocator::std.heap.FixedBufferAllocator.resize (test.obj)
                return error.OutOfMemory;
                ^
x.zig:4:5: 0x7ff79ce51c74 in test "out_of_memory" (test.obj)
    return err_file_not_found;
    ^
lib\zig\std\special\test_runner.zig:83:17: 0x7ff79ce54b52 in std.special.main (test.obj)
                return err;
                ^
error: the following test command failed with exit code 1:
zig-cache\o\ba6e08dd8b4d4acdab83572f25c3e027\test.exe C:\Users\mark\Downloads\zig-windows-x86_64-0.8.0-dev.1431+c760532be\zig.exe
```

I do not get the same error from main() when I return an error there. Something different inside the test environment?

Version: zig-windows-x86_64-0.8.0-dev.1431+c760532be.

**Comment by g-w1** [comment] 2021-03-10 16:33
It says `1/1 test "out_of_memory"... [default] (err): FileNotFound`. This is a FileNotFound error, not OutOfMemory. The OutOfMemory is a red herring. Maybe related to this. https://github.com/ziglang/zig/issues/1923

**Comment by mlawren** [comment] 2021-03-10 17:17
Thanks for the pointer - I've updated the title with a more accurate description of the issue. You are right that the correct error gets propagated in the end. But for a novice the message is confusing.

**Comment by SpexGuy** [comment] 2021-03-16 22:10
Closing as a duplicate of #1923

**Closed by SpexGuy** 2021-03-16 22:10 UTC
Labels: bug, duplicate
