### ISSUE TITLE
confusing error when I should have used `or`

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#16620] opened 2023-07-30 08:05 UTC
### Zig Version

0.11.0-dev.4315+f5239677e

### Steps to Reproduce and Observed Output

```zig
const std = @import("std");

pub fn main() void {
    var aa = false;
    const bb: u32 = 4;

    aa = aa || bb > 0;
}
```

```
test2.zig:7:10: error: expected type 'type', found 'bool'
    aa = aa || bb > 0;
         ^~
```

### Expected Output

this fails because `||` expects an error set. a nudge that operands are bools instead of types to use `or` instead would be really nice

**Comment by tau-dev** [comment] 2024-07-10 20:04
Sounds like a duplicate of #15526.

**Closed** 2024-07-15 10:58 UTC
Labels: frontend, error message
