### ISSUE TITLE
Bad line for the type of stuct field is not specified

### ISSUE THREAD

**Issue by go101** [ziglang/zig#17080] opened 2023-09-06 16:38 UTC
### Zig Version

0.12.0-dev.281+d1a14e7b6

### Steps to Reproduce and Observed Output

x.zig:

```zig
fn foo() void {
	const T = struct {
		x: u32 = 0,
		y: bool = true,
		z = false,
	};
}

pub fn main() void {
	foo();
}
```

Output:
```
x.zig:3:3: error: tuple field has a name
  x: u32 = 0,
  ^
```

### Expected Output

```
x.zig:4:3: error: tuple field has a name
  y: bool = true,
  ^
```

It would be even better to point out that the type of `z` must be specified.

**Comment by Vexu** [comment] 2023-09-07 10:01
Duplicate of #16019

**Closed by Vexu** 2023-09-07 10:01 UTC
Labels: error message
