### ISSUE TITLE
zig translate-c retains unreachable code after return, causing compilation errors

### ISSUE THREAD

**Issue by Yeaseen** [ziglang/zig#21871] opened 2024-11-01 00:31 UTC
### Zig Version

0.14.0-dev.2064+b5cafe223

## Source C code:

```c
int global_int ;
int func1() {
  int local_int = 21 ;
  return local_int += global_int * 3 ;
  local_int ++ ;
  return 0 ;
 }
void main() {
  func1();
}
```

## Translated Zig code:

```zig
pub export fn func1() c_int {
    var local_int: c_int = 21;
    _ = &local_int;
    return blk: {
        const ref = &local_int;
        ref.* += global_int * @as(c_int, 3);
        break :blk ref.*;
    };
    local_int += 1;
    return 0;
}
pub export fn main() void {
    _ = func1();
}
```
## zig build error:

```
runner.zig:66:15: error: unreachable code
    local_int += 1;
    ~~~~~~~~~~^~~~
runner.zig:61:5: note: control flow is diverted here
    return blk: {
    ^~~~~~
runner.zig:67:5: error: unreachable code
    return 0;
    ^~~~~~~~
runner.zig:61:5: note: control flow is diverted here
    return blk: {
    ^~~~~~
```

### Expected Behavior

zig translate-c should detect and remove unreachable code after a return statement to avoid these errors, generating:

```zig
pub export var global_int: c_int = @import("std").mem.zeroes(c_int);
pub export fn func1() c_int {
    var local_int: c_int = 21;
    const ref = &local_int;
    ref.* += global_int * @as(c_int, 3);
    return ref.*;
}

pub export fn main() void {
    _ = func1();
}
```

The above code has no zig build error.

**Comment by Vexu** [comment] 2024-11-02 19:33
Duplicate of #19716

**Closed by Vexu** 2024-11-02 19:33 UTC
Labels: bug
