### ISSUE TITLE
Plans to warn about unused code elements?

### ISSUE THREAD

**Issue by donaldcallen** [ziglang/zig#3395] opened 2019-10-07 14:48 UTC
Are there plans to provide warnings about unused elements, whether they be imports, structs, struct fields, enums, enums fields, consts, etc.?

I have found this to be very helpful in my Rust work in weeding out unused clutter in my code.

As a test, I just tried compiling this very incomplete code fragment, with a lot of unused stuff. it compiled without error or warning:

```
const std = @import("std");
const allocator = std.heap.c_allocator;
const constants = @import("open_positions_constants.zig");
const debug = std.debug;
const fs = std.fs;
const io = std.io;
const lib = @import("../library/lib.zig");
const math = std.math;
const mem = std.mem;
const os = std.os;
const process = std.process;

const OpenPosition = struct {
    symbol: []const u8,
    name: []const u8,
    cusip: []const u8,
    commodity_guid: []const u8,
    quantity: f64,
    current_value: ?f64,
    capital_gain: ?f64,
    total_gain: ?f64,
    annualized_return: ?f64,
    total_annualized_return: ?f64,
    most_recent_quote_timestamp: ?f64,
};

const InvestmentReportType = enum {
    Value,
    CapitalGain,
    TotalCapitalGain,
    AnnualizedReturn,
    TotalAnnualizedReturn,
    MostRecentQuote,
};

pub fn main() void {
    const END_DATE = 1;
}
```

**Comment by emekoi** [comment] 2019-10-08 13:03
duplicate of #335.

**Closed** 2019-10-09 15:45 UTC
Labels: proposal
