### ISSUE TITLE
Compiler error on return `?bool` from a function with `if`

### ISSUE THREAD

**Issue by cpkio** [ziglang/zig#9593] opened 2021-08-20 07:05 UTC
Returning `?bool` from a function with `if` results in an error.

### Code
```
const std = @import("std");

pub fn main() void {
    std.debug.print("Val is: {}", .{returnsNull(null, 2)});
}

fn returnsNull(a: ?bool, b: u8) ?bool {
    if (a == false and b == 0) {
        return true;
    } else if (a == true and b >= 4) {
        return false;
    } else {
        return a;
    }
}
```

### Compiler error
```
Code Generation [448/735] std.mem.Allocator.allocAdvancedWithRetAddr... broken LLVM module found: PHI node entries do not match predecessors!
  %11 = phi i1 [ %8, %Entry ], [ %10, %BoolAndTrue ], !dbg !21641
label %Entry
label %CmpOptionalNonOptionalEnd
Instruction does not dominate all uses!
  %8 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull ], [ %7, %CmpOptionalNonOptionalOptionalNotNull ], !dbg !21639
  %11 = phi i1 [ %8, %Entry ], [ %10, %BoolAndTrue ], !dbg !21641
PHI node entries do not match predecessors!
  %22 = phi i1 [ %19, %Else ], [ %21, %BoolAndTrue4 ], !dbg !21649
label %Else
label %CmpOptionalNonOptionalEnd3
Instruction does not dominate all uses!
  %19 = phi i1 [ false, %CmpOptionalNonOptionalOptionalNull2 ], [ %18, %CmpOptionalNonOptionalOptionalNotNull1 ], !dbg !21648
  %22 = phi i1 [ %19, %Else ], [ %21, %BoolAndTrue4 ], !dbg !21649

This is a bug in the Zig compiler.thread 1800 panic:
Unable to dump stack trace: debug info stripped
```

Tested on `0.8.0` and `0.9.0-dev.807+d785dc49a`

**Comment by Vexu** [comment] 2021-08-20 07:09
Duplicate of #6059.

**Closed by Vexu** 2021-08-20 07:09 UTC
