### ISSUE TITLE
incorrect error note when arrays are used inside packed structs

### ISSUE THREAD

**Issue by tgschultz** [ziglang/zig#2412] opened 2019-05-02 19:22 UTC
```zig
const std = @import("std");
const expect = std.testing.expect;

//removing `packed` or changing the `bytes` array to be a power of 2 fixes the issue.
const S = packed struct {
    bytes: [3]u8,

    pub fn foo(self: *@This(), index: usize) void {
        const bar = self.bytes[index];
        _ = bar;
    }
};

test "unable to evaluate constant expression" {
    var data: S = undefined;
    data.foo(0);
}
```

Probably has to do with alignment.

**Comment by andrewrk** [comment] 2019-09-28 21:31
I'll be sure to take a look at this as part of #3133.

**Comment by anaanook** [comment] 2020-12-27 06:32
Just dropping a note I hit this today.  Compiler hint was really throwing me off, and yes, setting the array to a power of two size fixed it.  Strange!

**Comment by cheeze42** [comment] 2022-01-03 02:30
I also ran into this today, and found another (similar) example of it cropping up:

```zig
const Foo = packed struct {
    arr: [6]u8
};

pub fn main() anyerror!void {
    var bar: Foo = undefined;
    for (bar.arr) |item| {
        _ = item;
    }
}
```

...which also gives the following error, when the struct is packed and the array size isn't a power of 2:
```
.\src\testing.zig:7:5: error: unable to evaluate constant expression
    for (bar.arr) |item| {
    ^
```

**Comment by nektro** [comment] 2022-10-16 06:23
stage2 packed structs are not allowed to contain array fields

**Comment by andrewrk** [comment] 2022-12-27 21:20
Currently this outputs:

```
$ stage4/bin/zig test test.zig 
test.zig:6:5: error: packed structs cannot contain fields of type '[3]u8'
    bytes: [3]u8,
    ^~~~~~~~~~~~
test.zig:6:5: note: type has no guaranteed in-memory representation
```

The note is incorrect; arrays do have a guaranteed in-memory representation.

**Comment by Vexu** [comment] 2023-01-10 13:30
Closing as duplicate of #12547

**Closed by Vexu** 2023-01-10 13:30 UTC
Labels: bug, stage2, error message
