### ISSUE TITLE
Zig standard library should adhere to the "Avoid Redundancy in Names" langref guide

### ISSUE THREAD

**Issue by linusg** [ziglang/zig#21734] opened 2024-10-17 12:50 UTC
### Zig Version

0.14.0-dev.1924+bdd3bc056

### Steps to Reproduce and Observed Behavior

Some examples:

- https://github.com/search?q=repo%3Aziglang%2Fzig+%22Context%3A+type%22+language%3AZig+path%3A%2F%5Elib%5C%2Fstd%5C%2F%2F&type=code
- https://github.com/search?q=repo%3Aziglang%2Fzig+%22Context+%3D+struct%22+language%3AZig+path%3A%2F%5Elib%5C%2Fstd%5C%2F%2F&type=code
- https://github.com/search?q=repo%3Aziglang%2Fzig+%22Data+%3D+struct%22+language%3AZig+path%3A%2F%5Elib%5C%2Fstd%5C%2F%2F&type=code
- https://github.com/search?q=repo%3Aziglang%2Fzig+%22Manager+%3D+struct%22+language%3AZig+path%3A%2F%5Elib%5C%2Fstd%5C%2F%2F&type=code

### Expected Behavior

The Zig standard library should serve as idiomatic example code for people learning Zig: in terms of how patterns are used, code is structured, things are named.

Naming things is hard and fixing the above will give others inspiration for moving away from generic names in their own code. Remaining violations of the rule can serve as legitimate examples for allowed exceptions.

**Comment by andrewrk** [comment] 2024-10-17 19:13
duplicate of #1629. if you want to fix something specifically, open a PR please

**Closed by andrewrk** 2024-10-17 19:13 UTC
Labels: standard library

**Comment by linusg** [comment] 2024-10-17 20:07
I would, but I'm just as guilty of using generic names like "context" in my own code and have a hard time coming up with better names - hence why I hope to get some inspiration from when these are fixed :)

I think you underestimate how many people find this difficult, please consider also suggesting improved names when pointing out violations as in https://github.com/ziglang/zig/pull/21713#discussion_r1802091877
