### ISSUE TITLE
C import of flag enum hits compile error for last bit flag (0x80000000)

### ISSUE THREAD

**Issue by Bekwnn** [ziglang/zig#9038] opened 2021-06-07 22:51 UTC
Experienced compiling with 0.8.0 release on windows.
```
.\zig-cache\o\86fe56bc69f3f2f12049d6f5e182d30e\cimport.zig:31644:34: error: integer value 2147483648 cannot be coerced to type 'c_int'
    aiProcess_GenBoundingBoxes = 2147483648,
                                 ^
```
The relevant enum definition goes,
```
enum aiPostProcessSteps
{
    aiProcess_CalcTangentSpace = 0x1,
    // . . .
    aiProcess_GenBoundingBoxes = 0x80000000
};
```

Line/code from the assimp project:
[https://github.com/assimp/assimp/blob/950495753493f6d4f62f2b2e24dff930c5b83bd4/include/assimp/postprocess.h#L605](https://github.com/assimp/assimp/blob/950495753493f6d4f62f2b2e24dff930c5b83bd4/include/assimp/postprocess.h#L605)

Wasn't experiencing it on windows-0.8.0-dev.1471+4e9894cfc

**Comment by Vexu** [comment] 2021-06-08 05:02
Duplicate of #8003.

**Closed by Vexu** 2021-06-08 05:02 UTC
