### ISSUE TITLE
Compiler error missing when `defer` used in `noreturn` scope 

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#19434] opened 2024-03-26 00:13 UTC
### Zig Version

0.12.0-dev.1830+779b8e259

### Steps to Reproduce and Observed Behavior

1. Code:
```zig
pub fn bye() noreturn {
    defer std.debug.print("\nThis will never be printed!\n", .{}); 
    std.os.exit(0);
}
const std = @import("std");
test {
    bye();
}
```
2. Run `zig test repro.zig`
3. Output:
```zig
❯ zig test /Users/jarred/Desktop/repro.zig
Test [1/1] test_0... ⏎                                                                                                             
```

### Expected Behavior

zig should emit a compiler error for using `defer` in a scope with `noreturn` and no errors. The `defer` can never be reached, therefore it is always a mistake for the programmer to use it

Related: https://github.com/oven-sh/bun/pull/9630#discussion_r1538387782

**Comment by paperdave** [comment] 2024-03-26 00:16
defer here is not analyzed at all, which leads to
`defer @compileError("lol");`
compiling fine

**Comment by ianprime0509** [comment] 2024-03-26 01:21
This seems like a duplicate of #5721.

**Closed** 2024-03-26 08:54 UTC
Labels: bug
