### ISSUE TITLE
`@call(.always_inline)` on a @ptrCast'd comptime-known function ignores the cast at the call site

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#18782] opened 2024-02-02 07:53 UTC
### Zig Version

0.12.0-dev.1830+779b8e259

### Steps to Reproduce and Observed Behavior

1. Code
```zig
pub fn C(comptime function: *const fn (*anyopaque) bool) type {
    return struct {
        a: *anyopaque,
        pub fn b(this: @This()) bool {
            return @call(.always_inline, function, .{this.a});
        }

        // works:
        pub fn works(this: @This()) bool {
            return function(this.a);
        }
    };
}

const D = struct {
    e: bool = true,
    pub fn f(this: *@This()) bool {
        return this.e;
    }
};

test {
    var d: D = .{};

    const c = C(@ptrCast(&D.f));

    var x: c = .{ .a = &d };
    const std = @import("std");

    try std.testing.expectEqual(x.works(), true);

    // does not work:
    try std.testing.expectEqual(x.b(), true);

 //Users/jarred/Desktop/repro.zig:18:20: error: type '*anyopaque' does not support field access
}

```

2. Run
```zig
zig test repro.zig
```

3. Error
```zig
repro.zig:18:20: error: type '*anyopaque' does not support field access
        return this.e;
               ~~~~^~
repro.zig:5:20: note: called from here
            return @call(.always_inline, function, .{this.a});
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    test_0: repro.zig:33:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

it should not return a compiler error

**Comment by Vexu** [comment] 2024-02-02 09:55
Duplicate of #18113

**Closed by Vexu** 2024-02-02 09:55 UTC
Labels: bug
