### ISSUE TITLE
std.sort.block anonymous struct

### ISSUE THREAD

**Issue by StringNick** [ziglang/zig#21244] opened 2024-08-29 19:12 UTC
### Zig Version

0.14.0-dev.1342+1a178d499

### Steps to Reproduce and Observed Behavior

Maybe its not a bug and anonymous struct is not allowed to use.
```
const std = @import("std");

pub fn compare(_: void, lhs: struct {u64}, rhs: struct{u64}) bool {
    return lhs[0] < rhs[0];
}


test "dfd"  {
    var d = std.ArrayList(struct{u64}).init(std.testing.allocator);
    defer d.deinit();
    
    try d.appendSlice(&.{ .{5}, .{1}, .{3}});
    
    std.sort.block(struct{u64}, d.items, {}, compare);
}
```
returning just failure with status 139 (without any error info)
but if we remove anonymous decl, and add type everything works:
```
const std = @import("std");

pub fn compare(_: void, lhs: tt, rhs: tt) bool {
    return lhs[0] < rhs[0];
}

const tt = struct {u64};


test "dfd"  {
    var d = std.ArrayList(tt).init(std.testing.allocator);
    defer d.deinit();
    
    try d.appendSlice(&.{ .{5}, .{1}, .{3}});
    
    std.sort.block(tt, d.items, {}, compare);
}
```

### Expected Behavior

Working behavior

**Comment by xdBronch** [comment] 2024-08-29 19:18
duplicate of https://github.com/ziglang/zig/issues/20759

**Closed** 2024-09-01 14:35 UTC
Labels: bug
