### ISSUE TITLE
add `@Here()` builtin for in-situ reference of known destination Type

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#20236] opened 2024-06-08 09:06 UTC
This provides an alternative for usecase 1A and 2A in the accepted proposal #9938 to reduce its scope (and complexity debt) down to just the addition of a streamlined union-literal syntax without changing the current rules for explicit location inference of enum literals or imposing the namespace restriction described in @mlugg's [acceptance notice.](https://github.com/ziglang/zig/issues/9938#issuecomment-2132570565)

From what I could see, the crux of the proposal was a need to access the destination namespace at callsite, in order to DRY destination types that are already explicitly known anyways.

The streamlining of union-literals in the original proposal seems to be adjacent to the motivation of callsite-type access, they are only syntactically related by the fact that Zig uses the same symbol for namespaced declarations and field access, but conceptually they are really two separate proposals. 

By making the inferred namespace-access functionality into a builtin instead of a change to the syntax, not only is the functionality achieved with significantly less syntactic complexity, it also decouples the two disparate motivations of the original proposal into separate changes that can be evaluated on their individual merit.

# Usecase demonstration

## 1A

```zig
const DeloreanOptions = packed struct {
    enable_flux_capacitor: bool,
    target_speed_mph: u7,
    enable_remote_control: bool = false,

    pub const time_travel: DeloreanOptions = .{
        .enable_flux_capacitor = true,
        .target_speed_mph = 88,
    };

    pub const highway: DeloreanOptions = .{
        .enable_flux_capacitor = false,
        .target_speed_mph = 60,
    };
};

pub fn startDelorean(options: DeloreanOptions) void { ... }

test {
    // invoke declarations in the namespace of the known result type
    startDelorean(@Here().time_travel);

    // The originally proposed late-binding proposal was omitted from the accepted version
    //// const highway_literal = .highway;
    //// startDelorean(highway_literal);

    // explicit instantiation of the location type works as expected
    startDelorean(.{
        .enable_flux_capacitor = true,
        .target_speed_mph = 88,
        .enable_remote_control = true,
    })
}
```

## 2A

```zig
var array_1: std.ArrayList(u32) = @Here().init(allocator); // forward declaration
var array_2 = @as(std.ArrayList(u32), @Here().init(allocator)); // inferred by @as
```

Using `@Here()` without an explicit result type will produce an error:
```zig
// error: @Here must have a known result type
var array_3 = @Here().init(allocator);
//            ^~~~~~~~~~~~~~~~~~~~~~~
// note: use @as to provide explicit result type


// error: @Here cannot infer from anytype
const ipi = math.complex.log(@Here().init(-1, 0));
//                           ^~~~~~~~~~~~~~~~~~~
// note: use @as to provide explicit result type
```

**Comment by nektro** [comment] 2024-06-08 10:27
seems like a duplicate of https://github.com/ziglang/zig/issues/16313

**Comment by mlugg** [comment] 2024-06-08 14:32
> Likewise this builtin *captures* its destination constraint and presents it for availability at invocation.

No, this builtin is different. Builtins like `@enumFromInt` utilize the result type they are provided; other than that, they work as atomic expressions. I can write `@enumFromInt(...)` in any expression which is forwarded a result type. In contrast, `@Here()` isn't interested in its own result type, because it doesn't receive one. If you consider a general field access `foo.bar`, knowing the type we expect from the field access tells us nothing about what type `foo` must be, so we can't propagate type information here; just the same, in `@Here().bar`, we can't propagate any type information to `@Here()`. Instead, the compiler will have to pick up on the *syntax form* `@Here().foo`, and treat it specially.

**Comment by mlugg** [comment] 2024-06-09 18:02
`@This()` is completely orthogonal to the result location mechanism; it just has a separate well-defined behavior which is to return the innermost enclosing namespace type (aka, the type of the current namespace). That isn't relevant here, since the proposed `@Here()` explicitly *is* to do with result types, it just uses the result type of a different expression.

**Comment by mlugg** [comment] 2024-09-02 00:17
Rejected in favour of #9938.

**Closed by mlugg** 2024-09-02 00:17 UTC
Labels: proposal
