### ISSUE TITLE
Enum generic over tag type crashes compiler

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#14195] opened 2023-01-04 15:35 UTC
### Zig Version

0.11.0-dev.1175+abd005f30

### Steps to Reproduce and Observed Behavior

```zig
// test.zig
const std = @import("std");

fn Int(comptime Inner: type) type {
    return enum(Inner) { _ };
}

test "Int" {
    const i = @intToEnum(Int(u32), 0);
    try std.testing.expect(@enumToInt(i) == 0);
}
```

```
$ zig test test.zig
Segmentation fault (core dumped)
```

### Expected Behavior

Compiles and test passes

**Comment by Vexu** [comment] 2023-01-04 16:09
Duplicate of #12272

**Closed by Vexu** 2023-01-04 16:09 UTC
Labels: bug
