### ISSUE TITLE
type 'void' does not support struct initialization syntax

### ISSUE THREAD

**Issue by pfgithub** [ziglang/zig#7575] opened 2020-12-28 10:36 UTC
This used to work but doesn't anymore (using 0.7.1+d96f5b38a but it broke before that)

```zig
test "" {
    _ = struct { a: u32 }{ .a = 25 };
}
```
```zig
./test.zig:2:28: error: type 'void' does not support struct initialization syntax
    _ = struct { a: u32 }{ .a = 25 };
                           ^
```

This error also occurs with
```zig
const a: void = struct { a: u32 }{ .a = 25 };
```
which doesn't make any sense because I would expect an error like more like
```zig
./test.zig:2:21: error: expected type 'void', found 'struct { a: u32 }'
```

**Comment by Vexu** [comment] 2020-12-28 11:20
Duplicate of #3054.

**Closed by Vexu** 2020-12-28 11:20 UTC
