### ISSUE TITLE
Dependency loop with function pointers and structs including them

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#5499] opened 2020-06-01 00:37 UTC
```zig
pub const Function = fn (*const Struct) callconv(.C) void;

pub const Struct = extern struct {
    a: fn (Function) callconv(.C) void,
};

comptime {
    @import("std").meta.refAllDecls(@This());
}
```

Reduced from [VapourSynth.h](https://github.com/vapoursynth/vapoursynth/blob/master/include/VapourSynth.h).

**Comment by Vexu** [comment] 2020-06-01 11:42
Duplicate of  #4476

**Closed by Vexu** 2020-06-01 11:42 UTC
