### ISSUE TITLE
`// zig fmt: on` isn't recognized at tuple literal end

### ISSUE THREAD

**Issue by Des-Nerger** [ziglang/zig#20300] opened 2024-06-15 00:09 UTC
### Zig Version

0.14.0-dev.32+4aa15440c

### Steps to Reproduce and Observed Behavior

Input code:
```zig
const _ = .{
    //zig fmt: off
    .{-1},
    .{ 0},
    //zig fmt: on
};
```
Observed output code after running `$ zig fmt`:
```zig
const _ = .{
    // zig fmt: off
    .{-1},
    .{ 0},
    //zig fmt: on
};
```

### Expected Behavior

Expected `$ zig fmt` output:
```zig
const _ = .{
    // zig fmt: off
    .{-1},
    .{ 0},
    // zig fmt: on
};
```

**Comment by xdBronch** [comment] 2024-06-15 00:11
duplicate of #10418

**Comment by Des-Nerger** [comment] 2024-06-15 00:17
@xdBronch, oops, my bad. Thanks.

**Closed** 2024-06-15 00:18 UTC
Labels: bug
