### ISSUE TITLE
translate-c fails in <sys/mman.h>

### ISSUE THREAD

**Issue by Shemar-Mc** [ziglang/zig#8201] opened 2021-03-10 19:11 UTC
demonstrative code

```zig
const c = @cImport({
    @cInclude("sys/mman.h");
});

test "c-translate" {
    _ = c.MAP_FAILED;
}
```

run `zig test  -target x86_64-linux -lc ./file.zig`

output
```
.\zig-cache\o\82a950f45adaa215e27d442d1bde3099\cimport.zig:368:35: error: integer value 1 cannot be coerced to type 'type'
pub const MAP_FAILED = ?*c_void - 1;
                                  ^
.\zig-cache\o\82a950f45adaa215e27d442d1bde3099\cimport.zig:368:33: note: referenced here
pub const MAP_FAILED = ?*c_void - 1;
                                ^
.\problem.zig:6:10: note: referenced here
    _ = c.MAP_FAILED;
         ^
```

**Comment by fengb** [comment] 2021-03-10 19:40
Problematic line in question:
```c
#define MAP_FAILED	((void *) -1)
```

**Comment by Vexu** [comment] 2021-03-10 21:39
Duplicate of #4071.

**Closed by Vexu** 2021-03-10 21:39 UTC
Labels: bug, translate-c
