### ISSUE TITLE
Looping over global undefined var slice is no error on debug

### ISSUE THREAD

**Issue by GigaGrunch** [ziglang/zig#20703] opened 2024-07-21 07:51 UTC
### Zig Version

0.14.0-dev.367+a57479afc

### Steps to Reproduce and Observed Behavior

Originially discovered with Zig 0.13.0, but verified that it's still the same on 0.14.0-dev.367+a57479afc. This might be related to https://github.com/ziglang/zig/issues/19798, but it doesn't seem to be a direct duplicate at least.

```
var undefined_slice: []u8 = undefined;

pub fn main() !void {
    for (undefined_slice) |char| {
        std.debug.print("{c}", .{char});
    }
}
```

This code compiles without any errors. On debug, it even _runs_ without any errors. On any release mode, it will crash at runtime with a segmentation fault. When that variable is in local scope instead of global scope, the compiler aborts with a `General protection exception (no address available)`.

### Expected Behavior

~~The compiler should fail the build for the global variable, same as for the local variable.~~ @nektro pointed out that the compiler doesn't know about the undefined-ness here. In that case, it should at least ensure that the code crashes in debug already. I actually had this bug sitting in my codebase until @marler8997 stumbled over it in his live stream code review session.

**Comment by nektro** [comment] 2024-07-21 08:01
it being `var` means its undefined-ness is not comptime-known. this is just [Unchecked Illegal Behavior](https://ziglang.org/documentation/master/#Undefined-Behavior) afaict.

**Comment by GigaGrunch** [comment] 2024-07-21 08:07
Ah, thanks for pointing this out! In that case, I'm just expecting a runtime crash in debug builds.

**Comment by rohlem** [comment] 2024-07-21 08:53
A safety check for this scenario might be subsumed by the general "undefined value" safety check proposed in https://github.com/ziglang/zig/issues/211 .

**Comment by nektro** [comment] 2024-07-21 09:09
im very surprised this doesnt crash in debug mode already

**Comment by nektro** [comment] 2024-07-21 09:11
adding `std.log.warn("{d} {d}", .{ @intFromPtr(undefined_slice.ptr), undefined_slice.len });` prints `warning: 0 0`. that feels like the bug here

**Comment by nektro** [comment] 2024-07-21 09:12
if folks agree that makes this a duplicate of https://github.com/ziglang/zig/issues/1987

**Comment by nektro** [comment] 2024-07-21 09:14
putting it on the stack does the expected:

```
warning: 12297829382473034410 12297829382473034410
Segmentation fault at address 0xaaaaaaaaaaaaaaaa
```

**Closed** 2024-07-21 10:51 UTC
Labels: bug
