### ISSUE TITLE
Can't have var with same name as const in block on top level

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#14697] opened 2023-02-21 17:53 UTC
### Zig Version

0.11.0-dev.1711+dc1f50e50

### Steps to Reproduce and Observed Behavior

```zig
const x = x: {
    var x: u8 = 0;
    x += 1;
    break :x x;
};

test {}
```
Doesn't work:
```
$ zig test x.zig
x.zig:2:9: error: local variable shadows declaration of 'x'
    var x: u8 = 0;
        ^
x.zig:1:1: note: declared here
const x = x: {
^~~~~
```
```zig
test {
    const x = x: {
        var x: u8 = 0;
        x += 1;
        break :x x;
    };
    _ = x;
}
```
Works:
```
$ zig test x.zig
All 1 tests passed.
```
I think this inconsistency is bad and should be resolved. In the block of the var, the const `x` is *not* already fully declared and it should allow me to do the same thing as in the `test` block.

### Expected Behavior

The same as when `x` is in the `test` block.

**Comment by Vexu** [comment] 2023-02-21 18:24
Duplicate of #13877

**Closed by Vexu** 2023-02-21 18:24 UTC
Labels: bug
