### ISSUE TITLE
Cannot build-exe with object files and generate executable file on windows

### ISSUE THREAD

**Issue by waruqi** [ziglang/zig#5825] opened 2020-07-09 01:48 UTC
I run `zig.exe build-exe --object xxx.obj` command, it cannot generate any executable file.

zig: master version

```console
y:\zig\zig.exe build-obj --release-fast -target x86_64-windows-msvc --output-dir build\.objs\test\windows\x64\release\src --name main.zig src\main.zig

y:\zig\zig.exe build-exe --strip -target x86_64-windows-msvc --output-dir build\windows\x64\release --name test --object build\.objs\test\windows\x64\release\src\main.zig.obj

Build Dependencies...compiler_rt...Initialize...
```

**Comment by alexnask** [comment] 2020-11-09 17:58
I cannot reproduce this on master with the new CLI (on both Linux and Windows hosts), closing.

**Comment by waruqi** [comment] 2020-11-10 08:43
I tried version 0.7.0, the obj file can be generated normally, but the link to the executable file still fails, and there is no error output

```console
[ 40%]: compiling.release src\main.zig
y:\zig\zig.exe build-obj -target x86_64-windows-msvc -O ReleaseFast -femit-bin=build\.objs\test\windows\x64\release\src\main.zig.obj src\main.zig
[ 60%]: compiling.release src\test.zig
y:\zig\zig.exe build-obj -target x86_64-windows-msvc -O ReleaseFast -femit-bin=build\.objs\test\windows\x64\release\src\test.zig.obj src\test.zig
[ 80%]: linking.release test.exe
y:\zig\zig.exe build-exe -target x86_64-windows-msvc --strip -femit-bin=build\windows\x64\release\test.exe build\.objs\test\windows\x64\release\src\main.zig.obj build\.objs\test\windows\x64\release\src\test.zig.obj
error: runv(y:\zig\zig.exe build-exe -target x86_64-windows-msvc --strip -femit-bin=build\windows\x64\release\test.exe build\.objs\test\windows\x64\release\src\main.zig.obj build\.objs\test\windows\x64\release\src\test.zig.obj) failed(1)
```

I execute the link command alone without any output.

```console
y:\zig\zig.exe build-exe -target x86_64-windows-msvc --strip -femit-bin=build\windows\x64\release\test.exe build\.objs\test\windows\x64\release\src\main.zig.obj build\.objs\test\windows\x64\release\src\test.zig.obj
```

**Comment by alexnask** [comment] 2020-11-10 08:46
@waruqi 
Can you point me to the example you are using?  
I tried this with basically the exact same commands both on linux (cross compiling for gnu windows) and on windows (compiling for msvc windows)

**Comment by waruqi** [comment] 2020-11-10 09:09
example project: https://github.com/xmake-io/xmake/tree/dev/tests/projects/zig/console

Please download xmake-latest.win64.exe install package to install xmake (dev version) from https://github.com/xmake-io/xmake/actions/runs/355512412

```console
$ git clone https://github.com/xmake-io/xmake.git 
$ cd xmake/tests/projects/zig/console
# configure zig bin path
$ xmake f --zc=f:\xxx\zig.exe -c
# do build and show verbose info
$ xmake -rvD
```

**Comment by alexnask** [comment] 2020-11-10 09:11
Thanks, will take a look right now and reopen and investigate the bug if necessary

**Comment by waruqi** [comment] 2020-11-10 09:11
Ok, thanks.

**Comment by alexnask** [comment] 2020-11-10 09:47
Hmm, my apologies, this does seem to be broken, I dont know how I got around it yesterday.  
Looking into it now

**Comment by alexnask** [comment] 2020-11-10 16:07
Unfortunately this looks like it is an LLD bug (I think somewhere in lld::link::coff, exit(1) is called)
Trying to verify this now somehow

**Comment by alexnask** [comment] 2020-11-10 16:35
@waruqi 
Apparently we are not passing a default subsystem to the linker when calling into LLD, which causes it to error.  
A separate bug in the compiler means the error from lld was not printed out.  
You can fix this by adding `--subsystem console` to the command (as well as `-lkernel32`, `-lntdll` for the winapi symbols used by the program).  

I suppose those should be added by default as well.  

I will fix the compiler to either use a default subsystem or emit a compiler error in cases when no zig file is compiled, but only objet files.

**Comment by waruqi** [comment] 2020-11-10 22:42
> If you need a temporary workaround, you can fix this by adding --subsystem console to the command (as well as -lkernel32, -lntdll for the winapi symbols used by the program).

ok, I will try it first. thanks.

**Comment by waruqi** [comment] 2020-11-11 01:20
> If you need a temporary workaround, you can fix this by adding --subsystem console to the command (as well as -lkernel32, -lntdll for the winapi symbols used by the program).

This temporary workaround works, thanks.  `--subsystem console -lkernel32, -lntdll`

But when I tried to continue to build dynamic and static libraries, two other problems appeared. 

#### undefined symbol: _DllMainCRTStartup when I use zig build-lib --dynamic to generate dynamic library on windows 
https://github.com/ziglang/zig/issues/7065

#### It crashes when I use zig build-lib to generate static library for msvc on windows 
https://github.com/ziglang/zig/issues/7066

**Comment by andrewrk** [comment] 2020-12-11 20:21
> Unfortunately this looks like an LLD bug (I think somewhere in lld:link:coff, exit(1) is called)
> Trying to verify this now somehow

This was #3825 which is now resolved.

>  Apparently we are not passing a default subsystem to the linker when calling into LLD, which causes it to error.

When `zig build-exe foo.zig` is used, zig can determine the subsystem based on the presence of `main`, `wWinMainCRTStartup`, `wWinMain`, etc.

When using build-obj to produce an object, and then using `build-exe` with only an object file, zig relies on the user to specify the subsystem. The current behavior is:

```
zig build-exe hello.obj -target x86_64-windows-msvc
lld-link: error: subsystem must be defined
```

What is the expected subsystem in this case?

In the meantime, can be solved with an explicit `--subsystem` flag:

```
zig build-exe hello.obj -target x86_64-windows-msvc --subsystem console
```

> as well as `-lkernel32`, `-lntdll` for the winapi symbols used by the program).
> 
> I suppose those should be added by default as well.

l don't think they should be added by default. What happens when you use `zig build-exe hello.zig` is that zig keeps track of which DLLs are needed, and puts them on the linker line automatically. When going through objects, `build-exe hello.obj` does not know which DLLs the object needs. So the user must provide them:

```
zig build-exe hello.obj -target x86_64-windows-msvc --subsystem console -lkernel32 -lntdll
```

And now (with the additional bug fix #7401) we have a viable executable:

```
> hello.exe
Hello, World!
```

**Comment by andrewrk** [comment] 2020-12-11 20:50
I believe this issue is solved once #7401 lands. I will look at #7065 and #7066 now.

Proposals to adjust the behavior regarding default subsystem selection are welcome.

However `build-exe` will not default to always link any libraries (such as kernel32 or ntdll). Zig users are encouraged to use `build-exe` in combination with Zig source files where possible, rather than forcing zig to go through object files, because it limits the amount of information Zig has to make compilation and linking decisions.

**Closed** 2020-12-11 23:34 UTC
Labels: bug, contributor friendly, os-windows, stage2

**Comment by waruqi** [comment] 2020-12-12 01:48
> However build-exe will not default to always link any libraries (such as kernel32 or ntdll). Zig users are encouraged to use build-exe in combination with Zig source files where possible, rather than forcing zig to go through object files, because it limits the amount of information Zig has to make compilation and linking decisions.

Thank you, I understand that it is reasonable if users use zig as the build system.

But this does not seem to be too friendly for other build systems. Like c/c++, usually gcc/clang and other compilers only compile source files to generate object files, while linkers only accept object files as input. This isolation allows the build system to handle compilation and linking more conveniently, which can also help the build system achieve better parallel compilation.

I think it is possible to let zig build-exe obtain the required zig source file information by passing additional intermediate files or caches.

**Comment by andrewrk** [comment] 2020-12-12 01:53
The problem is that the object file could have come from a different compiler, other than Zig, in which case we will be in the same situation as we are now, not knowing what we should or should not link to.

Please note that if you link libc (for example with `-lc`) then Zig will pull in these libs:

https://github.com/ziglang/zig/blob/d569e37cb538d17d009f5632c25acd643d3736cb/src/mingw.zig#L1098-L1105

Most C compilers assume linking against libc, but Zig does not.

**Comment by waruqi** [comment] 2020-12-12 02:03
And it can better achieve mixed compilation with other language files. Through the obj file isolation, we can conveniently set different compilation options to c/c++ files.

> The problem is that the object file could have come from a different compiler, other than Zig, in which case we will be in the same situation as we are now, not knowing what we should or should not link to.

ok, If zig does not know, the build system or users can help to additionally set these link libraries to zig build-exe

I hope that zig build-exe can have an optional mode so that it can only be used as an obj linker. Similarly, zig build-lib can only be used as static lib archiver or dynamic library linker, without passing zig source files as input.

**Comment by andrewrk** [comment] 2020-12-12 02:07
> I hope that zig build-exe can have an optional mode so that it can only be used as an obj linker. Similarly, zig build-lib can only be used as static lib archiver or dynamic library linker, without passing zig source files as input.

Yes, this is a supported use case. However it is a more advanced use case, so it requires the user (or build system) to pass flags to decide the subsystem and flags to decide which libraries to link. If you have suggestions for how Zig can figure out the subsystem and libraries to link without being told via command line flags, I would like to hear them.

**Comment by waruqi** [comment] 2020-12-12 02:26
> Yes, this is a supported use case. However it is a more advanced use case, so it requires the user (or build system) to pass flags to decide the subsystem and flags to decide which libraries to link. 

Ok, I will let xmake to pass these flags.

> If you have suggestions for how Zig can figure out the subsystem and libraries to link without being told via command line flags, I would like to hear them.

Is a subsystem set by default? For example, subsystem:console by default, and then build the system or users can modify it by setting -subsystem?

I seem to see that when msvc compiles c/c++, it only sets the subsystem at link time. Maybe I remembered it wrong, I will confirm it later.

**Comment by waruqi** [comment] 2020-12-12 08:59
I confirm that when I set `-subsystem` to zig build-exe, it works fine. thanks!
