### ISSUE TITLE
Saturating integer add/sub intrinsics/ops?

### ISSUE THREAD

**Issue by scottjmaddox** [ziglang/zig#4109] opened 2020-01-08 04:54 UTC
As far as I can tell from searching the documentation, there is currently no support for saturating integer add/sub built in to Zig. I find them extremely useful in Rust (i.e. the `saturating_add` and `saturating_sub` methods defined on integer types). For the sake of completeness, it would be awesome if there were built-in support in Zig, either in the form of intrinsic functions or in the form of operators. Note that [LLVM provides the necessary intrinsics](https://llvm.org/docs/LangRef.html#saturation-arithmetic-intrinsics).

If operators were desired, perhaps `+|` and `-|` would be good choices? They follow the same basic pattern as wrapping add/sub (`+%`/`-%`), and the bar, `|`, can be visually interpreted as a the saturation "wall".

**Comment by daurnimator** [comment] 2020-01-08 04:57
Duplicate of #1284

**Closed by daurnimator** 2020-01-08 04:57 UTC
