### ISSUE TITLE
Inline functions do not correctly propagate comptime values through return expressions

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#16361] opened 2023-07-08 17:27 UTC
### Zig Version

0.11.0-dev.3892+0a6cd257b

### Steps to Reproduce and Observed Behavior

```zig
const E = enum { a, b };

inline fn f(x: E) E {
    //if (x == .a) return .b else return .a;
    return if (x == .a) .b else .a;
}

test {
    @compileLog(f(.a));
}
```
```
$ zig test foo.zig
foo.zig:9:5: error: found compile log statement
    @compileLog(f(.a));
    ^~~~~~~~~~~~~~~~~~

Compile Log Output:
@as(foo.E, [runtime value])
```

### Expected Behavior

The return value should be comptime known, since `f` is inline:
```
Compile Log Output:
@as(foo.E, .b);
```
Note that if `f`'s body is replaced with the commented-out line, which puts the `return` inside the conditional branches, we get the correct behavior.

**Comment by Vexu** [comment] 2023-07-08 17:45
Duplicate of #12108

**Closed by Vexu** 2023-07-08 17:45 UTC
Labels: bug
