### ISSUE TITLE
pub fn main() !noreturn crashes the compiler

### ISSUE THREAD

**Issue by WoodyAtHome** [ziglang/zig#6181] opened 2020-08-27 18:51 UTC
```
pub fn main() !noreturn {
    while (true){

    }
}
```
then
`zig build-exe main.zig`

Sometimes the compiler gives an error, sometimes it doesn't stop on my machine and the hole machine is unusable. Only Power off helped.

zig version 0.6.0+fc001110b
ubuntu 20.04.1

**Comment by alexnask** [comment] 2020-08-27 18:54
Duplicate of #3461

**Closed** 2020-08-27 19:00 UTC
