### ISSUE TITLE
build.LibExeObjStep.strip is not working?

### ISSUE THREAD

**Issue by hronro** [ziglang/zig#9026] opened 2021-06-07 06:39 UTC
Steps to reproduce:

1. mkdir hello && cd hello && zig init-exe
1. add a new line `exe.strip = true;` in `build.zig`
1. run `zig build -Drelease-fast`
1. run `file zig-out/bin/hello`

Output is:

```
zig-out/bin/hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

Zig version: 0.8.0
OS version: Linux ArchLinux 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux

**Comment by LemonBoy** [comment] 2021-06-07 07:14
`strip` here means "tell the compiler not to emit any debug info", slightly different than objcopy's `--strip` definition and perhaps closer to `--strip-debug`.

**Comment by andrewrk** [comment] 2021-06-09 21:46
duplicate of #351

**Closed by andrewrk** 2021-06-09 21:46 UTC
