### ISSUE TITLE
`cond1 and cond2` not comptime-known when cond2 is comptime-known to be `false`

### ISSUE THREAD

**Issue by topolarity** [ziglang/zig#13341] opened 2022-10-29 00:13 UTC
### Zig Version

0.10.0-dev.4622+f28e4e03e

### Steps to Reproduce and Observed Behavior

```zig
test {
    var cond: bool = false;
    if (cond and false) {
        @compileError("this should never execute");
    }
}
```
```console
./test_cond.zig:5:9: error: this should never execute
        @compileError("this should never execute");
        ^
```

### Expected Behavior

Zig should evaluate the preceding arguments at runtime so that their side-effects are observed, and then treat this as a compile-time known conditional so that the compile error is not triggered.

**Comment by andrewrk** [comment] 2022-10-29 00:17
Duplicate of #6768

**Closed by andrewrk** 2022-10-29 00:17 UTC
Labels: bug, stage2, stage1
