### ISSUE TITLE
make ArrayList.replaceRange to support any overlap

### ISSUE THREAD

**Issue by maxzhao** [ziglang/zig#16125] opened 2023-06-21 02:33 UTC
### Zig Version

0.11 master version b77679039fd40aa1693781f99ac89f2dc705e5c2

### Steps to Reproduce and Observed Behavior

``` zig
 /// trimLeft removes `str` from the left of this Zigstr, mutating it.
pub fn trimLeft(self: *Self, str: []const u8) !void {
    var list = try self.list.asList();
    const trimmed = mem.trimLeft(u8, list.items, str);
    try list.replaceRange(0, list.items.len, trimmed);
}
```
above code from Zigstr run's error:
```
 thread 31108 panic: @memcpy arguments alias
std\array_list.zig:193:30: 0x7ff772c6582f in replaceRange (test.exe.obj)
                @memcpy(range[0..new_items.len], new_items); 
```
because `list` and `trimmed` is overlap, but I think this is reasonable。

### Expected Behavior

above code run success. make ArrayList.replaceRange to support any overlap

**Comment by rohlem** [comment] 2023-06-21 08:44
The builtin `@memcpy` assumes that more optimal code can be generated if we assert that there is no overlap.
(In fact, because the function may reallocate, it would require either manually comparing pointer ranges,
 or extending the allocator interface in some way. Either way, the change would be non-trivial.)
It might be better to instead introduce a new method `replaceRangeMayAlias` or `replaceRangeFromSelf` that allows this.

(And maybe clarify the current assertion by renaming the method to `replaceRangeNoAlias`?
 Although other methods like `appendSlice` currently assert the same thing - this might be a larger change.)

**Comment by IntegratedQuantum** [comment] 2023-06-21 13:35
I think there is no need to modify or add functionality to the standard library here.

You are basically trying to remove the first characters.
You could just do this directly:
```zig
try list.replaceRange(0, list.items.len - trimmed.len, &.{});
```

**Comment by matklad** [comment] 2023-06-21 17:20
>I think it would be better to instead introduce a new method replaceRangeMayAlias or replaceRangeFromSelf that allows this.


https://doc.rust-lang.org/stable/std/primitive.slice.html#method.copy_within

**Comment by andrewrk** [comment] 2023-07-23 00:07
Closing due to incomplete bug report. Please fill out "Steps to Reproduce and Observed Behavior" completely and I will re-open.

**Closed by andrewrk** 2023-07-23 00:07 UTC
Labels: standard library
