### ISSUE TITLE
Separate syntax for instance member function calls

### ISSUE THREAD

**Issue by user00e00** [ziglang/zig#3293] opened 2019-09-22 13:26 UTC
Consider the following struct `S`
```zig
const S = struct{
 num : i32,
 fna : fn(S,var) bool,

 const fnb = fn(self : S, param: var) bool{
  // ....
 }
}

const s = S{
 .num = 1,
 .fna = fn(s1 : S, b: var) bool{
   return true;
  }
}
```
Then, in code where instances `s`  of struct `S` are used
```zig
s.num = 53; // OK. This is a struct field
s.fna(3);   // Method or function pointer?
s.fnb(5);   // Method or function pointer?
```

Function pointers and "methods" imply different assumptions and usages, but here that information is hidden from the reader. I believe that is sub-optimal in terms of code readability, even though it's easy to refer to the struct definition whenever there is any ambiguity.

Proposal: Introduce slightly different syntax for instance function pointer calls/invocations.

```zig
// with changes
s.num = 53; // OK -> struct field
s.fnb(5);   // OK -> namespace function called with method syntax
s.fna(&,3); // OK -> function pointer (just one out of many possible syntax alternatives)

// other syntax alternatives for function pointer invocation
s.>fna(3); 
s.:fna(3);
s.fna->(3);
s.&fna(3);
s&.fna(3);
s.fna><(3);
s->fna(3);
```

Counter proposals: 
* Simply create and adhere to a convention, e.g function pointer identifiers should always be
prefixed with `f_`.
* IDEs and editors can use different syntax highlighting for function pointers
* Yet more syntax solely for slightly better readability might not be worth it.
* Change "method" syntax instead. With above example:
```zig
s.num = 53; // OK, struct field
s->fnb(5);   // OK, method call
s.fna(3);     // OK, function pointer invocation
```

**Comment by daurnimator** [comment] 2019-09-22 13:54
Duplicate of #705 I think

**Comment by user00e00** [comment] 2019-09-22 15:04
> Duplicate of #705 I think

Definitely related. I don't know if they are duplicates though.

Additional note:
```zig
Namespace.func();      // calling a namespace member function
instance.funcMethod(); // calling a namespace member function
instance.funcPtr();    // calling a function pointer (odd one out)
```
I feel like the "odd one out" here is the function pointer invocation, while the same assumptions apply to the namespace function and the method. In addition I suspect the usage of namespace "methods" to be more common in code than function pointer invocations. Hence, I would personally prefer the syntax to change on function pointer invocations, not on method calls.

**Comment by daurnimator** [comment] 2019-09-22 23:28
Your proposal here matches what andrewrk has in his comment [here](https://github.com/ziglang/zig/issues/705#issuecomment-472952480) so I'll close as a duplicate.

**Closed by daurnimator** 2019-09-22 23:28 UTC
Labels: duplicate
