### ISSUE TITLE
Segmentation fault compiling store to runtime memory at compile time

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#21304] opened 2024-09-04 04:37 UTC
### Zig Version

0.14.0-dev.1411+a670f5519

### Steps to Reproduce and Observed Behaviour

Compile example program with `zig build-obj comptime_ptr_error_111.zig`
`comptime_ptr_error_111.zig`:
```zig
var u: union { a: void } = undefined;
export fn entry() void {
    u = .{ .a = {} };
}
```
Output:
```
zig build-obj comptime_ptr_error_111.zig
Segmentation fault
```

**Comment by xdBronch** [comment] 2024-09-04 04:49
looks like a duplicate of https://github.com/ziglang/zig/issues/19832

**Comment by amp-59** [comment] 2024-09-04 05:06
> looks like a duplicate of #19832

Thanks.

If any of the others are duplicates please let me know.

**Comment by rohlem** [comment] 2024-09-04 05:44
I don't see what part of the example (global `var` and `export fn` declaration) would be storing to runtime memory at compile time - the issue title currently doesn't quite seem to fit the code example.
(I guess you might have reduced it from a different setup and forgot to update the title?)

**Comment by mlugg** [comment] 2024-09-04 05:48
Duplicate of #19832

**Closed by mlugg** 2024-09-04 05:48 UTC

**Comment by amp-59** [comment] 2024-09-04 06:03
> I don't see what part of the example (global `var` and `export fn` declaration) would be storing to runtime memory at compile time - the issue title currently doesn't quite seem to fit the code example. (I guess you might have reduced it from a different setup and forgot to update the title?)

It is a common oversight in `Sema`. Pointers to global `var` declarations are `comptime`-known, and because of this stores and reads are often attempted without checking whether the memory is also available at compile time.
