### ISSUE TITLE
Optional should not coerce to optional optional as null, if it is null

### ISSUE THREAD

**Issue by ArborealAnole** [ziglang/zig#10555] opened 2022-01-09 18:53 UTC
### Zig Version

0.10.0-dev.108+7c1e17a84

### Steps to Reproduce

    const std = @import("std");
    const print = std.debug.print;
    const builtin = std.builtin;
    
    const A = @Type(.{
        .Struct = .{
            .layout = .Auto,
            .fields = &[_]builtin.TypeInfo.StructField{
                .{ .name = "one", .field_type = ?i32, .default_value = @as(?i32, null), .is_comptime = false, .alignment = 0 },
            },
            .decls = &[_]builtin.TypeInfo.Declaration{},
            .is_tuple = false,
        },
    });
    pub fn main() !void {
        const a: A = .{ }; // error
        // const a: A = .{ .one = null }; // ok
        print("{}\n", .{a});
        print("{}\n", .{@TypeOf(@typeInfo(A).Struct.fields[0].default_value)});
        print("{}\n", .{@typeInfo(A).Struct.fields[0].default_value});
        print("{}\n", .{@TypeOf(@as(?i32, null))});
    }

### Expected Behavior

The optional `?i32` should coerce to a `??i32` but it should not be a `null` `??i32`. Therefore, the default value of the `one` field of `A` should be `null`.

### Actual Behavior

There is no default value for the `one` field in the reified `A`.

**Comment by InKryption** [comment] 2022-01-10 03:47
#7091 Possibly related? Which also looks at not being able to represent a default value when creating a `struct` using `@Type`, but with `undefined`.

**Comment by Vexu** [comment] 2023-01-19 16:47
The example in the issue no longer reproduces the issue due to changes to `std.builtin.Type` but the bug has been fixed in self-hosted.

**Closed by Vexu** 2023-01-19 16:47 UTC
Labels: bug, stage1
