### ISSUE TITLE
For loop range is unusable with types other than usize

### ISSUE THREAD

**Issue by TeamPuzel** [ziglang/zig#17039] opened 2023-09-01 07:59 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

I have this function:

```zig
pub fn sprite(data: *const Sprite, x: u8, y: u8) void {
    std.debug.assert(x <= 127);
    std.debug.assert(y <= 127);
    
    for (data, 0..8) |column, sy| {
        for (column, 0..8) |color, sx| {
            if (x + sx > 127 or y + sy > 127) break;
            const sxc: u8 = @intCast(sx);
            const syc: u8 = @intCast(sy);
            if (color != transparency) pixel(sxc + x, syc + y, color);
        }
    }
}
```
where Sprite is `[8][8]Color`

(Ignore that the function has bugs, that's not really the point 🙂)

Doesn't matter if I use `0..` or `0..8` it still doesn't compile, as the range is seemingly inferred to be usize.

The only way to make it work is to use the two casts as shown in the function above to make the compiler happy.
This is annoying because this range is compile time known, so it should be clear it can fit in a `u8`.

### Expected Behavior

I expected to be able to use `u8` in loops.

**Comment by IntegratedQuantum** [comment] 2023-09-01 08:21
I would also love to have more control over the index type.
However Andrew mentioned [in a related proposal](https://github.com/ziglang/zig/issues/14704#issuecomment-1502516847) that there would be problems with the compiler implementation.

**Comment by TeamPuzel** [comment] 2023-09-01 11:12
Oh well. is the problem just inference? Or is it not even possible to have the choice to manually choose what type the range is?

**Comment by TeamPuzel** [comment] 2023-09-01 11:21
Is there at least no performance cost when using `intCast`?

**Comment by rohlem** [comment] 2023-09-01 13:12
> Is there at least no performance cost when using `@intCast`?

`@intCast` works by employing [safety-checked illegal behavior](https://ziglang.org/documentation/master/#Undefined-Behavior).
(Note: The name "undefined behavior" is remnant C terminology, and inaccurate; the langref should IMO be updated in this regard.)
The short explanation is that the compiler of what behavior you expect (the value should fit into the target type), and other behavior is illegal.

In safe build modes (`Debug` and `ReleaseSafe`) and blocks with explicit safety, the overhead is that if the assumption turns out wrong, `@panic` is triggered, which prints a stack trace and aborts the program.
In unsafe build modes (`ReleaseFast` and `ReleaseSmall`), the compiler is allowed to rely on the assumption. Usually this is used to optimize the program, i.e. the compiler tries to always improve performance, and should never penalize you for stating such assumptions. (This hasn't really been formalized yet though.)

_Technically_ you could find some performance cost for originally allocating the `usize` instead of just the `u8` on the stack, but since `for` loops are language primitives and if there's no other dependency on the value before the cast, it should always be quite trivial for the compiler to see the equivalence in optimized build modes (all but `Debug`).

**Comment by nektro** [comment] 2023-09-01 16:40
@IntegratedQuantum hmm that comment was made before `@min` and `@max` were adjusted to return a result based on the operands too so i wonder if that bodes well for this getting in after all

**Comment by betonowy** [comment] 2024-03-07 20:59
I did find one way to do something similar with comptime, it works for me:

```zig
    fn i32Range(comptime a: i32, comptime b: i32) [b - a]i32 {
        comptime {
            var range = std.mem.zeroes([b - a]i32);
            for (range[0..], 0..) |*v, i| v.* = a + @as(i32, i);
            return range;
        }
    }
    // ...
    // somewhere in code you do this
    inline for (comptime i32Range(-1, 2)) |i| {
        // I guess "i" is now comptime known and is of type "i32"
    }
```

Hope it helps anyone who stumbles in here searching similar issues like I did.

**Comment by Zylann** [comment] 2024-03-30 14:50
I wanted to port this for loop to Zig: https://github.com/Auburn/FastNoiseLite/blob/e545377c6848bc1795b717990aea189770f920b5/Cpp/FastNoiseLite.h#L851

And ended up with this, which is really ugly:
```zig
    for (0..@as(usize, @intCast(self.octaves))) |_| {
```
The capture seems to be required too even though I didn't need it

**Comment by andrewrk** [comment] 2024-08-16 06:59
working as designed; duplicate of #14704.

there is a chance you may get your wish with #3806.

**Closed by andrewrk** 2024-08-16 06:59 UTC
Labels: bug
