### ISSUE TITLE
Compiler crash when defining a function with a (comptime src: std.builtin.SourceLocation)

### ISSUE THREAD

**Issue by roig** [ziglang/zig#13223] opened 2022-10-18 22:17 UTC
### Zig Version

0.10.0-dev.4448+687a7d38a

### Steps to Reproduce

Example to reproduce the crash:
```
const std = @import("std");
pub fn foo(comptime _: std.builtin.SourceLocation) void {
}
pub fn main() !void {
    foo(@src());
}
```

If you remove the **comptime** keyword it works correctly.

### Expected Behavior

I expect it to compile.

### Actual Behavior

The compiler error output:
`C:\dev\bug_zig> zig build run
error: bug_zig...
error: The following command exited with error code 3:
C:\Zig\zig.exe build-exe C:\dev\bug_zig\src\main.zig --cache-dir C:\dev\bug_zig\zig-cache --global-cache-dir C:\Users\Dani\AppData\Local\zig --name bug_zig --enable-cache
error: the following build command failed with exit code 3:
C:\dev\bug_zig\zig-cache\o\a22923fa2aca636f1f82116a3719173d\build.exe C:\Zig\zig.exe C:\dev\bug_zig C:\dev\bug_zig\zig-cache C:\Users\Dani\AppData\Local\zig run`

**Comment by InKryption** [comment] 2022-10-18 22:29
Interestingly it displays the exact same behavior with:
```zig
const std = @import("std");
pub fn foo(comptime src: struct{}) void {
    _ = src;
}
pub fn main() void {
    foo(@src());
}
```
(0.10.0-dev.4450+787788996)

**Comment by Vexu** [comment] 2022-10-18 22:34
Duplicate of #12702

**Closed by Vexu** 2022-10-18 22:34 UTC
Labels: bug
