### ISSUE TITLE
Address of anonymous struct can falsely be passed as a similar, yet incompatible type

### ISSUE THREAD

**Issue by AlxHnr** [ziglang/zig#17971] opened 2023-11-11 21:43 UTC
### Zig Version

0.12.0-dev.1583+97e23896a

### Steps to Reproduce and Observed Behavior

The following code compiles just fine but leads to funky runtime behavior. The anonymous struct has a different, incompatible type from the one expected.

```zig
const std = @import("std");

const Foo = struct { x: u32 };

fn updateFoo(foo: *Foo) void {
    foo.x = 20;
}

pub fn main() void {
    var foo = .{ .x = 10 };
    updateFoo(&foo); // Segfault with 0.11.0
    std.debug.assert(foo.x == 20); // Fails with today's 0.12.0 nightly
}
```

### Expected Behavior

The compiler should reject this code with an error message:

```
main.zig:12:15: error: expected type '*main.Foo', found '*anonymous.struct{ ... }'.
```

**Comment by Vexu** [comment] 2023-11-11 22:17
The compiler is transforming that to something like this:
```zig
var anon: Foo = undefined;
pub fn main() void {
    var foo = .{ .x = 10 };
    anon = foo;
    updateFoo(&anon);
    std.debug.assert(foo.x == 20);
}
```

#13334 is about a sibling coercion of this causing issues so I'll close this as a duplicate of it.

**Closed by Vexu** 2023-11-11 22:17 UTC
Labels: bug
