### ISSUE TITLE
mark some function that can only be called in comptime

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6647] opened 2020-10-11 10:04 UTC
use case: if I forgot to add comptime before std.fmt.comptimePrint, it will randomly crash in runtime because the buffer is large and be placed in stack...
![image](https://user-images.githubusercontent.com/13158903/95675692-a3e75900-0beb-11eb-9ace-e70f2b8430d9.png)

**Comment by Rocknest** [comment] 2020-10-11 11:12
I had a similar problem sometime ago, i think the solution is to put comptime block around the body of the function
```zig
pub fn comptimePrint(comptime fmt: []const u8, args: anytype) *const [count(fmt, args):0]u8 {
    comptime {
        var buf: [count(fmt, args):0]u8 = undefined; 
        _ = bufPrint(&buf, fmt, args) catch unreachable;
        buf[buf.len] = 0;
        return &buf;
    }
}
```

**Comment by andrewrk** [comment] 2020-10-13 03:34
This is a duplicate of #425.

The attached pull request is an OK workaround but the proposal remains. With the workaround there could still be a runtime function call whereas this proposal would make the function always called at compile time.

**Closed** 2020-10-13 06:55 UTC
Labels: proposal
