### ISSUE TITLE
Unable to evaluate constant expression (C interop)

### ISSUE THREAD

**Issue by iotasieve** [ziglang/zig#9548] opened 2021-08-11 12:08 UTC
Hello, I've been doing C interop with zig, and have encountered a problem. I use native `cInclude` and `cImport` functions and compilation fails for a very strange reason. The `DefaultScreen` function accepts a Display, which is the `display` variable declared above. But for some reason the first parameter of `DefaultScreen` is marked as `anytype`, which is strange, and apparently what creates this bizarre error.

```zig
const Xlib = @cImport({
    @cInclude("/usr/include/X11/Xlib.h");
});

const message = "Zig x11 window!";

pub fn main() void {
    var display: ?*Xlib.Display = Xlib.XOpenDisplay(null);
    if (display == null) unreachable;

    var screen = Xlib.DefaultScreen(display); // <- Unable to evaluate constant expression

```
Error logs:
```
/home/ishidex2/.cache/zig/o/9f73b1d2243b9fc35861f0c3d868e554/cimport.zig:2752:91: error: unable to evaluate constant expression
pub inline fn DefaultScreen(dpy: anytype) @TypeOf(@import("std").meta.cast(_XPrivDisplay, dpy).*.default_screen) {
                                                                                          ^
/home/ishidex2/.cache/zig/o/9f73b1d2243b9fc35861f0c3d868e554/cimport.zig:2752:43: note: called from here
pub inline fn DefaultScreen(dpy: anytype) @TypeOf(@import("std").meta.cast(_XPrivDisplay, dpy).*.default_screen) {
                                          ^
./x11.zig:7:20: note: called from here
pub fn main() void {
                   ^
/home/ishidex2/.cache/zig/o/9f73b1d2243b9fc35861f0c3d868e554/cimport.zig:2752:75: note: referenced here
pub inline fn DefaultScreen(dpy: anytype) @TypeOf(@import("std").meta.cast(_XPrivDisplay, dpy).*.default_screen) {
                                                                          ^
./x11.zig:11:36: note: referenced here
    var screen = Xlib.DefaultScreen(display); // <- Unable to evaluate constant expression
                                   ^
```
OS: Linux x86_64
Zig version: 0.8.0
X.Org version: 1.20.11

**Comment by Vexu** [comment] 2021-08-11 12:50
Duplicate of #5305.

The parameter is marked as `anytype` because `DefaultScreen` is a macro so we don't have type info.

The linked issue has a workaround which is pretty much just copied straight from the body of the macro.

**Closed by Vexu** 2021-08-11 12:50 UTC

**Comment by iotasieve** [comment] 2021-08-11 12:53
I see, I found out i can use XDefaultScreen instead, thank you
