### ISSUE TITLE
Switching on function variable with more than 3 cases causes compiler to crash

### ISSUE THREAD

**Issue by realaltffour** [ziglang/zig#12199] opened 2022-07-22 18:29 UTC
### Zig Version

0.10.0-dev

### Steps to Reproduce

```zig
const std = @import("std");

pub const func = fn (arg1: i32, arg2: i32) i32;

pub fn add(arg1: i32, arg2: i32) i32 {
    return arg1 + arg2;
}

pub fn sub(arg1: i32, arg2: i32) i32 {
    return arg1 - arg2;
}

pub fn mult(arg1: i32, arg2: i32) i32 {
    return arg1 * arg2;
}

pub fn sub5(arg1: i32, arg2: i32) i32 {
    return arg1 + arg2 - 5;
}

pub fn sub10(arg1: i32, arg2: i32) i32 {
    return arg1 + arg2 - 10;
}

pub fn main() !void {
    var f: func = add;

    switch (f) {
        add => std.log.warn("add", .{}),
        sub => std.log.warn("sub", .{}),
        mult => std.log.warn("mult", .{}),
        sub5 => std.log.warn("sub5", .{}),
        //sub10 => std.log.warn("sub10", .{}),
        else => std.log.warn("else", .{}),
    }
}
```

### Expected Behavior

Print "add".
### Actual Behavior

Crashing with more than 3 branches.
```
Code Generation [502/577] std.fmt.format... zigample...The following command terminated unexpectedly:
/usr/lib/zig/zig build-exe /data/sisyphus/proj/zigample/src/main.zig -lGL -lc --cache-dir /data/sisyphus/proj/zigample/zig-cache --global-cache-dir /home/ayham/.cache/zig --name zigample --enable-cache
error: the following build command failed with exit code 9:
/data/sisyphus/proj/zigample/zig-cache/o/c9ab010c1ad05cb639c3d501a1566faf/build /usr/lib/zig/zig /data/sisyphus/proj/zigample /data/sisyphus/proj/zigample/zig-cache /home/ayham/.cache/zig run

```

**Comment by Vexu** [comment] 2022-07-22 18:36
Duplicate of #7357

**Closed by Vexu** 2022-07-22 18:36 UTC
Labels: bug
