### ISSUE TITLE
Copy debug symbols to the zig build installation directory for debug builds

### ISSUE THREAD

**Issue by IanLilleyT** [ziglang/zig#2848] opened 2019-07-08 01:06 UTC
- Copy debug symbols to the installation directory along with the exe in Debug builds?
- ~~Allow embedding debug symbols (where possible)?~~
- ~~Pick debug symbols format for systems that support multiple~~
- ~~Maybe other uses?~~

Edited original post to be more specific to my problem

**Comment by daurnimator** [comment] 2019-07-08 04:31
Duplicate of #2300?

**Comment by andrewrk** [comment] 2019-07-08 18:53
@IanLilleyT thanks for the report. Can you turn this issue into an issue for your use case alone? What exactly are you trying to do? Let's start from there.

**Comment by IanLilleyT** [comment] 2019-07-08 19:29
Sure. I'm mainly concerned with the first bullet point and only added the other bullets after some minor brainstorming on irc. It looks like they might be duplicates of #2300.

Anyway, when using `zig build` for a debug build, I would like the debug symbols to be copied to the installation directory along with the executable, or at least have control over whether that happens. Currently only the exe moves into the zig-cache/bin folder, which means the debugger can't find the pdb file, and thus no symbols are loaded.

I haven't been able to find a workaround for copying the pdb file either, because the zig cache folders can't be hardcoded in a script.

**Closed** 2019-07-08 22:48 UTC
Labels: zig build system

**Comment by andrewrk** [comment] 2019-07-08 22:50
@IanLilleyT can you confirm that the commit I pushed allows you to use the debugger?

Now, when the target is windows, the install step will install the pdb file alongside the binaries. This can be disabled by setting `strip` to `true` for a build artifact.

**Comment by IanLilleyT** [comment] 2019-07-08 23:24
Debugging works 😄 

I also confirmed strip to true does not generate pdb

**Comment by sekoyo** [comment] 2022-01-25 00:25
> Debugging works 😄
> 
> I also confirmed strip to true does not generate pdb

Are you able to be a bit more specific how you got debug files to be emitted? I have a custom `build.zig` for a C++ project and want to output a `.dSYM` next to the binary which would allow me to visually step through code in VSCode. Clang does this but not sure how to make Zig (then again I don't even know if I'm doing a release or debug build at this point 😅)

**Comment by mmaciejeamd** [comment] 2023-03-11 00:22
Bump. I'm also wondering how to do that .
