### ISSUE TITLE
Zig compiler segfault on incomplete array initialization.

### ISSUE THREAD

**Issue by floooh** [ziglang/zig#13582] opened 2022-11-18 11:02 UTC
### Zig Version

0.11.0-dev.206+72d3f4b5d

(also happens in the stable 0.10.0 version)

### Steps to Reproduce and Observed Behavior

Compile this code snippet with ```zig build-exe bla.zig``` (tested on an M1 Mac):

```zig
const print = @import("std").debug.print;

const Bla = struct {
    arr: [8]i32 = [_]i32{0} ** 8,
};

pub fn main() void {
    const bla = Bla{
        .arr = .{ 1, 2, 3, 4 }
    };
    print("bla: {}", .{ bla });
}
```

The compiler segfaults because of the incomplete array initialization.

```
scratch ➤ zig build-exe bla.zig
[1]    25060 segmentation fault  zig build-exe bla.zig
```

### Expected Behavior

The compiler should throw a regular compilation error, or if this proposal (https://github.com/ziglang/zig/issues/6068) is accepted, compile without error (**hint hint nudge nudge**) ;)

**Comment by Pyrolistical** [comment] 2022-11-20 21:19
Is this a dupe of https://github.com/ziglang/zig/issues/13122

**Comment by Vexu** [comment] 2022-11-20 21:25
Yes.

**Closed by Vexu** 2022-11-20 21:25 UTC
Labels: bug, stage2
