### ISSUE TITLE
Allow using "hard tabs" for screen readers as better accessibility.

### ISSUE THREAD

**Issue by HeavyRain266** [ziglang/zig#9665] opened 2021-08-31 18:32 UTC
Currently, because of using only spaces, zig is unusable with most screen readers, for example when we use 4 spaces as indents then you will hear "space space space space _code_ space space space space _more code_...". 

I am aware that, it will be probably big change in compiler and/or language itself but some people wants to try zig but they can't because of screen reader problems as described here. A lot of language tries to add some accessibility features, I hope zig someday will become one of them.

**Comment by marler8997** [comment] 2021-08-31 18:55
Could this be solved if screen readers were able to read duplicates as "4 spaces" or "24 spaces" etc? I don't know much about screen readers, do you have more information about them?  This feels like it would be a problem for more than just Zig source code.

**Comment by andrewrk** [comment] 2021-08-31 19:01
duplicate of #544

**Closed by andrewrk** 2021-08-31 19:01 UTC
