### ISSUE TITLE
The Print is broken when I use a single line If statement 

### ISSUE THREAD

**Issue by haz00** [ziglang/zig#12454] opened 2022-08-16 09:26 UTC
### Zig Version

0.10.0-dev.3559+d2342370f

### Steps to Reproduce

This is broken, prints: `...`

```zig
const std = @import("std");

pub fn main() !void {
    const arr = [_]u8{0} ** 3;

    for (arr) |_, idx| {
        std.debug.print("{s}", .{ if (idx % 2 == 0) "." else "-"});
    }
}
```

### Expected Behavior

The valid result must be `.-.` 

This is valid code:

```zig
const std = @import("std");

pub fn main() !void {
    const arr = [_]u8{0} ** 3;

    for (arr) |_, idx| {
        var str = if (idx % 2 == 0) "." else "-";
        std.debug.print("{s}", .{ str });
    }
}
```

### Actual Behavior

No errors, just incorrect result from If expression.

**Comment by tauoverpi** [comment] 2022-08-16 10:38
duplicate of #5230, note that this works with `-fno-stage1`

**Closed** 2022-08-16 10:40 UTC
Labels: bug
