### ISSUE TITLE
no reference trace if use allocator.free() on one-elemented ptr

### ISSUE THREAD

**Issue by sergey6661313** [ziglang/zig#16580] opened 2023-07-27 15:05 UTC
### Zig Version

0.11.0-dev.4271+1aacfa718

### Steps to Reproduce and Observed Behavior

main.zig: 
```zig
const std = @import("std");

pub fn main() !void {
    var gpa: std.heap.GeneralPurposeAllocator(.{}) = .{};
    var allocator = gpa.allocator();
    var allocated = try allocator.create(usize);
    allocated.* = 4;
    allocator.free(allocated);
}
```
zig build run
```bash
zig11/lib/std/mem.zig:4143:9: error: expected []T or *[_]T, passed *usize
        @compileError("expected []T or *[_]T, passed " ++ @typeName(sliceType));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zig11/lib/std/mem.zig:4150:59: note: called from here
pub fn sliceAsBytes(slice: anytype) SliceAsBytesReturnType(@TypeOf(slice)) {
                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```

### Expected Behavior

zig11/lib/std/mem.zig:4143:9: error: expected []T or *[_]T, passed *usize
...
referenced by:
    main: src/main.zig:9

**Comment by sergey6661313** [comment] 2023-07-27 15:11
the same problem if you write destroy where free is required

**Comment by nektro** [comment] 2023-07-27 19:52
likely duplicate https://github.com/ziglang/zig/issues/12969

**Comment by rohlem** [comment] 2023-07-29 18:33
Exact duplicate of https://github.com/ziglang/zig/issues/15124 , which was marked duplicate of https://github.com/ziglang/zig/issues/14335 .
(But maybe if people keep opening the issue for `std.mem.Allocator` we should put "allocator" in the title of whichever one we leave open?)

**Comment by jacobly0** [comment] 2023-08-18 08:30
Duplicate of #14335

**Closed by jacobly0** 2023-08-18 08:30 UTC
Labels: bug

**Comment by jacobly0** [comment] 2023-08-25 18:09
Duplicate of #15124
