### ISSUE TITLE
in Debug, undefined in main scope is elided to 0x00 and not 0xaa as expected

### ISSUE THREAD

**Issue by dch** [ziglang/zig#7745] opened 2021-01-10 19:16 UTC
Not sure if this is over-optimisation, or just a misunderstanding of zig on my part. Tested against 0.7.1 and 20210109 master snapshot.

```zig
const std = @import("std");
const expect = @import("std").testing.expect;
// if this is moved inside the expect block tests instead pass
var i: u8 = undefined;

pub fn main() void {}

test "undef" {
    expect(i == 0xaa);
}
```

results:

```zig
$ zig test -O Debug  undefined.zig
Test [1/1] test "undef"... thread 101842 panic: test failure
/usr/local/lib/zig/std/testing.zig:274:14: 0x2041d8 in std.testing.expect (test)
    if (!ok) @panic("test failure");
             ^
/projects/playground/zig/undefined.zig:8:11: 0x2047f9 in test "undef" (test)
    expect(i == 0xaa);
          ^
/usr/local/lib/zig/std/special/test_runner.zig:69:28: 0x206861 in std.special.main (test)
        } else test_fn.func();
                           ^
/usr/local/lib/zig/std/start.zig:345:37: 0x208ac2 in std.start.main (test)
            const result = root.main() catch |err| {
                                    ^
/usr/src/lib/csu/amd64/crt1.c:76:7: 0x203fa1 in _start (/usr/src/lib/csu/amd64/crt1.c)
???:?:?: 0x800282fff in ??? (???)
error: the following test command crashed:
zig-cache/o/0602754304c8821a53531467bb3e603f/test /usr/local/bin/zig
```

**Comment by dch** [comment] 2021-01-10 20:02
some related discussions

- https://github.com/ziglang/zig/issues/1987
- https://github.com/ziglang/zig/issues/4846
- https://github.com/ziglang/zig/issues/460

**Comment by andrewrk** [comment] 2021-01-12 05:33
this is a duplicate of #1987

**Closed** 2021-01-26 16:53 UTC
