### ISSUE TITLE
package manager: Transitive dependencies have incorrect hash

### ISSUE THREAD

**Issue by Southporter** [ziglang/zig#17282] opened 2023-09-25 15:03 UTC
### Zig Version

0.11.0 and 0.12.0-dev.575+fb6fff256

### Steps to Reproduce and Observed Behavior

Create an new program with `zig init-exe`
Add one of the attached `build.zig.zon` files.
Run `zig build run`.
The hash of the packages dependencies will be incorrect. Seems to happen for any package that has dependencies.

This only seems to happen on my linux machine. Details below. For MacOS this works fine. I will try it on some other machines if I can get the time to spin up a few vms, or try a live usb. 

Machine Information:
<details><summary>Relevant details from cat of /etc/os-release</summary>
NAME="Fedora Linux"<br/>
VERSION="38.20230925.0 (Kinoite)"<br/>
ID=fedora<br/>
VERSION_ID=38<br/>
VERSION_CODENAME=""<br/>
PLATFORM_ID="platform:f38"<br/>
PRETTY_NAME="Fedora Linux 38.20230925.0 (Kinoite)"<br/>
VARIANT="Kinoite"<br/>
VARIANT_ID=kinoite<br/>
OSTREE_VERSION='38.20230925.0'<br/>
</details>

Example build.zig.zon files
[build.zig.zon with treez dependency](https://github.com/ziglang/zig/files/12716671/build.zig.zon.txt)
[build.zig.zon with mach-freetype dependency](https://github.com/ziglang/zig/files/12716682/build.zig.zon.txt)

![hash mismatch](https://github.com/ziglang/zig/assets/8585377/dd4887fe-55ba-4222-86f8-3452bc0025c7)

### Expected Behavior

`zig build run` should pull dependencies and hashes should be calculated correctly.

**Comment by Southporter** [comment] 2023-09-25 15:59
Yes, I'm on btrfs. One thing to note, this only seems to be an issue on x86_64. I have a Kinoite vm on aarch64 also on btrfs, but does not have the issue. I'll look at that other thread.

**Comment by Southporter** [comment] 2023-09-25 20:56
It does indeed seem to be btrfs related. I created a ext4 partition and moved the zig cache to that partition and it is pulling down and calculating the package hashes correctly.

Current workaround:
Create a new ext4 partition
Mount the partition to /var/cache/dev (or equivalent path) and `chown` the directory
`ln -s /var/cache/dev ~/.cache/zig`

**Comment by andrewrk** [comment] 2023-10-02 18:55
Closing as duplicate of #17095. Unfortunately, we have nothing to do but wait until users move on from the affected kernel versions.

Short summary of the problem:

* Bug only affects btrfs file system on linux
* Bug introduced in [6.4.12 kernel](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.4.12)
* Bug fixed in [this patch](https://lore.kernel.org/linux-btrfs/cover.1694260751.git.fdmanana@suse.com/) but not merged into the kernel yet

Recommend for btrfs users to stick with < 6.4.12 until a kernel version is released that has the fix.

**Comment by andrewrk** [comment] 2023-10-04 02:42
Re-opening because I have an idea to make this slightly better for Zig users. We can have an opt-in environment variable `ZIG_BTRFS_WORKAROUND=1` to get people unstuck. Re-opening until that is implemented (WIP).

**Comment by andrewrk** [comment] 2023-10-09 18:59
Workaround landed in f7bc55c0136b91805bd046a8cc8ea745d7e7567d. Please export the environment variable `ZIG_BTRFS_WORKAROUND=1` if you wish to use the workaround.

**Closed by andrewrk** 2023-10-09 18:59 UTC
Labels: bug, os-linux, upstream, zig build system
