### ISSUE TITLE
Naming: `@trunc` and `@truncate` are easily conflated

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17598] opened 2023-10-18 20:04 UTC
Unless you read the documentation every single time to double check, it's too easy to conflate the two especially if you're getting things done in a hurry.

It's not a big issue but it's not ergonomically optimal, perhaps some thoughts can be put into seeing if it's possible to give them more self-evident names.

**Comment by wooster0** [comment] 2023-10-19 08:33
Duplicate of #3788

**Closed** 2023-10-19 11:19 UTC
