### ISSUE TITLE
std.os: don't always retry close() on EINTR

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2425] opened 2019-05-04 04:24 UTC
At the moment, `close` is retried on `EINTR`. https://github.com/ziglang/zig/blob/f4798297ded2d05f4e1919fb27a9cdb9981a5e11/std/os.zig#L270

On many operating systems, you shouldn't do this. e.g. From [linux man page](http://man7.org/linux/man-pages/man2/close.2.html):
> In particular close() should not be retried after an EINTR since this may cause a reused descriptor from another thread to be closed.

If my [earlier research](https://github.com/wahern/cqueues/issues/56) is correct:
- HP-UX you try again
- Linux, Solaris and AIX you don't want to retry again
- OSX is ill-defined and hence unsafe, you should use `close_nocancel` instead and _not_ try again.

Related links:
- http://austingroupbugs.net/view.php?id=529
- http://alobbs.com/post/54503240599/close-and-eintr
- http://www.daemonology.net/blog/2011-12-17-POSIX-close-is-broken.html
- https://code.google.com/p/chromium/issues/detail?id=269623
- https://github.com/wahern/cqueues/issues/56

**Comment by bnoordhuis** [comment] 2019-05-05 07:45
> OSX is ill-defined and hence unsafe, you should use close_nocancel instead and not try again.

FWIW, I was curious if this is still an issue with recent xnu kernels and it is: `close()` returns EINTR when a thread cancellation request is pending but _without_ closing the file descriptor.

It seems like a rather bizarre deviation from the POSIX spec. I have no idea why xnu works like that. Legacy, perhaps?

FWIW, glibc's `close()` wrapper has a similar issue - it unwinds the thread when a cancellation is pending - but at least that's according to spec. Still a file descriptor leak, though.

Musl's `close()` isn't a cancellation point and isn't affected.

**Comment by daurnimator** [comment] 2019-05-05 08:09
> It seems like a rather bizarre deviation from the POSIX spec. I have no idea why xnu works like that. Legacy, perhaps?

POSIX leaves it undefined; as each POSIX OS does it differently :astonished: (see my austingroup link)

**Comment by bnoordhuis** [comment] 2019-05-05 08:39
Sorry, reading back what I wrote I realize it's not clear I was talking about thread cancellation itself, not whether it leaves the file descriptor open or not.

`close()` is a cancellation point with well-defined semantics but xnu doesn't follow the spec. EINTR is allowed when the thread is cancelled while _suspended_ inside the close() system call but xnu returns EINTR upon _entering_ the system call.

The expected behavior is that it terminates the thread but AFAICT, that never happens on xnu and hence `close()` is effectively not a cancellation point.

If you had something like `pthread_cancel(pthread_self()); RETRY_ON_EINTR(close(fd));` in your code, it looks like it could loop forever.

(That said, it's probably largely academic because no one uses thread cancellation. At least, I've never seen a program that does.)

**Closed** 2019-05-27 23:21 UTC
Labels: bug, userland
