### ISSUE TITLE
PGO support

### ISSUE THREAD

**Issue by zamazan4ik** [ziglang/zig#15137] opened 2023-03-31 22:26 UTC
Hi!

After a quick research on Zig lang, it's unclear to me what is the state of PGO support in Zig? Are there plans to add PGO support to the compiler?

Many thanks for considering my request.

**Comment by Vexu** [comment] 2023-03-31 23:36
See #237

**Comment by andrewrk** [comment] 2023-04-10 17:08
closing as duplicate of #237.

**Closed by andrewrk** 2023-04-10 17:08 UTC
