### ISSUE TITLE
No compiler error stacktrace when providing a single item pointer to `allocator.free`

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#15124] opened 2023-03-30 17:21 UTC
### Zig Version

0.11.0-dev.1913+95f6a5935

### Steps to Reproduce and Observed Output

Put anything that's not a slice into any `allocator.free` method:

```zig
const std = @import("std");

pub fn main() !void {
	var x = try std.heap.page_allocator.create(u32);
	std.heap.page_allocator.free(x);
}
```

Even with `-freference-trace` the stacktrace cuts off after just two places:
```
$ zig run test.zig -freference-trace
/home/mint/Downloads/zig/lib/std/mem.zig:3622:9: error: expected []T or *[_]T, passed *const *const [0:0]u8
        @compileError("expected []T or *[_]T, passed " ++ @typeName(sliceType));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mint/Downloads/zig/lib/std/mem.zig:3629:59: note: called from here
pub fn sliceAsBytes(slice: anytype) SliceAsBytesReturnType(@TypeOf(slice)) {
                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```

### Expected Output

This needs a stacktrace.
I just spend like 20 minutes to figure this out because I had no idea where the error came from.

**Comment by rohlem** [comment] 2023-03-31 08:55
duplicate of #14335 as far as I can tell

**Comment by IntegratedQuantum** [comment] 2023-03-31 09:11
Yeah, you are right.

**Comment by jacobly0** [comment] 2023-08-25 18:07
After fixing #14335, this issue still reproduces.

**Closed** 2023-08-28 19:28 UTC
Labels: frontend, error message
