### ISSUE TITLE
Proposal: standard wrappers for `zig cc` and `zig c++`

### ISSUE THREAD

**Issue by Andoryuuta** [ziglang/zig#8716] opened 2021-05-08 19:35 UTC
There are multiple existing tools which require a direct filename or filepath for C/C++ compiler(s), which causes issues when trying to use Zig's executable+argument (`zig` + `cc`) sub-command. People currently work around this by creating bash / batch wrappers which forward the arguments to `zig cc` or `zig c++`.

I personally ran into this issue today while trying to use cmake's `-DCMAKE_C_COMPILER` and `-DCMAKE_CXX_COMPILER` flags, as [it doesn't support spaces/multi-part commands](https://gitlab.kitware.com/cmake/cmake/-/issues/17346). Luckily I was able to work around the issue without changes to cmake itself by using [some other undocumented cmake flags](https://cmake-developers.cmake.narkive.com/OTa9EKfj/cmake-c-compiler-arg-not-documented).

There have been multiple other cases where this zig command could not be used and required workarounds or code patches:
* `cmake` - [zig cc: unsupported darwin linker args #4841](https://github.com/ziglang/zig/issues/4841#issuecomment-605507983)
* `cgo` (before downstream patch) - [ "zig cc" doesn't work with cgo (golang) #7342](https://github.com/ziglang/zig/issues/7342#issuecomment-740855108)
    * (This actually might still be an issue for cgo, as the issue was reopened recently: https://github.com/golang/go/issues/43078)
* `graal native-image` - https://discord.com/channels/605571803288698900/606246764651085829/804764962101788722

Given the above: Should we consider distributing two standard wrappers with Zig (e.g. `zigcc` and `zigcxx`) which would redirect arguments to `zig cc` and `zig c++`?

**Comment by tauoverpi** [comment] 2021-05-09 12:53
This would have helped quite a bit while trying to use zig within build scripts with guix. Instead of just `zigcc` and `zigcxx`, it would be nice if all commands came with a single word variant.

- `zig-cc`
- `zig-c++`
- `zig-build`
- `zig-build-exe`
- `zig-ld`
- `zig-ar`
- and so on

The wrappers might be easy to write but within build scripts you'd either repackage zig to export them or add them to every script it's needed in which quickly becomes error prone.

**Comment by kubkon** [comment] 2021-05-09 20:30
> This would have helped quite a bit while trying to use zig within build scripts with guix. Instead of just `zigcc` and `zigcxx`, it would be nice if all commands came with a single word variant.
> 
>     * `zig-cc`
> 
>     * `zig-c++`
> 
>     * `zig-build`
> 
>     * `zig-build-exe`
> 
>     * `zig-ld`
> 
>     * `zig-ar`
> 
>     * and so on
> 
> 
> The wrappers might be easy to write but within build scripts you'd either repackage zig to export them or add them to every script it's needed in which quickly becomes error prone.

@andrewrk might correct me here but I believe the idea is to ultimately drop in a `build.zig` file and use Zig as a full build system replacement for CMake etc., in which case adding single-word variants for all the commands is moot.

**Comment by jedisct1** [comment] 2021-05-09 21:54
Such wrappers remain useful to compile unmodified, existing code.

The ability to effortlessly cross-compile existing C/C++ code is a strong selling point. 

Now, should these wrappers be part of the Zig distribution? Maybe not.

They can reside in a dedicated repository, that the documentation can point to.

**Comment by andrewrk** [comment] 2021-05-12 21:58
Such wrappers are convenient, however they are a detail of the "glue" code between a Zig distribution and the system it is run on. Such wrappers will need system-specific code. Out of scope for this repository.

**Closed by andrewrk** 2021-05-12 21:58 UTC
Labels: proposal, zig cc

**Comment by dosgo** [comment] 2021-08-19 07:32
I made a small tool to automatically process the compilation target according to GOOS GOARCH.  https://github.com/dosgo/zigtool
Then I did not cross compile successfully under windows.
![image](https://user-images.githubusercontent.com/9545458/130027014-e2849f19-b7a8-469f-b55d-805f1432c5ce.png)
golang 1.17

**Comment by zhaozg** [comment] 2021-10-12 08:44
> Do you mind sharing your solution using the "some other undocumented cmake flags"?? I am also finding it very difficult using `zig cc` with CMake.

Not easy, but not so difficult. look here: https://github.com/zhaozg/luajit-cmake/blob/master/Utils/zig.toolchain.cmake

**Comment by tisonkun** [comment] 2022-12-16 13:01
FWIW I write a handy script that can work:

* `zig-cc`

```bash
#!/usr/bin/env bash
zig cc $@
```

* `zig-cxx`

```bash
#!/usr/bin/env bash
zig c++ $@
```

For Kvrocks project, I run:

```bash
git clone https://github.com/apache/incubator-kvrocks
./x.py build --ninja -DCMAKE_C_COMPILER="$(pwd)/zig-cc" -DCMAKE_CXX_COMPILER="$(pwd)/zig-cxx"
```

Although some macOS specific issues occur, the original proposal here is resolved.

**Comment by mulle-nat** [comment] 2023-04-17 16:34
Since I just ran into this: you can set `-DCMAKE_CXX_COMPILER=zig;cc` and it will work.

**Comment by multivac61** [comment] 2024-01-09 08:07
On macOS you'll need quotes: `-DCMAKE_C_COMPILER="zig;cc"`

**Comment by multivac61** [comment] 2024-01-09 08:24
> ```shell
> -DCMAKE_C_COMPILER="$(pwd)/zig-cc" -DCMAKE_CXX_COMPILER="$(pwd)/zig-cxx"
> ```

Won't work on macOS. Fortunately @tisonkun  [answer above does](https://github.com/ziglang/zig/issues/8716#issuecomment-1354733393).

**Comment by ekliptik** [comment] 2024-01-18 16:40
The answer by @tisonkun breaks when an argument has a space in it. For example, when you build clang, you have a define like `-DCLANG_VENDOR="\"CompanyName \""` as set by `clang/lib/Basic/CMakeLists.txt`:

```cmake
if(CLANG_VENDOR)
  set_source_files_properties(Version.cpp
    PROPERTIES COMPILE_DEFINITIONS "CLANG_VENDOR=\"${CLANG_VENDOR} \"")
endif()
```

This gets broken due to some problem with passing the args:
```
./zig-cxx -DFOO="\"Hi \"" a.cpp
In file included from <built-in>:490:
<command line>:8:13: warning: missing terminating '"' character [-Winvalid-pp-token]
#define FOO "Hi
            ^
1 warning generated.
LLD Link... ld.lld: error: cannot open ": No such file or directory
```

**Comment by rootbeer** [comment] 2024-01-18 17:59
If you add quotes around the `$@` in the script bash will "do the right thing" and preserve quoting/whitespace around the arguments it passes along:

```
#!/bin/bash
exec zig cc "$@"
```

**Comment by ekliptik** [comment] 2024-01-18 20:31
Notes from further experimentation: `-DCMAKE_C_COMPILER=zig;cc` sometimes didn't work for me but that probably was just caused by my CMakeCache being somehow polluted. Therefore the wrapper isn't needed. For example, it is used in [zig-bootstrap](https://github.com/ziglang/zig-bootstrap/blob/fb6231bb12648dc4a54a8afcd16eeebd6657ff4a/build). What is non-obvious is that `-DCMAKE_SYSTEM_NAME="$TARGET_OS_CMAKE"` is actually important to avoid some auto-detection magic.

**Comment by widlarizer** [comment] 2024-11-20 12:36
> sometimes the zig tool is called with other parameters before the cc or c++ option.
Under what circumstances does this happen?

**Comment by lars18th** [comment] 2024-11-20 13:43
> > sometimes the zig tool is called with other parameters before the cc or c++ option.
> 
> Under what circumstances does this happen?

Running CMake to try to compile Canonical Multipass with ZIG CC.
The CMake process will end without errors starting it with:
`cmake -DCMAKE_C_COMPILER="zig;cc;-static" -DCMAKE_CXX_COMPILER="zig;c++;-static" ../`
But when compiling with `make`, at some point the compiler called is `zig -std=c++17 c++`, instead of `zig c++ -std=c++17`.

**Comment by jedisct1** [comment] 2024-11-20 17:09
> at some point the compiler called is zig -std=c++17 c++, instead of zig c++ -std=c++17

This is exactly the issue wrappers would solve.

**Comment by lars18th** [comment] 2024-11-20 18:01
Hi to all,

I'm experimenting with something like this:
```
diff --git a/zig/src/main.zig b/zig/src/main.zig
index 9b245b3ed..5ef82b332 100644
--- a/zig/src/main.zig
+++ b/zig/src/main.zig
@@ -252,6 +252,7 @@ fn mainArgs(gpa: Allocator, arena: Allocator, args: []const []const u8) !void {
         }
     }
 
+    const bin_name = args[0];
     const cmd = args[1];
     const cmd_args = args[2..];
     if (mem.eql(u8, cmd, "build-exe")) {
@@ -290,10 +291,10 @@ fn mainArgs(gpa: Allocator, arena: Allocator, args: []const []const u8) !void {
     {
         dev.check(.lld_linker);
         return process.exit(try lldMain(arena, args, true));
-    } else if (mem.eql(u8, cmd, "cc")) {
+    } else if (mem.eql(u8, cmd, "cc") or mem.eql(u8, bin_name, "zig-cc")) {
         dev.check(.cc_command);
         return buildOutputType(gpa, arena, args, .cc);
-    } else if (mem.eql(u8, cmd, "c++")) {
+    } else if (mem.eql(u8, cmd, "c++") or mem.eql(u8, bin_name, "zig-c++")) {
         dev.check(.cc_command);
         return buildOutputType(gpa, arena, args, .cpp);
     } else if (mem.eql(u8, cmd, "translate-c")) {
```

With this if you call to `zig-cc` then it will be equivalent to call to `zig cc`. And you only need to creat the symlink `ln -s zig zig-cc`.

**Comment by lars18th** [comment] 2024-11-20 23:26
Hi @andrewrk ,

Please, could you check this patch?
```
diff --git a/zig/src/main.zig b/zig/src/main.zig
index 9b245b3ed..4e2a3bdb2 100644
--- a/zig/src/main.zig
+++ b/zig/src/main.zig
@@ -215,7 +215,12 @@ fn mainArgs(gpa: Allocator, arena: Allocator, args: []const []const u8) !void {
     const tr = tracy.trace(@src());
     defer tr.end();

-    if (args.len <= 1) {
+    const slash_pos = std.mem.lastIndexOf(u8, args[0], "/") orelse args[0].len;
+    const bin_name = args[0][(slash_pos + 1) ..];
+    const regular_name = mem.eql(u8, bin_name, "zig");
+    std.log.info("BIN_NAME: {s}", .{bin_name});
+
+    if (args.len <= 1 and regular_name) {
         std.log.info("{s}", .{usage});
         fatal("expected command argument", .{});
     }
@@ -252,8 +257,8 @@ fn mainArgs(gpa: Allocator, arena: Allocator, args: []const []const u8) !void {
         }
     }

-    const cmd = args[1];
-    const cmd_args = args[2..];
+    const cmd = if (regular_name) args[1] else bin_name;
+    const cmd_args = if (regular_name) args[2..] else args[1..];
     if (mem.eql(u8, cmd, "build-exe")) {
         dev.check(.build_exe_command);
         return buildOutputType(gpa, arena, args, .{ .build = .Exe });
@@ -290,10 +295,10 @@ fn mainArgs(gpa: Allocator, arena: Allocator, args: []const []const u8) !void {
     {
         dev.check(.lld_linker);
         return process.exit(try lldMain(arena, args, true));
-    } else if (mem.eql(u8, cmd, "cc")) {
+    } else if (mem.eql(u8, cmd, "cc") or mem.eql(u8, cmd, "zig-cc")) {
         dev.check(.cc_command);
         return buildOutputType(gpa, arena, args, .cc);
-    } else if (mem.eql(u8, cmd, "c++")) {
+    } else if (mem.eql(u8, cmd, "c++") or mem.eql(u8, cmd, "zig-c++")) {
         dev.check(.cc_command);
         return buildOutputType(gpa, arena, args, .cpp);
     } else if (mem.eql(u8, cmd, "translate-c")) {
```
If you agree with this approach, then I'll prepare a PR.
You agree? 😉

**Comment by widlarizer** [comment] 2024-11-21 08:48
Are you sure that wasn't the sort of auto-detection that I mentioned you can get around with `CMAKE_SYSTEM_NAME`? Commenting a diff on an issue and tagging a maintainer is the same as opening a (maybe draft) PR except less convenient

**Comment by widlarizer** [comment] 2024-11-21 09:48
> before writing a complete patch (this one is only a functional example)

I believe that is what draft PRs are exactly for

**Comment by lars18th** [comment] 2024-12-12 19:24
Hi to all!

I've created a _draft_ patch that solves the problem from the root: #22211 

The solution is quite simple: if you create a symlink (or rename) the binary with the name "zig-cc" then calling to it will be the same as "zig cc". Therefore any other paramters will be parsed after the "cc". So that's a definitive solution.

The PR is a draft because I need the help from @andrewrk to clean the code, add the resting cases (now only for "cc" and "c++"), and add support for Windows (perhaps adding "zig-cc.exe" checks).

What you think?

**Comment by lars18th** [comment] 2024-12-12 20:37
Hi @andrewrk ,

Please can you explain why it is rejected?
My patch does not change anything from the standard behaviour.

**Comment by nektro** [comment] 2024-12-12 21:34
https://github.com/ziglang/zig/issues/8716#issuecomment-840122458
