### ISSUE TITLE
String constants are placed in data section

### ISSUE THREAD

**Issue by vahur** [ziglang/zig#20046] opened 2024-05-23 05:20 UTC
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

Current master seems to be doing the same.

```
zig init
zig build -Dtarget=x86_64-windows -Doptimize=ReleaseSmall
objdump --section=.data --full-contents zig-out/bin/coff.exe

Contents of section .data:
 404000 ffffffff 52756e20 607a6967 20627569  ....Run `zig bui
 404010 6c642074 65737460 20746f20 72756e20  ld test` to run
 404020 74686520 74657374 732e0a00 416c6c20  the tests...All
 404030 796f7572 207b737d 20617265 2062656c  your {s} are bel
 404040 6f6e6720 746f2075 732e0a00 6572726f  ong to us...erro
 404050 723a207b 737d0a00 efbfbd00 00000000  r: {s}..........
 404060 00000000 00000000                    ........
```

### Expected Behavior

Constants are placed into read-only .rdata or equivalent section in binary.

**Comment by Vexu** [comment] 2024-05-23 10:11
Duplicate of #18404

**Closed by Vexu** 2024-05-23 10:11 UTC
Labels: bug
