### ISSUE TITLE
[Proposal] Documentation for standard library

### ISSUE THREAD

**Issue by Duckxz** [ziglang/zig#3264] opened 2019-09-20 08:07 UTC
i'm new to the language and it looks very interesting, but there is only a documentation for the language itselves (or i'm just not looking correctly). i can work around it by looking at the source of the standard library but it would be nice for others who want to learn it quickly.

**Comment by daurnimator** [comment] 2019-09-20 08:34
duplicate of #965

**Closed by daurnimator** 2019-09-20 08:34 UTC
