### ISSUE TITLE
Linker error using @atomicLoad on a platform without full support for atomics

### ISSUE THREAD

**Issue by MatthiasPortzel** [ziglang/zig#21600] opened 2024-10-05 03:21 UTC
### Zig Version

0.13.0

### Introduction
This is not a blocker, since it's easily worked around with a semantically incorrect `asm volatile ("" ::: "memory")`. I'm not going to investigate this further but wanted to create a tracking issue.

### Steps to Reproduce and Observed Behavior

**Target Platform**: `-target thumb-freestanding-eabi -mcpu cortex_m0plus`; RP2040, via microzig.

**Minimum reproduction**:
I have some code in a loop. The break condition on the loop checks a global variable which is mutated by an interrupt handler. (So I'm only actually using one core, but the code can be interrupted at any time.) This global is not mutated in the loop, so if I was compiling with optimizations, I would need a way to tell the compiler that this variable may be modified. *I believe* the correct way to do this is with `@atomicLoad(... .monotonic)`.

```zig
var val: isize = 0;

export fn testMe() void {
    while (@atomicLoad(isize, &val, .monotonic) == 0) {}
}
```

Godbolt: https://godbolt.org/z/3qeWq8qcE

**Error message**:
However, LLVM/Zig do not believe that the CPU target has support for atomics: LLVM emits a `bl __atomic_load_4` instead of normal instructions and Zig doesn't export `__atomic_load_4` from compiler_rt.

```
error: ld.lld: undefined symbol: __atomic_load_4
```

### Expected Behavior

I'm not actually interested in the atomic properties of `@atomicLoad` so I don't care that there might issues implementing this on the specific chip. My goal is only to prevent incorrect compiler optimizations. I expect that this `atomicLoad` ultimately gets lowered to a normal load.

I suspect Zig's behavior here is correct in emitting the LLVM IR `__atomic_load_4`, and LLVM is failing to lower this meaningfully on this platform. That is, this could very well be an upstream bug.

**Comment by alexrp** [comment] 2024-10-05 03:31
Duplicate of #19054.

**Closed by alexrp** 2024-10-05 03:31 UTC
Labels: bug

**Comment by MatthiasPortzel** [comment] 2024-10-05 03:37
Apologies for the noise. I must have searched the llvm issues and not the zig issues.
