### ISSUE TITLE
Compile error reference trace for incorrect `std.log` format string doesn't show the call that causes the error

### ISSUE THREAD

**Issue by Trevor-Strong** [ziglang/zig#20200] opened 2024-06-05 15:45 UTC
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

run `zig run test.zig -freference-trace`

test.zig:
```zig
const std = @import("std");

pub fn main() !void {

    const str = "Hello";

    std.log.warn("Hello {}", .{ str }); // Oops no {s}!

    // Later on ...

    std.log.warn("dummy", .{}); // This doesn't cause any compile errors

}
```

Produces this output:
```
C:\Program Files\zig\lib\std\fmt.zig:655:17: error: cannot format array without a specifier (i.e. {s} or {any})
                @compileError("cannot format array without a specifier (i.e. {s} or {any})");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    formatType__anon_7750: C:\Program Files\zig\lib\std\fmt.zig:615:38
    format__anon_6625: C:\Program Files\zig\lib\std\fmt.zig:185:23
    print__anon_3808: C:\Program Files\zig\lib\std\io\Writer.zig:23:26
    print: C:\Program Files\zig\lib\std\io.zig:324:47
    defaultLog__anon_2690: C:\Program Files\zig\lib\std\log.zig:158:15
    log__anon_2460: C:\Program Files\zig\lib\std\log.zig:125:22
    warn__anon_2034: C:\Program Files\zig\lib\std\log.zig:185:16
    main: test.zig:11:17
    callMain: C:\Program Files\zig\lib\std\start.zig:511:32
    WinStartup: C:\Program Files\zig\lib\std\start.zig:350:45
```

If you notice, the *only* reference listed that is not from the standard library is from main at line 11 which is the second, perfectly legal, log (`log.warn("dummy", .{})`). I tried increasing the reference trace limit, but the trace remained exactly the same.

### Expected Behavior

I would expect that the reference trace would actually point to the call that caused the problem, or at the *very* least, not point to an innocent call.

While it would be great if the specific call that causes the error could be listed; however, the biggest problem for me is that a totally unrelated call gets shown instead. This lead me to believe that this innocent log was the problem as when I discovered this, I was using some complicated custom formatter, and caused me to waste several hours looking for a bug in my formatter that wasn't even the problem.

This problem also occurs when the log messages have different or non-default scopes (`log.scoped()`).

**Comment by kcbanner** [comment] 2024-06-05 18:19
Maybe a duplicate of https://github.com/ziglang/zig/issues/18900 ?

**Comment by Vexu** [comment] 2024-06-05 19:25
> Maybe a duplicate of #18900 ?

It is.

**Closed by Vexu** 2024-06-05 19:25 UTC
Labels: bug
