### ISSUE TITLE
Compiler crashes with function that returns anonymous struct

### ISSUE THREAD

**Issue by tubo28** [ziglang/zig#17167] opened 2023-09-15 18:02 UTC
### Zig Version

0.12.0-dev.170+750998eef

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const print = std.debug.print;

const Foo = struct {
    i32,
};

fn foo() Foo {
    return .{0};
}

fn bar() .{i32} {
    return .{0};
}

pub fn main() !void {
    print("{}\n", foo());
    print("{}\n", bar()); // comment out this line => compile success
}
```

```console
> zig build-exe src/main.zig
fish: Job 1, 'zig build-exe src/main.zig' terminated by signal SIGTRAP (Trace or breakpoint trap)
> uname -a
Linux DESKTOP-******* 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Expected Behavior

Compile success

**Comment by Vexu** [comment] 2023-09-15 18:31
Duplicate of #17084, incorrect error message tracked in #16911

**Closed by Vexu** 2023-09-15 18:31 UTC
Labels: bug
