### ISSUE TITLE
Incorrect error message when assigning void result of function to non-void variable

### ISSUE THREAD

**Issue by Parzival-3141** [ziglang/zig#13291] opened 2022-10-24 21:01 UTC
### Zig Version

0.10.0-dev.4333+f5f28e0d2

### Steps to Reproduce

```zig
pub fn main() void {
    const false_positive: u32 = 3;
    _ = false_positive;

    const actual_error: u12 = foo();
    _ = actual_error;
}

fn foo() void {}
```

### Expected Behavior

The compiler should highlight where the actual error is
```
 error: expected type 'u12', found 'void'
   const actual_error: u12 = foo();
                                ^
```

### Actual Behavior

For some reason the error for assigning the the void result of a function to a non-void variable points at the declaration immediately before it.

```
 error: expected type 'u12', found 'void'
    const false_positive: u32 = 3;
                                ^
```

**Comment by Vexu** [comment] 2022-10-24 21:14
Duplicate of #12509

**Closed by Vexu** 2022-10-24 21:14 UTC
Labels: bug
