### ISSUE TITLE
Internal compiler error due to invalid LLVM IR

### ISSUE THREAD

**Issue by AndreasOlofsson** [ziglang/zig#8276] opened 2021-03-16 23:45 UTC
I managed to find a internal compiler error by combining optional and error types.

Here's a reduced (maybe not minimal) example:
```
fn a() ?(anyerror!void) {
    return error.E;
}

pub fn main() !void {
    _ = a();
}
```

Which fails to compile with the message
> broken LLVM module found: Operand is null
>   call fastcc void @__zig_return_error(<null operand!>), !dbg !17233
> 
> This is a bug in the Zig compiler.
> Unable to dump stack trace: debug info stripped

Tested on 0.7.1 and master. 
Here's the LLVM IR of the failing function:
```
; Function Attrs: nobuiltin nounwind
define internal fastcc void @a(%"?anyerror!void"* nonnull sret %0) unnamed_addr #1 !dbg !17223 {
Entry:
  %1 = getelementptr inbounds %"?anyerror!void", %"?anyerror!void"* %0, i32 0, i32 1, !dbg !17231
  store i1 true, i1* %1, align 1, !dbg !17231
  %2 = getelementptr inbounds %"?anyerror!void", %"?anyerror!void"* %0, i32 0, i32 0, !dbg !17231
  store i16 55, i16* %2, align 2, !dbg !17231
  call fastcc void @__zig_return_error(<null operand!>), !dbg !17233
  ret void, !dbg !17233
}

```

**Comment by Vexu** [comment] 2021-03-17 07:06
Duplicate of #1814.

**Closed by Vexu** 2021-03-17 07:06 UTC
