### ISSUE TITLE
Proposal: Make tagged union member accesses behave like optionals

### ISSUE THREAD

**Issue by N00byEdge** [ziglang/zig#9854] opened 2021-09-28 15:32 UTC
Today, accessing tagged unions is somewhat a bit of a pain. For a given tagged union value `un`, you can't do operations such as
```
if(un.mem) |value| // Not a valid optional in this context
```
or
```
un.mem = 5; // Asserts that `mem` is active for some reason
```

The proposal goes as follows
`un.mem` would result in an `?T`, or an internal type that directly coerces into one.
Clarifications:
* You can explicitly access the union member, asserting that it's active using `un.mem.?`, a big improvement over the current implicit assertion on doing `un.mem`
* Assigning to the optional should work like anywhere else, making the optional value active (and also magically setting it to be the active union variant)
  * You can't grab `&un.mem`, since this "optional" doesn't exist in reality
  * You should still be able to grab `&un.mem.?`, like on normal optionals, as the optional value _does_ exist.

This would bring the following:
```
union(tag) {
    v1: T1,
    v2: T2,
};
```
closer to
```
struct {
    v1: ?T1,
    v2: ?T2,
}
```
with the following differences:
* Only one of the members can be nonnull at a time.
* You can't take the addresses of the optionals (edge case coming later)
* You can switch on the tagged union

**Comment by MasterQ32** [comment] 2021-09-28 15:40
Can you provide real world examples where
```zig
un.mem = 10;
if(un.mem) |value| {
    foo = value;
}
```
cannot be conveniently written as 
```zig
un = .{ .mem = 10 };
if(un == .mem) {
    foo = un.mem;
}
```

For me that proposal brings in more complexity to the language than its trying to solve (which is reduce some characters that need to be typed).

Especially the need for a hacky intermediate type that *might* coerce to an optional sounds like something that is very hard to explain, and makes things like `@fieldParentPtr` way harder, as we cannot conveniently take the address of a union field.

Could you also specify how this would work:
```zig
const C = struct {
  fn foo(c: *C) void {  }
};

const U = union(enum) {
  x: C
};

var u = U { .x = .{} };
u.x.foo();
```
is there a allowed coercion of `UnionFieldMagic(C)` to `*C` similar to how it is for struct fields? 

I also don't like the assymetry from a tagged union to a untagged and external union.

So: Imho it's not worth the additional complexity

**Comment by Vexu** [comment] 2021-09-28 15:54
Duplicate of #8109.

**Closed by Vexu** 2021-09-28 15:54 UTC
Labels: proposal

**Comment by N00byEdge** [comment] 2021-09-28 16:08
> Can you provide real world examples where
>```un.mem = 10;
> if(un.mem) |value| {
>     foo = value;
> }```
> cannot be conveniently written as
> ```un = .{ .mem = 10 };
> if(un == .mem) {
>     foo = un.mem;
> }```

I don't think this criticism is valid, the same goes for optionals. Do you think this syntax should be removed for those too?
```
if(eval().String) |str|
```

I hadn't considered using `@fieldParentPtr` on unions, is that something that's done? If so, I don't think it's too bad to just implicitly access `&.mem.?` instead of `&.mem` on tagged unions.
If anything, the case is stronger for unions, as it discards the possibly much larger union type, and only keeps the member.

> Could you also specify how this would work: [...]
The last line would look like this: `u.x.?.foo();`

> I also don't like the assymetry from a tagged union to a untagged and external union.
The syntax would look different. But I think it's for good reasons that tagged union member access would look different from member access on `extern` unions, as the former has checked UB on accessing inactive members. Adding the `.?` would clarify, just like with optionals, that you're bypassing the normal checked flow (using `if`/`switch`) and just want to access the value directly.
