### ISSUE TITLE
Some arm32 targets are broken

### ISSUE THREAD

**Issue by Validark** [ziglang/zig#19894] opened 2024-05-08 01:08 UTC
### Zig Version

0.13.0-dev.74+67455c5e7

### Steps to Reproduce and Observed Behavior

Run:

```
zig init
zig build -Dtarget=arm-linux -Dcpu=cortex_m23 -Doptimize=ReleaseFast
```

Produces:

```
install
└─ install zig-empty-test
   └─ zig build-exe zig-empty-test ReleaseFast arm-linux failure
error: error: <inline asm>:1:6: instruction requires: thumb2
            stmfd sp!,{r4,r5,r6,r7}
            ^


error: the following command exited with error code 1:
/home/niles/zig/0.13.0-dev.74+67455c5e7/files/zig build-exe -OReleaseFast -target arm-linux -mcpu cortex_m23 -Mroot=/home/niles/Documents/github/zig-empty-test/src/main.zig --cache-dir /home/niles/Documents/github/zig-empty-test/zig-cache --global-cache-dir /home/niles/.cache/zig --name zig-empty-test --listen=- 
Build Summary: 2/5 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install zig-empty-test transitive failure
   └─ zig build-exe zig-empty-test ReleaseFast arm-linux failure
error: the following build command failed with exit code 1:
/home/niles/Documents/github/zig-empty-test/zig-cache/o/44e6d89a3b0853b297777f0f42fa275f/build /home/niles/zig/0.13.0-dev.74+67455c5e7/files/zig /home/niles/Documents/github/zig-empty-test /home/niles/Documents/github/zig-empty-test/zig-cache /home/niles/.cache/zig --seed 0xf36f60c5 -Za2a002dbf5025358 -Dtarget=arm-linux -Dcpu=cortex_m23 -Doptimize=ReleaseFast
```

### Expected Behavior

Inline assembly should be valid for whatever target I select.

**Comment by alexrp** [comment] 2024-09-15 08:12
This looks like a duplicate of #10411.

**Comment by alexrp** [comment] 2024-10-02 21:35
> This looks like a duplicate of #10411.

Confirmed; closing as duplicate.

**Closed by alexrp** 2024-10-02 21:35 UTC
Labels: bug, arch-arm
