### ISSUE TITLE
When I cross compile cgo from linux to macos, compile error

### ISSUE THREAD

**Issue by akkuman** [ziglang/zig#10660] opened 2022-01-21 14:16 UTC
### Zig Version

0.9.0

### Steps to Reproduce

When I cross compile cgo from linux to macos, compile error

```
cat $HOME/.bin/zcc
#!/bin/sh
ZIG_LOCAL_CACHE_DIR="$HOME/tmp" zig cc -target x86_64-macos-gnu

cat $HOME/.bin/zxx
#!/bin/sh
ZIG_LOCAL_CACHE_DIR="$HOME/tmp" zig c++ -target x86_64-macos-gnu
```

error

```
# github.com/akkuman/rotateproxy/cmd/rotateproxy
/opt/hostedtoolcache/go/1.17.6/x64/pkg/tool/linux_amd64/link: running zcc failed: exit status 1
warning: unsupported linker arg: -S
warning: unsupported linker arg: -no_pie
warning: unsupported linker arg: -pagezero_size
warning: unsupported linker arg: 4000000
warning: unsupported linker arg: --compress-debug-sections
warning: unsupported linker arg: zlib-gnu
warning(link): framework not found for '-framework CoreFoundation'
warning(link): framework not found for '-framework Security'
warning(link): Framework search paths:
error(link): undefined reference to symbol '_SecTrustSettingsCopyTrustSettings'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_SecTrustSettingsCopyCertificates'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_SecPolicyCopyProperties'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_SecItemExport'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_CFStringCreateWithBytes'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_CFRelease'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_CFNumberGetValue'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_CFEqual'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_CFDictionaryGetValueIfPresent'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_CFDataGetLength'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_CFDataGetBytePtr'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_CFArrayGetValueAtIndex'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error(link): undefined reference to symbol '_CFArrayGetCount'
error(link):   first referenced in '/tmp/go-link-800811870/go.o'
error: UndefinedSymbolReference
```

see https://github.com/akkuman/rotateproxy/runs/4863624753?check_suite_focus=true

### Expected Behavior

compile successfully

### Actual Behavior

error

**Comment by nektro** [comment] 2022-01-30 06:43
```
    echo 'ZIG_LOCAL_CACHE_DIR="$HOME/tmp" zig cc -target '${libc}' $@' >> "$HOME/.bin/zcc"
    echo 'ZIG_LOCAL_CACHE_DIR="$HOME/tmp" zig c++ '${libc}' $@' >> "$HOME/.bin/zxx"
```

the single quotes are likely destroying the variable text replacement

**Comment by andrewrk** [comment] 2022-02-02 20:14
These should be hard errors instead of warnings:

```
warning(link): framework not found for '-framework CoreFoundation'
warning(link): framework not found for '-framework Security'
```

In master branch, they are.

Looks like a duplicate of #1349.

@kubkon do we have a FAQ link or documentation page to link people to when they run into this particular issue?

**Closed by andrewrk** 2022-02-02 20:14 UTC
Labels: bug, os-macos, zig cc

**Comment by kubkon** [comment] 2022-02-02 20:15
> These should be hard errors instead of warnings:
> 
> ```
> warning(link): framework not found for '-framework CoreFoundation'
> warning(link): framework not found for '-framework Security'
> ```
> 
> In master branch, they are.
> 
> Looks like a duplicate of #1349.
> 
> @kubkon do we have a FAQ link or documentation page to link people to when they run into this particular issue?

Excellent question, and I don't think we have, no. Where would you think we should add info like this? Main docs? Or perhaps we should have a separate page for the toolchain (compiler+linker)?

**Comment by andrewrk** [comment] 2022-02-02 20:20
I'd start with making sure #1349 has up-to-date info. Maybe an entry in https://github.com/ziglang/zig/wiki/FAQ that we can link to. And that's enough for now.
