### ISSUE TITLE
Assertion failure at ir.cpp:13362 when calling comptime function

### ISSUE THREAD

**Issue by YohananDiamond** [ziglang/zig#8578] opened 2021-04-19 22:22 UTC
## Description

I've been frequently finding assertion failures when dealing with compile-time function calling, but haven't found the main issue yet. Here's the original code snippet I've experimenting with:

```zig
pub fn identQuote(comptime name: []const u8) []const u8 {
    const should_quote = comptime blk: {
        if (name.len > 0) switch (name[0]) {
            'a'...'z', 'A'...'Z' => {},
            else => break :blk true,
        };

        for (name[1..]) |c| {
            switch (c) {
                'a'...'z' => {},
                'A'...'Z' => {},
                '0'...'9' => {},
                '_' => {},
                else => break :blk true,
            }
        }

        break :blk false;
    };

    return comptime string: {
        if (should_quote) {
            break :string "\"" ++ name ++ "\"";
        } else {
            break :string name;
        }
    };
}

comptime {
    @compileLog(identQuote("foo"));
}
```

Output:
```
when analyzing /home/yohanan/a.zig:2:40 in compiler source at /home/vsts/work/1/s/src/stage1/ir.cpp:13362: thread 104446 panic: assertion failed. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Aborted (core dumped)
```

## Investigating

I tried making the function smaller so I could trace the bug and I came up with this small example:
```zig
pub fn something(comptime name: []const u8) bool {
    return comptime blk: {
        switch (name[0]) {
            else => break :blk true,
        }

        break :blk false;
    };
}

comptime {
    @compileLog(something("foo"));
}
```

If I remove the `comptime` from the `comptime blk:` the code seems to work okay but that wouldn't work on the initial code since it has compile-time string concatenation.

I feel like this has something to do with using multiple breaks on a comptime block - removing one of the `break :blk` statements makes the assertion failure go away. And here's a really minimal example that also throws the same assertion failure:

```zig
pub fn something() bool {
    return comptime blk: {
        break :blk true;
        break :blk false;
    };
}

comptime {
    @compileLog(something());
}
```

As for last, returning from the comptime block works fine, other than complaining about unreachable code being found, which is expected:

```zig
pub fn something() bool {
    comptime {
        return true;
        return false;
    }
}
```

If I remove one of the returns the other works, and branches seem to work well too:

```zig
const std = @import("std");

pub fn something(comptime a: bool) bool {
    comptime {
        if (a)
            return true
        else
            return false;
    }
}

test {
    var x = something(true);
    std.testing.expect(x);

    var y = something(false);
    std.testing.expect(!y);
}
```

## Workaround

As for the original code snippet I posted, I came up with a version that can be used as a workaround:

```zig
pub fn identQuote(comptime name: []const u8) []const u8 {
    comptime var should_quote: bool = false;

    comptime {
        if (name.len > 0) switch (name[0]) {
            'a'...'z', 'A'...'Z' => {},
            else => should_quote = true,
        };

        for (name[1..]) |c| {
            switch (c) {
                'a'...'z' => {},
                'A'...'Z' => {},
                '0'...'9' => {},
                '_' => {},
                else => should_quote = true,
            }
        }
    }

    return comptime string: {
        if (should_quote) {
            // TODO: escape special characters n' stuff
            break :string "\"" ++ name ++ "\"";
        } else {
            break :string name;
        }
    };
}

const std = @import("std");

test {
    const x: []const u8 = "foo";
    std.testing.expect(std.mem.eql(u8, x, comptime identQuote(x)));
}
```

Weirdly enough, the lower block (`return comptime string: {`) has no issues at all... I have no idea on what is happening here.

## Extra data

* OS: Arch Linux
* `uname -r`: 5.11.6-arch1-1
* `zig version`: 0.8.0-dev.1771+cc525bc00

**Comment by Vexu** [comment] 2021-04-20 17:07
Duplicate of #3376.

**Closed by Vexu** 2021-04-20 17:07 UTC
