### ISSUE TITLE
broken LLVM module found: Call parameter type does not match function signature

### ISSUE THREAD

**Issue by gegogi** [ziglang/zig#6431] opened 2020-09-26 16:54 UTC
When I compile my code, it fails with the following messages.
Where should I look? My code doesn't directly use ArrayListAligned.

```
PS D:\code\astro> zig build
Code Generation [709/717] std.fmt.formatText... broken LLVM module found: Call parameter type does not match function signature!
  %19 = getelementptr inbounds { %"[][*]const u8", i16 }, { %"[][*]const u8", i16 }* %0, i32 0, i32 0, !dbg !8999
 %"[][*:0]const u8"*  call fastcc void @"std.array_list.ArrayListAligned([*:0]const u8,null).toOwnedSlice"(%"[][*]const u8"* sret %19, %"std.array_list.ArrayListAligned([*:0]const u8,null)"* %extensions), !dbg !8999

This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
astro...The following command exited with error code 3:
D:\Code\zig\build\bin\zig.exe build-exe D:\code\astro\src\main.zig --library user32 --library kernel32 --library gdi32 --library shell32 --library vulkan-1 --library glfw3 --library c --c-source -std=c99 D:\code\astro\deps\stb_image\src\stb_image_impl.c --c-source -std=c99 D:\code\astro\deps\glad\src\glad.c --cache-dir D:\code\astro\zig-cache --name astro -I D:\Code1\VulkanSDK\1.2.148.1\Include -I D:\Code\vcpkg\installed\x64-windows-static\include -I D:\code\astro\deps\stb_image\include -I D:\code\astro\deps\glad\include -L D:\Code1\VulkanSDK\1.2.148.1\Lib -L D:\Code\vcpkg\installed\x64-windows-static\lib --cache on

Build failed. The following command failed:
D:\code\astro\zig-cache\o\MYD_uqCpXoLoHmj3wyBc-p0o96u7aSkRpu2H0AJPOjKooYEZbp7HYHdYmO05vdix\build.exe D:\Code\zig\build\bin\zig.exe D:\code\astro D:\code\astro\zig-cache
PS D:\code\astro>
```

**Comment by Vexu** [comment] 2020-09-26 17:07
Duplicate of #6416 

Finding the source of this error is a bit trickier but a good place to start would be checking for any usage of `File.readAllAlloc` and similar methods. Also note that `ArrayList` uses `ArrayListAligned`.

**Closed by Vexu** 2020-09-26 17:07 UTC
