### ISSUE TITLE
Semantic Analysis Out of Memory when testing std.zig

### ISSUE THREAD

**Issue by locriacyber** [ziglang/zig#10465] opened 2021-12-31 10:16 UTC
### Zig Version

0.10.0-dev.40+303bad998

### Steps to Reproduce

1. Use a machine with only 2GiB of memory
2. Clone and enter zig repository
3. run `zig test lib/std/std.zig --zig-lib-dir lib`

It's possible to test each package individually, but not together. It seems like Zig does not garbage collect in "Semantic Analysis [...]" phase.

### Expected Behavior

The command should work without using too much memory

### Actual Behavior

zig being killed by kernel for out of memory

**Comment by Vexu** [comment] 2021-12-31 17:45
Duplicate of #6485, stage2 handles resource usage better but is not ready for use yet.

**Closed by Vexu** 2021-12-31 17:45 UTC
Labels: bug
