### ISSUE TITLE
Compiler segfault when using simdjzon to parse json

### ISSUE THREAD

**Issue by sharpobject** [ziglang/zig#13869] opened 2022-12-10 10:58 UTC
### Zig Version

0.11.0-dev.661+d88eb75a6

### Steps to Reproduce and Observed Behavior

1. git clone https://github.com/sharpobject/simdjzon_segfault_demo
2. cd simdjzon_segfault_demo
3. zig build

output from a zig obtained from a tarball:
```
$ ~/repos/zig_tarball/zig-linux-x86_64-0.11.0-dev.661+d88eb75a6/zig build
error: simdjzon_segfault_demo...
error: The following command terminated unexpectedly:
/home/bluntsmoker/repos/zig_tarball/zig-linux-x86_64-0.11.0-dev.661+d88eb75a6/zig build-exe /home/bluntsmoker/repos/simdjzon_segfault_demo/src/main.zig --cache-dir /home/bluntsmoker/repos/simdjzon_segfault_demo/zig-cache --global-cache-dir /home/bluntsmoker/.cache/zig --name simdjzon_segfault_demo --enable-cache
error: the following build command failed with exit code 11:
/home/bluntsmoker/repos/simdjzon_segfault_demo/zig-cache/o/f9c2dbcd386bc5503ab54b44ccdb664a/build /home/bluntsmoker/repos/zig_tarball/zig-linux-x86_64-0.11.0-dev.661+d88eb75a6/zig /home/bluntsmoker/repos/simdjzon_segfault_demo /home/bluntsmoker/repos/simdjzon_segfault_demo/zig-cache /home/bluntsmoker/.cache/zig
```

output from a zig built from source, run under gdb:
```
$ gdb /home/bluntsmoker/repos/zig_install/build/stage3/bin/zig
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/bluntsmoker/repos/zig_install/build/stage3/bin/zig...
(gdb) r build-exe /home/bluntsmoker/repos/simdjzon_segfault_demo/src/main.zig --cache-dir /home/bluntsmoker/repos/simdjzon_segfault_demo/zig-cache --global-cache-dir /home/bluntsmoker/.cache/zig --name simdjzon_segfault_demo --enable-cache
Starting program: /home/bluntsmoker/repos/zig_install/build/stage3/bin/zig build-exe /home/bluntsmoker/repos/simdjzon_segfault_demo/src/main.zig --cache-dir /home/bluntsmoker/repos/simdjzon_segfault_demo/zig-cache --global-cache-dir /home/bluntsmoker/.cache/zig --name simdjzon_segfault_demo --enable-cache
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7c8d640 (LWP 2931120)]
[New Thread 0x7ffff6c8c640 (LWP 2931121)]
[New Thread 0x7ffff5c8b640 (LWP 2931122)]
[New Thread 0x7ffff4c8a640 (LWP 2931123)]
[New Thread 0x7ffff3c89640 (LWP 2931124)]
[New Thread 0x7ffff2c88640 (LWP 2931125)]
[New Thread 0x7ffff1c87640 (LWP 2931126)]
[New Thread 0x7ffff0c86640 (LWP 2931127)]
[New Thread 0x7fffefc85640 (LWP 2931128)]
[New Thread 0x7fffeec84640 (LWP 2931129)]
[New Thread 0x7fffedc83640 (LWP 2931130)]
[New Thread 0x7fffecc82640 (LWP 2931131)]
[New Thread 0x7fffebc81640 (LWP 2931132)]
[New Thread 0x7fffeac80640 (LWP 2931133)]
[New Thread 0x7fffe9c7f640 (LWP 2931134)]
[New Thread 0x7fffe8c7e640 (LWP 2931135)]

Thread 1 "zig" received signal SIGSEGV, Segmentation fault.
0x0000000005af4f6c in Air.typeOfIndex (air=..., inst=144436) at Air.zig:994
994	    const datas = air.instructions.items(.data);
(gdb) bt
#0  0x0000000005af4f6c in Air.typeOfIndex (air=..., inst=144436) at Air.zig:994
#1  0x000000000580bfd2 in Air.typeOf (air=..., inst=144512) at Air.zig:990
#2  0x0000000005606f43 in Sema.typeOf (sema=0x7ffffffb1100, inst=144512) at Sema.zig:31101
#3  0x000000000580c2e3 in Sema.coerceExtra (sema=0x7ffffffb1100, block=0x7ffffe001b50, dest_ty_unresolved=..., inst=144512, inst_src=..., opts=...) at Sema.zig:24135
#4  0x00000000056111c5 in Sema.coerce (sema=0x7ffffffb1100, block=0x7ffffe001b50, dest_ty_unresolved=<error reading variable: Cannot access memory at address 0x10>, inst=144512,
    inst_src=<error reading variable: Cannot access memory at address 0x10>) at Sema.zig:24080
#5  0x0000000005d81f42 in Sema.analyzeAsType (sema=0x7ffffffb1100, block=0x7ffffe001b50, src=..., air_inst=144512) at Sema.zig:1818
#6  0x0000000005d827a1 in Sema.getBuiltin (sema=0x7ffffffb1100, name=...) at Sema.zig:30721
#7  0x0000000005f11cee in Sema.safetyCheckFormatted (sema=0x7ffffffb1100, parent_block=0x7ffffe006e78, ok=144509, func=..., args=...) at Sema.zig:22487
#8  0x0000000005f119d9 in Sema.panicIndexOutOfBounds (sema=0x7ffffffb1100, parent_block=0x7ffffe006e78, index=144506, len=144508, cmp_op=cmp_lt) at Sema.zig:22378
#9  0x0000000006181882 in Sema.elemValSlice (sema=0x7ffffffb1100, block=0x7ffffe006e78, src=..., slice_src=..., slice=144504, elem_index_src=..., elem_index=144506)
    at Sema.zig:24009
#10 0x0000000005e3286f in Sema.elemVal (sema=0x7ffffffb1100, block=0x7ffffe006e78, src=..., indexable=144504, elem_index_uncasted=144506, elem_index_src=...) at Sema.zig:23671
#11 0x0000000005a16a70 in Sema.zirElemValNode (sema=0x7ffffffb1100, block=0x7ffffe006e78, inst=8574) at Sema.zig:9426
#12 0x00000000057dff86 in Sema.analyzeBodyInner (sema=0x7ffffffb1100, block=0x7ffffe006e78, body=...) at Sema.zig:932
#13 0x0000000005e801aa in Sema.resolveBlockBody (sema=0x7ffffffb1100, parent_block=0x7ffffe00c910, src=..., child_block=0x7ffffe006e78, body=..., body_inst=8560,
    merges=0x7ffffe006e40) at Sema.zig:5240
#14 0x0000000005ad3a9d in Sema.zirBlock (sema=0x7ffffffb1100, parent_block=0x7ffffe00c910, inst=8560) at Sema.zig:5223
#15 0x00000000057ee5e2 in Sema.analyzeBodyInner (sema=0x7ffffffb1100, block=0x7ffffe00c910, body=...) at Sema.zig:1449
#16 0x00000000059c5289 in Sema.analyzeBody (sema=0x7ffffffb1100, block=0x7ffffe00c910, body=...) at Sema.zig:798
#17 0x0000000005e44b50 in Sema.analyzeCall (sema=0x7ffffffb1100, block=0x7ffffe016ae8, func=144480, func_src=..., call_src=..., modifier=auto, ensure_result_used=false,
    uncasted_args=..., bound_arg_src=...) at Sema.zig:6597
#18 0x0000000005a10df7 in Sema.zirCall (sema=0x7ffffffb1100, block=0x7ffffe016ae8, inst=8391) at Sema.zig:6145
#19 0x00000000057df129 in Sema.analyzeBodyInner (sema=0x7ffffffb1100, block=0x7ffffe016ae8, body=...) at Sema.zig:916
#20 0x0000000005618ea2 in Sema.analyzeBodyBreak (sema=0x7ffffffb1100, block=0x7ffffe016ae8, body=...) at Sema.zig:815
#21 0x0000000005e3b744 in Sema.resolveBody (sema=0x7ffffffb1100, block=0x7ffffe016ae8, body=..., body_inst=8386) at Sema.zig:765
#22 0x0000000005a10912 in Sema.zirCall (sema=0x7ffffffb1100, block=0x7ffffe016ae8, inst=8386) at Sema.zig:6094
#23 0x00000000057df129 in Sema.analyzeBodyInner (sema=0x7ffffffb1100, block=0x7ffffe016ae8, body=...) at Sema.zig:916
#24 0x0000000005e801aa in Sema.resolveBlockBody (sema=0x7ffffffb1100, parent_block=0x7ffffe01c580, src=..., child_block=0x7ffffe016ae8, body=..., body_inst=8378,
    merges=0x7ffffe016ab0) at Sema.zig:5240
#25 0x0000000005ad3a9d in Sema.zirBlock (sema=0x7ffffffb1100, parent_block=0x7ffffe01c580, inst=8378) at Sema.zig:5223
#26 0x00000000057ee5e2 in Sema.analyzeBodyInner (sema=0x7ffffffb1100, block=0x7ffffe01c580, body=...) at Sema.zig:1449
#27 0x00000000059c5289 in Sema.analyzeBody (sema=0x7ffffffb1100, block=0x7ffffe01c580, body=...) at Sema.zig:798
#28 0x0000000005e44b50 in Sema.analyzeCall (sema=0x7ffffffb1100, block=0x7ffffe021a08, func=144451, func_src=..., call_src=..., modifier=auto, ensure_result_used=false,
    uncasted_args=..., bound_arg_src=...) at Sema.zig:6597
#29 0x0000000005a10ec4 in Sema.zirCall (sema=0x7ffffffb1100, block=0x7ffffe021a08, inst=9073) at Sema.zig:6112
#30 0x00000000057df129 in Sema.analyzeBodyInner (sema=0x7ffffffb1100, block=0x7ffffe021a08, body=...) at Sema.zig:916
#31 0x0000000005e801aa in Sema.resolveBlockBody (sema=0x7ffffffb1100, parent_block=0x7ffffe0274a0, src=..., child_block=0x7ffffe021a08, body=..., body_inst=9063,
    merges=0x7ffffe0219d0) at Sema.zig:5240
#32 0x0000000005ad3a9d in Sema.zirBlock (sema=0x7ffffffb1100, parent_block=0x7ffffe0274a0, inst=9063) at Sema.zig:5223
#33 0x00000000057ee5e2 in Sema.analyzeBodyInner (sema=0x7ffffffb1100, block=0x7ffffe0274a0, body=...) at Sema.zig:1449
#34 0x00000000059c5289 in Sema.analyzeBody (sema=0x7ffffffb1100, block=0x7ffffe0274a0, body=...) at Sema.zig:798
#35 0x0000000005e44b50 in Sema.analyzeCall (sema=0x7ffffffb1100, block=0x7ffffe02c928, func=144389, func_src=..., call_src=..., modifier=auto, ensure_result_used=false,
    uncasted_args=..., bound_arg_src=...) at Sema.zig:6597
#36 0x0000000005a10df7 in Sema.zirCall (sema=0x7ffffffb1100, block=0x7ffffe02c928, inst=8021) at Sema.zig:6145
#37 0x00000000057df129 in Sema.analyzeBodyInner (sema=0x7ffffffb1100, block=0x7ffffe02c928, body=...) at Sema.zig:916
#38 0x0000000005e801aa in Sema.resolveBlockBody (sema=0x7ffffffb1100, parent_block=0x7ffffe031010, src=..., child_block=0x7ffffe02c928, body=..., body_inst=8015,
    merges=0x7ffffe02c8f0) at Sema.zig:5240
#39 0x0000000005ad3a9d in Sema.zirBlock (sema=0x7ffffffb1100, parent_block=0x7ffffe031010, inst=8015) at Sema.zig:5223
#40 0x00000000057ee5e2 in Sema.analyzeBodyInner (sema=0x7ffffffb1100, block=0x7ffffe031010, body=...) at Sema.zig:1449
#41 0x0000000005e7b5ec in Sema.analyzeBodyRuntimeBreak (sema=0x7ffffffb1100, block=0x7ffffe031010, body=...) at Sema.zig:779
#42 0x0000000005ad6102 in Sema.zirCondbr (sema=0x7ffffffb1100, parent_block=0x7ffffe0356c8, inst=8012) at Sema.zig:16341
```

### Expected Behavior

The compiler does not segfault. Probably it should complain about various intrinsics not being available given that build.zig does not set a target that includes these SIMD extensions, or about various C things being missing given that the build.zig does not set these things up properly either.

**Comment by sharpobject** [comment] 2022-12-12 02:11
I think this input reduces to:
```zig
inline fn a() void {
    a();
}
pub fn main() !void {
    @setEvalBranchQuota(1_000_000);
    a();
}
```

**Comment by Vexu** [comment] 2022-12-15 15:58
In that case this is a duplicate of #12973

**Closed by Vexu** 2022-12-15 15:58 UTC
Labels: bug
