### ISSUE TITLE
File path missing from SourceLocation on Zig master

### ISSUE THREAD

**Issue by mnemnion** [ziglang/zig#20941] opened 2024-08-04 17:31 UTC
### Zig Version

0.14.0-dev.621+66b71273a

### Steps to Reproduce and Observed Behavior

Create a file `src/file.zig`. 

Add the following test:

```zig
test "source location" {
    const loc = @src();
    std.debug.print("location: {s}\n", .{loc.file});
}
```

### Expected Behavior

Expected: in Zig 0.13.0, the test prints `src/file.zig`.

With Zig `0.14.0-dev.621+66b71273a`, it prints `file.zig`. 

This breaks [ohsnap](https://github.com/mnemnion/ohsnap)'s ability to find and replace snapshots in a test.  The code which breaks is directly copied from TigerBeetle, so they'll be having the same issue.

**Comment by Rexicon226** [comment] 2024-08-04 17:36
duplicate of #20864

**Comment by mnemnion** [comment] 2024-08-04 17:40
I was only looking in open issues, because this problem is very much an open issue.

**Comment by kassane** [comment] 2024-08-07 00:02
Maybe similar to:

```zig
pub fn buildZigCC(b: *std.Build, target_options: *std.Build.Step.Options) *std.Build.Step.Compile {
    const exe = b.addExecutable(.{
        .name = "zcc",
        .target = b.graph.host,
        .optimize = .ReleaseSafe,
        .root_source_file = .{.cwd_relative = b.pathJoin(&.{
            rootPath(b),
            "tools",
            "zigcc.zig",
        }) },
    });
    std.debug.print("path: {s}\n", .{exe.root_module.root_source_file.?.getPath(b)});
    exe.root_module.addOptions("build_options", target_options);
    return exe;
}
fn rootPath() []const u8 {
    // not get filename from @src().file
    const src_path = comptime std.fs.path.dirname(@src().file) orelse
        @panic("@src().file not found");
    // get absolute path
    return src_path ++ std.fs.path.sep_str ++ "..";
}
```
**Output:**

```bash
## v0.13.0 (std.fs.path.dirname)
path: /home/kassane/.cache/zig/p/12205c2a6099046fa020851815379856632203d1f4ed7b9eee7015a60fa6736c0b66/tools/zigcc.zig

## v0.14.0-dev (std.fs.path.dirname)
path: tools/zigcc.zig
```

### Reference

- https://ziggit.dev/t/how-to-get-fullpath-on-build-zig-from-v0-14-0-dev/5469

**Comment by andrewrk** [comment] 2024-08-07 03:43
duplicate of #20864

**Closed by andrewrk** 2024-08-07 03:43 UTC
Labels: bug
