### ISSUE TITLE
[zig fmt] confusing formatting of if/else expressions in switch branches

### ISSUE THREAD

**Issue by InfiniteRain** [ziglang/zig#19350] opened 2024-03-18 19:55 UTC
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

I have a switch that has an `if`/`else` expression in one of the branches, and it gets formatted like this:

```zig
    pub fn identifierType(self: *Self) TokenType {
        return switch (self.source[self.start]) {
            'a' => self.checkKeyword(1, "nd", ._and),
            'c' => self.checkKeyword(1, "lass", .class),
            'e' => self.checkKeyword(1, "lse", ._else),
            'f' => if (self.current - self.start > 1)
                switch (self.source[self.start + 1]) {
                    'a' => self.checkKeyword(2, "lse", .false),
                    'o' => self.checkKeyword(2, "r", ._for),
                    'u' => self.checkKeyword(2, "n", .fun),
                    else => .identifier,
                }
            else
                .identifier,
            'i' => self.checkKeyword(1, "f", ._if),
            'n' => self.checkKeyword(1, "il", .nil),
            'o' => self.checkKeyword(1, "r", ._or),
            'p' => self.checkKeyword(1, "rint", .print),
            'r' => self.checkKeyword(1, "eturn", ._return),
            's' => self.checkKeyword(1, "uper", .super),
            'v' => self.checkKeyword(1, "ar", ._var),
            'w' => self.checkKeyword(1, "hile", ._while),
            else => .identifier,
        };
    }
```

Visually, `else` for the `if` and `else` for the `switch` are located on exactly the same level of indentation, which can be visually confusing.

### Expected Behavior

I propose the following way to format instead:

```zig
    pub fn identifierType(self: *Self) TokenType {
        return switch (self.source[self.start]) {
            'a' => self.checkKeyword(1, "nd", ._and),
            'c' => self.checkKeyword(1, "lass", .class),
            'e' => self.checkKeyword(1, "lse", ._else),
            'f' => 
                if (self.current - self.start > 1)
                    switch (self.source[self.start + 1]) {
                        'a' => self.checkKeyword(2, "lse", .false),
                        'o' => self.checkKeyword(2, "r", ._for),
                        'u' => self.checkKeyword(2, "n", .fun),
                        else => .identifier,
                    }
                else
                    .identifier,
            'i' => self.checkKeyword(1, "f", ._if),
            'n' => self.checkKeyword(1, "il", .nil),
            'o' => self.checkKeyword(1, "r", ._or),
            'p' => self.checkKeyword(1, "rint", .print),
            'r' => self.checkKeyword(1, "eturn", ._return),
            's' => self.checkKeyword(1, "uper", .super),
            'v' => self.checkKeyword(1, "ar", ._var),
            'w' => self.checkKeyword(1, "hile", ._while),
            else => .identifier,
        };
    }
```

This indentation makes it easier to differentiate the what `else` branches belong to.

**Comment by castholm** [comment] 2024-03-18 20:03
Duplicate of #5777
Also relevant: #7363

**Closed** 2024-03-18 20:16 UTC
Labels: bug
