### ISSUE TITLE
std.fmt.fmtIntSizeDec() and fmtIntSizeBin() do not consider FormatOptions

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#9184] opened 2021-06-21 03:05 UTC
Ultimately `formatSizeImpl()` is used to implement `fmtIntSizeDec()` or `fmtIntSizeBin()` and it does not consider FormatOptions and probably should.

motivating example (from @espindola  via IRC):
```zig
const std = @import("std");

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();

    var buf: [32]u8 = undefined;
    var slice = buf[0..];
    const partial = try std.fmt.bufPrint(slice, "{}", .{std.fmt.fmtIntSizeDec(42 * 1000)});

    try stdout.print("X {s:<14} Y\n", .{partial});
    try stdout.print("X {:<14} Y\n", .{std.fmt.fmtIntSizeDec(42 * 1000)});
}
```

```sh
$ zig run foo.zig
X 42kB           Y
X 42kB Y
```

@andrewrk you mentioned in IRC:
```
it should also be renamed to remove the redundant fmt
```

There is a pattern in `std.fmt` where all `pub fn fmt*()` functions return a `Formatter()` object; a grep follows. Do you want these  renamed like `fmtFirstSecond()` → `firstSecond()`?
```
pub fn fmtSliceHexLower(bytes: []const u8) std.fmt.Formatter(formatSliceHexLower) {
pub fn fmtSliceHexUpper(bytes: []const u8) std.fmt.Formatter(formatSliceHexUpper) {
pub fn fmtSliceEscapeLower(bytes: []const u8) std.fmt.Formatter(formatSliceEscapeLower) {
pub fn fmtSliceEscapeUpper(bytes: []const u8) std.fmt.Formatter(formatSliceEscapeUpper) {
pub fn fmtIntSizeDec(value: u64) std.fmt.Formatter(formatSizeDec) {
pub fn fmtIntSizeBin(value: u64) std.fmt.Formatter(formatSizeBin) {
pub fn fmtDuration(ns: u64) Formatter(formatDuration) {
```

**Comment by yujiri8** [comment] 2022-07-16 04:44
Another issue where it seems like a PR has been merged but the issue is still open. Can this be closed?

**Comment by Vexu** [comment] 2022-07-16 09:05
That PR did not address this issue.

**Comment by yujiri8** [comment] 2022-07-17 05:40
Oh, I see - that PR handled a similar issue with different functions. I'll see if I can do this one myself.

**Closed** 2022-07-21 15:41 UTC
Labels: enhancement, contributor friendly, standard library
