### ISSUE TITLE
Undefined struct fields not always set to 0xaa in debug

### ISSUE THREAD

**Issue by Srekel** [ziglang/zig#4846] opened 2020-03-29 10:03 UTC
I'm not 100% this is a bug per se, but it is inconsistent and if intended, I feel it ought to be clarified in the documentation. It currently states:

> In Debug mode, Zig writes 0xaa bytes to undefined memory. 

Compare:

```zig

pub const Test1 = struct {
    foo: u8 = undefined,
};

pub const Test2 = struct {
    foo: u8 = undefined,
    bar: u8 = 0,
};

pub fn TestFn3() type {
    return struct {
        foo: [1]u8 = undefined,
    };
}

pub fn TestFn4() type {
    return struct {
        foo: [1]u8 = undefined,
        bar: u8 = 0,
    };
}

test "undefined_test" {
    var test1a: Test1 = undefined;
    var test1b = Test1{};
    var test2a: Test2 = undefined;
    var test2b = Test2{};
    var test3a: TestFn3() = undefined;
    var test3b = TestFn3(){};
    var test4a: TestFn4() = undefined;
    var test4b = TestFn4(){};
    std.debug.warn("\n", .{});
    std.debug.warn("test1a {}\n", .{test1a.foo});
    std.debug.warn("test1b {}\n", .{test1b.foo});
    std.debug.warn("test2a {}\n", .{test2a.foo});
    std.debug.warn("test2b {}\n", .{test2b.foo});
    std.debug.warn("test3a {}\n", .{test3a.foo[0]});
    std.debug.warn("test3b {}\n", .{test3b.foo[0]});
    std.debug.warn("test4a {}\n", .{test4a.foo[0]});
    std.debug.warn("test4b {}\n", .{test4b.foo[0]});
}

```

This outputs:
```
1/1 test "undefined_test"...
test1a 170
test1b 170
test2a 170
test2b 0
test3a 170
test3b 170
test4a 170
test4b 0
OK
All 1 tests passed.
```

Seems a bit related to #1987.

**Comment by andrewrk** [comment] 2020-03-29 14:26
Yes this is a duplicate of #1987

**Closed by andrewrk** 2020-03-29 14:26 UTC
