### ISSUE TITLE
make @cImport take comptime []u8 instead of an expression

### ISSUE THREAD

**Issue by ontes** [ziglang/zig#9332] opened 2021-07-08 08:29 UTC
I'm learning Zig and I noticed that `@cImport` takes some arbitrary type `expression`, which seems quite confusing for me.
As an expansion of #2070 I propose that `@cImport` should take `comptime []u8` c code as an argument. 

This will produce to syntax like this:
```zig
// one line syntax
const c1 = @cImport("#include <header1.h>");
// multi-line string
const c2 = @cImport(
    \\#define INCLUDE_PROTOTYPES
    \\#include <header2.h>
);
// zig embedding
const c3 = @cImport(@embedFile("header3.h"));
// arbitrary code
const c4 = @cImport(
    \\extern int myFunction(void);
);
```
`@cInclude`, `@cDefine` and `@cUndef` could be removed.

**Comment by zigazeljko** [comment] 2021-07-08 13:44
Would `@cImport` then accept arbitrary comptime expressions or just string literals (like #2206)?

**Comment by g-w1** [comment] 2021-07-09 11:42
Also see https://github.com/ziglang/zig/issues/2070 , this may be a duplicate.

**Comment by ehaas** [comment] 2021-07-09 20:42
This makes the common-case simpler but also makes it uglier to use compile-time computations to control the C code that is compiled (you'd have to explicitly concat the strings yourself) - e.g. the second example here https://ziglang.org/documentation/0.8.0/#Import-from-C-Header-File

I think I prefer the proposal in #2070 for achieving the goal of this proposal.

I do agree that `@cImport` is a bit confusing at first, because it reuses function call syntax even though you're not really calling a function and passing it a value; you're starting a new C source buffer and telling the compiler how to build that buffer at compile-time using code that is lexically inside the "function call"

**Comment by nektro** [comment] 2021-07-10 07:52
The 3 functions you proposed removing are critical for Zig's C interop. Please read the documentation before making such large proposals.

**Comment by ifreund** [comment] 2021-07-10 08:10
> The 3 functions you proposed removing are critical for Zig's C interop. Please read the documentation before making such large proposals.

@nektro the proposed changes would not remove any functionality, they map directly to c preprocessor directives which could be used in the proposed `@cImport()`. In fact, the implementation of the status quo set of builtins works by generating a snippet of C source code based on the contents of the `@cImport()` then runs translate-c on that.

**Comment by ontes** [comment] 2021-07-10 09:34
> This makes the common-case simpler but also makes it uglier to use compile-time computations to control the C code that is compiled (you'd have to explicitly concat the strings yourself) - e.g. the second example here https://ziglang.org/documentation/0.8.0/#Import-from-C-Header-File

@ehaas Yeah, you are right. It may actually be uglier in some cases. But it would still be possible. (And maybe we could add library functions to make it easier.) For me it still seems like much cleaner way of doing it, because we would use comptime language features instead of compiler magic.

> Would `@cImport` then accept arbitrary comptime expressions or just string literals (like #2206)?

@zigazeljko Full comptime expressions would be necessary to keep the example mentioned by @ehaas possible.

**Comment by andrewrk** [comment] 2021-11-24 01:19
Duplicate of  #2070

**Closed by andrewrk** 2021-11-24 01:19 UTC
Labels: proposal
