### ISSUE TITLE
Not enough stack information when accidentally `free`ing a single pointer

### ISSUE THREAD

**Issue by courajs** [ziglang/zig#16956] opened 2023-08-25 17:13 UTC
### Zig Version

0.12.0-dev.167+dd6a9caea

### Steps to Reproduce and Observed Output

https://github.com/courajs/sliceAsBytes_generics_bad_msg/tree/main

```zig
const std = @import("std");

test "Thing" {
    const alloc = std.testing.allocator;
    var thing = try alloc.create(u8);
    alloc.free(thing);
}
```

`zig build test`

```
zig test Debug native: error: the following command failed with 1 compilation errors:
/Users/aaron/install/zig/zig-macos-aarch64-0.12.0-dev.167+dd6a9caea/zig test /Users/aaron/dev/zig/sliceAsBytes_generics_bad_msg/src/main.zig --cache-dir /Users/aaron/dev/zig/sliceAsBytes_generics_bad_msg/zig-cache --global-cache-dir /Users/aaron/.cache/zig --name test --listen=-
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
test transitive failure
└─ run test transitive failure
   └─ zig test Debug native 1 errors
/Users/aaron/install/zig/zig-macos-aarch64-0.12.0-dev.167+dd6a9caea/lib/std/mem.zig:4143:9: error: expected []T or *[_]T, passed *u8
        @compileError("expected []T or *[_]T, passed " ++ @typeName(Slice));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/aaron/install/zig/zig-macos-aarch64-0.12.0-dev.167+dd6a9caea/lib/std/mem.zig:4150:59: note: called from here
pub fn sliceAsBytes(slice: anytype) SliceAsBytesReturnType(@TypeOf(slice)) {
                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~

shell returned 2
```

### Expected Output

The error message should include information about the original user code triggering this error.

Duplicate of closed issue https://github.com/ziglang/zig/issues/15124 which has not actually been fixed

**Comment by jacobly0** [comment] 2023-08-25 18:08
Duplicate of #15124

**Closed by jacobly0** 2023-08-25 18:08 UTC
Labels: error message
