### ISSUE TITLE
a = @Call(.{}, b, .{c}) is not equivalent to a = b(c)

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#4850] opened 2020-03-30 00:19 UTC
I was poking around in std.mem.zeroes related to https://github.com/ziglang/zig/issues/4847#issuecomment-605721461.

Original code:
```zig
element.* = zeroes(info.child);
```
Broken code:
```zig
element.* = @call(.{}, zeroes, .{info.child});
```
This results in this error, repeatedly.
```
\zig\std\mem.zig:347:36: error: cannot assign to constant
                element.* = @call(.{}, zeroes, .{info.child});
                                   ^
.\main.zig:2:32: note: called from here
export var foo = std.mem.zeroes([500]u8)
                               ^
.\main.zig:2:32: note: called from here
export var foo = std.mem.zeroes([500]u8)
                               ^
.\main.zig:2:32: note: referenced here
export var foo = std.mem.zeroes([500]u8)
                               ^
```
This is broken in the same way, despite the docs saying .auto is equivalent to function call syntax.
```zig
element.* = @call(.{.modifier = .auto}, zeroes, .{info.child});
```

**Comment by Sobeston** [comment] 2020-03-30 00:57
Related, possible duplicate of https://github.com/ziglang/zig/issues/4639. Thanks fengb on the discord for pointing it out.

**Comment by Schroedingers-Hat** [comment] 2020-03-30 01:45
Seems very comptime related. Goes away again if you do this.
```
                comptime const opts = builtin.CallOptions{};
                element.* = @call(opts, zeroes, .{info.child});
```
Very nearly unrelated bikeshedding, but there are two spellings of zeros/zeroes in the stdlib.

Quick grep of llvm source indicates that zeros is the more common one there.

**Comment by Schroedingers-Hat** [comment] 2020-03-30 01:49
Comes back if you do this:
`                element.* = @call(builtin.CallOptions{}, zeroes, .{info.child});`

**Comment by Vexu** [comment] 2022-12-31 11:31
No test case, closing as duplicate of #4639

**Closed by Vexu** 2022-12-31 11:31 UTC
Labels: bug, stage1
