### ISSUE TITLE
When define array in packed struct, field address incorrect.

### ISSUE THREAD

**Issue by loganliug** [ziglang/zig#12329] opened 2022-08-04 06:43 UTC
### Zig Version

0.10.0-dev.3394+1a1b7a3af

### Steps to Reproduce

```
const std = @import("std");
pub fn main() !void {
    const S = packed struct {
        a: u32,
        b: [9]u8,
        c: u8,
        d: u32,
    };
    var s: S = undefined;
    std.debug.print("{}\n{}\n{}\n{}\n", .{
        @ptrToInt(&s.a),
        @ptrToInt(&s.b),
        @ptrToInt(&s.c),
        @ptrToInt(&s.d),
    });
}
```

### Expected Behavior

140737141157688
140737141157692
140737141157701
140737141157702

### Actual Behavior

140737141157688
140737141157692
140737141157692
140737141157692

**Comment by Vexu** [comment] 2022-08-04 07:46
Duplicate of #2627

**Closed by Vexu** 2022-08-04 07:46 UTC
Labels: bug
