### ISSUE TITLE
control flow attempts to use compile-time variable at runtime

### ISSUE THREAD

**Issue by vrischmann** [ziglang/zig#5149] opened 2020-04-23 17:31 UTC
Hello,

I'm unsure if this a bug or if I'm doing something wrong but I think it's a bug.

I'm getting the following compile error:
```
./src/main.zig:80:40: error: control flow attempts to use compile-time variable at runtime
            @field(args, field_name) = try self.readType(column_spec, column_data, struct_field.field_type);
                                       ^
./src/main.zig:146:37: note: called from here
    testing.expect(try iterator.scan(row));
                                    ^
./src/main.zig:169:25: note: called from here
    try testIteratorScan(&arena.allocator, column_specs, test_data, &row);
                        ^
./src/main.zig:149:29: note: called from here
pub fn main() anyerror!void {
                            ^
./src/main.zig:71:68: note: compile-time variable assigned here
        inline for (@typeInfo(child).Struct.fields) |struct_field, _i| {
                                                                   ^
./src/main.zig:146:37: note: referenced here
    testing.expect(try iterator.scan(row));
                                    ^
./src/main.zig:146:20: note: referenced here
    testing.expect(try iterator.scan(row));
                   ^
./src/main.zig:169:5: note: referenced here
    try testIteratorScan(&arena.allocator, column_specs, test_data, &row);
```

using the following code (it's kinda long, sorry):
```
const std = @import("std");
const mem = std.mem;
const heap = std.heap;
const testing = std.testing;

pub const ColumnData = struct {
    slice: []const u8,
};

pub const RowData = struct {
    slice: []ColumnData,
};

pub const ColumnSpec = struct {
    keyspace: ?[]const u8,
    table: ?[]const u8,
    name: []const u8,

    option: OptionID,

    listset_element_type_option: ?OptionID,
};

pub const RowsMetadata = struct {
    column_specs: []const ColumnSpec,
};

pub const OptionID = packed enum(u16) {
    Int = 0x0009,
    UUID = 0x000C,
    Tinyint = 0x0014,
    List = 0x0020,
    Set = 0x0022,
};

pub const Iterator = struct {
    const Self = @This();

    arena: heap.ArenaAllocator,
    metadata: RowsMetadata,
    rows: []const RowData,

    pos: usize,

    pub fn deinit(self: Self) void {
        self.arena.deinit();
    }

    pub fn init(allocator: *mem.Allocator, metadata: RowsMetadata, rows: []const RowData) Self {
        return Self{
            .arena = heap.ArenaAllocator.init(allocator),
            .metadata = metadata,
            .rows = rows,
            .pos = 0,
        };
    }

    pub fn scan(self: *Self, args: var) !bool {
        const child = switch (@typeInfo(@TypeOf(args))) {
            .Pointer => |info| info.child,
            else => @compileError("Expected a pointer to a tuple or struct, found " ++ @typeName(@TypeOf(args))),
        };
        if (@typeInfo(child) != .Struct) {
            @compileError("Expected tuple or struct argument, found " ++ @typeName(child) ++ " of type " ++ @tagName(@typeInfo(child)));
        }

        if (self.pos >= self.rows.len) {
            return false;
        }

        inline for (@typeInfo(child).Struct.fields) |struct_field, _i| {
            const i = @as(usize, _i);

            const field_type_info = @typeInfo(struct_field.field_type);
            const field_name = struct_field.name;

            const column_spec = self.metadata.column_specs[i];
            const column_data: []const u8 = self.rows[self.pos].slice[i].slice;

            @field(args, field_name) = try self.readType(column_spec, column_data, struct_field.field_type);
        }

        self.pos += 1;

        return true;
    }

    fn readType(self: *Self, column_spec: ColumnSpec, column_data: []const u8, comptime Type: type) !Type {
        const type_info = @typeInfo(Type);

        const option = column_spec.option;

        switch (type_info) {
            .Int => return try self.readInt(option, column_data, Type),
            .Pointer => |pointer| switch (pointer.size) {
                .Slice => {
                    return try self.readSlice(column_spec, column_data, Type);
                },
                else => @compileError("invalid pointer size " ++ @tagName(pointer.size)),
            },
            .Array => return try self.readArray(option, column_data, Type),
            else => @compileError("field type " ++ @typeName(Type) ++ " not handled yet"),
        }
    }

    fn readInt(self: *Self, option: OptionID, column_data: []const u8, comptime Type: type) !Type {
        var r: Type = 0;
        return r;
    }

    fn readSlice(self: *Self, column_spec: ColumnSpec, column_data: []const u8, comptime Type: type) !Type {
        if (column_spec.listset_element_type_option == null) {
            return error.InvalidColumnSpec;
        }

        var slice: Type = undefined;
        return slice;
    }
};

fn columnSpec(id: OptionID) ColumnSpec {
    return ColumnSpec{
        .keyspace = null,
        .table = null,
        .name = "name",
        .option = id,
        .listset_element_type_option = null,
    };
}

fn testIteratorScan(allocator: *mem.Allocator, column_specs: []ColumnSpec, data: []const []const u8, row: var) !void {
    const metadata = RowsMetadata{
        .column_specs = column_specs,
    };

    var column_data = std.ArrayList(ColumnData).init(allocator);
    for (data) |d| {
        _ = try column_data.append(ColumnData{ .slice = d });
    }

    const row_data = &[_]RowData{
        RowData{ .slice = column_data.toOwnedSlice() },
    };

    var iterator = Iterator.init(allocator, metadata, row_data);
    testing.expect(try iterator.scan(row));
}

pub fn main() anyerror!void {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();

    const Row = struct {
        age: u32,
        set: []u8,
    };
    var row: Row = undefined;

    var spec1 = columnSpec(.Set);
    spec1.listset_element_type_option = .Tinyint;
    var spec2 = columnSpec(.Tinyint);

    const column_specs = &[_]ColumnSpec{ spec2, spec1 };
    const test_data = &[_][]const u8{
        "\x00\x00\x20\x00",
        "\x00\x00\x00\x02\x00\x00\x00\x01\x20\x00\x00\x00\x01\x21",
    };

    try testIteratorScan(&arena.allocator, column_specs, test_data, &row);
}
```

however if you move the `age: u32` field below `set: []u8` it compiles fine:

```
const Row = struct {
        set: []u8,
        age: u32,
    };
```

I would expect both cases to work the same.

You can test here https://gcc.godbolt.org/z/-EnC8A

**Comment by tauoverpi** [comment] 2020-08-07 21:31
Same issue with https://gcc.godbolt.org/z/vsjE6z

```
const std = @import("std");
const mem = std.mem;
const testing = std.testing;
const SplitIterator = mem.SplitIterator;

pub fn main() !void {
    //  error: control flow attempts to use compile-time variable at runtime
    const T = struct {  b: []const u8,  c: enum { ok, no },d: []const u8 };
    // works
    //const T = struct {  c: enum { ok, no }, b: []const u8, d: []const u8 };
    var it = std.mem.split("", &[_]u8{','});
    _ = try parseLineInternal(T, &it);

}

fn parseColumnInternal(comptime T: type, text: []const u8) !T {
    switch (@typeInfo(T)) {
        .Enum => return std.meta.stringToEnum(T, text) orelse
            error.UnexpectedEndOfRow,

        .Pointer => return text,

        else => @compileError("unsupported type: " ++ @typeName(T)),
    }
}


fn parseLineInternal(comptime T: type, it: *SplitIterator) !T {
    switch (@typeInfo(T)) {
        .Struct => |info| {
            var r: T = undefined; // computed.result;
            inline for (info.fields) |field| {
                const slice = it.next() orelse return error.UnexpectedEndOfRow;
                if (field.field_type != void) {
                    @field(r, field.name) = try parseColumnInternal(field.field_type, slice);
                }
            }
            return r;
        }, else => @compileError(""),
    }
}
```

**Comment by michaelbartnett** [comment] 2021-01-02 20:02
Possibly another case of the same bug?

https://godbolt.org/z/YfajsM

```zig
const std = @import("std");
const meta = std.meta;
const trait = meta.trait;
const Allocator = std.mem.Allocator;

fn parseArg(comptime ArgType: type, alloc: *Allocator, token: []const u8) !ArgType {
    comptime const argtype_info = @typeInfo(ArgType);
    if (comptime ArgType == []const u8){
        return token;
    } else {
        switch (comptime argtype_info) {
            .Int => return std.fmt.parseInt(ArgType, token, 10),
            .Optional => |opt| if (std.mem.eql(u8, token, "null")) {
                    return null;
                } else {
/////////////////// what i expected to be able to do:
                    return try parseArg(opt.child, alloc, token);

/////////////////// what I had to do:
                    // return @as(anyerror!ArgType, parseArg(opt.child, alloc, token) catch |e| e);

                },
            else => return error.ArgTypeNotSupported,
        }
    }
}

const Commands = struct {
    pub fn generic(x: anytype) void {
        std.debug.print("this is a generic function\n", .{});
    }

    pub fn square(num: ?i32) void {
        if (num) |n| {
            std.debug.print("{} squared is {}!\n", .{n, n * n});
        } else {
            std.debug.print("Can't square nothin\n", .{});
        }
    }
};

fn doThing(alloc: *Allocator, token: []const u8, cmds: anytype) bool {
    {
        var arg = parseArg(?i32, alloc, "42") catch |e| return false;
        std.debug.print("arg is {}\n", .{arg});
    }
    inline for (meta.declarations(Commands)) |decl| {
        comptime var fn_arg0 = @typeInfo(decl.data.Fn.fn_type).Fn.args[0].arg_type orelse []const u8;
        var arg = parseArg(fn_arg0, alloc, token) catch |e| { return false; };
        std.debug.print("fn is {}, arg is {}, arg type is {}\n", .{decl.name, arg, @typeName(fn_arg0)});
    }
    return true;
}

pub fn main() !void {  
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};  
    var alloc = &gpa.allocator;
    var cmds = Commands{};
    _ = doThing(alloc, "42", cmds);
}
```

```
<source>:49:51: error: control flow attempts to use compile-time variable at runtime
        var arg = parseArg(fn_arg0, alloc, token) catch |e| { return false; };
                                                  ^
<source>:59:16: note: called from here
    _ = doThing(alloc, "42", cmds);
               ^
<source>:55:21: note: called from here
pub fn main() !void {  
                    ^
<source>:47:12: note: compile-time variable assigned here
    inline for (meta.declarations(Commands)) |decl| {
           ^
<source>:59:16: note: referenced here
    _ = doThing(alloc, "42", cmds);
               ^
ASM generation compiler returned: 1
<source>:49:51: error: control flow attempts to use compile-time variable at runtime
        var arg = parseArg(fn_arg0, alloc, token) catch |e| { return false; };
                                                  ^
<source>:59:16: note: called from here
    _ = doThing(alloc, "42", cmds);
               ^
<source>:55:21: note: called from here
pub fn main() !void {  
                    ^
<source>:47:12: note: compile-time variable assigned here
    inline for (meta.declarations(Commands)) |decl| {
           ^
<source>:59:16: note: referenced here
    _ = doThing(alloc, "42", cmds);
               ^
Execution build compiler returned: 1
```

**Comment by SpexGuy** [comment] 2021-04-27 18:37
I was able to build what I think is the minimal repro:
```zig
pub fn main() anyerror!void {
    inline for (.{0, 1}) |i| {
        try inner(i);
    }
}

fn inner(comptime i: comptime_int)
    if (i == 0) error{}!void
    else error{Foobar}!void
{
    return undefined;
}
```
The bug seems to be caused by an inline for which calls a function that returns an error union with an empty error set in the first iteration, and an error union with nonempty error sets in future iterations.

**Comment by Hadron67** [comment] 2021-05-30 06:26
Running into a similar issue when using comptime reflection, minimal repro:
```zig
fn inner(aaa: bool) void {
    inline for (.{u8, u16, u32, u64}) |val| {
        const h = if (comptime val == u16) aaa else false;
        if (!h){
            std.debug.print("hkm\n", .{});
        }
    }
}

pub fn main() !void {
    inner(true);
}
```
And yes, it seems to happen only if the rhs of the comparison at line 3 is not the first element of the array. If I change it to `u8`, the error doesnt occur.

**Comment by hronro** [comment] 2022-01-24 06:52
I'm facing the same error.

Whether this a bug or I'm doing something wrong, I think if the compiler could print which comptime variable is used at runtime, this would help a lot.

**Comment by Vexu** [comment] 2024-03-26 09:12
This seems to be fixed in master branch.

**Closed by Vexu** 2024-03-26 09:12 UTC
Labels: bug
