### ISSUE TITLE
Poor code generation when using packed struct for MMIO registers

### ISSUE THREAD

**Issue by tcrs** [ziglang/zig#8981] opened 2021-06-03 19:36 UTC
I'm experimenting with using Zig on an STM32F4 board I have. I have been experimenting using packed structs to read/write MMIO registers (inspired by https://scattered-thoughts.net/writing/mmio-in-zig/). I noticed the assembly being generated didn't look very efficient. I created this small example which does a read-modify-write on a fictional 8bit register (you can play with the code here: https://godbolt.org/z/soKcv9GWe):

```
const T = packed struct {
 a : u1,
 b : u3,
 c : u1,
 d : u3
};

const ptr = @intToPtr(* volatile u8, 99);

pub fn modify(comptime RegType : type, p : *volatile u8, new : anytype) void {
    var old = @bitCast(RegType, p.*);
    const info = @typeInfo(@TypeOf(new));
    inline for(info.Struct.fields) |field| {
        @field(old, field.name) = @field(new, field.name);
    }
    p.* = @bitCast(@TypeOf(p.*), old);
}

pub fn modify_mask(comptime RegType : type, p : *volatile u8, new : anytype) void {
    const info = @typeInfo(@TypeOf(new));
    var x : RegType = undefined;
    const RawType = @TypeOf(p.*);
    var old = p.*;
    inline for(info.Struct.fields) |field| {
        const DestType = @TypeOf(@field(x, field.name));
        const off = @bitOffsetOf(RegType, field.name);
        const width = @typeInfo(DestType).Int.bits;
        const mask : RawType = ((1 << width) - 1);
        const val : RawType = @as(DestType, @field(new, field.name));
        old = (old & ~(mask << off)) | ((val & mask) << off);
    }
    p.* = old;
}

export fn main() callconv(.C) void {
    modify(T, ptr, .{.a = 1, .b = 0});
    modify_mask(T, ptr, .{.a = 1, .b = 0});
}
```

This is the code generated for `modify` (looks inefficient)
```
main:
        sub     sp, sp, #4
        mov     r0, #99
        ldrb    r1, [r0]
        and     r1, r1, #240
        orr     r1, r1, #1
        strb    r1, [sp, #3]
        ldrb    r1, [sp, #3]
        strb    r1, [r0]
        add     sp, sp, #4
        bx      lr
```

and this for `modify_mask` (looks good)
```
main:
        mov     r0, #99
        ldrb    r1, [r0]
        and     r1, r1, #240
        orr     r1, r1, #1
        strb    r1, [r0]
        bx      lr
```

(to generate those assembly examples I've commented out the other function call in main)

As you can see the core of the update to the register is the same (and + orr) but the version using packed structs (`modify`) uses a pointless temporary stack value to stage the value.

This example is building for 32bit arm but you can see similar behaviour building for x86_64. It is also similarly poor codegen for 32bit registers (which is the size I'm actually dealing with). For now I'm working around this by using an improved version of `modify_mask` but the code for `modify` is much nicer really so it would be nice to be able to use that.

I'm totally new to Zig so sorry if I've missed something obvious here!

**Comment by LemonBoy** [comment] 2021-06-04 10:21
Duplicate of #4056.

**Comment by tcrs** [comment] 2021-06-04 16:24
I'm not sure this is a duplicate of #4056 - the stores used here are byte stores, which is correct in this case as it is a pointer to a `u8`. The pointer isn't to the packed struct type directly, a `@bitCast` is used to load/store the packed data. The issue I'm describing here is that the packed struct value is bounced through a stack location for seemingly no reason:

```
...
        strb    r1, [sp, #3]
        ldrb    r1, [sp, #3]
        strb    r1, [r0]
...
```
This also incurs extra overhead in the function prologue/epilogue to adjust the stack pointer.

**Comment by LemonBoy** [comment] 2021-06-04 17:34
I see. Values are often spilled on-stack at low optimization levels to let the debugger know where a given variable lives, compiling in release mode gets rid of most of the intermediate spills.

**Comment by SpexGuy** [comment] 2021-06-04 17:55
hmm this still seems like a problem though.  The extra spill persists even in ReleaseSmall and ReleaseFast modes, and means that from a performance standpoint, packed structs are not a suitable replacement for bitfields.  I think this issue needs further consideration.
https://godbolt.org/z/rvecorf7h

**Comment by tcrs** [comment] 2021-06-04 18:05
Oh sorry I forgot to say, those asm samples were from ReleaseSmall builds. ReleaseFast looks similar too.

**Comment by LemonBoy** [comment] 2021-06-04 18:07
Replace the bitcast with `p.* = @ptrCast(*u8, &old).*;`.

**Comment by LemonBoy** [comment] 2021-06-04 18:17
Long story short, it has nothing to do with packed structures. The `bitcast` offers a "forward" path `p -> old -> p` where the source and destination pointers are volatile thus stopping the SROA pass from eliding the on-stack local. Using a `ptrCast` breaks the pointer chain and lets the SROA do its job, you can see by yourself how the asm/llvm IR changes after removing the volatile specifier and/or the bitcast.

**Comment by tcrs** [comment] 2021-06-04 20:15
Oh I see. As you say replacing the `@bitCast` with the pointer casting does indeed make the generated assembly match the manual bit twiddly version. Thanks!

Might be worth some words in the documentation, although I'm not sure exactly what it would say...

**Comment by Vexu** [comment] 2023-01-21 22:41
Fixed by the new integer backed packed struct semantics.

**Closed by Vexu** 2023-01-21 22:41 UTC
