### ISSUE TITLE
Stage2 compiler terminates unexpectedly with exit code 11

### ISSUE THREAD

**Issue by GeffDev** [ziglang/zig#13031] opened 2022-10-01 04:46 UTC
### Zig Version

0.10.0-dev.4198+5e0d8a435

### Steps to Reproduce

In order for it to terminate unexpectedly with exit code 11, you need to do this and compile it with Stage2:

```zig
const std = @import("std");

var allocatorBuffer: [1000]u8 = undefined;
var fba = std.heap.FixedBufferAllocator.init(&allocatorBuffer);
const allocator = fba.allocator();

const ConfigItem = struct {
    section: [0x40]u8,
    hasSection: bool = false,
    key: [0x100]u8,
    value: [0x100]u8,
};

var items = std.ArrayList(ConfigItem).init(allocatorBuffer);

pub fn main() !void {
    var item: ConfigItem = std.mem.zeroes(ConfigItem);
    items.append(item);
}
```

### Expected Behavior

As I didn't pass an allocator into `init()`, I expected it to give me an error telling me what I did wrong. It gives me a useful error with `-fstage1`:

```
./src/main.zig:14:44: error: expected type 'std.mem.Allocator', found '[1000]u8'
var items = std.ArrayList(ConfigItem).init(allocatorBuffer);
```

### Actual Behavior

When compiling the code with Stage2, it terminates unexpectedly, and says that the build command failed with exit code 11.

**Comment by jacobly0** [comment] 2022-10-01 06:27
```
thread 26253 panic: incorrect alignment
Analyzing /home/jacob/Source/zig/lib/std/array_list.zig: array_list.zig:ArrayListAligned(issue13031.ConfigItem,null).init
      %118 = dbg_block_begin())
      %119 = dbg_stmt(2, 13)
      %120 = ret_ptr() 
      %121 = decl_val("Self") 
      %122 = validate_struct_init_ty(%121) 
      %123 = coerce_result_ptr(%121, %120) 
      %124 = field_ptr_init(%123, "items") 
    > %125 = closure_get(%104) 
      %126 = array_type(@Zir.Inst.Ref.zero_usize, %125) 
      %127 = struct_init_empty(%126) 
      %128 = ref(%127) 
      %129 = store_node(%124, %128) 
      %130 = field_ptr_init(%123, "capacity") 
      %131 = store_node(%130, @Zir.Inst.Ref.zero) 
      %132 = field_ptr_init(%123, "allocator") 
      %133 = store_node(%132, %115) 
      %134 = validate_struct_init({
        %124 = field_ptr_init(%123, "items") 
        %130 = field_ptr_init(%123, "capacity") 
        %132 = field_ptr_init(%123, "allocator") 
      }) 
      %135 = dbg_stmt(2, 13)
      %137 = dbg_block_end())
      %136 = ret_load(%120) 
    For full context, use the command
      zig ast-check -t /home/jacob/Source/zig/lib/std/array_list.zig


/home/jacob/Source/zig/lib/std/hash_map.zig:937:13: 0x129d0ae in header (zig)
            return @ptrCast(*Header, @ptrCast([*]Header, @alignCast(@alignOf(Header), self.metadata.?)) - 1);
            ^
/home/jacob/Source/zig/lib/std/hash_map.zig:951:31: 0x129cd1c in capacity (zig)
            return self.header().capacity;
                              ^
/home/jacob/Source/zig/lib/std/hash_map.zig:1137:39: 0x188c77b in getPtrAdapted__anon_220476 (zig)
            const mask = self.capacity() - 1;
                                      ^
/home/jacob/Source/zig/lib/std/hash_map.zig:1236:38: 0x161b426 in getPtrContext (zig)
            return self.getPtrAdapted(key, ctx);
                                     ^
/home/jacob/Source/zig/lib/std/hash_map.zig:1233:38: 0x13f7556 in getPtr (zig)
            return self.getPtrContext(key, undefined);
                                     ^
/home/jacob/Source/zig/src/Sema.zig:14016:34: 0x112789c in zirClosureGet (zig)
        if (scope.captures.getPtr(inst_data.inst)) |tv| {
                                 ^
/home/jacob/Source/zig/src/Sema.zig:728:68: 0xf52b4e in analyzeBodyInner (zig)
            .closure_get                  => try sema.zirClosureGet(block, inst),
                                                                   ^
/home/jacob/Source/zig/src/Sema.zig:611:30: 0xf50fe8 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/jacob/Source/zig/src/Module.zig:5593:21: 0xd9bc20 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/jacob/Source/zig/src/Module.zig:4291:40: 0xb8e698 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/jacob/Source/zig/src/Compilation.zig:3047:42: 0xb8cb53 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/jacob/Source/zig/src/Compilation.zig:2985:30: 0xa7ae0e in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/jacob/Source/zig/src/Compilation.zig:2325:31: 0xa776ad in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/jacob/Source/zig/src/main.zig:3376:20: 0xaa2776 in updateModule (zig)
    try comp.update();
                   ^
/home/jacob/Source/zig/src/main.zig:3061:17: 0x822c1f in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/jacob/Source/zig/src/main.zig:230:31: 0x7fc2f6 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/home/jacob/Source/zig/src/main.zig:174:20: 0x7fba00 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/jacob/Source/zig/lib/std/start.zig:578:37: 0x7fdf31 in main (zig)
            const result = root.main() catch |err| {
                                    ^
Aborted
```

**Comment by yujiri8** [comment] 2022-10-01 08:09
I replaced  the `header` method of HashMapUnmanaged with:
```zig
        fn header(self: *const Self) *Header {
            std.debug.print("{} {} {*}\n", .{ @alignOf(Header), @alignOf(@TypeOf(self.metadata.?)), self.metadata.? });
            return @ptrCast(*Header, @ptrCast([*]Header, @alignCast(@alignOf(Header), self.metadata.?)) - 1);
        }
```
And the output is saying the align of both types is 8, so I don't get why the align cast is even needed. But if I remove the align cast it says the cast increases alignment from 1 to 8.
(Compile is still running)

**Comment by DivergentClouds** [comment] 2022-10-01 08:09
I had a compiler failure with the same error code in zig-spork https://github.com/DivergentClouds/zig-spork/issues/1 someone fixed it as part of this PR https://github.com/DivergentClouds/zig-spork/pull/2 idk if this will help but i'm sharing in case it does

**Comment by yujiri8** [comment] 2022-10-01 08:17
Ah, ah, hit gold! Realized that I didn't need to build stage3 with this debug statement in there, which was taking forever because stage2 was hitting it billions of times during compilation. I could just use the stage2 binary to compile the test program.

And here's what I got:
```
8 8 std.hash_map.HashMapUnmanaged(u32,Zir.Inst.Ref,std.hash_map.AutoContext(u32),80).Metadata@7f4ca589f738
8 8 std.hash_map.HashMapUnmanaged(u32,Zir.Inst.Ref,std.hash_map.AutoContext(u32),80).Metadata@7f4ca589f738
8 8 std.hash_map.HashMapUnmanaged(u32,Zir.Inst.Ref,std.hash_map.AutoContext(u32),80).Metadata@7f4ca589f738
8 8 std.hash_map.HashMapUnmanaged(u32,TypedValue,std.hash_map.AutoContext(u32),80).Metadata@aaaaaaaaaaaaaaaa
thread 22635 panic: incorrect alignment
```
Undefined address.

**Comment by yujiri8** [comment] 2022-10-01 08:26
just realized that @jacobly0's stack trace seems to be from an older commit, as my `lib/std/hash_map.zig` has different code on some of those line numbers.

**Comment by yujiri8** [comment] 2022-10-01 08:27
My `getPtrAdapted` doesn't call `capacity`

**Comment by yujiri8** [comment] 2022-10-01 08:28
Ohhhh nevermind me, getIndex doesn't show up in the stack trace because it's inline, that's what I was confused about

**Comment by yujiri8** [comment] 2022-10-01 08:31
The stack trace shows `getIndex` being called with `ctx` as `undefined`, and that value seems to be used on line 1131: `const hash = ctx.hash(key);`. Could this be causing the problem?

**Comment by yujiri8** [comment] 2022-10-01 08:42
No I don't think that can be it, that only affects the `hash` variable. I'm looking at Sema.zig now

**Comment by yujiri8** [comment] 2022-10-01 09:33
Well, I think I'm out of steam here. The problem is `scope.captures` having an undefined metadata on line 14016 of Sema.zig, but I don't have enough knowledge to find out what's causing that

**Comment by Vexu** [comment] 2022-10-01 10:39
Related #12535 #12765 #12927

**Comment by Vexu** [comment] 2022-10-01 14:19
Actually just a duplicate of #12765

**Closed by Vexu** 2022-10-01 14:19 UTC
Labels: bug, stage2
