### ISSUE TITLE
Missing reference trace when using `-freference-trace`

### ISSUE THREAD

**Issue by siadat** [ziglang/zig#19281] opened 2024-03-13 01:51 UTC
### Zig Version

0.12.0-dev.3193+4ba4f94c9

### Steps to Reproduce and Observed Output

```
     1  const std = @import("std");
     2
     3  fn func() void {
     4      _ = std.mem.asBytes(4); // incorrect argument type
     5      _ = std.mem.asBytes("hello");
     6  }
     7
     8  pub fn main() void {
     9      func();
    10  }
    11
    12  test "testing" {
    13      func();
    14  }
```
```
~/src/misc/isolated-question $ zig test -freference-trace main.zig                                                                                           
/home/sina/src/zig/build/stage3/lib/zig/std/meta.zig:93:17: error: Expected pointer, optional, array or vector type, found 'comptime_int'
        else => @compileError("Expected pointer, optional, array or vector type, found '" ++ @typeName(T) ++ "'"),
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sina/src/zig/build/stage3/lib/zig/std/mem.zig:3846:40: note: called from here
    const size = @sizeOf(std.meta.Child(P));
                         ~~~~~~~~~~~~~~^~~
/home/sina/src/zig/build/stage3/lib/zig/std/mem.zig:3851:47: note: called from here
pub fn asBytes(ptr: anytype) AsBytesReturnType(@TypeOf(ptr)) {
                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
referenced by:
    test.testing: main.zig:13:5
```
```
~/src/misc/isolated-question $ zig run -freference-trace main.zig
/home/sina/src/zig/build/stage3/lib/zig/std/meta.zig:93:17: error: Expected pointer, optional, array or vector type, found 'comptime_int'
        else => @compileError("Expected pointer, optional, array or vector type, found '" ++ @typeName(T) ++ "'"),
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sina/src/zig/build/stage3/lib/zig/std/mem.zig:3846:40: note: called from here
    const size = @sizeOf(std.meta.Child(P));
                         ~~~~~~~~~~~~~~^~~
/home/sina/src/zig/build/stage3/lib/zig/std/mem.zig:3851:47: note: called from here
pub fn asBytes(ptr: anytype) AsBytesReturnType(@TypeOf(ptr)) {
                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
referenced by:
    main: main.zig:9:5
    callMain: /home/sina/src/zig/build/stage3/lib/zig/std/start.zig:501:17
    callMainWithArgs: /home/sina/src/zig/build/stage3/lib/zig/std/start.zig:469:12
    posixCallMainAndExit: /home/sina/src/zig/build/stage3/lib/zig/std/start.zig:425:17
    _start: /home/sina/src/zig/build/stage3/lib/zig/std/start.zig:338:40
```

### Expected Output

I expect line `main.zig:4` to be listed in the reference trace list.

**Comment by nektro** [comment] 2024-03-13 01:53
duplicate of https://github.com/ziglang/zig/issues/19116

**Closed** 2024-03-14 16:42 UTC
Labels: error message
