### ISSUE TITLE
embedded switch with multiple values crashed the compiler

### ISSUE THREAD

**Issue by ali5h** [ziglang/zig#11092] opened 2022-03-08 21:01 UTC
### Zig Version

0.10.0-dev.1185+404f5d617

### Steps to Reproduce

build this code 
```
const T = enum {
    value,
    pub fn fromStr(str: []const u8) T {
        switch (str.len) {
            1 => switch (str[0..1]) {
                "1", "2" => return .value,
                else => return .value,
            },
            2 => switch (str[0..2]) {
                "12", "13" => return .value,
                else => return .value,
            },
            else => return .value,
        }
    }
};

pub fn main() !void {
    _ = T.fromStr("12");
}
```

### Expected Behavior

code should build

### Actual Behavior

segmentation fault

**Comment by Vexu** [comment] 2022-03-08 21:17
Duplicate of #7357

Note that using a string literal in a switch would compare the pointer's value not the contents of the string.

**Closed by Vexu** 2022-03-08 21:17 UTC
Labels: bug

**Comment by ali5h** [comment] 2022-03-08 21:23
what is the right way then?

**Comment by ali5h** [comment] 2022-03-08 21:24
i don't think it is a duplicate, after removing any of the items in the internal switches the code compiles

**Comment by Vexu** [comment] 2022-03-08 21:26
You cannot switch on strings, use `std.mem.eql` instead.

**Comment by ali5h** [comment] 2022-03-08 21:51
this code with no issues
```
const std = @import("std");

const T = enum {
    one,
    two,
    none,
    pub fn fromStr(str: []const u8) T {
        switch (str.len) {
            1 => switch (str[0..1]) {
                "1" => return .one,
                else => return .none,
            },
            2 => switch (str[0..2]) {
                "12" => return .two,
                else => return .none,
            },
            else => return .none,
        }
    }
};

pub fn main() !void {
    _ = T.fromStr("12");
}

test "table" {
    try std.testing.expectEqual(T.fromStr("1"), T.one);
    try std.testing.expectEqual(T.fromStr("12"), T.two);
    try std.testing.expectEqual(T.fromStr("13"), T.none);
    try std.testing.expectEqual(T.fromStr("2"), T.none);
    try std.testing.expectEqual(T.fromStr("122"), T.none);
}
```

**Comment by ominitay** [comment] 2022-03-08 21:59
It's still incorrect code which doesn't do what you'll expect it to ;)
