### ISSUE TITLE
Compiler crash with boundedarray

### ISSUE THREAD

**Issue by Srekel** [ziglang/zig#11381] opened 2022-04-04 03:48 UTC
### Zig Version

0.10.0-dev.1462+b48d8cce5

### Steps to Reproduce

As minimal as I could get it:

```
const std = @import("std");

pub const Crash = struct {
    myfield: std.BoundedArray(u8, 16).init(0),
};

pub fn main() void {

    const crashtest = Crash{
        .myfield = ([_]u8{.{}} ** 16),
    };

    _ = crashtest;
}
```

I'm on Windows. Interestingly it doesn't crash when using zig build-exe src/main.zig, but does when I use zig.build and this build file.
```

const std = @import("std");
const Builder = std.build.Builder;

pub fn build(b: *Builder) void {
    const exe = b.addExecutable("ElvengroinLegacy", "src/main.zig");

    exe.setTarget(b.standardTargetOptions(.{}));
    exe.setBuildMode(b.standardReleaseOptions());

    exe.install();

    const run_cmd = exe.run();
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}

```

(Feel free to rename the issue to whatever the real problem is)

### Expected Behavior

NO CRASH!

(I know the code is wrong but would expect a compile error, not a crash :) )

### Actual Behavior

CRASH!

> ElvengroinLegacy...The following command exited with error code 5:
> E:\Programs\zig\zig.exe build-exe E:\Projects\elvengroin-legacy\src\main.zig --cache-dir E:\Projects\elvengroin-legacy\zig-cache --global-cache-dir C:\Users\Srekel\AppData\Local\zig --name ElvengroinLegacy --enable-cache 
> error: the following build command failed with exit code 5:
> E:\Projects\elvengroin-legacy\zig-cache\o\870c368d33ccbbc1f0717f11a8dc021e\build.exe E:\Programs\zig\zig.exe E:\Projects\elvengroin-legacy E:\Projects\elvengroin-legacy\zig-cache C:\Users\Srekel\AppData\Local\zig
> The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command zig build" terminated with exit code: 1.

**Comment by Vexu** [comment] 2024-03-28 10:10
Duplicate of #11615

**Closed by Vexu** 2024-03-28 10:10 UTC
Labels: bug, stage1
