### ISSUE TITLE
Tuple undefined when passed to a comptime generic parameter

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#3878] opened 2019-12-09 22:44 UTC
```zig
fn Foo(comptime args: var) void {}
// test "undefined" {
//     Foo(.{1});
// }

test "not undefined" {
    comptime Foo(.{1});
}

test "not undefined" {
    Foo(1);
}

fn Bar(args: var) void {}
test "not undefined" {
    Bar(.{1});
}

fn Baz(comptime args: [1]u32) void {}
test "not undefined" {
    Baz(.{1});
}

fn Qux(args: [1]u32) void {}
test "not undefined" {
    Qux(.{1});
}
```

**Comment by alexnask** [comment] 2020-03-04 01:00
This is fixed by https://github.com/ziglang/zig/pull/4610  
Unfortunately that PR also broke anonymous struct literal field redefinition errors.  

I will try to update it tomorrow.

**Comment by andrewrk** [comment] 2020-03-05 21:02
Solved by @alexnask in debcc79d56a40f77b92e243b4e344fc9385bd405

**Comment by andrewrk** [comment] 2020-04-05 21:09
I believe the fix was reverted due to causing a regression. I have a new fix for this with tests running locally.

**Closed** 2020-04-05 21:45 UTC
Labels: bug, stage1
