### ISSUE TITLE
Remove redundant type naming in nested arrays

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#3546] opened 2019-10-27 19:31 UTC
I propose to shorten the syntax associated with nested arrays - better explained by examples:

Current:
```
    const a = [2][2][3]u8{
        [2][3]u8{
            [3]u8{3, 2, 1},
            [3]u8{2, 6, 7},
        },
        [2][3]u8{
            [3]u8{3, 3, 1},
            [3]u8{2, 6, 7},
        },
    };
```

Proposed:
```
    const a = [2][2][3]u8{
        {
            {3, 2, 1},
            {2, 6, 7},
        },
        {
            {3, 3, 1},
            {2, 6, 7},
        },
    };
```

Related to https://github.com/ziglang/zig/issues/3545 - the zig compiler seems to be doing type inference and discarding what the user writes in array syntax in places anyway. 

Removing this writing where it is not necessary has an obvious benefit.

It is worth noting that go's syntax works like this.

**Comment by Sobeston** [comment] 2019-10-27 19:55
Something that may come with this proposal - allowing things like this `var a: [3]f32 = {3, 2.5, 1};`

**Comment by daurnimator** [comment] 2019-10-27 21:49
Duplicate of #685

**Closed by daurnimator** 2019-10-27 21:49 UTC
