### ISSUE TITLE
brew: --HEAD won’t install

### ISSUE THREAD

**Issue by ghoffart** [ziglang/zig#11938] opened 2022-06-26 20:50 UTC
### Zig Version

--HEAD

### Steps to Reproduce

user@Wintermute2 ~ % brew install zig --HEAD

### Expected Behavior

Functional Zig environment, installation pulls the required/matching LLVM version.

### Actual Behavior

user@Wintermute2 ~ % brew install zig --HEAD
==> Downloading https://ghcr.io/v2/homebrew/core/llvm/manifests/14.0.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:ec2fd8d43fcd0de5bfbffdf63d884
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:ec2fd8d43fc
######################################################################## 100.0%
==> Cloning https://github.com/ziglang/zig.git
Cloning into '/Users/user/Library/Caches/Homebrew/zig--git'...
Updating files: 100% (15472/15472), done.
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Installing dependencies for zig: llvm
==> Installing zig dependency: llvm
==> Pouring llvm--14.0.5.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/llvm/14.0.5: 5,851 files, 983.5MB
==> Installing zig --HEAD
==> cmake . -DZIG_STATIC_LLVM=ON
Last 15 lines from /Users/user/Library/Logs/Homebrew/zig/01.cmake:
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.10.0-dev.2751+08459ff1c
CMake Error at cmake/Findllvm.cmake:101 (message):
  expected LLVM 13.x but found 14.0.5 using
  /opt/homebrew/opt/llvm/bin/llvm-config
Call Stack (most recent call first):
  CMakeLists.txt:107 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/zig-20220626-73388-sllmln/CMakeFiles/CMakeOutput.log".

**Comment by leecannon** [comment] 2022-06-26 21:30
This is caused by homebrew updating to llvm 14 before zig master has been updated and the brew doesnt specify an llvm version.
As a workaround `brew edit zig` and change the depends_on "llvm" line to depends_on "llvm@13".

**Comment by ghoffart** [comment] 2022-06-26 21:33
Worked, thanks!

**Comment by andrewrk** [comment] 2022-06-28 04:23
Duplicate of  #11274

**Comment by nektro** [comment] 2022-06-28 06:32
filed fix here https://github.com/Homebrew/homebrew-core/pull/104496

**Comment by nektro** [comment] 2022-07-06 23:08
downstream issue now closed

**Closed** 2022-07-07 01:56 UTC
Labels: question, downstream
