### ISSUE TITLE
Bad type inference for struct pointers

### ISSUE THREAD

**Issue by recombinant** [ziglang/zig#13451] opened 2022-11-05 11:44 UTC
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() void {
    handler(S, &s);
}

const S = struct {
    // variable: i32 = 0,

    fn callback(_: *S) void {}
};

var s = S{};

fn handler(comptime T: type, t: *T) void {
    t.callback();
}
```

```
$ zig run repro.zig
repro.zig:2:16: error: expected type '*repro.S', found '*const repro.S'
    handler(S, &s);
               ^~
repro.zig:2:16: note: cast discards const qualifier
referenced by:
    callMain: C:\ProgramData\chocolatey\lib\zig\tools\zig-windows-x86_64-0.10.0\lib\std\start.zig:596:17
    initEventLoopAndCallMain: C:\ProgramData\chocolatey\lib\zig\tools\zig-windows-x86_64-0.10.0\lib\std\start.zig:540:51
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

Uncomment `variable` in `struct S` and the code compiles and runs as expected. Possibly related to [#13414](https://github.com/ziglang/zig/issues/13414) or [#13438](https://github.com/ziglang/zig/issues/13438)?

The immediate workaround for callbacks is to put a dummy **variable** in the struct (if there are no **variables** already).

**Comment by Vexu** [comment] 2022-11-05 12:09
Duplicate of  #12275

**Closed by Vexu** 2022-11-05 12:09 UTC
Labels: bug
